### PR TITLE
Change version numbering approach to YY.N

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - OK, so per our previous discussions, we seem to have landed on an Ubuntu-style version numbering, with 2 digit year and zero padded month.  This approach will allow us to always have official YY.03 and YY.09 releases each year, and then if we do an interim release of any kind, they will just be the release month, or maybe a YY.03.1 or something.  Anyway, this PR updates all the usual version changes.  
 - I tucked in a small change to the `change_version` script so that it will automatically convert epJSON files along with all the IDFs and IMFs.

I believe the version number was all settled previously, but if there is any final discussion then we can have it here on the PR.  The way it is now the version number for the March release is 22.03.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar @JasonGlazer 
I made a package of this on Windows.
1. Example files run fine and the EnergyPlus version stamp looks correct.
2. EP-Launch (classic) displays the correct version number but if you try to transition a 9.6 file from EP-Launch it says "Transition utility file not found"
3. IDFVersionUpdater thinks 9.6 is the latest version, so it won't transition.
4. Running Transition-V9-6-0-to-V22-03-0.exe directly works, but the new version object is missing the minor version `Version,22.;`

**Comment by mjwitte** [comment]
@Myoldmopar Here's the issue with the new version number in the idf. In  DataVCompareGlobals.f90 `CHARACTER(len=3) :: sVersionNum=''`.
There's a possibility that changing the size of this could break older transitions, because there's no `TRIM()` when the new Version object gets written.

**Comment by nealkruis** [comment]
I don't know if I care so much, but I thought we had settled on YY.N where N is the number of release for that year. So, with our current schedule, there would always be a "1" for the spring and a "2" for the fall.

**Comment by Myoldmopar** [comment]
I was hoping to keep the "twice a year main releases" consistent each year, which is what led me to do year/month.  That way if we do a release in between, it won't affect the suffix on the main releases.  If we did 1, 2, 3, then some years the main releases would be 1 and 2, and other years it would be 1 and 3.  That's the only driving reason I have for it.  I'm still open to suggestion, but we do need to lock it down right away so we can move forward on this.

**Comment by bonnema** [comment]
For the near term, I think a YY.MM.X is better. A YY.X wouldn't be a great idea, given the IDD will probably only change twice a year (like you don't want to redo transition for a bug fix).

In the long term (with more agile releases, transition, versioning, etc.) a YY.X version may be more appropriate.

**Comment by nealkruis** [comment]
I had always imagined that YY.N would also allow YY.N.X for bug-fix releases.

**Comment by bonnema** [comment]
:grin: in that case it probably doesn't matter either way (e.g. there will only be a .1 or .2 minor version per year).

**Comment by nealkruis** [comment]
Yeah, my only thought is that it might be more confusing if a major release somehow slips into April or October.

**Comment by bonnema** [comment]
Never! :grinning: I am indifferent now.

**Comment by nealkruis** [comment]
Final thought: YYYY.N.X might be more intuitive than a jump from 9.6 to 22.1. Again, I don't feel strongly but maybe I have a slight preference for 2022.1 so that it a more explicit departure from the old numbering scheme.

**Comment by Myoldmopar** [comment]
I'm OK with the patch number being used and going with .1 and .2.  And actually, I'd be OK with the 2 digit year.  Unless someone wants to re-convince me of my previous feeling, then I'll proceed with tweaking this branch to 22.1.  Please wrap up discussion tomorrow though so I can get to work on it.

**Comment by JasonGlazer** [comment]
YYYY.MM or YY.MM are my preference. To me, it is logical to have a month and year. Lets do the full Ubuntu (version numbering)!

**Comment by Myoldmopar** [comment]
Alright, after our discussion on the call, we will go with the YY.V.P approach, where:
- YY is the two digit year (I know, what happens in 2122!?!? Right, @mjwitte?
- V is the release number for that year, which will always be 1 or 2 until we really make drastic release changes
- P is the patch number which will always be 0 for the major releases, but could be 1 if we make a patch version
As fond as I am of the Ubuntu numbering, I think this way best sets us up for long-term version management, regardless of what we do.  And it seems the least drastic change for users (aside from the 10.0, 11.0, 12.0 alternative).  

I'm making these changes shortly and will push up the branch.  I'll try to investigate the issues identified by @mjwitte.  Thanks all for your input.

**Comment by Myoldmopar** [comment]
> @Myoldmopar @JasonGlazer I made a package of this on Windows.
> 4. Running Transition-V9-6-0-to-V22-03-0.exe directly works, but the new version object is missing the minor version `Version,22.;`

Got this one fixed by allowing a 4 digit version string just from 22.1 and beyond, it should not affect any version prior to this.

As for EPLaunch classic issue, do you think EPLaunch is using a 3 digit version?  I guess so...
- In the `transitionInputFile` subroutine, EPLaunch parses by number of characters: https://github.com/NREL/EnergyPlus/blob/00d968c57b48ff354fdc123d00e782e18842f1ba/src/EP-Launch/epl-ui.frm#L3248
- Same thing for the `getTransitionVersions` subroutine: https://github.com/NREL/EnergyPlus/blob/00d968c57b48ff354fdc123d00e782e18842f1ba/src/EP-Launch/epl-ui.frm#L5669
- The `convertVersionToNumber` subroutine maps the version to a numeric version, which I don't think is a problem, but should be considered: https://github.com/NREL/EnergyPlus/blob/00d968c57b48ff354fdc123d00e782e18842f1ba/src/EP-Launch/epl-ui.frm#L5779
- The `GetIDDVersion` subroutine also checks a specific number of characters: https://github.com/NREL/EnergyPlus/blob/00d968c57b48ff354fdc123d00e782e18842f1ba/src/EP-Launch/epl-ui.frm#L4666

I can try to fix those, but I don't have a VB6 compiler handy so I wouldn't be able to test them out.  @JasonGlazer would you be able to address them?  Or would you be able to test if I tried to fix them?

**Comment by JasonGlazer** [comment]
@Myoldmopar I can either fix them or check your fixes. If you want me to fix them, maybe open a new issue and point it to me.

**Comment by Myoldmopar** [comment]
No ERR diffs, that is the standard indicator that everything is fine with the version changes.  @JasonGlazer I'll open a ticket pointing back to the comment above so that we can address the EPLaunch changes.  I'd like to get the changes into this branch or at least into `develop` before this goes in, otherwise EPLaunch will have issues for developers.

**Comment by JasonGlazer** [comment]
I just addressed #9186 with #9192 so the EP-Launch classic support for two digit version numbers should be done as soon at as that clears CI. @Myoldmopar and @mjwitte this would benefit from additional testing. Most of the code was related to detecting versions in the IDD and IDF and transitioning files from old to new versions.

**Comment by Myoldmopar** [comment]
Pulled develop in, it should use the just-merged regression tool code and be all green on CI.  If so I'll merge this in to keep the momentum going.

**Comment by Myoldmopar** [comment]
ALL GREEN!  OK, merging this in.  We are now in a brand new, more meaningful, version number paradigm, everyone.  Enjoy!

**Pull request merged**
