### PR TITLE
ZoneHVAC:Baseboard:RadiantConvective:Water requesting flow at some times when scheduled off 

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #4962

CalcHWBaseboard() routine does not set the branch inlet node water mass flow rate to zero when the baseboard is off for any reason. 

Adding the following code resets the branch inlet was mass flow rate to zero when the baseboad is off ( e.g. during the summer design day).
WaterMassFlowRate = 0.0;
SetActuatedBranchFlowRate( WaterMassFlowRate, HWBaseboard( BaseboardNum ).WaterInletNode, HWBaseboard( BaseboardNum ).LoopNum, HWBaseboard( BaseboardNum ).LoopSideNum, HWBaseboard( BaseboardNum ).BranchNum, false );

Now the one of the defect files shows zero hot water flow rate for the entire duration of the summary design day.

https://github.com/NREL/EnergyPlus/issues/4962

### CODE REVIEW

**Comment by Nigusse** [comment]
CI machine runs all  green except only 7 example files show failed [here](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-04dd7e77fee2b8b11b7de6b5e9385641dc58e6bf-i386-Windows-7-VisualStudio-12.html).  But no details is provided why these files shown as failed.  These seven files run OK in my local machine.  These examples were not expected to fail because the code does not impact them. @Myoldmopar can you comment what the fail message mean? Could this be caused by other merges?

**Comment by mjwitte** [comment]
@Nigusse This branch is behind develop.  If you merge in the latest develop, that should clear the extra failures.

**Comment by Myoldmopar** [comment]
Yeah, @Nigusse, if you look on the ["BranchList"](https://github.com/NREL/EnergyPlus/branches/active), you'll see this branch is 35 commits behind develop, and 1 commit ahead.  If you pull develop into this branch, you will be 0 commits behind, 1 commit ahead, and CI will then only report related diffs.

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar Ok. Thanks.

**Comment by Nigusse** [comment]
Added unit test. The branch is also updated.  I expect the CI machine to run all green.

**Comment by Nigusse** [comment]
@Myoldmopar This PR is ready for review and merging into develop.  The CI machine run all came green.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Works a champ.  Defect file runs better now.  Pushing up a merged with develop version.  As long as it is clean, I'll merge this.

**Pull request merged**
