### PR TITLE
Fix build errors on clang16

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Allow building E+ with clang16. The issue is really boost 1.77.0 used in Kiva. Upgrading to 1.81.0 would solve these issues, but this is a temporary patch.

```shell
$ /opt/homebrew/opt/llvm/bin/clang++ --version
Homebrew clang version 16.0.1
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin

$ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@nealkruis this looks fairly minimal, and our CI is fully happy, so I'm good with it merging.  If you feel we should hold or you want to provide an alternative, let me know soon.  Thanks!

**Comment by nealkruis** [comment]
@Myoldmopar, I think this is fine for now. I hope to do a larger update to Kiva for this release, but that shouldn't hold this up.

**Comment by Myoldmopar** [comment]
Awesome, thanks!

**Comment by Myoldmopar** [comment]
Tested locally and it seems all happy, merging.  Thanks @jmarrec

**Pull request merged**
