### PR TITLE
Prettify IDFs

### PR DESCRIPTION
**Pull request by mitchute**
Ran transition with makingPretty enabled on the IDFs. This is the result. This cleans up field names, formatting, etc.

### CODE REVIEW

**Comment by mjwitte** [comment]
@mitchute Thanks.  This _should_ be no diffs.  Interesting that min-fields filled out a bunch of VAV terminal units with some additional blank fields at the end.  Also, we need to be sure to change the `MakingPretty=.true.` lines back to false before this gets merged.

**Comment by mitchute** [comment]
@mjwitte That should bring `makingPretty = .false.` back.

**Comment by mjwitte** [comment]
@mitchute This [comment](https://github.com/NREL/EnergyPlus/pull/5245#issuecomment-145610764) in #5245 explains the original justification for having the blanket comment that doesn't necessarily need to change with every release.

**Comment by mitchute** [comment]
OK. Works for me. The way it is worded looks like we can leave it.

**Review by mjwitte — APPROVED** [review]
@Myoldmopar This is good to go anytime.  I'll hold on the merge to avoid clouding other pull requests that are ready.

**Comment by Myoldmopar** [comment]
The Version is also a `\unique-object`, so if someone imports the whole dataset with, for example, `EP Macro`, it will get two version IDs, and I _think_ E+ will balk at that.

**Comment by mjwitte** [comment]
@mitchute Didn't notice until now that merging #5859 caused conflicts in this branch.

**Comment by mjwitte** [comment]
Or it might have been a different merge.

**Comment by mitchute** [comment]
@mjwitte The issue was in `RadLoTempCFloHeatCool_AddedAutosizing.idf`. Only numbers had changed so I accepted the `develop` values.

**Comment by mjwitte** [comment]
Merging this one - may cause conflicts with other pull requests that have test idf file changes.

**Pull request merged**
