### PR TITLE
Implement an Ice Rink model in EnergyPlus

### PR DESCRIPTION
**Pull request by punyasloka06**
Pull request overview
---------------------
New feature proposal to implement Ice Rink model in EnergyPlus. The model is based on the work of Mun and Krarti, “An Ice Rink Floor Thermal Model Suitable for Whole-Building Energy Simulation Analysis.”
The model proposed in this feature has two algorithms just like the low-temperature radiant system model already present in EnergyPlus. Although there are a couple of differences between the two models like the working temperature of the refrigerants used, control strategies used etc. which need to be addressed so as to implement the new feature.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@punyasloka06 thanks for posting this.   I just renamed the pull request to request the ultimate intent.  Could you add a couple sentences to the body of the PR above to better reflect the new implementation?

**Comment by JasonGlazer** [comment]
@punyasloka06 thank you for putting together the new feature proposal. I am finding it difficult to know exactly what is being proposed due to the extensive use of referencing other documents which I don't have access to. Could you possibly include or summarize the relevant portions of these other documents? Also, I understand that humidity control is often an issue with ice rinks, is anything special needed for this? Does the impact of regularly resurfacing the ice require anything specific in the model?

**Comment by punyasloka06** [comment]
Thank you @Myoldmopar and @JasonGlazer for your review. I will add more lines to clearly describe what is being implemented and summarise the relevant parts of the referenced document. I will upload the revised document asap.

**Comment by punyasloka06** [comment]
Hello, @Myoldmopar @JasonGlazer just updated the NFP.

**Comment by mjwitte** [comment]
@punyasloka06 The concept will be useful, but before you get too far in coding, we need a proposed input design. Some questions/comments:
1. Will this use `Construction:InternalSource` to interface with the surface heat transfer? If yes, then the area of the surface or sub-surface could be used as the rink size.
2. `SwimmingPool:Indoor` is also a similar object which uses a different method to connect into the surface heat transfer
3. Will this use the existing refrigeration system components to serve the rink, or will the refrigeration system be a separate dedicated model?

**Comment by nrel-bot-3** [comment]
@punyasloka06 @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I was reviewing this offline while flying, so my apologies that these notes are not more integrated with the changes themselves.  I can refine if needed:

- Feature will incorporate refrigerants - how?
- Brine outlet temp control
	- Time step is used a bit loose - is this operating on the hvac or zone time step?
	- Step 2A: Brine pumps stay on?
	- How much exposed brine piping is typical?  Consider insulation?
	- Step 2B: Required flow rate?  Presumably a mcpdt calc in here
	- Are 3A and 3B really important to separate?  Seems like it's just a
	calculation of mcpdt with a followup m_dot_max check
- Ice surface temp control
	- Step 2B: how are you calculating maximum heat flux available?
	- It does handle melting, right?
- A lot of arenas are used for hockey and other activities, could consider something like switchable construction
- Control statement at the end - if this is at the hvac time step level I can't imagine a lot of iteration is warranted to control the rink temperature.  If it is at the HVAC time step, it still may not be warranted.  Just take what the zone gives it, make a decision, and move on.

**Comment by punyasloka06** [comment]
Hey Edwin, 

- The feature will use brine ( Ethylene Glycol) in the secondary loop that forms the low-temperature radiant system embedded in the floor. I am still trying to figure out how to use fluids other than water in the low-temperature radiant system. I found similar fluids in the FluidPropertiesRefData.idf under FluidProperties:Concentration.

- Step 2A: The brine pump stays on while the refrigeration system is turned off. This means that the brine is still circulating in the piping although no heat rejection from the brine by the refrigeration system occurs. After looping through the embedded radiant system, the temperature of brine increases after each timestep( HVAC time step) and ultimately this triggers the refrigeration system to switch on. The reason to keep the brine pump on is to monitor the brine outlet temperature and make the decision to switch on or off the refrigeration system.

- Typically the piping length from the radiant system outlet till the chiller/refrigeration system inlet and from the chiller/refrigeration system outlet till the radiant system inlet is the part where the brine piping is exposed. This length of piping is insulated, although there is no specific data available as to how long this section will be.

- Yes, an mcpdt calculation is used to calculate the required mass flow rate. In this case, the relation between the brine inlet and outlet temperature, the brine flow rate and heat flux uses the equation:
Tb,out = Tb,in - (qsource / (m_dot.Cp)_brine)    -------------------------------------------- 1

qsource can be expressed as a function of the heat flux to the slab, the brine inlet temperature and the mass flow rate:
qsource = (Tb,in - C_k) / ( (C_l / A) + (1 / ε( (m_dot.Cp)_brine) ) )   -------------------------2

and required mass flow rate of brine can be obtained using the above two equations. 

- Yes, steps 3A and 3B are not separate steps but as you said are followed by an mcpdt calculation and m_dot_max check. The flowchart showing these two as separate steps will be changed.

- Ice Surface Temperature Control: Step 2B:  This method also modulates the brine flow rate to achieve the ice surface setpoint temp. The maximum heat flux is the heat flux obtained with the max brine mass flow rate and can be calculated using the eq 2 as shown above.

- Yes, this handles phase change situations.

**Comment by punyasloka06** [comment]
[NFP_icerink_v4.txt](https://github.com/NREL/EnergyPlus/files/3135418/NFP_icerink_v4.txt)

**Comment by nrel-bot-2b** [comment]
@punyasloka06 it has been 18 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@punyasloka06 New feature (I/O) freeze is in 2 weeks. Will this be ready soon for review or should I push the milestone to v9.3.0 (March 2020)?

**Comment by punyasloka06** [comment]
@mjwitte I do not think it will be ready in 2 weeks time for review. I will be very grateful if you can push it to v9.3.0.

**Comment by nrel-bot-3** [comment]
@punyasloka06 @lgentile it has been 29 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 8 days since this pull request was last updated.

**Comment by mjwitte** [comment]
What's the status of this pull request? It appears that current code activity is in #7536.  If I'm following correctly, please add the final version of the NFP to #7536 and close this PR.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@punyasloka06 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@punyasloka06 it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
It looks like #7536 is slightly more recent than this one.  I'm going to close this one.  @punyasloka06 feel free to reopen a PR if this was actually the correct one.

**Pull request closed without merging**
