### PR TITLE
Enable cycling in continuous mode Fan:System in VRF FluidTCtrl model

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - A follow-up PR to #10341
This PR allows the continous-mode Fan:SystemModel (converted from old Fan:VariableVolume) object to cycle at the minimum fan power.

The following is a before-after comparison, produced using the `US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf` and `USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw`

image

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Is this still at a testing phase or is this ready to be reviewed?

**Comment by yujiex** [comment]
> Is this still at a testing phase or is this ready to be reviewed?

It's ready for review. Thanks, @Myoldmopar

**Comment by Myoldmopar** [comment]
OK, thanks @yujiex.  I'm open to thoughts and concerns on this one variable change @nigusse @rraustad @mjwitte @EnergyArchmage @dareumnam

**Comment by Myoldmopar** [comment]
CI just has the one diff, I think this is ready.  I'll hold off from merging while I await a handful of other CI results, but this will go in soon.

**Comment by dareumnam** [comment]
I’m reviewing the test diffs, and they appear minor. I think this PR looks good to go.

**Comment by dareumnam** [comment]
@Myoldmopar This is the PR that can be merged before this bug freeze.

**Comment by Myoldmopar** [comment]
OK, done here as well.  Thanks @yujiex and @dareumnam

**Comment by yujiex** [comment]
Thanks @Myoldmopar

**Pull request merged**
