### PR TITLE
Fix #7151 - Generator Availability Schedule is silently ignored for Photovoltaics

### LINKED ISSUE #7151: Generator Availability Schedule
Issue overview
--------------
`ElectricLoadCenter:Generators: Generator Availability Schedule Name`
The schedule that I input didn't work and my PVs works all the day

here is my code:

```
!- =========== ALL OBJECTS IN CLASS: SCHEDULE:COMPACT ===========

Schedule:Compact,

PV_ON,                   !- Name
Any,                     !- Schedule Type Limits Name
Through: 12/31,          !- Field 1
For: AllDays,            !- Field 2
Until: 11:00,            !- Field 3
0.0,                     !- Field 4
Until: 15:00,            !- Field 5
1.0,                     !- Field 6
Until: 24:00,            !- Field 7
0.0;                     !- Field 8
!- =========== ALL OBJECTS IN CLASS: GENERATOR:PVWATTS ===========

Generator:PVWatts,
PV-AA,                   !- Name
5,                       !- PVWatts Version
4160,                    !- DC System Capacity {W}
Standard,                !- Module Type
FixedOpenRack,           !- Array Type
0.14,                    !- System Losses
TiltAzimuth,             !- Array Geometry Type
25,                      !- Tilt Angle {deg}
204;                     !- Azimuth Angle {deg}
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:INVERTER:PVWATTS ===========

ElectricLoadCenter:Inverter:PVWatts,
Inverter1,               !- Name
1.022,                   !- DC to AC Size Ratio
0.981;                   !- Inverter Efficiency
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:GENERATORS ===========

ElectricLoadCenter:Generators,
PVList1,                 !- Name
PV-AA,                   !- Generator 1 Name
Generator:PVWatts,       !- Generator 1 Object Type
4160,                    !- Generator 1 Rated Electric Power Output {W}
PV_ON,                   !- Generator 1 Availability Schedule Name
;                        !- Generator 1 Rated Thermal toElectrical Power Ratio
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:DISTRIBUTION ===========

ElectricLoadCenter:Distribution,
ELC1,                    !- Name
PVList1,                 !- Generator List Name
Baseload,                !- Generator Operation Scheme Type
0,                       !- Generator Demand Limit Scheme Purchased Electric Demand Limit {W}
,                        !- Generator Track Schedule Name Scheme Schedule Name
,                        !- Generator Track Meter Scheme Meter Name
DirectCurrentWithInverter,  !- Electrical Buss Type
Inverter1;               !- Inverter Name
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.0.1
 - Helpdesk ticket number 13171

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7151: add a warning if generator has an availability schedule while type is Generator:PVWatts or Generator:Photovoltaic with performance type = Simple

Note: I started by adding a `DataPhotovoltaics::clear_state` function since it was missing.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
Well this could go with a warning to alert users of an avail schedule that is not used in certain cases, or the schedule could simply be ignored as appropriate and noted in the IO Reference. The user with the question was confused so I guess a warning is appropriate.

I'm confused as to the diff's shown in CI but they look innocuous and/or unrelated to these changes. So this could move forward for merge unless others have issue with these changes. @Myoldmopar @mjwitte ?

**Comment by jmarrec** [comment]
@rraustad I merged develop in, tests results make more sense now, only err diffs due to tne warning i added
Last one (gcc) should come in anytime soon.

**Comment by rraustad** [comment]
@mjwitte this looks ready. For the example files that now show the new warning that electric load center:generator will ignore it's availability schedule, should those example files be corrected (avail schedule removed)?

**Comment by jmarrec** [comment]
> @mjwitte this looks ready. For the example files that now show the new warning that electric load center:generator will ignore it's availability schedule, should those example files be corrected (avail schedule removed)?

@rraustad @mjwitte Done in https://github.com/NREL/EnergyPlus/pull/7394/commits/7b9a3ef6251207c9e71ddf879904018011f506de which can be reverted easily if you'd rather still see the warning (trying to be proactive given the milestones coming)

**Comment by Myoldmopar** [comment]
So there is still 1 file with ERR diffs due to the unused schedule warning.  It seems like the above comment was implying that the diffs should be fully gone.  Can you just confirm the intent?

**Review by Myoldmopar — APPROVED** [review]
This all looks great, and CI is happy except the one potential remaining cleanup.  This can merge as soon as that is resolved.

**Comment by Myoldmopar** [comment]
Merging this in.

**Comment by jmarrec** [comment]
@Myoldmopar thanks for removing the unused schedule, didn't see that one coming when I removed the availability schedules in elcd:generators

**Pull request merged**
