### PR TITLE
Refactoring Plant Component Models

### PR DESCRIPTION
**Pull request by Myoldmopar**
## Pull request overview

This PR brings in some of the plant components that were refactored at the Hackathon.  The components included currently are:
- Pipes (adiabatic, steam, indoor, outdoor, underground)
- Ground heat exchangers (vertical, pond, surface)
- Plant load profiles

There are many other branches waiting to get merged in over in the [fork](github.com/energy-plus/EnergyPlus), and I anticipate bringing those in, but I want to at least get _something_ in to get things moving.

For the current status of components, just check out the block in src/EnergyPlus/PlantLoopEquip.cc and see which components are still using dangling Sim**\* functions, and which ones are using the new simulate() virtual function.
### Things to do to wrap up the current list of components
- [x] Add virtual destructors
- [x] Re-add RunFlag as an argument to simulate()
- [x] Ensure override/virtual is applied to all overriding functions
- [x] Make sure to use const args in all the new functions where possible
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by Myoldmopar** [comment]
There are still definitely pieces to wrap up in this work:
- [ ] add `virtual` destructors
- [ ] factories should use `const` argments
- [ ] add `virtual` to all overridden functions
- [ ] update arguments to simulate() -- `RunFlag`...

**Comment by Myoldmopar** [comment]
@mjwitte @kbenne would one of you be interested in looking this over before I merge it?  I want to start dropping in more of the hackathon-refactored objects, but I want to get a good baseline into develop before going much farther.  If neither of you speak up, I'm happy to just do it myself after the last green result comes back.

**Comment by mjwitte** [comment]
@Myoldmopar I did a quick glance over it, but nothing thorough.  If I'm following correctly, and this PR is going in, then the top comment box needs to be replaced with a description of what this one does - list the specific components that have been refactored, summary of the approach.  And the checklist would move to a new PR?  And change the title of this one?

**Comment by mjwitte** [comment]
Also - we need to give the team a heads up that this requires VS2013 Update 5 or it won't build.  That's my understanding from @rraustad

**Comment by Myoldmopar** [comment]
This is building fine on the CI boxes with Update 4.  I am happy to declare a requirement, but it isn't Update 5.

**Comment by Myoldmopar** [comment]
We are working out some issues with the performance part of the dashboard, but I anticipate this being a net positive improvement on performance.

**Comment by Myoldmopar** [comment]
@rraustad @mjwitte Can you confirm the compiler requirement details?  As I mentioned, I was building this just fine with Update 4.  But maybe there is something that you added in one of the other plant components that required Update 5.  In which case, we'll nail that down at that point.  

Maybe @mbadams5 would have some random thoughts before this goes into develop...

**Comment by Myoldmopar** [comment]
Oh, and the performance dashboard is now working properly for external pull requests (bonus) and it shows a small, but positive, improvement in runtime for this branch.  I may run some local, annual, tests for fun, but that shouldn't hold this from going in.

**Comment by rraustad** [comment]
I upgraded from MSVS Premium 2013 Update 3 right to Update 5, so I can't comment on Update 4. The problem I had was with Amir_SolarCollectors branch. It compiled fine with 2013 Update 5 (and 2015). All of us here at FSEC are now at 2013 Update 5.

**Comment by mjwitte** [comment]
@Myoldmopar My VS2013 is still at Update 3.  I'll try to build this branch.

**Comment by Myoldmopar** [comment]
Great, thanks @mjwitte.  If it builds for you with Update 3, can you go ahead and merge this in?  I'll start working on bringing in the other branches, and if we get to a point where it appears we need to require a newer version of the compiler, so be it.

**Comment by mjwitte** [comment]
This branch builds and executes for Win64 release and debug in VS2013 Update 3.  Merging in 5 - 4 - 3 - 2 - 1 . . .

**Comment by Myoldmopar** [comment]
Yahoo! :tm: 

Thanks @mjwitte.

**Pull request merged**
