### PR TITLE
Add LCCusePriceEscalationDataSet2015 dataset

### PR DESCRIPTION
**Pull request by JasonGlazer**
Added the LCCusePriceEscalationDataSet2015.idf file to address #5227. This file is based on the 2015 update to NIST 135. This is for use with the LifeCycleCost:\* objects to include energy price escalation data based on the NIST projection.
- [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [X] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### CODE REVIEW

**Comment by mjwitte** [comment]
@JasonGlazer This dataset file should be added to [Datasets.unit.cc](https://github.com/NREL/EnergyPlus/blob/5177c051a0bce39b57bd3e1bcd7f10ae15d7b059/tst/EnergyPlus/unit/Datasets.unit.cc#L132-L145).
Also, does it make sense to keep adding new LCC datasets without removing older ones?  This gives us 6 files now for 2010-2015.

**Comment by JasonGlazer** [comment]
@mjwitte It probably makes sense to keep some of them since projects may be getting modeling done over several years but six is probably too many. What do you think?

**Comment by mjwitte** [comment]
5 is a nice number.  We could zip up old ones to post on energyplus.net

**Comment by JasonGlazer** [comment]
@mjwitte I removed one of the old LCC datasets files so that their are only five and added the latest to the unit test related to datasets. After the CI runs, this should be ready to review.

**Comment by mjwitte** [comment]
@Myoldmopar Does the installer script package every file that's in the Datasets folder, or do we need to modify a cmake file to add/remove specific file names?

**Comment by Myoldmopar** [comment]
Installer behaves and only does what it is told to do: https://github.com/NREL/EnergyPlus/blob/develop/cmake/Install.cmake#L67

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar I just updated Install.cmake.

**Pull request merged**
