### PR TITLE
Updating IDD and error handling for GHX:Vertical

### PR DESCRIPTION
**Pull request by mitchute**
Addresses #5203. 

Now catches wrong wrong values in the Num G-Func field and catches wrong number of inputs.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
So, @mmatts.  Unit test.  I can imagine this wouldn't be too hard if you use the EnergyPlusFixture.  You could, at a minimum, put invalid idf snippet that has the bad inputs we were encountering, and expect a failed process_idf or whatever the function is called.

**Comment by mitchute** [comment]
@Myoldmopar yeah, that should be easy enough. I will try to push something up tonight.

**Comment by EnergyArchmage** [comment]
I reviewed these changes, all seems good to go to me.

**Comment by Myoldmopar** [comment]
@mmatts Could you pull develop back into this branch one more time?

**Comment by mitchute** [comment]
@Myoldmopar I just pushed it up [here](4bddc8ff0e8de5680269e4cbc67938ec5898f4b5). I'm not sure why it is not showing up in this PR though.

I got hung up on the unit tests, but once that is resolved this should be ready.

**Comment by Myoldmopar** [comment]
OK, so it looks like the unit test works. I think you might want to say EXPECT_TRUE though since you are checking an erroneous condition.

**Comment by Myoldmopar** [comment]
@mmatts @mbadams5 Once #5259 is merged in, maybe you guys could coordinate to get this unit test working with the new structure so the dashboard will be all green again and happy and :grinning:.

**Comment by mitchute** [comment]
@mbadams5 A couple of unit testing questions for you:

For these unit tests I am passing bad idf objects in [here](https://github.com/NREL/EnergyPlus/blob/4bddc8ff0e8de5680269e4cbc67938ec5898f4b5/tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc#L262) and [here](https://github.com/NREL/EnergyPlus/blob/4bddc8ff0e8de5680269e4cbc67938ec5898f4b5/tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc#L356) and trying to test the error handling [here](https://github.com/NREL/EnergyPlus/blob/4bddc8ff0e8de5680269e4cbc67938ec5898f4b5/src/EnergyPlus/GroundHeatExchangers.cc#L1456-L1463). I keep getting stuck because the out of range idd error handling [here](https://github.com/NREL/EnergyPlus/blob/4bddc8ff0e8de5680269e4cbc67938ec5898f4b5/tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc#L423) is stopping it. I just pulled develop in and have tried all combinations of ASSERT/EXPECT TRUE/FALSE. Do you have any suggestions on what I should be using around the process_idf so I can continue on to test that block? Also, I did not see any examples in unit tests of where were are checking for a fatal error. Is it possible to "EXPECT_DEATH" for something like that, or do I need to work around it some other way?

**Comment by mbadams5** [comment]
@mmatts I added new functionality to suppress the assertions within process_idf() for this use case. Normally these assertions shouldn't be suppressed but in this case you know the IDF is bad. So pass `false` after your idf_snippet and it should pass now.

**Comment by mitchute** [comment]
@mbadams5 thanks, that works. As far as expecting a fatal error, is there a way to do that? If not, I will probably need to do a _little_ code work to make the `errorsFound` flag available.

**Comment by mbadams5** [comment]
@mmatts What do you mean "expecting a fatal error"? Like the function you are calling will call ShowFatalError or whatever it is called? Basically, if the function throws a Fatal Error then you need to wrap it in EXPECT_DEATH test because it will kill the whole unit test framework otherwise. Just be aware that you can only test that a function exits, aborts, or throws an exception when you use EXPECT_DEATH, nothing else.

If you are talking about something else then I need some more information.

**Comment by mitchute** [comment]
@mbadams5 yes, they eventually call ShowFatalError [here](https://github.com/NREL/EnergyPlus/blob/4bddc8ff0e8de5680269e4cbc67938ec5898f4b5/src/EnergyPlus/GroundHeatExchangers.cc#L1490).

So is `EXPECT_DEATH( GetGroundHeatExchangerInput(), "" );` something along the lines of what I'm looking for? Or, `EXPECT_EXIT( GetGroundHeatExchangerInput(), ::testing::ExitedWithCode( 1 ), "" );`?

**Comment by mitchute** [comment]
@Myoldmopar ready for review.

**Comment by mbadams5** [comment]
@mmatts `EXPECT_DEATH( GetGroundHeatExchangerInput(), "" );` is the same as `EXPECT_EXIT( GetGroundHeatExchangerInput(), ::testing::ExitedWithCode( 1 ), "" );` and in fact more. EXPECT_DEATH checks for any exit that is not EXIT_SUCCESS, which is usually 0 but is platform dependent.

Also you can still wrap the `process_idf()` in EXPECT_TRUE() since it will return true if there is a failure. It will just not assert within the function if you pass `false`.

**Comment by mitchute** [comment]
@mbadams5 thanks for the information. I added EXPECT_TRUE around process_idf.

**Comment by Myoldmopar** [comment]
Hmmm, not sure why the other CI boxes decided not to work on 1c8e038.  Maybe because of the underlying CI robustness improvements that were made?  Anyway, just to be super careful, @mmatts, can you merge develop -- one more time.  The changes look good, this will merge if CI is happy.

**Pull request merged**
