### PR TITLE
Replace Array1D with EPVector

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
This PR implements a replacement for the Array1D object. Building on previous PRs that streamlined the use of Array1D, this PR replaces Array1D with EPVector, an object that is currently a subclass off of std::vector. Because multidimensional arrays are used throughout the code, it is not possible to completely remove Array1D (and the related objects) until multidimensional arrays are addressed. It is anticipated that in the future, regular std::vectors will be used.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jasondegraw does this PR stay open with the EPVector class pulled into #8707?  Happy to leave it open, or try to reconcile any of it from conflicts, or whatever else, but I just didn't want to leave it open for no reason.  Thanks.

**Comment by Myoldmopar** [comment]
No response and I believe this is addressed by the other PR so closing this.  Obviously reopen if I'm mistaken.

**Comment by jasondegraw** [comment]
@Myoldmopar You may or may not be mistaken, but I have not had time to review. Reopening.

**Comment by nrel-bot-2** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by jasondegraw** [comment]
We did a lot of work here to move over to the EPVector class, and I'll make sure it's at least preserved elsewhere, but the branch itself is now too hopelessly conflicted to ever be merged.

**Pull request closed without merging**
