### PR TITLE
Preparing a few things for release

### PR DESCRIPTION
**Pull request by Myoldmopar**
Transition, IDD, packaging stuff

 - [x] Probably still a few more dataset files to be updated to 8.3
 - [x] Process idf, imf files for version 8.3

### CODE REVIEW

**Comment by kbenne** [comment]
@Myoldmopar  I'd like to build on this with some additional commits.  cool?

**Comment by Myoldmopar** [comment]
Cool

**Comment by Myoldmopar** [comment]
@kbenne I updated the DataSet files for 8.3.  I'll run the testfiles idfs and imfs through tomorrow to get them up to 8.3 as well.  I also need to chat about Transition.  We didn't do a report variable name change this cycle (right, @mjwitte?  I know you mentioned you had one waiting...)  Anyway, if we don't have that, we won't need to have an install command for a Report Variables... transition file. I'll also make sure the Transition source doesn't report any serious error if that file isn't found.

I'm going to be editing the main comment on this PR to keep my checklist.

**Comment by Myoldmopar** [comment]
Gah, on my end GitHub wouldn't render the files changed for this PR, unicorn-ing.  So I looked at the raw view and couldn't figure out what I did to change the whole IDD.  It was just that I had added the 8.2 idd to the repo...no worries...carry on.

**Comment by mjwitte** [comment]
Wouldn't it be easier to still have the report variable file? Will transition run ok if it just has the headers and no other rows? Then we don't need to add it back next time.

<div>-------- Original message --------</div><div>From: Edwin Lee <notifications@github.com> </div><div>Date:03/23/2015  10:31 PM  (GMT-06:00) </div><div>To: NREL/EnergyPlus <EnergyPlus@noreply.github.com> </div><div>Cc: "Michael J. Witte" <mjwitte@gard.com> </div><div>Subject: Re: [EnergyPlus] Preparing a few things for release (#4812) </div><div>
</div>@kbenne I updated the DataSet files for 8.3. I'll run the testfiles idfs and imfs through tomorrow to get them up to 8.3 as well. I also need to chat about Transition. We didn't do a report variable name change this cycle (right, @mjwitte? I know you mentioned you had one waiting...) Anyway, if we don't have that, we won't need to have an install command for a Report Variables... transition file. I'll also make sure the Transition source doesn't report any serious error if that file isn't found.

I'm going to be editing the main comment on this PR to keep my checklist.

**Comment by Myoldmopar** [comment]
Valid point, @mjwitte. It will run with an empty one. I'll rename it and
clean it out.

**Comment by kbenne** [comment]
@Myoldmopar i know we need a report variable changes file, but I'm going to merge to keep things moving.

**Comment by Myoldmopar** [comment]
Thanks @kbenne; that'll be great.

**Comment by Myoldmopar** [comment]
@kbenne I snuck in a fix to Transition so that it writes the correct version number now.  I also updated the report variables file over in BuildSupport.  This can freely go in anytime you want.

**Pull request merged**
