### PR TITLE
UnitarySystem missing supply air flow method causes error when coil has no flow rate

### PR DESCRIPTION
**Pull request by rraustad**
Added errors when AirloopHVAC:UnitarySystem has blanks for flow rate fields and the coil does not have a flow rate specified.  Addresses #4672

### CODE REVIEW

**Comment by rraustad** [comment]
This is too restrictive. For one, the cooling coil operated as expected so there should have only been one warning. Second, if the cooling coil had been autosized, then the heating coil could have been as well. There are many combinations of coils that do not require these inputs. The defect file has a DX cooling and electric heating coil. The electric heating coil does not have an air flow input field, which is the reason only the heating coil failed to operate. So I suggest relaxing the warning a bit which I will work on now. I suggest that if a coil does not have an air flow input, that the model use the other coils air flow input: 1) if there is a second coil, 2) if that coil has an air flow rate input field, and 3) if it is autosize (since we don't want unmet load if the air flow rate of the other coil is insufficient to meet the load for this coil).

**Comment by rraustad** [comment]
Added more logic to allow blank inputs when possible. Now there is only 1 warning message:

   *\* Severe  *\* AirLoopHVAC:UnitarySystem = AIR LOOP UNITARY HEATCOOL
   *\*   ~~~   *\* Input for Heating Supply Air Flow Rate Method is blank and relates to COIL:HEATING:ELECTRIC = AIR LOOP UNITARY HEATCOOLELECTRIC HEATING COIL
   *\*   ~~~   *\* Blank field not allowed for this coil type when cooling coil air flow rate is not autosized.

Note that the last line, had the cooling coil not been present, would have been:
*\*   ~~~   *\* Blank field not allowed for this type of heating coil.

**Comment by rraustad** [comment]
@kbenne @mbadams5 this branch unit test shows a warning issued. Please show me how to read that err stream in the unit test and EXPECT_TRUE that it exists. I want to use this in many places.

**Comment by mbadams5** [comment]
@rraustad I don't see a unit test warning in the latest CI results...

**Comment by rraustad** [comment]
Not in the CI results, the local PC err file shows the warning message I posted above. If you pull this branch and run it (up to the unit test after this one, since someone is deleting the error file right before SQLite tests) and look at the err file you'll see this warning. I want to test that string, or portion thereof, within a unit test.

*\* Severe *\* AirLoopHVAC:UnitarySystem = AIR LOOP UNITARY HEATCOOL
*\* ~~~ *\* Input for Heating Supply Air Flow Rate Method is blank and relates to COIL:HEATING:ELECTRIC = AIR LOOP UNITARY HEATCOOLELECTRIC HEATING COIL
*\* ~~~ *\* Blank field not allowed for this coil type when cooling coil air flow rate is not autosized.

**Comment by mbadams5** [comment]
Well, currently, there is no way to compare against that string in the error file. You can query against the error table in the SQLite output. See [this comment](https://github.com/NREL/EnergyPlus/pull/5150#issuecomment-137792623) and subsequent discussion on why we can't compare against the error file yet.

**Comment by rraustad** [comment]
OK, I see the extra effort in getting this to work. But from my simple sense, I see a pointer to a string, so why can't I see that string? No real need to answer, I just wanted to ask the original question. I do eventually want that capability (but could never do it myself).

**Comment by mjwitte** [comment]
In v8.2, the heating coil did not run, but in v8.3 it does, and in current develop it runs.  Both the heating and cooling airflows autosize to 0.76927, but when I add SupplyAirFlowRate and autosize to both heating and cooling airflows, they autosize to 0.4555.  So, I guess this change is needed.  But why is there only a heating flow error and not one for the cooling flow also with the defect file that has neither one specified?

**Comment by rraustad** [comment]
Because the defect file cooling coil has an air flow input field in the DX coil object where the unitary system mined the data. The heating coil does not have an air flow input field so the unitary system needs the user to tell the program how to size the heating flow.

```
Coil:Cooling:DX:TwoSpeed,
  Air Loop Unitary HeatCoolDX Cooling Coil TwoSpeed,  !- Name
  0.769274,                !- High Speed Rated Air Flow Rate {m3/s}

Coil:Heating:Electric,
  Air Loop Unitary HeatCoolElectric Heating Coil,  !- Name
  AlwaysOn,                !- Availability Schedule Name
  1.00,                    !- Efficiency
  10000,                   !- Nominal Capacity {W}
  Air Loop Unitary HeatCoolDX Cooling Coil Outlet,  !- Air Inlet Node Name
  Air Loop Supply Side Outlet 1;  !- Air Outlet Node Name
```

**Comment by mjwitte** [comment]
Didn't know it would take the coil flow rate.

**Comment by mjwitte** [comment]
So, made a case with the heating flow autosized in the unitary system and left the cooling flow fields blank.  Is this the result you expect?  The branch flow is smaller than the system flow.  

```
 Component Sizing Information, Branch, AIR LOOP UNITARY HEATCOOL MAIN BRANCH, Maximum Flow Rate [m3/s], 0.45555
 Component Sizing Information, AirLoopHVAC:UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Supply Air Flow Rate [m3/s], 0.45555
 Component Sizing Information, AirLoopHVAC:UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Heating Supply Air Flow Rate [m3/s], 0.76927
 Component Sizing Information, AirLoopHVAC:UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Cooling Supply Air Flow Rate [m3/s], 0.76927
 Component Sizing Information, AirLoopHVAC:UnitarySystem, AIR LOOP UNITARY HEATCOOL, User-Specified Cooling Supply Air Flow Rate [m3/s], 0.76927
 Component Sizing Information, AirLoopHVAC:UnitarySystem, AIR LOOP UNITARY HEATCOOL, User-Specified No Load Supply Air Flow Rate [m3/s], 0.00000
```

**Comment by mjwitte** [comment]
@rraustad If sizing mentioned above is ok, I can merge this in. I'm hoping to get rid of branch flow rates anyway at some point.

**Comment by rraustad** [comment]
Design Size Supply Air Flow Rate is the fan flow rate and the fan was not autosized. I would expect the fan flow to be the same as the cooling coil air flow rate. I think I see why this happened.

**Comment by rraustad** [comment]
This is what I would expect:

```
Branch, AIR LOOP UNITARY HEATCOOL MAIN BRANCH, Maximum Flow Rate [m3/s], 0.44993        
UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Supply Air Flow Rate [m3/s], 0.44993
UnitarySystem, AIR LOOP UNITARY HEATCOOL, User-Specified Supply Air Flow Rate [m3/s], 0.76927
UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Heating Supply Air Flow Rate [m3/s], 0.76927
UnitarySystem, AIR LOOP UNITARY HEATCOOL, Design Size Cooling Supply Air Flow Rate [m3/s], 0.76927
UnitarySystem, AIR LOOP UNITARY HEATCOOL, User-Specified Cooling Supply Air Flow Rate [m3/s], 0.76927
UnitarySystem, AIR LOOP UNITARY HEATCOOL, User-Specified No Load Supply Air Flow Rate [m3/s], 0.00000
```

**Pull request merged**
