### PR TITLE
75127368 dcfsec Data Center HVAC

### PR DESCRIPTION
**Pull request by Myoldmopar**
Creating a pull request to start conversation to get this merged.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar @lgu1234 What is the status on this pull request?

**Comment by Myoldmopar** [comment]
It's on my review checklist and I should be able to make a pass today.

**Comment by kbenne** [comment]
https://www.pivotaltracker.com/story/show/75127862

**Comment by Myoldmopar** [comment]
@kbenne Assigning myself to this since there are transition changes.  Feel free to take another one of mine :wink:

@Nigusse Do you have the transition rules written out for this PR?  It looks like the 2-speed DX coil and the research special evap cooler went through some pretty drastic changes.  I'll provide further comments as I review it.

**Comment by Nigusse** [comment]
@Myoldmopar Yes, transition rules were provided at the time of final code commit. If you cannot find it I will forward it to you.

**Comment by Myoldmopar** [comment]
Thanks, I see it attached to the Pivotal ticket.

**Comment by Myoldmopar** [comment]
@Nigusse 

 - Looking at [EvaporativeCoolers::EvapCoolerRDDOperatingMode](https://github.com/NREL/EnergyPlus/pull/4624/files?diff=split#diff-6930deb07926eae294737f74d13eb5cdR110).  Is there any reason why this was made as a "global" variable and not just a variable on the evap cooler data structure?
 - There are a few formatting/indentation issues that I'll clean up as I go along
 - It's nice that you broke out the functionality into small utility functions.  This will make it easy to test.  I'll try to rough out some unit tests but will want your input on them as well.
 - For format statements, oddly enough we _don't_ want const, per an odd performance boost.  Now, in this case, it is not getting called over and over so it likely won't make **any** difference, but still good to employ best practice everywhere.  I'll clean those up as well.
 - Economizer is [misspelled](https://github.com/NREL/EnergyPlus/pull/4624/files?diff=split#diff-179b5639d0e757ab896ebb87ac6d1566).  I'll rename the file and update the CMakeLists.txt file accordingly.
 - I'll work on the transition changes as well so those changes will come.

**Comment by Myoldmopar** [comment]
@DeadParrot As the resident FArray expert, could you comment on[this](https://github.com/NREL/EnergyPlus/pull/4624/files?diff=split#diff-6930deb07926eae294737f74d13eb5cdR2201)?  I believe this needed to be called Optional before because the regula falsi function had it as optional.  But IIRC you changed that so it is non-optional, and therefore this should also be non-optional.  What is the best signature here for performance?

**Comment by Myoldmopar** [comment]
@Nigusse Running the 1ZoneDataCenterCRAC... file results in a pretty big error file.  Need to clean up at least the first one... It could have been due to a bad transition, but still need to figure out what went wrong.

```
Program Version,EnergyPlus, Version 8.2.9-beef31cf99, YMD=2015.02.23 09:08,IDD_Version 8.2.9
   ** Severe  ** SetupZoneInternalGain: developer error, trapped inconsistent internal gains object types sent to SetupZoneInternalGain
   **   ~~~   ** Object type character = ElectricEquipment:ITE:AirCooled
   **   ~~~   ** Type of Num object name = ELECTRICEQUIPMENT
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed="MAIN COOLING COIL 1" - Air volume flow rate per watt of rated total cooling capacity is out of range at 2.915E-006 m3/s/W.
   **   ~~~   **  Environment=DENVER CENTENNIAL ANN CLG 1% CONDNS DB=>MWB, at Simulation time=07/21 00:00 - 00:10
   **   ~~~   ** Expected range for VolumeFlowPerRatedTotalCapacity=[2.684E-005--6.713E-005]
   **   ~~~   ** Possible causes include inconsistent air flow rates in system components,
   **   ~~~   ** or variable air volume [VAV] system using incorrect coil type.
   ** Warning ** Enthalpy out of range (PsyTsatFnHPb)
   **   ~~~   **  Routine=CalcDoe2DXCoil, Environment=DENVER CENTENNIAL ANN CLG 1% CONDNS DB=>MWB, at Simulation time=07/21 00:00 - 00:10
   **   ~~~   **  Enthalpy=-272521.42802 Pressure= 81560.00
   **   ~~~   **  Initial Resultant Temperature= -59.98
   ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)
   **   ~~~   **  Routine=PsyWFnTdbTwbPb, Environment=DENVER CENTENNIAL ANN CLG 1% CONDNS DB=>MWB, at Simulation time=07/21 00:00 - 00:10
   **   ~~~   **  Input Temperature=-288.26
   ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed "MAIN COOLING COIL 1" - Full load outlet air dry-bulb temperature < 2C. This indicates the possibility of coil frost/freeze. Outlet temperature = -289.01 C.
   **   ~~~   **  ...Occurrence info = DENVER CENTENNIAL ANN CLG 1% CONDNS DB=>MWB, 07/21 00:00 - 00:10
   **   ~~~   ** ... Possible reasons for low outlet air dry-bulb temperatures are: This DX coil
   **   ~~~   **    1) may have a low inlet air dry-bulb temperature. Inlet air temperature = 25.729 C.
   **   ~~~   **    2) may have a low air flow rate per watt of cooling capacity. Check inputs.
   **   ~~~   **    3) is used as part of a HX assisted cooling coil which uses a high sensible effectiveness. Check inputs.
   ************* Simulation Error Summary *************
   ** Warning ** The following Report Variables were requested but not generated
   **   ~~~   ** because IDF did not contain these elements or misspelled variable name -- check .rdd file
   ************* Key=*, VarName=ZONE ELECTRIC EQUIPMENT TOTAL HEATING RATE, Frequency=Timestep
   ************* There are 1 unused schedules in input.
   ************* Use Output:Diagnostics,DisplayUnusedSchedules; to see them.
   *************
   ************* ===== Recurring Error Summary =====
   ************* The following recurring error messages occurred.
   *************
   *************  ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed="MAIN COOLING COIL 1" - Air volume flow rate per watt of rated total cooling capacity is out of range error continues...
   *************  **   ~~~   **   This error occurred 288 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=2.930217E-006  Min=2.906744E-006
   *************
   *************  ** Warning ** Enthalpy out of range (PsyTsatFnHPb)
   *************  **   ~~~   **   This error occurred 2736 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=-233001.051263 J/kg  Min=-279169.316969 J/kg
   *************
   *************  ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)
   *************  **   ~~~   **   This error occurred 288 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=-249.060074 C  Min=-295.621658 C
   *************
   *************  ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed="MAIN COOLING COIL 1" - Full load outlet temperature indicates a possibility of frost/freeze error continues. Outlet air temperature statistics follow:
   *************  **   ~~~   **   This error occurred 143 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=-249.676622  Min=-295.62166
   *************
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Completed Successfully-- 3456 Warning; 1 Severe Errors; Elapsed Time=00hr 00min 10.90sec
```

**Comment by Nigusse** [comment]
@Myoldmopar.  @mjwitte.  I think the first issue "SetupZoneInternalGain: developer error, trapped inconsistent internal gains" is that the HVAC enhancement did not include IT equipment model when the HVAC model was implemented.  Probably, you are using the example file after Mike added the IT equipment model.

**Comment by Myoldmopar** [comment]
Yeah, I tried to merge the two together as best I could tell.  I'll have to rely on you and/or @mjwitte to assist in getting the right objects in there.  

However, that message is a 'developer error' that likely shouldn't be accessible from mismatched inputs and means something is wrong in the code.

I'm about to make a push with develop merged in and lots of other issues fixed.  Do a git pull once I push that up and see if you can figure out the problem.

**Comment by Myoldmopar** [comment]
OK, here are some remaining steps:
 - [ ] Figure out the error file, do further testing alongside IT equipment enhancements (@nigusse @mjwitte)
 - [ ] Work with @DeadParrot to figure out proper FArray argument form (@myoldmopar)
 - [ ] Complete unit test implementation that I stubbed out (@nigusse)
 - [ ] Write transition changes and update idfs (@myoldmopar)

**Comment by mjwitte** [comment]
@Myoldmopar @Nigusse I need to address issues #4655 and #4719 . It's probably pointless for you to work on this until those are cleaned up and merged in.  Will move up on my list.

**Comment by mjwitte** [comment]
@Myoldmopar Regarding format statements should *not* be const, do we have a list of all these tips somewhere in the wiki?

**Comment by Myoldmopar** [comment]
@mjwitte Not yet, though I think there is [a spot](https://github.com/NREL/EnergyPlus/wiki/Development-Tips-%26-Resources) is ready for it.

**Comment by Myoldmopar** [comment]
@Nigusse In the transition rules, you have this:

> modify the Secondary Air Inlet Node name to Outlet Node Name and enter here

Can you explain this?  I guess (hope) you are adding an _optional_ new outlet node so that I can leave it blank.  Otherwise I'd have to mine the whole idf looking for node names so that I don't cause a conflict.  And I'd have to presumably wire this outlet node up to something else?

Please clarify, and hopefully just say I can leave this blank.  Or explain the simple solution I'm missing.

**Comment by Nigusse** [comment]
@Myoldmopar. In the current code it is not optional.  Now, we calculate and report the secondary air outlet parameters.  It may lead to crash, if you leave it blank, I think .  This node number is used in update stage only. There are two options that can be done.
(1)  Add a conditional statement in the update routine such that only when the node number is not zero is used.
(2) Automatically add secondary air outlet node name during transition ( my suggestion was to modify the secondary air inlet node name such that it becomes unique). If you give it a generic name it may create duplicate node name when there are more than one Evap Coolers.

**Comment by Myoldmopar** [comment]
Option 1.  

For option 2, even if I think I've made an optional node name, there's no guarantee that a user has named their nodes appropriately.  It could still collide.  And if the idf originated from a GUI, the node name could be a UUID that isn't human readable.

**Comment by mjwitte** [comment]
@Myoldmopar @Nigusse There is precedent (for better or worse) for the component to self-generate a node name.  e.g.  Don't the chillers fabricate a condenser inlet node name if it's an air-cooled chiller and that node is left blank?  Or is the DX coils that do that?  @rraustad

**Comment by Myoldmopar** [comment]
That's fine as an adjusted option # 1 to me.  I'm not going to handle it in transition, so if the component wants to ignore if it is blank, that's fine, or if it wants to try to generate a node name and update it appropriately, that's fine too.

**Comment by DeadParrot** [comment]
@Myoldmopar Wrt the Optional Par argument in Residual calls, I made those regular arguments for performance and clarity. In practice I found no places where the Par argument wasn't present but I added an overload of RegulaFalsi without Par anyway. You can look at the changes to all the other Residual functions to see the effect of making Par a regular argument. I believe the Par array also becomes a pass-by-ref `FArray1< Real64 >` (unless a slice is really going to be passed), also for performance, and the `Par()` usage becomes `Par`.

**Comment by Nigusse** [comment]
@Myoldmopar.  @mjwitte. I looked at the code, I think for transitioned IDFs, it is optional.  You may leave it blank. If we run into issues then we will add if statement to check if the node name is specified.  @Myoldmopar.  The idd for "EvaporativeCooler:Indirect:ResearchSpecial," object in the branch shows that the merging did not come clean.  There are duplicate input fields.

**Comment by Myoldmopar** [comment]
OK, I pushed up several commits.  I _think_ the transition changes are done.  I grabbed a couple evap cooler idfs and transitioned them.  Might still need some changes overall, but I actually think this isn't too far off.

**Comment by rraustad** [comment]
Re: Or is the DX coils that do that?
DX coils just check to see if the node name is valid: CheckOutAirNodeNumber
Chillers will actually add the node if it's missing: CheckAndAddAirNodeNumber

**Comment by Myoldmopar** [comment]
OK, with the fixes from #4748, the example file now runs great, and the error file is reduced to just minor warnings about the coil entering condition out of bounds.  A great step.

Thanks @mjwitte for the quick fix.

**Comment by Myoldmopar** [comment]
Thanks for the tip @DeadParrot.  I think I'd lean toward removing the overload.  By the nature of regula-falsi it has to have a perturbed input to produce a different result and allow the caller to continue to solve the equation of interest.  It will always need par.  Unless I'm missing something...  Anyway, we can do it later, but eliminating that option would eliminate a check during reviews.

**Comment by Myoldmopar** [comment]
OK, d00d02d cleaned up the argument so it isn't optional anymore.  I actually think the transition work is also complete; I only found the research special coolers in a couple files that I transitioned and pushed yesterday. 

@Nigusse Can you flush out the unit tests today according to the [stubs I put in](https://github.com/NREL/EnergyPlus/pull/4624/files#diff-bc3d9a46433bd7c48b31aac57ec6e47fR1)?  If you find the function ```CalcSecondaryAirOutletCondition``` in [these coverage results](http://energyplus.s3-website-us-east-1.amazonaws.com/coverage/2015-02-23-EP-beef24fb92-x86_64-G4.8UTCD/EnergyPlus/EvaporativeCoolers.cc.gcov.html), you can see I barely touch the code with my simple unit test.  It would be great to get all the different code paths covered.  Let me know if you have any questions.

After the unit test is flushed out, this could be pretty close.

**Comment by Myoldmopar** [comment]
Updating those files seems to have caused them to fail...not sure why yet.  I'll take a look after my current related task.

**Comment by Nigusse** [comment]
@Myoldmopar. Flushed out the unit tests and added multiple flavors of unit test for primary and secondary air outlet calculation routines and the power calculating routine. I am ready to commit the unit test code if that alright with you?

**Comment by Myoldmopar** [comment]
Yeah, please do, and thanks for the speed.

**Comment by Nigusse** [comment]
@Myoldmopar. Committed the unit test code of evaporative cooler.  There are three unit tests and each unit test has multiple flavor.

**Comment by mjwitte** [comment]
@Myoldmopar @Nigusse At some point, I should add the "real" ITE equipment object to 2ZoneDataCenterHVAC_wEconomizer.idf  Would you like me to add that to this PR or wait until this is in and then make a new PR?

**Comment by Myoldmopar** [comment]
This one, please.

**Comment by mjwitte** [comment]
@Myoldmopar This branch has the SysTotCoolCap being used uninitialized problem.  Is there an issue or PR in progress to fix that?

**Comment by EnergyArchmage** [comment]
dunno the answer to that, but adding this at line 4723 in SimAirServingZones.cc is working for me.

				SysTotCoolCap = 0.0;

**Comment by Myoldmopar** [comment]
Nothing in progress yet. I can try to add that to this branch today. Thanks
@energyarchmage.

**Comment by mjwitte** [comment]
@Myoldmopar On this branch the error pops up with 2ZoneDataCenterHVAC_wEconomizer  I'm a little concerned that initializing it to zero may be masking the real problem.  It gets used multiple times, if you keep hitting ignore (on windows), the error keeps occurring (at least 30 times or so until I gave up).  It fails at SimAirServingZones.cc line 4790

**Comment by Myoldmopar** [comment]
OK, so back to this PR.  That SysTotCoolCap bug really _isn't_ being worked on anywhere else, right?  And is the bug also in develop, or was it introduced in this branch?  If it was in develop too, then I'm splitting responsibility away from this PR to fix it so that I can get this merged and fix it separately.  If it was introduced here, then I'm going to step away from this branch and work on reviewing/merging others.

@Nigusse @EnergyArchmage @mjwitte

**Comment by mjwitte** [comment]
@Myoldmopar It was not introduced here, but it is preventing one of these new example files from running, the 2-zone data center.  I just noticed some missing \object-list lines in the ITE IDD object, will commit those here shortly.  I don't see SysTotCoolCap in the diffs for this PR, so I'm fairly certain it was introduced into develop with the recent sizing:system changes, #4635 .  Let's make a new issue for that,get that fixed and merged, then come back to this one.

**Comment by Myoldmopar** [comment]
Note I pulled in the _current_ state of #4766 to this branch in anticipation of it getting fixed first.  Once that is merged in successfully, this can get merged right on top of it.

**Comment by Myoldmopar** [comment]
@Nigusse this is close but not done yet. Take a look at the test results and you'll see two files have fatal errors and a couple others have node connection errors causing lots of issues. Let me know what you find in there.

**Comment by Nigusse** [comment]
@Myoldmopar The two test files with fatal error have not been transitioned yet.  I don't see test files with node connection errors. Did you transition the rest of the test files? Do you want me to transition them manually, test them and commit them? Let me know.

**Comment by Myoldmopar** [comment]
The two files that are failing have been transitioned, at least attempted:
 - [DirectIndirectEvapCoolers](https://github.com/NREL/EnergyPlus/pull/4624/files#diff-0795ce0bbe9c3fa72116614f9882b574)
 - [DirectIndirectEvapCoolersVSAS](https://github.com/NREL/EnergyPlus/pull/4624/files#diff-4f30b6989cecfa817c52a49ab77706bd)
If there is something wrong with the transition of those files, then that should be addressed.

The files with node connection errors are the other ones listed on [this page](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-34a2a192ccd475d46f30c8995c0fec761905d7f3-x86_64-MacOS-10.9-clang.html), including:
 - IndEvapCoolerRTUoffice
 - ReliefIndEvapCoolerRTUoffice
 - StripMallZoneEvapCooler

[Here](http://energyplus.s3-website-us-east-1.amazonaws.com/1ab2e08766c5e728f8ce6eb8a492fd516a07d5ec-34a2a192ccd475d46f30c8995c0fec761905d7f3/ReliefIndEvapCoolerRTUoffice/x86_64-MacOS-10.9-clang/eplusout.err.diff.html) is an example of one of the error files.

If something went wrong with transition, let me know and I'll try to fix it this morning.

**Comment by Nigusse** [comment]
@Myoldmopar.  I see the transitioned objects for indirect evaporative cooler objects after the input field "Dewpoint Effectiveness Factor" are truncated (left out).  The secondary air inlet and outlet node names, and the remaining input fields are also are missing in the transitioned objects. 

Also the transitioned direct evaporative cooler objects are also truncated after the input field "!- Sensor Node Name".

I have manually transitioned the five test files and they all run successfully here in my machine. Do you want me to push them to the remote branch?

**Comment by Myoldmopar** [comment]
Yes, and I'll make sure the Transition code is doing the right thing
according to IDD changes.

On Tue, Mar 3, 2015 at 10:44 AM, Bereket Nigusse <notifications@github.com>
wrote:

> @Myoldmopar <https://github.com/Myoldmopar>. I see the transitioned
> objects for indirect evaporative cooler objects after the input field
> "Dewpoint Effectiveness Factor" are truncated (left out). The secondary air
> inlet and outlet node names, and the remaining input fields are also are
> missing in the transitioned objects.
>
> Also the transitioned direct evaporative cooler objects are also truncated
> after the input field "!- Sensor Node Name".
>
> I have manually transitioned the five test files and they all run
> successfully here in my machine. Do you want me to push them to the remote
> branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NREL/EnergyPlus/pull/4624#issuecomment-76995618>.
>



-- 
Edwin Lee, PhD
Engineer, Commercial Buildings Research Staff
National Renewable Energy Laboratory

**Comment by Nigusse** [comment]
@Myoldmopar. Committed the five test files.

**Comment by Myoldmopar** [comment]
OK, CI will run and I'll check out the transition source.

**Comment by mjwitte** [comment]
@Myoldmopar Sounds like \min-fields may need to be changed for those objects to transition properly?

**Comment by mjwitte** [comment]
@Myoldmopar And remember I'm still planning to modify to 2zone data center example fiile once the systotcap fix in merged in here (or did that happen already and I missed it?)

**Comment by Myoldmopar** [comment]
That did already happen, go ahead and make the change to this branch.

**Comment by Myoldmopar** [comment]
@Nigusse So updating those files in https://github.com/NREL/EnergyPlus/commit/db026d7785bf18256c0ebfcec5cb345d62ec2c3f might have helped them run, but it seemed to undo some of the things Transition had cleaned up previously.  The system sizing objects got the new fields truncated down, so the input processor is now filling them with defaults, and lots of comments are reverted.  There will definitely need to be a follow-up to clean up those files (along with the change @mjwitte wants to make to the example file), but after those are done, I do think this is close.  I'll wait to merge develop into this branch until we get those issues worked out.

**Comment by Nigusse** [comment]
May be I have to revert the five test files that I committed yesterday and update only the evaporative cooler objects changes individually and re-commit them.  Is that okay with  you?

**Comment by Myoldmopar** [comment]
That's perfect; thank you.

**Comment by Nigusse** [comment]
@Myoldmopar @mjwitte Cleaned up the four test files and committed to the remote branch. Only four them needed cleanup, I think.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse; I merged develop back in now and we'll see what CI says.  @mjwitte still may make another commit to modify an input file, but this should get us very close.

**Comment by mjwitte** [comment]
@Myoldmopar @Nigusse Fixed some errors with the IDD and ITE get input.  I have a modified version of 2ZoneDataCenterHVAC_wEconomizer that uses the ITE object instead of the generic electric equipment object, but it fails in June on an annual run, so I am reluctant to commit it.  I can keep working on that here or perhaps that should be moved to a new issue so this can be merged at CI tests the fix commit?

**Comment by mjwitte** [comment]
New issue #4773 opened to resolve the 2ZoneDataCenterHVAC_wEconomizer  problems with ITE object.  Leaving 2ZoneDataCenterHVAC_wEconomizer  as-is for now with simple ElectricEquipment so this branch can get in after CI reports back.

**Comment by mjwitte** [comment]
@Myoldmopar Unit test fixed.  Ready for your final review and merge.

**Pull request merged**
