### PR TITLE
Minor fixes to EP-Launch 2, IDF Editor, IDF Version Updater

### LINKED ISSUE #7238: Remove GettingStarted and add references to Essentials and QuickStart
Issue overview
--------------
EP-Launch 2, EP-Launch 3, and IDF Editor currently can open GettingStarted PDF. These applications should be updated to remove opening Getting Started and should add the capability to open the Essentials document and the QuickStart web page. In addition, the Getting Started document should be removed and all references to it in other documentation should be fixed. References to the Essentials and QuickStart guides should be added where appropriate to other documentation.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9403: Support Output:JSON output files in EP-Launch 2 and 3
Issue overview
--------------
When specifying to produce output files using:

```
  Output:JSON,
    TimeSeriesAndTabular,    !- Option Type
    Yes,                     !- Output JSON
    No,                      !- Output CBOR
    No;                      !- Output MessagePack

```

and using EP-Launch 2 or EP-Launch 3, the output files are not renamed the user provided names and for EP-Launch 2, stay in the EPTEMP directory with names eplusout.json and eplusout_hourly.out

The files that need to be supported in EP-Launch 3 workflows and in EP-Launch 2 are identified in the list in CommandLineInterface.cc files:

```
        state.files.json.outputJsonFilePath = composePath(normalSuffix + ".json");
        state.files.json.outputTSZoneJsonFilePath = composePath(normalSuffix + "_detailed_zone.json");
        state.files.json.outputTSHvacJsonFilePath = composePath(normalSuffix + "_detailed_HVAC.json");
        state.files.json.outputTSJsonFilePath = composePath(normalSuffix + "_timestep.json");
        state.files.json.outputYRJsonFilePath = composePath(normalSuffix + "_yearly.json");
        state.files.json.outputMNJsonFilePath = composePath(normalSuffix + "_monthly.json");
        state.files.json.outputDYJsonFilePath = composePath(normalSuffix + "_daily.json");
        state.files.json.outputHRJsonFilePath = composePath(normalSuffix + "_hourly.json");
        state.files.json.outputSMJsonFilePath = composePath(normalSuffix + "_runperiod.json");
        state.files.json.outputCborFilePath = composePath(normalSuffix + ".cbor");
        state.files.json.outputTSZoneCborFilePath = composePath(normalSuffix + "_detailed_zone.cbor");
        state.files.json.outputTSHvacCborFilePath = composePath(normalSuffix + "_detailed_HVAC.cbor");
        state.files.json.outputTSCborFilePath = composePath(normalSuffix + "_timestep.cbor");
        state.files.json.outputYRCborFilePath = composePath(normalSuffix + "_yearly.cbor");
        state.files.json.outputMNCborFilePath = composePath(normalSuffix + "_monthly.cbor");
        state.files.json.outputDYCborFilePath = composePath(normalSuffix + "_daily.cbor");
        state.files.json.outputHRCborFilePath = composePath(normalSuffix + "_hourly.cbor");
        state.files.json.outputSMCborFilePath = composePath(normalSuffix + "_runperiod.cbor");
        state.files.json.outputMsgPackFilePath = composePath(normalSuffix + ".msgpack");
        state.files.json.outputTSZoneMsgPackFilePath = composePath(normalSuffix + "_detailed_zone.msgpack");
        state.files.json.outputTSHvacMsgPackFilePath = composePath(normalSuffix + "_detailed_HVAC.msgpack");
        state.files.json.outputTSMsgPackFilePath = composePath(normalSuffix + "_timestep.msgpack");
        state.files.json.outputYRMsgPackFilePath = composePath(normalSuffix + "_yearly.msgpack");
        state.files.json.outputMNMsgPackFilePath = composePath(normalSuffix + "_monthly.msgpack");
        state.files.json.outputDYMsgPackFilePath = composePath(normalSuffix + "_daily.msgpack");
        state.files.json.outputHRMsgPackFilePath = composePath(normalSuffix + "_hourly.msgpack");
        state.files.json.outputSMMsgPackFilePath = composePath(normalSuffix + "_runperiod.msgpack");

```
Also note a related issue #9393 

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9721: IDFVersionUpdater.exe is deleting the idd when the transition occurs in the transition folder
Issue overview
--------------
When tying to update an older input file the IDFVersionUpdater.exe transition program is deleting the idds for the previous version and the new version when the transion folder is used. Running the transition program (Transition-V9-6-0-to-V22-1-0.exe) directly did not cause the idds to be deleted.

Work around: use a different folder to store and update the input file (i.e., any folder other than IDFVersionUpdater)

The pop-up message also needs updating (...\EnergyPlus\src\IDFVersionUpdater\Window1.rbfrm). The older version of the input file is named *_Vxxx.idf

image

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (5ZoneAirCooled example file)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9737: v22.2 IDF Version Updater fails to recognize some forms of complex version numbers
Issue overview
--------------
The IDF version updater program fails to recognize some complex version number, such as "8.9.0.001"---which is commonly seen in DesignBuilder edited files. When opening an IDF that contains "Version, 8.9.0.001;", the IDF Version Updater will show the following error messages and failed to update:
image

A temporary workaround is to revise simplify the version number---e.g. change "8.9.0.001" to "8.9". The v22.2 IDF Version Updater will then work properly.

Previous versions (e.g. v22.1) recognize the more complex form (e.g. "8.9.0.001") without problems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Possibly All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10166: IDF Version Updater still shows energyplus.gov link
Issue overview
--------------
Remove any links to energyplus.gov from IDF Editor:

image

add a link to the correct location for these files.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #10166 
 - Fixes #9737 
 - Fixes #9721 
 - Fixes #9403 
 - Fixes #7238

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@JasonGlazer I've tested everything except EP-Launch 2/3 and everything is good except #9721 . It transitions a file in the IDFVersionUpdater folder successfully now (before it kept complaining), but it's still deleting the IDD and report variables files.

**Comment by JasonGlazer** [comment]
@mjwitte I just tried to reproduce #9721 and it seems to work. Here are the steps I did and you can tell me what you did that did not work. Starting with 24.1 iofreeze version I copied the IDFVersionUpdater folder to IDFVersionUpdater17 then copied all the new IDFVersionUpdater files from the repo. The version should show in the about box as 0.17 (not sure why we are using under 1.0 versions for this still). Then I copied the the EngineChiller.idf file from EnergyPlus 9.5 calling it EP9-05-0-EngineChiller.idf into the IDFVersionUpdater17 folder. I ran IDFVersionUpdater and selected that file and transitioned and it did that successfully and left all the ReportVariables files and IDDs alone.

**Comment by mjwitte** [comment]
I built an installer from this branch, copied 1ZoneDataCenterCRAC_wApproachTemp.idf into "C:\EnergyPlus\EnergyPlusV24-1-0-AuxToolsTest\PreProcess\IDFVersionUpdater\1ZoneDataCenterCRAC_wApproachTemp.idf" and launched IDFVersionUpdater.exe "IDF Version Updater - Version 0.17", transitioned the file, and, um, well, everything's there just fine. So never mind. I must have looked in the wrong folder before or something. So this is all ok. Still need to test the new EP-Launch changes.

**Review by mjwitte — APPROVED** [review]
@JasonGlazer Everything checks out ok here.
@Myoldmopar This is ready for your final review/merge.

**Review by Myoldmopar — APPROVED** [review]
No objection here.  If you've tested it out and all, it's good to go.  Thanks for these fixups.

**Comment by Myoldmopar** [comment]
Something went wildly wrong and CI can't even checkout the repo after this merge.  I'm reverting it...but happy to fix it up and merge it in again.  https://github.com/NREL/EnergyPlus/actions/runs/8239232019/job/22531987495#step:2:487

**Pull request merged**
