### PR TITLE
Fix typos in docs/IDD

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
 - Fixes hundreds of typos in docs (I/O Ref and Engineering Ref) and IDD.
 - There were some IDD field names changed as a result of this, so Rules23-1-0-to-23-2-0.md is updated.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by dareumnam** [comment]
On my local machine, `SQLiteFixture.UpdateSizing_EndSysSizingCalc` test passed, but failed on CI. Once I'll merge develop again and see how it goes.

**Comment by dareumnam** [comment]
`SQLiteFixture` tests seem unrelated to it. I built it locally and all the tests passed locally. It generated all documents clean. It's great to see that tons of typos have been removed. Thanks for the huge effort here.

**Comment by nrel-bot-2b** [comment]
@shorowit it has been 8 days since this pull request was last updated.

**Review by Myoldmopar — COMMENTED** [review]
This is really awesome.  Such a huge set of typo fixes, thanks!  I will ask one question related to the like -- 6 -- IDD field changes.  What happens if we do this full PR but leave those out.  That way it is one less thing to break for EpJSON inputs.  I'm not saying that _needs_ to happen here, but I wonder what other folks think about that.  We desperately need to resolve our IDD/EpJSON transition process, but for now I'm just trying to balance our IDD fixes with the impact on JSON users.

**Comment by nrel-bot-2** [comment]
@shorowit it has been 8 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
OK, I'll set aside my concerns about the IDD field change and get this in.  I'll fix the minor conflict and give it a quick build/test locally now.

**Comment by Myoldmopar** [comment]
Conflict was one line from the earth tube PR.  Fixed it, built happily, committed, and pushed.  Merging now, thanks @shorowit

**Pull request merged**
