### PR TITLE
Reduce external interface maximum variables

### PR DESCRIPTION
**Pull request by kbenne**
A recent increase in the maximum number of allowed variables caused in integer to overflow causing the program to crash. Ref #6339 
See here: https://github.com/NREL/EnergyPlus/blob/2a735636b95cbc73b3e133b6d3319a3db8cc582a/src/EnergyPlus/ExternalInterface.cc#L544

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by kbenne** [comment]
@tsnouidui I reduced the size of maxVars to 100000 so that the ```int lenXmlStr``` is not initialized to a number that it is not capable of holding, but I think my fix is still poor quality and brittle. The max size of int is platform dependent so it might be better to use std::numeric_limits<int>::max() but this get tricky because maxVars is multiplied by MaxNameLength. 

In any case this change makes ExternalInterface work for me on Linux 64 bit. Prior to this change E+ was killed at the line I referenced in the commit message.

**Comment by Myoldmopar** [comment]
@kbenne did you ever get any feedback from @tsnouidui about this?

**Comment by tsnouidui** [comment]
@Myoldmopar Yeah I gave feedback to @kbenne and said that the fix is OK.

**Comment by Myoldmopar** [comment]
Works for me.

**Pull request merged**
