### PR TITLE
Fix get input problem when same file has unitary systems as zone equipment and on airloop

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Addresses #6405, get input errors for unitary systems used as both zone equipment and airloop equipment in the same file.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@rraustad This fixes the defect file.  The diff on github is a mess.  There are two changes here:
1.  Remove the GetInputFlag checks in [GetUnitarySystemInput](https://github.com/NREL/EnergyPlus/blob/a969bdd4338121f9ae15b58fd2ebbe38475cbab2/src/EnergyPlus/HVACUnitarySystem.cc#L2706) that were added as part of the multiple airloop changes.
2.  Move [this entire block](https://github.com/NREL/EnergyPlus/blob/a969bdd4338121f9ae15b58fd2ebbe38475cbab2/src/EnergyPlus/HVACUnitarySystem.cc#L3244-L3504) up before the fan and coil input processing.

**Comment by rraustad** [comment]
I made these changes to my local develop and then on my SZVAV branch. Compiled both exe's to compare a few test files, including this defect file. I also copied this defect file and changed to Load based control for the 2 UnitarySystem objects in this file. This appears to be working. The only SMALL diff's I see are in my SZVAV test file. The defect file using Load control has 0 diff's.

**Comment by mjwitte** [comment]
Well, foo.  The failing tests ran locally.  Hmm.

**Comment by rraustad** [comment]
These are hard to fix. If you look up in the virtual void Setup section where I try to set everything up that's needed, except for the parent and child objects for unitary systems. It's probably that something is missing in that setup and these unit tests hit an uninitialized variable, unallocated array, or something. The only way I've figured these out is to single step very carefully looking for something missing (from Setup). MAYBE you could find it in debug but I'm not sure.

**Comment by mjwitte** [comment]
I had these tests in `ZoneUnitarySystemTest` instead of `EnergyPlusFixture`.  Hopefully that will fix it.

**Comment by rraustad** [comment]
@Myoldmopar why can't I see the test failure for the SQLiteFixture tests? When I click the Test Badge button (which isn't there but the text is) I get a GitHub 404 error page that says File Not Found.
Would you agree that a failure in SQLiteFixture has nothing to do with these changes and I can accept this PR since everything else passes?

**Comment by mjwitte** [comment]
@rraustad I deleted those results and it should rebuild - it was system errors - not real failures.  I figured it would be done by now.

**Review by rraustad — APPROVED** [review]
Reviewed and implemented in parallel branch (SZVAV) and works as expected. CI clean.

**Pull request merged**
