### PR TITLE
Enable crash dialog on windows debug

### PR DESCRIPTION
**Pull request by kbenne**
[#87641650]

### CODE REVIEW

**Comment by kbenne** [comment]
https://www.pivotaltracker.com/story/show/87641650

**Comment by mjwitte** [comment]
@kbenne Thanks!  So, this should not impact CI as long as we keep the debug tests on Linux or Mac?

**Comment by kbenne** [comment]
I'm trying to confirm that with @lefticus now.  I'm pretty sure they are all running release.

**Comment by EnergyArchmage** [comment]
Can we get windows debug builds to give a decent traceback?  I have yet ever see one with any history before the line that crashed...

**Comment by kbenne** [comment]
@EnergyArchmage I still have an open issue on that and it hasn't slipped my mind.  My thoughts are summarized [here](https://github.com/NREL/EnergyPlus/issues/4471#issuecomment-59973607).

**Comment by mjwitte** [comment]
@kbenne I tested debug and release builds of this branch with a user file that crashes.  Debug build popped up the dialog, and when run in the Win VS debugger, it allows you to press "retry" and then "break" to see where it failed.  Release build just exits without a dialog.  Merging.

**Comment by EnergyArchmage** [comment]
This is helping when debugging EnergyPlus.exe, but the behavior is not the same when running EnergyPlus_Tests.exe.  I get the dialog pop up in the same way but with EnergyPlus_Tests.exe it never seems to work to let VS go to the crash in the debugger.  

I am finding it is fairly difficult to flush out missing peices of unit test fixtures when the hard crashes are in places like 'vector line 1201'

**Comment by mjwitte** [comment]
@kbenne That would be nice if it's possible.
@EnergyArchmage My current method for debugging unit tests is rather primitive, breakpoints in my unit test right at the call to an EnergyPlus routine, then F10 single-stepping until it fails.

**Comment by kbenne** [comment]
@mjwitte @EnergyArchmage do either of you have a specific unit test that I might be able to recreate this in?  Or perhaps I just create a test with a deliberately failed assertion or access violation?  What would best recreate your circumstances?

**Comment by mjwitte** [comment]
@kbenne Here's one example, if you comment out lines 68:75 the unit test will crash with an assertion error down in objexxfcl.  I will confirm shortly.
https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/unit/PurchasedAirManager.unit.cc#L68

**Comment by mjwitte** [comment]
@kbenne That will cause a crash, but leave the PurchAirNum=1 line active.  So it should look like this:
```
	//PurchAir.allocate( 1 );
	//PurchAirNumericFields.allocate( 1 );
	PurchAirNum = 1;
	//PurchAirNumericFields( PurchAirNum ).FieldNames.allocate( 8 );
	//PurchAirNumericFields( PurchAirNum ).FieldNames( 5 ) = "Maximum Heating Air Flow Rate";
	//PurchAirNumericFields( PurchAirNum ).FieldNames( 6 ) = "Maximum Sensible Heating Capacity";
	//PurchAirNumericFields( PurchAirNum ).FieldNames( 7 ) = "Maximum Cooling Air Flow Rate";
	//PurchAirNumericFields( PurchAirNum ).FieldNames( 8 ) = "Maximum Total Cooling Capacity";
```

**Comment by kbenne** [comment]
@mjwitte I was able to completely reproduce this and I can see why this is totally unacceptable.  I think I can help.

**Comment by mjwitte** [comment]
Our hero!

**Comment by kbenne** [comment]
Well not yet.  But this gives me some idea where to go looking.

PS this is not the experience on non windows computers.

**Comment by kbenne** [comment]
It wasn't even clear that the dumb thing crashed until i looked at the exit code.  just radio silence.

**Comment by kbenne** [comment]
screen shot 2015-02-19 at 4 51 39 pm


Seriously this is it...

**Comment by mjwitte** [comment]
Of course, non-windows machines don't do that.  I run energyplus_tests.exe from a dos box so I can see the output, and there it terminates with this message, so I know something's happened:

Assertion failed: contains( i ), file C:\MJW-Work\EnergyPlus Git\EnergyPlus-MJWDevelopment2\third_party\ObjexxFCL\src\ObjexxFCL/FArray1.hh, line 1131

**Comment by kbenne** [comment]
It is possible to connect the CLI debugger to the test. somehow.  I think.  But we should be able to get this working inside VS.

**Comment by mjwitte** [comment]
Yep, that's the kind of useless information that prompted this branch in the first place for the main program.

**Comment by EnergyArchmage** [comment]
It does work sometimes when completely inside VS and actually running in the debugger, sometimes I can get it to break and show a stack to find the real issue.  But running from the dos prompt seems like the usual way to run the unit tests to see the output -- so when that hard crashes in FArray1 or vector you end up having to go back to the debugger .

**Comment by kbenne** [comment]
After research I found this one is not particular to environment.  I was wrong that you would not see this outside of Windows / VS setup.  The behavior we are seeing is a function of gtest capturing the exceptions and assertions and deliberately smothering them, so that the test suite continues on.  In automated testing, such as the dashboard, this is a good thing because then other tests can be run.  But obviously in debug scenarios it is not so helpful.  

Here is the solution in purest form.  Pass two command line arguments to the energyplus_tests executable.

```
energyplus_tests --gtest_break_on_failure --gtest_catch_exceptions=0
```

Details are documented [here](https://code.google.com/p/googletest/wiki/AdvancedGuide#Controlling_How_Failures_Are_Reported).

In VS you can set these properties through the IDE like this.

screen shot 2015-02-20 at 10 01 40 am

This will make things work, but when you hit the assertion the first time a couple of VS dialogs are going to come up.  I think if you read them they are fairly self explanatory.  On my setup some of the debug libraries were not installed so one dialog prompted me to install them, which I did, and things continued smoothly to a call stack like this.

screen shot 2015-02-20 at 10 01 48 am


There are also environment variables as an alternative to CLI arguments.  

```
GTEST_BREAK_ON_FAILURE=1
GTEST_CATCH_EXCEPTIONS=0
```

Of course we can document this, but I think it might be better to have something a little more pre configured.  I'm going to experiment with some new test runner targets for VS that might help do this for you.

**Comment by EnergyArchmage** [comment]
Thank you Kyle!  those args are working for me here.  maybe I'll get this blasted unit test working yet

**Comment by kbenne** [comment]
@EnergyArchmage @mjwitte on other fronts, how are you debugging integration style tests, aka full energyplus simulations?  Are you content with your workflow?  There isn't really anything in the project making this convenient from within the IDE.  Would you like something?

**Comment by mjwitte** [comment]
@kbenne I'll be content once the IDD stops moving around.  For now, reinstating the crash dialog for debug builds has solved most of the problems for debugging full simulations for me.

**Comment by EnergyArchmage** [comment]
The main thing missing for me is a useful traceback to stdout.  Running large full simulations in the dugger does work but it is quite a bit slower than command line execution.  I'll often wait for minutes and minutes to get to the crash point.  I have years of experience placing breakpoints in E+ so I can make good use of the debugger, but I don't know how new developers are going to manage.

**Comment by kbenne** [comment]
@EnergyArchmage help me understand this.  

1) Running debug builds from the command line (ie. ```./energyplus.exe .... ```) is signficantly faster than running debug build through the IDE using the debug feature?  

2) We aren't talking about a difference between release and debug builds are we?

3) If the previous are both true then presumably the act of attaching to the debugging is slowing things down, perhaps regardless of making that attachment to the debugger from the command line or the graphical IDE?  (It is possible somehow to use the windows CLI to debug)

4) So you would like a call stack to standard out when a normal invocation of (```./energyplus.exe```) fails for debug and release?

I am assuming all of the above is true, and I have been thinking about item 4, knowing it is something people want.  But I don't think it is trivial and line numbers in release call stacks are probably out of the question unless our release builds became something like debug builds with optimization flags turned on.  Which is possible but I doubt anyone would want it and it would surely increase the executable size.

All that said, I think it is possible to write a custom error handler to print the stack (sans line numbers in release).  As I mentioned some time ago I started to get into this when I disabled the dialog on release builds, but it became an "investment" that I didn't have the appetite for then.  Mac and Linux do this by default.  And wouldn't be surprised to learn if this is a function of the particular runtime as much as a function of platform.  i.e. Intel might dump differently from MSVC.

**Comment by kbenne** [comment]
Oh and my investigation of the Win API lead me to believe that they were pushing you toward these mini dump files which are binary snapshots of what happened, that a developer could inspect using Visual Studio.  Fancy, but not actually what you want.  The mini dumps appeared easy to retrieve.  Like one API call.

**Comment by Myoldmopar** [comment]
@energyarchmage just to verify, you do have the no_debug_heap switch turned on, right?

**Comment by EnergyArchmage** [comment]
@kbenne 
1. yes, maybe factor of 10 slower running in VS IDE debugger compared to command line execution of a debug build.  
2. no. all debug builds
3. search me. but doesn't surprise me the IDE is slower, fortran was that way. 
4. just debug.   the equivalent of what /traceback in fortran used to give. 

@Myoldmopar eh? haven't found that switch yet, nor messed with whatever cmake is producing.

**Comment by Myoldmopar** [comment]
Check step 9 here:
https://github.com/NREL/EnergyPlus/blob/develop/README.md#windows

**Comment by kbenne** [comment]
For what its worth it seems Intel supports /traceback on their icc compiler same as ifort.

https://software.intel.com/en-us/node/523197

If there is an equivalent for MSVC I haven't found it yet.

**Pull request merged**
