### PR TITLE
Revise memory allocation in FMU import libraries

### PR DESCRIPTION
**Pull request by tsnouidui**
Fix type mismatch.
Address #5221

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@tsnouidui Why did you change permissions on the source?

image

**Comment by tsnouidui** [comment]
@Myoldmopar  I haven't intentionally changed permissions and don't even know how this should be done...

**Comment by tsnouidui** [comment]
@Myoldmopar Anything I need to do? Will you merge this pull request soon?
Thanks!

**Comment by Myoldmopar** [comment]
I had just needed the executable bit removed from the files.  You should figure out why your editor/system is saving the files with the executable bit.  If you are accessing a volume from multiple operating systems it is possible something is being masked and saved awkwardly.  (such as accessing an NTFS volume from Linux...)

I took care of it.  And merged develop in.  It should come back clean then it can merge.

**Comment by tsnouidui** [comment]
Great. Thanks. Thierry

**Pull request merged**
