### PR TITLE
Update to shading airflow coefficients feb2022

### PR DESCRIPTION
**Pull request by vidanovic**
Pull request overview
---------------------
 - Implementation of new airflow coefficients in WCE and tarcog legacy code
 - WCE have one bugfix: https://github.com/LBNL-ETA/Windows-CalcEngine/issues/97

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - No changes to IDD

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@vidanovic Is this intended for v22.1 release?

**Comment by vidanovic** [comment]
@mjwitte Yes, for the April release.

**Comment by mitchute** [comment]
I'm building and testing this locally now. Most of the changes here are buried down in the third-party WCE code, so I won't comment on any design or functionality there. The rest of the changes look minimal, but they are expected to produce diffs due to updated coefficients. I'll merge develop in here one more time, but I suspect this can go after that.

**Comment by vidanovic** [comment]
@mitchute Thanks!

**Comment by Myoldmopar** [comment]
For some reason the Windows CI bot specifically had gone down, but the Linux ones were all running well.  Probably more forced updates.  Anyway, this seems like reasonable CI results.  No reason to really hold it up I don't think.

**Pull request merged**
