### PR TITLE
For multiple year run periods, only show final simulation year in tabular reports

### PR DESCRIPTION
**Pull request by JasonGlazer**
Fixing #4284.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
This should be all the code changes needed. No test cases developed yet.

**Comment by JasonGlazer** [comment]
Yes, that is what it turned out to be. It is passing Clang now.

**Comment by JasonGlazer** [comment]
I think this finally ready to be reviewed and merged. I assume either @Myoldmopar or @mjwitte are willing to review, if not let me know.

**Comment by mjwitte** [comment]
I will leave this for @Myoldmopar to review.
@JasonGlazer Please edit the pull request title and description to be appropriate for the change log.

**Comment by Myoldmopar** [comment]
@JasonGlazer, this looks good.  Built and ran locally.  Took an example file and ran 3 years with develop and this branch, and as expected, the tabular output is only showing the last year in this branch.  Merging and closing the bug.  Thanks.

**Pull request merged**
