### PR TITLE
Correct Humidity Ratio control variable false warning message in Controller:WaterCoil

### PR DESCRIPTION
**Pull request by Nigusse**
Address issue #4958 
This false warning is reported during Controller:WaterCoil object get input. Controller:WaterCoil with Control Variable of HumidityRatio throws false node setpoint warning due to mismatch in control variable type specified in water controller and setpoint manager schedule. The fix resets the Control Variable type, issues warning message about the mismatch and the simulation continues.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Nigusse If you can, please merge in current develop and resolve conflicts.

**Comment by Nigusse** [comment]
@mjwitte Merged in current develop, resolved conflict found in CMakeList file and pushed it to remote.

**Comment by mjwitte** [comment]
@Nigusse I've started reviewing this.  I've fixed the build failure and I'll bring in latest develop (as of a few minutes ago).

**Comment by Nigusse** [comment]
@mjwitte Thanks.  I was not sure what exactly problem was even though it was caused by merge conflict.

**Comment by mjwitte** [comment]
HVACSizingSimulationManagerTest.unit.cc ended up in the cmake list in two places.

**Comment by mjwitte** [comment]
Tested with defect file, and error is fixed.  As soon as CI comes back, this can be merged.

**Comment by mjwitte** [comment]
Even though windows CI is sickly, all the other tests are green, so merging.

**Pull request merged**
