### PR TITLE
Improved Scalable Pump Sizing

### PR DESCRIPTION
**Pull request by EnergyArchmage**
add design doc, IDD changes, I/O ref changes, Eng Ref changes.  For
Review
This addresses #3980 along with other changes to pump sizing.

### CODE REVIEW

**Comment by EnergyArchmage** [comment]
Comments from Larry

1) Your document says:

   Design Power Consumption = Design Flow Rate \* Design Pump Head / (scaling factor \* Motor Efficiency)
      where scaling factor = Design Power per Unit Flow Rate Per Unit Head

In its current configuration, the units don't match up:

   Design Power Consumption = Design Flow Rate \* Design Pump Head / (scaling factor \* Motor Efficiency)
   Watts                                     = m3/s                     \* Pa                           / [Watt/(Pa_m3/s)] \* nondim
                                                  = m3/s                    \* Pa                           \* Pa_m3/s / Watt = (m3/s)^2 \* Pa^2 / Watt

The equation should read:

   Design Power Consumption = Design Flow Rate \* Design Pump Head \* scaling factor / Motor Efficiency
                                                = m3/s \* Pa \* [Watt/(Pa*m3/s)] = Watt

2) Ashrae 90.1 specifies design pump consumption in terms of Watts/gpm; therefore, let's add Power/Design Flow Rate as a second scaling factor

These have been addressed in https://github.com/NREL/EnergyPlus/commit/32c28a2723c8fd14a433df478ec1664f05220aee

Note that test failures are expected because of changes in the count of input fields being caught in audit and html summary files

**Comment by nrel-bot-3** [comment]
@Myoldmopar @EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@EnergyArchmage I merged develop in, there was a minor conflict.  I'll look over the changes again, then after CI comes back happy; I'll look back over all the expected diffs, and this can go in if all is well.

**Comment by Myoldmopar** [comment]
And from what I can tell, this is all additional fields with defaults, so no transition rules, right?  Transition will handle the changed field names by default without special rules, so we're good with field name changes.

**Comment by EnergyArchmage** [comment]
That is right, no transition rules and let transition update the field name changes/corrections.  Some of the name corrections will impact OS but I have already discussed with Kyle and he is more or less okay with them.

**Comment by Myoldmopar** [comment]
Perfect, and yeah I fixed the tree conflict by pulling your changes in the OutputChanges document from txt to md.  I think this should be good to go in after CI is happy with my merge.

**Pull request merged**
