### PR TITLE
MELs Categorization for Reporting

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
Energy use by miscellaneous electric loads (MELs) has become a growing portion of energy consumption in residential and commercial buildings in the U.S. and worldwide. Currently,  EnergyPlus reports aggregated plug loads (under General end-use subcategory) without a way to break it down into major subcategories such as set-top boxes, TVs, PCs, etc. reported in the National Energy Modeling System (NEMS). This new feature proposal will implement end-use subcategorization to enable detailed MELs energy calculations and reporting in EnergyPlus to support GEBs research and application of tools such as Scout. The MELs categorization will be standardized based on previous research, DOE appliances standards, building energy codes and standards, as well as their significance in total energy use.

Currently, MELs are aggregated into the Interior Equipment end-use category in EnergyPlus. The default subcategory Interior Equipment does not provide a breakdown of MELs end uses. We propose to add a categorization for MELs which cover major plug loads in residential and commercial buildings

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by shorowit** [comment]
I don't know how far it makes sense to go with this, but on the residential side see Table 22 from the [Building America House Simulation Protocols](https://www1.eere.energy.gov/buildings/publications/pdfs/building_america/house_simulation.pdf) for two and a half pages of MELs.

**Comment by JasonGlazer** [comment]
The proposal is not clear, will the End Uses By Subcategory table in the Annual Building Utility Performance Summary report includes all of these predefined subcategories with zeros when the result is zero? I hope not it will make the report almost unreadable with so many extra lines. If that is not the goal, then I don't understand the reason for providing specific a specific subcategory list. What will that do that the simple string approach that is used cannot do now? 

My other comment is that this list of subcategories is far from complete and seems to be primarily for residential and offices. There are probably 1000s of additional subcategories if you expand into hospitals/medical buildings, laboratories, commercial kitchens, theaters, museums, police stations, fire stations, airports, auto repair, etc.. It is almost endless. Once the list gets long enough to capture them all, it becomes nearly impossible to find something specific. Lets say you think of a "portable fan" as simply a "fan" and look through the list of 100s of items and do not find "fan" then the user needs to think "what else could a fan be called?"

In general, I don't see a benefit to this addition.

**Comment by mjwitte** [comment]
I agree with @JasonGlazer. It seems this belongs in an interface or other input file generator rather than the EnergyPlus input schema.

**Comment by hongtz68** [comment]
> 
> 
> The proposal is not clear, will the End Uses By Subcategory table in the Annual Building Utility Performance Summary report includes all of these predefined subcategories with zeros when the result is zero? I hope not it will make the report almost unreadable with so many extra lines. If that is not the goal, then I don't understand the reason for providing specific a specific subcategory list. What will that do that the simple string approach that is used cannot do now?
> 
> My other comment is that this list of subcategories is far from complete and seems to be primarily for residential and offices. There are probably 1000s of additional subcategories if you expand into hospitals/medical buildings, laboratories, commercial kitchens, theaters, museums, police stations, fire stations, airports, auto repair, etc.. It is almost endless. Once the list gets long enough to capture them all, it becomes nearly impossible to find something specific. Lets say you think of a "portable fan" as simply a "fan" and look through the list of 100s of items and do not find "fan" then the user needs to think "what else could a fan be called?"
> 
> In general, I don't see a benefit to this addition.

**Comment by hongtz68** [comment]
Jason, thanks for your comments.

Brief response to your questions:
1. The end use by subcategory reporting shows up at this table with those added sub categories when selected by users:
Annual Building Utility Performance Summary - End Uses By Subcategory

The table structure is not changed, only more rows may show up if MELs categories are provided in the IDF files.

2. The MELs list is prioritized based on MELs energy use reported in EIA's Annual Energy Outlook 2017. It is not an inclusive list. Users can define new categories as needed (last choice is UserDefined which allows customization)

3. The MELs standard categorization will support tools such as Scout which uses native EnergyPlus w/o interfaces, and support modeling/analysis of MELs for BTO's MELs subprogram.

Edwin, can we have 10 to 15 minutes to discuss this at May 19's EnergyPlus Technicalities meeting?
 
> 
> The proposal is not clear, will the End Uses By Subcategory table in the Annual Building Utility Performance Summary report includes all of these predefined subcategories with zeros when the result is zero? I hope not it will make the report almost unreadable with so many extra lines. If that is not the goal, then I don't understand the reason for providing specific a specific subcategory list. What will that do that the simple string approach that is used cannot do now?
> 
> My other comment is that this list of subcategories is far from complete and seems to be primarily for residential and offices. There are probably 1000s of additional subcategories if you expand into hospitals/medical buildings, laboratories, commercial kitchens, theaters, museums, police stations, fire stations, airports, auto repair, etc.. It is almost endless. Once the list gets long enough to capture them all, it becomes nearly impossible to find something specific. Lets say you think of a "portable fan" as simply a "fan" and look through the list of 100s of items and do not find "fan" then the user needs to think "what else could a fan be called?"
> 
> In general, I don't see a benefit to this addition.

**Comment by xuanluo113** [comment]
@Myoldmopar

**Comment by amirroth** [comment]
In this example Scout _is_ the interface. I believe the point @JasonGlazer was trying to make is that there is already a facility for any client application to define end-use sub-categories which Scout can use to define the EIA typology. What is the marginal benefit of hardwiring this subset into EnergyPlus?

**Comment by hongtz68** [comment]
One significant benefit is to standardize the naming of MELs for reporting purpose (which serve other purposes, e.g., comparison of MELs energy use/efficiency/control). As Jason said before, fan as user named it, can mean different things, e.g., HVAC fan, ceiling fan, portable fan. By allowing the choice of CeilingFan and PortableFan, we try to standardize the naming; and if user will, it can be customized into any term say MyFan.

> 
> 
> In this example Scout _is_ the interface. I believe the point @JasonGlazer was trying to make is that there is already a facility for any client application to define end-use sub-categories which Scout can use to define the EIA typology. What is the marginal benefit of hardwiring this subset into EnergyPlus?

**Comment by shorowit** [comment]
If there was work being done to improve categorization of EnergyPlus outputs, I would personally prefer work done on:
- Allowing more end use subcategory fields (https://github.com/NREL/EnergyPlus/issues/7673)
- Allowing pump/fan energy to be disaggregated by heating vs cooling -- A) this is needed for a variety of calculations, like HERS/ERI, B) using EMS as a workaround becomes surprisingly complicated when dealing with a large variety of different HVAC systems, and C) this question comes up a lot (like [this Unmet Hours post](https://unmethours.com/question/54329/how-to-calculate-total-space-heatingair-conditioning-in-ep/) from less than a week ago)

These would both have larger benefits in my opinion.

**Pull request closed without merging**
