### PR TITLE
Add CalcSoilSurfTemp source, build commands, and install commands

### PR DESCRIPTION
**Pull request by Myoldmopar**
Built it locally just fine.  Steps to complete:
- [x] Verify CI is happy building it
- [x] Test a package build from CI
- [x] Add/Test Mac...
- [x] Remove binaries and such from BuildSupport

Might need to get @mbadams5 or @kbenne to assist with the Mac side, at least testing.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@kbenne, @mmatts found that this branch was building the CalcSoilSurfTemp binary, but _not_ installing it in the package.  The line that should do it is [here](https://github.com/NREL/EnergyPlus/pull/5001/files#diff-f5871afe302fe59a8f0861ee6ea25187R44).  Can we chat about this?  And maybe test it out on your Mac so we could merge this and remove our dependence on pre-built binaries?

**Comment by kbenne** [comment]
hmmm... Try explicitly rerunning cmake.

**Comment by mitchute** [comment]
I did try that. Maybe I missed something though.

**Comment by Myoldmopar** [comment]
So this still isn't placing the binary in the package, right @mmatts?  I tried to model the changes to make them just like ExpandObjects, since it is the same type of thing, so I don't know why it isn't working.  I'll try it manually on Windows as well when I get a chance.  @kbenne, earlier you said this [worked for you](https://github.com/NREL/EnergyPlus/pull/5001/#commitcomment-12309504).  Which platform was that?

**Comment by mitchute** [comment]
@Myoldmopar The only thing I'm seeing in that directory is the .bat file. This is on my Windows 7 laptop and desktop machines. It all appears to be set up correctly. e.g. the slab and basement preprocessors are being built and put in the correct directory; just not seeing this one.

**Comment by Myoldmopar** [comment]
hmmmmmmmm.... @kbenne

So I can `make package` on Linux, and I get the file in the installer:

```
_CPack_Packages/Linux/TGZ/foo/EnergyPlus-8-3-4/PreProcess/CalcSoilSurfTemp/CalcSoilSurfTemp
```

@mmatts is still not seeing it, however.  One odd thing I noted is in the output of `make package`:

```
[100%] Built target CalcSoilSurfTemp
Run CPack packaging tool...
CPack: Create package using STGZ
CPack: Install projects
CPack: - Run preinstall target for: EnergyPlus
CPack: - Install project: EnergyPlus
 +++ AutoDocs: Completed processing output variable audit: processed 3659 calls
 +++ AutoDocs: Completed processing example file summary: processed 521 example files
 +++ AutoDocs: Completed processing example file links summary: processed 521 example files
 +++ AutoDocs: Completed processing changelog: processed 58 merged pull requests
CPack: - Run preinstall target for: ExpandObjects
CPack: - Install project: ExpandObjects
CPack: - Run preinstall target for: ReadVars
CPack: - Install project: ReadVars
CPack: - Run preinstall target for: Transition
CPack: - Install project: Transition
CPack: - Run preinstall target for: Basement
CPack: - Install project: Basement
CPack: - Run preinstall target for: HVAC-Diagram
CPack: - Install project: HVAC-Diagram
CPack: - Run preinstall target for: ParametricPreprocessor
CPack: - Install project: ParametricPreprocessor
CPack: - Run preinstall target for: Slab
CPack: - Install project: Slab
CPack: - Run preinstall target for: ConvertESOMTR
CPack: - Install project: ConvertESOMTR
CPack: Create package
CPack: - package: /home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch2/builds/calcsoilsurftemp/d/EnergyPlus-8.3.4-871d548895-Linux-x86_64-Debug.sh generated.
```

The `CalcSoilSurfTemp` target is being built, but CPack doesn't seem to run for that target?  Could that lead to why it isn't ending up in the installer on Windows?  I mean I figured it would be exactly like all the other Fortran targets listed out in `make package`.  Any thoughts?

**Comment by mitchute** [comment]
@Myoldmopar I noticed the same behavior regarding Cpack on my machines.

**Comment by kbenne** [comment]
Seems like a clue. Windows is different because it is the only one that uses an "external project". This is because there is a make based (gfortran) project inside the main VS project. They are basically like totally independent projects that cmake stitches together with custom build rules. https://github.com/NREL/EnergyPlus/blob/develop/CMakeLists.txt#L183

**Comment by Myoldmopar** [comment]
So in this branch that [line](https://github.com/NREL/EnergyPlus/blob/AddCalcCoilSurfTempSource/CMakeLists.txt#L184) for this external project is replicated properly, right?

**Comment by Myoldmopar** [comment]
@mmatts, it appears @kbenne fixed it... 675662d

**Comment by Myoldmopar** [comment]
I can confirm that the last commit doesn't break anything anyway.  A fresh `make package` still includes it as before, as expected. @mmatts I'm real curious about this now on Windows.

**Comment by Myoldmopar** [comment]
@kbenne Any idea why CI started going crazy with that last commit?  I pulled develop in, but that was quite a shock.

**Comment by kbenne** [comment]
@Myoldmopar don't know but it appears your merged pulled in recent CLI changes. It is not hard to imagine those changes having complications.

**Comment by mitchute** [comment]
@Myoldmopar @kbenne It's there on Windows now.

**Comment by Myoldmopar** [comment]
Thanks @mmatts, I'll merge this if CI comes up happy.

**Pull request merged**
