### PR TITLE
Corrected a link in the readme

### PR DESCRIPTION
**Pull request by DavidHollman**
Pull request overview
---------------------
This is just a broken link in the readme file.

### Pull Request Author
n/a

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmythms** [comment]
Good catch! I'd suggest setting the PR label as Defect or Documentation.

**Comment by mjwitte** [comment]
Or maybe we need to change the wiki page name back to what it was?

**Comment by Myoldmopar** [comment]
> Good catch! I'd suggest setting the PR label as Defect or Documentation.

@jmythms just a heads up that I don't think external contributors can modify the labels, only authorized users.  I made it defect.

@DaveInCaz I can't recall, have you submitted a contributor agreement?  Even for a small typo like this we still need to make sure we are covered when taking any contribution.  I don't see it in my current documents, but I may be looking under the wrong name.  If you haven't, go ahead and check one out [here](https://energyplus.net/contributing) and get it submitted and we'll accept this directly.

Thanks!

**Comment by DavidHollman** [comment]
@Myoldmopar  I have just done so. Thanks for pointing that out.

**Comment by Myoldmopar** [comment]
Thanks @DaveInCaz , I received it and filed it.  You are now able to contribute changes, and I will accept this typo fix to kick that off.

**Pull request merged**
