### PR TITLE
Unitary System and MultiSpeed Air To Air Heat Pump Total Htg/Clg Rate sometimes zero

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #4976

AirloopHVAC:UnitarySystem Unitary System Total Heating/Cooling Rate sometimes zero when coils are operating. Also Multi Speed Air To Air Heat Pumps Unitary System Total Heating/Cooling Rate sometimes zero when the coils are operating and there are multiple heat pump in the IDF. Other variables impacted are:

Unitary System Sensible Cooling Rate
Unitary System Latent Cooling Rate
Unitary System Sensible Heating Rate
Unitary System Latent Heating Rate

Theses defects have been fixed now.

https://github.com/NREL/EnergyPlus/issues/4976

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@Nigusse As a first step, could you remove the unused variables that are being reported by CI?

**Comment by Nigusse** [comment]
@Myoldmopar OK.  I will remove the unused variables.  Diffs reported in one of the example is expected.

**Comment by Nigusse** [comment]
@Myoldmopar OK. Removed removed the unused variables, updated the branch and pushed it.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse.

**Comment by Nigusse** [comment]
The unused variable warning massage is gone. The one example that shows diffs is expected as explained above. @Myoldmopar This PR is ready for final review and merging.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@Nigusse I tried merging develop in here for you, as the only conflict was in the UnitarySystem unit test.  But the conflicts became confusing, and I wasn't able to build successfully.  I think it will be very straightforward to you.  If you can do that merge, I'll work on getting this reviewed and merged in.

**Comment by Nigusse** [comment]
@Myoldmopar I am working on the desiccant review comment, will get back to this later.

**Comment by Nigusse** [comment]
@Myoldmopar I just pulled the latest code from this branch.  Run the unit test I added separately and all unit test in debug mode, but found no issue. Did you push your merge to remote branch? If not I will merge develop and see what is going on.

**Comment by Myoldmopar** [comment]
I didn't push because I didn't do a successful merge; it's all yours.

**Comment by Nigusse** [comment]
Resolved merge conflict and transitioned "UnitarySystemPerformance:Multispeed" object in the idd snippet. All unit tests passed in debug mode.  I do not expect any issue but will wait CI machine run clean. Pushed the branch to remote.

**Pull request merged**
