### PR TITLE
Correct HPWH fan sizing

### PR DESCRIPTION
**Pull request by rraustad**
## Pull request overview

HPWH fan air flow rate sizing may not match the coil air flow rate when more than one HPWH is used in the simulation. Standards rating report is also missing in special cases.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
Issue #5560
- Somehow the standard rating report was not provided for 4 of the 6 HPWHs in the HeatPumpWaterHeater example file.
- Zone4BHPWHFan was previously sizing to 0.
- Standard ratings are now reported later in the simulation.
- Nominal Total Capacity (html) does not consider Rated Condenser Inlet Water Temperature
- HeatPumpWaterHeaterWrappedCondenser shows standard rating warning in V8.4 and this branch. Also shows tank temp at 100C at the end of standard rating. How is that possible during a rating procedure?

**Comment by rraustad** [comment]
@Myoldmopar @mjwitte This is needed for V8.5 since HPWHs were not sizing correctly or issuing standard rating report in all cases.

**Comment by rraustad** [comment]
So if Zone4BHPWHFan sized to 0, why is the performance the same?

```
Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, Design Size Maximum Flow Rate [m3/s], 0.00000
Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, Design Size Maximum Flow Rate [m3/s], 0.20140
```

hpwhexamplefile

**Comment by rraustad** [comment]
Oh, it wasn't the flow rate that sized to 0, it was the design flow rate that was 0. The fan flow was hard sized.

```
Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, Design Size Maximum Flow Rate [m3/s], 0.00000
Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, User-Specified Maximum Flow Rate [m3/s], 0.26850

Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, Design Size Maximum Flow Rate [m3/s], 0.20140
Component Sizing Information, Fan:OnOff, ZONE4BHPWHFAN, User-Specified Maximum Flow Rate [m3/s], 0.26850
```

**Comment by rraustad** [comment]
Looks like something else is wrong.

**Comment by rraustad** [comment]
The Nominal Total Capacity is changing in the html because the HPWH condenser inlet water temp has changed, from 60C to 57.2C in the case of Zone4HPWHDXCoil. Oddly, both these temps are different than the rated water inlet temp. The rated evaporator inlet air dry-bulb/wet-bulb temperatures are both used during sizing, however the rated water temperature is not. The only thing the rated water temperature is used for is to validate the performance curves. I think it would be beneficial to include the rated water temp in sizing so if someone changes that value, there is an impact on sizing.

```
Coil:WaterHeating:AirToWaterHeatPump:Pumped,
  Zone4HPWHDXCoil,         !- Name
  4000.0,                  !- Rated Heating Capacity {W}
  3.2,                     !- Rated COP {W/W}
  0.6956,                  !- Rated Sensible Heat Ratio
  29.44,                   !- Rated Evaporator Inlet Air Dry-Bulb Temperature {C}
  22.22,                   !- Rated Evaporator Inlet Air Wet-Bulb Temperature {C}
  55.72,                   !- Rated Condenser Inlet Water Temperature {C}

Coil:WaterHeating:AirToWaterHeatPump:Pumped,
  N6 , \field Rated Condenser Inlet Water Temperature
    \type real
    \units C
    \minimum> 25
    \default 57.5
    \note Condenser inlet water temperature corresponding to rated coil performance
    \note (heating capacity, COP and SHR).
```

**Comment by rraustad** [comment]
@mjwitte @EnergyArchmage @Myoldmopar Not sure if Mike/Brent see the questions without specifying their name. See last comment regarding rated inlet water temp. I have corrected sizing to include rated condenser inlet water temp.

**Comment by rraustad** [comment]
Revised use of HPWH condenser water inlet temp during standard rating procedure. Only reset to standard rating temperature once in case coil was sized.

**Comment by rraustad** [comment]
This is ready for review.
- The 1 error file shows the error changed places.
- The eio files show mostly added reports for HPWH standard rating and location changes for output with 1 fan that shows corrected "design" air flow rate (fan flow was had-sized).
- Html files show differences in coil sizing since the rated condenser water inlet temp is used instead of the plant temperature.

**Comment by Myoldmopar** [comment]
It's not really great that the CalcStandardRatings relies on you to, somewhat arbitrarily, place the right temperature at the inlet node.  It would be much nicer to just pass in the required rated conditions to the function and have it use those.  I realize that is out of scope for this, just noting for the future.  Thanks for the quick fix here, @rraustad!

**Pull request merged**
