### PR TITLE
Upgrade to C++17 std::filesystem library

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

This is a NFP to upgrade `FileSystem` to use C++17 `std::filesystem` instead of relying on macros to call OS-specific functions, 

example: https://github.com/NREL/EnergyPlus/blob/7f35ab639d5a75b6e090a0db19ec83c3f0199025/src/EnergyPlus/FileSystem.cc#L258-L266

This potential upgrade was discovered via #8376. A minimal fix that doesn't use `std::filesystem` was made in #8410 and it is now proposed to make it a larger defect and do the upgrade to `std::filesystem`.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by Myoldmopar — COMMENTED** [review]
I personally love this idea, and frankly would not mind going all the way to # 2 and using fs::path everywhere.  The more we can push toward standard library and standard practice things, the lower the barrier for bringing on new devs, and in most cases at least, the lower our maintenance. 

I am curious about those handful of other places that use FileSystem.hh, most importantly the Schedule:File handling and the Python Plugin handling.
But I would love to know what others think.

**Comment by Myoldmopar** [comment]
With a stray FileSystem unit test failing spuriously for me, I'm even more inclined to push for full `std::filesystem` implementation to reduce our maintenance with file system operations.  Anyone else have comment?  I'm also inclined to go ahead and push toward using the `std::filesystem::path` in the codebase to make it more familiar to modern C++ developers.

@jmarrec if you don't hear any reason why we **shouldn't** move to the standard C++ FileSystem library, then please proceed to fix this issue.  And consider the unit test failure another defect that this will resolve (https://github.com/NREL/EnergyPlus/issues/8430)

**Comment by Myoldmopar** [comment]
@jmarrec no one has provided any reason to not push ahead and just bring in full file system library support.  Please go ahead and do that.

**Comment by jmarrec** [comment]
@Myoldmopar I'm on it.

**Comment by jmarrec** [comment]
Superseeded by #8480

**Pull request closed without merging**
