### PR TITLE
For non-convex quad fix triangles chosen for proper centroid calculation to avoid unrealistic z values

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #5497 
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte the one file that is showing the new warning message is the 5ZoneGeometryTransform.idf file that contains the GeometryTransform object which is processed in the TransformVertsByAspect() routine. The issue is happening because the GrossArea of the surfaces is computed prior to the application of the GeometryTransform. In each place that the GrossArea is computed right after the CreateNewellAreaVector() call, the call to TransformVertsByAspect happens later. It happens in several places in SurfaceGeometry. This does not make much sense to me but maybe I am not understanding the bigger picture. Do you know why those two calls are in the order that they are?

**Comment by mjwitte** [comment]
Not sure.  Does TransformVertsByAspect need the GrossArea info to do the transform?  Perhaps TransformVertsByAspect needs to re-compute GrossArea?  And possibly other surface properties?  What about the "length" and "width" that get reported in the surface details report?

**Comment by JasonGlazer** [comment]
No, it just uses and changes the vertex() array.

**Comment by mjwitte** [comment]
If you run 5ZoneGeometryTransform with and without the transform, do the various surface reports look correct?  Both table and eio surface details.

**Comment by JasonGlazer** [comment]
The speed seems slow so I am going to merge it again and see how the performance tests go. The 1 failing file, 5zoneGeometryTransform.idf is a known issue and #5849 was posted about it.

**Comment by JasonGlazer** [comment]
This pull request got messed up by merging two active branches by accident. Starting a new branch and pull request. #5852

**Pull request closed without merging**
