### PR TITLE
Use StdRhoAir to calculate OA mass flow rate for consistency

### PR DESCRIPTION
**Pull request by lgu1234**
## Pull request overview

Addresses #5366.

Use StdRhoAir to calculate outdoor air mass flow rate for consistency, instead of current air density from a node.
The same issue is found in DualDuct::CalcOAMassFlow and DualDuct::CalcOAOnlyMassFlow. A new issue will be created.

Differences were found in 5ZoneAutoDXVAV.idf as expected.   
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@mjwitte @lgu1234 @lgentile it has been 16 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
It looks like there is a crash in HospitalLowEnergy.  It only appears on the debug build leading me to think we have an array out-of-bounds type of crash.

**Comment by lgu1234** [comment]
@Myoldmopar My changes should not impact a crash with array out-of-bounds in HospitalLowEnergy.idf. Since this branch is 334 commits behind. Let me merge the branch and see what happens.

**Comment by lgu1234** [comment]
@Myoldmopar After merge, CI results are all green. It is ready for review.

**Comment by mjwitte** [comment]
@Myoldmopar OK to close #5366?

**Comment by Myoldmopar** [comment]
I'm sure, i think i was merging that from my phone after ci was done, as i
am now..., so i probably forgot to grab the issue too.

**Pull request merged**
