### PR TITLE
Put EP into a single static lib again

### PR DESCRIPTION
**Pull request by Myoldmopar**
Addresses #5368 
This builds fine locally on my Mac.  I believe it will build fine on others.  The hack lines that sorta forced energypluslib and energypluslib2 were removed, which is nice, but it would be awesome if @jasondegraw could test on MinGW to verify.  If everything is clean, this should merge right in to make the lives of IDE-based devs easier...

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Let's not merge until we confirm build times on Win VS.

**Comment by jasondegraw** [comment]
@Myoldmopar  I haven't tested anything, but MinGW (gcc 4.9.1, 32 bit) successfully builds it.

**Comment by Myoldmopar** [comment]
@mjwitte According to the dashboard, the 64-bit Windows build is right on track with the rest of the builds of the same machine.  @mbadams5 PC0... machines are a little slower than the W7-VM-1 machines consistently, and this build is right in line.  The 32-bit build for this branch is actually the fastest build on the dashboard for Windows.  Do you want more testing than these CI results?  I can hold a drag race between develop and this branch I guess...it's in my handle's heritage...

**Comment by mjwitte** [comment]
@Myoldmopar I'd like to try it locally.  Rebuild develop and then rebuild this branch - debug and release.

**Comment by Myoldmopar** [comment]
OK sounds good.  If you are happy with the changes and the results of your build test, go ahead and merge.

**Comment by mjwitte** [comment]
Build times with uni-lib vs dual-lib are similar on Windows with VS Express 2013, maybe even a little faster with uni-lib.

image

Merging.

**Pull request merged**
