### PR TITLE
Address IDD errors in CI

### PR DESCRIPTION
**Pull request by nealkruis**
@Myoldmopar @kbenne Moving discussion on https://github.com/NREL/EnergyPlus/issues/4700 here. Currently waiting on CI for results.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@nealkruis The readlink function is returning a stray trailing character.  Here is the output from gdb right after it gets called:

```
(gdb) p executableRelativePath
$1 = "/home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch4/builds/iddpath/d/Products/energyplus-8.2.8\177", '\000' <repeats 18 times>, "\001\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\300\247\377\367\377\177\000\000\001\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\300\247\377\367\377\177\000\000\001\000\000\000\377\177", '\000' <repeats 18 times>...
```

So, it has the actual path, followed by the invalid ```\177```, followed by a null (repeated 18x), then blah blah.  The string gets trimmed down to the first null character properly, but it includes this stray character from random memory in the actual path since it is before the first null.  I looked into the call to readlink and don't see anything wrong.  Maybe @kbenne or @lefticus would have some thought here.  I'm sure once we get this path right everything will go green again.

**Comment by nealkruis** [comment]
@Myoldmopar Yeah, I was just looking into this. The funny thing is that it only happens for the coverage tests. 

@lefticus Is there anything different about the coverage tests that might cause this? Is there a way to test the coverage tests on my ubuntu machine?

**Comment by Myoldmopar** [comment]
There is a CMake flag ```ENABLE_COVERAGE```, but I'm not using it.  I'm just doing a simple debug build when I saw that inside gdb.  I'm not sure what's going on with it only showing up on the CI coverage tests, but I think it is really super random.  Like if the memory happens to be null there, it'll work fine.

**Comment by Myoldmopar** [comment]
Hmmm, well, I ran that binary that I was debugging and found that it actually ran to completion.  I had jumped right into the debugger to see that path issue.  Maybe it's part of the randomness, I don't know.  In any case, I am building with ENABLE_COVERAGE to see if I can get the issue to appear.

**Comment by lefticus** [comment]
@nealkruis @Myoldmopar 

The documentation for `readlink` explicitly says "does not append a null" so this line of code is basically guaranteed to return wrong data: https://github.com/NREL/EnergyPlus/blob/issue-4700-idd-file-directory/src/EnergyPlus/FileSystem.cc#L122

You need to at least change that to (or maybe something smarter and more generic for all platforms):

    return std::string(executableRelativePath, len);

http://linux.die.net/man/2/readlink  

>  readlink() does not append a null byte to buf

**Comment by nealkruis** [comment]
The answer [here](http://stackoverflow.com/questions/5525668/how-to-implement-readlink-to-find-the-path) shows hardcoding the last character to `'\0'`. I'll pass this by the CI and see if it cleans things up.

**Comment by nealkruis** [comment]
@Myoldmopar that seems to have fixed the problem. I don't know what the change in the *.eio is about, but it seems to be unrelated. You comfortable merging this?

**Comment by mjwitte** [comment]
@nealkruis I merged PR #4642 on Sunday which changed a bunch of field names which show in the eio sizing outputs.  So, may be best to merge develop in here to get a clean report.

**Comment by nealkruis** [comment]
Thanks, @mjwitte. I'll take care of it.

**Comment by Myoldmopar** [comment]
@nealkruis Looks like it is going to be fine; Clang is now clean.  I'll merge when CI does a few more.  Thanks for this fix.

**Pull request merged**
