### PR TITLE
Fix Vertex array size when a coincident vertex is dropped

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Address #6995. It's not clear to me that this problem was triggered by the changes in #6853, because the defect file does not seem to hit that section of the code.

The defect file is large and takes about 2hrs to run on my machine, so I've put zips of outputs in EnergyPlusDevSupport\DefectFiles.
Note that the 6995-SmallerDefectFile.idf runs quickly and exhibits the symptom, but it did not cover all the bases. An initial fix allowed 6995-SmallerDefectFile to run, but the user file failed in other places. So, the fix had to be expanded to two other places to get the user file to run to completion.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 @Myoldmopar This is ready for initial review. See comments at top regarding defect files. I *had* a full output for the user file and then overwrote it, so it's running again now. I"ll post the zip of outputs when it's done (takes about 2 hrs).

**Comment by mjwitte** [comment]
I'll think about a unit test for this.

**Comment by Myoldmopar** [comment]
Thanks for the quick fix on this @mjwitte; I'll watch for the outputs.  It looks like we might have a couple of issues that we should fix and create a 9.0.1 release.  Oh, and Gort has really been struggling.  Don't sweat his unhandled exceptions.  I'm able to build successfully on my CI instance.  And I am in the process of upgrading the CI system anyway.

**Comment by lgu1234** [comment]
@mjwitte I tested 6995-SmallerDefectFile.idf with debug on my local computer and worked as expected.

I have a concern for future. We use 0.01 as a distance check between two points. It may not be user's intent. We may allow an input of distance limit and use 0.01 as default.

**Comment by lgu1234** [comment]
@mjwitte I also tested 6995-SmallerDefectFile-SingleZone.idf. It worked as expected.

**Comment by mjwitte** [comment]
@Myoldmopar @lgu1234 Just added a zip of outputs for the user file with v9.0 after this fix.  So, you can compare v8.9 vs v9.0 before fix (fatal) vs v9.0 after fix.

**Comment by lgu1234** [comment]
@mjwitte @Myoldmopar I added one more line in Revised_V890.idf: Output:Diagnostics, DisplayExtraWarnings; and ran it again. Uploaded is an err file as Revised_V890 WithDisplayExtra.err. Then I compare both files of Revised_V890 WithDisplayExtra.err and Revised-FixSetpoinsAfterFix.err. They are very compatible.

**Comment by Myoldmopar** [comment]
This looks great.  Error file from 8.9 to after fix looks similar.  Compared some outputs in the csv data and they match up well.  CI is generally happy except for the Ubuntu issue (which I have a fix for, w00t!).  I'm inclined to merge this in so we can try to re-release today.  Any issues with that @mjwitte ?

**Pull request merged**
