### PR TITLE
New fan input object Fan:SystemModel

### PR DESCRIPTION
**Pull request by EnergyArchmage**
This is for adding an entirely new fan input object, called Fan:SystemModel, that serves as a direct substitute for Fan:VariableVolume, Fan:ConstantVolume, or Fan:OnOff. In addition it incorporates input for night ventilation operation mode so that a separate FanPerformance:NightVentilation is not required when using the night ventilation availability manager. The core fan model is not significantly changed, but rather the simple (not component model) model variants are all available within a single input object.  The exception is that for fans with discrete speed levels, the power calculation will be done using a time-weighted method instead of a flow-weighted method. Also, motor losses that do not get added to the air stream can be rejected to the surrounding thermal zone if desired. 

The older fan objects will be retained for some number of release cycles with the plan that they will eventually be deprecated and transitioned to use the new fan object. There is no transition forcing a change to use the new Fan:SystemModel ( though it will be possible to transition files eventually). 

This is a large project with 105 file changes, github browser can't show all the diffs.  The new fan is made available in a wide variety of places in EnergyPlus, but not quite everywhere.  Here is a list of parent objects with fans that did _not_ get changed to allow new fan:

AirLoopHVAC:Unitary:Furnace:HeatCool
AirLoopHVAC:UnitaryHeatCool
AirLoopHVAC:UnitaryHeatPump:AirToAir
AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed
AirLoopHVAC:Unitary:Furnace:HeatOnly
AirLoopHVAC:UnitaryHeatPump:WaterToAir

Also the new fan was not propagated for use with AirflowNetwork. 
### CI testing "failures" summary

Hundreds of RDD diffs:  Output Variable called "Fan Air Mass Flow Rate [kg/s]" was added to the legacy fan models as well as the new fan model.  This affects RDD files, every testfile with a fan is expected to have a changed RDD file.

30 existing example files have been changed to use the new fan.  Many of these show in CI robots as test failures.  The only test failures are in test files that were changed to use the new fan. This is expected to throw table and eio diffs because the new fan does more reporting design maximum electric power and changes the count for number of input fields.  

Here are notes on individual files showing as failures:  
- StripMallZoneEvapCoolerAutosized (very tiny results diffs, expected changes from new object )
- UnitarySystem_DXCoilSystemAuto ( small changes , expected changes from new object )
- UnitarySystem_HeatPumpAuto (0.01% change in annual fan energy)
- UnitarySystem_MultiSpeedCoils_SingleMode ( 0.08% change in annual energy)
- DesiccantDehumidifierWithCompanionCoil  ( some small diffs in cooling and heating energy )
- FanCoilAutoSize_MultiSpeedFan (Fan substituted with three speed levels and discrete power fractions and so fan power during operation is expected to be different)
- 5ZoneSupRetPlenVSATU (lots of diffs, issue #5592 fixed with this and changes are expected,  runs better now)
- HeatPumpWaterHeater and HeatPumpWaterHeaterStratified (HPWHSCHEDULEDDXCOIL capacity is 38W different, refactoring out FanElecPower fixed a HPWH fan identitiy issue along the way, this is issue #5630) 
- PackagedTerminalHeatPump (some small 0.002% changes in fan energy, exact match not expected because of the different formulation for combination power curve from legacy on/off fan power and fan eff curve )
- PackagedTerminalHeatPumpVSAS  (some  changes 0.12% in fan energy, exact match not expected because of the different formulation for combination power curve from legacy on/off fan power and fan eff curve )
- UnitarySystem_WaterCoils_wMultiSpeedFan ( small 0.1% change in annual fan energy, exact match not expected because of changes in multispeed calculation )
- 5ZoneNightVent3  (just expected diffs from object change, some very tiny diffs)
- HVACStandAloneERV_Economizer (just expected diffs from object change)
- OutdoorAirUnit (just expected diffs from object change)
- PackagedTerminalAirConditioner (just expected diffs from object change)
- PackagedTerminalAirConditionerVSAS (just expected diffs from object change)
- VentilatedSlab (just expected diffs from object change)
- VariableRefrigerantFlow_5Zone (just expected diffs from object change)
- UnitHeaterAuto (just expected diffs from object change)
- UnitVent5ZoneAuto  (just expected diffs from object change)
- PIUAuto (just expected diffs from object change, fixed "HOURLYP" )
- VSHeatPumpWaterHeater (just expected diffs from object change)
- WaterHeaterHeatPumpStratifiedTank (just expected diffs from object change)
- WaterHeaterHeatPumpWrappedCondenser (just expected diffs from object change)
- UnitarySystem_5ZoneWaterLoopHeatPump  (just expected diffs from object change)
- UnitarySystem_VSHeatPumpWaterToAirEquationFit (just expected diffs from object change)
- UnitarySystem_FurnaceWithDXSystemRHcontrol (just expected diffs from object change)
- WindACAuto     (just expected diffs from object change)
- ZoneWSHP_wDOAS   (just expected diffs from object change)
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by EnergyArchmage** [comment]
Once the legal excuses go away for this, the c++ refactoring design needs some serious review --  for example reuse of integer index over some smart pointer.  I am happy to merge this up if it is headed in a good-enough direction.

**Comment by jasondegraw** [comment]
@EnergyArchmage My browser goes bonkers trying to look at the diff, but I'd be happy to do a review. I'm going to want to propagate this over into AirflowNetwork ASAP, so it'll be helpful for me to have a look now.

**Comment by EnergyArchmage** [comment]
Replacing with PR #6014

**Comment by Myoldmopar** [comment]
This one goes away then @EnergyArchmage ?

**Comment by EnergyArchmage** [comment]
yes, past mark of mouth; web browsers can't always load the github pages.

**Comment by Myoldmopar** [comment]
> past mark of mouth

!!!  That is some nice _gewintred_ vocabulary from the 1850s.  OK then I will close this.  But I'll wait a few minutes so I don't get too ahead of things clicking these buttons 😉

**Comment by mjwitte** [comment]
Superceded by #6014. Closing.

**Pull request closed without merging**
