### PR TITLE
Improve Spaces example file and implement DesignSpecification:OutdoorAir:SpaceList everywhere

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Completes implementation of DesignSpecification:OutdoorAir:SpaceList anywhere that DesignSpecification:OutdoorAir can be used.
 - Fixes a Construction:AirBoundary bug (failed if the object was shortened to just a name).
 - Fixes space assignments for subsurfaces.
 - Fixes using SpaceList to assign internal gains.
 - Adds features to example file 5ZoneAirCooledWithSpaces. Complete list of Space features in this example file:
   - Zone 5 has 2 floor surfaces defined to create 2 spaces: Space 5 Conference and Space 5 Office (all other surfaces are auto-assigned to space=Zone 5-Remainder).
   - Zone 5 is all one enclosure=Zone 5.
   - Zone 3 is divided into 3 spaces with fully defined surfaces: Space 3 Storage, Space 3 Open Office 1, Space 3 Open Office 2
   - Space 3 Storage is its own enclosure
   - Space 3 Open Office 1 and Space 3 Open Office 2 are connected with an air boundary wall, so they are in the same enclosure=Solar Enclosure 1.
   - Internal gains are assigned using Zone, ZoneList, Space, and SpaceList.
   - Zone 5 uses a DesignSpecification:OutdoorAir:SpaceList.

image

Expecting no diffs, except for 5ZoneAirCooledWithSpaces because it was showing zero OA before and many changes have been made to this example.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
1 diff on CI, as one would expect.  I'll check out the changes here and run the modified file locally with latest develop pulled in to get this on the path toward merging.

**Comment by Myoldmopar** [comment]
Build and unit tests pass nicely locally.  The updated example file now has this in the ERR file:

```
   ** Warning ** GetSurfaceData: CAUTION -- Interzone surfaces are occuring in the same zone(s).
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual occurrences.
   ** Warning ** CalculateZoneVolume: 1 zone is not fully enclosed. For more details use:  Output:Diagnostics,DisplayExtrawarnings; 
   ** Warning ** GetInternalHeatGains: People="ZONE 5-Remainder ZONELIST PEOPLE", specifies People per Floor Area, but Space Floor Area = 0.  0 People will result.
```

Seems concerning...did you expect this @mjwitte ?  I'm guessing no, but just let me know if you need anything from me on this.  I will consider merging this with a warning in the ERR file if that issue is purely an IDF mistake and nothing needs to change in the code.

**Comment by Myoldmopar** [comment]
OK, so this is as intended, but can be cleaned up later with a code change.  I'm going to merge this in tomorrow unless someone really wants to hold it up.

**Comment by rraustad** [comment]
NO, merge this in.

**Pull request merged**
