### PR TITLE
Add residential simulation test file

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
 - Try to catch more issues up front that may affect our residential models.
 - Expecting this to fail until https://github.com/NREL/EnergyPlus/pull/10768 is merged.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by shorowit** [comment]
Am I supposed to add the filename to [testfiles/emall.list](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/emall.list) too? I have no idea what that file is for, I don't see any references to it.

**Comment by mjwitte** [comment]
> Am I supposed to add the filename to [testfiles/emall.list](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/emall.list) too? I have no idea what that file is for, I don't see any references to it.

Given the history on that file I'd say no. @Myoldmopar Is that file obsolete?

**Comment by Myoldmopar** [comment]
> > Am I supposed to add the filename to [testfiles/emall.list](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/emall.list) too? I have no idea what that file is for, I don't see any references to it.
> 
> Given the history on that file I'd say no. @Myoldmopar Is that file obsolete?

Good question, and yes, it is obsolete.  Hasn't been used in quite some time. 

I'll pull develop in and this should be passing and ready to merge later this morning.  Thanks @shorowit !

**Comment by Myoldmopar** [comment]
This still failed, even with develop pulled in...   I'll take a look but @shorowit if you have any thoughts that might speed up my investigation, that would be great.

**Comment by Myoldmopar** [comment]
```
    Start 760: integration._ResidentialBase
1/2 Test #760: integration._ResidentialBase ................***Failed  Error regular expression found in output. Regex=[Test Failed]  0.15 sec
EnergyPlus Starting
EnergyPlus, Version 24.2.0-aacaefade0, YMD=2024.09.30 10:25
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
EnergyPlus Run Time=00hr 00min  0.03sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.
Test Failed
```

**Comment by Myoldmopar** [comment]
Oh lol, there was a line at the header of the IDF that wasn't commented properly.  That took care of it...pushing it up shortly.

**Comment by Myoldmopar** [comment]
OK, GHA is back to happiness again on this branch.  Decent is running, so I think I'll let it continue before merging this later today.  Unless there are more PRs needed in this patch, I will plan on tagging v24.2.1-RC1 right after that, getting some testing done, and releasing 24.2.1 tomorrow if everything is happy.  Thanks @shorowit

**Comment by Myoldmopar** [comment]
Decent finally finished, but it seemed to take a really really long time relative to other CI runs.  I did not notice any issue when I was doing my testing.  I restarted the CI machines and deleted the long build result file so that it would re-run.  Assuming it comes back in reasonable time, this can go in.

**Pull request merged**
