### PR TITLE
Updating Site:GroundDomain:Slab/Basement Error Messages

### PR DESCRIPTION
**Pull request by mitchute**
Addresses #5073. Error messages did not reflect the generalized nature of the code. This has been updated so users can more easily diagnose input errors.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mitchute, there are build warnings coming up due to an implicit type conversion.  The message is coming from the gtest source, which indicates to me that the arguments you are passing to one of the EXPECT_EQ or EXPECT_NEAR or EXPECT_FALSE are not exactly a match.  Maybe an accidental passing integer to EXPECT_FALSE for example.  Can you take a quick look?  If so we'll merge this right in.

**Comment by mitchute** [comment]
@Myoldmopar I'm checking bools in the [unit tests](https://github.com/NREL/EnergyPlus/blob/5073_GroundDomainErrorMessage/tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc#L146). Is there some other way that I need to initialize `ErrorsFound`?

**Comment by mitchute** [comment]
@Myoldmopar I updated the unit tests. Hopefully that will clear it up.

**Comment by Myoldmopar** [comment]
Interesting.  We'll see!

**Pull request merged**
