### PR TITLE
Fix incorrect "other" row ABUPS end-used by subcategory table

### LINKED ISSUE #7556: "Other" heating subcategory appears (incorrectly)
Issue overview
--------------
See IDF below where >12 GJ of energy appears in an "Other" heating subcategory in the End Uses By Subcategory output table. The subcategory is being automatically created. Across several hundred test IDFs, this is the _only_ file where this subcategory appears. In every other test file, heating energy correctly shows up in the "General" subcategory. (This particular test file includes a complex set of HVAC systems serving a single conditioned zone.)

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3725469/in.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - Version 9.2.0-921312fa1d

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #7556 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Note: the branch for this pull request was copied from another branch to rectify some GitHub weirdness. The original PR was #7693

**Review by mjwitte — APPROVED** [review]
Tested defect file and confirmed fix. Ran unit tests locally. 
Merged in develop and resolved yet another conflict.
Will wait for CI results before merging - want to confirm that the extra meters are slowing things down.

**Comment by JasonGlazer** [comment]
The same three files are "failing" which are as expected.

**Comment by mjwitte** [comment]
@JasonGlazer Thanks. I'm waiting on a full set of CI results before merging. Primarily to be sure the extra meters aren't causing a slowdown in performance.

**Comment by Myoldmopar** [comment]
Very small performance penalty, I'm not sure it's worth investigating at the moment.  You can open up a ticket to follow-up on this and try to optimize some code to balance the penalty back out after freeze if you want.

**Comment by mjwitte** [comment]
And it looks like the [format checker errors](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-55a31aa62b00cf045b2989635becd9bce786ad1e-x86_64-Linux-Ubuntu-18.04-custom_check.html) are all from the coil refactor? Nor related to this PR.

**Pull request merged**
