### PR TITLE
Use hg to report latent load instead of hfg in AirflowNetwork

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
When Cp is used to report sensible load as

Sen = mdot * Cp * DeltaT

the latent load should be reported using hg instead of hfg as 

Lat = mdot * hg * DeltaW

so that a sum of sensible and latent loads is equal to

Total = mdot * DeltaH

A test file is provided to show differences of results. The unit test also proves the above conclusion.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
I recently found my 10-foot cattle prod. So I guess I should ask, is this ready for review?

**Comment by lgu1234** [comment]
@mitchute Yes. It is ready for review.

**Comment by mitchute** [comment]
@lgu1234 this looks good. I made a few minor cleanups in https://github.com/NREL/EnergyPlus/pull/7860/commits/b801ee5771ff91cd24af6d3d1220f7cbd39b1926, but other than that this looks straightforward. 

@mjwitte @Myoldmopar It appears that the output variables affected here do not appear in the test suite. In situations like this should they be added somewhere? I'd assume that we want at least one file to compare these results FFR.

**Comment by mjwitte** [comment]
@mitchute Yes on adding these outputs to at least one existing example file.

**Comment by mitchute** [comment]
OK, I'll add them somewhere.

**Comment by mitchute** [comment]
These results look reasonable and the minor AUD and MTD diffs are expected. Merging.

**Pull request merged**
