### PR TITLE
Global PlantPipingSystemsMgr

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Moves the following namespaces to state:
   - PondGHE
   - GlobalNames
   - PlantPressureSystems
   - PlantPipingSystemsManager
   - PlantManager
   - PlantHeatExchangeFluidToFluid
   - PlantLoadProfile
   - PlantUtilities
   - HeatPumpWaterToWaterSimple
   - HeatPumpWaterToWaterCooling
   - HeatPumpWaterToWaterHeating
   - FluidCoolers
   - FuelCellElectricGen
   - IceThermalStorage

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mitchute any thoughts on what change is causing the big math diff before I review this?

**Comment by mitchute** [comment]
I was surprised by that one, but I haven't had a chance to dig into it yet.

**Comment by mitchute** [comment]
@Myoldmopar the diffs we're seeing across multiple branches from ```PythonPlugin1ZoneUncontrolledCondFD.idf``` was due to a problem with #8417, where the report variables for conductivity and specific heat were never being initialized to 0. I went ahead and fixed it here: 69611b1599e777a1e0e0d315b08aed2f2c0be96c. Once this goes in, we should be back to zero (unexpected) diffs.

**Comment by Myoldmopar** [comment]
Awesome!  OK, as soon as CI reports back, this can merge in.

**Comment by Myoldmopar** [comment]
The diff is actually fixed in this branch now, so merging this in will clean that up for future runs.  This is good to go.  Thanks @mitchute !

**Pull request merged**
