### PR TITLE
Updating the error messages. I missed these when I cleaned up issue #466...

### PR DESCRIPTION
**Pull request by mmatts**
...0.

 I missed these earlier...

### CODE REVIEW

**Comment by mmatts** [comment]
@Myoldmopar This should be the end of this one, I hope.

**Comment by Myoldmopar** [comment]
I'm going to kill the Ubuntu integration test results and re-run and see if it shows failures again.

**Comment by Myoldmopar** [comment]
@mmatts Not sure what is going on with CI up there, I merged develop.  If it is clean, I'll merge this in right away.

**Comment by Myoldmopar** [comment]
omg so green...

**Pull request merged**
