### PR TITLE
#4833 Changes to documentation

### PR DESCRIPTION
**Pull request by rraustad**

### CODE REVIEW

**Comment by mjwitte** [comment]
@rraustad I/O Ref looks good (I checked in a missing apostrophe), but the Engineering Ref needs similar changes.

**Comment by mjwitte** [comment]
@rraustad Added another sentence or two to the end of the AirLoopHVAC:UnitarySystem intro regarding use as a coil-only component.  Please review and edit as needed.  Otherwise everything else in here looks good.

**Comment by rraustad** [comment]
Yes, those sentences are true. The only other thing I see is at line 5886 "Other temperature set control may also be used." Not sure it's worth another check in to slightly reword this sentence.

**Comment by mjwitte** [comment]
@rraustad Fixed that sentence.  Merging.

**Pull request merged**
