### PR TITLE
Upgrade nlohmann json for string view

### PR DESCRIPTION
**Pull request by lefticus**
Upgrades to nlohmann::json 3.11.2, which includes native support for `std::string_view` lookup keys.

This should allow for a measurable performance improvement around the use of JSON and the Schema.

This PR has moved to 3.11.2 and has started the process of piping `std::string_view` through more places where possible.

It should be mergeable, but is not yet ideal.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@lefticus if you happen to have a chance, could you offer some tip as to why this build is failing across the board?  I'd love to try to push on this myself soon before it gets lost, and I could figure it out, but you may be able to immediately identify the issue and save some time.

**Comment by nrel-bot-2** [comment]
@lefticus @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@lefticus @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@lefticus @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I took a few minutes and tried to get this branch going.  One thing that seems to be weird is that the JSON library's "constructor from initializer list" is creating lists instead of hashes.  So then trying to access the elements by index is failing.  I tried fixing a few instances in the unit tests where we are manually creating JSON objects from nested initializer lists, and it would get further before once again failing.  I am not going to take any more side time.  

@mbadams5 @jasondegraw I would have thought this would be an easy simple win.  Nlohmann already did the work to allow string views as lookup keys, so it seems like we could just take advantage of it.  I'd love to use it moving forward but I'm not so sure now.  If either of you have any thoughts I'd be happy to hear them.  But for now I'm going to close this PR, leaving the branch in place.

**Pull request closed without merging**
