### PR TITLE
Fix issue with VRF Heat Pump COP and Electricity Rate

### LINKED ISSUE #9252: Issue with VRF Heat Pump COP and Electricity Rate
Issue overview
--------------
In the attached EnergyPlus example with VRF system object "AirConditioner:VariableRefrigerantFlow", I found the output variable VRF Heat Pump COP is very low and Electricity Rate very high. In this model, the user specified Rated Cooling COP is  2.753. However, in the calculation output, the COP for July 16 is less than 1.9 for the whole day, even though the outdoor air temperature is much lower than the rating condition outdoor air temperature of 35 C. 

In the attached Excel spreadsheet file, I did a manual calculation of the VRF unit COP and electricity rate based on the performance curves and compared with the EnergyPlus output. Based on the results, I think the RHS of the following two equations should multiply the "VRF Heat Pump Part Load Ratio", though I am not sure which variable it corresponds to in the source code.

https://github.com/NREL/EnergyPlus/blob/0474bcff0f09143605459c4168e69a17d49e7dd1/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L1183-L1184

https://github.com/NREL/EnergyPlus/blob/0474bcff0f09143605459c4168e69a17d49e7dd1/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L1205-L1206

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10 64 bit)
 - Version of EnergyPlus (EnergyPlus 9.6)
 - Unmethours link or helpdesk ticket number: N/A

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
1.  [DOASDXCOIL_wADPBFMethod.idf](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DOASDXCOIL_wADPBFMethod.idf)
2. [DOASDXCOIL_wADPBFMethod_9.6_ManualCalculation.xlsx](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DOASDXCOIL_wADPBFMethod_9.6_ManualCalculation.xlsx)
 - [ ] Ticket added to Pivotal for defect - N/A
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Tentative fixes #9252
 - After some investigation, the problem pin-points to the VRF cooling electricity calculations. It is believed that the part load ratio (CoolingPLR) should be included in the expression to scale down values for the part load conditions. 
 - The same fix should be applied to the heating electricity energy calculations (via HeatingPLR) as well. 
 - Some additional thoughts: there are also some thoughts about whether the electricity energy related crank case heater, evaporator/condenser pump, and defrost operations should also be discounted by the same PLR ratios as well. However, this seems to be complicated, in that 1) the other equipment might not need to be scaled down by PLR (depending on the detailed physics happening there); and 2) the scale might not be a simple linear scaling, if any scaling/discount should be considered in some cases (also depending on the detailed physics happening there).
- Also includes a few additional minor changes in the code/comments for clarity/consistence; and a few corrections in related sections in the IORef documentation. 
- Some further updates / corrections have also made on the IORef and Engineering Reference. 

After undergoing some investigation and discussions (in the original issue post and also via email with other developers (thanks @mjwitte)), this issue should be rooted on how the EIRFPLR curve was generated. The latest version of the VRF implementation adapted the definition used in the Chiller:Electric:EIR model, which defines that the curve was defined or obtained using the full capacity as the basis:
image

This sense, the current code (for v22.2) does not really need a change. Although it is suggested to add a clear message to the IORef for VRF section inputs about how this curve should be used similar to the Chiller:Electric:EIR IORef entries above. Currently, the following texts have been added to the VRF section, using some language revised form the EIR chiller model:
```
This curve is generated by dividing the operating electric input power by the available full-load capacity (do not divide by load) at the specific operating temperatures. The output of this curve is multiplied by the reference full-load EIR (inverse of the reference COP) and the other EIR Curves (e.g. EIR as Function of Temperature Curve, EIR Defrost curve etc) to give the EIR at the specific temperatures and part-load ratio at which the equipment is operating.
```

Also, the original issue report seems to stem from the recent change of the VRF model using the "capacity" based curves from the slightly over versions which used "load" based versions. According to a discussion with @mjwitte regarding this, there have been some debate in the past about whether "load" or "capacity" based EIR curves should be used in some EnergyPlus equipment models. There could still be other other models in EnergyPlus that either one of these two ways are still used.

The overall conclusion is to that for the VRF AC/Heat Pump models, the current code reflected the description in some other EIR chiller equipment in using "capacity" as basis for the EIR curves (especially the EIRfPLR curve)---this means that the actual measurements and/or post-processing procedures of obtaining these curves in VRF should also follow the "capacity" norm, in that the PLR should not be multiplied into the "capacity" (to get instantaneous load value) as the basis of the curves. In other words, the PLR factor should now be considered in the EIRfPLR curve when generating or obtaining the curve from the original measurement data.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@jcyuan2020 this is currently marked as draft.  That is totally fine, but if you plan on getting it in for 23.1, please add that milestone, or comment back here and I can do it.

**Comment by jcyuan2020** [comment]
Adding to the milestone now.

**Comment by Myoldmopar** [comment]
@jcyuan2020 after reading through this and the original issue, I get the sense that the development team, and at least one user, agree that the PLR change is not needed.  While we certainly might not need a code change for PLR, I'm not sure the other users agree with the right way to wrap this up.  The conversation over on the issue kinda just stops.  Could you provide some additional closure over there so future users searching through the issues understand where we landed and why?   Thanks!

**Comment by edwardv720** [comment]
I've been following the changes and I also see that there's no need to change the code now.

**Comment by Myoldmopar** [comment]
Thanks @edwardv720 that's helpful.

@jcyuan2020 I do think it would be helpful to provide one more conclusion comment on the issue, so that future users and developers understand how/why this wrapped up.  Also, this branch has unit test failures from the PLR change, so those need to be addressed.  With those completed, this could be ready for merge.

**Comment by jcyuan2020** [comment]
The unit test if now fixed. For the concluding message, the following is added to the top comment:
```
The overall conclusion is to that for the VRF AC/Heat Pump models, the current code reflected the description in some other EIR chiller equipment in using "capacity" as basis for the EIR curves (especially the EIRfPLR curve)---this means that the actual measurements and/or post-processing procedures of obtaining these curves in VRF should also follow the "capacity" norm, in that the PLR should not be multiplied into the "capacity" (to get instantaneous load value) as the basis of the curves. In other words, the PLR factor should now be considered in the EIRfPLR curve when generating or obtaining the curve from the original measurement data.
```

**Comment by Myoldmopar** [comment]
Thanks @jcyuan2020, I'll do a quick test with latest develop after I just merged a branch, but this should be on track to merge.

**Comment by Myoldmopar** [comment]
OK, all good here.  Merging this one, thanks @jcyuan2020 and all the others involved.

**Comment by TiejunWu** [comment]
@jcyuan2020 @edwardv720 I was checking back at issue #9252  it has been fixed by this pull. So I ran the original example attached to issue #9252 with EnergyPlus 23.2. The VRF Heat Pump Electricity Rate and COP still has the same problem as mentioned in that ticket. I suppose any changes made by this pull has been incorporated in EnergyPlus 23.2. Am I missing something ?

**Comment by jcyuan2020** [comment]
If that is the case, my suspicion is that it was indeed fixed for 23.1 but then it may be somehow got  reverted in v23.2. For example you may want to check if PR #9979 changed anything on this VRF module.

**Comment by mjwitte** [comment]
@TiejunWu No substantive code changes were made in this PR. The conclusion of the (lengthy) discussion above was that the EIRfPLR curves in the defect file are incorrect.

**Pull request merged**
