### PR TITLE
Bump python interpreter to 3.12

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Since setup-python action doesn't have a python 3.8 for arm (there are arm pythons only starting at 3.10), we need to bump. So go to 3.12 everywhere

Tested at https://github.com/NREL/EnergyPlus/releases/tag/v24.1.0-TestBuildWithPython312

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Alright.  Given what we learned today, this is on hold for now.  I'm going to push a different branch/PR where I'm taking the ARM build back out of GHA and we'll just upload our own manually for now.  I'll change the milestone here accordingly, and thanks for all your help @jmarrec

**Comment by nrel-bot-2b** [comment]
@jmarrec @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jmarrec as Python 3.8 is nearing EOL, this is now a defect that we would be making packages targeting it in 24.2.  As part of a defect, would you like to get these changes ready to go again with any additional action or dependency updates along the way?  If not I'll be happy to do it soon.

**Comment by jmarrec** [comment]
@Myoldmopar yes, I'll do that

**Comment by Myoldmopar** [comment]
@jmarrec OK, now that the Decent CI machines have 3.12 on them, let me know if you need anything here.

**Comment by jmarrec** [comment]
THis is superseded by #10554 , I forgot I had open this one in march.

**Pull request closed without merging**
