### PR TITLE
Add default TeX interaction if not set

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
This works around the odd cases where CI, and now my local Windows VM, can't build the documentation because the TeX interaction variable isn't being set by CMake.  Other devs seem to still be able to build package afaik.  Anyway, this provides the same effective behavior there was before, just in a different way.  And now CI should build package.  I'll kick off a tag to verify.  If all is well this should drop in right away.

### CODE REVIEW

**Comment by jasondegraw** [comment]
@Myoldmopar I think this will clash with my static Fortran fix branch, where I've also made some (different) changes to get past this. Could we fix this over there and get that PR merged?

**Comment by Myoldmopar** [comment]
Thanks @jasondegraw. It doesn't look like this will clash with yours actually.  You have added defines for TEX_INTERACTION on the Windows builds, which is great.  Frankly though, CI should have picked up the default value for TEX_INTERACTION even if it wasn't defined explicitly.  Somehow CI (and my local machine) was making it all the way to the XeLaTeX call with an empty value on that variable.  This change here simply protects that XeLaTeX call from being invalid if somehow TEX_INTERACTION doesn't make it to that point.  I think it's an OK thing to bring this in here in addition to your changes over there.  It will at worst simply be an extra check on that variable.  

I already kicked off a tag of this branch, so I'll at least keep it in place for a while to see if Windows CI is more happy with this change.  If so, we can merge it into your branch or continue discussion.

**Comment by jasondegraw** [comment]
@Myoldmopar I'm fine either way, just want to make sure #6042 goes in for 8.9. I'm pretty sure I've had this issue on my local machine for some time due to my nonstandard TeX installation.

**Comment by Myoldmopar** [comment]
So this branch and one other are seeing non-UTF8 issues in decent_ci in stdout, which fails in a call to split the string into lines.  

I started investigating by looking at how decent_ci is protecting against this.  It is currently trying to encode stdout with an argument `:invalid=>:replace`, which should replace any invalid characters it finds.  I made a [branch](https://github.com/lefticus/decent_ci/compare/ModifyEncodingArgs?expand=1) of decent_ci with some added arguments that will also replace any undefined characters.  I think once this gets tested, it should help protect the final call to split and make this more robust.  I hoped I could just point this branch here on E+ to the new branch over on decent_ci, but I don't see an option to do it.  I'd probably have to modify the decent_ci_runner config file.

I then took this branch and tried to sanitize all non-utf8 characters in the source, docs, and test files folders.  I pushed this change up now.  As far as I could tell they were comment only changes in the IDFs, but I haven't looked at the Files Changed tab here yet, so it may reveal meaningful changes.  For the error itself, I am betting it was the TeX file causing it, since that gets echoed during builds.  If the test files all still run and there aren't any diffs, then this will clean up the bad degree symbols.  If the test files fail, I'll revert that and push the TeX change only back up.

**Comment by Myoldmopar** [comment]
@mjwitte @jasondegraw OK, this looks great now.  The Linux CI is now all happy, no more UTF-8 issues.  I think it was mostly the tex change, but overall there are now a lot less bad characters in the repo.  The one file that is showing ERR diffs is just because the order of the two lines in the ERR file, so one line has a `~~~~~~~~~` type of prefix and the other has a `~~~***~~~` type of prefix.  I'd like to merge this in right away, since it is fairly large but no impact.  Any objections?

**Pull request merged**
