### PR TITLE
Change ZoneHVAC:HybridUnitaryHVAC lookup tables to reference Watts instead of kW

### LINKED ISSUE #7750: ZoneHVAC:HybridUnitaryHVAC - Change lookup tables to use Watts instead of kW
Issue overview
--------------
The lookup tables for all fuel power and consumption rates in the ZoneHVAC:HybridUnitaryHVAC object currently expect table values to be in kW, instead of the EnergyPlus typical standard of Watts.  This is also not explained anywhere in the documentation or IDD file.  The calculation from the output value from the table to the EnergyPlus output can be seen [here](https://github.com/NREL/EnergyPlus/blob/b1c11ff5a75e8e34a6e667b25b8d350f4f1cddae/src/EnergyPlus/HybridEvapCoolingModel.cc#L2128).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #7750
 - This pull request changes the lookup tables for System Electric Power, Supply Fan Electric Power, Second Fuel Consumption, and Third Fuel Consumption to expect values to be in Watts instead of kW.  The associated test file [UnitaryHybridUnitTest_DOSA.idf](tst/EnergyPlus/unit/UnitaryHybridUnitTest_DOSA.idf) and example file [UnitaryHybridAC_DedicatedOutsideAir.idf](testfiles/UnitaryHybridAC_DedicatedOutsideAir.idf) was also updated to reflect lookup tables in Watts instead of kW.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nealkruis** [comment]
@matthew-larson do you know why the entire file is showing as diffs? I wonder if there's a line ending or white space change that you made by accident.

**Comment by matthew-larson** [comment]
I think it is white spaces.  The tables are so large that changing from kW to Watts I did in Excel and pasted back in instead of doing it manually.  This changed the number of spaces between the comma and comment I think.  I can try to resolve this if you think it's important.

**Comment by matthew-larson** [comment]
@nealkruis resolved whitespace issue so entire file isn't showing as a diff anymore.

**Comment by matthew-larson** [comment]
Moving this to https://github.com/NREL/EnergyPlus/pull/7827.

**Pull request closed without merging**
