### PR TITLE
Improve handling water to water heat pumps on plant loops

### LINKED ISSUE #4385: GLHE works on condenser loop but not on plant loop
Ticket 9725

From user:
Heatpump:WatertoWater:EquationFit not being activated

I'm attaching two files. Both use a geothermal loop to provide source water for water to water heat pumps.

In the first file, the geothermal well is located on a PlantLoop, and the source side nodes for the water to water heat pumps are connected to this PlantLoop. In this file, the water to water heat pumps do not operate.

In the second file, the geothermal well is located in a CondenserLoop, and the source side nodes for the water to water heat pumps are connected to this CondenserLoop. In this file, the water to water heat pumps operate.

It is my understanding that in the current Version of EnergyPlus (V8.1.0.009), PlantLoops and CondenserLoops are essentially the same. I would like to request that water to water heat pumps be allowed to connect the source side nodes to PlantLoops. If this is not possible, please provide the user with a severe error if a water to water heat pump is connected on the source side to a PlantLoop.

------------------------
I compared the two files and the only differences are condenserloop-->plantloop and condenserequipmetoperationschemes--->plantequip.....  So, it seems like this should work, but the plantloop version does not.

Two test files added.

### PR DESCRIPTION
**Pull request by EnergyArchmage**
fixes #4385 and #4972.  

Add interconnect calls to water-to-water heat pumps and it seems to work the same when on a plant loop as when on a condenser loop.  

Added a lot of clear_state stuff to plant to get the unit test to work.

### CODE REVIEW

**Comment by EnergyArchmage** [comment]
This assumes that VS-equipment-issues gets merged in first as it was merged in here to get the clear_state stuff.

The same seven integration tests with EIO diffs show here, as from VS-equipment-issues but that is now merged into develop

**Comment by EnergyArchmage** [comment]
I think this pull request is ready to go.  

I have run additional tests with a chiller and could not reproduce the problem.  All the defect files submitted were water to water loop heat pumps and those now work.  Chillers already have calls to do the interconnect setup.  

One difference between CondenserLoop and PlantLoop is that the CondenserLoops automatically get placed at the back of the line when first populating the calling order table.  Water-to-water component models need to call PlantUtilities::InterConnectTwoPlantLoopSides to let the system know about the relationship between two PlantLoops.

**Comment by mjwitte** [comment]
@EnergyArchmage You mean you can't reproduce the chiller problem at all?  Or you've shown it's not present with these changes.

**Comment by Myoldmopar** [comment]
> Add interconnect calls to water-to-water heat pumps and it seems to work the same when on a plant loop as when on a condenser loop.

I read it as he was able to fix it and now it works properly with plant or condenser loops.

**Comment by EnergyArchmage** [comment]
I meant I cannot reproduce chiller problem at all having tried release version 8.3, current develop and with these changes.    

Also have to change CondenserEquipmentOperationSchemes input to PlantEquipmentOperationSchemes.

**Comment by Myoldmopar** [comment]
@EnergyArchmage The cppcheck warnings were bizarre and appeared unrelated.  I deleted those results and if it comes back green, I propose merging this in.  There is a lot of work in the clear_state()s that need to be brought in sooner rather than later.

**Comment by Myoldmopar** [comment]
Oh geez.  I noticed that cppcheck had responded earlier and was green, so I'd be waiting forever for CI to re-run that platform on that commit.  OK, I'm going to merge.  If something pops up and this is still an issue we can re-address, but we need to move on.

**Comment by Myoldmopar** [comment]
Or not; OK thanks @mjwitte

**Comment by mjwitte** [comment]
(sorry - meant to put this comment here in the pull request)
@EnergyArchmage 4972 defect files PlantModel6 and PlantModel6-CondenserLoop crash with an array bounds error. In a debug build.

**Comment by EnergyArchmage** [comment]
I had to make some changes to the ground heat exchanger input object in those files, I think the original file, or a transition step, had corrupted the GroundHeatExchanger:Vertical.    I will add my versions of those files to get them to run.  I have run these files repeatedly in debug builds.

**Comment by mjwitte** [comment]
@EnergyArchmage Regardless, these shouldn't crash.  They didn't before.

**Comment by EnergyArchmage** [comment]
Well they do crash now in develop and it isn't related to this issue, branch or pull request.  I didn't follow the ground changes closely but the IDD changed from V. 8.2 to V8.3 and it seems like transition did not work properly.

**Comment by Myoldmopar** [comment]
@mjwitte OK, so we should merge this and track it in the new issue?

**Comment by EnergyArchmage** [comment]
yes I think this is good to merge.

**Pull request merged**
