### PR TITLE
Correction of Reference Temperature for Fisher-Pedersen Convection Models when Specified for Surfaces

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
Corrected the reference temperatures for the Fisher-Pedersen convection models when specified at the surface level.  The code was using the supply air temperature as the reference temperature for these models.  However, the code for the calculation of the coefficients were the equations based on the zone air temperature.  This was corrected by using the zone mean air temperature as the reference temperature to match the equations.

*The problem is with the surface-level FisherPedersenCeilingDiffuser\* algorithms. These are not used by default by the AdaptiveConvection option. They are only used if the user inputs specifies them at the surface-level or as an override to the defaults in AdaptiveConvection.*

*The zone-level CeilingDiffuser algorithm was correct - it has always used the zone air temperature as the reference temperature.*

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue #6539 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [x] Argument types
   - [x] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes: n/a

### CODE REVIEW

**Comment by mjwitte** [comment]
@RKStrand Functionally, the code changes look fine, but there are [formatting errors](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-138f843027936f6dc65d2004779fb69740056ffb-x86_64-Linux-Ubuntu-14.04-custom_check.html).

**Comment by RKStrand** [comment]
@mjwitte Did the format changes I made trigger a new run of the test suites?  I committed the changes but I'm not seeing that it actually ran again.

**Comment by mjwitte** [comment]
@RKStrand There a no new commits in github on this branch since May 29. Maybe you must need to push the commit?

**Comment by RKStrand** [comment]
@mjwitte That's weird.  My desktop GitHub app usually does that when I "sync" things.  Not sure why it didn't do it this time.  But I just did a push, and then updated from develop, and then synced again.  If that doesn't trigger something, I don't know what will...

**Comment by nrel-bot-3** [comment]
@RKStrand @lgentile it has been 14 days since this pull request was last updated.

**Comment by RKStrand** [comment]
Mike:

Did this finally get pushed properly?

Rick

**Comment by mjwitte** [comment]
@RKStrand I think it's all here.  It's a little confusing because the commits are dated when you commit them locally not when they get pushed into the branch on github.  CI is all green now, so I think it's good.

**Comment by mjwitte** [comment]
@RKStrand Added some defect files in EnergyPlusDevSupport\DefectFiles based on example file Convection.idf.  One uses the zone-level ceilingdiffuser model, and the other uses the surface-level.  Before this fix, the adjacent air temps and surface convection heat transfer rate are very different.  With this fix, they are very close, but not identical. Can you explain why they wouldn't be exactly the same?

**Comment by mjwitte** [comment]
And I merged in current develop to this branch for another round of CI.

**Comment by RKStrand** [comment]
@mjwitte Well, I looked into this and found something very interesting in the code.  In subroutine CalcCeilingDiffuserIntConvCoeff for the Zone Level calculations, when AirDensity is calculated (ACH is then based on this density), it assumes a temperature of 0.0.  When AirDensity is calculated in EvaluateIntHcModels for the Surface Level calculations (same equation for ACH), it is based on the node temperature.  That's a bug and it explains why the two are slightly off--different air densities will result in slightly different ACH values and thus slightly different results.  Want to log that and point it to me?

**Comment by mjwitte** [comment]
@RKStrand Can we just fix that here in this pull request?

**Comment by RKStrand** [comment]
@mjwitte Ok, I'll put in the fix in this pull request and will push it up when it's ready.

**Comment by RKStrand** [comment]
@mjwitte Ok, I need to take back what I wrote last night.  The zero temperature assumption is only at the beginning of the environment since it doesn't have a zone temperature yet.  Once BeginEnvrnFlag is false, it uses the same temperature from the same place.  So, what I wrote last night is not correct.
Which gets us back to your question--I wonder if the issue is the updating of the zone node temperature, when that happens relative to when these calculations are being made.  It is very possible that one happens after an additional update of the zone temperature that this would explain the difference.  So, I have a feeling that these will be close but not exactly the same as a result of that.

**Comment by mjwitte** [comment]
That's a possible explanation, however, I would expect that all convection coefficients get calculated at the same point in the simulation regardless of whether it was set by zone or by surface.  If that's not the case, then maybe one of them should move, but that's a bigger issue.  Could we reproduce the same test using a different convection model?  Say, set to TARP in both?  But since that's the default it may not show anything interesting. Maybe I missed a class of surfaces in the one that uses SurfaceProperty:ConvectionCoefficients:MultipleSurface.

**Review by mjwitte — APPROVED** [review]
@RKStrand My bad - the zone-level test file still had a different outside convection algorithm for zone 2, so that was driving slightly different surface temps.  With that fixed, the two files produce very nearly identical results.  There's still some differences out after 7 or 8 figures, but that's ok. I've merged in develop for one last round of CI tests, then this will be ready to drop in.

**Comment by RKStrand** [comment]
@mjwitte Awesome--glad this resolved itself.  Hopefully this is good to go now.  Thanks!

**Pull request merged**
