### PR TITLE
Implement operating modes in unitary system and new fan model

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
This adds a new set of optional arguments for flowratios and runtimefractions to AirLoopHVAC:UnitarySystem and Fan:SystemModel so that the fan power can be calculated correctly for the following types of situations:
* Unitary system with multi-speed fan which runs on high for heating, when the fan operating mode is cycling, then the fan model needs to know to cycle at high speed, not a lower speed.
* Unitary system with different no-load flow rate that has a small load and runs part of the timestep at cooling or heating flow and part of the timestep at no-load flow; needs to tell the fan model to run at flow1 for runtimefration1 and flow2 for runtimefraction2.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by EnergyArchmage — APPROVED** [review]
pull branch, built, and inspected code changes, looks good.

**Comment by Myoldmopar** [comment]
Merge at will if you are happy with it being done @EnergyArchmage

**Comment by mjwitte** [comment]
@EnergyArchmage Thanks.  Did you review the CI diffs?  I didn't circle back on them yet.  Just looking at the err diffs,
UnitarySystem_VSHeatPumpWaterToAirEquationFit has new max iteration warnings, but maybe there's a bunch already and this just adds a few?
UnitarySystem_5ZoneWaterLoopHeatPump has new `** Warning ** Plant Loop: SINGLE WATER PLANT LOOP Demand Side is storing excess heat the majority of the time.`

**Comment by EnergyArchmage** [comment]
ah shoot, maybe not so much.  Sorry,was not really working today.  This probably does need more review

**Comment by mjwitte** [comment]
No problem.  I'll look at it later today and add to this branch if need be.

**Comment by EnergyArchmage** [comment]
I did find a problem with fan power in continuous fans and made a commit to this branch.  I shouldn't have merged this PR.

**Pull request merged**
