### PR TITLE
Fix some errors in the Eng Ref for Rad-Conv HW Baseboard.

### PR DESCRIPTION
**Pull request by wfbuhl**
This fixes issue 4347

Dude, I pushed the wrong branch. And the issue is 5249. Good Grief.

### CODE REVIEW

**Comment by wfbuhl** [comment]
Let this die!

**Comment by Myoldmopar** [comment]
@wfbuhl Don't worry, I'll kill it off, but CI will probably still ping you about it approximately 6 more times today.

**Comment by wfbuhl** [comment]
I get lonely without mail

**Comment by Myoldmopar** [comment]
Closing and deleting this branch per @wfbuhl.

**Pull request closed without merging**
