### PR TITLE
Plant component refactor of Absorption ChillerHeater

### PR DESCRIPTION
**Pull request by Myoldmopar**

### CODE REVIEW

**Comment by Myoldmopar** [comment]
If CI comes back happy this can be merged.

**Comment by mitchute** [comment]
It looks like the regression on gasAbsorptionChillerHeater is adding some entries on the eio. Other than that, this looks ready.

**Comment by Myoldmopar** [comment]
Thanks for the review @mitchute! I had accidentally left a second size() call in there in getDesignCapacities.  It should be cleaned up now ready to merge but we'll see what CI says.

**Comment by Myoldmopar** [comment]
Woohoo!  Back to just BND diffs in the one file, this now really _should_ be ready to drop in I hope.

**Comment by Myoldmopar** [comment]
All green!  Alright @mitchute let me know if you see anything to hold this up.

**Comment by mitchute** [comment]
Good stuff! Merging.

**Pull request merged**
