### PR TITLE
Update DX Coil warning messages, coil bypass factor functions, and rated SHR documentation

### PR DESCRIPTION
**Pull request by aaron-boranian**
Pull request overview
---------------------
Work performed under the Big Ladder Software Contributor License Agreement.

- Downgrade severe error messages to warnings when no fatal error is triggered for DX coil flow rate per capacity limits and outlet RH > 1 per issue #6115 
- Have VariableSpeedCoils.cc and DXCoils.cc use same coil bypass factor functions, which are now only defined in DXCoils.cc
- Update Engineering Reference documentation for autosizing rated SHR per issue #6113 (the other part of this issue was already addressed in PR #6034)

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by nealkruis — APPROVED** [review]

**Comment by aaron-boranian** [comment]
@rraustad would you mind taking a look at the failed regression tests? They look like pretty small diffs, but I want to double-check with you to make sure that the diffs related to variable speed DX coils are similar to the diffs that we saw after the DX coil fixes in #5116 and #6048.

**Comment by rraustad** [comment]
I have no problem with these changes. Although I don't see anything here that would change a non-VS coil sizing result, I'm stumped by the eio diff's I see.

**Comment by aaron-boranian** [comment]
@rraustad Where do you see non-VS coil sizing eio diffs? I'm only seeing VS coil sizing eio diffs for failed regression tests.

**Comment by rraustad** [comment]
Sorry, your correct. I saw ChangeoverBypassVAV_AirToAirHeatPump and didn't realize someone put a VS coil in that example file.

    COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1

So these diff's then look reasonable.

**Review by rraustad — APPROVED** [review]
Reviewed and accepted.

**Comment by Myoldmopar** [comment]
@aaron-boranian I don't think this task was funded as part of a subcontract for DOE, and I don't think we have a contribution policy signed and in place.  I'm going to target this for EnergyPlus 8.9.0, but if I'm wrong, or if we can get one signed very quickly, this could still go in for 8.8.0.

**Comment by nealkruis** [comment]
@Myoldmopar

**Pull request merged**
