### PR TITLE
Improve chilled water storage tank deadband control

### PR DESCRIPTION
**Pull request by Myoldmopar**
Switch the sign of the deadband delta for chilled water tanks
- [x] Code change
- [x] Testing
- [x] Documentation change (none)
- [x] Review (@energyarchmage liked the change)

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Fixes #4685.

**Comment by Myoldmopar** [comment]
@EnergyArchmage Can I assign this PR to you?  It should be a quick merge:
- Code change is minimal, just the sign of the deadband delta
- I extracted this logic and put it in an instance method on the tank struct
- I then added a unit test to test this function in both possible code paths
- CI is showing diffs in the chilled water file as it is now operating with the proper deadband operation
- Testing is discussed in the issue itself: #4685 

If not, I'll ask others, just let me know.

**Comment by Myoldmopar** [comment]
@mjwitte Could you be reviewer on this?  The summary is [above](https://github.com/NREL/EnergyPlus/pull/4918#issuecomment-104286709), and @EnergyArchmage liked the fix but I think he's unavailable for review.

**Comment by mjwitte** [comment]
@Myoldmopar Yes, I will review.

**Comment by Myoldmopar** [comment]
@jasondegraw I changed the condenser minimum temperature from 5C to 4C.  This should hush up the new warning messages that stem from the change in deadband control.  I believe that was the only change required, so this should be able to merge if the changes don't cause any trouble.  Let me know if you see anything else!

**Pull request merged**
