### PR TITLE
Fix issue 6998 Fuel Cell Zero Cp causing div-by-zero and repeated root solver errors

### LINKED ISSUE #6998: Fuel Cell Cp is zero when using "LiquidGeneric"
Issue overview
--------------

The `fuelcell.rb` test in OpenStudio-resources now crashes, and I can't really explain why. It used to run with E+ 8.9.0. Transitioning the file using E+ transition utility to 9.0.0, then running it makes it crash too.

[fuelcell.rb.idf.txt](https://github.com/NREL/EnergyPlus/files/2450191/fuelcell.rb.idf.txt)

*Backtrace*:

```
* thread #1, name = 'energyplus', stop reason = signal SIGFPE: invalid floating point operation
    frame #0: 0x00007ffff4aa0018 libenergyplusapi.so.9.0.0`EnergyPlus::FuelCellElectricGenerator::CalcFuelCellGeneratorModel(GeneratorNum=1, RunFlag=true, MyLoad=3400, (null)=true) at FuelCellElectricGenerator.cc:1657
   1654	            } else {
   1655	                FuelSupply(FuelCell(GeneratorNum).FuelSupNum).TfuelIntoFCPM =
   1656	                    ((1.0 - FuelSupply(FuelCell(GeneratorNum).FuelSupNum).CompPowerLossFactor) *
-> 1657	                     FuelSupply(FuelCell(GeneratorNum).FuelSupNum).PfuelCompEl / (FuelCell(GeneratorNum).FCPM.NdotFuel * Cp * 1000.0)) +
   1658	                    FuelSupply(FuelCell(GeneratorNum).FuelSupNum).TfuelIntoCompress; // 1000 Cp units mol-> kmol
   1659	            }
   1660	            // calc skin losses from fuel compressor
```

`Cp` is zero. Here's my FuelSupply:

```
Generator:FuelSupply,
  Generator Fuel Supply 1,                !- Name
  Scheduled,                              !- Fuel Temperature Modeling Mode
  ,                                       !- Fuel Temperature Reference Node Name
  Fuel Temperature,                       !- Fuel Temperature Schedule Name
  Compressor Power Multiplier Function of FuelRate Curve, !- Compressor Power Multiplier Function of Fuel Rate Curve Name
  1,                                      !- Compressor Heat Loss Factor
  LiquidGeneric,                          !- Fuel Type
  43100,                                  !- Liquid Generic Fuel Lower Heating Value {kJ/kg}
  46200,                                  !- Liquid Generic Fuel Higher Heating Value {kJ/kg}
  1,                                      !- Liquid Generic Fuel Molecular Weight {g/mol}
  0,                                      !- Liquid Generic Fuel CO2 Emission Factor
  0;                                      !- Number of Constituents in Gaseous Constituent Fuel Supply
```

Just before that line there's `FigureFuelHeatCap(GeneratorNum, Tavg, Cp);`, where Cp is passed By Ref, so that's where it's calculated: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/FuelCellElectricGenerator.cc#L2530

In my case: `FuelSupply(FuelCell(GeneratorNum).FuelSupNum).NumConstituents`   => using debugger it's -56624, because it's not initialized.

It seems that `NumConstituents` is only initialized is Fuel Type is `GaseousConstituents`: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/GeneratorFuelSupply.cc#L227:L229

I know there has been some work done by @EnergyArchmage on the Fuel Cell model recently, could this be linked?

### Details
Some additional details for this issue (if relevant):
 - Platform: Ubuntu
 - Version of EnergyPlus: 9.0.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #6998
 - Fixed the Zero-Cp problem when using LiquidGeneric fuel type for Fuel Cells, which could cause repeated root solver warning errors. What's worse for the problem is that, it could cause divide-by-zero faults but could still sneakily allow the program to run and get meaningless results. 
 - Also suppressed the recurring warning/error messages to show only the first instance and then summarize the following instances into the recurring warnings/errors report. 
 - Added a minor fix for Issue #8600 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
When I take the 9.4 defect file from devsupport and transition it up to latest code, I get the huge error file in develop, as expected.  But with this branch (with develop pulled in), I get a NaN:

```
Program Version,EnergyPlus, Version 9.5.0-aa2716547d, YMD=2021.03.20 21:18,
   ************* Beginning Zone Sizing Calculations
   ** Warning ** CalcFuelCellGeneratorModel: Root Solver problem, flag = -1, check accuracy and iterations, did not converge
   ** Severe  ** DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   **   ~~~   ** occurs in Zone=ZN_1_FLR_1_SEC_1 During Warmup & Sizing, Environment=NEWARK ANN HTG 99.6% CONDNS DB, at Simulation time=01/21 00:00 - 00:10
   **   ~~~   ** LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   **   ~~~   ** Zone Heating Set-point=21.00
   **   ~~~   ** Zone Cooling Set-point=33.00
   **   ~~~   ** Zone TempDepZnLd=NAN
   **   ~~~   ** Zone TempIndZnLd=NAN
   **   ~~~   ** Zone ThermostatSetPoint=27.03
   **  Fatal  ** Program terminates due to above conditions.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
```

Can someone confirm?

**Comment by jcyuan2020** [comment]
> 
> When I take the 9.4 defect file from devsupport and transition it up to latest code, I get the huge error file in develop, as expected. But with this branch (with develop pulled in), I get a NaN:
> 
> Can someone confirm?

You need use a slightly changed defect file---there original had a few missing field. I will have this sent in in some way.

**Comment by Myoldmopar** [comment]
Thank you @jcyuan2020 , but I'm still not quite there.  When I download your modified file, in develop the file passes just fine.  And in this branch the error file looks similar.  I'm building a release build but even the numerics are the same in the error file.  Can you confirm what I should be verifying as the reviewer?  Or if there is some configuration I'm missing?  Thanks!

**Comment by jcyuan2020** [comment]
@Myoldmopar It is a little bit strange why the release version would let the simulation go so far with the div-by-zero error---the reason might partially be that the release version does not check the div-by-zero unless some other (severe) warnings or problems are triggered? 
I tried with the most updates versions of both branches (most recent current PR branch with most recent `develop` branch (7ae55678f68) pulled in) In the debug mode, the  `develop` branch will indeed encounter div-by-zero caused by zero Cp and then would not go any further. The current PR branch will set to handle the the zero Cp case and will allow the simulation to continue.

**Comment by Myoldmopar** [comment]
OK, I'm starting to believe that it's just a thing on my machine.  I trust that it is behaving well for you, and the changes are fine.  This is going in.  Thanks for bearing with me @jcyuan2020

**Pull request merged**
