### PR TITLE
Fix Divide by Zero in CentralHeatPump

### LINKED ISSUE #5904: CentralHeatPumpSystem problems
## Issue overview

User notes that example file CentralChillerHeaterSystem_Simultaneous_Cooling_Heating does not seem to be working.  Reviewing this file, and the companion CentralChillerHeaterSystem_Cooling_Heating, there are some problems:
1. The heat transfer from the ground heat exchanger is always negative.
2. The ground heat exchanger is only operating when the central heat pump system is in heating mode.  Flows to the HX are zero when the system is cooling, so where is the heat rejection going?
3. Both files have unused district heating and cooling objects that should be removed.
4. Also see #5808 
5. The IDD is missing the "autosizable" tag for ChillerHeaterPerformance:Electric:EIR field "Design Hot Water Flow Rate".
*MJW 15 Feb 2019 - quick inspection of the code says this isn't autosizeable, that's why.*
6. And the curve types are wrong for the ChillerHeaterPerformance:Electric:EIR fPLR curves - the code assumes a single variable curve. IDD and I/O ref talk about bi-cubic curves. This needs review, but it appears these should just accept any univariate curve or table.
7. And user file trips over divide by zero [here](https://github.com/NREL/EnergyPlus/blob/fa73d590331fc1852c4c9ad1b9502035dbff99a5/src/EnergyPlus/PlantCentralGSHP.cc#L1885).  At this point CHPower and FRAC are zero, because QEvaporator is zero.  Regardless of why QEvaporater is zero (there are many places in the code above where this can happen), this line needs protection for divide by zero and possibly a whole block can be skipped when it's zero.
8.  So, QEvaporator is zero because of this check [here](https://github.com/NREL/EnergyPlus/blob/fa73d590331fc1852c4c9ad1b9502035dbff99a5/src/EnergyPlus/PlantCentralGSHP.cc#L1827-L1837).
TempLowLimitEout =12.2, EvapInletTemp =8.0, and EvapOutletTempSetPoint = 6.7.  So, the setpoint is 6.7 but the min temp limit is 12.2.  Is this an input error or a logic flaw?
The 12.2 comes from here
```
ChillerHeaterPerformance:Electric:EIR,

    12.22,                   !- Heating Mode Entering Chilled Water Temperature Low Limit {C}
```
This field is being misapplied in the model as lower limit on leaving chilled water temp.

9.  Defect file has times with negative values for HEATPUMP:Chiller Heater Cooling Electric Energy Unit 1.
10.  With the 12.22 changed to 6.7, there's another place that divides by zero because ReferenceCOP = 0 [here](https://github.com/NREL/EnergyPlus/blob/fa73d590331fc1852c4c9ad1b9502035dbff99a5/src/EnergyPlus/PlantCentralGSHP.cc#L1883). That's zero, because the heating capacity calcs are done [here](https://github.com/NREL/EnergyPlus/blob/fa73d590331fc1852c4c9ad1b9502035dbff99a5/src/EnergyPlus/PlantCentralGSHP.cc#L1082-L1084) before the cooling cap has been sized!  What a mess.  Are there other places that aren't fully compatible with autosizing this component?

### Details

Some additional details for this issue (if relevant):
- Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket number 11251 and 12051
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file - use example files  CentralChillerHeaterSystem_Simultaneous_Cooling_Heating and CentralChillerHeaterSystem_Cooling_Heating
Also, user file added to EnergyPlusDevSupport\DefectFiles (run with Melbourne Australia epw)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by YanfeiNREL**
Pull request overview
---------------------
 - Fixes #5904 
 - recreate the issues reported by users for CentralHeatPump. Fix issues currently available. 

### Pull Request Author
 - [x] Label the PR with at least one of: Defect
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
   **Line 2376-2380:**
 ```
   if (CHPower == 0.0) {
                        ActualCOP = 0.0;
    } else {
                        ActualCOP = (QEvaporator + ChillerFalseLoadRate) / CHPower;
    }
```
**Line 2369 - 2373**
```
   if (ReferenceCOP <= 0.0) {
                    CHPower = 0.0;
    }else{
                    CHPower = (AvailChillerCap / ReferenceCOP) * ChillerEIRFPLR * ChillerEIRFT * FRAC;
    }
```

 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
    For this issue, there are no after-fix plots, because the issue will be fixed after the updated GSHP model is being added and replacing the current model.

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] CI status: all green or justified

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@YanfeiNREL @lgentile it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
@Myoldmopar This has a couple of basic fixes from @YanfeiNREL. It should be ready to go.

**Comment by nrel-bot-2** [comment]
@YanfeiNREL @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I was trying to review this.  I transitioned the defect file up to latest IDD and ran it with develop.  I was using Melbourne weather, but I did not encounter a divide by zero.  I ran with this branch and also did not encounter an issue, but I'm having trouble verifying if I can't reproduce the issue.

@mjwitte I know this is pulling from a long time back but if you have any tips I'd be happy to hear them.

In general, these protections are fine, so I'm OK with this going in, but I'd like it better if I could verify the fix.

**Comment by mjwitte** [comment]
@Myoldmopar Depending on the configuration and platform divide by zero could slip by unnoticed. Have you tried running it in the debugger with a breakpoint when Qevap=0 on the affect line? If that doesn't work, I can try to reproduce here.

**Comment by Myoldmopar** [comment]
I never get to any of the `==0` lines in the debugger.  I'm inclined to just accept this and move on.

**Comment by Myoldmopar** [comment]
OK, I'll call it, these changes are sensible and CI is happy.  I can't verify the fix though, so I'll merge this, and close the issue with a note about reopening if it is still present.

**Pull request merged**
