### PR TITLE
Fix logic issue in special day calculation

### LINKED ISSUE #8214: Special Days Failures
Issue overview
--------------
Special days are causing simulation failures. To test, run ```5ZoneVAV-ChilledWaterStorage-Stratified.idf``` with ```USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw```. This fails on current develop but runs with the 9.3.0 bugfix version. Confirmed by myself and *the* @mjwitte .

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 10.15.4)
 - Version of EnergyPlus (5bf36f34b)
 - Unmethours link or helpdesk ticket number - None

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] ~Defect file added (list location of defect file here)~
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - Fixes #8214
 - Marking as DoNotPublish since the defect was just introduced in #8157

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Should we add some special days to one of the annual regression test files? And DST if not there already?

**Comment by Myoldmopar** [comment]
Sounds like a great plan, though I probably won't do that until after the freeze this week.

**Comment by mitchute** [comment]
Are we holding this until after IOFreeze so those regression changes can be applied here?

**Comment by mjwitte** [comment]
@mitchute I don't think so. The fix needs to be in for I/O Freeze. We can change the test file later (if we remember).

**Comment by mitchute** [comment]
OK, testing now.

**Comment by mitchute** [comment]
Looks good here. Tests all pass and this resolves the problem. I'll merge once CI confirms.

**Comment by mitchute** [comment]
CI is happy. Merging now.

**Comment by nmerket** [comment]
Sorry, guys. Thanks for catching this @mitchute @mjwitte @Myoldmopar

**Pull request merged**
