### PR TITLE
Improve error checking in SQLite database connection

### PR DESCRIPTION
**Pull request by simularis**
Pull request overview
---------------------
 - Motivation: heard reports of SQLite fatal error messages. See  [1](https://unmethours.com/question/36452/fatal-the-sqlite-database-failed-to-open/),[2](https://discourse.ladybug.tools/t/the-sqlite-database-failed-to-open/15394),[3](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/pull/31) and issue #7512.
 - Proactive effort to avoid failure modes for opening SQLite connection:
    1. Attempting to execute query after open failed. This violates documentation for [`sqlite3_exec()`](https://www.sqlite.org/c3ref/exec.html) that the connection must be valid.
    2. If deleting the test file fails, attempting to get error message when SQLite did not return an error code. In that case, the sqlite.err file would show `SQLite3 message, can't remove old database: bad parameter or other API misuse`.
- I haven't been able to reproduce the errors mentioned by other sources.

Suggested tag: Defect

### Discussion
Additional refactoring idea: currently the code creates a new empty file, writes a test table, deletes the file, then creates a new empty file again. It seems unnecessary to close the file, as this also creates another potential point of failure where some other application could lock the file after the deletion.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mbadams5 and @JasonGlazer, you were the ones who usually messed with this stuff.  If you have any thoughts here, I'd welcome them.  Otherwise this seems like a harmless addition, and I don't mind merging it as-is.  

@simularis I got your contribution agreement, thanks!

**Comment by JasonGlazer** [comment]
Looks like a good addition to me.

**Comment by Myoldmopar** [comment]
Thanks @JasonGlazer.  I'm going to keep this in the merge queue, but I won't plan on merging until next week sometime to give others a review chance.

**Comment by Myoldmopar** [comment]
Alright, I'm going to go ahead and merge.  @mbadams5 if you, or anyone else, gets time to look at this later and have any thoughts on these changes, I am happy to add tweaks to it at any time.

**Comment by simularis** [comment]
Thank you.

**Pull request merged**
