### PR TITLE
Convert misc files from gio

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview
---------------------

Convert to {fmt}

 * edd
 * ems
 * eplusmap
 * airloop statistics
 * shading
 * mtd
 * delightin

Expected Changes

 * Might fix test failures on Windows

Refactor:

 * Begin merge of EnergyPlusData and OutputFiles where reasonable

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@lefticus something is still failing to build on Windows here.  Are you able to build this branch on Windows yourself?  If so, I'll try to build locally to investigate as well.

**Comment by lefticus** [comment]
@Myoldmopar yes, I definitely have some issues I'm sorting out. I need to make this a draft PR

**Comment by lefticus** [comment]
@Myoldmopar seem to have hit 100% tests passing on Windows. I'm busy all day tomorrow but if this PR merits a phone call for any reason, I'm available all next week.

**Comment by Myoldmopar** [comment]
Fantastic!  I mean those mtd file errors were not always hitting 100%, but the percent seemed to be > 50%, so it's a great sign that this came back all clean.  I'll look it over.

**Comment by mitchute** [comment]
Probably not necessary, but one more pass from CI then this should go in.

**Comment by mitchute** [comment]
Hmm... I guess I'll hold off for now until we figure out what's going on.

**Comment by mitchute** [comment]
Conflicts resolved and the failing unit tests fixed. Letting CI take another pass.

**Comment by mitchute** [comment]
@nealkruis I've just recently noticed this warning starting to pop up: https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-8b4b22693e26c765c363e453426d78aad5d6cec5-Win64-Windows-10-VisualStudio-16.html

Not sure how long it's been around. NBD, just FYI.

**Comment by nealkruis** [comment]
@mitchute I've noticed it too. It's in an external dependency [libtess2](https://github.com/memononen/libtess2). Is MSVC making `size_t` something other than `unsigned int`?

**Comment by mitchute** [comment]
> @mitchute I've noticed it too. It's in an external dependency [libtess2](https://github.com/memononen/libtess2). Is MSVC making `size_t` something other than `unsigned int`?

Unknown. Looks like it could be ```unsigned __int64``` also: https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types?view=vs-2019

**Comment by mitchute** [comment]
Things look good now. I like that ```outputFiles``` is now a state member variable. Merging.

**Pull request merged**
