### PR TITLE
Hvac flex measures

### PR DESCRIPTION
**Pull request by shenb**
Pull request overview
---------------------
 - DESCRIBE PURPOSE OF THIS PULL REQUEST
 - this pull aims to check in the codes which implemented grid-responsive HVAC flexible measures, to model modulating cooling coils, dual-source heat pumps, multi-mode coils and hot water and ice/PCM storage, etc. during grid-response periods to achieve reduced electricity consumption. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**
-->all the NFPs have been placed into EnergyPlus\design\FY2021, for review. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@shenb I am marking this for the future release of EnergyPlus, it's simply coming in too late.  The first step will be to get a review of the scope/purpose, the layout for the new input objects, the testing plan, etc., from the EnergyPlus team before looking at any code.  We hold technical review calls every other week, in the same timeslot as the biweekly iteration calls.  I'll send that to you separately if you don't already have the invite. 

It's a bit premature to worry too  much about these things, but you have lots of things to clean up that our CI system has been alerting you to on these commits.  You have tabs in your IDFs, your new IDFs aren't in the testfiles/CMakeLists so they aren't being run by our system, you have build warnings, you have license year mismatches, you have bad units in your IDD.

**Comment by shenb** [comment]
Edwin,

Thank for help starting this checking in procedure. We are OK to have the new features merged after the 9.5 release.

Sorry for noticing the E+ team late. The customers wanted a functional, customized version ready by last December. We were kind of in a hurry to meet that goal first. Now, we are ready for the E+ formal review and test procedure.

We will clean up the CI issues next.

Best,

Bo

**Review by EnergyArchmage — COMMENTED** [review]
Quite the ambitious pull request!  I would think this should be separated into a number of smaller pull requests and features.  

It is unfortunate that this work has gotten so far seemingly without review and so these comments are going come off as a bit harsh.  I fear too often it happens that features get "into EnergyPlus" but then during implementation the scope gets so restricted that in actual application the features are not as useable as expected. 

It appears that CoilSystem:IntegratedHeatPump:AirSource is currently limited to single-zone, load-based control.  That is the zone named in the parent AirLoopHVAC:UnitaryHeatPump:AirToAir is used for the indoor conditions, load-to-setpoint etc.  I would guess that grid-tied operation involves larger customers than those with single-zone residential packages which IHP framework was originally designed for. For such complex and involved packaged equipment, it seems that medium-sized commercial applications are important and these need multi-zone air handlers.  The packages here should allow for setpoint based operation in addition to load-based operation.  It appears that much of this set of features is centered around small single-zone applications, whereas EnergyPlus as a general engine needs to be tailored to all sizes of buildings. 


Is CoilSystem:IntegratedHeatPump:AirSource going off the ranch with regard to unitary system modeling?  It appears to be available within parent AirLoopHVAC:UnitaryHeatPump:AirToAir but hasn't that model been more or less abandoned in favor of AirLoopHVAC:UnitarySystem?  Suggest to extend work to add IHP to AirLoopHVAC:UnitarySystem and make sure it works with both load-based control (for single-zone) and setpoint based control (for multizone).


Is CoilSystem:IntegratedHeatPump:AirSource going off the ranch with regard to plant modeling?  What is the fuller input situation for ice storage and/or air source chilled water? does input involve using the usual set of central plant objects? Or is the idea everything is contained within CoilSystem:IntegratedHeatPump:AirSource?

Coil:Chiller:AirSource:VariableSpeed object seems to be both an process air cooling coil and a chiller for charging ice storage? If so I find it a confusing combo of devices, if not then a new name will help.   Seems that the air source chiller piece of this should be a broadly usable plant component, like a Chiller:Electric:AirSource:VariableSpeed, that can be used in all manner of plants as well as the IHP. The chilled water coil piece should just be existing Coil:Cooling:Water:DetailedGeometry.  

ThermalStorage:Pcm:Simple.  Suggest to be careful about following ThermalStorage:Ice:Simple, more advanced control capabilities are needed to actual model ice storage in a useful way.  Perhaps the controls are intended to be handled differently here but suggest to follow detailed ice storage implementation for more usability in generic plant configurations.

ThermalStorage:Cooling:Pair and ThermalStorage:Heating:Pair as designed are only going to be useful for small single-device applications.  Again a small equipment mind set appears to lead to a much less useful design for E+.  It would be more broadly useful, and easier implement, to use the general plant sizing framework where the fluid flow rates of all the devices on the demand side of the system are added together and the storage sized appropriately. It is possible to add a field to Sizing:Plant for the nominal time to charge the storage and then calculate storage capacity as a function of autosized loop design flow rate and temperature difference. The plant sizing is already summing up the loading on the system and this can work for both hot and cold plant loops with one field in and existing object instead of two new objects of limited usefulness. 


Coil:LiquidDesiccant:Simple appears to be more like a DX coil than chilled water coil from the point of view of connections to other objects in E+.  I don't see what the water node connections are for, is the intent really that a plant loop will circulate liquid desiccant?  If not the self-contained liquid desiccant system doesn't need plant connections here. 

CoilSystem:DesiccantStorageHeatPump:AirSource is yet another IHP.  The fact that CoilSystem:IntegratedHeatPump:AirSource wasn't extended for liquid desiccant shows that overall approach here lacks good design. For example, what happens when a liquid desiccant package comes along with chilled water coil instead of DX cooling. Again this should be for AirLoopHVAC:UnitarySystem. 


Proposed changes to Coil:Heating:DX:VariableSpeed, Coil:Cooling:DX:VariableSpeed, and Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed look okay.

**Comment by shenb** [comment]
Brent,

Thanks for all the nice comments, please see our highlighted responses,


@EnergyArchmage commented on this pull request.

Quite the ambitious pull request! I would think this should be separated into a number of smaller pull requests and features.

-->yes, we agree.

It is unfortunate that this work has gotten so far seemingly without review and so these comments are going come off as a bit harsh. I fear too often it happens that features get "into EnergyPlus" but then during implementation the scope gets so restricted that in actual application the features are not as useable as expected.

--> DOE managers asked us to deliver a customized version in four months by last December and then use this initial version for policy analyses. We were in a hurry to meet this goal first. Now, we are ready to go through the formal review process to improve all the new features per team’s suggestions. We can spend the entire FY21 to go through and improvements and the check-in process as needed. That is not a hurry,

It appears that CoilSystem:IntegratedHeatPump:AirSource is currently limited to single-zone, load-based control. That is the zone named in the parent AirLoopHVAC:UnitaryHeatPump:AirToAir is used for the indoor conditions, load-to-setpoint etc. I would guess that grid-tied operation involves larger customers than those with single-zone residential packages which IHP framework was originally designed for. For such complex and involved packaged equipment, it seems that medium-sized commercial applications are important and these need multi-zone air handlers. The packages here should allow for setpoint based operation in addition to load-based operation. It appears that much of this set of features is centered around small single-zone applications, whereas EnergyPlus as a general engine needs to be tailored to all sizes of buildings.
-->the CoilSystem:IntegratedHeatPump:AirSource were also incorporated in CoilSystem:Cooling:DX and CoilSystem:Heating:DX parent objects for commercial building multi-zone simulations.

Is CoilSystem:IntegratedHeatPump:AirSource going off the ranch with regard to unitary system modeling? It appears to be available within parent AirLoopHVAC:UnitaryHeatPump:AirToAir but hasn't that model been more or less abandoned in favor of AirLoopHVAC:UnitarySystem? Suggest to extend work to add IHP to AirLoopHVAC:UnitarySystem and make sure it works with both load-based control (for single-zone) and setpoint based control (for multizone).

-->yes, can be done next.

Is CoilSystem:IntegratedHeatPump:AirSource going off the ranch with regard to plant modeling? What is the fuller input situation for ice storage and/or air source chilled water? does input involve using the usual set of central plant objects? Or is the idea everything is contained within CoilSystem:IntegratedHeatPump:AirSource?

-->the charging side, i.e. using a chiller to charge an ice/pcm tank is contained in the integrated heat pump to simplify the iterations.

On the other hand, the delivery side, i.e. chilled water coil + tank, is still the same plant loop.

Coil:Chiller:AirSource:VariableSpeed object seems to be both an process air cooling coil and a chiller for charging ice storage? If so I find it a confusing combo of devices, if not then a new name will help. Seems that the air source chiller piece of this should be a broadly usable plant component, like a Chiller:Electric:AirSource:VariableSpeed, that can be used in all manner of plants as well as the IHP. The chilled water coil piece should just be existing Coil:Cooling:Water:DetailedGeometry.

-->it is an air-source chiller, not an air cooling coil. We can change the name to Chiller:Electric:AirSource:VariableSpeed and make it a part of plant loop children objects next.

ThermalStorage:Pcm:Simple. Suggest to be careful about following ThermalStorage:Ice:Simple, more advanced control capabilities are needed to actual model ice storage in a useful way. Perhaps the controls are intended to be handled differently here but suggest to follow detailed ice storage implementation for more usability in generic plant configurations.

-->can be improved as suggested.

ThermalStorage:Cooling:Pair and ThermalStorage:Heating:Pair as designed are only going to be useful for small single-device applications. Again a small equipment mind set appears to lead to a much less useful design for E+. It would be more broadly useful, and easier implement, to use the general plant sizing framework where the fluid flow rates of all the devices on the demand side of the system are added together and the storage sized appropriately. It is possible to add a field to Sizing:Plant for the nominal time to charge the storage and then calculate storage capacity as a function of autosized loop design flow rate and temperature difference. The plant sizing is already summing up the loading on the system and this can work for both hot and cold plant loops with one field in and existing object instead of two new objects of limited usefulness.

-->can be implemented in the sizing:plant next.

Coil:LiquidDesiccant:Simple appears to be more like a DX coil than chilled water coil from the point of view of connections to other objects in E+. I don't see what the water node connections are for, is the intent really that a plant loop will circulate liquid desiccant? If not the self-contained liquid desiccant system doesn't need plant connections here.

-->from outside, it is connected and treated as water nodes, i.e. no liquid desiccant properties added to the plant loop yet. It will be called by a desiccant integrated heat pump project, CoilSystem:DesiccantStorageHeatPump:AirSource which knows the properties.

CoilSystem:DesiccantStorageHeatPump:AirSource is yet another IHP. The fact that CoilSystem:IntegratedHeatPump:AirSource wasn't extended for liquid desiccant shows that overall approach here lacks good design. For example, what happens when a liquid desiccant package comes along with chilled water coil instead of DX cooling. Again this should be for AirLoopHVAC:UnitarySystem.

--> CoilSystem:DesiccantStorageHeatPump:AirSource turned out not very useful for grid-responsive flexibilities. Probably, not really useful for wide end users. So, we simplified the implementations. We can make it a part of AirLoopHVAC:UnitarySystem next, as needed.

Proposed changes to Coil:Heating:DX:VariableSpeed, Coil:Cooling:DX:VariableSpeed, and Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed look okay.
Thanks again,

Bo

**Comment by mjwitte** [comment]
Some initial comments on the new objects:
1. Instead of inserting new fields for grid controls into new objects, it seems a better approach would be to use the existing DemandManager:* system and add new types of demand managers that can act on the desired components.
2. Coil:Cooling:DX:VariableSpeed will be deprecated in the (near) future. New objects should use Coil:CoolingDX instead.
3. The proposed new Coil:Chiller:AirSource:VariableSpeed object - is it a chiller or a coil? If I'm following correctly it is a one-off that can only be used with CoilSystem:IntegratedHeatPump:AirSource. 
4. ThermalStorage:Heating:Pair and ThermalStorage:Cooling:Pair appear to be used only for tank sizing? If so, perhaps these should be named ThermalStorage:Sizing:Heating/Cooling similar to the existing WaterHeater:Sizing object.
5. Let's avoid naming anything *:Simple especially if it doesn't have a comparable *:Detailed object.

Some of these comments overlap with Brent's comments which I just saw.

**Comment by shenb** [comment]
Thanks for the nice comments

Some initial comments on the new objects:

  1.  Instead of inserting new fields for grid controls into new objects, it seems a better approach would be to use the existing DemandManager:* system and add new types of demand managers that can act on the desired components.
-->OK, can be done that way, while we will connect the DemandManager to the coil objects?

  1.  Coil:Cooling:DX:VariableSpeed will be deprecated in the (near) future. New objects should use Coil:CoolingDX instead.
-->can change the name as needed. or also the source codes?

  1.  The proposed new Coil:Chiller:AirSource:VariableSpeed object - is it a chiller or a coil? If I'm following correctly it is a one-off that can only be used with CoilSystem:IntegratedHeatPump:AirSource.
-->it should be a chiller, not an air cooling coil. Now, it is only used in CoilSystem:IntegratedHeatPump:AirSource..

  1.  ThermalStorage:Heating:Pair and ThermalStorage:Cooling:Pair appear to be used only for tank sizing? If so, perhaps these should be named ThermalStorage:Sizing:Heating/Cooling similar to the existing WaterHeater:Sizing object.
-->agree.

  1.  Let's avoid naming anything *:Simple especially if it doesn't have a comparable *:Detailed object.
-->agree

**Comment by Myoldmopar** [comment]
@shenb with the future of this branch uncertain, I will make one suggestion and one request:

- I don't think it is necessary to keep pulling the latest develop into your code.  The develop branch is moving fast right now and you don't need to make constant updates to this branch.
- Please push this branch to a fork of EnergyPlus.  Every time you make another push it triggers another set of CI results, and with 4 commits just today, that's taking a toll on our testing framework.

I'm going to close this PR, and as soon as you get this pushed to a fork of the repo, let me know and we'll delete this branch from the main repo for now.  NOTE: This doesn't mean that some of these changes can't go in at some point, you can still open a new PR from that fork.  This will just help keep our testing under control.

If you need a fork of the repo, we keep one at github.com/energy-plus/EnergyPlus, and I can give you access so you can push to that repo.  Or you can fork it into your own user and push all you want.

**Comment by shenb** [comment]
Edwin,

How about this,


·         Allow me keep this branch to follow the change of Develop (am afraid if it takes too long with no merging Develop, I will have start everything over)

·         From now on, I won’t push my changes to the server, i.e. not test required for this branch.

Thanks,

Bo

**Comment by shenb** [comment]
Edwin,

I will follow your suggestion next.

Thanks,

Bo

**Comment by Myoldmopar** [comment]
@shenb yes, of course that sounds great.  You can keep any branch you want locally and keep up to date with develop as often as you'd like.  Right now the develop branch is moving very quickly so it's a lot to keep up with, but of course most of the time it won't be this crazy.  I will delete this remote branch now from this repo to keep our testing a little calmer.  But I do recommend pushing your branch to **some** repo here on github, either shenb/EnergyPlus or energy-plus/EnergyPlus.

**Comment by shenb** [comment]
Edwin,

Please allow me a final push, then, I will fork it to

energy-plus/EnergyPlus.
—
thanks,

Bo

**Comment by Myoldmopar** [comment]
@shenb I invited you to the `energy-plus/EnergyPlus` repository so you have write access there.  Now in your local folder, just add that repository as a remote and push your branch to it.  No reason to push anything to here.

**Comment by shenb** [comment]
Thanks Edwin.

I had it successfully pushed to energy-plus/EnergyPlus.

We are good.

Bo

**Comment by shenb** [comment]
Edwin,

Am wondering if you could please also grant my colleague Dr. Jian Sun the write access to energy-plus/EnergyPlus. We will both work at the HVAC Flex branch, as below:

account id: JianSun2020
Email: sunj2@ornl.gov<mailto:sunj2@ornl.gov>

Thanks,

Bo

**Pull request closed without merging**
