### PR TITLE
Fix EAp2-4/5 table to use individual peak demands instead of part of building peak demand

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #5672 

The LEED Summary report table EAp2-4/5 was reporting the demand for each end use at the time of the peak building demand. GBCI and users of LEED were expecting to see the individual peak demand for each end use separately (which might occur at different times). This fix changes to show the individual peak demands.

Also addresses remaining portion of #5559 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [x] Argument types
   - [x] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by mjwitte** [comment]
I used RefBldgLargeHotelNew2004_Chicago.idf as a test file.  All of the end-use peaks agree with max values from meter output at the timestep frequency.  Is there a reason that the cells for demand are empty in the "Heating -- Other" row?
screenshot 2

**Comment by JasonGlazer** [comment]
Interesting, I will take a look.

**Comment by JasonGlazer** [comment]
@mjwitte this should address the missing demand values that you found.

**Comment by mjwitte** [comment]
Missing values are there now.

**Pull request merged**
