### PR TITLE
Coil leaving air humidity ratio in Coil Sizing Summary shows wrong unit (temperature)

### LINKED ISSUE #7565: Imperial conversion of coil leaving air humidity ratio in Coil Sizing Summary shows temperature
Issue overview
--------------
Test of example file 5ZoneWaterCooled_HighRHControl shows incorrect conversion of humidity ratio in Coil Sizing Summary and Coil Sizing Details report in column "Coil Leaving Air Humidity Ratio at Ideal Loads Peak [F]".

Only change to example file is:

  OutputControl:Table:Style,
    HTML,                    !- Column Separator
    InchPound;

image

The Component Sizing Summary report for Coil:Cooling:Water is also missing units for humidity ratio.

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (use example file 5ZoneWaterCooled_HighRHControl or any water coil file)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7565
 - Coil Leaving Air Humidity Ratio in Coil Sizing Summary was using Celsius as unit
    * Images from HTML: [Ori (SI)](https://user-images.githubusercontent.com/5479063/67211683-6fe3b880-f41b-11e9-9c48-cccf4b0a11d1.png), [New (SI)](https://user-images.githubusercontent.com/5479063/67211718-7d00a780-f41b-11e9-9f5e-c4b91e669ef8.png), [New (IP)](https://user-images.githubusercontent.com/5479063/67211760-8db11d80-f41b-11e9-8cad-5e0c2a2443bc.png)

 - Standardized around kgWater/kgDryAir throughout the code base
 - Updated UnitConv accordingly. 

 - Adding units for  Design Inlet/Outlet Air Humidity Ratio in WaterCoils.cc
     * Ori:
image
    * New (SI):
image
    * New (IP):
image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport: N/A
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label: N/A
 - [x] If structural output changes, add to output rules file and add OutputChange label: N/A
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies: N/A

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Whoa, I wasn't expecting 32 files changed, but I see now it's heavily just comment changes.  There are a few conflicts in some files that got overhauled in the plant refactor.  Unless you specifically made functional changes in those files I think the safest thing would just be to accept the `develop` version of those files and then reapply any comment fixes you made.  If you are able to handle that I'm assuming this could drop in.

**Comment by mjwitte** [comment]
@Myoldmopar I'm actually working on the merge as we speak.

**Review by mjwitte — APPROVED** [review]
Reviewed a few table diffs. Confirmed that defect file is fixed. Unit tests all run. Added an entry in output rules (technically not a structural change but good to highlight this anyway since column headings change). Will merge after CI finishes.

**Comment by jmarrec** [comment]
Thanks for the review!

**Pull request merged**
