### PR TITLE
Enable more compiler warnings and clean them up

### PR DESCRIPTION
**Pull request by Myoldmopar**
This phase included:
- [x] Turning up compiler warnings
- [x] Fixing unused variables (@myoldmopar)
- [x] Fixing unused parameters (@mbadams5)
- [x] Fixing a few uninitialized variables (@myoldmopar)
- [x] Turning compiler warnings back down

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Here goes trial 2, @mbadams5 :smile: 

I'm working through them, so don't worry about chipping in, unless you are so bored that you can't even believe it.

**Comment by Myoldmopar** [comment]
This is going really well.

The remaining Clang warnings are [here](http://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-beefd14caf228a753bf900fe8fb66f19e2cec153-x86_64-MacOS-10.9-clang.html#build)  There are 3:
- 2 Objexx unused variable warnings, though I don't understand how.  @DeadParrot Could you peruse for a moment and help me understand why it might be complaining about those unused variables?
- 1 gtest warning that I'd like to just mute.  @kbenne, what is your preferred **shut-up** protocol for library warnings?

**Comment by DeadParrot** [comment]
@Myoldmopar if you turn on unused warnings in release builds it will complain about variables only used in asserts, like these, since they are removed in those compiles. I have hit these before but these 2 were missed in the recent update pass. I will push up the revisions to eliminate the warnings and make a PR.

PR created: #4923

**Comment by DeadParrot** [comment]
@Myoldmopar The gtest warning is a [known issue](https://code.google.com/p/googletest/issues/detail?id=433) and one fix is to add  -Wno-missing-field-initializers to the gtest clang options.

**Comment by Myoldmopar** [comment]
@kbenne Would you care to be merger on this?  Nothing was added. @mbadams5 and I just worked to clean up a ton of compiler warnings, almost entirely unused variables and parameters.  I then muted the compiler warnings again to get a merge checkpoint.  Next week or so I'll turn them back up and start addressing the rest of them.  Eventually `-Wall -Wpedantic -Wextra`, right @mbadams5 !!?

**Comment by mbadams5** [comment]
@Myoldmopar Hopefully those, if not more...

**Comment by kbenne** [comment]
Hard to do much code review with the scale of the diff, so I will merge leaning on the test results heavily.  I did look at the compiler flag changes.  Looks like you are close to your goal `-Wall -Wpedantic -Wextra` just haven't got pedantic.

**Comment by kbenne** [comment]
@Myoldmopar looks like you are continuing the work under the same Pivotal ticket so I will leave it open and leave the branch here too.

**Pull request merged**
