### PR TITLE
Added support for tool coupling.

### PR DESCRIPTION
**Pull request by tsnouidui**
This addresses issue #5714 and add support for FMI tool coupling for the FMU parser.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@tsnouidui Can you comment on the cppcheck concern above?

**Comment by tsnouidui** [comment]
@Myoldmopar A bad commit managed to sneak in. I reverted some changes. Let see if this fixes the previous issue.

**Comment by Myoldmopar** [comment]
OK, we're having an issue with CI, so it may be a day or two before it catches up again.

**Comment by Myoldmopar** [comment]
Thanks @tsnouidui, cppcheck is cleaned up, and I have no comments on the code changes.

**Pull request merged**
