### PR TITLE
NFP dedicated exhaust system for verstile exhaust configurations

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - NFP draft for a new feature development on allowing more flexible exhaust air configurations for multiple airloops, to deal with situations such as when an exhaust system must span across multiple airloops.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by EnergyArchmage** [comment]
One application for such exhaust systems is health care.  ANSI/ASHRAE/ASHE Standard 170-2013 Ventilation of Health Care Facilities specifies that certain types of spaces have a requirement that "All Room Air Exhausted Directly to Outdoors,"  e.g. ER waiting rooms, laboratories, laundry, etc.   

Presumably users will want/need to show the exhaust flows and exhaust fan energy are being modeled correctly for such spaces.  For VAV systems, whenever the loads are high and the flow is larger than the minimum total ACH, the zone exhaust flows will have to track the supply air flow rates.    Currently this sort of tracking can only be modeled using the system return air and outdoor air mixer, but that is explicitly disallowed for such spaces in Std. 170.  It may be out of scope for this project, but for Std. 170 the exhaust fan modeling should be improved to allow both autosizing, so that the zone exhaust fan is as large as the primary air supply, and during operation the zone exhaust flows **vary** to match the supply air entering the zone at each timestep. 

image
image

It may make sense to move the zone exhaust fan from legacy code to the newer Fan:SystemModel code base and allow for variable speed.

**Comment by jcyuan2020** [comment]
@EnergyArchmage Thank you!

**Comment by nrel-bot-3** [comment]
@jcyuan2020 @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Just an NFP here with a couple of comments. Closing this. Will start a new branch when work resumes.

**Pull request closed without merging**
