### PR TITLE
Fix air mass flow rate in radiative convective HW baseboard heater

### PR DESCRIPTION
**Pull request by wfbuhl**
Addresses #4347 
The use of rated water mass flow to set the air mass flow was incorrect. Instead we use maximum water mass flow.

### CODE REVIEW

**Comment by wfbuhl** [comment]
I expect 2 files to show significant differences.

**Comment by mjwitte** [comment]
If the equation you changed shows in the Engineering Reference, then it should be updated to match.

**Comment by wfbuhl** [comment]
The Eng Ref does not show this equation. But it does indicate that the air
mass flow rate is twice the water mass flow rate. Whereas currently it is:

  AirMassFlowRate = Constant + Coeff \* DesCoilLoad; // m_dot = 0.0062 +
2.75e-05*q

So this needs to be fixed.

Also I want to check the 3 files that changed. I'll do annual runs and look
at the diffs.

Fred

**Comment by mjwitte** [comment]
@wfbuhl Tested before/after on several example files and they look good.  Just curious, why doesn't the autosized UA value change?

**Comment by Myoldmopar** [comment]
> The Eng Ref does not show this equation. But it does indicate that the air mass flow rate is twice the water mass flow rate. Whereas currently it is:
> 
>  AirMassFlowRate = Constant + Coeff \* DesCoilLoad; // m_dot = 0.0062 +
> 2.75e-05*q
> 
> So this needs to be fixed.

So there are still doc changes to be made?  If so, make sure to pull develop in one more time so you get rid of stray diffs.

**Comment by mjwitte** [comment]
5ZoneWaterCooled_Baseboard-Annual shows deltaTs that are a few degrees larger at times, but the user file doesn't appear to show a significant. different in deltaT.

**Comment by wfbuhl** [comment]
I got minor diffs in annual energy usage for the 3 files in annual runs. I
changed the Eng Ref. and pushed up after catching up with develop.

On Tue, Sep 22, 2015 at 12:19 PM, Michael J. Witte <notifications@github.com

**Pull request merged**
