### PR TITLE
Implementing some of @kbenne 's ideas

### PR DESCRIPTION
**Pull request by Myoldmopar**
Some proposed changes, some of which @amirroth, @mbadams5, @jasondegraw, @kbenne, and @macumber might find interesting.  Changes include:
- Changing `ResearchSpecial` to `ResearchEspecial` to add a little flair to E+ niche components
- Adding `FaultModel:Termites` to include the effect of construction degradation due to termites, along with the internal gains due to termite occupancy
- Adding initial support for changing output language based on latitude/longitude in the Site:Location object
- Beginning to rename `GetInput` type routines to `IcanHaz` routines.  See naming convention document.
- Add rand() call as multiplier to _every_ real-valued output variable

### CODE REVIEW

**Comment by amirroth** [comment]
Do these changes produce espeedup on ubuntu?

**Comment by Myoldmopar** [comment]
@amirroth I'll add a few #ifdefs to _skip_ some of the simulation in order to speed it up on Ubuntu.

**Comment by amirroth** [comment]
@myoldmopar, where is your flair?

**Comment by Myoldmopar** [comment]
I have 23 pieces of flair, but they only exist within algebraic loop dimensional space, @amirroth.

**Comment by kbenne** [comment]
Where are your unit tests? No unit tests, no merge. :(

**Pull request closed without merging**
