### PR TITLE
Remove top-level "using namespace" statements

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
Previously, `EnergyPlus.hh` had a couple `using namespace` statements that contaminated the top-level namespace and made the inclusion of other third party libraries (e.g. the fmt library) very difficult due to the name clashes. For most objects, the ObjexxFCL forward declaration header is included and then the object is used in a using statement. A similar procedure is used for functions. A few cases had to be treated differently:

  * The `gio` namespace was included in such a way that it was easier to prepend `ObjexxFCL::` than to try to work out another way
  * The `abs` function caused problems for GCC once the `using namespace` was removed. To address this, the C++ standard library was used in most cases by prepending `std::`. It's possible that this should also be done with `min` and `max`.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by jasondegraw** [comment]
Fixes #6986

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by jasondegraw** [comment]
@Myoldmopar The additional `.get<std::string>()` calls I added in the merge up to develop are needed because ObjexxFCL was providing an `operator+` that's no longer accessible after the header changes. At least that's what Visual Studio is telling me.

**Comment by Myoldmopar** [comment]
@jasondegraw any idea why those last CI results show a unit test failure (not just an anomaly, but on both Linux and Mac)?

**Comment by jasondegraw** [comment]
@Myoldmopar I believe that is a merge failure in the hybrid model code. There were conflicts there that were hard to work out due to some differing ideas on formatting. I'll break out the git time machine and get that straightened out.

**Comment by jasondegraw** [comment]
@Myoldmopar Also known as PBKAC

**Comment by Myoldmopar** [comment]
Great!  No conflicts!  This is the last one.  Once Linux blesses it later tonight I'll merge this in and tag RC1.

**Comment by Myoldmopar** [comment]
Tempted to merge now since Linux looks happy but I'll give it a little longer I guess.  Once unit tests are happy I may go ahead and merge though.

**Comment by rraustad** [comment]
I'd have to agree. Simple change.

**Pull request merged**
