### PR TITLE
Warn when the compact schedule minute does not line up with time step

### PR DESCRIPTION
**Pull request by JasonGlazer**
Fixes issue #4401 
When Compact:Schedule is used to define a schedule which changes at times which are not aligned with the timestep, e.g. 7:26am, and "Interpolate" is not specified, then then schedule will not change until the next timestep begins. A warning has been added.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Do not merge yet, I still have not added code to check for status of interpolation.

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar This pull request is not passing 100% of the tests, a few are failing. Is this indicative of how develop is running the tests right now? If not, I will try to figure out how the code change is impacting these couple of files.

**Comment by mjwitte** [comment]
@JasonGlazer This branch is a bit behind develop, but these are schedule errors, probably due to these changes?

```
+   ** Warning ** ProcessScheduleInput: DecodeHHMMField, Invalid "until" field value is not a multiple of the minutes for each timestep: UNTIL: 13:10
+   **   ~~~   ** Other errors may result. Occurred in Day Schedule=HOT WATER DEMAND SCHEDULE_dy_1
```

**Comment by mjwitte** [comment]
@JasonGlazer So, these may be legitimate errors?  if so, then we should think about fixing these example files to make them line up?

**Comment by JasonGlazer** [comment]
That is the new error message that I added to address the issue.

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte Looks like this is ready to be merged.

**Pull request merged**
