### PR TITLE
Update life cycle cost tables to handle water utility tariff costs correctly

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #5006 

Water costs are shown in the correct column of the Operating Cash Flow table in the Life Cycle Cost Report. Also changed the title of Energy Cost Cash Flows (Without Escalation) to Energy and Water Cost Cash Flows (Without Escalation). Also updated Present Value for Recurring, Nonrecurring and Energy Costs to show water in the correct places.
- [X] Code style (parentheses padding, variable names)
- [X] Functional code review (it has to work!)
- [X] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [X] Unit Test(s)
- [x] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@DavidGoldwasser please let me know if this addresses all the issues you saw.

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar looks like this is ready to review and merge. The original Win64-Windows-7-VisualStudio-12 CI case had one failure that I could not reproduce. When I asked the CI machine to rerun that case everything passed.

**Comment by mjwitte** [comment]
Merged in develop, tested the defect file, did some cleanup in the unit test (like adding it to the cmake list . . .) and a little editing in the output rules.  Once CI comes back, should be ready to go in.

**Comment by mjwitte** [comment]
Cleaned up build warning, wait for another round of CI tests.

**Comment by mjwitte** [comment]
Last minute thought - it would be nice to add water use and tariff to 5ZoneEconomicsTariffAndLifeCycleCosts.  Use the objects that were added to the defect file?  Perhaps scaled down a bit?

**Comment by JasonGlazer** [comment]
@mjwitte Those were totally made up numbers. I would need to find out a typical water rate. Do you want me to do that research?

**Comment by mjwitte** [comment]
Seems we should be able to find a reasonable value for hot and cold water use in a small office without too much effort.  Any suggested values in Appendix G or in the reference buildings?

**Comment by JasonGlazer** [comment]
@mjwitte I just added some water costs to the 5ZoneEconomicsTariffAndLifeCycleCosts.idf file.

**Pull request merged**
