### PR TITLE
Fix VS2017 build error in OpenMP code

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
From @rraustad, there seems to be a build error with Visual Studio 2017 related to the new OpenMP code added for the file conversions.
image

This PR should fix the issue for VS 2017, while not affecting other operating systems/compilers.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I've got no problem with this going in, but I'm not able to reproduce the problem or verify the fix.  @rraustad can you verify this works?

**Comment by rraustad** [comment]
VS2017 compiler error on one of my branches (using Rebuild Solution).

```
27>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\src\ConvertInputFormat\main.cpp(503): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type
27>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\src\ConvertInputFormat\main.cpp(507): fatal error C1903: unable to recover from previous error(s); stopping compilation
27>Done building project "ConvertInputFormat.vcxproj" -- FAILED.
```

and with these changes:

```
54>ConvertInputFormat.vcxproj -> C:\Users\RRaustad\Documents\MyProjects\Builds\EnergyPlus\Products\Debug\ConvertInputFormat.exe
54>Done building project "ConvertInputFormat.vcxproj".
```

but there are many other warnings that I don't understand.

```
54>main.cpp
54>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\numeric(26): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
54>        with
54>        [
54>            _Ty=unsigned long
54>        ]
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(12176): note: see reference to function template instantiation '_Ty std::accumulate<std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,unsigned long,nlohmann::detail::binary_writer<nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,char>::calc_bson_object_size::<lambda_c3a75d6aa8cfa5472b9d749134abdb95>>(const _InIt,const _InIt,_Ty,_Fn)' being compiled
54>        with
54>        [
54>            _Ty=unsigned long,
54>            StringType=std::string,
54>            _InIt=std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
54>            _Fn=nlohmann::detail::binary_writer<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,char>::calc_bson_object_size::<lambda_c3a75d6aa8cfa5472b9d749134abdb95>
54>        ]
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(12171): note: while compiling class template member function 'size_t nlohmann::detail::binary_writer<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,char>::calc_bson_object_size(const std::map<StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,doj::alphanum_less<StringType>,std::allocator<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>> &)'
54>        with
54>        [
54>            StringType=std::string
54>        ]
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(12187): note: see reference to function template instantiation 'size_t nlohmann::detail::binary_writer<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,char>::calc_bson_object_size(const std::map<StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,doj::alphanum_less<StringType>,std::allocator<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>> &)' being compiled
54>        with
54>        [
54>            StringType=std::string
54>        ]
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(21259): note: see reference to class template instantiation 'nlohmann::detail::binary_writer<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,char>' being compiled
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(21258): note: while compiling class template member function 'void nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::to_bson(const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::detail::output_adapter<char,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>)'
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\src\ConvertInputFormat\main.cpp(302): note: see reference to function template instantiation 'void nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::to_bson(const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::detail::output_adapter<char,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>)' being compiled
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\nlohmann/json.hpp(22492): note: see reference to class template instantiation 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' being compiled
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\ObjexxFCL\src\ObjexxFCL/IndexSlice.hh(246): note: see reference to class template instantiation 'std::initializer_list<int>' being compiled
54>C:\Users\RRaustad\Documents\MyProjects\EnergyPlus\third_party\ObjexxFCL\src\ObjexxFCL/IndexRange.hh(114): note: see reference to class template instantiation 'std::initializer_list<ObjexxFCL::Index>' being compiled
54>ConvertInputFormat.vcxproj -> C:\Users\RRaustad\Documents\MyProjects\Builds\EnergyPlus\Products\Debug\ConvertInputFormat.exe
54>Done building project "ConvertInputFormat.vcxproj".
```

**Review by rraustad — COMMENTED** [review]
These changes appear to work but with new compiler warnings so others will have to make the decision.

    ========== Rebuild All: 54 succeeded, 0 failed, 7 skipped ==========

**Comment by Myoldmopar** [comment]
@mbadams5 any thoughts on the json related warnings?  Ignore them and merge this?

**Comment by mbadams5** [comment]
@Myoldmopar @rraustad I just compiled this branch on my Windows 10 VM with VS2017 (15.9.18) using CMake 3.16.2 and it compiled without any of the above warnings... I don't know how to recreate @rraustad's warnings.

**Comment by rraustad** [comment]
My branch is behind develop so let me merge and try again.

**Comment by rraustad** [comment]
Well, I see the same warnings but I need Py3 now to finish compiling. Using MSVS Pro 2017 V 15.9.12.

**Comment by mbadams5** [comment]
@rraustad Can you upgrade to 15.9.18 and see if that fixes the issue?
Which branch are you trying to compile?

**Comment by rraustad** [comment]
No need. Warnings are gone with Py 3.8.1. Does that make any sense to you? I am using branch: NFP---Connect-split-DX-to-VRF-refrigerant-loop. CMake V 3.14.5

    44>------ Rebuild All started: Project: ConvertInputFormat, Configuration: Debug Win32 ------
    44>Building Custom Rule C:/Users/RRaustad/Documents/MyProjects/EnergyPlus/src/ConvertInputFormat/CMakeLists.txt
    44>CMake does not need to re-run because C:/Users/RRaustad/Documents/MyProjects/Builds/EnergyPlus/src/ConvertInputFormat/CMakeFiles/generate.stamp is up-to-date.
    44>main.cpp
    44>ConvertInputFormat.vcxproj -> C:\Users\RRaustad\Documents\MyProjects\Builds\EnergyPlus\Products\Debug\ConvertInputFormat.exe

**Comment by rraustad** [comment]
Up to date with develop, warnings are gone with fresh CMake and rebuild. OK to merge.

========== Rebuild All: 44 succeeded, 0 failed, 7 skipped ==========

37>------ Skipped Rebuild All: Project: NightlyMemoryCheck, Configuration: Debug Win32 ------
38>------ Skipped Rebuild All: Project: Nightly, Configuration: Debug Win32 ------
39>------ Skipped Rebuild All: Project: Experimental, Configuration: Debug Win32 ------
40>------ Skipped Rebuild All: Project: Continuous, Configuration: Debug Win32 ------
41>------ Skipped Rebuild All: Project: RUN_TESTS, Configuration: Debug Win32 ------
49>------ Skipped Rebuild All: Project: documentation, Configuration: Debug Win32 ------
51>------ Skipped Rebuild All: Project: INSTALL, Configuration: Debug Win32 ------

**Comment by rraustad** [comment]
@Nigusse just told me he saw the same warnings and upgraded to 15.9.18 as @mbadams5 suggested and the warnings disappeared. I just compile release to be sure and everything is OK. I am merging this.

**Comment by rraustad** [comment]
Tested on VS2017 with error prior to this fix and passing with this fix. Multiple ways to eliminate the warnings found during testing (see discussion), but even with warnings with older versions of MSVS the program compiles.

**Pull request merged**
