### PR TITLE
Allow regular expressions as keys for Output:Variable

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
This pull request allows regular expressions to be used to better filter Output:Variable keys. Previously, only the exact key or all keys (*) were valid options. Now most typical regular expressions are allowed as options. Check [RE2 Syntax](https://github.com/google/re2/wiki/Syntax) for allowed regular expressions as well as what regular expression syntax RE2 supports.

One key note is that ANY regular expression with a comma (`,`) will fail regardless if it is valid regular expression syntax or not. This is due to the nature of the EnergyPlus input processor since fields are delimited by commas. Thus any comma is seen as the end of one field and the beginning of another.

How this regular expression filtering is powerful:

Given the following IDF snippet
```
NodeList, Zone1Inlets, SalesFloor InletNode 1;
NodeList, Zone2Inlets, SalesFloor InletNode 2;
NodeList, Zone3Inlets, SalesFloor InletNode 3;
NodeList, Zone4Inlets, Office InletNode 1;
NodeList, Zone5Inlets, Office InletNode 2;
NodeList, Zone6Inlets, Office InletNode 3;
```

Previously, if you wanted all `SalesFloor InletNode`'s `System Node Mass Flow Rate`, you had to individually write each as an Output:Variable as follows...

```
Output:Variable, SalesFloor InletNode 1, System Node Mass Flow Rate, timestep;
Output:Variable, SalesFloor InletNode 2, System Node Mass Flow Rate, timestep;
Output:Variable, SalesFloor InletNode 3, System Node Mass Flow Rate, timestep;
```
Or you could select ALL nodes `System Node Mass Flow Rate`, which would include the Office nodes...
```
Output:Variable, *, System Node Mass Flow Rate, timestep;
```
Now you can write it much more concisely with a regular expression...
```
Output:Variable, SalesFloor InletNode [\d]+, System Node Mass Flow Rate, timestep;
```

This is just a simple example, but begins to show the filtering capabilities.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
lol   https://github.com/NREL/EnergyPlus/pull/6017/files?w=1#diff-064872bdf78c6174c034845f5426b83f

**Comment by Myoldmopar** [comment]
The E+ changes are super minimal here, and look good.  Unit tests look good.  I think this can drop right in easily.  This will be a big improvement!  I'll give CI some time to get through the platforms.

**Comment by mjwitte** [comment]
@mbadams5 Will this alter the case of the variable keys/names in the output?
And I assume the licensing of the 3rd party package has been cleared with @jasondegraw

**Comment by mjwitte** [comment]
@mbadams5 Are there I/O Ref changes for this?

**Comment by jasondegraw** [comment]
@mjwitte re2 is BSD-style, so we're all good.

**Comment by mbadams5** [comment]
@mjwitte Yes, the `\retaincase` will alter the case of the variable keys in the output, at least as far as how I understand it to work.  The issue was that without it, the input processor was uppercasing the key and was causing the regular expressions to not match. The code will still use a case-insensitive comparison fall back method if the regular expression engine doesn't find a match.

There are no needed changes to the existing I/O Ref but I guess I could add new text about the regular expressions if needed.

**Comment by Myoldmopar** [comment]
Yeah, good call.  The IO ref could definitely use some info.  @mbadams5 Can you add some content to the relevant output object(s) to describe the capabilities and the limitations (no comma, repetition)?

**Comment by mbadams5** [comment]
@Myoldmopar I updated the I/O Ref to include information about the new regular expression option.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
OK, I'm going to get this in.  If anything comes up due to the abrupt merge I'll deal with it.  Thanks @mbadams5, this is a very cool enhancement.

**Comment by mjwitte** [comment]
Then the case change needs a mention in the output rules doc.

-------- Original message --------

**Comment by mbadams5** [comment]
For posterity, the `\retaincase` ends up NOT affecting the ESO file and outputs. Everything is still upper-cased, so there is no need to update the output rules doc.

**Comment by jmarrec** [comment]
Major +1 @mbadams5! Thanks for this!

**Pull request merged**
