### PR TITLE
Eliminate Other Usages of readItem

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - To be merged after #8819 
 - Replaces some other usages of ```readItem``` in lieu of ```ProcessNumber```. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
I've been intermittently trying to determine the performance effects of this PR over the last few days. I ran the suite Tuesday with the regression tool and came up with about a 1% reduction in the runtime of the full test suite. From that run, there were about 20-ish % of the files that actually went *up* in runtime, but overall, the time from the full suite was down. My computer has a history of thermal throttling (sometimes below 50%), so it could be possible that some of those effects carried over on to this since the baseline simulations are run first, then the mod branch sims. Once the computer warms up, those later sims might take longer just due to the throttling.

So I ran it again last night overnight limiting the regression tool to a single core. All but nine files were even or down in runtime. The full suite runtime went from 5072s to 4354s which is a 14% reduction. For the nine files that went up, I ran those again three times this morning and averaged the results. After that, only 1 actually showed an increase in runtime. This "14%" may or may not be the actual number, but I believe we can state that this is helping. Although, exactly how much would need some further investigations.

Caveats
- The regression tool is just grepping the runtime from the eplusout files, and it's only reporting to 1 decimal in the runtimes summary file. The regression tool should probably be measuring the time independently for more accuracy.
- My computer - obviously the throttling is having some effect. I've tried to mitigate that as best I can, but it's probably having some effects due to how the simulations are ordered.
- Maybe wall runtime isn't the best measure, and we should just look at the Valgrind numbers reported on CI, though they are not reported for the full suite.

**Comment by amirroth** [comment]
Valgrind (i.e., instruction count) is only loosely correlated with performance. Obviously it matters, but when you consider that mispredicted branches and cache misses (and some arithmetic operations like division) take 10-30X the time of an average instruction, you see that not all instructions are created equal.

**Comment by shorowit** [comment]
I had sent this information to @mitchute in an email, but I am seeing impressive runtime reduction for a single residential model where readItem calls (weather processing) represent a significant fraction of the total simulation runtime:

- `develop`: 8.1 sec
- `eliminate-readitem`: 5.4 sec
- Savings: 33%

The above values were averaged over 3 runs, but very reproducible. Caveat: these runs were on Windows.

**Comment by Myoldmopar** [comment]
I'm going to pull develop in after a quick burst of merges just now to make sure it's all building and running fine.  I anticipate this merging in the morning if no one has any additional concerns.

**Comment by Myoldmopar** [comment]
All good here.  Thanks @mitchute, merging in now.

**Pull request merged**
