### PR TITLE
Add accelerated initialization to Foundation:Kiva surfaces

### PR DESCRIPTION
**Pull request by nealkruis**
Pull request overview
---------------------
This follows on the recent addition of Kiva to perform ground heat transfer calculations. It is an internal (i.e., no interface changes) modification to the way the Kiva ground temperatures are initialized. In future versions we may expose some settings to modify this from user input.

Work completed for:

- Subcontract AEU-7-70112-01: “2017 EnergyPlus Foundation Heat Transfer Algorithm Model Development”

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully

### CODE REVIEW

**Comment by nealkruis** [comment]
@nmerket @EnergyArchmage @Myoldmopar @mjwitte This is ready for review. As discussed on the call (a while back), this is an internal change to improve the initialization specifically for sizing periods. Please let me know if you have any comments.

**Comment by EnergyArchmage** [comment]
I have reviewed the code changes here and seems okay. 

the integration coverage CI machine is catching 3 assertions that need to be dealt with I think.

 [with T = EnergyPlus::DataHeatBalance::ConstructionData]: Assertion `contains( i )' failed.

**Comment by nealkruis** [comment]
@EnergyArchmage Thanks for pointing those out...I'll look into them and get them settled.

**Comment by Myoldmopar** [comment]
Are you satisfied with 7aa262c being the last commit here?

**Pull request merged**
