### PR TITLE
Fixes #4564 and #4798

### LINKED ISSUE #4564: Cooling airflow rate being used in heating mode for variable speed cooling coils
from @jonwinkler,

The attached two IDFs are identical with the exception of the cooling coil type. 1.idf uses the `Coil:Cooling:DX:SingleSpeed` and 1_var_speed.idf uses `Coil:Cooling:DX:VariableSpeed`. A gas furnace and the `AirLoop:UnitaryHeatCool` object are used in both files.

The issue is with the heating air flow rate. When the variable speed cooling coil is used, the cooling airflow rate is being used in heating mode. The heating airflow rate specified in the unitary object is not being used. In the attached Excel files I’ve highlighted several hours when the runtime fraction of the heating coil equals 1. You’ll see in 1_var_speed.xlsx that the airflow rate is equal to the cooling air flow rate. The results are correct in 1.xlsx.

This has a significant impact on the fan energy. Please let me know if you want to discuss.

(I’ve also attached a schedule file you’ll need to run the simulations. The path in the IDFs will have to be updated accordingly.)

### PR DESCRIPTION
**Pull request by rraustad**
Fixed flow rate issue with variable speed coils and fixed another issue with max iteration warning reporting.

### CODE REVIEW

**Comment by mjwitte** [comment]
@rraustad Tested defect files for #4564 and the flow rates are correct now.  I'm not sure how to test the changes for the max iteration reporting.  But I see in the CI test results, the max iteration warnings are gone now for DirectIndirectEvapCoolersVSAS.  Is that expected?

**Comment by mjwitte** [comment]
@rraustad Not sure what's up with the two Linux debug tests.  Going to delete those results and force a rebuild.

**Comment by rraustad** [comment]
Run HVACTemplate_5ZoneUnitarySystem in V8.2. You should see the max iteration warnings and if you add the display diagnostics to the idf, they won't show up. In this branch they will show up.

As far as DirectIndirectEvapCoolersVSAS, it depends on what caused the max iteration warnings on whether or not they remain or are corrected. I can see how they could disappear (and I would believe is was changes to the VS coil object not the changes to max iteration warnings). In the defect file, there are now max iteration warnings since the correct flow rates are used. I'm still trying to figure out how I could possibly avoid these warnings when different flow rates are used for cooling and heating...and outdoor air is included. This is a separate issue for all VS or MS coils that use different flow rates.

**Comment by mjwitte** [comment]
Regarding DirectIndirectEvapCoolersVSAS, results do change (about 1% more energy, and about 5% increase in water use) vs. 8.2.9.  I need to roll a current develop and compare.

**Comment by mjwitte** [comment]
@rraustad Current develop vs this branch shows similar changes for DirectIndirectEvapCoolersVSAS.  This file does have AirloopHVAC:UnitaryHeatCool with single-stage gas heat and variable speed DX cooling, so this would be the combination that was fixed.

**Comment by rraustad** [comment]
Added unit test for VS furnaces

**Comment by mjwitte** [comment]
This has been replaced by #4803 , so closing this PR.

**Pull request closed without merging**
