### PR TITLE
Fixed the degree day bases used with the LEED and Climatic summaries

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #5083. Also started OutputChanges8-5-0-to-8-6-0.md since first change expected for 8.6 release.
- [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [X] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- [x] If output changes, including tabular output structure, add to output rules file for interfaces
  …as well as added unit test and started new OutputChanges8-5-0-to-8-6-0.md

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar @mjwitte I started OutputChanges8-5-0-to-8-6-0.md with this checkin. I assume that it won't be part of 8.5 but if you want to move it we can just move the paragraph I wrote to the OutputChanges8-4-0-to-8-5-0.md document.

**Comment by JasonGlazer** [comment]
@Myoldmopar @mjwitte @amirroth A bunch of the tests fail with the following:

evice id: i386-Windows-7-VisualStudio-12
Comparing `C:/CI/EnergyPlus-9d4086aaed-i386-VS12/build/testfiles/1ZoneEvapCooler` with `C:/ci/EnergyPlus-d6014cbff3-i386-VS12/build/testfiles/1ZoneEvapCooler`
Processing (Diffs) : 1ZoneEvapCooler
Traceback (most recent call last):
File "C:/CI/EnergyPlus-d6014cbff3-i386-VS12/regressions/Testing/RegressionSuite/Scripts/RunComparison.py", line 76, in
runner.process_diffs_for_one_case(entry, base_dir, mod_dir, mod_dir)
File "C:\CI\EnergyPlus-d6014cbff3-i386-VS12\regressions\Testing\RegressionSuite\Scripts\runtests.py", line 442, in process_diffs_for_one_case
path_to_tablediff_log)))
File "C:\CI\EnergyPlus-d6014cbff3-i386-VS12\regressions\Testing\RegressionSuite\Scripts\TableDiff.py", line 432, in table_diff
hdict2soup(abs_diff_soup, uheading1, count_of_tables, abs_diff_dict, h_thresh_dict, horder1)
File "C:\CI\EnergyPlus-d6014cbff3-i386-VS12\regressions\Testing\RegressionSuite\Scripts\TableDiff.py", line 203, in hdict2soup
tdtag.append(str(hdict[h][i]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 37: ordinal not in range(128)

Any ideas what this means?

**Comment by Myoldmopar** [comment]
Well, it means it hit an invalid byte sequence when trying to process a table entry.  The _only_ thing I could guess right now is that there is a weird non-printing character or something.  Or maybe when you saved the python file, it tried to do some conversion of some of the characters.  Might be able to fix it by adding the unicode declaration at the top of the file per: http://stackoverflow.com/questions/10589620/syntaxerror-non-ascii-character-xa3-in-file-when-function-returns-%C2%A3

**Comment by mbadams5** [comment]
@Myoldmopar Could it be python 2 vs 3 issue? In python3, strings are unicode by default. I think your suggestion to add `from __future__ import unicode_literals` or 

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
```

is probably the right solution. Basically it is trying to print out the unicode for the degree sign and python2 doesn't realize it is unicode by default.

**Comment by Myoldmopar** [comment]
Yeah.....but it doesn't look like he changed that.  That's what is confusing.  It was already printing those out, right?

**Comment by JasonGlazer** [comment]
I changed some lines that use the degree symbol but they were there already.

**Comment by JasonGlazer** [comment]
It is finding differences on lines with degree symbols so maybe that is enough. So which Python files do I need to fix? TableDiff.py, RunComparison.py, runtests.py? All of them?

**Comment by Myoldmopar** [comment]
It looks like TableDiff is the culprit from that error message, but once that is updated, it might reveal another file or two that also need it.  Not too many files in use in there though, so even if it takes a couple iterations, it won't be an endless cycle.

**Comment by JasonGlazer** [comment]
If I make the change TableDiff.py in the EnergyPlusDevSupport repo, does that automatically get used in the CI testing?

**Comment by Myoldmopar** [comment]
Yes....and no.  Depends on which branch you make the fix.  The CI system is set up so it can use a different branch over in DevSupport for your testing.  The branch to use over in DevSupport is defined in the CI yaml files, like right here: https://github.com/NREL/EnergyPlus/blob/c87e61b44bce627bc0fac6f0574d9b018015a3be/.decent_ci.yaml#L5

So, if you make the TableDiff.py change in a branch over there called "JasonBranch", then just change the line in the yaml file in this branch over here in EnergyPlus itself to point to "JasonBranch".  The CI tests will then use this modified version.  Once it looks good, we can merge that branch over in DevSupport into master and change this branch to point back to master.  Sorry if that's a bit fuzzy.

**Comment by JasonGlazer** [comment]
Got it, thanks.

**Comment by JasonGlazer** [comment]
@Myoldmopar @mjwitte  @amirroth  @mbadams5 @santoshphilip I think I have come across a bug in TableDiff and BeautifulSoup that is because a lines that have differences in the HTML files include the degree symbol: \xb0 

Here are the test files:

[29.zip](https://github.com/NREL/EnergyPlus/files/199865/29.zip)

I have made a small change in TableDiff.py adding two lines near the top that are supposed to help with unicode. See:

https://github.com/NREL/EnergyPlusDevSupport/pull/47

In addition I changed line 205 from 

tdtag.append(str(hdict[h][i]))

to

tdtag.append((hdict[h][i]).encode('utf-8'))

But all this does is move the problem into BeautifulSoup 

C:\temp\29>python TableDiff.py base\5ZoneEndUses-devtbl.htm mod\5ZoneEndUsestbl.htm out_abs_diff.htm out_rel_diff.htm err_log.txt my
_summary_file.csv
Traceback (most recent call last):
  File "TableDiff.py", line 500, in <module>
    sys.exit(main())
  File "TableDiff.py", line 495, in main
    table_diff(thresh_dict, inputfile1, inputfile2, abs_diff_file, rel_diff_file, err_file, summary_file)
  File "TableDiff.py", line 434, in table_diff
    hdict2soup(abs_diff_soup, uheading1, count_of_tables, abs_diff_dict, h_thresh_dict, horder1)
  File "TableDiff.py", line 205, in hdict2soup
    tdtag.append((hdict[h][i]).encode('utf-8'))
  File "C:\temp\29\BeautifulSoup.py", line 432, in encode
    return self.decode().encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 37: ordinal not in range(128)

This is also using the latest BeautifulSoup 3.2.1, the normal distribution uses 3.1.0.1. When I used 3.1.0.1 I got the same problem. There is also a version of BeautifulSoup 4.4.1 but I did not try that since it requires more changes to the code. 

I am discussing this here instead of on EnergyPlusDevSupport repo because this is public and wanted to include Santosh in the discussion.

Any ideas?

**Comment by JasonGlazer** [comment]
@Myoldmopar This is the issue we discussed on the call yesterday that I was hoping you could try to figure out.

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar this fix is not moving forward because of an issue with TableDiff not liking to compare stuff with the degree symbol. If we can't fix this now, do either of you have a suggestion on how to separate the issues so that the TableDiff issue doesn't block this fix from being incorporated?

**Comment by Myoldmopar** [comment]
Did you happen to try propagating the changes further through that testing code?  There's something like 10 Python files, and it might take pushing the unicode declaration throughout that entire code so the entire operation is unicode.

**Comment by JasonGlazer** [comment]
I will give it a try.

**Comment by JasonGlazer** [comment]
The latest changes to the Python files used in comparing files seems to have resolved the issue seen earlier with the degree symbol. Now it seems like all the comparisons occur but it finds diffs which I believe are all as expected. It has been long enough that I am going to do some retesting locally.

**Comment by JasonGlazer** [comment]
I spot checked the differences (too many failed tests to check each one) and they all seem to be as expected making changes to the LEED report and the ClimaticDataSummary. I am merging in the latest develop but assuming similar results, this is ready to be reviewed and merged.

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar 

This pull request does not improve performance but the change is in the noise range -0.0017% so I think it is probably ok.

The large number of failed tests is more worrisome but it really is as expected since it was a fix to some rows in the ClimaticSummary and LEED Summary tabular reports which are widely used.  The degree days being reported were not using the correct degree day bases. I could not check all the failed tests, there are just too many, but I spot checked probably five to ten for each of the platforms and those were all diffs that were expected. I think we need to extrapolate the the other failed tests are the same issue.

I recommend to go ahead and review and merge this pull request.

**Comment by Myoldmopar** [comment]
@JasonGlazer it looks like your TableDiff fixes are working fine.  Can you go ahead and change:
- the [regression branch](https://github.com/NREL/EnergyPlus/pull/5572/files#diff-1a8b3da72c5ea9e9992980187b4ca729L5)
- [this line](https://github.com/NREL/EnergyPlus/pull/5572/files#diff-cd588b6af83972de5496d052036a1457R34) because I have _no_ idea what that trailing "5572" does 😃

**Comment by JasonGlazer** [comment]
@Myoldmopar lets see how the CI does with this now.

**Comment by JasonGlazer** [comment]
There are the same number of failed tests as before using the TableDiff changes merged in which is exactly as expected. I did a brief spot check again for each machine and all the diffs are as expected. @Myoldmopar or @mjwitte  I think it is ready for your review.

**Pull request merged**
