### PR TITLE
Revert extended min-fields for PlantLoop and CondenserLoop

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
This undoes the extended min-fields for PlantLoop and CondenserLoop that was introduced in #6000 

This *should* come back with no results or eio diffs but many audit and err diffs.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar or @EnergyArchmage The diffs here are as expected.  Table diffs are due to changes in the number of Defaulted Fields	and 
Fields with Defaults.

**Review by EnergyArchmage — APPROVED** [review]
I have reviewed changes and approve them.

**Comment by Myoldmopar** [comment]
Yeah, this looks good.  Lots of diffs, but nothing relevant.  I'll merge this in after taking a look at whether I should stage it against other PRs dropping in.

**Comment by Myoldmopar** [comment]
Nah, this doesn't need to be staged with any other PRs, this is going in.

**Pull request merged**
