### PR TITLE
Ics solar collector #4723

### PR DESCRIPTION
**Pull request by Nigusse**
The parameters were set to default values when the collector is not allocated. This fix resolved the crash in the defect file due to un-allocated ICS collector data.

### CODE REVIEW

**Comment by jasondegraw** [comment]
@Nigusse Your test works for me on Visual Studio, but doesn't seem to work on any of the CI machines. Could you verify that it works for you? I'll see what I can find out Monday on Ubuntu.

**Comment by Nigusse** [comment]
@jasondegraw It works for me as well. I also use Visual Studio. The kind error messages that I saw, I think, may require adding "InitializePsychRoutines();" function in the unit test. Do you want me to add this change commit again and then see how the CI machine works?

**Comment by jasondegraw** [comment]
@Nigusse I'm able to get the failure if I build in Release mode. Adding InitializePsychRoutines() changes the error but it still fails. There may be a problem with the SizePurchasedAir test, which is making it hard for me to figure out what is going on.

**Comment by Nigusse** [comment]
@jasondegraw Are you saying that the "ICSSolarCollector.unit" failure is some how cause by SizePurchasedAir test? I did not understand.

**Comment by jasondegraw** [comment]
@Nigusse It isn't clear yet, but it doesn't look like your test is the problem. I was getting a crash in the SizePurchasedAir test, so it could be there, but it is hard to tell for sure. We've got a couple of builds in progress that should help us figure out what is going on.

**Comment by jasondegraw** [comment]
@Nigusse Since this unit test isn't the problem, I'm going to merge this now. See @Myoldmopar's email for more info.

**Comment by mjwitte** [comment]
@Nigusse @jasondegraw @Myoldmopar The ICSSolarCollector unit test may be missing some needed initializations, even though they don't cause any failures here on Windows with release or debug.  But following the logic in CalcPassiveExteriorBaffleGap, it calls InitExteriorConvectionCoeff which is looking at all sorts of surface attributes that have not been set, e.g. Surface( SurfNum ).ExtWind and Surface( SurfNum ).ExtConvCoeff, and more.  Not sure, but this may be why this unit test is failing in the CI.

**Comment by Nigusse** [comment]
@mjwitte: I do remember setting surface windpeed and convection coefficient values but I could have missed some.  Now, I am working on creating unit test for another issue #4625 (WindowMaterial:Blind:EquivalentLayer), will get back to this issue in about an hour.

**Comment by mjwitte** [comment]
@Nigusse Maybe it's in there and I missed it.

**Comment by jasondegraw** [comment]
@Nigusse If you do end up making changes, it would be good to change the name of the test to "ICSSolarCollectorTest". I missed that in my review.

**Comment by Nigusse** [comment]
I tested the ICSSolarCollectorTest unit test in debug and release modes. It passed in both modes but the PurchasedAirManager unit test failed in release mode. I removed the ICSSolarCollectorTest unit code from build and tested again but the PurchasedAirManager unit test still failed. It appears the PurchasedAirManager unit test failure is not related to ICSSolarCollectorTest.

Corrected the "ICSSolarCollectorTest" name typo (Jason pointed to me). I will commit this change along with minor cleanup shortly.

**Comment by mjwitte** [comment]
@Nigusse I know.  ICS unit test doesn't fail locally but it fails on the CI, which makes it nearly impossible to debug.  Maybe @Myoldmopar can get it fail running locally on Linux?  I fixed the purchased air test last night - it's waiting to be merged #4809 .  Out of curiosity I single-stepped through the ICS test and saw the things I noted above.  So, for example, are you setting Surface( SurfNum ).ExtWind?  I search the unit test file for "ExtWind" and it's not there.

**Comment by Nigusse** [comment]
@mjwitte CalcPassiveExteriorBaffleGap routine requires "Surface( SurfPtr ).WindSpeed" variable and I specified this variable in the unit test.  And the outside convection coefficients was set to ASHRAESimple (Zone( ZoneNum ).OutsideConvectionAlgo = ASHRAESimple;) in the unit test.  So, I did not see the need for "Surface( SurfPtr ).WindSpeed" variable. Let me add/initialize this variable, and test the code again.

**Comment by Nigusse** [comment]
Corrected. 

@mjwitte CalcPassiveExteriorBaffleGap routine requires "Surface( SurfPtr ).WindSpeed" variable and I specified this variable in the unit test. And the outside convection coefficients was set to ASHRAESimple (Zone( ZoneNum ).OutsideConvectionAlgo = ASHRAESimple;) in the unit test. So, I did not see the need for "Surface( SurfPtr ).ExtWind" variable. Let me add/initialize this variable, and test the code again.

**Comment by mjwitte** [comment]
@Nigusse Not talking about .WindSpeed.  If you single step through the unit test, when it enters ConvectionCoefficients::InitExteriorConvectionCoeff it executes this line:

		if ( ! Surface( SurfNum ).ExtWind ) {

And then a few lines later

		{ auto const SELECT_CASE_var( Surface( SurfNum ).ExtConvCoeff );

I don't see either one of these initialized in the unit test.  Setting the zone attribute doesn't have any effect, because we're not running any of the routines that would transfer that to the surfaces.

**Comment by Nigusse** [comment]
@mjwitte Let me initialize these two variables and step though the InitExteriorConvectionCoeff routine code.

**Comment by mbadams5** [comment]
@mjwitte @Nigusse Do you think you need to ' InitializePsychRoutines(); '? Looking at [Linux Debug results](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-648b95450c260bbf3cfc300de1d29a8945629d69-x86_64-Linux-Ubuntu-14.04-gcc-4.8-UnitTestsCoverage-Debug.html) at the failed unit tests, it seems like they are failing on assertions in Psychrometrics. But I could be off on this...

**Comment by mjwitte** [comment]
@mbadams5 Thanks!  Did not see that - much more informative than the reports I looked at.  @Nigusse If you're doing a pull request, would you please add that to the ZoneTempPredictorCorrector.CorrectZoneHumRatTest also?  Or I can do one for both.

**Pull request merged**
