### PR TITLE
Thermostat based on Adaptive Thermal Comfort Model 

### PR DESCRIPTION
**Pull request by hongtz68**
## Pull request overview

ASHRAE Standard 55-2010 and CEN 15251-2007 provide adaptive thermal comfort models for naturally ventilated buildings. The adaptive comfort models are getting used for mechanically cooled and ventilated buildings especially in hot climates to save energy. We propose to enhance the existing ZoneControl:Thermostat:OperativeTemperature object to indicate the applicability of the adaptive comfort model. Users requested this feature.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by hongtz68** [comment]
@mjwitte Thanks for your review, we updated the NFP to DD addressing your comments.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@hongtz68 @lgentile it has been 15 days since this pull request was last updated.

**Pull request merged**
