### PR TITLE
Add 4 new example files

### PR DESCRIPTION
**Pull request by wfbuhl**
4 new example files to illustrate CoilVsSpacePeak feature

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@wfbuhl Re-opening this pull request.

**Comment by Myoldmopar** [comment]
@wfbuhl To get these example files added to the list of tests, they need to be listed in the testfiles/CMakeLists.txt file.  Could you do that and then we'll get this merged in?

**Comment by wfbuhl** [comment]
Yes

**Comment by wfbuhl** [comment]
Pushed it up

**Comment by Myoldmopar** [comment]
Thanks @wfbuhl.  I merged develop in also to make sure the CI is all green when it catches up.  Once it catches up and looks green, this can go right in.

**Pull request merged**
