### PR TITLE
Changes interpolation for wind direction when to do it properly around 0 degrees

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #5682 
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar How do I figure out which weather file is used for failing regression tests? Is it using the CMakeLists.txt file in the EnergyPlus/testfiles directory?

**Comment by Myoldmopar** [comment]
Yep @JasonGlazer

**Comment by JasonGlazer** [comment]
Thanks. Although the failing files all use USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw which lots of other files do also. I was hoping the issue was a particular weather file.

**Comment by JasonGlazer** [comment]
I was expecting that any file that used weather files that were interpolated incorrectly would show at least some small diffs. The CI results of just a few files that use a specific weather file showing diffs and lots of others not, is not what I expected.

**Comment by Myoldmopar** [comment]
The three failing files are the only ones with SizingPeriod:WeatherFileDays.  Suspicious...

**Comment by EnergyArchmage** [comment]
CI only runs design days. Probably want to run locally and force annual simulations.

**Comment by mjwitte** [comment]
More generally, CI only runs sizing periods, which includes SizingPeriod:WeatherFileDays and as @Myoldmopar pointed out, these are the only files like that.

**Comment by JasonGlazer** [comment]
Thanks. I am running everything locally as annual simulations as @EnergyArchmage suggested.

**Comment by JasonGlazer** [comment]
@Myoldmopar @EnergyArchmage @rraustad @mjwitte I ran 40 files locally  (picked randomly using Edwin's testing GUI) and forced them to be annual runs. Of the 40, 30 had big mathdiffs and 6 had big tablediffs. Lots more had small diffs. For the six files with big tablediffs, the annual site energy percent diff impact was 0.00015. That is pretty small. The results of the 40 file are [here](https://www.dropbox.com/s/5yxtfuoijmykfu7/5682-test40.7z?dl=0) in 7z file. 

5701-mathdiffs
5701-tablediffs

If you look into the 7z file, you will notice all sorts of variables and table changes occur. It is not surprising given that it is the weather file interpretation that is changing. Given the number and nature of the diffs, how do I come to a conclusion if the changes worked or not?

I should also mention that I also ran all 495 files annually and 140 had big tablediffs and 393 had big mathdiffs. That was way to much to try to digest so I stuck with the 40 files discussed above.

**Comment by EnergyArchmage** [comment]
I totally agree that diffs of this magnitude are expected for this change.  Thanks for running annuals locally.

**Comment by JasonGlazer** [comment]
@Myoldmopar @EnergyArchmage @rraustad @mjwitte Given the nature of the change, the CI diffs are reasonable. I also ran 60 files chosen randomly using Edwin's EnergyPlus Test Suite GUI. Analyzing this, of the 60 files, 57 successful simulations, 22 had big table diffs, 16 had site energy per area diffs, 5 larger than 0.0001 with the largest being HeatPumpWaterToAirWithRHControl: 0.000171. Which is a change from 937.37 MJ/m2 to 937.53MJ/m2. All together, I think this is ready to be reviewed and merged.

**Comment by Myoldmopar** [comment]
Curious when you say 

> 60 files, 57 successful simulations

Maybe the three failures were EMSTestMathAndKill and the like...

**Comment by JasonGlazer** [comment]
1ZoneUncontrolled_win_1 which needed the Window5 Data File
_ExternalInterface-functionalmockupunit-to-variable which needed all the FMU stuff
EMSTestMathAndKill (this file has been kind of depressed lately...)

Bad luck that random picked those three files.

**Comment by Myoldmopar** [comment]
Thanks @JasonGlazer, I figured as much.  And thanks a huge amount for the great looking unit test on this.  This is a fantastic example of pulling out a logical amount of code and testing it really well.  Great.  Merging.

**Pull request merged**
