### PR TITLE
Disable Linux LTO compiling

### LINKED ISSUE #4814: Determine whether to remove LTO
# Summary

A placeholder issue for discussing whether or not to remove LTO with @kbenne and @lefticus (and @mbadams5 indirectly since it kinda involves his sqlite branch).

So the point is that @mbadams5 created an updated sqlite branch, but then it went quiet because there was some issue with LTO I think.  I'd like to either fix LTO or remove it so that the sqlite update goes in.  Either way is fine.  

It seems right now LTO is only enabled on Linux and Mac, so this won't affect Windows at all.  I don't have a Mac to test performance on, so if that is of interest based on initial (Linux) results, we'll have to tag another package for Mac with disabled LTO.
# Performance Testing

The main point of LTO is performance, so I'm doing some testing for performance with and without.  I am comparing the following conditions:
- Base: 8.2.10 iteration build
- Mod: 8.3.0 (beta) "Without LTO" tag build

The only core difference between these builds is that I disabled LTO (for Linux) in the mod case.  I then ran a sample of 20 random files, in both design-day/hourly output and annual/monthly output to check the difference in performance.  The random file set includes short running files and large models.

This is for Linux.  And I ran a single thread, without anything else of significance running on the machine while the simulations ran.
## Design Day Results

image
OK, so this might be a little difficult to discern.  Basically, the columns are absolute runtimes in both the 8.2.10-iteration and the 8.3.0-WithoutLTO builds.  For the most part these are both very small.  So I also plotted the spark line with percent worseness when I removed LTO.  Basically, we expect that when I remove LTO, the runtimes will increase, and this line will be positive on the right hand axis.  For a few files, it goes up, but for a few it also goes down.  Negative here means that the simulation was actually faster when I removed LTO.  When the worseness is at its peak of 25%, the runtime actually went from 0.4 to 0.5 seconds, which is right on the edge of E+ runtime reporting.  So it could've been 0.49 to 0.50.  Basically, let's not worry too much about this here.  Let's look at annual runs.
## Annual Results

image
For the annual results, the simulations are almost entirely running faster without LTO.  There are still a couple files that run a little longer, but these are the very short cases that could be more affected by startup IO.  In the longer running models, the runtime decreases.  
# Summary

So, I think we should probably pull LTO back out.  It would make the project quite a bit cleaner, and I'm assuming it would let the sqlite updates get in (which I think have some performance gains of their own).  

Thoughts?

### PR DESCRIPTION
**Pull request by Myoldmopar**
OK, I think I want to take out LTO.  Looks like it is killing the Linux package builds right now.  @lefticus @kbenne Could you confirm what we should do before I do anything drastic?  If this goes in, it will fix #4814.

### CODE REVIEW

**Comment by kbenne** [comment]
I think we need to run a current build without LTO with our past [performance release](https://github.com/NREL/EnergyPlus/releases/tag/v8.2.6-3) and see if we regress on performance.  That said I'm all for getting rid of the complexity of LTO.

**Comment by Myoldmopar** [comment]
@kbenne Without looking at specific commits, how is the past performance release much different from the 8.2.10 that I compared against?  I can do it, I just don't know what else it will tell us, since I don't think much performance stuff went in between them.

**Comment by kbenne** [comment]
oh you compared to 8.2.10.  And the results were?  sorry I'm not tracking all of this very well.

**Comment by Myoldmopar** [comment]
#4814

**Comment by lefticus** [comment]
I'll just say that I think your comment of it making the project "quite a bit cleaner" seems incorrect in the conclusion of #4814. Or more to the point, you would need to separately evaluate MacOS and see what that changes.

Most of the complexity in the build would need need to exist for the sake of PGO, which you have left enabled.

**Comment by Myoldmopar** [comment]
Closing this as it will go in with #4818.

**Pull request closed without merging**
