### PR TITLE
Fixed total number of hours not met by adding variable reset 

### PR DESCRIPTION
**Pull request by JasonGlazer**
after design days. Addresses #5296

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Diffs all seem small. Not sure why I am getting more diffs after checking in the unit test than with the original code change. Maybe "develop" changed. I think this is ready to merge.

**Comment by JasonGlazer** [comment]
@mjwitte or @Myoldmopar would one of you like to review the code change and merge this.

**Comment by mjwitte** [comment]
@JasonGlazer This branch is 28 commits behind develop, thus the diffs. Please merge in develop for one more round of tests, or I can if you want.

**Comment by JasonGlazer** [comment]
Looks like this is ready to go. The RadLoHydrHeatCoolAuto.idf change in the test cases is expected.

**Pull request merged**
