### PR TITLE
Global SurfaceGeometry

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Move SurfaceGeometry data to state

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
Hmm, the Kiva integration failures pass on my Mac.

**Comment by mitchute** [comment]
@Myoldmopar when you get a minute, can you take a look at this? I'm not able to replicate the errors locally, and they are strange ones to boot.

```expected comma after name `_ZN9__gnu_cxx14__alloc_traitsISaIN5boost8geometry5model5pointIdLm2ENS2_2cs9cartesianEEEEE27_S_propagate_on_copy_assignE' in .size directive```

**Comment by Myoldmopar** [comment]
That's.  Weird.  I'll try to kick off a debug build and see if I can replicate.

**Comment by Myoldmopar** [comment]
Nothing seemed awry on my debug build, but I wasn't building with coverage, let me retry.

**Comment by Myoldmopar** [comment]
Yeah energyplus built fine again even with coverage on.  I'm on 20.04 so that's the only thing I can think of.  I'll try it on an 18.04 machine or one of the CI machines manually tomorrow.

**Comment by Myoldmopar** [comment]
Built perfectly fine on my 18.04 VM with GCC 7.5.0.  I'll try on the CI machine.

**Comment by Myoldmopar** [comment]
Aaaand I just built it fine on the CI machine itself.  I'm going to take the CI machines down for a quick reboot and re-run the failed builds.

**Comment by Myoldmopar** [comment]
OK, well that's better I suppose.  The build didn't fail, though the tests did.

**Comment by Myoldmopar** [comment]
Built on 18.04 with debug/coverage turned on and ran some unit tests.  No problems......hmm.  I'll have to try to run some tests on the CI box as well.

**Comment by mitchute** [comment]
I also ran unit and integration tests on a local 18.04 machine with debug/coverage. There were no problems that I could see.

**Comment by Myoldmopar** [comment]
And now build failed again.  What is happening.

**Comment by Myoldmopar** [comment]
I tried rolling back to the original set of commits here to see if I could find anything, but I did not.  The very first commit is an incremental that doesn't build on its own, and by the second one, CI was already having trouble on this.  I still have yet to have this trouble locally.  I'm going to have to think through how to deal with this.  I may need to try to rebuild at least some of the changes very, very, very slowly and let CI run it a bunch of times to see if I can identify where the problem finally gets introduced.

**Comment by Myoldmopar** [comment]
OK, CI machines upgraded from 24GB to 30GB and now my branch built fine.  Let's see what happens here now.

**Comment by Myoldmopar** [comment]
I logged into the CI machine and built a release build and confirmed the failure on those two files.  I built a debug version and it again failed so that I could debug into it.  With lldb, I was able to find an array out of bounds error at [this line](https://github.com/NREL/EnergyPlus/blob/global_Ss/src/EnergyPlus/HeatBalanceKivaManager.cc#L1061).  At that point in the simulation, the value of `kv.constructionNum` was like `-18374823` or some nonsense.  So it seems that `constructionNum` may be accidentally used uninitialized?  I think a debug build on any Mac should reveal this, and maybe it's not showing up on Linux because GCC or the C runtime is initializing that variable in a way that Clang is _not_.  I can try to investigate some more tomorrow but maybe that's enough to get this solved.

**Comment by Myoldmopar** [comment]
OK, let's call it.  There may be an uninitialized variable, but I'm not seeing it, and I'm inclined to get this in.  Any objections?  Here's my imaginary timer as I step away for a while.

**Comment by mitchute** [comment]
Fine by me!

**Comment by Myoldmopar** [comment]
And my imaginary timer just went off, merging this in.  If something remains funny with that uninitialized variable we'll investigate at that time.

**Pull request merged**
