### PR TITLE
Fix doc issues

### PR DESCRIPTION
**Pull request by Myoldmopar**
Some documentation issues slipped in.  CI was able to get passed them, but if you built the engineering reference in, say, TeXMaker, you would see lots of errors.  This addresses that.

### CODE REVIEW

**Comment by mjwitte** [comment]
Patience is @Myoldmopar 's middle name, as patient as his mopar engine.

**Comment by jasondegraw** [comment]
@Myoldmopar Which bot are we waiting for?

**Comment by Myoldmopar** [comment]
I would love to see Gort report back that he built the docs successfully.  But we don't have to.  Let me do a full fresh build of this branch and all docs and package.  If it builds OK, we can merge this and get it in the other branches.

**Comment by jasondegraw** [comment]
@Myoldmopar I highly doubt that will happen, it's currently hanging on the doc build. I'm building develop on the VM to see if that also hangs, and there is a long running xelatex process, so we'll see.

**Comment by Myoldmopar** [comment]
I just built a full package on Linux.  Everything seems super clean.  I'm going to merge this down and it should be safe for other branches to pick it up as needed.  It looks like CI is churning now, however, so it may not be important for other branches to integrate these fixes anymore.

**Comment by Myoldmopar** [comment]
Sorry, I missed your comment there @jasondegraw.  I had been able to reproduce a delay in building on CI, it seemed stuck.  I just pulled a fresh develop on that machine, configured, and made the engineering reference in about 40 seconds including all 3 passes of LaTeX.  We may have a couple issues here and there where CI takes a while, but I think once branches get this in place, things should improve.

I'll continue to monitor my CI box and if I see any very long running XeLaTeX processes I'll kill them.  The builds will have errors but at least they can move forward to better commits.

**Comment by Myoldmopar** [comment]
So actually, on that note @jasondegraw, go ahead and kill the latex process you are seeing.  The CI box will be able to move to the next commit that way!

**Comment by jasondegraw** [comment]
@Myoldmopar Actually, I'm not sure that it will based on what I was seeing. If I have to reboot, I'll let you know.

**Pull request merged**
