### PR TITLE
Keep EP-Launch options upon uninstall

### LINKED ISSUE #7515: Prep for 9.2.0 Release
Issue overview
--------------
A catch-all for tasks to accomplish for the 9.2.0 release.  Add to this list as needed:
- [x] Tag RC1
- [x] Check on Windows 8.1 Installer issues
- [x] Review any other last minute pull requests
- [x] Update README
- [x] Test on all platforms
- [x] Tag RC2
- [ ] Final Testing
- [ ] Tag v9.2.0

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7515, specifically https://github.com/NREL/EnergyPlus/issues/7515#issuecomment-535709306
 - No longer delete the registry key for EP-Launch where EP-Launch stores the Options the user has set.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
@mjwitte test build here: https://drive.google.com/open?id=19HBXKv2FCNdlDssi-vWBbUJ1bQ9VD9ay

I tested it locally on Win10, the `Computer\HKEY_CURRENT_USER\Software\VB and VBA Program Settings\EP-Launch` does remain with the settings I've set.

**Comment by Myoldmopar** [comment]
Thanks @jmarrec, this looks like a very promising fix.  I'll let @mjwitte review since he's been experiencing the issue and if this is good to go, I'll merge it and 9.2.0 is done.

**Review by mjwitte — APPROVED** [review]
Works perfectly. Thanks @jmarrec !

**Comment by Myoldmopar** [comment]
Ok great! I'm merging this and then tagging 9.2!

**Pull request merged**
