### PR TITLE
Add a clear_state to DataStringGlobals to avoid problems when running unit tests serially (FiniteDiff)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

cf #7247 and revert #7317. **Fixed by adding a `clear_state()` function to `DataStringGlobals`**

`DataStringGlobals.hh` declares a bunch of `extern std::string`, some of which aren't actually initialized to anything in `DataStringGlobals.in.cc`, and including `inputWeatherFileName`.

In my unit test from #7247 `FiniteDiffGroundTempModel_GetWeather_Weather` I do 

```
DataStringGlobals::inputWeatherFileName = configured_source_directory() + "/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw";
```

As a result when my runs first, then HVACFourPipeBeam's `Beam_sizeandSimulateOneZone`, `inputWeatherFileName` is still initialized, and therefore `WeatherManager::WeatherFileExists` evaluates to true and does a lot of weird things.

----

**Note**: I noticed that DataStringGlobals.in.cc and some other files aren't UTF-8. Will separate these changes into another PR

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
**Edit**: I forced pushed so that I can separate the UTF-8 stuff into another PR

**Review by Myoldmopar — APPROVED** [review]
Code changes look good.

**Comment by Myoldmopar** [comment]
I built develop and this branch locally and ran the test suite.  In develop, the tests will fail unless they are disabled.  In this branch they are enabled and pass.  This is good to go in.  Nice find @jmarrec .  Merging.

**Comment by jmarrec** [comment]
@Myoldmopar So generally speaking, should a clear_state() function also clear variables that are initialized to a value?

**Comment by Myoldmopar** [comment]
Generally speaking, my clear_state functions tend to reset all global state back to the default value.  This often means duplicating the default value that is used in an initializer statement.

**Pull request merged**
