### PR TITLE
Add unit test for ideal loads sizing Issue 4604

### PR DESCRIPTION
**Pull request by mjwitte**
Completes fix for #4604

### CODE REVIEW

**Comment by rraustad** [comment]
I don't know what to do to merge this pull request. 

I tried Step 1 above and failed on the second line:
git checkout -b 87342444-IdealLoadCoolingAutosize-UnitTest origin/87342444-IdealLoadCoolingAutosize-UnitTest

Failed with:
fatal: A branch named '87342444-IdealLoadCoolingAutosize-UnitTest origin/87342444-IdealLoadCoolingAutosize-UnitTest' already exists.

**Comment by mjwitte** [comment]
@rraustad This is a recurring issue with adding a unit test name to the cmake list file.  I have resolved one of these before using tortoise git.  I'll fix this one and document the sequence with some screen shots.

**Comment by rraustad** [comment]
Thanks. I was just getting ready to try skipping the second line in Step 1 to see what happens (i.e., move directly to "git merge develop"). The problem is, I am hesitant to throw commands at git without knowing what they actually do. I also don't understand why the command line example asks to checkout a branch that should have already been checked out in order to verify the code changes. When a developer clicks the "Merge pull request button", shouldn't they already have that branch on their computer?

**Comment by mjwitte** [comment]
> When a developer clicks the "Merge pull request button", shouldn't they already have that branch on their computer?

Not necessarily.  Nothing has to be on your local machine to execute the merge on github.  That's an entirely remote operation.

**Comment by mjwitte** [comment]
@rraustad Develop merged into here and conflict resolved.  CI should report back all green.  Conflict resolution doc sent to developer group list.

**Comment by rraustad** [comment]
I'm still skeptical of these unit tests. It seems we are telling the program what answer we want and then testing to see if it actually happens. Since this method does include calls to subroutines, I guess this does have some benefit.

**Pull request merged**
