### PR TITLE
Added logic in src/EnergyPlus/EvaporativeCoolers.cc > SizeEvapCooler

### LINKED ISSUE #9933: Evaporative Coolers have missing logic in SizeEvapCooler.
Issue overview
--------------
Code review has revealed some sizing differences between zone and air loop equipment.

One issue is HardSizeNoDesRun is set for air loop equipment but not zone equipment.

        if (SizingDesRunThisAirSys) {
            HardSizeNoDesRun = false; // Check if design infomation is available
        }

Another issue is SizingDesRunThisAirSys is used for zone equipment when SizingDesRunThisZone should be used.

    if (CurSysNum > 0) { // central system
        if (!IsAutoSize && !SizingDesRunThisAirSys) {
    } else if (CurZoneEqNum > 0) {                    // zone equipment
        if (!IsAutoSize && !SizingDesRunThisAirSys) { // this should be SizingDesRunThisZone

[This commit](https://github.com/NREL/EnergyPlus/pull/9928/commits/3479177459da86dccb0e0cf2d5ef6f0a5dd91afb) highlights these issues.

This loop also uses the wrong index when checking all evap coolers for a proper set point. The index should be EvapUnitNum for checking and warnings. The use of the function reference evapCond inside this loop should be removed and instead use state.dataEvapCoolers->EvapCond(EvapUnitNum).*

    // Check that setpoint is active
    if (!state.dataGlobal->SysSizingCalc && state.dataEvapCoolers->MySetPointCheckFlag && state.dataHVACGlobal->DoSetPointTest) {
        for (int EvapUnitNum = 1; EvapUnitNum <= state.dataEvapCoolers->NumEvapCool; ++EvapUnitNum) {

            // only check evap coolers that are supposed to have a control node
            if ((evapCond.evapCoolerType != EvapCoolerType::IndirectRDDSpecial) && (evapCond.evapCoolerType != EvapCoolerType::DirectResearchSpecial))
                continue;

            int ControlNode = state.dataEvapCoolers->EvapCond(EvapUnitNum).EvapControlNodeNum;
            if (ControlNode > 0) {
                if (state.dataLoopNodes->Node(ControlNode).TempSetPoint == DataLoopNode::SensedNodeFlagValue) {
                    if (!state.dataGlobal->AnyEnergyManagementSystemInModel) {
                        ShowSevereError(state, format("Missing temperature setpoint for Evap Cooler unit {}", evapCond.Name));
                        ShowContinueError(state, " use a Setpoint Manager to establish a setpoint at the unit control node.");
                    } else {
                        bool localSetPointCheck = false;
                        CheckIfNodeSetPointManagedByEMS(state, ControlNode, EMSManager::SPControlType::TemperatureSetPoint, localSetPointCheck);
                        state.dataLoopNodes->NodeSetpointCheck(ControlNode).needsSetpointChecking = false;
                        // Let it slide apparently
                        if (localSetPointCheck) {
                            ShowSevereError(state, format("Missing temperature setpoint for Evap Cooler unit {}", evapCond.Name));
                            ShowContinueError(state, " use a Setpoint Manager to establish a setpoint at the unit control node.");
                            ShowContinueError(state, " or use an EMS actuator to establish a setpoint at the unit control node.");
                        }
                    }
                }
            }
        }
        state.dataEvapCoolers->MySetPointCheckFlag = false;
    }

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ateevwasalreadytaken**
Pull request overview
---------------------
 - Fixes #9933 
 - Added missing logic to lines 1202-onwards, set HardSizeNoDesRun for zone equipment.
 - Used SizingDesRunThisZone for zone equipment where it should be used. line 1274
 - Use of the function reference evapCond inside this loop line 1048 is justified by initialization of alias on line 1044, seemingly nullifying this issue

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@ateevwasalreadytaken it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@ateevwasalreadytaken it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
There's already a test named `EvaporativeCoolers_SizeEvapCooler`, you can't use a duplicate name.  That's the primary reason the CI dashboard went all red here.

**Comment by nrel-bot-2b** [comment]
@ateevwasalreadytaken it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@ateevwasalreadytaken it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@ateevwasalreadytaken it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@ateevwasalreadytaken it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@ateevwasalreadytaken it has been 7 days since this pull request was last updated.

**Pull request closed without merging**
