### PR TITLE
Correct EIO Wind Angle Output

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
The angles being written to the EIO when the advanced single-sided natural ventilation feature is used are not correct. Reordering the logic a bit fixes the output so that the correct values are used. Addresses #6857.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by jasondegraw** [comment]
Oops, accidentally submitted this off of my own fork. That was not intentional, I can move the branch into this repo if need be.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@jasondegraw This is blocked by #6912. But in the meantime, please add a description of the output changes to the [output rules doc](https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/OutputRulesFiles/OutputChanges8-9-0-to-9-0-0.md).

**Comment by mjwitte** [comment]
This code works as intended. However, the Initialization Summary table output doesn't display the full tables in the html (not sure about sql), likely because the row headers aren't set up with all of the columns.
image
A for loop to add fill out the column headings of "Wind Direction #2 {deg}" etc. is needed [here](https://github.com/NREL/EnergyPlus/blob/f2e822120ce2620da9ab77c203634f1feb6e4eb8/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L2571).

And for the wind coefficients table, those column headings should also be "Wind Direction #1 {deg}", "Wind Direction #2 {deg}", etc. That code is [here](https://github.com/NREL/EnergyPlus/blob/f2e822120ce2620da9ab77c203634f1feb6e4eb8/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L2594).

**Comment by mjwitte** [comment]
@jasondegraw Any chance we can get this fixed today?

**Comment by jasondegraw** [comment]
@mjwitte I doubt it, and since this has been this way at least 6 months with no reports, I'm inclined to think it's OK to push it to the next release.

**Comment by mjwitte** [comment]
@jasondegraw OK. I'll drop this so that the eio angles are all there, and then post a new issue to fix the tables.

**Comment by mjwitte** [comment]
drop this = drop this in = merge . . . but after RunPeriod is merged.

**Pull request merged**
