### PR TITLE
Fix WaterHeaterReportMonthly source energy output field

### LINKED ISSUE #10208: WaterHeaterReportMonthly output fields look wrong
Issue overview
--------------
https://github.com/NREL/EnergyPlus/blob/2ad5b542c761abde2179225b08ce7af0b94a5d3b/src/EnergyPlus/InputProcessing/InputProcessor.cc#L2372

and

https://github.com/NREL/EnergyPlus/blob/2ad5b542c761abde2179225b08ce7af0b94a5d3b/src/EnergyPlus/OutputReportTabular.cc#L2667

Seems like these should both be:
https://github.com/NREL/EnergyPlus/blob/2ad5b542c761abde2179225b08ce7af0b94a5d3b/src/EnergyPlus/WaterThermalTanks.cc#L5293

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
 - Fixes #10208 
 - Interestingly, the documentation has the correct names so no fix is needed there

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by shorowit** [comment]
I took the CoilWaterDesuperheating.idf test file and changed `AllSummary` to `AllMonthly` for the Output:Table:SummaryReports.

Before:

image

After:

image

**Comment by shorowit** [comment]
Technically an `OutputChange` since the name is changed, but the previous output was always zero so maybe no one is using it.

**Comment by Myoldmopar** [comment]
Yeah, you are right, _technically_ an output change.  But probably a worthwhile one, since it was always zero.  I'm OK with this going in.  @mjwitte you have any concerns?  @jmarrec?  If it's good to go in, I'll test it out and resolve the minor output change conflict.

**Comment by mjwitte** [comment]
Fine with me.

**Comment by Myoldmopar** [comment]
Excellent, doing this now then.

**Comment by Myoldmopar** [comment]
Good to go, merging.  Thanks @shorowit

**Pull request merged**
