### PR TITLE
Assign the same HeatTransferAlgorithms for an interior surface with reverse constructions

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
This fix assign the same HeatTransferAlgorithm for an interior surface with reverse constructions.
 
### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I was ready to get this merged in, but I wanted to run tests locally.  I pulled develop into this branch and ran all the unit tests.  It fails here:
```
tst/EnergyPlus/unit/DaylightingManager.unit.cc:869: Failure
      Expected: ZoneDaylight(zn).ShadeDeployOrderExtWins.size()
      Which is: 12
To be equal to: 6ul
      Which is: 6
```

This is unexpected given these changes, but nonetheless, we are dealing with reversed surface changes, etc., so I wanted to let CI verify what I was seeing.  I pushed this branch up again, let's see how it goes now.

**Comment by lgu1234** [comment]
@Myoldmopar I ran unit test on my local computer and got the same failure. When I add a line in the beginning of MapShadeDeploymentOrderToLoopNumber_Test with release as

    ZoneDaylight.deallocate();

The unit test went to completion. Then I tried to add this statement in the clear_state function in DaylightingManager. Unfortunately, DaylightingManager does not have one.

**Comment by Myoldmopar** [comment]
That's super helpful @lgu1234 .  I will add that clear_state function in this branch.  Should be able to push it up here in a few minutes.

**Comment by Myoldmopar** [comment]
@lgu1234 I added a clear_state, with just the one deallocation for now, and the unit test passes locally on my machine.  Thanks.  I'm going to take a small risk and just go ahead and merge this in since CI was going to be happy with it before anyway.  Thanks!

**Pull request merged**
