### PR TITLE
Setup heat recovery flag for multispeed DX coils in AirloopHVAC:UnitarySystem

### PR DESCRIPTION
**Pull request by lgu1234**
Addresses #5222 
Allow AirloopHVAC:UnitarySystem, as a parent object, to set up heat recovery flag for multispeed heating and cooling coils as child objects.

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 Please add a description at the top of the PR.  Also, is there a test file that shows how this works?

**Comment by lgu1234** [comment]
@mjwitte A description is added at the top. 

No. I don't have a test file. A unit test was used to test logic to ensure the heat recovery flag setting for DX coils is correct. DX coil testing was performed in #5162.

**Comment by Myoldmopar** [comment]
I'm hesitant here without a defect file to work from.  I see that the unit test properly sets the heat recovery flag, but I don't know about the consequences of that without seeing it demonstrated.  Is it possible to work up an idf that has this capability running incorrectly in develop but correctly over here?  If not, I'll have to slog through to trace the flag and see how it is used, etc., which I don't _mind_, but it will certainly take a lot more time.

**Comment by lgu1234** [comment]
@Myoldmopar The defect was fixed in DXCoils using multispeed cooling and heating coils in #5162 by setting up a heat recovery flag from a parent object. The parent object in #5162 is AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed. AirLoopHVAC:UnitarySystem has the same functionality to call multispeed cooling and heating coils. In order to be consistent with the fix of #5162, the AirLoopHVAC:UnitarySystem object should have to set up heat recovery flag to realize the fix of #5162. This is the goal for this issue.

Since I can't to have a defect file, I will generate 3 test files, similar to 3 test files in #5162 (case1.idf, case2.idf, and case3.idf). The difference is a parent object from AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed to AirLoopHVAC:UnitarySystem. You may compare err file to see no warnings.

**Comment by Myoldmopar** [comment]
That's great, @lgu1234, it will be interesting to see the code coverage from the integration tests if you add those additional cases.  Let me know when you have them ready and I'll check them out.

**Comment by lgu1234** [comment]
@Myoldmopar and @mjwitte I just created 4 test files to show heat recovery works properly or not based on heat recovery flag by looking at an output variable: Unitary System Heat Recovery Rate.

HeatingCoolingHeatRecovery.idf, Heat recovery happens during heating and cooling time
CoolingCoilHeatRecovery.idf, Heat recovery happens during cooling time
HeatingCoilHeatRecovery.idf, Heat recovery happens during heating time
NoHeatRecovery.idf, No heat recovery at all using Electricity fuel type

I am going to upload these four files.

**Comment by Myoldmopar** [comment]
Hmmm.  OK, go ahead and do that.  If it is just the scheduling that is different, it will be nice to demonstrate the fix here.  But it may be a little too much redundancy to add to the full CI setup, so we may just pick one for actually adding to the repo.  For now, add them so we can work to get this merged in.

**Comment by lgu1234** [comment]
@Myoldmopar Four test files were uploaded in EnergyPlusDevSupport\DefectFiles\5000s\5222.

**Comment by Myoldmopar** [comment]
Ahh, thanks @lgu1234

**Comment by mjwitte** [comment]
Tested with the four defect files.  With this fix, DXAC HEAT PUMP 1:Unitary System Heat Recovery Rate [W] now has non-zero values at the appropriate times.  Merged in develop and fixed some node registrations (the heat recovery branch wasn't showing up in the svg drawing).  The water heater source side heat transfer rate changes with this fix, but I'm surprised that the source side heat transfer only goes up by about half of the reported coil heat recovery rate.  Where does the rest of the energy go?  Not sure whether to pursue that here or make a new issue.

**Comment by mjwitte** [comment]
#5516 posted to look deeper into the heat recovery energy balance.  Merging.

**Pull request merged**
