### PR TITLE
Update slab and basement output variable names

### PR DESCRIPTION
**Pull request by mitchute**
Name changes from #5323. Pushed to V8.5

### CODE REVIEW

**Comment by mjwitte** [comment]
Just a reminder that these changes need to be added to https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/SupportFiles/Report%20Variables%208-4-0%20to%208-5-0.csv

**Comment by mitchute** [comment]
Ah, thanks @mjwitte for pointing that out (again).

**Comment by nrel-bot-3** [comment]
@mmatts @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@mmatts Merged in develop.  There was a single merge conflict where the old report variables had been added to an idf in both branches.  No biggy.  This is a pretty simple one to merge in.

@macumber @kbenne On the OpenStudio side, this output-change is noted as it always has been with the report variable change [file](https://github.com/NREL/EnergyPlus/pull/5326/files#diff-59bda655e0f621a53de76099739ed33a).  The report variables will be transitioned properly by the 8.4 to 8.5 transition utility as well.

**Pull request merged**
