### PR TITLE
ZoneHVAC VRF Plant Component Refactor

### PR DESCRIPTION
**Pull request by mitchute**
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
@Myoldmopar @rraustad This is a very minimal refactor to make the condenser inherit PlantComponent. Feel free to review it when you can. Tests run OK locally, so I'm expecting it to be CI to be happy. 

Also (Rich), I haven't applied clang-format on this yet since I wasn't sure of your other work going on here. I can do that after review, or just skip it and let you do it when you're done.

**Comment by rraustad** [comment]
I'll just include these changes once this is merged into develop.

**Comment by rraustad** [comment]
@mitchute I'd like to get this in quickly if possible. What issues remain before this can merge? Should there be any diffs?

**Comment by Myoldmopar** [comment]
The wild looking Mac results should be ignored, it's behaving better now.  The Windows failures are surprising...just a couple files that seem to have failed to produce proper .end file contents.  The Linux results are exactly what I would expect here -- diffs in the text files as things are reordered but no math diffs.  I'd suggest pulling develop in again here to let Mac and Windows have a confirmation pass.

**Comment by mitchute** [comment]
@rraustad sorry for the delayed response. Email rules sent this to the trash. I'm pulling in develop now to make one final pass, but I'm not expecting any significant diffs other than what was noted by @Myoldmopar.

**Comment by mitchute** [comment]
@Myoldmopar @rraustad this is looking like it's going to be ready. I just checked the results from the HVACTemplate_VRF file locally and confirmed that the diffs are just due to fields moving around. Let me know if there's anything else. I didn't run clang-format on the files but would be happy to before this drops.

**Comment by Myoldmopar** [comment]
I'm all for skipping clang-format here, there is a chance other tasks could have big conflicts.  I'll watch for CI to finish up but it looks good so far.

**Comment by mitchute** [comment]
@Myoldmopar 👍 

Merge away when ready.

**Comment by rraustad** [comment]
But there are numerical diff's in the one file on CI x86_64-Linux-Ubuntu-18.04-gcc-7.4 for HVACTemplate-5ZoneVRF. Red data starting at left is: Electricity Annual (GJ), Electricity Minimum (W) and Electricity Maximum (W). 1 GJ is about 300 kWhs so there is certainly something different here.

Table from:
FullName:Energy Meters_Entire Facility_Annual and Peak Values - Electricity

image

**Comment by mitchute** [comment]
@rraustad I believe the table diff summary isn't accurate when fields are moving around with the tables. As I understand it, the tables are compared but the fields within are not matched and compared.

Heres a snippet of the tables from a local run of the HVACTemplate_5ZoneVRF:

develop
Screen Shot 2020-01-16 at 10 35 00 AM

mod
Screen Shot 2020-01-16 at 10 35 51 AM

It looks to me like these diffs are just due to the fields moving around, but the numerics are the same. Let me know if I've missed something here, though.

**Comment by rraustad** [comment]
OK, I see. You said that but it didn't click until now. Thanks for clarifying.

**Comment by rraustad** [comment]
Results reviewed and discussed. CI is clean once explained.

**Comment by rraustad** [comment]
Just to be sure, there are no issues to close with these refactor branches?

**Comment by mitchute** [comment]
No, I believe they can be deleted.

**Comment by rraustad** [comment]
"No" and "they can be deleted" does not compute. Is there an issue to close or not?

**Comment by mitchute** [comment]
No issues.

**Comment by rraustad** [comment]
Thank you, I couldn't find one. These refactor PRs don't need one but I didn't want an open issue lying around.

**Comment by rraustad** [comment]
Geez, I can't tell what's your changes vs what's mine. Not sure how to go about this. Maybe accept version of code and then manually go through and include all your changes from this PR.

**Comment by mitchute** [comment]
Glad I didn't run clang format on it!

**Pull request merged**
