### PR TITLE
Add warning to IDF Editor when \min-fields is greater than number of fields

### LINKED ISSUE #7606: IDF editor adding extra fields and causing simulation error
Issue overview
--------------
The IDF editor is adding an extra field to the HeatPump:WaterToWater:EIR:Heating and Cooling objects. The problem can be reproduced with the WaterToWaterHeatPump_EIR.idf example file. Just open the file, add another Version object, Save, delete extra Version object, Save. When you run this time, there will be some errors.

BEGIN BEFORE USING IDF EDITOR
```
  HeatPump:WaterToWater:EIR:Heating,
    Heating Coil,            !- Name
    Heating Coil Load Loop Intermediate Node, !- Load Side Inlet Node Name
    Heating Coil Load Loop Supply Outlet Node,  !- Load Side Outlet Node Name
    Condenser Loop Demand Inlet Node,  !- Source Side Inlet Node Name
    Condenser Loop Demand Intermediate Node,  !- Source Side Outlet Node Name
    Cooling Coil,            !- Companion Coil Name
    0.005,                   !- Load Side Design Volume Flow Rate {m3/s}
    0.002,                   !- Source Side Design Volume Flow Rate {m3/s}
    80000,                   !- Reference Capacity
    3.5,                     !- Reference COP
    ,                        !- Sizing Factor
    CapCurveFuncTemp,        !- Heating Capacity Function of Temperature Curve Name
    EIRCurveFuncTemp,        !- Electric Input to Heating Output Ratio Function of Temperature Curve Name
    EIRCurveFuncPLR;         !- Electric Input to Heating Output Ratio Function of Part Load Ratio Curve Name
```
END BEFORE USING IDF EDITOR

BEGIN AFTER USING IDF EDITOR
```
HeatPump:WaterToWater:EIR:Heating,
    Heating Coil,            !- Name
    Heating Coil Load Loop Intermediate Node,  !- Load Side Inlet Node Name
    Heating Coil Load Loop Supply Outlet Node,  !- Load Side Outlet Node Name
    Condenser Loop Demand Inlet Node,  !- Source Side Inlet Node Name
    Condenser Loop Demand Intermediate Node,  !- Source Side Outlet Node Name
    Cooling Coil,            !- Companion Heat Pump Name
    0.005,                   !- Load Side Reference Flow Rate {m3/s}
    0.002,                   !- Source Side Reference Flow Rate {m3/s}
    80000,                   !- Reference Capacity {W}
    3.5,                     !- Reference Coefficient of Performance {W/W}
    ,                        !- Sizing Factor
    CapCurveFuncTemp,        !- Capacity Modifier Function of Temperature Curve Name
    EIRCurveFuncTemp,        !- Electric Input to Output Ratio Modifier Function of Temperature Curve Name
    EIRCurveFuncPLR,         !- Electric Input to Output Ratio Modifier Function of Part Load Ratio Curve Name
    CapCurveFuncTemp;        !- Name
```
END AFTER USING IDF EDITOR

ERR file
```
Program Version,EnergyPlus, Version 9.2.0-921312fa1d, YMD=2019.11.07 16:34,
   ** Severe  ** Line: 458 Index: 0 - Error parsing "HeatPump:WaterToWater:EIR:Cooling". Error in following line.
   ** Severe  ** ~~~ 
   ** Severe  ** Line: 458 Index: 21 - "CapCurveFuncTemp2" is not a valid Object Type.
   ** Severe  ** Line: 478 Index: 0 - Error parsing "HeatPump:WaterToWater:EIR:Heating". Error in following line.
   ** Severe  ** ~~~ 
   ** Severe  ** Line: 478 Index: 20 - "CapCurveFuncTemp" is not a valid Object Type.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
```

If I removed the added lines and move the semicolons, then the IDF simulates with no errors. The IDF editor seems to be adding an extra field to the HeatPump:WaterToWater:EIR:Heating and Cooling objects.

### Details
 - Windows 10
 - EnergyPlus 9.2

### Checklist
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #7606 
 - Fixes the Energy+.idd file and adds a warning to the IDF Editor so that this (hopefully) is less likely to happen again.
 - It specifically impacted the HeatPump:WaterToWater:EIR:Heating and HeatPump:WaterToWater:EIR:Cooling objects when edited in the IDF Editor.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [X] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte or @Myoldmopar could one of you pull down the IDF Editor and confirm the fix?

**Comment by Myoldmopar** [comment]
I don't have a Windows setup immediately ready but I could if needed.  From a code changes alone perspective I like the IDD fixup, thanks, and the only issue I could think of is that the MsgBox is shown for every instance of a min-fields problem.  In the case of someone adding a few objects, this _could_ throw a whole series of msgbox's, which would be a bit annoying.  You could alternatively just create one informative string and throw a single MsgBox.  That said, I understand it shouldn't happen like ever, so I'm not demanding you change it.

As an aside, it would be pretty easy to add a custom_check that processes the IDD and looks for this sort of thing and throws a warning right on CI instead of waiting to find the issue after it's already merged..........

**Comment by JasonGlazer** [comment]
@Myoldmopar I had never looked at the custom_check scripts before. Adding one is a good idea. That would be easy to do.

**Comment by mjwitte** [comment]
@JasonGlazer The warning works, but there's a couple of typos.
image
\min-field --> \min-fields
number of fiels --> fields

So, the only change to IDF Editor is to add the warning, but it still writes the bad object when used with the current v9.2.0 idd. Would it be hard to limit the object length to the lesser of min-fields and total number of fields?

**Comment by mjwitte** [comment]
@JasonGlazer Tested the latest changes - all good.

**Comment by JasonGlazer** [comment]
I think it ready to merge. I don't think I am going to put a new custom_check together this time.

**Comment by mjwitte** [comment]
Windows never finished here, but everything else is ok and it's only IDD and idf editor changes. So merging this.

**Pull request merged**
