### PR TITLE
Low Temperature Radiant System Sizing Concerns and Pump Efficiency Bug

### PR DESCRIPTION
**Pull request by RKStrand**
## Pull request overview

This pull request is to address GitHub Issue #4393 relating to low temperature radiant system sizing concerns that were brought up by a user and also others on the development team.  A user noted that the low temperature radiant system simply would not meet the load and that the example files in the test suite all had the same issue.  This was clarified and additional documentation was created to address this concern.  While investigating these issues, a problem was uncovered in an init routine.  While the problem in the init routine was not the source of the issue with the sizing problem, it was uncovered during this work and spurred by the presence of autosizing.  Basically, the pump efficiency for constant flow radiant systems was produce a negative number for autosizing cases and the error messages related to problems with the pump efficiency for all cases had a bug in them.  This is now corrected.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ x ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ x ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs GitHub Issue #4393.
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things
- IDD changes n/a
- [x] If new idf included, locally check the err file and other outputs
- [x] Documentation changes in place
- [x] Changed docs build successfully

### CODE REVIEW

**Comment by mjwitte** [comment]
@RKStrand Do you have a test file that shows the bad pump error?

**Comment by RKStrand** [comment]
@mjwitte I was getting the error message in the test suite file named: RadLoTempCFloHeatCool_AddedAutosizing.idf

**Comment by RKStrand** [comment]
@mjwitte I should add that I was getting it for the West Zone radiant system that is autosized.

**Comment by mjwitte** [comment]
@RKStrand Oh - I see it now.

**Review by mjwitte — APPROVED** [review]
2nd round of test file revisions is much better.

**Pull request merged**
