### PR TITLE
Allow unitary system single mode operation with single speed gas heating coil and continuous fan

### PR DESCRIPTION
**Pull request by lgu1234**
## Pull request overview

Allow a single speed gas heating coil and continuous fan operation for single mode operation.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s) n/a
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things
- IDD changes: n/a

### CODE REVIEW

**Comment by lgu1234** [comment]
@mjwitte I tested 4 combinations using one of your testing files HVACTemplate-5ZoneUnitarySystem-MultispeedDXCool-exp-SingleModeNo-CyclingFan.idf. Results are expected.
1. Single mode + Cycling fan
2. Single mode + constant volume fan
3. Regular mode + Cycling fan
4. Regular mode + constant volume fan

**Comment by mjwitte** [comment]
@lgu1234 This does not need any doc changes?

**Comment by lgu1234** [comment]
@mjwitte It expects some add-on. I think @Myoldmopar is revising doc format. Can I still use old version to make changes?

**Comment by Myoldmopar** [comment]
Make doc changes as you need. I'll port them over after the latex doc
merge.

**Comment by Myoldmopar** [comment]
The one diff file obviously makes sense.  The actual logic being employed seems to make sense, but I'd love a +1 from @rraustad or @mjwitte to confirm before moving to merge.  @lgu1234 you mentioned you ran those four cases and everything looks good.  Could you either show the results or get me the four files so I can run them also to verify?

**Comment by rraustad** [comment]
I'm not up to speed on the fan power impact. I'd have to see a graph (with an expected fan power trace included) to know if this is working correctly.

**Comment by Myoldmopar** [comment]
OK, for the time being, I'm going to move this to the 8.6 milestone and assume we won't get this in within the next couple days.  @lgu1234 if you have time to discuss the fix and help verify it, then it can still go in no problem.  Thanks.

**Comment by lgu1234** [comment]
@Myoldmopar I sent you input and output files yesterday for verification. I still prefer to get it in 8.5.

**Comment by Myoldmopar** [comment]
Yeah, I looked over the outputs of all the files, but I think I need to get
more familiar with the defect before I can click the button.  I imagine it
will go in today, I just need to spend more time reviewing than I hoped.

**Comment by Myoldmopar** [comment]
OK, talked with @rraustad offline and this is good to go in.  I'll resolve the doc merge conflict and get this in.

**Comment by mjwitte** [comment]
Appears that this was a followup to #5375

**Pull request merged**
