### PR TITLE
Fix Foundation:Kiva Custom Block Material Input Processing

### LINKED ISSUE #10766: EnergyPlus 24.2 material error for residential model w/ Kiva custom blocks
Issue overview
--------------
We use Kiva in all of our residential models and the E+ 24.2 release (but not the IO Freeze release) produces an error for every model.

```
** Severe  ** Did not find matching material for Foundation:Kiva="FOUNDATION KIVA 1", Custom Block Material Name, missing material = EXTERIOR VERTICAL INS
```

The material does exist in the model. So it is probably a bug related to https://github.com/NREL/EnergyPlus/pull/10720.

Example file to reproduce:
[in.idf](https://github.com/user-attachments/files/17134789/in.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #10766 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by amirroth** [comment]
Thanks for dealing with this @mjwitte, I've not had time to pay attention to EnergyPlus GitHub the last few days and maybe I should have made time given the impending release. And thanks for adding a test to catch this case.

**Comment by shorowit** [comment]
Built this branch and confirmed that it fixes the issue. Thanks, @mjwitte!

**Comment by Myoldmopar** [comment]
Alright, let's start with this one today.  I will be merging the high priority things and preparing new RCs for 24.2.1.

**Comment by Myoldmopar** [comment]
Everything is happy on CI and locally.  Thanks for this quick fix up @mjwitte

**Pull request merged**
