### PR TITLE
Add Heating Coil that can handle other fuel types

### LINKED ISSUE #5752: Additional fuel type options for furnace heating coils
## Issue overview

Similar to #5746 , furnaces currently only support gas or electric heating coils.  Propane and fuel oil are commonly used fuel types, especially for residential models.  This is similar to #5656 / #5746  which added a fuel type field to OtherEquipment.  In this case, I would suggest adding a fuel type field to Coil:Heating:Gas, and possibly change it's name to Coil:Heating:FuelFired, but maybe not at this point.
### Details

Some additional details for this issue (if relevant):
- Platform (all)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket number 11461.
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by nmerket**
## Pull request overview

Fixes #5752 by adding a new heating coil object that can handle other fuel types.
### Work Checklist
- [x] NFP
- [x] idd changes
  - [x] rename object
- [x] code changes
- [x] unit tests
- [x] transition
  - [x] Expand Objects
- [x] integration/regression test files
  - [x] update old files
  - [x] create a new one
- [x] documentation updates
  - [x] IO Ref
  - [x] Engineering Ref
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nmerket** [comment]
@nealkruis I'm fine with that. I know people get weird about deprecating frequently used object. I was kind of leaning towards doing that under the hood anyway. At least combining this new object with the Gas heating object, that is. I was thinking of leaving electric alone.

**Comment by nmerket** [comment]
Okay, new plan. I'd like to make the following changes to the idd:
- `Coil:Heating:Gas` is to be replaced with `Coil:Heating:Fuel` or something like that. It's identical to the original except that it has a user specified fuel type. The file will rename and transition objects from earlier EnergyPlus releases.
- `Coil:Heating:Electric` will remain the same.

**Comment by Myoldmopar** [comment]
That sounds like a good forward-looking plan.  I think the next phase of this would be to go for Coil:Heating ( or _Coil_ ), and this starts a pattern of generalizing the coil.  I'm not sure about the Fuel name, but you are right, "something like that".  Let me kick off that conversation with some _really good_ ideas:
- Coil:Heating:NotElectric
- Coil:Heating:GasOrWhatever
- Coil:Heating:Fire
- Coil:Heating:DinosaurPowered
- Coil:Heating:UserSpecifiedFuelType

**Comment by nmerket** [comment]
My favorites are GasOrWhatever and DinosaurPowered.

**Comment by EnergyArchmage** [comment]
What about multistage flavors of the coils?  Are you sure don't also need a Coil:Heating:Fuel:MultiStage?

If you have to transition Coil::Heating:Gas to anything else, I say might as well go for changing it all the way to Coil:Heating  (and Coil:Heating:MultiStage) .  The down side of trying to phase things is that the name changes keep happening more often.

**Comment by nmerket** [comment]
The reason to not go to `Coil:Heating` is that I won't be getting rid of `Coil:Heating:Electric`. As for multi stage coils. It's certainly doable, but I'm trying to get this done before the code freeze, so I'm trying to keep it simple.

**Comment by nmerket** [comment]
So, how do we make a final decision about what to call this thing? This will end up replacing Coil:Heating:Gas.

**Comment by shorowit** [comment]
`Coil:Heating:Fuel` seems like a logical name to me.

**Comment by EnergyArchmage** [comment]
"DirectFired" is used in an absorption chiller heater.  so maybe Coil:Heating:DirectFired.

**Comment by mjwitte** [comment]
In this context DirectFired (or the earlier suggestion of Direct) could be confused with direct-fired gas burners (where the combustion products go into the supply air) which is _not_ what we model here.  

I'm ok with `Coil:Heating:Fuel`. 
Other options:
`Coil:Heating:FuelFired`
`Coil:Heating:Combustion`
`Coil:Heating:Burner`.

**Comment by nmerket** [comment]
`Coil:Heating:Fuel` it is.

**Comment by nmerket** [comment]
@Myoldmopar this is ready for review and to be merged.

**Comment by mjwitte** [comment]
@nmerket In the IDD, the Fuel Type field should not be `\required-field`, because it has a `\default`.  (EnergyPlus allows this, but it's confusing to interfaces, so #5817 gets rid of those combinations, among other things.)

**Comment by mjwitte** [comment]
And this object should have a `\min-fields 7` to ensure the default gets filled.

**Comment by nmerket** [comment]
@mjwitte that should take care of your comments on the idd.

**Pull request merged**
