### PR TITLE
Correction of Problem in Natural Convection Equation

### PR DESCRIPTION
**Pull request by RKStrand**
A typo was noted in the natural convection equation in a couple of places.  The main place where it was used was correct, but several subsequent uses of the equation contained a typo (two digits were inverted in a constant in the equation).  This is now fixed and includes a change to the engineering documentation, new unit tests, and corrections to others that had results shifted slightly by this fix.  Some minor differences in some output files are to be expected but should be fairly minor.  This corrects GitHub Issue #6806

Pull request overview
---------------------
This fixes GitHub Issue #6806 (see above).

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue #6806

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by RKStrand** [comment]
@Myoldmopar I've tagged you as the reviewer on this since we have had discussions about it over the last couple of days.  Hope it is easy to review.  I'm guessing there will be some diffs in the output of some files.  Let me know if you run into any trouble (hopefully not).  Thanks!

**Comment by RKStrand** [comment]
@Myoldmopar Hmmm...ok I get that this could have some impacts on various output.  I changed a natural convection correlation in the third significant figure and I would assume that would affect everything.  I'm not sure why this is causing a unit test failure.  I went through and fixed all of the places where there were unit test issues.  So, on my machine, it passed all of the unit tests.  Why is it failing then on the ci machine?

**Comment by mjwitte** [comment]
@RKStrand I merged in latest develop here, let's see how the CI results look now.

**Review by Myoldmopar — APPROVED** [review]
Code changes all look fine, but CI isn't happy with it.  I can pull develop in to the branch and make sure it's related to this branch.  If CI is still unhappy tonight/tomorrow, please investigate.

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte Well, there should not have been a unit test failure.  I was certain I took care of all of those, but clearly one is failing.  That can be fixed.  I should have known that messing with the convection coefficient would result in a lot of differences.  I have spot checked a couple of files and the results are not super surprising.  The natural convection equation got changed in the third significant figure.  That's going to filter through to results in a lot of places.  In the two outputs files I saw, the changes in convection coefficients and temperatures are not that big.  Some heating and cooling numbers are off by a matter of several Watts.  Percentage-wise those are all relatively small (all less than 1%).  I can look at this some more (probably tomorrow) but I'm not sure what to say with respect to what to expect in the differences exactly.  I don't think we are going to get an all tests passed with this kind of change.

**Comment by Myoldmopar** [comment]
You're right, no doubt there will be diffs, but a unit test failure can't go into develop, or it will turn our dashboard red forever.

**Comment by RKStrand** [comment]
@Myoldmopar Agreed--the unit test is a problem and that I can and will definitely fix.  I'll take a break from Eng Ref and get this fixed as soon as possible.

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte Ok, I've fixed the unit test problems and pushed that up to this branch.  New CI run should get triggered and that will hopefully show that there are no more unit test fails now.

**Comment by nrel-bot-3** [comment]
@RKStrand @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@RKStrand This looks good.  It's scary with all the diffs, but the only code change is properly calculating the convection coefficient.  There's no way around it.

This will introduce diffs in other PR regression results, so my plan is to wait and let any remaining CI runs finish up overnight, then when I'm up early in the morning, I'll merge this in.  That should be the least invasive approach.

FYI those of you who may have active PRs with CI runs going: @jasondegraw @rraustad @lgu1234 @Nigusse @JasonGlazer

**Pull request merged**
