### PR TITLE
Fix specific values in component load summary reports

### PR DESCRIPTION
**Pull request by JasonGlazer**
The airloop and facility component loads summary reports had a few numbers that seemed inconsistent with the zone component loads summary report. The pull request addresses some issues found in #6337. 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@larryscheier I have fixed some of the issue that you have found. Some of the issues you reported were based on the times reported at zone, airloop and facility being consistent and one of the fixes was to make the reporting of the times themselves. Given this, more of the differences can be explained because the reports are at different times. I'm still working on some remaining issues but just wanted you to see the status of the fixes so far.

**Comment by JasonGlazer** [comment]
@EnergyArchmage Thank you again for the code for reporting the correct time on the component load summary reports.

**Comment by larryscheier** [comment]
Thanks, Jason! Good to see you are making progress. I have added @EnergyArchmage as reviewer since he will be porting the code changes for T3D+.

**Comment by JasonGlazer** [comment]
Thanks @EnergyArchmage

**Comment by EnergyArchmage** [comment]
I have reviewed the code changes so far and they seem good direction.  I ran some tests on the code changes and they do fix problems we have been finding with the grand totals adding up correctly.  

@JasonGlazer , you mention above you are still working on this, so will wait to do more on the review.

**Comment by JasonGlazer** [comment]
@EnergyArchmage I just did some more final checks and I think that is all the code changes I'm going to do. I still need a unit test and I need to add something to the documentation.

**Comment by JasonGlazer** [comment]
Merged develop because diffs did not seem related to the pull request.

**Comment by JasonGlazer** [comment]
The Aud and Err diffs for Windows and MacOS all look reasonable. Not sure why they are manifesting during for this branch but they are ok.

**Comment by JasonGlazer** [comment]
@larryscheier and @EnergyArchmage this is ready to be reviewed and merged. Let me know if you have any questions.

**Comment by Myoldmopar** [comment]
@JasonGlazer the diffs here looked very minor until the last round of CI.  It looks like you merged develop in, so I don't think it would've been an out of date problem, but I guess it's possible.  I will try to pull it up to develop and let some re-run.

**Comment by JasonGlazer** [comment]
@Myoldmopar those last CI results look very suspicious to me since the changes are only related to reporting. I'm going to do some local testing but I am hoping that it is somehow a disconnect between develop and my branch.

**Comment by Myoldmopar** [comment]
OK, I hope I didn't stomp on your changes when I brought develop into here.  At this point if CI starts reporting, there definitely shouldn't be any unrelated diffs.

**Comment by Myoldmopar** [comment]
Now we're getting somewhere!  Windows was showing the big diffs before but not now.  I will be waiting on merging until a little later today, but this should go in smoothly then.

**Comment by JasonGlazer** [comment]
Great!

**Pull request merged**
