### PR TITLE
HAMT1: Component moisture source (user defined airflow)

### PR DESCRIPTION
**Pull request by antretterf**
Pull request overview
---------------------
Internal moisture source in HAMT components due to user defined air flow through the component. The moisture source is deposited on a user selected layer inside the component. The input for the moisture source is added to the idf file.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 29 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@antretterf I think you should've received an email query about this PR.  If it is to make it into this release, it will need, at a minimum, unit tests, plus reviewers to look it over and evaluate it.  Our cutoff is coming very soon, so I doubt this will drop in this release.  I'm going to label it for the next milestone.  If you feel like you could dedicate some time to writing some unit tests this week then I would be willing to push on it from my end to review it, and we could easily change the label back to E+ 9.0 for this release.

**Comment by mjwitte** [comment]
@antretterf Looks like #6911 supercedes this, so I'm closing this PR.

**Pull request closed without merging**
