### PR TITLE
Update paths to dataset files to eliminate audit diffs

### PR DESCRIPTION
**Pull request by Myoldmopar**
This is one very quick way to clean up the audit diffs.  How will this affect runs from EP-Launch, etc., @JasonGlazer ?

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Nope, sorry.  Running 1ZoneUncontrolled_win_1

```
not found (user input)=C:\datasets\Window5DataFile.dat
not found (idf)=C:\EnergyPlusV8-4-0-Update1\ExampleFiles\datasets\Window5DataFile.dat
not found (epin)=C:\datasets\Window5DataFile.dat
not found (input_path)=C:\datasets\Window5DataFile.dat
not found (program_path)=C:\datasets\Window5DataFile.dat
not found (CWF)=C:\datasets\Window5DataFile.dat
not found (program path - ini)=C:\datasets\Window5DataFile.dat
```

**Comment by Myoldmopar** [comment]
Yeah, I figured it was too easy.  I'll revert out that commit and hack the CMake rules to copy the dataset files into those idfs that need them.

**Comment by JasonGlazer** [comment]
@Myoldmopar I still wish we had a more elegant way of handling file paths in IDF files. Maybe it is time to think about an approach to search parent and sibling directories for the file name. Still allowing for hard paths and relative paths if the user wants.

**Comment by Myoldmopar** [comment]
OK, trial 3: just cleanse the audit file lines before doing the diff.  If this is successful, this branch should be deleted and the branch over in DevSupport merged in.

**Pull request closed without merging**
