### PR TITLE
Add the latest LCC fuel escalation factors from NIST 2016

### PR DESCRIPTION
**Pull request by JasonGlazer**
Added the LCCusePriceEscalationDataSet2016.idf file to address #5873. This file is based on the 2016 update to NIST 135. This is for use with the LifeCycleCost:* objects to include energy price escalation data based on the NIST projection.

Includes same updates for the unit tests and installer as made in #5522

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

…ts and installer.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@EnergyArchmage I know you were hoping for this to be in 8.6.0 but it should be in the next release.

**Comment by JasonGlazer** [comment]
Reran the Linux Ubuntu tests and they came back clean

**Comment by JasonGlazer** [comment]
For the Windows 7 unit tests, the EnergyPlusFixture.SiteGroundDomainSlab_CheckInputs_BadOSCMName had the error:

> unknown file: error: C++ exception with description "InitializeMeters: Could not open file eplusout.mtd for output (write)." thrown in the test body.


I cannot reproduce this locally so I am rerunning those tests.

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte the CI is finally clear on this and it is ready to be reviewed and merged.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Pull request merged**
