### PR TITLE
Ground domain update

### PR DESCRIPTION
**Pull request by Myoldmopar**
## Pull request overview

This replaces the previous ground domain update PR that was gobbled by gitmania.  This is nearly ready for merge, with only one remaining test file to investigate.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@mitchute I'm pulling develop into this branch to resolve conflicts, then pulling the VS2015 branch into here to get this moving again.  Hopefully testing will reveal no issues so this can just drop in very soon.

**Comment by Myoldmopar** [comment]
So, I merged develop.   Quite a few random conflicts in idfs, look to be due to a cleanup pass on the idfs along the way.  I think I got them done without any numeric differences, but we'll see.  Where the conflicts looked annoying, I took the version from this branch.  Where the conflicts looked like just cleanup, I took the version from develop.  

I then merged in the VS2015 branch.  That should produce a successful 2015 build, and a failed 2013 build.  At which point, I can use this branch or another one to delete the 2013 build from the decent ci yaml files.

**Comment by Myoldmopar** [comment]
@mitchute The Windows builds are going to be fine now that we have 2015.  But something between [Jun 16](https://github.com/NREL/EnergyPlus/pulls?page=2&q=is%3Apr+is%3Aopen#commitcomment-17891181) and [Aug 17](https://github.com/NREL/EnergyPlus/pulls?page=2&q=is%3Apr+is%3Aopen#commitcomment-18669391) caused Linux to go down too, and it never recovered.  I'll check this morning, but I hadn't noticed this in the face of the blatant failing Windows builds.

**Comment by Myoldmopar** [comment]
Aaaaand of course the Linux build on my Ubuntu 14.04 VM runs the tests perfectly smooth.  In debug build anyway.  I guess I'll kick off a release build and see if I can replicate this.

**Comment by Myoldmopar** [comment]
Yep, release builds also pass locally.  What in the heck.  OK, I'll get on the CI machine itself and see what's going on.

**Comment by Myoldmopar** [comment]
..........and on the CI machine, the tests run fine also.  Hmmmmm.

**Comment by Myoldmopar** [comment]
@mitchute Can you build this on your Linux box real quick and try running a few tests?  After getting on the CI box and building/testing locally right there, I'm feeling half crazy.

**Comment by mitchute** [comment]
@Myoldmopar building locally now. I'm running to a meeting, but will test when I get back.

**Comment by mitchute** [comment]
@Myoldmopar I ran integration tests on 1Zone*, 5Zone*, and AirflowNetwork*. All passed OK.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 15 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Looks like a clear starting point since `ZoneCoupledGroundHTSlabOnGrade` is failing now.

**Comment by Myoldmopar** [comment]
Oh haha, there's a merge conflict left in that file.  I'll fix it.

**Comment by Myoldmopar** [comment]
OK, that should fix the failing file, and this can be merged.

**Comment by Myoldmopar** [comment]
And yeah, I'm also not sure what's up with the Linux results there.  I just built locally on Linux and it seems to be running tests OK.  Though I'm having an issue with compiling the milo third_party library.

**Comment by Myoldmopar** [comment]
Still not sure about those Linux results.  I tested a release build as well, and it runs OK.

**Comment by Myoldmopar** [comment]
I just built on the CI Linux box, release build, and it runs fine.  I'm not holding this up because of the stray Linux issues...

**Comment by Myoldmopar** [comment]
All the diff files are ground heat transfer related.  Final call for objections to drop this in.  Countdown begins now:
image

**Pull request merged**
