### PR TITLE
Fix Tiny IDD Issues

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
I don't know if we'll do a re-release or not to accommodate these fixes, but I'm pushing the commit anyway.  Any changes to the IDD have to be incredibly small here.  Right now it is just the key choices for plant op schemes.

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@mjwitte (or anyone else) I'm planning on dropping this in now.  It just adds the operation scheme idd keys that caused such an issue at the end of the last release.  I'll merge if I don't hear back in a bit.

**Comment by mjwitte** [comment]
@Myoldmopar Yeah, that's fine.

**Pull request merged**
