### PR TITLE
Sixth (and Final) Set of Engineering Reference Comprehensive Edits

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
This work is the sixth and final defect that looked to fix a host of issues in the Engineering Reference including equation reference errors, equation inconsistencies and errors, figure and table reference issues, and a host of other mistakes, typos, formatting issues noted along the way. This final defect covers from roughly p. 1454 (start of what is now the start of Section 19.5) through the end of the Engineering Reference. This work resolves GitHub Issue #6982 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs github defect issue #6982 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by Myoldmopar — APPROVED** [review]
This looks great.  I just built it locally and it builds fast and with zero errors.  CI had a bit of trouble, but I'm hoping an unrelated blip, so I kicked off the Linux build again just to be sure.  If it comes back clean I'll merge this in and it'll be all done for 9.0.

Future work: It would be great if you or someone could now go through the document and adjust the figure widths.  It would be a **much** less intensive process (maybe a couple hours max) but could go a long way toward making the document really shine.

**Comment by RKStrand** [comment]
@Myoldmopar Sounds good--hopefully it's just a blip and this makes it into 9.0.  I was really hoping for that and kinda crossing my fingers that it would still make it.

As for the next round, I'm definitely up for working on figures in the next round.  We can discuss that sometime after the flurry of the release is past.  Thanks!

**Comment by Myoldmopar** [comment]
Hmmmm another unhandled failure.  I don't see how this could cause that, but I'm not willing to risk much at this point.  I just did a merge of develop into @rraustad 's branch for #6989, let's see what Linux reports there here in an hour and then I'll decide how to proceed.

**Comment by RKStrand** [comment]
@Myoldmopar Hmmm.  Not sure why that is happening or even what is causing it.  Hard to see how doc changes would cause something like this...and I made sure to check for bad math issues so there shouldn't be any of those.  I totally get not wanting to risk anything this close to the release though.  I know that I merged develop into that branch at least once...hopefully that didn't cause a problem.  Keep me posted.

**Comment by Myoldmopar** [comment]
OK.  I have **no** idea why this is causing an issue.  I'll have to investigate, but for now, we can't risk this anomaly causing an issue with the release.  After we tag v9.0 done, we'll work on figuring out why this is a problem and get it merged in right after release.

**Comment by Myoldmopar** [comment]
The unhandled failure was showing up in package builds too, totally unrelated to this.  But now those seem to have cleaned themselves up.  I have also tagged v9.0.0, so now we are on to the next release.  This is the first merge of the (next version number TBD) release cycle.

**Pull request merged**
