### PR TITLE
AirloopHVAC:UnitarySystem  heating only systems incorrectly size flow rate when using FlowPerHeatingCapacity method

### PR DESCRIPTION
**Pull request by rraustad**
Addresses #4702 
Corrects AirloopHVAC:UnitarySystem sizing when FlowPerCoolingCapacity or FlowPerHeatingCapacity are specified as the Cooling/Heating Supply Air Flow Rate Method.
Also fixes sizing issue with multi-speed coils. CapFT curve was not being used during sizing.

### CODE REVIEW

**Comment by rraustad** [comment]
It's not surprising the multi-speed coil example files show diff's. Sizing was incorrectly using CapFT to size the coil instead of MSCapFT.

**Comment by Myoldmopar** [comment]
@rraustad If you take a look at the [Files Changed](https://github.com/NREL/EnergyPlus/pull/5209/files) for this pull request, you'll see that DXCoils.cc has 884 lines added, 864 lines deleted.  This means every line in the file was modified.  This screams of a line ending problem.

My steps:
- Check out this branch
- Open src/EnergyPlus/DXCoils.cc in my text editor [of choice](https://www.geany.org).  It recognizes that the file has my native (Linux) line endings.  So far so good.
- Search for Windows line endings -- none

Hmm.  OK.  

Next steps:
- Merge develop into this branch  (`git fetch origin; git merge origin/develop`)
- Compare develop and this branch locally (`git diff develop..'#4702reallylongbranchname'`)
- Investigate the diffs.....looks like it is tab vs. space issue.

To Fix:
- Back in text editor, change spaces to tabs
- Commit and compare branches ... looks better, but not 100% confident.
- Push up and let Github show me what it thinks the diffs look like (40a0a78)

There we go!! DXCoils now shows about 80 lines changed.  Good to go.

**Comment by nrel-bot-3** [comment]
@rraustad @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@rraustad I did a small cleanup where trailing spaces were left in and merged up develop.  I am building this locally and will do some runs to verify the fix and if all is good I'll merge this.

**Comment by Myoldmopar** [comment]
@rraustad It looks like the last time I pulled develop in, develop moved shortly after causing some unrelated diffs to appear.  I pulled in develop one more time, and CI isn't very busy, so I would expect it to report quickly back.  Thanks for providing the defect file and verification information.

**Comment by Myoldmopar** [comment]
Yep, already looking better.  Back down to 7 issues.  And 1 may be the merge I just made.

**Comment by rraustad** [comment]
What the heck is this? AirflowNetwork_Multizone_House_TwoSpeed

User-Specified Minimum Outdoor Dry-Bulb Temperature for Compressor Operation [W], 10164.00000

**Comment by amirroth** [comment]
The house is on the surface of the sun?

**Comment by rraustad** [comment]
This looks better. 

The new VRF model was using the wrong input field to describe air flow rate, a different field for the cooling and heating coil. Since that new coil type does not have an input field for air flow rate, the sizing routine "sets" the reported text. Reporting a result to the eio file that does not exist in the object is not standard practice, I didn't notice that before.

```
- Component Sizing Information, Coil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl, TU1 VRF DX COOLING COIL, Design Size Rated Sensible Heat Ratio [m3/s], 0.34609
+ Component Sizing Information, Coil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl, TU1 VRF DX COOLING COIL, Design Size Rated Air Flow Rate [m3/s], 0.34609
```

I will take a close look at the remaining diff file.

**Comment by Myoldmopar** [comment]
It's an E+ Easter Egg.  We just pick miscellaneous temperatures, watts, and field nums, and then fill them into a madlib and spew it to the eio.  It's fun!

```
_____ error, check ______ and _______ ______, then re-run.
 adj              pl. noun      adj    noun
```

**Comment by rraustad** [comment]
The HVACTemplate-5ZoneUnitarySystem file now looks correct to me. The multispeed coil was not including fan heat in it's calculation of capacity.

The difference here is fan heat at 198.19 W (value from single stepping code) which is now included.

```
- Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL MULTISPD UNITARY SYSTEM, Design Size Nominal Cooling Capacity [W], 4379.31471
+ Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL MULTISPD UNITARY SYSTEM, Design Size Nominal Cooling Capacity [W], 4577.73056
```

**Comment by rraustad** [comment]
Unit test: DXCoils_Test1 passes on my PC.

**Comment by nrel-bot-3** [comment]
@rraustad @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Ugh.  I tried to do the merge on this one and am not confident I'm getting them right.  The unitary system is conflicted, but it has to do with the clear_state function.  I think that one I got.  But the DXCoils has diffs because of changes with the new VRF model updates.  @rraustad Could you try to do the merge?  If it gets bad, we could either work together during the merge with @rongpengzhang as well, or we could just re-apply your changes for this PR into a brand new branch.  I'm not sure which is easier.  You might do the conflict resolution and be able to easily see the issues.  But when I see a block like this:

```
<<<<<<< HEAD
        Real64 QZnReqSenCoolingLoad; // Zone required cooling load (W)
        Real64 FanSpdRatio; // Fan speed ratio
        Real64 TcoilIn; // Air temperature at the inlet of the coil (C)
        Real64 HcoilIn; // Air enthalpy at the inlet of the coil (kJ/kg)
        Real64 ActualSH; // Super heating degrees (C)
        Real64 ActualSC; // Sub cooling degrees (C)
        int OperatingMode; // Coil operation mode: 0 for cooling, 1 for heating, 2 for neither cooling nor heating
=======
        Real64 QCoilReq; // Coil load (W)
        Real64 FanSpdRatio; // Fan speed ratio
        Real64 AirMassFlowMin; // Min air mass flow rate due to OA requirement [kg/s]
        Real64 ActualSH; // Super heating degrees (C)
        Real64 ActualSC; // Sub cooling degrees (C)
>>>>>>> origin/develop
```

Where in this branch a `QZnReqSenCoolingLoad` variable exists, but in develop, a `QCoilReq` variable exists, I get uncomfortable about just picking one.

**Comment by rongpengzhang** [comment]
@Myoldmopar It seems @rraustad started from an older version. This is not a big deal. I will fix it by pushing a new commit in this branch.

**Comment by Myoldmopar** [comment]
OK @rongpengzhang, and good luck.  @rraustad I'll need a verification from you on how the conflict resolution turned out, and then I'll get back to normal review mode.  Thanks all.

**Comment by rraustad** [comment]
So do I do something here? Or will Rongpeng's commit fix this?

On 1/11/2016 12:08 PM, Rongpeng Zhang wrote:

> @Myoldmopar https://github.com/Myoldmopar It seems @rraustad 
> https://github.com/rraustad started from an older version. This is 
> not a big deal. I will fix it by pushing a new commit in this branch.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/NREL/EnergyPlus/pull/5209#issuecomment-170620578.

## 

Richard Raustad
Florida Solar Energy Center
1679 Clearlake Road
Cocoa, FL 32922
Ph: (321)638-1454
http://www.fsec.ucf.edu/en/

Program Director
Electric Vehicle Transportation Center
http://evtc.fsec.ucf.edu/

**Comment by Myoldmopar** [comment]
@rongpengzhang is offering to resolve the conflicts, and he will push up a commit that merges the changes together.  After that, however, I'll just need you to look over his resolution and make sure the changes you intended are still being made properly.  So nothing for now until @rongpengzhang commits here or messages that he has questions during the merge.

**Comment by rongpengzhang** [comment]
@Myoldmopar @rraustad I thought that the one conflict Edwin mentioned is all we need to face, so I thought it should be quick. But then I found there are much more conflicts than that, coming from (1) DXCoils.cc and (2) HVACUnitarySystem.cc. Edwin just gave an example.

@rraustad Edwin offered two options. Which one do you think is better to solve these conflicts? If you like, I can help you to clean up the conflicts in (1) DXCoils.cc, since the conflicts in this file mainly come from my codes that I am most familiar with.

**Comment by mjwitte** [comment]
@rongpengzhang , This branch was current as of Dec 8., but it didn't make the cut to get merged for Update 1.  So, probably best at this point to create a branch of develop as of Dec 8 to show @rraustad 's original changes in context without yours.  I can help do that if you want. Or @Myoldmopar can probably create a link with that diff in 2 seconds or less.

**Comment by Myoldmopar** [comment]
So this compares develop on December 8, 2015 to the current state of this 4702 branch:

https://github.com/NREL/EnergyPlus/compare/develop@%7B2015-12-08%7D...%234702-AirloopHVACUnitarySystem-autosizing-incorrect-for-heating-only-systems-when-using-FlowPerHeatingCapacity

**Comment by mjwitte** [comment]
@Myoldmopar Thanks - except GitHub chokes on dxcoils.cc and won't display the diffs, so have to compare that locally.

**Comment by Myoldmopar** [comment]
OK, so it looks like the effort for this PR is to either:
1. Try to resolve the merge conflicts, which will likely require having @rongpengzhang and @rraustad on the same call and do it interactively, or
2. maybe it would be easier for @rraustad to just re-apply the same changes to develop as of today and throw this one away.  

@rraustad Your call.  I'm happy to pitch in to help coordinate or whatever.  I was happy to try to resolve the merge conflicts, but it was going to take a lot of time for me to get it right on this one.

**Comment by rongpengzhang** [comment]
@rraustad @Myoldmopar @mjwitte 

I have updated DXCoil.cc, solving its conflicts with the most updated Develop branch. Note that I only solve the conflicts related with the VRF-FluidTCtrl model. There are also some other conflicts in this files, probably related with Rich's work in another branch. I didn't touch them since I'm not very familiar with them.

**Comment by rongpengzhang** [comment]
Oops, I didn't read the two options given by Edwin just now. 

@rraustad If you choose option 1, I think you can use the DXCoil.cc file I just pushed, and continue working on it to solve other conflicts. If you choose option 2, then just forget about the commit I just pushed.

In my opinion, option 2 may be a better choice.

**Comment by rraustad** [comment]
I wound up with this, is this the correct version?

```
    // Followings for VRF FluidTCtrl Only
    Real64 QCoilReq; // Coil load (W)
    Real64 FanSpdRatio; // Fan speed ratio
    Real64 AirMassFlowMin; // Min air mass flow rate due to OA requirement [kg/s]
    Real64 ActualSH; // Super heating degrees (C)
    Real64 ActualSC; // Sub cooling degrees (C)
```

**Comment by rongpengzhang** [comment]
@rraustad Yes, this is the right version. Please let me know if you have any questions on my updates.

**Comment by rraustad** [comment]
I think I got everything. I don't understand what is causing the error with ControlVRFIUCoil?

**Comment by rraustad** [comment]
Must I really move this function to avoid this error? Why hasn't this happened before?

http://stackoverflow.com/questions/16290834/error-c3861-rolldice-identifier-not-found

Compiler goes through your files from the beginning till the end, meaning that the placement of the definition of your function matters. In this case, you can either move the definition of this function before it is used first time:

void rollDice()
{
    ...
}

void otherFunction()
{
    // rollDice has been previously defined:
    rollDice();
}
or you can use forward declaration to tell the compiler that such a function exists:

// function rollDice with the following prototype exists:
void rollDice();

void otherFunction()
{
    // rollDice has been previously declared:
    rollDice();
}

// definition of rollDice:
void rollDice()
{
    ...
}

**Comment by rongpengzhang** [comment]
@rraustad At the beginning of each cc file, we include the corresponding hh file, such as DXCoil.hh. So we don't need to define functions in the cc file before it is first called.

I think I didn't update DXCoil.hh just now when I updated DXCoil.cc to solve the conflicts. I renamed function "CalcVRFIUAirFlow" to "ControlVRFIUCoil", so it should be updated in hh file.

Can you please delete the "CalcVRFIUAirFlow" defenition in DXCoil.hh, and paste the following:

```
void
ControlVRFIUCoil (
    int const CoilIndex,  // index to VRFTU coil 
    Real64 const QCoil,   // coil load
    Real64 const Tin,     // inlet air temperature
    Real64 const Win,     // inlet air humidity ratio
    Real64 const TeTc,    // evaporating or condensing temperature
    Real64 const OAMassFlow,  // mass flow rate of outdoor air 
    Real64 & FanSpdRatio, // fan speed ratio: actual flow rate / rated flow rate
    Real64 & Wout,    // outlet air humidity ratio
    Real64 & Tout, // outlet air temperature
    Real64 & Hout, // outlet air enthalpy
    Real64 & SHact,   // actual SH
    Real64 & SCact    // actual SC
);
```

**Comment by rraustad** [comment]
There is no CalcVRFIUAirFlow in the hh file.
Should there be something else at the top of the hh or cc file?

DXCoils.hh

```
#ifndef DXCoils_hh_INCLUDED
#define DXCoils_hh_INCLUDED

// ObjexxFCL Headers
#include <ObjexxFCL/Array1D.hh>
#include <ObjexxFCL/Optional.hh>

// EnergyPlus Headers
#include <EnergyPlus.hh>
#include <DataGlobals.hh>
#include <DataHVACGlobals.hh>
#include <DataEnvironment.hh>

namespace EnergyPlus {
```

**Comment by rraustad** [comment]
Sorry, that was DXCoils.hh. At the top of the cc file is

```
#include <cassert>
#include <cmath>
#include <string>

// ObjexxFCL Headers
#include <ObjexxFCL/Fmath.hh>
#include <ObjexxFCL/gio.hh>

// EnergyPlus Headers
#include <DXCoils.hh>
```

**Comment by rraustad** [comment]
Only 1 diff now explained by change in sizing (fan heat now included for multispeed coil, see Dec 8 comment above)

**Comment by Myoldmopar** [comment]
I made some very minor changes, formatting only.  I guess I'll let CI take one more pass just to make sure I didn't break anything doing that, then this can merge.  Thanks for all the effort in merging the work together.

**Comment by Myoldmopar** [comment]
Another pull up to develop....gosh, if @myoldmopar would just stop merging other things in.....

**Comment by rraustad** [comment]
:smile: :+1: :clap:

**Comment by rongpengzhang** [comment]
:clap:

**Comment by Myoldmopar** [comment]
:penguin: :high_brightness: :cyclone: :woman: :arrow_up_down:

**Comment by Myoldmopar** [comment]
@rraustad Can you update the title of this PR so that it is more user-digestable in the auto-generated ChangeLog?  Thanks!

**Pull request merged**
