### PR TITLE
Global DataGlobals: Part 3

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Continue moving DataGlobals to state

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
FYI @Myoldmopar 

It looks like ```Test_UnitaryHybridAirConditioner_Unittest``` is beginning to show some spurious failures. I noticed it over on #8302 today, and now it's showing up here. I haven't been able to reproduce it reliably locally, though, my Mac is on 10.14 and CI is on 10.15 which may make a difference.

Why don't you go ahead and share the link to your Google Keep to-do list so I can add it? 🤪

**Comment by Myoldmopar** [comment]
OK, the audit diffs are unrelated and will be resolved soon.  The hospital timeout has always happened spuriously and even throughout this PR it's happened sometimes and sometimes not.  The Kiva failure is also appearing occasionally and I don't think it is related to this.  

@mitchute if you are planning on adding more to this branch, then just let me know and continue on.  If not then I think let's go ahead and get this merged in.

**Comment by mitchute** [comment]
No, I'm done here. I'll deal with the conflicts tonight (if you don't get to them first).

**Comment by Myoldmopar** [comment]
This looks fantastic!  I'll merge this thing in.

**Pull request merged**
