### PR TITLE
VRP fix D term application and Vou reporting

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Pull request overview
---------------------
addresses issue #6790.  Trane identified mistakes in VRP Standard 62.1 and is contributing these code corrections to DOE version. 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by rraustad** [comment]
@mjwitte @Myoldmopar these are not the same diffs we get on the FSEC CI. As @EnergyArchmage said there are diffs in coil sizes, air flow, etc.

Subset of diffs for 5ZoneAirCooled_VRPSizing_MaxZd on FSEC CI:

fsec_ci_diffs for vrp change

**Comment by Myoldmopar** [comment]
When I run 5ZoneAirCooled_VRPSizing_MaxZd locally on develop and this branch, I get the following eio files, which seem to agree with CI.

[base.eio.txt](https://github.com/NREL/EnergyPlus/files/2121656/base.eio.txt)
[mod.eio.txt](https://github.com/NREL/EnergyPlus/files/2121657/mod.eio.txt)

**Comment by rraustad** [comment]
Those match exactly to CI. I will check the code changes in each of these branches.

**Comment by rraustad** [comment]
OK, this code lacks a change that would certainly make OA increase but has nothing to do with this VRP issue. So maybe I spoke too soon and the example files do all have D=1 and diff's should not show up with our test suite and the changes here are still valid (and now explainable).

**Comment by rraustad** [comment]
Sure enough, D=1 so there should be no change with the new calculations.

vrp_d1

**Comment by EnergyArchmage** [comment]
After reviewing CI and local integration tests, there is something strange going on with capacity values in system sizing sequences.  These changes need more investigation.

**Comment by EnergyArchmage** [comment]
I believe this is finished and ready for review, merging.  small diffs in VRP system sizing outcomes are expected.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@EnergyArchmage I'm going to merge in develop here and see how it looks. Holler if you're working on this.

**Review by mjwitte — APPROVED** [review]
This is a fairly compact set of changes which make significant changes in some VRP values but overall no huge diffs. The only thing missing here is unit tests.
@Myoldmopar I'm inclined to merge this anyway. Should probably wait for a few more CI reports.

**Comment by Myoldmopar** [comment]
I'm OK with this going in.  The same VSCoil unit test failure that periodically comes up (a missing thing in a clear_state no doubt) is happening, but that's nothing to do here.  I'll wait until morning and let some more CI results pop up then merge if all is well.

**Comment by mjwitte** [comment]
Same here, still waiting on more CI results.

**Pull request merged**
