### PR TITLE
Continue Refactor of LoadProfile:Plant Code

### PR DESCRIPTION
**Pull request by drewyh**
Pull request overview
---------------------
This pull request does some refactoring of the LoadProfile:Plant code to continue the conversion to a more object oriented approach which was mostly complete for this component. Also includes a cleanup of variable renaming, code restructuring etc. This should result in no diffs.

There are some changes beyond the scope of the LoadProfile:Plant file:
- InputOutput Ref - Updated docs to simplify/clarify some items
- Engineering Ref - Updated docs to simplify/clarify some items

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] ~~If defect, results of running current develop vs this branch should exhibit the fix~~
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
- ~~IDD changes:~~
   - [ ] ~~Verify naming conventions and styles, memos and notes and defaults~~
   - [ ] ~~Open windows IDF Editor with modified IDD to check for errors~~
   - [ ] ~~If transition, add to input rules file for interfaces~~
   - [ ] ~~If transition, add transition source~~
   - [ ] ~~If transition, update idfs~~
 - [ ] ~~If new idf included, locally check the err file and other outputs~~
 - [ ] Required documentation updates?
 - [ ] ~~ExpandObjects changes?~~
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 49 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@drewyh I pulled the latest develop branch into here to see about getting some good CI results and see if we can push this along into our main branch.

**Comment by Myoldmopar** [comment]
Those ESO small diffs are Joules, and on the order of e-09, so indeed exceedingly small, and likely just due to the minor change in calling sequence.  I'll do a full review of the changes now that CI is really happy and see if we can get this in.

**Comment by nrel-bot-2b** [comment]
@drewyh @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I have no idea why our CI engine is getting stuck on this and re-running things.  I'm going to close this for right now and see if CI gives up or if I need to make some changes to the CI code.

**Pull request closed without merging**
