### PR TITLE
Update to version 22.2

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
Standard version change stuff: 
 - Update CMake version spec to 22.2.0
 - Added 22.1.0 IDD and supporting transition material
 - Ran change_version script which ran with 100% success, including the EpJSON files

The review check is whether CI is all clean.  For example, if I forgot to change a version in an IDF, it would show up as a diff in the accompanying err file (expected version XYZ, etc.).  If it's clean it should be good to merge in as we have reached cruising altitude toward 22.2.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
The Windows failures are being fixed in a hotfix branch, this is all clean.

**Comment by dareumnam** [comment]
Looked at every file and this looks great. I think this is good to get merged in.

**Review by dareumnam — COMMENTED** [review]
Looked at every file and this looks great. I think this is good to go.👍

**Comment by dareumnam** [comment]
`release/readme.html` is going to be updated right before the release after we know exactly what new features and capabilities we've added. Everything looks great, merging. Thanks, @Myoldmopar!

**Pull request merged**
