### PR TITLE
Member array usage eliminated

### PR DESCRIPTION
**Pull request by DeadParrot**
Member array usage (treating members of elements of an array as an array) via hard-coded array method names has been eliminated to facilitate use of other containers. C++ does not provide a good mechanism to emulate Fortran's member array capability with a clean syntax. ObjexxFCL continues to provide a member array (MArray) capability via a less elegant syntax for special case usage.

The migration used a combination of for loops, C++ library calls such as `std::any_of` and `std::count_if`, and some functions in a new member.functions.hh header that accept member pointers to provide common operations such as sum, minval, and maxval. When it provided for much more compact and clear code the member functions were preferred even though member pointer usage will be new to most EnergyPlus developers.

### CODE REVIEW

**Comment by DeadParrot** [comment]
@Myoldmopar Looks like all the diffs are epsilon so it should be ready for review when time allows.

**Comment by DeadParrot** [comment]
@nealkruis It looks like @lgentile has asked you to review this one as well. If you need some background on why we are doing this let me know.

**Comment by mjwitte** [comment]
@DeadParrot Curious why this would result in any diffs at all.  These should all be equivalent operations, no?  Also, given the sweeping changes and conflict potential this probably needs to hold until after the 8.4 bugfix release.

**Comment by mbadams5** [comment]
I am curious as well.

**Comment by Myoldmopar** [comment]
@mjwitte I agree on the no-diffs; I was expecting all green.  They may all be epsilon-related changes, but now it takes time to verify it.  

As for the merge conflicts, I could see arguments for both sides  I'm not inclined to hold this up and let it become conflicted in many places, if it's just a matter of a couple lines in other folk's branches.  I am able to help resolve merge conflicts _related to this change_ if one of the developers is having trouble, so don't sweat that too much.

**Comment by mbadams5** [comment]
@DeadParrot It seems like vectorize.hh is a new file but it isn't showing the added lines in the PR. Anyways, [this will fail on Mac with Apple's clang](https://github.com/NREL/EnergyPlus/blob/e1db6cefbc60c9c1b7f0221de47ee9a3740bbab4/third_party/ObjexxFCL/src/ObjexxFCL/vectorize.hh#L19). Only the newest version of Apple's clang has the builtin, which is major version 7; however there is major version 6 and lower which will be caught by your check. Clang has a builtin that can check if it has another builtin function, [__has_builtin()](https://github.com/NREL/EnergyPlus/blob/8c5c3d8fcc3f8e4a2e4b8d63a39fffcd0e493fc3/src/EnergyPlus/HeatBalanceIntRadExchange.cc#L242), which can be used like `#if __has_builtin( __builtin_assume_aligned )`

**Comment by DeadParrot** [comment]
@mjwitte @Myoldmopar this effect is something we've seen all along. These epsilon diffs are at the level I get from compilers simply reorganizing code: register use changes, loop operation order, etc. In some places we do the same computation with a library function vs a loop and, yes, that will cause epsilon changes unfortunately. This becomes a validation problem for less stable cases that can blow these least significant bit changes up to something bigger. We might reduce this by doing CI runs with floating-point-precise types of switches, or else we should rework the CI system to use a tolerance.

**Comment by DeadParrot** [comment]
@mbadams5 I don't know why Github isn't showing an added file. vectorize.hh is really from an upcoming bigger ObjexxFCL update that has improved vectorization support and efficiency gains for the vector-like API by doing raw+placement allocations (so you aren't default constructing elements in the excess capacity portion). I pulled vectorize over now to give Amir the portable macros for alignment and restrict.

I'm not sure why that check is failing but the intent was that (I thought) Clang added `__builtin_assume_aligned` in version 3.6 on all platforms. Can you tell me where I went wrong on that and if by "fail" you mean it breaks building or that it doesn't provide the builtin that is actually supported? I could switch to the `__has_builtin` approach if that helps.

**Comment by mbadams5** [comment]
@DeadParrot I figured vectorize.hh was part of a bigger update later.

Clang DID add `__buildtin_assume_aligned` in version 3.6 on all platforms, however Apple being, well, Apple, changed things. So with Apple's version of Clang, XCode 6 == Clang 6.0.0 and XCode 7 == Clang 7.0.0. Apple didn't include that new builtin until XCode 7 aka Clang 7.0.0. With XCode 6, it will throw the following compiler error:

```
main.cpp:6:25: error: use of undeclared identifier '__builtin_assume_aligned'
  double *aa = (double*)__builtin_assume_aligned(AA, 16);
                        ^
1 error generated.
```

But if you check XCode 6 (Clang 6.0.0) with `( ( __clang_major__ > 3 || ( ( __clang_major__ == 3 ) && ( __clang_minor__ >= 6 ) ) )` I bet it will pass that check because `6 > 3`.

**Comment by DeadParrot** [comment]
@mbadams5 I'm not sure what the best/suggested approach is. Is there a macro that tells us we are in XCode? Is using the `__has_builtin` the best and safe approach?

**Comment by mbadams5** [comment]
@DeadParrot It isn't so much that you are in XCode since command line clang on Mac is still the XCode version.

Anyways, I personally think `__has_builtin` is probably the safe approach as you can see in [Amir's branch](https://github.com/NREL/EnergyPlus/blob/8c5c3d8fcc3f8e4a2e4b8d63a39fffcd0e493fc3/src/EnergyPlus/HeatBalanceIntRadExchange.cc#L242). I thought it would be too hard otherwise to have conditionals for regular LLVM/Clang and Apple's Clang. The only other thing to watch out for is that [clang (and ICC) both implement](http://nadeausoftware.com/articles/2012/10/c_c_tip_how_detect_compiler_name_and_version_using_compiler_predefined_macros) `__GNUC__`. However, your existing code will be fine for Apple's clang since it defines `__GNUC__ = 4; __GNUC_MINOR__ = 2; __GNUC_PATCHLEVEL__ = 1;`

If you have more questions, thoughts, concerns, etc. let's email since this isn't really related to this pull request.

**Comment by DeadParrot** [comment]
Looks like we are now all green so the next decision is whether to merge or wait until after the 8.4.1 release. I already had to resolve conflicts to catch up because @nmerket did some of his own member array elimination work. If it is decided not to merge this for 8.4.1:
- Since this is going to be a lot of work for me to catch up it would be great if we had a 8.5 branch set up where we can merge non-fix PRs that are not for 8.4.1
- I will want to pull out the ObjexxFCL changes and make an 8.4.1 PR for them since there are some potential performance and problems addressed.

**Comment by Myoldmopar** [comment]
@DeadParrot I think we are going to wait until the 8.4.0+BugFix release to get this in.  Code for that will be frozen on December 14.  If we can just let this hold for less than 2 weeks, I will be happy to help resolve any conflicts that occur during that time.  On that date, _this_ branch will be a primary to get in, to avoid a big resolution issue.  In the next release cycle, we'll set up the more typical approach of having a branch ready for a bug fix release as well as branch: `next`.  If that's OK with you, we'll hold here and then after code unfreezes, I'll assist in any more merge conflicts that arise.  In the meantime, you can start on any other tasks.

**Comment by DeadParrot** [comment]
OK. If we merge this first after the freeze that will be good to avoid a lot of redo work. I found that after the earlier pass of fixing all the `FindtItem*` and `VerifyName` calls that a lot of new usage of them with member arrays reappeared quickly in new code. Until we pull out the member array support people will continue using it by habit.

The `next` branch approach will be good overall. The downside is needing to merge patches to the bug fix branch into the `next` branch but that isn't usually terrible.

What about doing just the ObjexxFCL part of this for 8.4.bugfix? There is a small chance of a performance or behavior issue addressed affecting the current code base.

**Comment by Myoldmopar** [comment]
I am totally open to the ObjexxFCL changes dropping in now if you feel like extracting those changes out by themselves.  Issue me a new PR with just those and I'll review and merge.

**Comment by DeadParrot** [comment]
@Myoldmopar OK, ObjexxFCL update is up in PR #5347.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@DeadParrot I pulled develop in from today.  There were some conflicts from the licensing text changes.  They were all pretty straightforward though.  I got a build completed on my machine, so I went ahead and pushed it up.  If CI is happy with it, I will merge this in.

**Comment by Myoldmopar** [comment]
Already looking promising.  Expect this merged this evening.

**Pull request merged**
