### PR TITLE
Avoid AFN fan array bounds error

### LINKED ISSUE #10630: AFN fan array bounds error with multiple airloops
Issue overview
--------------
User file fails with 
```
   ** Severe  ** AirflowNetwork: The airflow direction is opposite to the intended direction (from node 1 to node 2) in AirflowNetwork:Distribution:Linkage = ZONECONNECTIONDUCT_UNIT1_ZN2_RETURN LINKAGE
   **   ~~~   **  Environment=ANNUAL, at Simulation time=01/04 12:00 - 12:10
   **   ~~~   ** The sum of the airflows entering the zone is greater than the airflows leaving the zone (e.g., wind and stack effect).
   **   ~~~   ** Please check wind speed or reduce values of "Window/Door Opening Factor, or Crack Factor" defined in AirflowNetwork:MultiZone:Surface objects.
```

Tried to debug this, but hit an array bounds error here, because both fans have airloop=1, so the for loop exits, leaves `FanNum=3` but there's only 2 fans, so array bounds exceeded. This for loop to look for a matching fan is fragile, and this pattern appears several times.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L8889-L8894

So, why are both `DisSysCompCVFData(FanNum).AirLoopNum=1`? The problem is this function, which was added in #7884 . The logic here ends up setting all fans to the same airloop number.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L10101-L10117

Later on in the simulation, airloopnum is set properly in `Solver::validate_distribution`
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L10485-L10486

But `validate_distribution` isn't called until later for some reason.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L278-L287

In #10372, code was added so that all airloop fans know what airloop they are on, so perhaps the fix is to grab this from the fan data?
https://github.com/NREL/EnergyPlus/pull/10372/files#diff-737f152cfc96fe6b347b1793b736ad42fc93d2f282532c533c6212d073edcda7R1355

### Details
Some additional details for this issue (if relevant):
 - Platform Win11
 - Version of EnergyPlus v24.2-https://github.com/NREL/EnergyPlus/commit/18f5c3fb9b5068e6123a09ad3ee542b24b09beff
 - Helpdesk ticket number 16731

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 - Fixes #10630 
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

The logic of assign_fan_airloop function is not correct. After further testing, the function is not necessary. The get_airloop_number function covers the same functionality of assign_fan_airloop. Therefore, the assign_fan_airloop function is removed to avoid possible array bounds error. No differences are found in local testing.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [X] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lgu1234** [comment]
@mjwitte The above check-in is for testing only to see any possible differences after a function is removed.

**Comment by Myoldmopar** [comment]
> @mjwitte The above check-in is for testing only to see any possible differences after a function is removed.

I'm a little confused @lgu1234.  Is this PR just for testing then?

**Comment by lgu1234** [comment]
@Myoldmopar Sorry, I may not explain my actions clearly to cause your confusion. This PR is to avoid array bounds error. When @mjwitte posted this issue, he found AirLoopNum is not assigned correctly in the assign_fan_airloop function. Then I check the function and found that the logic in the function is not correct for multiple AirLoops. Fortunately, get_airloop_number function covers the same functionality, so that assign_fan_airloop function is not needed. That is why I removed the function to see if there are any differences in CI testing. The results show no differences, so that the function removal is correct.

Although I assume array bounds errors are removed. Hope @mjwitte can test it.

The error file also shows a fatal error because AFN model is unable to find a solution. Further investigation may be needed.

**Review by mjwitte — APPROVED** [review]
Ok, I tested this with the defect files from both #10630 and #7871 (which is what prompted adding this function the first place). Something must have changed since then (4 yrs ago) that make this function moot. Thanks @lgu1234 I will update this branch and let CI run one more time.

**Comment by mjwitte** [comment]
All green, no diffs. Merging.

**Pull request merged**
