### PR TITLE
Name changes for heating coil energy/rate report variables

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
Heating coils have different naming convention for reporting heating coil energy/rate. This makes it difficult to remember which variable name applies to which coil type. This change addresses #6471 and unifies the naming convention for heating coils across all heating coil types.

Existing naming convention:

<strong>Water heating coils:</strong>
Heating Coil Heating Rate
Heating Coil Heating Energy

<strong>DX heating coils</strong> (includes VRF):
Heating Coil Total Heating Rate
Heating Coil Total Heating Energy

<strong>non-DX/water heating coils</strong> (i.e., elect, multistage, other fuel, gas, desuperheater):
Heating Coil Air Heating Rate
Heating Coil Air Heating Energy

The report variable names were changed to:
Heating Coil Heating Rate
Heating Coil Heating Energy

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
All heating coil reports now show up in the same place, columns 1-3 for all coil types (see description [here](https://github.com/NREL/EnergyPlus/issues/6471)).

heatingcoilreporting3

**Comment by rraustad** [comment]
Before I change 112 example files maybe someone can say yeah or nay on this change. This specifically addresses GUI needs.

**Comment by EnergyArchmage** [comment]
I have reviewed these changes and agree they are a helpful improvement.  I created a new label for output change (so it doesn't get ignored for I/O freeze).

**Comment by Myoldmopar** [comment]
It seemed a bit fuzzy whether this needed to drop before IO freeze or not.  There's no structural changes, but since the output variables names are changing, it probably does make sense.  The output change label is a good idea, we'll just need to be specific about what exactly it means.  Hmm...can you add a description to a label?

**Review by Myoldmopar — APPROVED** [review]

**Comment by EnergyArchmage** [comment]
Regarding the label, I don't find anyplace to add a description to them.

**Comment by Myoldmopar** [comment]
Yeah, I didn't either, kind of a surprise.  If both the IDDChange and Output Change labels are intended to mark a PR based on when it needs to be merged, maybe we can just combine them into an IOFreeze label or something so we don't have to keep track of both.

**Comment by mjwitte** [comment]
@Myoldmopar Happened to notice some related I/O ref mistakes that were wrong before this PR. I can push them up here or send to @rraustad to go in with the example file changes (just to save a CI cycle).

**Comment by Myoldmopar** [comment]
I'm indifferent about where the IO ref changes go as long as they don't trigger another CI build.

**Comment by rraustad** [comment]
While transitioning example files, noticed that there were several files with both flavors of report request (i.e., Heating Coil Air Heating vs Heating Coil Total Heating) (~20ish). Only kept one. I also removed duplicate reports (existing) where appropriate. I am thinking this will cause big diff's, regardless if there was only one flavor in example file or both, because now all heating coils will report to the csv while before only specific heating coil types would report.

**Comment by rraustad** [comment]
Looks like I missed one:

SingleFamilyHouse_TwoSpeed_CutoutTemperature

    +   ** Warning ** The following Report Variables were requested but not generated -- check.rdd file
    +   **   ~~~   ** Either the IDF did not contain these elements, the variable name is misspelled,
    +   **   ~~~   ** or the requested variable is an advanced output which requires Output : Diagnostics, DisplayAdvancedReportVariables;
    +   ************* Key=*, VarName=HEATING COIL TOTAL HEATING ENERGY, Frequency=TimeStep
    +   ************* Key=*, VarName=HEATING COIL AIR HEATING ENERGY, Frequency=TimeStep

I could fix that on a different commit?

**Comment by Myoldmopar** [comment]
I say fix it in another commit and push, but then we'll merge before CI wastes time on it.

**Comment by Myoldmopar** [comment]
(And by fix it in another commit, I mean push a commit to this branch, but we won't wait for a full CI pass just for the variable name fixup.)

**Comment by Myoldmopar** [comment]
(And by all that above, I mean I'll just do it real quick and merge this, thanks @rraustad)

**Comment by rraustad** [comment]
Thanks, I am in the middle of 6372 - Std 62.1 refactor.

**Pull request merged**
