### PR TITLE
AvailabilityManager:OptimumStart output variable name change and add units

### PR DESCRIPTION
**Pull request by mjwitte**
This is a followup to #5352 
Change output variable "Availability Manager Optimum Start Hours Before Occupancy []" to
"Availability Manager Optimum Start Time Before Occupancy [hr]"

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mjwitte This looks fine.  I'm going to fix one small typo in the [doc change](https://github.com/NREL/EnergyPlus/pull/5373/files#diff-b6434fa810dd29e9d6ebc4eed75f299eR20) and merge in develop to get rid of the conflict.  Then this should be able to go in right after.

**Comment by Myoldmopar** [comment]
Alright, merged in develop, only conflicts were in the transition support files.  As long as CI is happy I'll merge this in.

**Comment by Myoldmopar** [comment]
Realized the diffs included a warning in the err file that the report variable wasn't found, which caused even more other diffs.  [Thank you @nrel-bot-3!](http://energyplus.s3-website-us-east-1.amazonaws.com/regressions/2016-01/da43757921bbf1606cd38230b5972b4b8396d692-10159f54ac6eec96934db4d43b7df70c6dbf32a6/OptimalStart_RefBldgLargeOfficeNew2004_Chicago/x86_64-MacOS-10.9-clang/eplusout.err.diff.html).

@mjwitte Once CI comes back happy _this time_ I'll merge.

**Comment by mjwitte** [comment]
@Myoldmopar Thanks for catching the example file variable name change.

**Comment by Myoldmopar** [comment]
Don't thank me...thank @nrel-bot-3.  Nothing gets past him!

**Comment by Myoldmopar** [comment]
@mjwitte I didn't see an issue specifically for this PR.  If there is one, can you close it or point me to it?

**Comment by mjwitte** [comment]
@Myoldmopar This was noticed while addressing a related item in #5087 " I/O Ref does not have a description of output:variable Availability Manager Optimum Start Control".

**Pull request merged**
