### PR TITLE
transition _ExternalInterface files and add example file for IdealLoa…

### PR DESCRIPTION
**Pull request by rraustad**
…dsAirSystem w/ Return Plenum

Addresses #6320.

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
I could not run the _ExternalInterface files to test if they are actually up to date.

**Comment by rraustad** [comment]
This will need another commit.

    [decent_ci:test_result:warn]: Files in idf folder missing from CMakeLists.txt. Files:
    5Zone_IdealLoadsAirSystems_ReturnPlenum.idf

**Comment by rraustad** [comment]
@Myoldmopar which CMakeLisets.txt file is the CI referring to?
@tsnouidui have you had a chance to test these 2 files?

**Comment by mjwitte** [comment]
testfiles\CMakeLists.txt

**Comment by Myoldmopar** [comment]
Yeah, I don't have it setup to run either.  Worst case is that there is still something funny about the transition, but that it is much closer now, so even if @tsnouidui isn't able to test those files, I'd like to get this in for the sake of the added example file.

**Review by Myoldmopar — APPROVED** [review]

**Comment by tsnouidui** [comment]
@Myoldmopar @rraustad Sorry, but my Windows machine got corrupted and needed to be reinstalled. The whole has delayed the testing. It is working now and I was able to compile E+. Next will be to test it with the BCVTB. Hopefully nothing needs to be changed here.

**Comment by tsnouidui** [comment]
@Myoldmopar @rraustad The "actuator" example works. The "variable" example doesn't. This is probably not related to changes on this branch but rather to #6017. 

For completeness, the error message I still get is 

`Simulation model has no variable "ERL SHADING CONTROL STATUS" with key "EMS".`

**Comment by rraustad** [comment]
These look correct at first glance. Not sure of the blank lines if allowed or not. The text "EMS" noted in the warning is just on the right side of the comment line after the global variable. This may or may not highlight a bug. I don't see anything else in this file that stand out regarding text of "EMS". CI should be all green when it finishes.

_ExternalInterface-variable.idf

    EnergyManagementSystem:OutputVariable,
     Erl Shading Control Status,  !- Name
     Shade_Signal_01,         !- EMS Variable Name
     Averaged,                !- Type of Data in Variable
     ZoneTimeStep,            !- Update Frequency
     ,                        !- EMS Program or Subroutine Name
     ;                        !- Units

    EnergyManagementSystem:GlobalVariable,
     Shade_Signal_01;         !- Erl Variable 1 Name

**Comment by mjwitte** [comment]
@tsnouidui I commented out the external interface objects in _ExternalInterface-variable.idf and ran it (with a minor change to one program) just to confirm that the key for that variable is still "EMS".  In the csv header `EMS:Erl Shading Control Status [](Hourly)`.  Is the error you are seeing possibly related to the fix proposed in #6298 ?

**Comment by tsnouidui** [comment]
@mjwitte Yes seems to be related to that fix.

**Review by mjwitte — APPROVED** [review]
@tsnouidui Thanks.
@rraustad This can drop in once CI finished up its work.

**Comment by Myoldmopar** [comment]
Another one for which I'm not waiting on CI.  Merging now.

**Pull request merged**
