### PR TITLE
fluid coolers delay high speed UA

### LINKED ISSUE #4560: EvaporativeFluidCooler:TwoSpeed getinput is overly strict and halts with false error
Helpdesk ticket 9966

Issue A:  User file with EvaporativeFluidCooler:TwoSpeed fails with this error:

   *\* Severe  *\* EvaporativeFluidCooler:TwoSpeed "CSHQA MAIN TOWER". Evaporative fluid cooler UA at low fan speed must be less than the evaporative fluid cooler UA at high fan speed.
   *\*  Fatal  *\* InitEvapFluidCooler: Program terminated due to previous condition(s).

but the user is specifying design capacities, so this should not occur.  

Issue B:  Various attempts to resolve this error resulted in other somewhat strict fatal errors, such as "   *\* Severe  *\* EvaporativeFluidCooler:TwoSpeed = "CSHQA MAIN TOWER", invalid data for "Low Speed User Specified Design Capacity", entered value <= 0.0, but must be > 0 for Performance Input Method = "USERSPECIFIEDDESIGNCAPACITY".

Overall the input options for capacity are confusing and excess inputs (e.g. value or "autosize") in a field that is not being used by the current input method should result in warnings not fatal errors.  Getinput for this object needs a review and needs test files for each method using both hard values and autosize/autocalculate to make sure the logic all flows correctly.

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Add logic bool to delay when UA is calculated until sizing is further along.  Previously the UA calculation could execute with a design flow rate still at -99999.0 and cause a fatal error.  

probably fixes https://github.com/NREL/EnergyPlus/issues/4560 

TRANE contribution

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@EnergyArchmage @lgentile it has been 28 days since this pull request was last updated.

**Comment by jmarrec** [comment]
@EnergyArchmage Checked out locally, merged develop in and pushed again.

I added test files to `EnergyPlusDevSupport/DefectFiles/4000s/4560`, tested with your branch, still fatals out.

Given a a fluid cooler like so:
```
EvaporativeFluidCooler:TwoSpeed,
  Evaporative Fluid Cooler Two Speed 1,   !- Name
  Node 88,                                !- Water Inlet Node Name
  Node 89,                                !- Water Outlet Node Name
  9.911,                                  !- High Fan Speed Air Flow Rate {m3/s}
  Autosize,                               !- High Fan Speed Fan Power {W}
  4.911,                                  !- Low Fan Speed Air Flow Rate {m3/s}
  0.5,                                    !- Low Fan Speed Air Flow Rate Sizing Factor
  Autocalculate,                          !- Low Fan Speed Fan Power {W}
  0.16,                                   !- Low Fan Speed Fan Power Sizing Factor
  0.002208,                               !- Design Spray Water Flow Rate {m3/s}
  UserSpecifiedDesignCapacity,            !- Performance Input Method
  ,                                       !- Outdoor Air Inlet Node Name
  1.25,                                   !- Heat Rejection Capacity and Nominal Capacity Sizing Ratio
  ,                                       !- High Speed Standard Design Capacity {W}
  ,                                       !- Low Speed Standard Design Capacity {W}
  0.5,                                    !- Low Speed Standard Capacity Sizing Factor
  ,                                       !- High Fan Speed U-factor Times Area Value {W/K}
  ,                                       !- Low Fan Speed U-factor Times Area Value {W/K}
  0.6,                                    !- Low Fan Speed U-Factor Times Area Sizing Factor
  0.001703,                               !- Design Water Flow Rate {m3/s}
  87921,                                  !- High Speed User Specified Design Capacity {W}
  47921,                                  !- Low Speed User Specified Design Capacity {W}
  0.5,                                    !- Low Speed User Specified Design Capacity Sizing Factor
  46.11,                                  !- Design Entering Water Temperature {C}
  35,                                     !- Design Entering Air Temperature {C}
  25.6,                                   !- Design Entering Air Wet-bulb Temperature {C}
  1,                                      !- High Speed Sizing Factor
  SaturatedExit,                          !- Evaporation Loss Mode
  ,                                       !- Evaporation Loss Factor {percent/K}
  0.008,                                  !- Drift Loss Percent {percent}
  ConcentrationRatio,                     !- Blowdown Calculation Mode
  3;                                      !- Blowdown Concentration Ratio
```

```
   ** Severe  ** EvaporativeFluidCooler:TwoSpeed "EVAPORATIVE FLUID COOLER TWO SPEED 1". Evaporative fluid cooler UA at low fan speed must be less than the evaporative fluid cooler UA at high fan speed.
   **  Fatal  ** InitEvapFluidCooler: Program terminated due to previous condition(s).

```

**Comment by Myoldmopar** [comment]
@EnergyArchmage is this the one that you said you wanted to try to re-run to figure out the problem?  If so, do you anticipate resolving this early this week as we try to freeze things up?  Thanks!

**Comment by EnergyArchmage** [comment]
yes this is the one I was thinking of.  I just pushed up a fix for the old issue. defect file for 4560, test901.idf runs now.

**Comment by Myoldmopar** [comment]
@jmarrec could you retest as you did above but with the latest commit here on this branch.  I believe the Linux results there to be an anomaly, and I'll re-run that if it turns out this is now fixing the issue.

**Comment by jmarrec** [comment]
`EnergyPlusDevSupport/DefectFiles/4000s/4560/test910.idf` runs fine with this branch. 

I also pulled the old 4560 files (v820) and transitioned them again (the 9.0.0 ones were probably transitioned with the release that had a broken transition utility). Also transitioned them to 9.1.0 and tried to run them: they fail, but for a different issue. eg for `10_27_ClgTwr-ddays-IssueA-AddPlantSizing-v910.idf`

```
   ** Warning ** GetAirPathData: AirLoopHVAC="CSHAQ DOAS SYSTEM" has no Controllers.
   ************* Beginning Plant Sizing Calculations
   ** Warning ** Calculated Relative Humidity out of range (PsyRhFnTdbWPb) 
   **   ~~~   **  Routine=Unknown, Environment=BOISE AIR TERMINAL  UO ANN HUM_N 99.6% CONDNS DP=>MCDB, at Simulation time=12/21 24:00 - 24:10
   **   ~~~   **  Dry-Bulb= 0.00 Humidity Ratio= 8.000E-003 Calculated Relative Humidity [%]= 205.54
   **   ~~~   ** Relative Humidity being reset to 100.0%
   ** Severe  ** For Controller:OutdoorAir: CSHAQ DOAS SYSTEM OA CONTROLLER
   **   ~~~   **   maximum outdoor air flow rate (0.6404) < minimum outdoor air flow rate (0.8816)
   **   ~~~   **   To set the minimum outside air flow rate use the "Design (minimum) outdoor air flow rate" field in the Sizing:System object
   ** Warning ** InitOAController: Minimum Outdoor Air Flow Rate for Controller:OutdoorAir=CSHAQ DOAS SYSTEM OA CONTROLLER is greater than Design Supply Air Flow Rate for AirLoopHVAC=CSHAQ DOAS SYSTEM.
   **   ~~~   ** ...Minimum Outdoor Air Flow Rate=0.881598 will be reset to loop Design Supply Air Flow Rate=0.640416
   **  Fatal  ** Error in Controller:OutdoorAir; program terminated
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=For Controller:OutdoorAir: CSHAQ DOAS SYSTEM OA CONTROLLER

```

**Comment by Myoldmopar** [comment]
Thanks for retesting @jmarrec!  OK, I'm rerunning that Linux result and if it comes back clean I'll merge this in.  If you feel that the unrelated severe warrants a defect, feel free to file that separately.

**Comment by jmarrec** [comment]
I have a strong feeling that the severe is a user input error, and it appears to be properly reported in the eplusout.err, so I don't think it's worth investigating.

**Comment by Myoldmopar** [comment]
Looks perfect.  Merging.

**Pull request merged**
