### PR TITLE
Improve input error handling in boiler and pump to allow file to run while outputting error messages

### LINKED ISSUE #6164: User file hot water heating loop not running - bad boiler and pump inputs - need error messages
Issue overview
--------------
User file with hot water baseboard and boiler was not producing any heating.

An input problem was found in the boiler object.  The Design Water Flow Rate field was blank.  This field has no default, so it resulted in zero.  This should at least produce a warning if the flow rate is zero.  And this field should either be required or default to autosize.

With that fixed, the baseboards still did not operate. 

The other problem was the pump input.
```
  Pump:VariableSpeed,
    supply inlet pump,       !- Name
    Node supply inlet in,    !- Inlet Node Name
    Node supply inlet out,   !- Outlet Node Name
    0.00101,                 !- Design Maximum Flow Rate {m3/s}
    1793520,                 !- Design Pump Head {Pa}
    2237,                    !- Design Power Consumption {W}
    0.9,                     !- Motor Efficiency
    ,                        !- Fraction of Motor Inefficiencies to Fluid Stream
    ,                        !- Coefficient 1 of the Part Load Performance Curve
    1,                       !- Coefficient 2 of the Part Load Performance Curve
    ,                        !- Coefficient 3 of the Part Load Performance Curve
    ,                        !- Coefficient 4 of the Part Load Performance Curve
    0.0010116,               !- Design Minimum Flow Rate {m3/s}
    Continuous,              !- Pump Control Type
```
The min flow is greater than the max flow.  No error message and the loop doesn't run.  Change the min flow to zero and the loop runs.

Four defect files, original, fix the boiler flow, fix the pump min flow, and fix both.  The only one that produces any heating is with both of these problems fixed.

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus 8.7.0
 - Helpdesk ticket number 12097

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles (use Toronto weather)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #6164, changelog:
* IDD change for Boiler:HotWater, default field ` Design Water Flow Rate` to `autosize` (follows other objects such as Chiller:Electric:EIR, and this field needs a default or should be marked as required anyways)
* When Pump Min Flow is greater than Pump Max Flow, output a message and reset Min to 99% of Max (turns out if you set Min = Max, it won't run).
    * If you have a more sensible default, I'm all ears.
* Unit tests for both

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
There is some logic messed up here.  This is showing errors in 187 files where it looks like any pump that is autosized has the error:

```
  ** Warning ** GetPumpInput: Pump:VariableSpeed="CW CIRC PUMP", Invalid 'Design Minimum Flow Rate'
  **   ~~~   ** Entered Value=[0.00000] is below the Design Maximum Flow Rate=[-99999.00000].
  **   ~~~   ** Reseting value of 'Design Minimum Flow Rate' to the value of 'Design Maximum Flow Rate'.
```

CI was nicely [clear](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-92cceeae01939c4f2edb4d59f0905208079d1735-Win64-Windows-7-VisualStudio-14.html) about it.  I think you probably need to delay the warning until after sizing has run.  I'll watch for when a fix is made before reviewing further, @jmarrec .

**Comment by Myoldmopar** [comment]
Much better now!  I'm building it locally to just make sure the unit tests pass when merged with develop but I anticipate this merging here in just a few minutes.

**Comment by Myoldmopar** [comment]
Yeah, everything still looks good, and the error message issue is gone.  Merging.

**Pull request merged**
