### PR TITLE
Improved flushing of output per line

### LINKED ISSUE #5288: EnergyPlus doesn't flush output each line
EnergyPlus doesn't consistently flush stdout on each line.  The effect ranges from an annoyance when running manually, to more of a problem when a GUI relies on monitoring the output to provide feedback to users.  This can be addressed by appending each display call with `std::flush`.

### PR DESCRIPTION
**Pull request by Myoldmopar**
Fixes #5288

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This reverts out the accidental commit from before.  I can't quite imagine a unit test here...
- time the output flying by and snapshot it at a certain time to make sure only a partial amount of the output has come out?  :-1: 
- Kill EnergyPlus after a couple seconds and see if something came out?  :-1: 

I'm not trying to get out of a unit test here, so if someone has an idea I'll do it.  Otherwise this is going in without one.

@mbadams5 I assigned you since this was from your idea, and it worked perfectly.  Let me know if you have thoughts on a unit test.  Otherwise merge at will.

**Comment by mbadams5** [comment]
@Myoldmopar My only comment/thought is why not using `std::endl` instead of `<< '\n' << std::flush;`? Just minor nitpick.

**Comment by Myoldmopar** [comment]
You like that better @mbadams5?  It still does properly flush now during the simulation, so as far as I am concerned, this is done.

**Comment by nealkruis** [comment]
@mbadams5 @Myoldmopar Thanks for making this happen! It's been a nuisance for a while.

**Comment by Myoldmopar** [comment]
Yeah, for sure @nealkruis.

**Pull request merged**
