### PR TITLE
Fix CBVAV terminal unit error introduced with multi-HVAC controls

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Addresses #6544. Fixes problem introduced in #5952.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
Thanks for the reactivity @mjwitte.

I suggest removing this build warning

```
/home/julien/Software/Others/EnergyPlus/src/EnergyPlus/HVACUnitaryBypassVAV.cc: In function ‘void EnergyPlus::HVACUnitaryBypassVAV::GetCBVAV()’:
/home/julien/Software/Others/EnergyPlus/src/EnergyPlus/HVACUnitaryBypassVAV.cc:534:14: warning: unused variable ‘EquipNum’ [-Wunused-variable]
   static int EquipNum( 0 ); // local do loop index for equipment listed for a zone
```

**Comment by Myoldmopar** [comment]
This is looking clean.  I think I'm going to merge this, and the 8.9 prep branch.  The JSON branch looks really close, but since there may still be one round of changes, @mbadams5 can pull the latest develop in over there before pushing again.  Then we'll be done when the JSON branch is finalized.

**Comment by Myoldmopar** [comment]
Well, there's the Windows bot working, I'll let TikTok have a pass over it before merging, but I assume this will drop shortly after that.

**Comment by Myoldmopar** [comment]
Diff from my develop merge I'm sure; merging now.

**Pull request merged**
