### PR TITLE
Reference to trackSorageOpMeterName_ correction

### PR DESCRIPTION
**Pull request by ecoeficiente**
Pull request overview
---------------------
In component ElectricLoadCenter:Distribution, using Storage Operation Scheme TrackMeterDemandStoreExcessOnSite, the required Storage Control Track Meter Name is not assigned in code which leads to a fatal error during simulation.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@ecoeficiente @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@ecoeficiente @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@ecoeficiente @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@ecoeficiente, thanks for this contribution.  I was wondering if you had a chance to submit the contribution agreement here: https://energyplus.net/contributing

Please let me know if you have any questions about it.  You can email me at edwin dot lee at nrel dot gov.  Thanks!

**Comment by nrel-bot-2** [comment]
@ecoeficiente @lgentile it has been 30 days since this pull request was last updated.

**Comment by ecoeficiente** [comment]
> @ecoeficiente, thanks for this contribution. I was wondering if you had a chance to submit the contribution agreement here: https://energyplus.net/contributing
> 
> Please let me know if you have any questions about it. You can email me at edwin dot lee at nrel dot gov. Thanks!

Sorry, I had missed this. I have just sent the contribution agreement.

**Comment by Myoldmopar** [comment]
@ecoeficiente thank you for sending your contribution agreement.  This is a very small fix, and I appreciate you contributing it.  I see there was a build warning when this last ran.  I'd like to get some freshened up CI results before digging into any potential ramifications of the change.  I'll merge our latest develop branch into your branch here, and we'll see what CI says.  Then I'll get to testing the functional change.

**Comment by Myoldmopar** [comment]
@ecoeficiente do you happen to have a defect file available where I can verify the issue and your fix?

**Comment by ecoeficiente** [comment]
[TrackStorageBug.zip](https://github.com/NREL/EnergyPlus/files/3255957/TrackStorageBug.zip)

**Comment by nrel-bot-2** [comment]
@ecoeficiente @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I verified that this test file does fail on the develop branch with the expected error.  With this branch it gets farther into the simulation and fails for an unrelated reason, so I'm going to merge this fix in.

**Pull request merged**
