### PR TITLE
Clean out non-ascii characters in source code and test files

### LINKED ISSUE #4215: Text files: Special character encoding causes unintentional diffs
There are a lot of special characters (e.g., the copyright at the bottom of the page, and almost every double quote in the IDD) in source files that cannot be read by many non-Windows editors (including eclipse). For me, this means that every time I save a file, these characters are all converted to meaningless symbols and cause unintentional diffs in version control.

Has the team encountered this in the past? If not, I suggest we standardize on something like UTF-8 for all file encoding.

### PR DESCRIPTION
**Pull request by Myoldmopar**
Fixes #4215

### CODE REVIEW

**Comment by nealkruis** [comment]
@Myoldmopar will this address the IDD, too?

**Comment by mjwitte** [comment]
@nealkruis There shouldn't be any in the IDD - did you find some?

**Comment by Myoldmopar** [comment]
Yeah, the IDD didn't show any.  If you are seeing some let me know.

**Comment by nealkruis** [comment]
All of the apostrophes are non UTF-8 characters. Do a search for this thing -> � in [this file](https://raw.githubusercontent.com/NREL/EnergyPlus/develop/idd/Energy%2B.idd.in).

**Comment by Myoldmopar** [comment]
Thanks @nealkruis; I'll expand my search a bit and update this.

**Comment by Myoldmopar** [comment]
Lumping in a one-line error message text-only change into this PR with 2d7f696.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte, that's a great idea.  But it should be `cNumericFieldNames( 5 )`, right?  (Updated in 04c7b93)

**Comment by mjwitte** [comment]
Oh - right.

**Pull request merged**
