### PR TITLE
Simple python script to parse C++ code for EMS variable calls

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

This is a simple python script that aims to get some info about which EMS internal Variables and EMS Actuators are available, and where they are set, similar to the existing `parse_output_variables.py` script if you will.

It doesn't affect E+ in any shape or form. The only thing it does is to print some info to the screen, and create a CSV file. I commited said CSV file so you could get a sense of what it does, but I suggest just keeping the python file.

Please refer to the Python file's module docstring for more info: [parse_ems_actuators.py#L1:L32](https://github.com/jmarrec/EnergyPlus/blob/Find_EMS_Calls/doc/tools/parse_ems_actuators.py#L1:L32)

----

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by jmarrec** [comment]
Rebase onto develop + modification to handle multi-line function calls.

**Comment by Myoldmopar** [comment]
I haven't tested, but from a quick glance at the code (matching up parentheses on a single "working_line") I feel like this will likely break with the new style rules in place (just like the output variable script did).  @jmarrec do you have interest in updating this for multiline calls?  I moved to using multiline regex to gather up function call matches and then I replace the newline with nothing so that I end up with a list of nicely parse-able function calls.  Let me know if you want to make a similar update here.  If not I'll close this PR (or at least move it to a later release).  Also, if you are making changes, can we get rid of the dependency on pandas?  I'm not against dependencies, but it doesn't seem like it's worth having that dependency for this.  Please clarify if that's important to you or not.

**Comment by jmarrec** [comment]
I do handle multi line calls. See around line 135, I count closing and opening parenthesis until the initial one is closed down, even if on several lines. I added that when I last rebased onto develop, and commented on that fact above in this thread.

Pandas is just nice to go from dict to csv, it does that really well. Plus, you could use the function to just build the dataframe then do some analysis / sorting in python.

This is clearly an imperfect script (namely the problem is figuring out c++ semantics, what’s behind cModuleobjects etc), and it’s going to be used by a handful of people at best, so I wouldn’t worry too much.

I just wrote it for my own purpose and thought it could be of use to someone else down the line, but that’s pretty much it. The goal was never to create a perfect list of EMS variables for use in documentation or something like that. I wouldn’t even include the CSV file that is generated by the script if it was merged in develop, just the python script itself.

Edit: I just reread the script’s docstring and the pull request overview I wrote months ago, and most of what I just said is covered in there already.

**Comment by jmarrec** [comment]
That being said, I do understand that one might be thinking that someone in a distant future will say “hey this script doesn’t work anymore” and that you probably don’t want to maintain it.

I guess what I’m saying is that I think it’d make sense to add it to develop for future reference but without any warranties (at worse it doesn’t work but it’s a nice starting point to make it work again), but I wouldn’t be disappointed if it doesn’t make it in. I have my own copy, and I’ll be able to find it either way.

I’ll let you be the judge or whether that’s more trouble than it’s worth.

**Comment by jasondegraw** [comment]
As far as I'm concerned, the pandas dependency is a deal breaker. If that is to be a dependency, then there's a time and place for that, but this isn't it.

**Comment by jmarrec** [comment]
Would take 6 lines and about 5 minutes to convert the pandas call to standard library. The summary function can be eliminated altogether.
Is this still something you want though...?

**Comment by jmarrec** [comment]
@Myoldmopar I removed the pandas dependencies, and keep all functionality intact (I chose to rewrite the summary function instead of eliminating it).

**Comment by Myoldmopar** [comment]
@jmarrec OK, now that we are done with our IO freeze, I'm on to the non-IO-affecting PRs.  I pulled this locally and ran it.  It ran fine.  I do see your issues with so many of the arguments being stored in variables and how that is very difficult to trace.  I also see your point that this is just a potentially useful script for someone out there, and that it still adds value.  I am ready to merge the script in, but I would like to get the output csv file out of the branch now.  I don't want to accidentally leave a stale output file in the repo.  If you can remove that file from this branch I'll merge it right away.

**Comment by jmarrec** [comment]
I can remove it tomorrow when I get access to a computer or you can do it now (any member of this repo should have write access on this PR (or any other I may open))
I’ll check tomorrow anyways.

**Comment by Myoldmopar** [comment]
Thanks @jmarrec.  I thought Github would have a little tag on the action section here at the bottom of the PR saying I had write access to the branch.  When I didn't see an indicator, I assumed it wasn't enabled.  Anyway, I pushed a commit to remove that file, and I'll merge this now.  Thanks!

**Pull request merged**
