### PR TITLE
Bump github actions (to avoid deprecation warnings)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - The official ones are fine
 - The jidicul clang format one should be ok (I left the clang-format binary at clang-format-10...)
 - The cppcheck bumps the cppcheck binary, so it's likely it'll start reporting new failures, just testing the waters right now

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
the cppcheck 2.10 is muuuuuuuch slower than 1.82, 3min before and now still not half done at 25 minutes. This is weird, because I did a similar transition on OpenStudioApplication a few months ago and did not see any increase in runtime. Maybe it's a fluke for this specific run, not sure?

And it does report some new warnings, some of which are justified.

One example of such a warning: https://github.com/NREL/EnergyPlus/blob/1504f8b59baf734bfa30a9209dc3a1c1c70bb455/src/EnergyPlus/Construction.cc#L1184

```
[Construction.cc:1184]:(warning),[invalidFunctionArg],Invalid std::log() argument nr 1. The value is 0 but the valid values are '4.94066e-324:'.
```

`AMatRowNormMax` **could** be zero indeed.

**Comment by Myoldmopar** [comment]
Wow, 53 minutes for cppcheck!  That's intense, and I'm not sure what to make of it.  I mean I guess we could deal with it, but that seems like a lot of runtime.

**Comment by Myoldmopar** [comment]
This is great, but among all the good messages, I found false positives in the cppcheck output.  I'm not sure the best way to proceed, as I don't want it to just fail on all commits.  Rollback to an older cppcheck again? What do you think is the best way forward @jmarrec ?

**Comment by jmarrec** [comment]
Options:

* fallback to not passing --enable (which means --enable=error)
* Keep reporting warnings, style, performance, and all, but just don't fail the workflow (which is what I have currently)
    * Could make an effort to remove all valid warnings and suppress the others)

**Comment by Myoldmopar** [comment]
CI is happy, just one left to run.  I'll get this merged in if it's also happy.

**Comment by Myoldmopar** [comment]
This one can go in now.  Thanks @jmarrec, this is a really great step for our CI images.  It will be great to continue the work to clean up the cppcheck warnings that emerged.  Merging.

**Pull request merged**
