### PR TITLE
Correct OA controller mixed air node set point calculation to allow values <0

### PR DESCRIPTION
**Pull request by rraustad**
## Pull request overview

Addresses #5412. Fixed the OA controller to honor mixed air setpoints < 0C.  Previously setpoints < 0C were ignored.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things
- IDD changes n/a

### CODE REVIEW

**Comment by rraustad** [comment]
I can't think of a reason why the mixed air SP should not be used. The OA system can either meet that condition or not.

**Comment by rraustad** [comment]
@Myoldmopar the only failure is a unit test. Does this indicate an issue with disk space?

Note: Google Test filter = EnergyPlusFixture.MixedAir_TestHXinOASystem
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from EnergyPlusFixture
[ RUN ] EnergyPlusFixture.MixedAir_TestHXinOASystem
unknown file: error: C++ exception with description "InitializeMeters: Could not open file eplusout.mtd for output (write)." thrown in the test body.
[ FAILED ] EnergyPlusFixture.MixedAir_TestHXinOASystem (546 ms)
[----------] 1 test from EnergyPlusFixture (546 ms total)

**Comment by Myoldmopar** [comment]
Hmmm.  Well it's on the box on my desk, so I'll check it out when I get into the office.  In the meantime I'm going to delete those results and have it re-run, possibly on a different machine.

**Comment by mjwitte** [comment]
@Myoldmopar These unit test failures "Could not open file x for output (write)" seem to happen randomly but always on one of the windows machines (don't remember if it's always Win32).  And it's usually the mtr file, this time it's mtd. And it's not always the same unit test. Odd. Maybe a timing issue where the OS hasn't gotten things cleared out completely before the next test runs?  Or a space issue?

**Comment by Myoldmopar** [comment]
That VM has 44 GiB free on it, so not a space issue.  It must be a stray timing issue.

**Comment by nrel-bot-3** [comment]
@mjwitte @rraustad @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @rraustad @lgentile it has been 14 days since this pull request was last updated.

**Pull request merged**
