### PR TITLE
IDF Editor added dialog explaining workaround for #9010 out of memory error

### LINKED ISSUE #9010: Out of memory when IDFEditor reads in a large IDF file
Issue overview
--------------
There was a "Run-time error '7': out of meomory" warning when using IDFEditor to open a large idf file:  

image

The case file can finish running with EP-Launch tough. This warning is a rare occurrence and the file size may not be the single factor---there seemed to be larger files that can be opened ok without such a warning.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 IOFreeze
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9010))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #9010 
 - Adds a dialog box in IDF Editor that displays how to work around this out of memory error. The dialog box only shows up when the memory error occurs.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@jcyuan2020 could you test this again and see if the dialog box showing the workaround is displayed?

**Comment by jcyuan2020** [comment]
@JasonGlazer Sure. Also, will this involve compiling the idfeditor from source code? I may need some help with that.

**Comment by jcyuan2020** [comment]
The first test is on v9.6. The newly added message showed up as expected:
image

After clicking "OK", then the following message will come up:
image

Click "OK" again, the IDFEditor window will disappear (presumably being closed).

**Comment by JasonGlazer** [comment]
Thanks, that is how it should be working now.

**Comment by jcyuan2020** [comment]
Also, tested on v22.2 IOFreeze using an upgraded idf file, the results are the same.

**Comment by mjwitte** [comment]
@JasonGlazer I'm curious why the memory error doesn't occur when the file is opened directly from IDFEditor? With this branch, if the file is opened directly, the dialog comes up but there is no memory error. Would a better dialog be to simply suggest opening the file directly from IDF Editor?

**Comment by mjwitte** [comment]
> @JasonGlazer I'm curious why the memory error doesn't occur when the file is opened directly from IDFEditor? With this branch, if the file is opened directly, the dialog comes up but there is no memory error. Would a better dialog be to simply suggest opening the file directly from IDF Editor?

Per @JasonGlazer (in an actual face-to-face conversation) opening the file directly from IDFEditor is not a reliable solution.

@Myoldmopar If you're ok with this change, it can merge.

**Comment by Myoldmopar** [comment]
No problem here, merging.

**Pull request merged**
