### PR TITLE
Fix VRF fluid control model cycling ratio and runtime fraction at low cooling load

### LINKED ISSUE #10105: VRF cooling issue: same cooling power with different min-speed curve at low cooling load
Issue overview
--------------

**Cycling issue at the lowest fan speed**

The two idf files reproducing this problem is derived from the "US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf". They differ at the performance curves at the lowest compressor speed, the speed_1920.idf is created by removing the lowest speed as follows:

image

Row 2-7 shows the simulation results when the minimum compressor minimum speed is 900 with speed curve 1. Row 9-14 shows the simulation results when the compressor minimum speed is 1920 and using performance curve 2. Note that the capacity curves of speed levels are in the order of ascending capacity. We can see that even if the two settings have different compressor curves for the minimum speed, they output the same cooling rates, yet very different cooling electricity rate and COP. The heat pump runtime fraction and cycling ratio are 1 in both cases.  For the same cooling demand (both the zone and outdoor temperature are the same), if it runs fulltime in speed_900.idf, it should only run part of the time in speed_1920.idf, as its min capacity is larger than the former. They can't both run fulltime. 

image
 
### Defect files

[simulation_with_different_speeed_update.zip](https://github.com/NREL/EnergyPlus/files/14543997/simulation_with_different_speeed_update.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.3)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10105

It uses the same min-speed capacity in the cycling calculation as is used in the compressor speed calculation

image

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I assume this is nowhere near ready, since it only has a new IDF/EPW test.  I'm not going to do any reviewing here.  Please let me know if you need anything here @yujiex

**Comment by yujiex** [comment]
> I assume this is nowhere near ready, since it only has a new IDF/EPW test. I'm not going to do any reviewing here. Please let me know if you need anything here @yujiex

@Myoldmopar, it's not going to be ready for this release. We're still in the diagnosing phase. We probably need some discussion in some technicality meeting. Should I convert it to draft?

**Comment by nrel-bot-3** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Pull request closed without merging**
