### PR TITLE
Update ChangeLog script for a better header

### PR DESCRIPTION
**Pull request by Myoldmopar**
Tiny change to the ChangeLog script so the header is more descriptive.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
## New Markdown Header

# Changelog for EnergyPlus 8.5.0-424cbc1a47

Consists of pull requests merged in since the last release - starting with SHA [832e4bb](https://github.com/NREL/EnergyPlus/commit/832e4bb)

## New Features
- [#5256](https://github.com/NREL/EnergyPlus/pull/5256) : Only show final simulation year in tabular reports multiple year run periods
- [#5267](https://github.com/NREL/EnergyPlus/pull/5267) : Improve reheat coil sizing when there is no central heating coil

**Comment by Myoldmopar** [comment]
## New HTML Header

See: https://gist.github.com/Myoldmopar/3167462e4730a0d8db33

**Comment by Myoldmopar** [comment]
@mjwitte If those headers work for you, merge at will.  Waiting on green CI is fine, but not necessary.

**Comment by mjwitte** [comment]
@Myoldmopar New header looks good.  I was surprised, though that this list goes all the way back to v8.4.0 original release, so there's some overlap with the v8.4.0 Update 1 changes.  Just want to be sure that's your intent.

**Comment by Myoldmopar** [comment]
That was my intent,  but I'm not fixed on it.  I'm open to suggestion.

**Pull request merged**
