### PR TITLE
Correct ERV sizing reports to eio file

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
ZoneHVAC:EnergyRecoveryVentilator sizing reports were missing or duplicating information to the eio file. This corrects #6820 and #6987.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
image
YES!

**Comment by Myoldmopar** [comment]
@rraustad I merged develop and cleaned up the build warning.  It should come back all green now.  I'll review and see if we can drop this in today before I tag 9.0.

**Comment by rraustad** [comment]
Perfect, thank you. I thought you might want this in the release so I worked to get it quickly.

**Comment by rraustad** [comment]
@Myoldmopar @RKStrand no unhandled exceptions here.

**Review by Myoldmopar — APPROVED** [review]

**Pull request merged**
