### PR TITLE
Refactor rich cooling tower1 spd

### PR DESCRIPTION
**Pull request by rraustad**
let's see where this stands...

### CODE REVIEW

**Comment by rraustad** [comment]
WTF(ork)? How did this get here? Still need to see diff's so let her rip.

**Comment by rraustad** [comment]
Hard to find the diff's when all I know is count. Merkel cooling tower was one of them, but I don't see any diff's?
coolingtower

**Comment by mjwitte** [comment]
@rraustad Yeah, we don't get the regression results for things that are just warnings instead of fails and the rules for warning vs fail have changed.  @lefticus Would it be possible to save the regression results for warnings as well?  It is useful to review those, especially if one expects zero diffs and you get small diffs.

**Comment by rraustad** [comment]
So why didn't we pass RunFlag into the new simulate routine? Did someone already refactor the chillers and find an issue with RunFlag being false while CurLoad > 0 or vice versa?

} else if ( GeneralEquipType == GenEquipTypes_Chiller ) {
    SimChiller( LoopNum, LoopSideNum, EquipTypeNum, sim_component.Name, EquipFlowCtrl, EquipNum, **RunFlag**, FirstHVACIteration, InitLoopEquip, **CurLoad**, MaxLoad, MinLoad, OptLoad, GetCompSizFac, SizingFac, TempCondInDesign, TempEvapOutDesign );

**Comment by rraustad** [comment]
The ReportTowers routine uses the RunFlag to either set variables to zero, or ELSE set them to non-zero values. We don't have that flag anymore. I tried using CurLoad == 0, but that doesn't work, the towers are always off (at least in the diff's files I'm looking at). Or maybe it's working now and the answer was wrong before? UPDATE: No, all the towers were off, not just those that were simulated last.

**Comment by rraustad** [comment]
Much better. @Myoldmopar please run this with your script.

**Comment by rraustad** [comment]
That CompDemand test is exactly why I thought CurLoad == 0 would be equivalent to !RunFlag but that didn't work for cooling  towers. So there must be a disconnect between CurLoad and RunFlag for towers? When I did this the towers were always off.

```
if (CurLoad == 0)
    set variables for off condition
} else {
    set variables for on condition
}
```

**Comment by rraustad** [comment]
@Myoldmopar I ran using your Test Suite setup. I have 0 big Mathdiffs and 0 small Mathdiffs.  There are big table diffs but those are due to rows changing places. I couldn't run the water-cooled VRF, still trying.

**Comment by rraustad** [comment]
@Myoldmopar Water-cooled VRF ran. I had to trick the GUI by using the same name as the existing VRF file (so much for creating new files with unique names?). 

No small or big diff's. Big table diffs since rows changed places.
VRF = complete
Cooling Towers = complete

**Comment by Myoldmopar** [comment]
Yeah, that's a deficiency with the GUI where it relies on a pre-canned list
of files.  I have a task for myself to clean that up sometime...​

**Comment by mjwitte** [comment]
Isn't there a button to rebuild the list?

**Comment by rraustad** [comment]
There's a button to read the files from a folder but all it does is uncheck the files in the left pane and recheck the one's that match those in the folder. If a file name doesn't match the list, a warning is issued and that file does not run. It does run the file from the folder if the name matches so just change the name to match an existing example file.

**Comment by mjwitte** [comment]
You can edit the master file list in ..\RegressionSuite\Scripts\FullFileSetDetails.csv

**Comment by Myoldmopar** [comment]
@rraustad This PR is trying to merge this directly into NREL/EnergyPlus.  I'm going to close this one and open a new PR to merge it into develop over in our sandbox repo.

**Comment by Myoldmopar** [comment]
(Opened over there as: https://github.com/energy-plus/EnergyPlus/pull/22)

**Pull request closed without merging**
