### PR TITLE
Remove extra space at end of readvars header

### PR DESCRIPTION
**Pull request by mitchute**
ReadVarsESO places an extra space character at the end of the header line in the csv file. I only noticed the issue when I was using Python/Pandas to reference columns by name, and found that one had an extra space. It's super minor, so feel free to ignore it, especially if it has a purpose that I'm not seeing.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This would be a great addition, but I think we'll need to make it so this
with a command line argument. Something like --no-extra-header-space or
something. Not sure if anyone out there relies on that space when parsing
the output.

**Comment by Myoldmopar** [comment]
With the `fixheader` command line argument available, using an eso file where I cut the output variables down to just one, here is the output:

```csv
$ ./ReadVarsESO 
 ReadVarsESO program starting.
 ReadVars Run Time=00hr 00min  0.01sec
 ReadVarsESO program completed successfully.

$ head -n 2 eplusout.csv 
Date/Time,Environment:Site Outdoor Air Drybulb Temperature [C](Hourly) 
 12/21  01:00:00,-15.5 

$ ./ReadVarsESO '' fixheader
 ReadVarsESO program starting.
 ReadVars Run Time=00hr 00min  0.01sec
 ReadVarsESO program completed successfully.

$ head -n 2 eplusout.csv 
Date/Time,Environment:Site Outdoor Air Drybulb Temperature [C](Hourly)
 12/21  01:00:00,-15.5 
```

Note the header line does not have a trailing space.  I really wish I could just cut this trailing space off without a command line argument, but I'm afraid some interface might be purposely cutting off the last character of the header before processing variable names, and this change would break their workflow.  So I won't.  But in ReadVars2, which will be in Python, ... :upside_down_face: 

This needs documentation to be updated before it's ready.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Retested this, I think it is good to go.  It just adds a new, totally optional, command line switch to readvars to allow eliminating that weird trailing space.  Won't affect any current workflows.  Merging.

**Pull request merged**
