### PR TITLE
Test of including all transition files in the installer

### PR DESCRIPTION
**Pull request by Myoldmopar**
This may or may not go anywhere.  This packages up all the transition binaries, idds, and support files with every installer, so that we don't have to do the manual process of providing these via helpdesk.  I'm tagging a pre-release to get a feel for the final size difference once compressed.  If the size difference isn't that bad, then why not just include them and remove this extra step?  If the size difference is too large, we could potentially trim down the _very_ old ones off and only include from 8.0 to current.  The full, older, set could still be posted _statically_ on the helpdesk.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Installer package size, MB

| Platform | PackageSize-Develop | PackageSize-All | PackageSize-Recent |
| --- | --- | --- | --- |
| Darwin | 89.1 | 98.9 | 90.5 |
| Linux | 85.6 | 108 | 90.5 |
| Win32 | 78.3 | 88.4 | 80.6 |
| Win64 | 80.1 | 90.1 | 82.5 |

**Comment by Myoldmopar** [comment]
Hmm, @mjwitte, what do you think about those [numbers](https://github.com/NREL/EnergyPlus/pull/5265#issuecomment-148494769).  If I include just the 8.0+ required transition files, the installers only go up by a couple MB (except Linux...which goes up by 5...but that still is OK in my book).  Then we can leave those "older" transition files up on Helpdesk as they are without having to update them for each release.  Sounds awesome in my book, and easier on the users that might want to go up 2-3 releases.

**Comment by mjwitte** [comment]
All ok with me.  Can this be merged as-is?

**Comment by mjwitte** [comment]
I suppose I should test one of the installers.

**Comment by mjwitte** [comment]
Tested the Win64 installer and transitioned a v7.2 file to v8.4 and all seems OK.  Except, there is a Transition-V8-4-0-to-V8-5-0.exe present - is that expected?  There isn't a V8-5-0-Energy+.idd

**Comment by Myoldmopar** [comment]
@mjwitte The 8.5.0 idd should get itself worked out shortly.  I thought I had already updated the cmake work for 8.5.0, but it doesn't appear so.  I'll do that 100% separate from this work, so if you are OK to merge, that would be great.

**Comment by Myoldmopar** [comment]
PS @mjwitte The idd thing is now worked out in #5270, but this one here has to drop in before that one.  Let me know if you want me to do anything else to get this merged.

**Comment by mjwitte** [comment]
@Myoldmopar Mac clang is showing an unhandled failure - is that real?

**Comment by Myoldmopar** [comment]
Unlikely, but I pulled develop in so it should be all green.  Now to figure out what happened over in #5270...

**Comment by Myoldmopar** [comment]
Wait.  What??  

Oh right.  Develop has those two failures.  That's good.  This is fine to go in, but if #5268 goes in first, develop will go back to, and remain, green.

**Pull request merged**
