### PR TITLE
macOS 11 Release Packages

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Builds release packages on macOS 11.

### CODE REVIEW

**Comment by mitchute** [comment]
I tested this on my personal computer running macOS 11.6. I ran 1ZoneUncontrolled and PythonPluginPlantOperation_largeOff. The CSV outputs look normal; however, I noticed was the following message: 

```
% ./energyplus -r -w WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw ExampleFiles/PythonPluginPlantOperation_largeOff.idf
EnergyPlus Starting
EnergyPlus, Version 9.6.0-7567ba7abb, YMD=2021.09.20 20:15
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Initializing Response Factors
...
```

I'm not sure how important the "Could not find platform independent libraries" messages are, but it seems to have worked regardless.

**Comment by bonnema** [comment]
@mitchute, pretty sure I saw same/similar messages with 9.5 on macOS 11.

**Comment by Myoldmopar** [comment]
Yeah, those annoying little lines have been coming out since the Python interpreter integration.  I have followed all the policies I have found to get Python happy before calling `PyInitialize`, but they still come out.  I've found [the spot](https://github.com/python/cpython/blob/bdb56902a3bfe12b10f85a941d5dd0eae739f1a8/Modules/getpath.c#L569-L601) in the CPython code where it is emitted, and traced it all the way up through the config setup, but still cannot tell what I am missing in the setup process.  Anyway, it is harmless, EnergyPlus works fine, and it is nothing to do with this particular platform.

**Comment by mitchute** [comment]
Thanks, @Myoldmopar. I think this one is ready for review.

**Comment by Myoldmopar** [comment]
Yeah this looks good.  Package naming is working nicely.  A great addition, thanks @mitchute !

**Pull request merged**
