### PR TITLE
SAM simulation core to 3rd party library

### PR DESCRIPTION
**Pull request by nmerket**
Pull request overview
---------------------
This moves the SAM Simulation Core (SSC) code into the third_party library folder which should make it easier to keep up to date as well as add new capabilities. 

This code *should* have no diffs. 

@Myoldmopar I'd appreciate your help on the CMake stuff. I'm not super confident that I'm doing it right. Also, SSC throws some warnings which I'm not suppressing. 

I grabbed the latest released version, but it looks like the old license is still in there even though they've changed to BSD-3. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nmerket** [comment]
Okay, it looks like there are some build failures on linux, but no good error messages. I'll go build it on Ubuntu myself and see if I can get any clues there.

**Comment by nrel-bot-3** [comment]
@nmerket @lgentile it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
@nmerket I believe I've addressed the CMake issues here. I could be wrong, but based on what ssc looks like over [here](https://github.com/NREL/ssc/tree/develop/ssc), it looks like you're missing a bunch of source code. Now it's at least attempting to build on my machine but then gets stuck looking for the table externs in ```sscapi.cpp```, which I don't think have been added yet.

**Comment by nrel-bot-2** [comment]
@nmerket @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by mitchute** [comment]
@nmerket what do you think about closing this PR for now? We can leave the branch in place to make sure the proposed changes get preserved for when work is ready to proceed.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 17 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nmerket it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nmerket it has been 8 days since this pull request was last updated.

**Comment by nmerket** [comment]
This is superceded by #8275.

**Pull request closed without merging**
