### PR TITLE
Fix Electric EIR Chiller model delivering chilled water when off

### PR DESCRIPTION
**Pull request by lgu1234**
Try to merge after cleanup yesterday

### CODE REVIEW

**Comment by lgu1234** [comment]
@Myoldmopar I committed cleanup yesterday. However, I got failure of 4 checks. Could you help me to understand these failures?

I thought that my branch may be too old with 500 commits behind "develop" branch. I tried to merge my old branch with develop. It seems I could not find any conflict during merge. Any suggestions?

**Comment by Myoldmopar** [comment]
Maybe you didn't have develop updated on your machine when you tried to merge it into this branch.  I did a fresh git pull so that my version of develop was up to date, and then merged it into this branch.  It came up with a minor conflict in the unit test CMakeLists file, but nothing too hard.  I resolved the conflict and pushed it up.  CI should come back much happier now.

**Comment by Myoldmopar** [comment]
Yes, looking much better, @lgu1234

**Comment by lgu1234** [comment]
@Myoldmopar Thanks a lot. They are much better. How can I have a fresh git pull of develop branch using TortoiseGit?

**Comment by Myoldmopar** [comment]
When you do a Git Pull, two things are done:
1) `git fetch`, which grabs the latest info from GitHub and updates all your `origin/*` references, including `origin/develop`.  This **does not** update your local develop branch, however.
2) If your current branch tracks a branch on the remote GitHub, it will then merge those changes in.  This is basically: `git merge origin/branchName`
If you aren't on the develop branch when you do a git pull, your origin/develop reference _will_ be updated, but your actual develop branch _will not_ be updated.

When I merge develop into a branch, I kinda do these two steps individually:

``` shell
git fetch origin # this makes sure my origin/develop reference is up to date - my local develop is NOT updated
git merge origin/develop # I merge from the origin/develop reference, not directly from my develop branch, since I never updated that
```

Another path that _does_ update your local develop branch:

``` shell
git checkout develop # this just checks out your local develop branch
git pull # this fetches origin/develop, and ALSO merges those...your local develop IS now updated
git checkout featureBranch # this just checks out the feature branch
git merge develop # this merges from your now UPDATED develop branch...good to go
```

Let me know if you still have questions and I can add some detail or take some away.

**Pull request merged**
