### PR TITLE
Global DataHeatBalance

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Moves DataHeatBalance to state.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
@Myoldmopar eccef7b7d0ac70d2bf3789c21f096f9583a30d4f is probably worth a review for this PR.

Some of the arrays in the ctor for ```ConstructionProps``` (https://github.com/NREL/EnergyPlus/blob/d0f0bdd93d50291e4fc66e08139a5aef8730a8ab/src/EnergyPlus/Construction.hh#L286) were dimensioned based on ```DataHeatBalance::MaxSolidWinLayers```. However, now that both ```Construct``` (which is the array of ```ConstructionProps```) and ```MaxSolidWinLayers``` are both parts of the state of EnergyPlus, there was no way continue with these arrays in the ctor. I've moved them out into a standalone member method for ```ConstructionProps``` and added a call everywhere these arrays needed to be setup.

**Comment by mitchute** [comment]
@Myoldmopar assuming CI says so, this is ready. We could probably reduce a decent number of line changes here if we make a pass through replacing ```state.dataHeatBal->Blah``` with ```auto &Blah(state.dataHeatBal->Blah)``` where it makes sense. We should probably make a pass through the code anyway and make these replacements for the rest of the globals that have already been merged, but that can happen later.

**Comment by mitchute** [comment]
And I spoke too soon, there are merge conflicts again. I'm not in a hurry on this, so I'll just wait on this until other PRs have merged then I'll deal with those along with whatever cleanups you want to see.

**Comment by Myoldmopar** [comment]
OK, built locally and ran a few regressions.  Although I had a stray table-only diff in one case, I believe it to be an anomaly.  Dozens of other files sampled showed no diffs at all.  I'm going to merge this.  

This will likely cause some conflicts in branches, but that's OK.  We are prepared to help resolve conflicts as needed during this period.

Thanks for bearing with us on this @mitchute.  I think it was worth a few extra conflict-resolution commits in this branch to get the number of open PRs way down and reduce the widespread conflicts.

**Pull request merged**
