### PR TITLE
Correct Fan:SystemModel crash when Continuous mode is used without power as a function of flow fraction curve

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
The Fan:SystemModel has two operating modes, Discrete and Continuous. The Continuous operating mode requires that a power as a function of flow fraction curve is provided so that power can be calculated. If this curve is not provided the simulation will crash. This corrects #6598.

Work around: Provide the required performance curve.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
Tested all cases where Power as a function of Flow Fraction could be used.
- Discrete, no curve
- Discrete w/curve
- Continuous w/curve
- added fatal when no curve is used with Continuous

Performance curve in question is:

    Fan:SystemModel,
      CombinedPowerAndFanEff,  !- Electric Power Function of Flow Fraction Curve Name

6598-fanpowercurveresults

The performance curve is not used for Discrete operating mode so it doesn't matter if it's present or not. Fan power for both discrete test cases are the same.

6598-fanpowercurveresults_samefanpower

**Comment by Myoldmopar** [comment]
So these changes are fine, but I might be missing something so I just want to check.  I took the UnitarySystem_MultiSpeedCoils_SingleMode.idf file and removed the Electric Power curve value.  In **develop**, the file ran until a fatal error saying the field is required.  With this branch I get the same error.  I'm just wanting to recreate the error.  I could use the defect file if there is one, but I also want to understand it just a bit.

**Comment by rraustad** [comment]
I had a file that showed an issue with fan operation and I fixed that. Then I wanted to make sure it worked when I switched the fan control type. When I switched the fan control type from discrete to continuous, the program crashed (defect file = 6598-Office_Chicago_MultiStageGasHeatingCoil_Continuous) ... because there was no power function of flow curve. It's because the code checked for discrete in Init but didn't check for discrete in calc. This fixes that.

**Comment by Myoldmopar** [comment]
OK, I took the defect file and modified our example file to be similar for the Fan:System model object.  I was able to see the hard crash.  I did the same thing on this branch and saw the fatal error.  This is good, CI is happy, I'm re-running the unit tests locally to make sure nothing is introduced when this merges with develop, but I anticipate it will be fine and I'll merge this in a few minutes.  Thanks @rraustad.

**Comment by Myoldmopar** [comment]
Tests pass locally, good to go.

**Pull request merged**
