### PR TITLE
Clarification of the documentation regarding the 'Main Pipe' in the VRF-FluidTCtrl-HP and VRF-FluidTCtrl-HR models

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
As suggested by @jmarrec [here](https://unmethours.com/question/26176/main-pipe-in-airconditionervariablerefrigerantflowfluidtemperaturecontrol/), clarification of the documentation (IDD file, I/O reference guide and engineering manual) regarding the meaning of the 'Main Pipe' in the VRF-FluidTCtrl-HP and VRF-FluidTCtrl-HR models.

The proposed changes are based on an email exchange with Kaiyu Sun and Rongpeng Zhang.

> The "main pipe" refers to the pipe connecting the outdoor unit to the first branch joint. That's where the most piping loss occurs.

### Review Checklist
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
 - [ ] Documentation changes in place

### CODE REVIEW

**Review by rraustad — APPROVED** [review]
Appropriate changes to docs to clarify meaning of main pipe length.

**Comment by Myoldmopar** [comment]
@lymereJ This work wasn't funded as part of a subcontract for DOE, and I don't think we have a contribution policy signed and in place from you for accepting contributions.  As much as I'd like to just accept this, I can't without the contribution policy.  I'm going to target this for the next EnergyPlus release, but if I'm wrong, or if we can get one signed very quickly, we could still consider this for 8.8.0. 
 However, the IDD changes would have to be removed as our IDD is frozen for this release.

**Comment by lymereJ** [comment]
@Myoldmopar, I did sign a LCA last year, under the name of the company I work for (Madison Engineering PS). I have a copy of it signed by both party. Please, let me know if it has changed or if you'd like a copy of it. Thanks!

**Comment by Myoldmopar** [comment]
Thanks @lymereJ for the quick reply!  You know, I kinda thought I had gone through this with you, but I couldn't find the correspondence.  So two things:
 - I'll coordinate with @jasondegraw to figure out the status of your CLA and get back with you.
 - Assuming we get the CLA taken care of quickly: this PR has IDD changes, which will keep it from going into this release.  If you want this PR to try to get in for 8.8, it'll need to have those removed.  If you'd rather just keep the PR as-is, we can drop it in right after the release.  Either way is fine with me; thanks for the contributions!

**Comment by lymereJ** [comment]
@Myoldmopar, next release is fine for me.

**Comment by nrel-bot-2** [comment]
@lymereJ @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@lymereJ @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@lymereJ @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Sorry this took so long @lymereJ.  I will merge this.  Thanks for the contribution.

**Pull request merged**
