### PR TITLE
Fix PTHP hard crash when autosizing is requested but no sizing run was done

### LINKED ISSUE #8812: EnergyPlus Hard Crash: Error file cut short when autosizing not set up correctly
Issue overview
--------------
When a model does not include SizingPeriod:* objects and "Do Zone Sizing" and "Do Plant Sizing" inputs are turned off but HVAC fields are set to "Autosize", the model generates an appropriate warning but continues to run and then experiences a hard crash further along in the simulation, burying the warning associated with the sizing issue.  If the model does not include SizingPeriod:* objects but "Do Zone Sizing" and "Do Plant Sizing" inputs are turned on, a severe error is generated along with a fatal error to easily identify the sizing input issue.  The crash occurs at [line 5429](https://github.com/NREL/EnergyPlus/blob/ab0f1654a033a273fadf40f9856f850cf791e2f7/src/EnergyPlus/PackagedTerminalHeatPump.cc#L5429) in PackagedTerminalHeatPump.cc due to no zone sizing being performed since `state.dataGlobal->ZoneSizingCalc` is set to `false` in the [ManageZoneEquipment](https://github.com/NREL/EnergyPlus/blob/ab0f1654a033a273fadf40f9856f850cf791e2f7/src/EnergyPlus/ZoneEquipmentManager.cc#L146) function in ZoneEquipmentManager.cc.

Warning generated followed by another 500+ lines of other warnings before hard crash
image

Severe/Fatal error generated when "Do Zone Sizing" and "Do Plant Sizing" inputs are turned on
image

The warnings/errors are from the [CheckForMisMatchedEnvironmentSpecifications](https://github.com/NREL/EnergyPlus/blob/ab0f1654a033a273fadf40f9856f850cf791e2f7/src/EnergyPlus/SimulationManager.cc#L1490) function in SimulationManager.cc.  Need to add an additional check in the code somewhere to account for this situation.

[in.zip](https://github.com/NREL/EnergyPlus/files/6628495/in.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #8812 
 - This pull request adds CheckZoneSizing call before looking for the FinalZoneSizing MinOA to prevent a hard crash if the cooling outside air flow rate is autosized but no zone sizing run was done.  This approached is used in other similar situations, as well as within this file.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This is such a simple fix I'm tempted to just review it as is and merge it in, even without a unit test.  But I think I'll hold back for now.  Maybe you could just tweak an existing unit test to support this code path?

**Comment by matthew-larson** [comment]
I can see about getting this in an existing unit test.

**Comment by Myoldmopar** [comment]
Add a space after the comma in the new unit test and this will pass Clang Format and likely be ready to merge if CI is all happy.  Thanks for getting the test added!

**Comment by Myoldmopar** [comment]
Nailed it, thanks @matthew-larson !

**Pull request merged**
