### PR TITLE
CppCheck style suggestions for UnitarySystem

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes UnitarySystem style suggestions from CppCheck
 - Clean up some poor code construct

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Addresses majority of:

image

image

image

image

image

**Comment by rraustad** [comment]
@Myoldmopar @jmarrec what switch do I flip in what workflow so that this branch will show me the CppCheck style suggestions? I want to know how many of the suggestions I fixed and how many are remaining. There are no diffs so I only need to run the workflows.

**Comment by amirroth** [comment]
When are we enabling chatGPT?

**Comment by jmarrec** [comment]
> @Myoldmopar @jmarrec what switch do I flip in what workflow so that this branch will show me the CppCheck style suggestions? I want to know how many of the suggestions I fixed and how many are remaining. There are no diffs so I only need to run the workflows.

No sure I'm following the question?

The list of warnings for your file can be found here: https://github.com/NREL/EnergyPlus/actions/runs/4320399437/jobs/7540606510#step:8:3701

```
[src/EnergyPlus/UnitarySystem.cc:14463]:(style),[duplicateCondition],The if condition is the same as the previous if condition
[src/EnergyPlus/UnitarySystem.cc:2960]:(style),[knownConditionTrueFalse],Condition 'MSHPIndex>-1' is always true
[src/EnergyPlus/UnitarySystem.cc:12420]:(style),[redundantAssignment],Variable 'CycRatio' is reassigned a value before the old one has been used.
[src/EnergyPlus/UnitarySystem.cc:12424]:(style),[redundantAssignment],Variable 'PartLoadFrac' is reassigned a value before the old one has been used.
[src/EnergyPlus/UnitarySystem.cc:12420]:(style),[redundantAssignment],Variable 'CycRatio' is reassigned a value before the old one has been used.
[src/EnergyPlus/UnitarySystem.cc:12424]:(style),[redundantAssignment],Variable 'PartLoadFrac' is reassigned a value before the old one has been used.
[src/EnergyPlus/UnitarySystem.cc:12246]:(style),[variableScope],The scope of the variable 'SpeedNum' can be reduced.
[src/EnergyPlus/UnitarySystem.cc:14231]:(style),[variableScope],The scope of the variable 'LatentLoad' can be reduced.
[src/EnergyPlus/UnitarySystem.cc:4902]:(style),[shadowVariable],Local variable 'ActualCoolCoilType' shadows outer variable
[src/EnergyPlus/UnitarySystem.cc:5418]:(style),[constVariable],Variable 'thisSuppCoil' can be declared as reference to const
[src/EnergyPlus/UnitarySystem.cc:18175]:(style),[constParameter],Parameter 'state' can be declared as reference to const
[src/EnergyPlus/UnitarySystem.cc:942]:(style),[useStlAlgorithm],Consider using std::fill algorithm instead of a raw loop.
[src/EnergyPlus/UnitarySystem.cc:3227]:(style),[unreadVariable],Variable 'SizingMethod' is assigned a value that is never used.
[src/EnergyPlus/UnitarySystem.cc:3246]:(style),[unreadVariable],Variable 'SizingMethod' is assigned a value that is never used.
[src/EnergyPlus/UnitarySystem.cc:3269]:(style),[unreadVariable],Variable 'IsAutoSize' is assigned a value that is never used.
[src/EnergyPlus/UnitarySystem.cc:1364]:(style),[unusedVariable],Unused variable: SystemType
[src/EnergyPlus/UnitarySystem.cc:6638]:(style),[unreadVariable],Variable 'errFlag' is assigned a value that is never used.
```

Comparing the summary between your branch and latest cppcheck run for develop: https://github.com/NREL/EnergyPlus/actions/runs/4320399437/jobs/7540606510#step:8:16

develop: 4362 style(s)
this branch: 4278 style(s)
=> fixed = 84

**Comment by rraustad** [comment]
Reduced style messages to 2:

    [src/EnergyPlus/UnitarySystem.cc:18169]:(style),[constParameter],Parameter 'state' can be declared as reference to const
    [src/EnergyPlus/UnitarySystem.cc:18172]:(style),[useStlAlgorithm],Consider using std::any_of algorithm instead of a raw loop.

which associate with this function. I am not sure of the correction.

    18169 void isWaterCoilHeatRecoveryType(EnergyPlusData &state, int const waterCoilNodeNum, bool &nodeNotFound)
          {
              for (auto const &unitarySystem : state.dataUnitarySystems->unitarySys) {
    18172         if (unitarySystem.m_HRcoolCoilFluidInletNode == waterCoilNodeNum && unitarySystem.m_WaterHRPlantLoopModel) {
                      nodeNotFound = false;
                      break;
                  }
              }
          }

**Comment by rraustad** [comment]
I don't plan on adding any other style changes to this branch. Review and merge as appropriate.

**Comment by Myoldmopar** [comment]
Thanks @rraustad, on the dashboard it looks like this branch is showing one build warning.  It's just an unused variable, so it's easy to fix, but should be done before merge.  If you want to update the branch with it, that's cool, but I can also do it right as I'm doing final review on the branch and just push/merge quickly.

**Comment by Myoldmopar** [comment]
(http://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-74dcd03669b93d21c7677a3d528a7b4f9567a33e-x86_64-Linux-Ubuntu-18.04-gcc-7.5.html#build)

**Comment by rraustad** [comment]
Unused variable removed. A chunk of unused code in init had been removed and was the only place where this function argument was needed. Several units tests also updated.

**Comment by rraustad** [comment]
Only 1 style suggestion left for UnitarySystem and I was not sure how to correct this.

    [src/EnergyPlus/UnitarySystem.cc:18171]:(style),[useStlAlgorithm],Consider using std::any_of algorithm instead of a raw loop.

             void isWaterCoilHeatRecoveryType(EnergyPlusData const &state, int const waterCoilNodeNum, bool &nodeNotFound)
             {
                 for (auto const &unitarySystem : state.dataUnitarySystems->unitarySys) {
    18171            if (unitarySystem.m_HRcoolCoilFluidInletNode == waterCoilNodeNum && unitarySystem.m_WaterHRPlantLoopModel) {
                         nodeNotFound = false;
                         break;
                     }
                 }
             }

**Comment by amirroth** [comment]
> Only 1 style suggestion left for UnitarySystem and I was not sure how to correct this.
> 
> ```
> [src/EnergyPlus/UnitarySystem.cc:18171]:(style),[useStlAlgorithm],Consider using std::any_of algorithm instead of a raw loop.
> 
>          void isWaterCoilHeatRecoveryType(EnergyPlusData const &state, int const waterCoilNodeNum, bool &nodeNotFound)
>          {
>              for (auto const &unitarySystem : state.dataUnitarySystems->unitarySys) {
> 18171            if (unitarySystem.m_HRcoolCoilFluidInletNode == waterCoilNodeNum && unitarySystem.m_WaterHRPlantLoopModel) {
>                      nodeNotFound = false;
>                      break;
>                  }
>              }
>          }
> ```

You basically take the `if ()` body and make it into a lambda that returns a `bool`, then pass that to `any_if`. Something like:

```cpp
nodeFound = std::any_if(state.dataUnitarySystems->unitarySys.begin(), // iterator to beginning of range
                        state.dataUnitarySystems->unitarySys.end(), // iterator to  end of range
                        [waterCoilNodeNum](auto const &us) { return (us.m_HRcoolCoilFluidInletNode == waterCoilNodeNum) && us.m_WaterHRPlantLoopModel; }); // lambda that returns true for matching elements
```

I assume that CppCheck would not make this suggestion if it resulted in a performance penalty, e.g., the lambda becomes inlined because `any_of` is a template. Is this a safe assumption?

**Comment by Myoldmopar** [comment]
I've got it almost done building locally with any_of and a lambda.  I could check runtime change, but this is probably not going to show anything really measurable.  How often is this called?

**Comment by Myoldmopar** [comment]
Oh looks like one spot during get input.  Yeah...probably not going to show much change lol

**Comment by Myoldmopar** [comment]
OK well scratch that...something about this change made my unit tests run BRUTALLY slow.  I'm not sure if my quick hack was a mistake or what.  Anyway, no reason to sweat that change right now, you've already made a bunch of great fixes here, thanks @rraustad

**Comment by rraustad** [comment]
This does seem to work since all unit tests pass with no noticable slowdown. But I still don't understand the syntax. I won't check this in here since I was just testing out this new pattern.

in Autosizing/Base.cc replacing:

        if (this->sysSizingRunDone) {
            for (auto const &sizingInput : this->sysSizingInputData) {
                if (sizingInput.AirLoopNum == this->curSysNum) {
                    this->sizingDesRunThisAirSys = true;
                    break;
                }
            }
        }

with:

        if (this->sysSizingRunDone) {
            int sysNum = this->curSysNum;
            this->sizingDesRunThisAirSys = std::any_of(
                this->sysSizingInputData.begin(), this->sysSizingInputData.end(), [sysNum](auto const &ssid) { return (ssid.AirLoopNum == sysNum); });
        }

**Comment by amirroth** [comment]
> ```cpp
>     if (this->sysSizingRunDone) {
>         int sysNum = this->curSysNum;
>         this->sizingDesRunThisAirSys = std::any_of(
>             this->sysSizingInputData.begin(), // iterator that points to beginning of range you are testing
>             this->sysSizingInputData.end(), // iterator that points to end of range you are testing
>             [sysNum](auto const &ssid) { return (ssid.AirLoopNum == sysNum); }); // function that returns true when current item matches condition
>     }
> ```

I annotated your code to try to clarify. The first two arguments are the way you pass the array to `any_of`, iterator-style. Instead of passing the array and its size, you pass an iterator to the beginning and an iterator to the end. This is a very common pattern in standard template library container functions.

The trickier parameter is the third one. This is a function you have to provide that returns true whenever the object reference passed to it by `any_of` matches the criterion you want. This is essentially a function pointer. You could have declared that function in the normal way and then just passed its name as the third argument to `any_of`. Except for one thing. How would you pass `sysNum` to this function? You couldn't pass it through the argument because `any_of` specifies that the function you pass it takes only one argument, a reference to an object in the array. How else could you get the `sysNum` in there? You need some version of the `Par` array trick that we used to do for Residual functions before @Myoldmopar got rid of it. That's where `[sysNum]` comes in. That little bit is what makes the function you are defining as the third parameter from just a normal function into what is called a "closure". `[sysNum]` essentially "captures" `sysNum` from the surrounding context and lets you use it in the body of the function without passing it as a parameter. It's essentially a formal language-level mechanism for doing the `Par` trick. [Here](https://github.com/NREL/EnergyPlus/wiki/Lambdas%3A-When-and-How-to-Use-Them) is a longer explanation of this feature, which for historical reasons is called "lambda".

**Comment by rraustad** [comment]
And this also worked fine. Unit tests ran in < 3 min with all 3 of these changes. Since no merge will happen until tomorrow, I might just push these changes tonight. I assume the `(auto const &us)` is a reference to the begin/end iterators?

    void isWaterCoilHeatRecoveryType(EnergyPlusData const &state, int const waterCoilNodeNum, bool &nodeNotFound)
    {
        nodeNotFound =
            std::any_of(state.dataUnitarySystems->unitarySys.begin(), state.dataUnitarySystems->unitarySys.end(), [waterCoilNodeNum](auto const &us) {
                return (us.m_HRcoolCoilFluidInletNode == waterCoilNodeNum) && us.m_WaterHRPlantLoopModel;
            });
    }

**Comment by rraustad** [comment]
CI shows at least 1 of the last changes is not working.

**Comment by rraustad** [comment]
Ah, the lambda in UnitarySystem should return false if the condition is true (the node was found), but not change nodeNotFound if condition is false. This lambda will return true or false and here we only want to return false so as not to change the bool passed in if the condition is false. This is one of those "don't change the bool if it comes in false". Maybe this would work?

    nodeNotFound =
        std::any_of(state.dataUnitarySystems->unitarySys.begin(), state.dataUnitarySystems->unitarySys.end(), [waterCoilNodeNum](auto const &us) {
            return (if (!nodeNotFound) ? nodeNotFound : !(us.m_HRcoolCoilFluidInletNode == waterCoilNodeNum && us.m_WaterHRPlantLoopModel));
        });

or add at the top:

    if (!nodeNotFound) return;

**Comment by amirroth** [comment]
I would keep the lambda simple and just use `nodeFound` rather than `nodeNotFound`. There is also a `std::none_of` that you can use instead of doing these gymnastics.

**Comment by jmarrec** [comment]
suggest this:

```c++
void isWaterCoilHeatRecoveryType(EnergyPlusData const &state, int const waterCoilNodeNum, bool &nodeNotFound) {
    return std::none_of(state.dataUnitarySystems->unitarySys.cbegin(), state.dataUnitarySystems->unitarySys.cend(), [waterCoilNodeNum](auto const &us) {
                return us.m_WaterHRPlantLoopModel && us.m_HRcoolCoilFluidInletNode == waterCoilNodeNum;
            });
}
```

**Comment by Myoldmopar** [comment]
> something about this change made my unit tests run BRUTALLY slow. I'm not sure if my quick hack was a mistake or what.

It wasn't anything about this change.  In that particular build folder I had turned on the more aggressive valgrind analysis and it was bogging things down.  I saw you reverted your change @rraustad, and for the moment I am fine with leaving this branch however it ended up.  This won't be a consequential change, and is not urgent.

**Comment by Myoldmopar** [comment]
The WIndows build failure appears unrelated.  It happens on a very rare basis, nothing to worry about.  I'll pull in develop and test just to be sure locally.

**Comment by Myoldmopar** [comment]
Everything fully happy here, merging this one.  Thanks @rraustad

**Pull request merged**
