### PR TITLE
Fix daylighting shape test for isosceles trapezoid surfaces which were incorrectly marked as rectangular

### PR DESCRIPTION
**Pull request by mjwitte**
Address #5173 Base surfaces with 4 sides which are isosceles trapezoids were being classified as rectangular which caused some errors in daylighting calculations.

Initial tests with annual runs show no diffs with 5ZoneAirCooled where all the trapezoidal surfaces are interzone ceilings between the upper plenum zone and the occupied zones below, or are floor surfaces.  This has solar distribution = FullExterior.

5ZoneVAV-ChilledWaterStorage-Mixed showed small annual diffs.  This is one of the few 5zone models which do not have the upper plenum zone, so there are trapezoidal exterior roof surfaces.  This has solar distribution = FullInteriorAndExterior.

Will let CI identify any test suite files with significant diffs.

@DeadParrot Do you know where this defect would have the most impact?  Shadow casting surface?  Receiving surface?  Interior surface for FullInterior solar distribution?  Solar shading or daylighting or both?

### CODE REVIEW

**Comment by DeadParrot** [comment]
@mjwitte I saw diffs in HospitalLowEnergy in the Sky Daylight Factors from the #5173 issue. Anywhere that PierceSurface might get called for one of those trapezoid "rectangles" has a reasonable chance of yielding incorrect results with the current develop code.

**Comment by mjwitte** [comment]
@DeadParrot @Myoldmopar So, at first glance, it appears to only impact daylighting.  Significant changes in daylighting factors (eio output), trickling in to smaller differences in sizing, and some significant differences in reported illuminance values. Curious that some files are with big eso diffs are in the warnings group instead of the failures.

**Comment by mjwitte** [comment]
@Myoldmopar This should really go in for v8.4.  Need to add a unit test.

**Comment by mjwitte** [comment]
Setting up an annual test suite comparison against develop.

**Comment by mjwitte** [comment]
Annual test suite with daily output reports big diffs for these files (same as the failures on CI)
5ZoneVAV-ChilledWaterStorage-Mixed
5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd
5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MultiPath
5ZoneVAV-ChilledWaterStorage-Stratified
EcoroofOrlando
PlantApplicationsGuide_Example2
The files listed above all share esssentially the same building which is a variation on the 5zone building with long ribbon windows in trapezoidal perimeter zones, skylights, and daylighting controls.
image

EMSPlantLoopOverrideControl has a similar two-story building with long ribbon windows under trapezoidal roof surfaces.

And HospitalLowEnergy has a large two-story wing with similar configuration.

Total electric and gas use changed by <1%.  Interior lighting energy went down by as much as 5%.  For these files, no significant difference in runtime was seen.

**Comment by Myoldmopar** [comment]
Does the lighting energy change make sense because of the different shape classification?

**Comment by mjwitte** [comment]
If I understand PierceSurface, it's using the first two sides when the surface is tagged as a rectangle.  So this would turn trapezoids into prallelograms (which as I say this, may work fine as "rectangle" but it's still confusing).  PierceSurface is used in many different ways to both obstruct daylighting and to absorb/reflect daylighting.  So, it is hard to say what change to expect (up or down) for these files without more digging into specific surface-level variables.

**Comment by Myoldmopar** [comment]
Which I don't think we have time for right now, so I'm proposing moving this to the bug fix milestone.

**Comment by mjwitte** [comment]
Added unit tests and realized that parallelograms were correct before this fix - they have unequal diagonals (duh).  So, the only affected 4-sided shape which i can think of that would have equal length diagonals but not be a rectangle is an isosceles trapezoid.  Will try to expose some additional output variables to explain the differences in results.

**Comment by DeadParrot** [comment]
@mjwitte I noticed then forgot to mention the parallelograms red herring -- sorry.

I am concerned about the tests used to determine rectangularity. Shouldn't these be relative, not absolute, tolerances? And if we understand the precision required for surface vertices we could derive an appropriate precision for the tolerances.

**Comment by mjwitte** [comment]
@DeadParrot Good point that the tolerances are arbitrary.  The tolerance for vertices is 0.01 which is used [here](https://github.com/NREL/EnergyPlus/blob/9bb8c3440f96be4d4897f12e0c0d13cc64eb7a02/src/EnergyPlus/SurfaceGeometry.cc#L6455-L6460) to remove a coincident vertex.  So a tolerance of 0.02 on comparing diagonals is appropriate.  I suppose the dotproduct could be normalized by the vector lengths, but I'm not sure what we gain there.  If the rectangularity test fails, then the more general quadrilateral method is used in PierceSurface, but I'm open to a change.  

Also, stumbled across [another place](https://github.com/NREL/EnergyPlus/blob/9bb8c3440f96be4d4897f12e0c0d13cc64eb7a02/src/EnergyPlus/SurfaceGeometry.cc#L8530-L8535) that has the same rectangularity test to flag non-rectangular 4-sided fenestration surfaces as an error.

**Comment by DeadParrot** [comment]
@mjwitte so the vertex accuracy spec is an absolute 1 cm with no precision (relative) spec? For a test like rectangularity that means that large surfaces are held to a much tighter shape spec than small surfaces. Having both absolute and relative specs may be best.

It is possible that when I redo PierceSurface I can reduce or eliminate the assumption of strict orthogonality of rectangle corners so it may not end up being as big a problem.

**Comment by mjwitte** [comment]
@DeadParrot That's my understanding - absolute 1 cm.

**Comment by mjwitte** [comment]
Just to verify that the changes make sense, I took 5ZoneVAV-ChilledWaterStorage-Mixed and removed the celing from one zone.  For that zone, the daylighting results are identical before and after this fix.  Interestingly, the illuminance levels in that zone are higher without the ceiling surface than with it.  That is consistent with the results comparison noted above showing that interior lighting energy use goes down with this fix - less ceiling surface results in higher daylighting levels.

**Comment by mjwitte** [comment]
@Myoldmopar This is ready for review (again).  Check the clear_state gymnastics (tried to follow existing patterns found elsewhere) carefully.

**Comment by Myoldmopar** [comment]
@mjwitte This looks awesome.  The isRectangle function is good, clear_state() all looks good, and the unit tests are good.  I cleaned up one tiny indentation issue and will happily let CI take a pass at it and merge this afternoon.

**Comment by Myoldmopar** [comment]
I've changed my mind, I'm not waiting on CI to run on this branch with just the indentation change only.  Merging.

**Pull request merged**
