### PR TITLE
Fixing typo in documentation for `Room Air Models`

### PR DESCRIPTION
**Pull request by jmarrec**

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jmarrec Could you shoot me an email at edwin dot lee at nrel dot gov from your preferred email address?  I'd like to chat with you about getting this PR merged.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jmarrec OK, I think we have been cleared to get your work in according to @lgentile.  Thanks for sticking with it.  So....this PR....it got real conflicted in the meantime, since we went from Markdown to LaTeX.  Do you care you check the changes out locally and re-apply then in the LaTeX?  If not, I'm happy to do it, but wanted to give you the chance first.      (FYI @jasondegraw)

**Comment by jmarrec** [comment]
Yeah I noticed this got moved to LaTeX (after all, the PR is open since February 7...).
I have no time to do the changes in LaTeX myself, sorry. (I'm implementing higher priority stuff in OpenStudio and it's taking all of my free time)

Most of the changes I made can be picked up using a word corrector.

**Comment by Myoldmopar** [comment]
Yeah, sorry about the hold up getting it in.  I will cherry pick your commit, and then merge develop in to resolve the conflict.  Even though I'll basically be redo-ing the changes, you'll still have your commit there in the history.

**Comment by Myoldmopar** [comment]
Replaced with #5735, which does contain your commits here in the history, just got messy with Git/Github, so I kept it separate.  Closing this one, and I'll merge the other one.

**Pull request closed without merging**
