### PR TITLE
#10545  - Provide facilities for testing enums in a safe way (EXPECT_ENUM_EQ / EXPECT_ENUM_NE) 

### LINKED ISSUE #10545: Provide facilities for testing enums in a safe way (EXPECT_ENUM_EQ / EXPECT_ENUM_NE)
Issue overview
--------------

Provide facilities for testing enums in a safe way (EXPECT_ENUM_EQ / EXPECT_ENUM_NE)

https://github.com/NREL/EnergyPlus/pull/10537#discussion_r1622292656

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): all (571482d1b18c7b3a6cdcba840f355152efe181e5)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #10545

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
in c I added tests that fail voluntarily, so we can check the output messages on all platforms. They are ok, even on windows (https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-c66399d1a80eff32a675a543edfa24a33b255661-Win64-Windows-10-VisualStudio-16.html) 

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CustomMatchers
[ RUN      ] CustomMatchers.enums_not_ok_assert_eq
/Users/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/CustomMatchers.unit.cc:85: Failure
In comparing enums of type 'EnergyPlus::Constant::eResource', Expected equality of these values:
  Constant::eResource::Electricity
    Which is: 0
  Constant::eResource::NaturalGas
    Which is: 1
[  FAILED  ] CustomMatchers.enums_not_ok_assert_eq (0 ms)
[----------] 1 test from CustomMatchers (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CustomMatchers.enums_not_ok_assert_eq

 1 FAILED TEST
[2/4] CustomMatchers.enums_not_ok_assert_eq returned/aborted with exit code 1 (19 ms)
[3/4] CustomMatchers.enums_not_ok_assert_ne (17 ms)
Note: Google Test filter = CustomMatchers.enums_not_ok_assert_ne
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CustomMatchers
[ RUN      ] CustomMatchers.enums_not_ok_assert_ne
/Users/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/CustomMatchers.unit.cc:90: Failure
Expected: (Constant::eResource::NaturalGas) != (Constant::eResource::NaturalGas), actual: both are EnergyPlus::Constant::eResource(1)
[  FAILED  ] CustomMatchers.enums_not_ok_assert_ne (0 ms)
[----------] 1 test from CustomMatchers (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CustomMatchers.enums_not_ok_assert_ne

 1 FAILED TEST
[3/4] CustomMatchers.enums_not_ok_assert_ne returned/aborted with exit code 1 (17 ms)
[4/4] CustomMatchers.enums_not_ok (19 ms)
Note: Google Test filter = CustomMatchers.enums_not_ok
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CustomMatchers
[ RUN      ] CustomMatchers.enums_not_ok
/Users/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/CustomMatchers.unit.cc:79: Failure
In comparing enums of type 'EnergyPlus::Constant::eResource', Expected equality of these values:
  Constant::eResource::Electricity
    Which is: 0
  Constant::eResource::NaturalGas
    Which is: 1
/Users/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/CustomMatchers.unit.cc:80: Failure
Expected: (Constant::eResource::NaturalGas) != (Constant::eResource::NaturalGas), actual: both are EnergyPlus::Constant::eResource(1)
[  FAILED  ] CustomMatchers.enums_not_ok (0 ms)
[----------] 1 test from CustomMatchers (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CustomMatchers.enums_not_ok

 1 FAILED TEST
[4/4] CustomMatchers.enums_not_ok returned/aborted with exit code 1 (19 ms)
FAILED TESTS (3/4):
      19 ms: Products/energyplus_tests CustomMatchers.enums_not_ok_assert_eq
      17 ms: Products/energyplus_tests CustomMatchers.enums_not_ok_assert_ne
      19 ms: Products/energyplus_tests CustomMatchers.enums_not_ok
Built branch '10545_EXPECT_ENUM_EQ' in 0min13s, tests ran in 0min5s
```

**Review by Myoldmopar — APPROVED** [review]
:scream: that's a lot of changes!  Great stuff.  I am fine with pulling this in, even if we have to fix it up in some of the other PRs that add more testing.

**Comment by Myoldmopar** [comment]
The windows failure is unrelated.....right?

**Comment by Myoldmopar** [comment]
Allll clean now.  Thanks @jmarrec, this is cool!

**Pull request merged**
