### PR TITLE
121174135 compute int thermal absorp factors movable insulation bugs

### PR DESCRIPTION
**Pull request by RKStrand**
## Pull request overview

This fixes GitHub Issue #5720 
Changes to the code will now pick up the proper thermal absorptivity (interior rather than exterior). Unit test shows this working properly in ComputeIntThermalAbsorpFactors subroutine.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ x ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ x ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  This issue number is #5720 
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by RKStrand** [comment]
@mjwitte @Myoldmopar Code and unit test ready for review...would one of you be willing to take a look at it?  Pretty straightforward bug fix and not too complicated.  No conflicts...shouldn't take too long to review and merge hopefully.  Thanks!

**Comment by Myoldmopar** [comment]
So, for reference, it looks like there may be a hard crash in HospitalLowEnergy.  It's only showing up in the Debug build, which makes me think there may be an array bounds error or something.

Hmm, well, that was actually brought in when you merged develop, and that was almost two weeks ago.  I'm going to pull develop in now and see if it goes back away since your changes seem fine.  If CI is happy with it, I'll do a couple local runs and get it merged in.

**Comment by Myoldmopar** [comment]
Code changes look good.  Built locally with no issue.  Unit test is fine.  CI is happy.

I then ran a few tests, plotting the inside surface temperature of the surface with the insulation in place, for the summer design day.

image
- Before the fix is made (in develop branch), a change to the thermal absorptance of inside movable insulation does _not_ cause a change in the inside surface temperature.  This is the blue line, and it is always zero.  This is the first half of bug #5720.
- Before the fix is made (in develop branch still), a change to the thermal absorptance of _outside_ movable insulation _does_ cause a change in the inside surface temperature.  This is the red line, and is the other half of the bug.
- After the fix is made in this branch, a change to the thermal absorptance of inside movable insulation _does_ cause a change in the inside surface temperature. This is the green line, and is good news.
- In similar fashion, a change to the thermal absorptance of outside movable insulation causes no difference in inside surface temperature.  (Maybe nonzero, but waaay small.)  This is the purple line, and is also good news.

This is merging.  Thanks for the fix @RKStrand.

**Comment by RKStrand** [comment]
@Myoldmopar Awesome--thanks for reviewing this and merging it, Edwin!

**Pull request merged**
