### PR TITLE
Add HeatExchanger:AirToAir:SensibleAndLatent as a valid air loop main branch component 

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #5156 
Added the HeatExchanger:AirToAir:SensibleAndLatent component  on the main branch. This heat exchanger was a valid component in the outdoor air system. The air outlet conditions behaved as expected. Also added a unit test that confirms that the component is read correctly during get input.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
So, shouldn't this have an idf test file to demonstrate this added capability?

**Comment by Nigusse** [comment]
I can create one if desired.

**Comment by Nigusse** [comment]
Fixed the new unit test added that resulted an existing unit test to fail. Updated branch is pushed to remote. The CI machine is expected to run clean.

**Comment by nrel-bot-3** [comment]
@mjwitte @Nigusse @lgentile it has been 15 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Merged up to current develop.  Tested the new example file.  Unit tests run fine separately, but fail when all tests are run together, assertion failure in EnergyPlusFixture.HeatRecoveryHXOnMainBranch_SimHeatRecoveryTest

**Comment by mjwitte** [comment]
@mbadams5 Thanks for the review.  This should be all cleaned up now.

**Comment by mjwitte** [comment]
Ready to merge once windows CI reports in

**Pull request merged**
