### PR TITLE
Github Actions Trial

### PR DESCRIPTION
**Pull request by Myoldmopar**
First test of an action on the E+ repo, the workers aren't big enough to keep up with our full tests, but they could be a good place to drop random tests like custom_check stuff for now.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
OK, so this should be ready to go once CI is done. We are now splitting our CI duties between Decent CI and Github Actions.  Eventually everything will go through Github Actions, we just need to figure out the horsepower situation.

For now, we have these builds on Decent CI:
  - Mac release build, unit test, integration test, regression test
  - Windows release build, unit test, integration test
  - Linux release build, unit test, integration test, regression test, performance test
  - Linux debug build, unit test -> unit test coverage
  - Linux release build, integration test -> integration test coverage
  - Mac release DMG, TAR
  - Windows 64-bit release EXE, ZIP
  - Windows 32-bit release EXE, ZIP (*not linked to Python)

And then these will now run on Github Actions:
  - Custom Checks
  - Pull request label verification
  - CppCheck
  - Documentation builds (Linux)

Note that the documentation PDFs are included as artifacts on the build results page, as on the top right of [this](https://github.com/NREL/EnergyPlus/runs/1098189111) page:

image

Moving forward, we'll get things more and more moved over to Github Actions.  We also will have our API documentation built dynamically with ReadTheDocs.

**Comment by Myoldmopar** [comment]
@mitchute or @mjwitte if you see the final build come up green from the Decent CI builds this afternoon, feel free to merge away or ask questions if you have any.

**Comment by mitchute** [comment]
Excellent!

**Comment by mitchute** [comment]
This is going to be great! Everything looks good. Merging.

**Pull request merged**
