### PR TITLE
Fix gcc 4.8.2 internal compiler errors

### LINKED ISSUE #5854: Can't build EnergyPlus on Centos 6.6
@Myoldmopar @lefticus 

I've tried building EnergyPlus 8.6 on Centos 6.6.  The default compiler is gcc 4.4 which doesn't seem to support c++11.  I get compiler crashes using gcc 4.7 and 4.8.  When I tried to install clang 3.4 I get GLIBCXX_3.4.15, GLIBC_2.15 and GLIBC_2.14 not found.  What compiler should I use?

### PR DESCRIPTION
**Pull request by mbadams5**
## Pull request overview

This fixes all internal compiler errors with GCC 4.8.2. Some of the changes are hacky, but were easy fixes. I tested this on Centos 6.7 with devtoolset 2.0 (gcc 4.8.2).

Fixes #5854
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mbadams5** [comment]
This should address #5854 when using devtoolset 2.1 on Centos 6, @macumber

**Comment by macumber** [comment]
Fixes #5854

**Comment by macumber** [comment]
@Myoldmopar this did allow me to build E+ but I was not able to build package on CentOS, @mbadams5 hit some other issue but I don't think he was able to build package either

**Comment by macumber** [comment]
Here is the error I get, seems to be related to finding dependencies of ExpandObjects:

```
Run CPack packaging tool...
CPack: Create package using TBZ2
CPack: Install projects
CPack: - Run preinstall target for: EnergyPlus
CPack: - Install project: EnergyPlus
 +++ AutoDocs: Completed processing output variable audit: processed 3795 calls
 +++ AutoDocs: Completed processing example file summary: processed 565 example files
 +++ AutoDocs: Completed processing example file links summary: processed 565 example files
CMake Error at /usr/share/cmake-3.6/Modules/GetPrerequisites.cmake:824 (message):
  /usr/bin/ldd failed: 1

Call Stack (most recent call first):
  /home/dmacumbe/EnergyPlus/cmake/ProjectMacros.cmake:196 (get_prerequisites)
  /home/dmacumbe/EnergyPlus/build/src/ExpandObjects/cmake_install.cmake:48 (fixup_executable)
  /home/dmacumbe/EnergyPlus/build/cmake_install.cmake:444 (include)


CPack Error: Error when generating package: EnergyPlus
make: *** [package] Error 1
```

**Comment by macumber** [comment]
And here is what I get from ldd (note ExpandObjects is executable and I can run it):

```
[dmacumbe@localhost build]$ ldd Products/ExpandObjects 
    not a dynamic executable
[dmacumbe@localhost build]$ Products/ExpandObjects 
ExpandObjects Started.
ExpandObjects Finished with Error(s). Time:     0.001
```

**Pull request merged**
