### PR TITLE
Fix #5982 - add hyperlinks to classes in I/O Ref

### LINKED ISSUE #5982: Add "Hypertext" Linking for Object Names in Documentation
Issue overview
--------------
Allow clicking on any object name in the documentation to go to the InputOutputReference description of the object. PDF supports this kind of "hypertext" style of linking of terms to documentation sections.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #5982 - add hyperlinks to classes 

I've done it only inside I/O Ref, since jumping to a label in another document is trickier (and in the build folder the PDFs aren't in the same folder, as it is when E+ is installed)

I used Python to implement some logic and regexes to replace class names with a `\hyperref` link to the label of the section where its defined. The logic includes "protecting" some stuff from replacement: don't do it inside the section itself, an equation, the "outputs" section for a class (where variables are defined), and handle cases where a link might already exists, or the object is inside a `!lstinline` or `emph` or `textbf` etc.

eg:
```latex
\paragraph{Field: Dedicated Outdoor Air System Name}\label{field-dedicated-outdoor-air-system-name-2}

Enter the name of an HVACTemplate:System:DedicatedOutdoorAir object if this zone is served by a dedicated outdoor air system (DOAS).
```
becomes:
```latex
\paragraph{Field: Dedicated Outdoor Air System Name}\label{field-dedicated-outdoor-air-system-name-2}

Enter the name of an \hyperref[link-hvactemplate-system-dedicatedoutdoorair]{HVACTemplate:System:DedicatedOutdoorAir} object if this zone is served by a dedicated outdoor air system (DOAS).
```
so that you have a link to jump to the section:

image

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@jmarrec thanks for taking on this one. I think it will be very useful. Have you tested all the way to the PDFs to see if the hyperlinks are working?

**Comment by jmarrec** [comment]
@JasonGlazer I didn’t look through all the gazillion pages of the I/O ref one by one, but I tested a bunch randomly (and caught a bunch of problems iteratively). It appears to be working fine right now.
I also checked the log file, and there are two warnings about bad hyperref location but that’s because it’s pending integration of another PR of mine (I renamed one and added a section altogether).
There are also warnings about “muiltiply defined” labels but that isn’t due to one my changes (and explains why I wanted to regenerate all labels)

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I merged develop in here and resolved a ton of conflicts.  I then built the IO ref locally and clicked around a whole bunch.  This is a nice addition.  I'm going to merge it now.  Thanks @jmarrec

**Pull request merged**
