### PR TITLE
Fix VRF large predicted heating load when outdoor temperature is high

### LINKED ISSUE #10273: Zone temperature drops below setpoint even if autosized supplemental coil present
Issue overview
--------------
In the example file "US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf", when the VRF system capacity is 3000W (AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl field Rated Evaporative Capacity {W}), and the heating coil rated heating capacity is 10023W. A supplemental coil is present and autosized. The zone temperature drops below setpoint when the outdoor is above 0C. As a result, the predicted heating load (output "predicted sensible load to heating setpoint heat transfer rate") is also very large when outdoor temperature is above 0C.

image

Attempted fixing it by removing the following hardcoded limitation on the fan speed ratio.

```
     FanSpdRatioMin = min(max(OAMassFlow / Garate, 0.65), 1.0); // ensure that coil flow rate is higher than OA flow rate
```

This resolved the zone temperature problem, which also resolved the predicted heating load issue. But the fan air mass flow still do not behave as expected

image

It seems the problem is an instance of the issue #10282, where the supplemental coil is turned off at 0C.

image

After adding this field explicitly in the idf.

```
 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
    TU1,                     !- Zone Terminal Unit Name
    …    
    Coil:Heating:Electric,   !- Supplemental Heating Coil Object Type
    TU1 Supp Heating Coil,   !- Supplemental Heating Coil Name
    50,                      !- Maximum Supply Air Temperature from Supplemental Heater {C}
    ;                          !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation  <-- add this
```
The problem of zone temperature, predicted heating load, and air mass flow is resolved

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.5)
 - Version of EnergyPlus (23.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10273

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@yujiex @myoldmopar it has been 29 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Pull request closed without merging**
