### PR TITLE
Documentation Fixes - Batch 1

### LINKED ISSUE #4275: How to model AppG Supply Air Temp Reset
Would be good to add as a section to the Compliance doc.
Helpdesk Ticket 2199

### LINKED ISSUE #4299: Missing equation for relative Optical Air Mass in docs
User is asking how EnergyPlus calculates relative optical air mass (variable
 'm')? Can't seem to find the answer in the engineering reference  manual.

MJW responded
For daylighting, the calculation in the source code is

 AirMass = (1.d0-0.1d0_Elevation/1000.d0) / (SinSunAltitude + 0.15d0/(SunAltitude/DegToRadians + 3.885d0)_*1.253d0)

For the ASHRAE Clear Sky ("Tau") model, the equation is in the Engineering Reference on pdf p. 164.

 I will make a note to add the daylighting equation to the Engineering Reference.

 Mike

Helpdesk Ticket 9326
No user idf file

### LINKED ISSUE #4307: Need definition of Calculated Design Load, User Design Load, Average Number of Occupants and Nominal Number of Occupants in docs
Cannot find explanation of these terms and user is confused.

Rich says:
Calculated Design Load - load calculated by the program
 User Design Load - load calculated by the program and adjusted for user inputs (e.g. sizing factor)
 These should be the same if the sizing factor (and any other scalable inputs, I'm not sure of all possible) is 1

 Average Number of Occupants - the average number of occupants during the simulation based on the occupancy schedule
 Nominal Number of Occupants - the number of occupants based on the inputs in the people object
 These should be the same if the occupancy schedules are 1 at all times

Helpdesk Ticket 9390
No test files

### LINKED ISSUE #4414: Docs not consistent with what code is doing for "Difference Schedule"
Helpdesk Ticket 9427

Posted on: 19 May 2014 07:56 PM
I was referring to the SizingPeriod:DesignDay object, where there 
 might be "difference Schedule" usage.

 e.g. the field :Dry-Bulb Tmperature Range Modifier Type and subsequent
 field: Dry-Bulb Temperature Range Modifier Day Schedule Name

 Or Humidity Condition type and WetBulbProfileDifferenceSchedule.

 (Hopefully, these are already consistent in the SizingPeriod:DesignDay object)

 That is, where we have a "difference schedule", the Sky Temperature 
 object should follow the same rules.
 Linda 

Posted on: 19 May 2014 06:26 PM
Yes, if you confirm what I am seeing, then the documentation needs to be changed to reflect what the source code is actually doing.

 Linda responded last Tuesday with “I would want it to be consistent with the other "difference schedule" actions -- such as in the Design Day definition.”. Not sure exactly what is meant by this… I assume that the Design Day definition also has a difference schedule offset input, and she suggests that the source code for that offset be consistent with the one that I am finding in the WeatherProperty:SkyTemperature object. For example, if the equation is “Y= X - OffsetScheduleValue”, the this should be consistent for both the “Design day definition” (Linda) and the “WeatherProperty:SkyTemperature” object. It might be confusing if the equation was “Y = X + Offset” for some objects and “Y = X – Offset” for other objects.

 From: EnergyPlus Support [mailto:energyplus-support@gard.com]
 Sent: Monday, May 19, 2014 2:11 PM
 To: Don Shirey
 Subject: [EnergyPlus #9427]: WeatherProperty:SkyTemperature object

 So, it sounds like we just want to change the docs to match what the code is doing? And also need to verify what DifferenceScheduleDewPointValue value is doing as well, in object WeatherProperty:SkyTemperature.
 Mike

Posted on: 13 May 2014 09:48 PM
It sounds like you've already figured out what the code does...

 I would want it to be consistent with the other "difference schedule" actions -- such as in the Design Day definition.
 Linda 

Posted on: 12 May 2014 04:56 PM
In the IO reference, it says:

 Field: Calculation Type
 Allowable entries here are: ScheduleValue, DifferenceScheduleDryBulbValue, or DifferenceScheduleDewPointValue. In each case the following field must specify a valid
 schedule name. ScheduleValue - the values in the schedule are used as the sky temperature. DifferenceScheduleDryBulbValue - the values in the schedule are used as a
 difference to the drybulb temperature value (+values would then be greater than the drybulb temperature, -values would then be less than the drybulb temperature) for the resulting sky
 temperature value. DifferenceScheduleDewPointValue - the values in the schedule are used as a difference to the dewpoint temperature value (+values would then be greater than
 the dewpoint temperature, -values would then be less than the dewpoint temperature) for the resulting sky temperature value.

 I was trying to use the "DiffferenceScheduleDryBulbValue" type... with sky temperature 6 degrees C below the outdoor dry bulb temperature.

 I entered a Compact:schedule with value of -6, per the guidance above. However, it looks like the "Site Sky Temperature" output variable is 6C higher than the outdoor dry-bulb temperature... instead of 6C below.

 So, I changed the schedule value to +6, and the "Site Sky Temperature" output variable shows 6C below the outdoor dry-bulb temperature.

 Please see attached IDF and weather file.

 Please test and confirm my suspicion that the IO Ref text is backwards from what is actually being done in source code.... else correct me in my interpretation of the text writeup.

 Thanks,
Don Shirey

User files
in.epw
in26_Sky TempMode.idf

### LINKED ISSUE #4429: Calculation of ChillerCapFTemp for Chiller:Electric:EIR
Helpdesk Ticket 6171

Do we dare add a CR for this? The EIR chiller models have used temp SP from the start and using actual temps would required iteration.

 Since the chiller needs to know the available capacity before calculating outlet temp, the CAPFT term uses the SP as input to the curve object. No action is taken if the outlet temp does not meet the SP.

 ChillerCapFT = CurveValue(ElectricEIRChiller(EIRChillNum)%ChillerCapFT, &
 EvapOutletTempSetpoint,CondInletTemp)
 Richard Raustad on 12 July 2012 01:11 AM

Adding iteration to use actual leaving evap T would be more of an enhancement. For now, the docs should be modified to clearly state that the setpoint temp is used - I/O Ref and Engrg Ref both need this. And this is probably true for other chiller types?
 Michael J. Witte on 04 March 2014 04:53 PM

Posted on: 09 July 2012 04:49 PM
It looks like this model has always used the evaporator outlet water set point temperature to calculate CAPFT.
 'Richard Raustad

Posted on: 09 July 2012 04:44 PM
I don't know when this changed, but the CAPFT curve is evaluated at the evaporator outlet water set point temp, not the actual water temp.

 ! Get capacity curve info with respect to CW setpoint and entering condenser water temps
 ChillerCapFT = CurveValue(ElectricEIRChiller(EIRChillNum)%ChillerCapFT, &
 EvapOutletTempSetpoint,CondInletTemp)

 Your set point temp is 7C, if you change your spreadsheet to use 7, instead of column C, then the answer matches the curve ouput.

 =$R$4+$R$5_7+$R$6_(7^2)+$R$7_D7+$R$8_(D7^2)+$R$9_7_D7

 Either change the lower temp limit to 7C, or find out why the outlet water temp is falling to the minimum.

 Chiller:Electric:EIR,
 Main Chiller 1, !- Name
 5, !- Leaving Chilled Water Lower Temperature Limit {C}
 'Richard Raustad

Posted on: 09 July 2012 03:50 PM
According to the EngineeringReference P.562 (Ver. 5/24/12), it lists out the equation of "ChillerCapFTemp". I tried to use this equation to calculate ChillerCapFTemp value for Chiller:Electric:EIR, but it didn't give me the correct answer when compared with EnergyPlus output file of this value. 

 However, I can successfully calculate “ChillerEIRTemp” and “ChillerEIRPLR” according to the equations provided in the EngineeringReference.

 So I would like to ask how EnergyPlus calculates "ChillerCapFTemp", is my calculation wrong?(my calculation file is attached as “Chiller 1". In "Chiller 1 file, "Calculated CapFTemp" with purple color is my own calucation, "MAIN CHILLER 1:Chiller CapFTemp(Hourly)" is the EnergyPlus calculation value)

 Thanks!
 Pan

User files
Original_Air cooled.idf

### LINKED ISSUE #6135: Add Kiva to Acknowledgements
The origin of the Kiva algorithm is currently not shown in the Acknowledgements document. It should be added attributing Big Ladder and Neal Kruis.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #6357: Equation typo in documentation for "Chilled-Water-Based Air Cooling Coil"
Issue overview
--------------
The equation is _16.2.4_ in _Engineering Reference_ v8.8.0, under _16.2.1.4 Design Block Calculations_. The denominator in log mean enthalpy difference appears to be incorrect. It is listed as:

log((hair,in − hw,sat,out) - (hair,out − hw,sat,in))

where I believe it is supposed to be:

log((hair,in − hw,sat,out) / (hair,out − hw,sat,in))

### Details
 - EnergyPlus v8.8 documentation

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #7018: Degree sign not showing in doc PDF, standardize around siunitx
Issue overview
--------------

Package `siunitx` is already included, but `\textdegree` is used through the documentation, while `textcomp the package package that provides this `\textdegree` command` isn't actually used, so you end up with missing degree signs in the PDF.

Eg:
image

```
\paragraph{Field: Full Load Temperature Rise}\label{field-full-load-temperature-rise}

This numeric field defines the temperature rise of the windings above the ambient temperature, when the transformer is loaded at its nameplate rating. For liquid-immersed distribution transformers, the full load temperature rise usually takes the value of 65 \textdegreeC. For dry-type transformers, the temperature rise usually takes three optional values: 80, 115 and 150 \textdegreeC. This field accepts any value between the minimum (50 \textdegreeC) and the maximum (180 \textdegreeC). The default is 150 \textdegreeC.
```

We should standardize around the `siunitx` package, and I'll also implement a `\farenheit` unit.

**Edit:** In fact, to encourage/ensure usage of `siunitx`, I think we should upgrade the entire documentation to use `siunitx` rather than rely on a mixture of things (eg: "5C, 5 C, 5 °C (not sure the ° will render properly), `5$^\circ$`, etc)). This could be automated to some extent with a scripting language and regexes.

In the process, we'll define the appropriate units we need, including IP units.

### Details
Some additional details for this issue (if relevant):
 - Platform: Any
 - Version of EnergyPlus: 9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

This pull request fixes some documentation problems:

* [x] Fix #6357: update equation for Log mean enthalpy difference
* [x] Fix #6135: Add Kiva to Acknowledgements
* [x] Fix #4429: Note about Chiller:Electric:EIR CapFT being evaluated at **setpoint** LChWT in both I/O ([4429_IO](https://user-images.githubusercontent.com/5479063/47144538-f1b07b80-d2c7-11e8-947e-de95d7c8a48e.png)) and Engineering reference ([4429_Eng](https://user-images.githubusercontent.com/5479063/47144645-28869180-d2c8-11e8-8206-61f38105d96d.png))
* [x] Fix #4414: `WeatherProperty:SkyTemperature` update docs about sign convention for Calculation Type schedule (see [4414_IO](https://user-images.githubusercontent.com/5479063/47146921-5f12db00-d2cd-11e8-973b-d149ae1692cc.png))
* [x] Fix #4299: Add Optional Air Mass equation to docs (I added 7.59 and 7.60: [4299_EngRef](https://user-images.githubusercontent.com/5479063/47151969-9ab4a180-d2db-11e8-9ac1-62acd431c18c.png))
* [x] Fix #4275: I decided to put it in the Tips and Tricks and added: HW LWT Reset, ChW LWT Reset, AirLoopHVAC SAT Reset, and Cooling Tower Reset (see extract [4275_SATReset](https://user-images.githubusercontent.com/5479063/47161700-d4dd6d80-d2f2-11e8-97f5-40aa95c914fa.png))
. Added a reference to it (see [4275_Compliance](https://user-images.githubusercontent.com/5479063/47161648-becfad00-d2f2-11e8-8352-b415a6da2d8e.png)
* [x]  Fix #7018: replace \textdegree with siunitx 

* [x] Investigate and close #4307: decided to close this one after I found explanations in both the I/O and output details documents.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
Closing temporarily while I process it

**Comment by jmarrec** [comment]
Note to self: try \usepackage[math]{mathspec}

**Comment by jmarrec** [comment]
`usepackage[math]{mathspec}` indeed seems to avoid problems with siunitx. I didn't see any side effects in the PDF so I think that's ok. If not, you can revert the last commit I made

**Review by Myoldmopar — APPROVED** [review]
Changes look good on here.  Built the PDFs locally also and spot checked the changes once built in PDF.  Everything looks good, no errors or anything.  Merging.

**Pull request merged**
