### PR TITLE
Fix missing MTR output

### LINKED ISSUE #8229: Output Files Not Being Overwritten
Issue overview
--------------
The output files are not being overwritten by subsequent runs. I've dropped the terminal output from my testing here: https://gist.github.com/mitchute/fbebfdfbb092ea3a64c58e0d6d5f0702. 

To test, I took ```1ZoneUncontrolled.idf``` and ran it as a design-day only run. After tailing the CSV file, I forced an annual run and tailed the file again but am seeing the previous DD run results. Finally, I delete all of the eplus* files, run an annual simulation again, and tail the CSV file. Now the results line up with the annual run.

Maybe related to the recent PR #7904 ?

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 10.14.6)
 - Version of EnergyPlus (9.4.0 IOFreeze 908c5cedf5)
 - Unmethours link or helpdesk ticket number - None

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] ~Defect file added (list location of defect file here)~
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
 - Fixes #8229 
 - Follow on from #8236

This fixes a bug in MTR output due to wrong default in IDD and wrong stream selected for the MTR CSV file. I mistakenly put and thought `mtr` was the CSV output, not the actual MTR file, in the ResultsFramework. This addresses that mistake and the MTR file correctly outputs now.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — COMMENTED** [review]
@mbadams5 This fixes the missing mtr file, but OutputControl:Files is not working. Tried a couple variations, turning files off, and saw no change in the files produced. This was running with classic ep-launch, but I don't think that should matter. 

Test files: [8246-MeterFiles.zip](https://github.com/NREL/EnergyPlus/files/5162373/8246-MeterFiles.zip)

Also, I don't see a testfile with the new OutputControl:Files object. I'd suggest adding it to one of the *_JSON_Outputs test files and have it turn off some files and use the direct CSV option.

**Comment by Myoldmopar** [comment]
Indeed there is still some funny business to be cleaned up: https://github.com/NREL/EnergyPlus/pull/7904#issuecomment-678405079

**Comment by mjwitte** [comment]
Ah - OK so do we want to hold this PR for those fixes, or get this one in quickly to restore the mtr file?

**Comment by Myoldmopar** [comment]
Totally fine either way.  This one is an obvious improvement, so if it's ready, drop it on in and the other fixes can come later.

**Comment by mjwitte** [comment]
I'll merge this now, so it doesn't block catching mtr diffs in other branches.

**Pull request merged**
