### PR TITLE
update python plugin file to duplicate all EMS

### LINKED ISSUE #8710: PythonPluginConstantVolumePurchasedAir.py has incorrect content
Issue overview
--------------
I just installed EnergyPlus 9.5 and was looking over example files. It appears that "PythonPluginConstantVolumePurchasedAir.py" has incorrect content. The file installed has two classes: Set_Shade_Control_State and InitializeShadeControlFlags, which don't have anything to do with purchased air.,

### Details
Some additional details for this issue (if relevant):
 - Windows 10 Pro
 - EnergyPlus 9.5, downloaded 4/12/2021

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by bonnema**
Pull request overview
---------------------
 - Fixes #8710
 - Expanding python plugin example file to include all EMS.

### Pull Request Author
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new IDF included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
LGTM! I just plotted the data for this latest commit and everything looks like "small" diffs over here. I'm not sure if we actually can get to zero diffs with a case like this, but regardless, it looks like it's close enough, and (IMO) we need not spend any more effort on this.

EAST_ZONE_Zone_Predicted_Sensible_Load_to_Cooling_Setpoint_Heat_Transfer_Rate_ W (TimeStep)

**Comment by bonnema** [comment]
> LGTM! I just plotted the data for this latest commit and everything looks like "small" diffs over here. I'm not sure if we actually can get to zero diffs with a case like this, but regardless, it looks like it's close enough, and (IMO) we need not spend any more effort on this.


In developing this, I had done a little different testing; that is, compared to `EMSConstantVolumePurchasedAir.idf`. I do get zero diffs for this case, at least for the release of 9.5 on Windows ([MS Excel workbook](https://github.com/NREL/EnergyPlus/files/6930958/pypurchair.xlsx)). Another data point I guess.

**Comment by mitchute** [comment]
Interesting. I also get zero diffs testing EMSConstantVolumePurchasedAir vs. PythonPluginConstantVolumePurchasedAir. 

Old vs. new PythonPluginConstantVolumePurchasedAir is showing small diffs. Either way, I think this is very close.

**Comment by bonnema** [comment]
> Interesting. I also get zero diffs testing EMSConstantVolumePurchasedAir vs. PythonPluginConstantVolumePurchasedAir. 
> 
> 
> 
> Old vs. new PythonPluginConstantVolumePurchasedAir is showing small diffs. Either way, I think this is very close.

I'll take another look. I did remove a few objects that seemed extraneous.

**Comment by bonnema** [comment]
> > Interesting. I also get zero diffs testing EMSConstantVolumePurchasedAir vs. PythonPluginConstantVolumePurchasedAir.
> > Old vs. new PythonPluginConstantVolumePurchasedAir is showing small diffs. Either way, I think this is very close.
> 
> I'll take another look. I did remove a few objects that seemed extraneous.

After a second look, the only "extra" object I removed was:
```
EnergyManagementSystem:Sensor,
  Zone_Sensible_Heat_Rate, !- Name
  WEST ZONE,               !- Output:Variable or Output:Meter Index Key Name
  Zone Air System Sensible Heating Rate;  !- Output:Variable or Output:Meter Name
```
I don't think that would cause these small diffs.

Old PythonPluginConstantVolumePurchasedAir was half EMS, half python plugin. New PythonPluginConstantVolumePurchasedAir is all python plugin (with all EMS now removed). Maybe that is the reason for the small differences?

**Comment by mitchute** [comment]
Yeah, that's what I'm thinking. @Myoldmopar do you think this could explain the small diffs?

**Comment by Myoldmopar** [comment]
I'm not sure, but I'm not going to wait to resolve this to zero diffs for this change.  This is good.  I am going to do a quick build test with latest develop just to make sure everything is happy then merge.  Thanks @bonnema and @mitchute

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Tested locally, included running regressions on all the Python files just for fun.  The one changed file shows diffs of course. Good to go in.

**Pull request merged**
