### PR TITLE
Add a new field of Per Person Ventilation Rate Mode to AirTerminal:SingleDuct:Uncontrolled and AirTerminal:SingleDuct:Mixer

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
A new field was added to enhance both terminal units types of AirTerminal:SingleDuct:Uncontrolled and AirTerminal:SingleDuct:Mixer. The ventilation rate determined by the Outdoor Air Flow per Person input in DesignSpecification:OutdoorAir can be varied by choosing either CurrentOccupancy or DesignOccupancy in the Per Person Ventilation Rate Mode field.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [x] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
So why are we adding a new field to zone equipment instead of adding the new field to the DesignSpecification:OutdoorAir object? Then everyone would have access to that information instead of just TUs.

**Comment by mjwitte** [comment]
@rraustad Well, both approaches were discussed.  We opted for this one because it follow the precedent already present in AirTerminal:DuaDuct:VAV:OutdoorAir and it avoids confusion at the system OA controller level.  This clearly applies to just this terminal unit.  A bit ugly, yeah, but safe.

**Comment by rraustad** [comment]
OK, that makes sense. But thinking out loud, if one TU wanted to use the people schedule, doesn't that mean the OA controller would also use the schedule? I guess not but it's a little strange for the OA controller doing something different than the TU. Or if one TU wanted to use max occupancy, and another wanted to use the schedule, then what would the OA controller need to do? How would the OA controller know how much OA to bring in? Yes, this can get very messy. So worst case, the OA controller could ask each TU how much OA it needed. I guess then OK for now until we get more comfortable with how this plays out.

**Comment by rraustad** [comment]
There are no diff's with this change and the warning was already fixed. This appears to do what is expected.

**Comment by rraustad** [comment]
Reviewed and merged.

**Pull request merged**
