### PR TITLE
Add logging information from installer to diagnose future OCX issues on Windows

### PR DESCRIPTION
**Pull request by JasonGlazer**
Adding a way for the installer on Windows to keep the log of its activities so that problems with the registration of OCX files can be diagnosed in the future. This starts to address #5105 since the problems shown there were not reproducible.

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

…e added logging to installer. Does not seem to do much.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@kbenne Following some of the links you provided, I added a function to do logging on the installer but unfortunately, it only creates a small log file that says “Output folder: C:\EnergyPlusV8-6-0”. Could you please look at the code I added and see what I am missing. I think we may need to use a special build of NSIS that has logging enabled also but I am not sure how CMake installs NSIS on the computer doing Package builds. Your further guidance would be appreciated.

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte the ASIHPMixedTank test in the integration coverage test is failing but this change was limited to the installer so it is probably failing in develop also.

**Comment by mjwitte** [comment]
Yep - it's failing in develop. See #5845

**Comment by JasonGlazer** [comment]
For this to work the special "log" version of NSIS must be used. See

https://sourceforge.net/projects/nsis/files/NSIS%202/2.51/

And download the nsis-2.51-log.zip version and copy the contents into the location that NSIS is installed.

**Comment by JasonGlazer** [comment]
@kbenne Could you please look over the changes. 

@Myoldmopar  How do we get the "log" version of NSIS (see previous comment) to be using on the machine that builds the installs for release?

**Comment by mjwitte** [comment]
@JasonGlazer @Myoldmopar There's a later version 3.0 available.  Do we want that instead of 2.5?
http://nsis.sourceforge.net/Special_Builds#Advanced_logging
http://prdownloads.sourceforge.net/nsis/nsis-3.0-log.zip?download

**Comment by JasonGlazer** [comment]
@mjwitte I think there will need to be some additional transition to using NSIS 3.0 that might require some additional expertise in creating installers.

**Comment by mjwitte** [comment]
@JasonGlazer OK.  To answer @Myoldmopar 's question from the iteration call, nsis-2.51-log.zip is a standard build from NSIS.

**Comment by Myoldmopar** [comment]
@JasonGlazer Sorry about the mute button on here.  So I am open to trying a different build of NSIS, but I don't think we'll do it before the release since this issue is not a common occurrence now.  Can we just push this until right after release and try the new version of NSIS then?

**Comment by JasonGlazer** [comment]
@Myoldmopar it would probably be wise to wait until after the release to try a new version of NSIS

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 25 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Got it installed, testing a package build now: https://github.com/NREL/EnergyPlus/releases/tag/NSISLogTest1

**Comment by Myoldmopar** [comment]
OK.  So we got NSIS installed, but this branch won't build.  It looks like it is because of the changes in this branch.  I haven't done much research on this, so I'm curious.  With the logging version of NSIS do we actually need these changes or does the logging happen without these changes?  I'm going to kick off a develop tag.

**Comment by JasonGlazer** [comment]
The logging of the specific install steps require the changes.

**Comment by Myoldmopar** [comment]
OK, well I'm getting some error messages when trying to kick off the build of this branch.  I'll start in a fresh folder and try again and we'll see.

**Comment by Myoldmopar** [comment]
So it looks like CI was happy to build the develop branch with the custom NSIS installed.  Which is good.  But I'm still unable to build, with NSIS complaining about the added code in this branch, such as the variable already having been defined, etc.

**Comment by JasonGlazer** [comment]
Could you provide some more details of the NSIS complaints?

**Comment by Myoldmopar** [comment]
Here is the tail of the NSIS log:

```
WriteRegStr: HKCR\IDFEditor.expidf\shell\=open
WriteRegStr: HKCR\IDFEditor.expidf\shell\open\=Open with IDFEditor
WriteRegStr: HKCR\IDFEditor.expidf\shell\open\command\=$INSTDIR\PreProcess\IDFEditor\IDFEditor.exe %1
FunctionEnd
!define: "LVM_GETITEMCOUNT" already defined!
Error in script "C:/tmp/ep/build/_CPack_Packages/win64/NSIS/project.nsi" on line 602 -- aborting creation process
```

I'm not too familiar with NSIS, but I mean it looks like `LVM_GETITEMCOUNT` is a definition added by this PR, so it's suspicious.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by JasonGlazer** [comment]
@Myoldmopar I cannot reproduce the NSIS install log that you show.  I tried it on my existing windows 10 pro computer and on a clean Windows 8.1 VM. You are showing the install.log file that is created when installing EnergyPlus right?

**Comment by Myoldmopar** [comment]
No, that's the output from the failed package build.  I can't build a package, so I can't try to install it.

**Comment by JasonGlazer** [comment]
Mine is building fine. I just merged it with develop since it was getting kind of old. What log file specifically are you finding those problems?

**Comment by Myoldmopar** [comment]
I'll have to check, it's been a while.  But iirc, it's right in the build folder, deep where it is building the package contents.  I'll check it out again.

**Comment by JasonGlazer** [comment]
Did you copy the special nsis-2.51-log.zip files (primarily the makensis.exe file) over the file in your c:\Program Files (x86)\NSIS\ directory?

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@JasonGlazer @lgentile it has been 97 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I'll keep this branch around for now, but there's no point in leaving the PR open just for CI to nag us about it still being open.  Closing.

**Pull request closed without merging**
