### PR TITLE
Attempt VS2015 build

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview
---------------------

This PR enabled building of VS2015 for EnergyPlus

 * Currently all unit tests are passing, so it looks good
 * I am unable to verify what went right or wrong when @Myoldmopar did the manual / automated install of VS2015 on the build system
 * My investigation indicates that the likely scenario is that the automated installer was attempting to initiate Windows updates that were necessary to run VS2015 and this process was hidden from the user and appeared as a timeout
 * I will document what should have happened during the update process in a formal document.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Since we know some PRs are going to start failing to build with 2013 (thus driving this effort) should we go ahead and remove the VS2013 build configuration in this PR as well?

**Comment by lefticus** [comment]
My own intellectual curiosity would say to leave it until you see the breakage, but it's up to you.

**Comment by Myoldmopar** [comment]
@mbadams5 Since it's been so long since we last tried, do you want to just pull this into your JSON branch and let's get the conversation going again?

**Comment by Myoldmopar** [comment]
> My own intellectual curiosity would say to leave it until you see the breakage, but it's up to you.

I see the breakage [here](https://github.com/NREL/EnergyPlus/pulls?page=2&q=is%3Apr+is%3Aopen#commitcomment-20165682) in #5828 for VS2013, so I will remove 2013 with this branch, merge it into develop, and start propagating the move to 2015 to other branches.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 19 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Alllllright.  Moving to VS2015 exclusively.  Congratulations?  Merging.

**Pull request merged**
