### PR TITLE
Use local nodes for air flow network calculation 

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
1. Use local nodes for air flow network calculation
2. Tests and docs for local environmental data for urban context

### CODE REVIEW

**Comment by Myoldmopar** [comment]
It looks like https://github.com/NREL/EnergyPlus/commit/8746f3baa056ee89a2e4c37b3421a9cf79c12f55 did the trick.  Assuming it stays green as CI gets around to it, this will go in.

**Comment by Myoldmopar** [comment]
@XuanLuoLBL can you update this PR?
 - [x] Copy the description and title from the old PR into this one
 - [x] Update all PR labels/milestones to be like the old one
 - [x] Reference the old one in this description to point back to the old one so that we can get back to the original conversation if needed.
 - [x] Close the other PR **without merging**.

**Comment by xuanluo113** [comment]
@Myoldmopar Guess `8746f3b` works!

**Comment by xuanluo113** [comment]
#6227 
The original feature PR - Improving Building Energy Simulation in an Urban Context
#6263 
The orignal feature update PR - Use local nodes for air flow network calculation

**Comment by xuanluo113** [comment]
@Myoldmopar Done.

**Comment by Myoldmopar** [comment]
This is good to go in.  Merging.

**Pull request merged**
