### PR TITLE
Constant COP chiller sizing is broken and leads to zero chiller energy consumption #6010

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
Issue #6010, #4991  

Fixed water cooled Constant COP chiller and associated cooling tower autosizing problem that lead to zero chiller energy consumption, and in some cases negative heat transfer on both sides causing extreme loop temperatures.

Now chillers: Chiller:ConstantCOP, Chiller:Electric, Chiller:CombustionTurbine, and Chiller:EngineDriven properly report autosized and user specified design variables.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [x] Argument types
   - [x] If any virtual classes, ensure virtual destructor included, other things
 - n/a IDD changes:
 - n/a If new idf included, locally check the err file and other outputs
 - n/a Documentation changes in place
 - n/a ExpandObjects changes?
 - n/a If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Nigusse** [comment]
@mjwitte  The sizing problem in this bug issue is that three autosizing flag variables were never set for this chiller type, so autosizing of chiller nominal capacity, Evaporator water vol flow rate, and condenser water vol flow rate could not be performed. I set the flags [here](https://github.com/NREL/EnergyPlus/blob/6010_ConstantCOPChiller/src/EnergyPlus/PlantChillers.cc#L1879-L1881), [here](https://github.com/NREL/EnergyPlus/blob/6010_ConstantCOPChiller/src/EnergyPlus/PlantChillers.cc#L1908-L1910), and [here](https://github.com/NREL/EnergyPlus/blob/6010_ConstantCOPChiller/src/EnergyPlus/PlantChillers.cc#L1915-L1917). This has resolved the issue in this defect file and results are as expected. Will investigate issue #4991.

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar Nominal capacity, evaporator and condenser loops water flow rates autosizing issues for Constant COP Chiller are also resolved. Cooling tower connected to water cooled Constant COP Chillers are now sized correctly. Defect file was showing all zeros for cooling tower because of zero flow rate in the chiller condenser loop. Tested the defect idfs of issue #4991. This fix also resolved the sizing problems of issue #4991 and the constant cop chiller operations are now as expected.  We can close bug issue #4991 via this fix.

**Comment by mjwitte** [comment]
Tested this with user file from helpdesk ticket 11886 and the fix works.  But, this revealed that the transition rules for the cooling towers are incorrect.  Will check in a fix for that here along with updating this to latest develop.

**Comment by mjwitte** [comment]
@Nigusse 
The problems noted in the issues have been fixed.  But there are still a couple of problems.  Test file 4991\Chillers V8.7.idf has two const COP chillers with a hard size for capacity, and autosized water flow rates.  Here is the eio output:
```
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Nominal Capacity [W], 80000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, User-Specified Nominal Capacity [W], 80000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Design Chilled Water Flow Rate [m3/s], 8.69937E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Nominal Capacity [W], 600000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Nominal Capacity [W], 600000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Chilled Water Flow Rate [m3/s], 8.69937E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Condenser Water Flow Rate [m3/s], 3.45975E-002
```
Two problems, 
1. The Design Capacity and the User Specified Capacity are the same value.  If you fully autosize these chillers, the design capacity is quite different.
2. Chiller 1 above is not reporting the Condenser water flow rate, but Chiller 2 is.  I've added a couple of other flavors of this defect file.
*MJW - Duh-Chiller 1 is air-cooled - so there is no condenser water*

This is the current output if all of the value (capacity, evap flow and cond flow) are hard-sized:
```
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Nominal Capacity [W], 80000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, User-Specified Nominal Capacity [W], 80000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Design Chilled Water Flow Rate [m3/s], 8.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, User-Specified Design Chilled Water Flow Rate [m3/s], 8.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Nominal Capacity [W], 600000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Nominal Capacity [W], 600000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Chilled Water Flow Rate [m3/s], 6.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Design Chilled Water Flow Rate [m3/s], 6.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Condenser Water Flow Rate [m3/s], 3.00000E-002
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Design Condenser Water Flow Rate [m3/s], 3.00000E-002
 Component Sizing Information, CondenserLoop, CONDENSER LOOP, Maximum Loop Flow Rate [m3/s], 3.00000E-002
```
Note how the condenser loop max flow is equal to the chiller 2 condenser water flow rate.  Should be bigger - that says that condenser water flow is being skipped entirely(?) for the first chiller.

**Comment by Nigusse** [comment]
@mjwitte Did you add/commit the new defect idf to the defect folder? I do not see them.

**Comment by mjwitte** [comment]
Yes, look in 4991.

**Comment by Nigusse** [comment]
Got it. Thanks. I was looking in #6010.

**Comment by Nigusse** [comment]
@mjwitte Below are results for all hardsized defect file:

Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Nominal Capacity [W], 131482.63876
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, User-Specified Nominal Capacity [W], 80000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, Design Size Design Chilled Water Flow Rate [m3/s], 8.54250E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.1, User-Specified Design Chilled Water Flow Rate [m3/s], 8.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Nominal Capacity [W], 131482.63876
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Nominal Capacity [W], 600000.00000
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Chilled Water Flow Rate [m3/s], 8.54250E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Design Chilled Water Flow Rate [m3/s], 6.00000E-003
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, Design Size Design Condenser Water Flow Rate [m3/s], 3.45975E-002
 Component Sizing Information, Chiller:ConstantCOP, CHILLER NO.2, User-Specified Design Condenser Water Flow Rate [m3/s], 3.00000E-002
 Component Sizing Information, CondenserLoop, CONDENSER LOOP, Maximum Loop Flow Rate [m3/s], 3.00000E-002

**Comment by Nigusse** [comment]
Now the autosized and user specified values are different.  This is caused by incorrect setting of a local variables for the temp sized variables when the field is not autosized. This is corrected now.

For the second case, if the plant loop maximum vol flow rate is hard sized, then the design plant sizing maximum vol flow rate is set to the minimum of the two [here](https://github.com/NREL/EnergyPlus/blob/6010_ConstantCOPChiller/src/EnergyPlus/PlantManager.cc#L3232-L3236).

**Comment by Nigusse** [comment]
@mjwitte I pushed the branch with the fix.  I am suspicious that all the other chillers will have the same problem by looking at the sizing code but I have not tested them.

**Comment by Nigusse** [comment]
The differences in 10 example files are in variables Design Size Nominal Capacity and Design Size Design Chilled Water Flow Rate. The diffs are expected. Previously the user specified values were reported as Design value.

**Comment by Nigusse** [comment]
@mjwitte Created defect files and confirmed that chillers: Chiller:Electric, Chiller:CombustionTurbine, and Chiller:EngineDriven have the same two problems that you found in Constant COP chiller. I am addressing them now.

**Comment by Nigusse** [comment]
Diffs are expected in EIO file if the example files have autosized field in the four chiller objects.

**Comment by Nigusse** [comment]
Fixed unit tests: EngineDrivenChiller_HeatRecoveryAutosizeTest and GTChiller_HeatRecoveryAutosizeTest failed while addressing issues #6010 and #4991.  This is ready for review.

**Pull request merged**
