### PR TITLE
Fixed Capitalization Errors in IDD

### PR DESCRIPTION
**Pull request by rglazer2**
Addresses #4856

### CODE REVIEW

**Comment by mjwitte** [comment]
@rglazer2 Did you check other curve types for similar inconsistencies?

**Comment by rglazer2** [comment]
@mjwitte Yes, I looked through the other object-lists and only found the
one other inconsistency that I fixed.

**Comment by Myoldmopar** [comment]
I generated a list of the `\reference`s and the `\object-list`s in the idd.  Here are the remaining differences:

References not in object-list:
- AirflowNetwork
- GapVentTypeName
- ITEEquipmentNames

Object-lists not in references:
- MultivariateTables (There is a MultiVariateTables in both lists, note case of the v)

I would say we want to fix the MultiVariate table one.  The others might be out of scope unless @mjwitte wants to simply remove those orphan `\reference`s.

**Comment by mjwitte** [comment]
@Myoldmopar Is that a script that we can keep around?  These things could creep in at any point.
The "Airflownetwork" one is a typo here.  Note the space before LinkageNames.

```
AirflowNetwork:Distribution:Linkage,
      \min-fields 4
      \memo This object defines the connection between two nodes and a component.
 A1 , \field Name
      \required-field
      \type alpha
      \note Enter a unique name for this object.
      \reference AirflowNetwork LinkageNames
```

The GapVentTypeName reference is not valid, should be deleted (the object has a reference earlier in its name field).

```
  A3 , \field Gap Vent Type
       \required-field
       \type choice
       \key Sealed
       \key VentedIndoor
       \key VentedOutdoor
       \reference GapVentTypeName
```

\reference ITEEquipmentNames should be deleted if it's the only unused reference in the entire IDD.  One can be added later if needed.

@rglazer2 Please go ahead an make these fixes.

**Comment by Myoldmopar** [comment]
Script is just bash commands...

```
$ grep '\\object-list' idd/Energy+.idd.in  | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | cut -d " " -f 2 | sort | uniq > /tmp/objs
$ grep '\\reference' idd/Energy+.idd.in  | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | cut -d " " -f 2 | sort | uniq > /tmp/refs
$ diff /tmp/objs /tmp/refs
```

**Comment by mjwitte** [comment]
@rglazer2 @Myoldmopar Actually, AirflowNetworkLinkageNames is never used, so that reference can be deleted.

**Comment by Myoldmopar** [comment]
@rglazer2 @mjwitte Just a reminder that this pull request is ready to go in after those relatively simple changes mentioned are addressed.

**Comment by rglazer2** [comment]
@Myoldmopar This should be ready to go now.

**Pull request merged**
