### PR TITLE
Add configure option to help debug unit tests

### LINKED ISSUE #4741: Unit tests are difficult to debug
Unit tests are difficult to debug because the test runner traps assertions and exceptions and continues on instead of stopping and unwinding the stack.  This is good for automated tests, but not so good for developers who are debugging.  Please add a configure option to control this behavior.

### PR DESCRIPTION
**Pull request by kbenne**
There is now a new CMake configure option called ENABLE_GTEST_DEBUG_MODE
that is defaulted to ON.  When on this will make gtest stop and unwind
on assertions and exceptions.

The decent_ci yamls configure this option OFF for automated testing.

fix #4741

### CODE REVIEW

**Comment by kbenne** [comment]
@mjwitte and @Myoldmopar this has been spurred on by our conversation over on https://github.com/NREL/EnergyPlus/pull/4713#issuecomment-75288848.  Here is the PR for a proper solution that will do what we talked about by default.  So no more setting flags in the IDE.  

I'm assigning to @lefticus because it has a relationship to the decent_ci.

**Comment by kbenne** [comment]
@mjwitte and @EnergyArchmage but maybe one of you can give it a test drive with your use cases on behalf of @lefticus.  Still need his eyes on the changes to decent yaml.

**Comment by EnergyArchmage** [comment]
@kbenne @lefticus I merged this into my branch and gave it a test drive.  I can confirm it works in the same way as passing the arguments, on my windows box.

**Comment by kbenne** [comment]
@lefticus we good?

**Pull request merged**
