### PR TITLE
Refactor HeatBalanceIntRadExchange to Use Eigen

### PR DESCRIPTION
**Pull request by drewyh**
Pull request overview
---------------------
This pull request refactors FixViewFactors and CalcScriptF in HeatBalanceIntRadExchange to use Eigen in place of for loops and custom implemented matrix inverse calculation. This simplifies the code by outsourcing the looping and linear algebra calculations to the Eigen library, making it somewhat clearer what the code is doing. It may also improve the performance of the code with Eigen's optimisations.

Local testing showed diffs in the last few decimal places of eso files.

### To-Do List
 - [ ] Revisit the solutions formulated in the code to remove expensive operations (e.g. explicitly finding the matrix inverse). If it is only needed to solve a linear equation, this can be done more efficiently.

### Work Checklist
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus

### Review Checklist
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I'm definitely going to have to spend some time in here to make sure I understand all the changes, but I will say this makes the code look so much nicer.  Thanks for this!

**Comment by nrel-bot-2** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 26 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 60 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@drewyh I don't have any availability to dig in and review this.  If you'd like to contribute this, we'll need to start with a proposal and design document that should be approved before we inspect the code, and we'll need engineering reference changes and unit tests to accompany those changes.  If you have availability to work on this through our regular workflows, that's awesome.  If not, no big deal.  I'm going to close this PR however, so our CI system stops warning about it being outdated.

**Pull request closed without merging**
