### PR TITLE
Enable c++17 mode

### LINKED ISSUE #8103: compiling energyplus with c++14
Issue overview
--------------
I am trying to add HELICS as an external interface into energyplus.

### Details
I added helics header files in the externalinterface.cc file and tried to build energyplus with HELICS. The helics header file would reference some third party library where single quotes are used as number separators thus require c++14 to compile. However, when I use c++14, there would be error in energyplus so the build process stops. I am wondering if there's a way to build energyplus with c++14.

I also opened an issue here [issue#1440](https://github.com/GMLC-TDC/HELICS/issues/1440#issue-644197682)

Thank you very much!

### PR DESCRIPTION
**Pull request by lefticus**
This is a test to see about building with C++17 mode on the CI and what performance impact (or not) there might be in moving to `std::string_view` for common parameters and values for things like `RoutineName`

**Not ready for merging yet** (probably)

Fix #8103

### CODE REVIEW

**Comment by lefticus** [comment]
@bonnema can you test this branch on the clusters/computers you care about and see what problems (if any) you have?

**Comment by mbadams5** [comment]
@lefticus I will push up an update to the JSON library here in a little bit, which should fix the build issues

**Comment by bonnema** [comment]
@lefticus I was able to build this on Eagle - any particular tests you're looking for?

**Comment by lefticus** [comment]
> @lefticus I was able to build this on Eagle - any particular tests you're looking for?

Just wanted to make sure it built in environments you cared about. We're experimenting with moving from C++11 to C++17.

**Comment by lefticus** [comment]
@mbadams5 it looks like the move to C++17 should be relatively painless. We'd still have to be careful - MSVC 2017 doesn't support all of C++17. And my move to string_view for some things seems to be showing a 0.25% perf improvement on the dashboard. Nothing to write home about, but interesting to see regardless.

re: @Myoldmopar

**Comment by lefticus** [comment]
We may need to update gtest for the sake of newer C++ standard on MSVC it seems.`

> > @lefticus I was able to build this on Eagle - any particular tests you're looking for?
> 
> Just wanted to make sure it built in environments you cared about. We're experimenting with moving from C++11 to C++17.

FYI:

`$ cat /etc/redhat-release`
`CentOS Linux release 7.4.1708 (Core)`
`$ ml list`

`Currently Loaded Modules:`
`  1) conda/5.3   2) cmake/3.12.3   3) gcc/8.2.0`

`$ conda list -n py`
`# packages in environment at /home/ebonnema/.conda-envs/py:`
`#`
`# Name                    Version                   Build  Channel`
`_libgcc_mutex             0.1                        main`
`blas                      1.0                         mkl`
`bottle                    0.12.18                  pypi_0    pypi`
`ca-certificates           2020.1.1                      0`
`certifi                   2019.11.28               py36_0`
`chardet                   3.0.4                    pypi_0    pypi`
`colorama                  0.4.3                    pypi_0    pypi`
`conan                     1.23.0                   pypi_0    pypi`
`deprecation               2.0.7                    pypi_0    pypi`
`distro                    1.1.0                    pypi_0    pypi`
`fasteners                 0.15                     pypi_0    pypi`
`future                    0.18.2                   pypi_0    pypi`
`glob3                     0.0.1                    pypi_0    pypi`
`gmp                       6.1.2                h6c8ec71_1`
`idna                      2.9                      pypi_0    pypi`
`intel-openmp              2019.4                      243`
`jinja2                    2.11.1                   pypi_0    pypi`
`libedit                   3.1.20181209         hc058e9b_0`
`libffi                    3.2.1                hd88cf55_4`
`libgcc-ng                 9.1.0                hdf63c60_0`
`libgfortran-ng            7.3.0                hdf63c60_0`
`libstdcxx-ng              9.1.0                hdf63c60_0`
`markupsafe                1.1.1                    pypi_0    pypi`
`mkl                       2019.4                      243`
`mkl_fft                   1.0.12           py36ha843d7b_0`
`mkl_random                1.0.2            py36hd81dba3_0`
`monotonic                 1.5                      pypi_0    pypi`
`ncurses                   6.1                  he6710b0_1`
`node-semver               0.6.1                    pypi_0    pypi`
`numpy                     1.16.4           py36h7e9f1db_0`
`numpy-base                1.16.4           py36hde5b4d6_0`
`openssl                   1.1.1e               h7b6447c_0`
`packaging                 20.3                     pypi_0    pypi`
`pandas                    0.24.2           py36he6710b0_0`
`patch-ng                  1.17.2                   pypi_0    pypi`
`pip                       19.1.1                   py36_0`
`pluginbase                0.7                      pypi_0    pypi`
`pyjwt                     1.7.1                    pypi_0    pypi`
`python                    3.6.8                h0371630_0`
`python-dateutil           2.8.0                    py36_0`
`pytz                      2019.1                     py_0`
`pyyaml                    5.3.1                    pypi_0    pypi`
`readline                  7.0                  h7b6447c_5`
`requests                  2.23.0                   pypi_0    pypi`
`ruby                      2.5.1                h7fb2391_0`
`setuptools                41.0.1                   py36_0`
`six                       1.12.0                   py36_0`
`sqlite                    3.29.0               h7b6447c_0`
`tk                        8.6.8                hbc83047_0`
`wheel                     0.33.4                   py36_0`
`xz                        5.2.4                h14c3975_4`
`yaml                      0.1.7                had09818_2`
`zlib                      1.2.11               h7b6447c_3`

**Comment by bonnema** [comment]
> > > @lefticus I was able to build this on Eagle - any particular tests you're looking for?
> > 
> > 
> > Just wanted to make sure it built in environments you cared about. We're experimenting with moving from C++11 to C++17.
> 
> FYI:
> 
> `$ cat /etc/redhat-release`
> `CentOS Linux release 7.4.1708 (Core)`
> `$ ml list`
> 
> `Currently Loaded Modules:`
> ` 1) conda/5.3 2) cmake/3.12.3 3) gcc/8.2.0`
> 
> `$ conda list -n py`
> `# packages in environment at /home/ebonnema/.conda-envs/py:`
> `#`
> `# Name Version Build Channel`
> `_libgcc_mutex 0.1 main`
> `blas 1.0 mkl`
> `bottle 0.12.18 pypi_0 pypi`
> `ca-certificates 2020.1.1 0`
> `certifi 2019.11.28 py36_0`
> `chardet 3.0.4 pypi_0 pypi`
> `colorama 0.4.3 pypi_0 pypi`
> `conan 1.23.0 pypi_0 pypi`
> `deprecation 2.0.7 pypi_0 pypi`
> `distro 1.1.0 pypi_0 pypi`
> `fasteners 0.15 pypi_0 pypi`
> `future 0.18.2 pypi_0 pypi`
> `glob3 0.0.1 pypi_0 pypi`
> `gmp 6.1.2 h6c8ec71_1`
> `idna 2.9 pypi_0 pypi`
> `intel-openmp 2019.4 243`
> `jinja2 2.11.1 pypi_0 pypi`
> `libedit 3.1.20181209 hc058e9b_0`
> `libffi 3.2.1 hd88cf55_4`
> `libgcc-ng 9.1.0 hdf63c60_0`
> `libgfortran-ng 7.3.0 hdf63c60_0`
> `libstdcxx-ng 9.1.0 hdf63c60_0`
> `markupsafe 1.1.1 pypi_0 pypi`
> `mkl 2019.4 243`
> `mkl_fft 1.0.12 py36ha843d7b_0`
> `mkl_random 1.0.2 py36hd81dba3_0`
> `monotonic 1.5 pypi_0 pypi`
> `ncurses 6.1 he6710b0_1`
> `node-semver 0.6.1 pypi_0 pypi`
> `numpy 1.16.4 py36h7e9f1db_0`
> `numpy-base 1.16.4 py36hde5b4d6_0`
> `openssl 1.1.1e h7b6447c_0`
> `packaging 20.3 pypi_0 pypi`
> `pandas 0.24.2 py36he6710b0_0`
> `patch-ng 1.17.2 pypi_0 pypi`
> `pip 19.1.1 py36_0`
> `pluginbase 0.7 pypi_0 pypi`
> `pyjwt 1.7.1 pypi_0 pypi`
> `python 3.6.8 h0371630_0`
> `python-dateutil 2.8.0 py36_0`
> `pytz 2019.1 py_0`
> `pyyaml 5.3.1 pypi_0 pypi`
> `readline 7.0 h7b6447c_5`
> `requests 2.23.0 pypi_0 pypi`
> `ruby 2.5.1 h7fb2391_0`
> `setuptools 41.0.1 py36_0`
> `six 1.12.0 py36_0`
> `sqlite 3.29.0 h7b6447c_0`
> `tk 8.6.8 hbc83047_0`
> `wheel 0.33.4 py36_0`
> `xz 5.2.4 h14c3975_4`
> `yaml 0.1.7 had09818_2`
> `zlib 1.2.11 h7b6447c_3`

`

**Comment by mbadams5** [comment]
@lefticus I updated gtest to the latest version (1.10.0) in a VM but ran into issues with duplicate cmake targets for gmock. I kludged a solution that got past that issue, but I am running into issues with [std::unary_function](https://github.com/NREL/EnergyPlus/blob/185e20e71c38982ae12f355ab950587cc20caa7f/src/EnergyPlus/DataRuntimeLanguage.hh#L490) and [boost 1.61.0 contained within third_party/kiva-ep.](https://github.com/NREL/EnergyPlus/tree/185e20e71c38982ae12f355ab950587cc20caa7f/third_party/kiva-ep/vendor) There might be other lurking issues once these first build errors are solved. I am not going to push up my changes since they are kludgy.

**Comment by lefticus** [comment]
@mbadams5 might be simplest to just hack gtest then, until we are ready to update *all* of the dependencies. This should be easy to do, theoretically, I just need to tell it to not use TR1 in MSVC.

I'll look at that shortly.

**Comment by mbadams5** [comment]
@lefticus, those other issues I pointed out will still be there, even if you hack gtest. I do think it is useful to update the gtest version and maybe 1.8.1 will work better than 1.10.0.

**Comment by lefticus** [comment]
@mbadams5 I see - I misunderstood that those other problems were a cascade from updating gtest.

**Comment by nrel-bot-3** [comment]
@lefticus @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@lefticus @mbadams5 do either of you have interest in continuing pushing on this PR?  We have a new issue that would be elegantly solved if we could use C++17's File System, but we can do our own fix if needed.  Just wondering which path to go down.

**Comment by nrel-bot-3** [comment]
@lefticus @lgentile it has been 28 days since this pull request was last updated.

**Comment by jmarrec** [comment]
Any updates on this?

I found this PR **after** I enabled C++17 mode already, by only setting the CMAKE_CXX_STANDARD and changing a few lines in compiler flags + patching DOJ (less elegantly than @mbadams5). (That compiled fine on gcc 7).

**Comment by nrel-bot-3** [comment]
@lefticus @lgentile it has been 28 days since this pull request was last updated.

**Comment by lefticus** [comment]
#8355 gets C++17 mode working, so this PR and associated branch can be deleted.

**Pull request closed without merging**
