### PR TITLE
Fix EMS actuators for dual temperature setpoints

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Fix for issue #5255. 

Also some valuable clear_state changes for OutputReportTabular.  and RuntimeLanguageProcessor.

### CODE REVIEW

**Comment by nmerket** [comment]
From what I'm told this fixes #5294 as well.

**Comment by mjwitte** [comment]
@EnergyArchmage Merged this up to current develop and then made a test file to confirm the fix based on EMSReplaceTraditionalManagers_LargeOffice.idf which revealed some incorrect node names in that example file.  Those are fixed here. No impact on results, because those particular setpoints aren't ever used, but it was confusing.

**Comment by mjwitte** [comment]
@EnergyArchmage Also added fix for unit test failure when run all together.  Will merge once this all comes back green.

**Comment by mjwitte** [comment]
Mac CI has not reported yet, but prior Mac CI reports were clean, so merging this.

**Pull request merged**
