### PR TITLE
Add siunitx macros and change defaults

### PR DESCRIPTION
**Pull request by drewyh**
Pull request overview
---------------------
This PR adds some unit macros as helpers for documentation. It also changes the default mode so that negative exponents are not used.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] ~~If defect, results of running current develop vs this branch should exhibit the fix~~
 - [ ] CI status: all green or justified
 - [ ] ~~Performance: CI Linux results include performance check~~
 - [ ] ~~Unit Test(s)~~
 - ~~C++ checks:~~
   - [ ] ~~Argument types~~
   - [ ] ~~If any virtual classes, ensure virtual destructor included, other things~~
 - ~~IDD changes:~~
   - [ ] ~~Verify naming conventions and styles, memos and notes and defaults~~
   - [ ] ~~Open windows IDF Editor with modified IDD to check for errors~~
   - [ ] ~~If transition, add to input rules file for interfaces~~
   - [ ] ~~If transition, add transition source~~
   - [ ] ~~If transition, update idfs~~
 - [ ] ~~If new idf included, locally check the err file and other outputs~~
 - [ ] Required documentation updates?
 - [ ] ~~ExpandObjects changes?~~
 - [ ] ~~If output changes, including tabular output structure, add to output rules file for interfaces~~

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by jmarrec** [comment]
I'm just seeing this PR.

Just FYI @drewyh I also added a few things for siunitx in #7015 : https://github.com/NREL/EnergyPlus/pull/7015/files#diff-4214edae9d28b8f880a5c074d667b898R80

Mostly adding a `\fahenheit` unit (even though it's a bit weird to call something with SI and °F in the same command `\SI{10}{\fahrenheit}`), and more importantly overloading the `\degree` one since it wasn't showing. 

In discussing with the devs on https://github.com/josephwright/siunitx/issues/351 it's been suggested that requiring `mathspec` with the option `math` as in `\usepackage[math]{mathspec}` would fix it, and indeed it does, but I'm not sure what other implications that would have: I couldn't find any in looking through the docs. Do you have an opinion on this please?

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@drewyh @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@drewyh @lgentile it has been 28 days since this pull request was last updated.

**Comment by jmarrec** [comment]
This has already been functionally merged in develop in https://github.com/jmarrec/EnergyPlus/commit/de666f9b746b9fe8f9529bd991e004685b94c583

**Comment by jmarrec** [comment]
Thank you @drewyh! This already made it into develop.

**Pull request closed without merging**
