### PR TITLE
Initial implementation to simulate pets in EnergyPlus

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - Implements the capability to simulate pets in similar fashion to people and other internal gains

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
Ha, haha. But seriously... I'm working on a chicken barn modeling project now, so maybe there's something here :)

**Review by nealkruis — APPROVED** [review]
Probably needs some differentiation for metabolic rates of ectotherms, but I don't want that to hold this up.

**Comment by Myoldmopar** [comment]
Anyone have a good reference for equivalent units of `clo` for different fur types and lengths?

**Comment by shorowit** [comment]
Finally! [This guy](https://unmethours.com/question/31745/how-can-i-assign-the-sensible-heat-provided-by-the-chickens-in-openstudio/) is going to be very happy.

**Comment by shorowit** [comment]
And [this guy](https://unmethours.com/question/32265/shading-in-openstudio/) too. Edit: Apparently it's the same person.

**Comment by dareumnam** [comment]
🤣😂😁

**Comment by amirroth** [comment]
> Anyone have a good reference for equivalent units of `clo` for different fur types and lengths?

Gives a whole new meaning to "yak shaving". @Myoldmopar I applaud your commitment to this bit.

**Comment by Myoldmopar** [comment]
> Gives a whole new meaning to "yak shaving". @Myoldmopar I applaud your commitment to this bit.

Thanks.  I had an alternative topic I wanted to do, but it would've taken more than a 30 minute investment...  This one won't rise to the level of the [Great Gmail April Fools Double Hoax](https://web.archive.org/web/20150709114953/http://techland.time.com/2013/04/01/google-april-fools/), but maybe there is some **very** low level of seriousness around this topic.  I actually thought about just implementing this as a Python Plugin example where we actuated the People object using custom equations and stuff for animals.

**Pull request closed without merging**
