### PR TITLE
Corrected surface convection calculation with AirRef ZoneSupplyAirTemp

### LINKED ISSUE #5905: ZoneHVAC:LowTemperatureRadiant:VariableFlow array bounds error
## Issue overview

While debugging for a different issue, this use file tripped on an array bounds error in the ZoneHVAC:LowTemperatureRadiant:VariableFlow model.  The first radiant system is heating-only, and `HydrRadSys( RadSysNum ).CoolingSystem=false` as it should, but it's getting to [this block](https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/src/EnergyPlus/LowTempRadiantSystem.cc#L5102-L5106) which then tries to access data for Node(0).  `OperatingMode` shouldn't equal `CoolingMode` at this point if the system can't cool.

Need to check logic for both cooling and heating operation for both the variable flow and constant flow radiant systems to be sure that CoolingMode is never set when CoolingSystem=false, likewise for heating.
### Details

Some additional details for this issue (if relevant):
- Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket number 11490 (but this is not related to the user's original question)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added to EnergyPlusDevSupport\DefectFiles
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
Addresses #5906. The changes in ZoneTempPredictorCorrector corrected surface convection load calculation when TAirRef = ZoneSupplyAirTemp. The existing surface load calculation was treated similar to internal gain. When the supply air temperature is higher than the surface temperature, the negative item made zone air temperature drops at every time step. Eventually, zone air temperature was very low to cause severe errors in psy functions. 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [x] Argument types
   - [x] If any virtual classes, ensure virtual destructor included, other things
 - n/a IDD changes:
 - n/a If new idf included, locally check the err file and other outputs
 - n/a Documentation changes in place
 - n/a Changed docs build successfully
 - n/a ExpandObjects changes?
 - n/a If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 Does this PR address #5905 *and* #5906?

**Comment by lgu1234** [comment]
@mjwitte Yes. It covers both.

**Comment by mjwitte** [comment]
Now I see there is PR #5993 which fixes #5905.  So, once that one drops in, then this one will fix only #5906.

**Comment by lgu1234** [comment]
@mjwitte The main reason to use the fix of #5905 is a pre-requirement to fix #5906, as you mentioned.

**Comment by mjwitte** [comment]
See [comments](https://github.com/NREL/EnergyPlus/issues/5906#issuecomment-283092813) in issue thread for 5906.

**Pull request merged**
