### PR TITLE
Row major with vectorization

### PR DESCRIPTION
**Pull request by Myoldmopar**
Making a pull request out of this for easier conversation.

### CODE REVIEW

**Comment by mbadams5** [comment]
@amirroth 

I compiled the code and output the assembly code on my Ubuntu 14.04 VM using GCC. For everyone's reference, I had to use either Release (-O3) build or I had to supply these flags '-ftree-vectorize -ftree-slp-vectorize'. I also output the assembly code for HeatBalanceIntRadExchange.cc using Develop branch.

Comparing the two generated assembly codes, it seems like you gained 1 or 2 more vectorized loops. I didn't test the performance impact of these vectorizations. I think this is a great first step towards vectorizing more of E+ code, however, I do have some concerns.

First, this code uses builtins to tell the compiler to assume data is aligned. I know C++11 added features around alignment so maybe those could be used instead for more portable code [(std::align)](http://en.cppreference.com/w/cpp/memory/align)?

Next, I think that if we want to pursue vectorization then we should probably favor explicit vectorization instead of auto-vectorization done by the compiler. While it is nice (and easy!) when the compiler auto-vectorizes the code, this can be prone to silently regressing to scalar if the loop changes. The problem with this is that you won't know if and when a loop falls out of vectorization. So a simple code change could have large performance impacts without you even knowing.

I might have more to discuss later, but this should hopefully get the conversation going...

Also, I think [this presentation](https://deplinenoise.files.wordpress.com/2015/03/gdc2015_afredriksson_simd.pdf) is a good primer on vectorization for people who are interested.

**Comment by amirroth** [comment]
Which code did you compile? RowMajorWithVectorization or just develop? And
which gcc version? I used 4.9. Yes, you need to build -O3 for vectorization
to happen.

I sort of agree about the builtins, but there is nothing better at this
point. std::align is only have the solution. We also need std::is_aligned.

I completely disagree about explicit vectorization. Ever done it? I have.
It's not readable or maintainable. And while I agree that code changes
could undo vectorization, the answer is documentation. With
explicit-vectorization there will be no code changes to a vectorized loop.
Ever. Good luck debugging also. General rule, anything that happens in a
single-thread (e.g., vectorization) let the compiler do, anything across
multiple threads (e.g., parallelization) do yourself. Word!

By the way, this thing is still not passing all of the tests and I am
considering reapplying it to develop. Gosh darnit!

-Amir

**Comment by mbadams5** [comment]
I compiled both RowMajorWithVectorization and develop to see the difference between the two. I used 4.8.2 so that could explain some differences in the number of vectorized loops.

What about [alignas](http://en.cppreference.com/w/cpp/language/alignas) and [alignof](http://en.cppreference.com/w/cpp/language/alignof)? From my searching, it seems to replace 

```
#ifdef __GNUC__
typedef __attribute__((aligned(16))) float aligned_block[4];
#else
typedef __declspec(align(16)) float aligned_block[4];
#endif
```

and instead can be either

```
typedef float aligned_block [4] alignas(16);

or

using aligned_block alignas(16) = float[4];
```

found [here](https://stackoverflow.com/questions/15788947/where-can-i-use-alignas-in-c11), but I still need to read into this more to see if it can replace __builtin_assume_aligned...

Humm... I see your point about not being able to change the code in an explicitly vectorized loop, at least not easily. Maybe i'll try to spend some time figuring out how to make the auto-vectorization portable in addition to explicit vectorization. :wink:

**Comment by amirroth** [comment]
alignas and alignof make what you get from GNU attributes more portable.
What they don't change is the fact that your basic data type becomes a
block of two (or four) values as opposed to just one. You need to rewrite
all of your code around that idiom--and this idiom does add overhead when
you have to access things in a non-vector way. Maybe that's fine for a
brand new project where you can plan ahead and structure everything
properly ahead of time. It might also be fine for very compartmentalized
local rewrites, but I don't think this is something that can very easily be
done automatically (e.g., by Stuart magic), and once you modify a data
structure you have to redo all the code that touches it. I would rather use
a more implicit approach that doesn't require you to do that. At least for
now.

I'm glad people are interested in vectorization, it's "free money" if you
can do it. I may also have some slides and homework assignments about
vectorization from when I used to teach. Should I distribute? :)

-Amir

**Comment by Myoldmopar** [comment]
@amirroth I'm going to close this PR on GitHub.  This doesn't modify the source code or delete the branch.  As you [mentioned](https://github.com/NREL/EnergyPlus/pull/5003#issuecomment-117183150), I'll let you delete this RMWV branch whenever you are ready.  This simply keeps @nrel-bot from chattering about this PR being out of date.  Thanks.

**Comment by amirroth** [comment]
OK.

**Pull request closed without merging**
