### PR TITLE
Fix struct name for NumTimesCalled

### PR DESCRIPTION
**Pull request by jmythms**
Pull request overview
---------------------
NumTimesCalled in Psychrometrics.cc was pointing to [PsychrometricsData](https://github.com/NREL/EnergyPlus/blob/42846a95e03cabcc18ef22f9778ca58ae6468128/src/EnergyPlus/Psychrometrics.hh#L1355) and not [PsychrometricCacheData](https://github.com/NREL/EnergyPlus/blob/42846a95e03cabcc18ef22f9778ca58ae6468128/src/EnergyPlus/PsychCacheData.hh#L120). This PR fixes it. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by amirroth** [comment]
Why were these separated into two files to begin with? Anybody know? @Myoldmopar @JasonGlazer @mjwitte?

**Comment by mjwitte** [comment]
I don't think it ever was. `Psychrometrics.hh` includes `PsychCacheData.hh` which is where `NumTimesCalled` is declared.

**Comment by mjwitte** [comment]
Oh, duh, you mean why is it declared in `PsychCacheData` in the first place?

**Comment by mjwitte** [comment]
Here's why/when. https://github.com/NREL/EnergyPlus/commit/2c112e35c73c4d4e90d77d94c37944ef918b65c9

**Comment by amirroth** [comment]
I'm saying that it doesn't really make any sense why these are two separate files. Would there be a reason for any other file to include only `PsychCacheData.hh`? The downside is creating these types of bugs. The upside is ... what?

**Comment by Myoldmopar** [comment]
My guess is that it was to get rid a circular reference to it -- or something -- and just got missed when moving it to the new location.  I doubt it was intended to keep a new copy.

**Comment by Myoldmopar** [comment]
Quick fix here, good catch @jmythms.  Merging this directly.

**Comment by jmythms** [comment]
Thank you!

**Pull request merged**
