### PR TITLE
Few doc fixes

### PR DESCRIPTION
**Pull request by Myoldmopar**
This fixes many things in the documentation; with the list here still yet to be added to:
- [x] Clean up html _title page_ content
- [x] Clean up the `PRE` content-type tags that were problematic
- [x] Clean up local (`file:///`) links in the source
- [x] Clean up lots of bad voodoo characters in the docs
- [x] Clean up lots of bad voodoo characters in the docs
- [x] Clean up lots of bad voodoo characters in the docs
- [x] Clean up lots of bad voodoo characters in the docs
- [x] Get rid of `svg.png` file extension

With a few more things to do:
- [ ] Clean up lots of bad voodoo characters in the docs (IO)
- [ ] Clean up lots of bad voodoo characters in the docs (Eng)

Because this cleans up so many thousands of bad characters, in so many lines, it will definitely wait until bug fix release is completed.  Then I will assist with merging in currently open PRs with the changes.

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Potentially obsolesced...

**Pull request closed without merging**
