### PR TITLE
Fix #7213: encode all IDF/IMF files as UTF-8, and add ci script to check encoding.

### LINKED ISSUE #7213: Wrong encoding for testfiles is making EnergyPlusRegressionTool hang
Issue overview
--------------

cf https://github.com/NREL/EnergyPlusRegressionTool/issues/32

`AirflowNetwork_MultiAirLoops.idf`, `AirflowNetwork_PressureControl.idf` both have degree signs that aren't UTF-8 encoded by latin-1.

We should correct these, and add a ci script to ensure this doesn't happen anymore.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7213: encode all IDF/IMF files as UTF-8, and add ci script to ensure this doesn't happen again.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
@Myoldmopar The mac build failure appears unrelated to this PR. Do you want me to make adjustments so you can merge or is it ok now?

**Comment by Myoldmopar** [comment]
It's definitely not related, but Mac is now working great.  Could you just bring develop into this branch to make sure the script is happy on there before we merge?

**Comment by jmarrec** [comment]
@Myoldmopar should be good to go

**Comment by Myoldmopar** [comment]
Yep, looks great.  Merging.

**Pull request merged**
