### PR TITLE
Fixed NAN problem with a horizontal door as a floor sub-surface in displacement ventilation room air model 

### PR DESCRIPTION
**Pull request by lgu1234**
## Pull request overview

Added two subsections in the Door section of the displacement ventilation room air model to handle doors with base surfaces as ceiling and floor. Addresses #5533.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things
- IDD changes: N/A

### CODE REVIEW

**Comment by lgu1234** [comment]
@mjwitte The test file was revised slightly to test NAN only. There are some issues of heating coil sizing.

**Comment by lgu1234** [comment]
@Myoldmopar Another failure is from the same machine: Win64-Windows-7-VisualStudio-12. The failed example file is HVACTemplate-5ZoneBaseboardHeat. What I have changed is one of RoomAir model only: DisplacementVent. I don't expect anything happens to this example file. Could you check it and let me know what happens.

**Comment by mjwitte** [comment]
@lgu1234 I changed the title of this.  Please confirm that it is accurate, and edit if needed.

**Comment by lgu1234** [comment]
@mjwitte I think it is a door as a surface of a floor and prefer not to use "opening". Here is my opinion:
Fixed NAN problem with a horizontal door as a floor sub-surface in displacement ventilation room air model

**Comment by mjwitte** [comment]
@lgu1234 Thanks for the clarification.  Title changed.

**Pull request merged**
