### PR TITLE
Added more error handling when it comes to converting strings into reals...

### PR DESCRIPTION
**Pull request by JasonGlazer**
....

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte I pointed this one to you since you probably do the most ExpandObjects updates these days.

**Comment by mjwitte** [comment]
Fixes #4440

**Comment by mjwitte** [comment]
@JasonGlazer So, will this silently turn it into zero?  Seems an error message would be warranted.

**Comment by JasonGlazer** [comment]
@mjwitte If you run the file that reproduces the problem, you will see that with this fix it ends up putting the string value ( "0..7" ) into the expidf file which does trigger an energyplus error. It is consistent with the way other number to string conversion errors were handled in the past.

**Comment by mjwitte** [comment]
@JasonGlazer CI tests all look good (except one small failure which has been fixed on develop).  Tested the defect file and the fix works as intended.  Merging.

**Pull request merged**
