### PR TITLE
Fix Invalid Object Type Names

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes several invalid object type names which are being passed around.
 - This is should be merged upstream of #9220 since this will cause diffs.

### CODE REVIEW

**Comment by mitchute** [comment]
@Myoldmopar @mjwitte 

The parameter estimation heat pump changes should be straightforward. Those just need to pass the full name of the object and fix the object type that's being sent to error messages.

I could use some input on the `ZoneHVAC:UnitVentilator` and `ZoneHVAC:VentilatedSlab` objects. These are appending "-OA Mixer" and "-System" to the object type name and node names in places. For example:

https://github.com/NREL/EnergyPlus/blob/4a865aa62d34e784c6a0ac3f07c433a916def8cf/src/EnergyPlus/UnitVentilator.cc#L485-L493

and here

https://github.com/NREL/EnergyPlus/blob/4a865aa62d34e784c6a0ac3f07c433a916def8cf/src/EnergyPlus/VentilatedSlab.cc#L838-L855

If I'm understanding things, there's an implicit OA mixer object that sometimes gets built up. But it's not really a standalone object, just some of the nodes doing double-duty on the parent object and pretending to be an OA mixer. I could be off in how I'm interpreting the code, so feel free to correct me.

There's also this note

https://github.com/NREL/EnergyPlus/blob/4a865aa62d34e784c6a0ac3f07c433a916def8cf/src/EnergyPlus/VentilatedSlab.cc#L726-L754

So, my question: can we get away from appending "-OA Mixer" and "-System" to these nodes and object types, or is that going to cause problems elsewhere?

**Comment by mjwitte** [comment]
> So, my question: can we get away from appending "-OA Mixer" and "-System" to these nodes and object types, or is that going to cause problems elsewhere?

@mitchute That would cause problems elsewhere with the component connection checking, node connection checking, and BND interpretation for HVAC Diagram. This is all ripe for a redesign, but it won't be a trivial exercise. Part of the problem here is inconsistent input object design. So one path forward would be to add explicit mixer objects in the input - not saying that's the best path forward.

Or it might work to add these suffixes to the object name rather than the object type - it's worth a try. As it stands now, I think everything that checks the object type is checking the combination of object type and name as a unique identifier. 

Looking more closely, VentilatedSlab is adding the suffix to both the type and name already, but Unit Ventilator is not. One downside of this approach is that the object types for these implicit sub-objects will look like it's another occurrence of the full object. Current code may not care about that, but it makes the node registry inconsistent. I suppose another option to consider is to add another component type to `DataLoopNode::NodeConnectionObjectType::` like `ImplicitOAMixer` and `ImplicitSystem`. Since this is a speparate enum for NodeConnections it shouldn't hurt anything else.

**Comment by mitchute** [comment]
Thanks, @mjwitte. 

> Part of the problem here is inconsistent input object design.

Could you elaborate? Is that across the board in general or just these two specific objects?

**Comment by mjwitte** [comment]
I meant just these two objects. 

In general, a parent object references child objects that do all of the actual work and make all of the node connections. The parent usually lists an inlet and outlet node name, but those are duplicates of the first component inlet and last component outlet nodes.
```
  ZoneHVAC:FourPipeFanCoil,
    Zone1FanCoil,            !- Name

    Zone1FanCoilAirInletNode,!- Air Inlet Node Name
    Zone1FanCoilAirOutletNode,  !- Air Outlet Node Name
    OutdoorAir:Mixer,        !- Outdoor Air Mixer Object Type
    Zone1FanCoilOAMixer,     !- Outdoor Air Mixer Name
    Fan:ConstantVolume,      !- Supply Air Fan Object Type
    Zone1FanCoilFan,         !- Supply Air Fan Name
    Coil:Cooling:Water,      !- Cooling Coil Object Type
    Zone1FanCoilCoolingCoil, !- Cooling Coil Name
    Coil:Heating:Water,      !- Heating Coil Object Type
    Zone1FanCoilHeatingCoil, !- Heating Coil Name
```

The unit ventilator is not consistent with this design, It's got three extra node names in the parent object that should come from a child OutdoorAir:Mixer object if it was like the others:
```
  ZoneHVAC:UnitVentilator,
    Zone2UnitVent,           !- Name
    Zone2UnitVentAirInletNode,  !- Air Inlet Node Name
    Zone2UnitVentAirOutletNode,  !- Air Outlet Node Name
    Zone2UnitVentOAInNode,   !- Outdoor Air Node Name
    Zone2UnitVentExhNode,    !- Exhaust Air Node Name
    Zone2UnitVentOAMixerOutletNode,  !- Mixed Air Node Name
    Fan:ConstantVolume,      !- Supply Air Fan Object Type
    Zone2UnitVentFan,        !- Supply Air Fan Name
    Coil:Heating:Water,      !- Heating Coil Object Type
    Zone2UnitVentHeatingCoil,!- Heating Coil Name
```

**Comment by mjwitte** [comment]
@mitchute I'm not sure if HVACDiagram outputs get run/checked on CI? So, you should run a UnitVentilator and the ventilated slab files locally to see if this breaks it.

**Comment by mitchute** [comment]
Thanks, @mjwitte.

I just pushed 213d29c3d0e5a410c059a100eaabca5b118a4739 which removes the suffixes from the object types but makes sure they are present on the object name. Local regression shows BND diffs but otherwise looks clean. I haven't checked the unit tests yet.

**Comment by mjwitte** [comment]
Actually I remember now from working on #9076 and #9096 that HVAC Diagram doesn't run on CI, there's no command line support for it. I started coding that up at one point but then dropped it - it requires that the output files all be flushed before trying to call any postprocessing programs.

**Comment by mitchute** [comment]
I just ran UnitVent5ZoneAuto with these changes and HVAC-Diagram ran successfully. The diagram looks OK to me 🤷‍♂️ .

[eplusout.svg.zip](https://github.com/NREL/EnergyPlus/files/7840420/eplusout.svg.zip)

**Comment by mitchute** [comment]
This is looking like I expected - some BND diffs and potentially an ERR diff or two. Feel free to have a look around and let me know if you see anything. I’ll merge it tomorrow if nothing comes up or I don’t hear from anyone.

**Pull request merged**
