### PR TITLE
Created pull request for working branch 86046200_CondenserToZone Connection.

### PR DESCRIPTION
**Pull request by Nigusse**
The code change is complete and ready for review.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Ummmm @Nigusse something went awry here with this pull request.  I'm not sure.  Let me know if you want to chat about redo-ing this...

**Comment by Nigusse** [comment]
Edwin: are you suggesting that we re-do the whole code change starting 
from the latest develop?

**Comment by jasondegraw** [comment]
@Nigusse There's a problem with your branch - the pull request is 300+ commits. It looks like some sort of rebase happened. What client are you using?

**Comment by Nigusse** [comment]
Whenever I clone a new branch to my desktop I use github but for all 
others purposes I use Tortoisegi. However, for this task I used 
Tortoisegit for cloning to a different directory.  It cloned 
successfully but merging from develop has been an issue.
So, for this task I used Tortoisegit only.

**Comment by mbadams5** [comment]
@Myoldmopar @Nigusse @jasondegraw  The issue with this branch isn't rebase or anything like that. @Nigusse is trying to merge develop into his branch instead of the other way around.

	Nigusse  wants to merge 355 commits into 86046200_CondenserToZone from develop

**Pull request closed without merging**
