### PR TITLE
Include zone equipment in night cycle manager warmup reset and fix crash when no airloops present

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Addresses #6370.  
A reset for night cycle start-stop times during warmup was added in #6285, but did not allow for the difference between availability manager data when applied to zone equipment vs air loops.  This resulted in an array bounds crash for simulations which applied the night cycle manager only to zone equipment (and possibly other combinations). This may result in small changes in warmup results when the night cycle manager is used for zone equipment.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
Initial commit adds warmup reset test to unit tests.  Expect one test to fail.

**Comment by mjwitte** [comment]
Smalls diffs as expected in ZoneSysAvailManager. Ready for review.

**Comment by mjwitte** [comment]
FYI @EnergyArchmage

**Review by Myoldmopar — APPROVED** [review]
This is great.  And awesome job with the test driven development.  Seeing the newly added test fail then showing it fixed is :+1:

**Comment by Myoldmopar** [comment]
It looks good to me.  Code changes and test are great.  CI results show very tiny magnitude diffs.  I am ready to merge.

I saw you tagged @EnergyArchmage; did you want him to look this over as well before merge?  Or literally just an FYI?

**Comment by mjwitte** [comment]
Just an FYI, because @EnergyArchmage was first to note the issue [here](https://github.com/NREL/EnergyPlus/commit/2a6f67174c4f9e6c7f3789c4c7b56513f2b223e3#r25137486)

**Pull request merged**
