### PR TITLE
Improve Transition Configuration

### PR DESCRIPTION
**Pull request by Myoldmopar**
This changes the code so that when you do a build, it automatically pulls in, and names properly, the prior and current Energy+.idd files right into the Product directory.  As well as the Report Variables...csv file.  This way as soon as you build the transition binaries, you can immediately run them right in that same directory.  If you have to transition older files, that's not covered here.  Just the latest release.

This is based on the branch of #5265, so that one will have to drop in first.  I have only tested this on Linux, but as long as it doesn't cause any failures on Mac/WIndows, it should go in easily.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar That's odd.  I'm sure the windows tests were all green a couple of hours ago.  Now the build failures?

**Comment by Myoldmopar** [comment]
Yeah, it's my fault, I just didn't see this locally so I'm not sure.

**Comment by Myoldmopar** [comment]
@mjwitte Merged develop; it should be green later this morning.

**Comment by mjwitte** [comment]
Transition_build still builds all of the old transition binaries.  Might be nice to have a cmake switch to build just the current transition.  Or two separate projects - one to build current transition, and one to build older ones?

**Comment by Myoldmopar** [comment]
I _could_.  I'm hesitant, and curious as to how strongly you would like to see that feature added here.  If we could drop this in and move on, I may have a slightly different approach that would satisfy this issue in mind.  If you feel strongly about it, just say and I'll work up a fix here.

**Comment by mjwitte** [comment]
No, that's fine to consider for later.  Haven't merged this yet 'cause linux CI still hasn't completed - taking way longer than it should.

**Comment by Myoldmopar** [comment]
Totally fine.  It looks like CI got busy with the other branches during a little transition.  It'll get to it...and now that we have @nrel-bot-2 and @nrel-bot-3 carrying some of the GitHub API per-user-limit, we should have even fewer hiccups moving forward.

**Pull request merged**
