### PR TITLE
Re-adding and completing Coil:Heating:Gas transition.

### PR DESCRIPTION
**Pull request by mitchute**
The transition for this got squished during a merge with develop. It's back, by popular demand, in all of its fantastic glory.  Addresses #5833.
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar @mitchute @nmerket Getting there.  The `Coil:Heating:Gas` object is getting transitioned to `Coil:Heating:Fuel`, but references to the coil in other objects are not getting changed.  Looks like that was never part of the original transition for the new coil type.

**Comment by Myoldmopar** [comment]
Wow, that's a great catch @mitchute.  @mjwitte any tips?  Because my inclination would be to just look for all the possible references (obvious ones like Branch and AirLoopHVAC) and find the field numbers that could contain them.    Or....since we _are_ looping over every object already...maybe we just loop over all the fields in that object and replace it if it is Coil:Heating:Gas.  💪 **Brute force** 💪 !

**Comment by Myoldmopar** [comment]
Or, yeah, you know, great catch, @mjwitte 💯 .  The comment author wasn't clear in the email, sorry.

**Comment by nmerket** [comment]
Oh right, I didn't think of that. I defer to your wise judgement, @Myoldmopar. And, yes, thanks for catching that @mjwitte.

**Comment by mjwitte** [comment]
@Myoldmopar There is precedent for that, sort of, when "Load Range Based Operation" was forked into "Cooling Load Range Based Operation and Heating Load Range Based Operation" back in the v1.0.3 transition. There might be another more recent example, but this was the first one I stumbled onto.

 [This block](https://github.com/NREL/EnergyPlus/blob/8280b7e5e1d2ed7a1b0beae2a916669d15039dde/src/Transition/CreateNewIDFUsingRulesV1_0_3.f90#L294-L314) searches the entire idf for plant and condenser operation scheme objects and replaces fields.  Note this comment:
`!  Actually going to "act" directly on the IDFRecord ... scary`
Also note that this is all done early - prior to the remaining transition steps if I'm following correctly.  I'm guessing that was done so that the revised field strings would simply flow through normally from old to new idf.  So, for this one, you could add a list of all possible objects that reference coil:heating:gas/fuel, or eliminate that part and simply cycle through every alpha field (>1) in the entire incoming idf.

**Comment by Myoldmopar** [comment]
I mean, I could imagine a fancy way, creating a map filled with objects mapping to lambda functions that would return a list of alpha index numbers that could have that field.  And then I see just looping over all the Alphas searching for any that start with Coil:Heating:Gas.  I vote for the latter.

**Comment by Myoldmopar** [comment]
OK @mjwitte @mitchute that should take care of that issue.  5ZoneAutoDXVAV transitions up fine with field name updates, branch object cleanups, heating coil fuel changes, and references to the coil cleaned up in the terminal units, branches, etc.

**Comment by mjwitte** [comment]
Tested this with a group of files that I've been using to test another fix.  Now they are all transitioning as expected.  I'm going to merge this, but I'm going to add a comment to #5805 that we need to run all of the 8.5 testfiles through transition and run them to check for any lingering issues.

**Pull request merged**
