### PR TITLE
Input Verification And Results Summary: handle "Not Part of Total" Zones correctly

### LINKED ISSUE #6350: Zone Summary does not report Lighting, People, and Plug and Process loads if zone is not part of floor area
Issue overview
--------------
I use the `Zone Summary` table for QAQC to ensure that baseline and proposed models are the same/different where expected. 

During QAQC of LEED models I noticed that an unconditioned zone incorrectly had a Lights object assigned to it in the baseline model, which the proposed model did not have. In this case the Zone Summary tables showed blanks for the Lighting, People, and Plug and Process columns, which was misleading because the baseline did in fact have a lighting power that showed up in the Energy Meters report. 

### Details
Some additional details for this issue (if relevant):
 - Windows 7
 - EnergyPlus 8.8.0
 - Unmethours link or helpdesk ticket number - NA

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #6469: Not Part of Total in IVRS report showing wrong total
Issue overview
--------------
The Zone Summary table in the Input Verification and Results Summary report on the Not Part of Total line at the bottom is showing the total of all zone areas and volumes instead of just the zones where the Zone object field Part Of Total Floor Area is set to No. The user reported this with 8.6.0 but it is still a bug in 8.8.0.

See:

https://unmethours.com/question/29610/not-part-of-total-energyplus-table/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (devsupport)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
Fix #6350 and Fix #6469: show loads even if not part of total, and calculate summary rows properly.

The pseudo code algorithm I implemented if as follows:

```
if (notPartOfTotal) {
   NotPartOfTotal += thisZoneFloorArea
} else {
  Total += thisZoneFloorArea
  if (conditioned) {
     ConditionedTotal += thisZoneFloorArea
  } else {
     UnconditionedTotal += thisZoneFloorArea
  }
}
```

meaning I consider "Conditioned/Unconditioned" subtotal rows of the "Total" one. I did discuss this with @JasonGlazer on slack (thanks!). Perhaps we should change the row header to be more explicit? 

**Edit**: I didn't change the row headers thinking it'd produce diffs, but now I realize that obviously there are already diffs...

**Before:**

6350_6469_before

**After:**

6350_3469_after

Also updated documentation in Output Details and Example to be explicit about how things are calculated.

image

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes n/a
 - [x] Required documentation updates?

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jmarrec it has been 8 days since this pull request was last updated.

**Review by mjwitte — APPROVED** [review]
Tested with the 6469 defect file which shows both issues. All looks good now. Unit tests run. Merged in current develop and removed some stray JM comments. Once CI comes back green, will merge.

**Comment by mjwitte** [comment]
@jmarrec There are some build warnings.

**Comment by mjwitte** [comment]
@Myoldmopar I can't tell for sure if the build warnings here are from these changes or something else.

**Comment by mjwitte** [comment]
Diffs are as expected now, build warnings are gone.

**Pull request merged**
