### PR TITLE
Fix #8748 - Fix broken symlink for ParametricPreprocessor on Unix

### LINKED ISSUE #8748: Symlink to ParametricPreprocessor is broken on Unix
Issue overview
--------------

image

This symlink is broken on 20.04 at least (but it should be the case on all unix systems)
The folder is called `ParametricPreprocessor`  not `ParametricPreProcessor`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Unix
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.5.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #8748 - Fix broken symlink for ParametricPreprocessor on Unix

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
I've confirmed the broken symlink. Once GH Actions comes back online, I'll merge develop into this branch and make a test build.

**Comment by mitchute** [comment]
@Myoldmopar FYI

```
[100%] Built target energyplus
Run CPack packaging tool...
CPack Error: Cannot find QtIFW compiler "binarycreator": likely it is not installed, or not in your PATH
CPack Error: Cannot initialize the generator IFW
Makefile:92: recipe for target 'package' failed
make: *** [package] Error 1
Error: Process completed with exit code 2.
```

**Comment by jmarrec** [comment]
> @Myoldmopar FYI
> 
> ```
> [100%] Built target energyplus
> Run CPack packaging tool...
> CPack Error: Cannot find QtIFW compiler "binarycreator": likely it is not installed, or not in your PATH
> CPack Error: Cannot initialize the generator IFW
> Makefile:92: recipe for target 'package' failed
> make: *** [package] Error 1
> Error: Process completed with exit code 2.
> ```

See my commit e0a164e621b729f052af071e35812f0ca33a28a1 on the FileSystem branch...

Edit: Cherry picked and put in this PR: https://github.com/NREL/EnergyPlus/pull/8774. Then merged that branch here so CI could report. I re-spawned your release build by untagging and retagging at HEAD (https://github.com/NREL/EnergyPlus/releases/tag/SymLink)

**Comment by jmarrec** [comment]
all good for Github Actions.

image

**Comment by jmarrec** [comment]
I tested the Linux 18.04 .run from the GHA:

I installed it to /usr/local/EnergyPlus-9.5.0-temp. symlink works correctly

```
$ ls -la /usr/local/bin/Pa*
lrwxrwxrwx 1 root root 89 May 19 13:10 /usr/local/bin/ParametricPreprocessor -> /usr/local/EnergyPlus-9-5-0-temp/PreProcess/ParametricPreprocessor/ParametricPreprocessor
```

**Comment by mitchute** [comment]
I've confirmed the fix on my 18.04 VM. I'm gonna merge #8774, then immediately this PR. Thanks, @jmarrec!

**Pull request merged**
