### PR TITLE
#7771 - AirLoopHVAC:UnitarySystem crashes in getting input when 'Minimum Supply Air Temperature' is 'Autosize'

### LINKED ISSUE #7771: AirLoopHVAC:UnitarySystem crashes in getting input when 'Minimum Supply Air Temperature' is 'Autosize'
Issue overview
--------------

throws

```
** Severe  ** [json.exception.type_error.302] type must be number, but is string`
```

Extract from IDD:

```
AirLoopHVAC:UnitarySystem,
  [...]
  A16, \field Use DOAS DX Cooling Coil
       \type choice
       \key Yes
       \key No
       \default No
       \note If Yes, the DX cooling coil runs as 100% DOAS DX coil.
       \note If No, the DX cooling coil runs as a regular DX coil.
       \note If left blank the default is regular dx coil.
  N2 , \field Minimum Supply Air Temperature
       \type real
       \units C
       \minimum 0.0
       \maximum 20.0
       \default 2.0
       \autosizable         <-------------------------- H E R E 
       \note When Use DOAS DX Cooling Coil is specified as Yes, Minimum Supply Air Temperature
       \note defines the minimum DOAS DX cooling coil leaving air temperature that should
       \note be maintained to avoid frost formation. This field is not autosizable when
       \note the input for Use DOAS DX Cooling Coil = Yes.
       \note When Control Type = SingleZoneVAV, enter the minimum air temperature limit for reduced fan speed.
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7771 
 - In UnitarySystem, handle one autosizable fields correctly in GetInput Add unit test for all autosizable fields

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
@jmarrac @Myoldmopar I was checking off review items and got to unit tests. I see this yet Py is certainly in my path. This is a clean build (new build folder) with Docs, unit testing and Py.

image

**Comment by Myoldmopar** [comment]
@rraustad can you reproduce that?  If you just run it again will it fail on that same unit test over and over?

**Comment by rraustad** [comment]
Hmm, unit tests ran through this time. I guess that was a fluke.

**Review by rraustad — APPROVED** [review]
Correction is good, unit test checks autosized fields.

**Pull request merged**
