### PR TITLE
Revert "Adopt the Extended Heat Index calculation in zone resilience"

### PR DESCRIPTION
**Pull request by Myoldmopar**
The develop branch hit a pretty severe runtime slow down, and it appears it was because of this.  I'm opening this PR to confirm and then we'll decide what to do.  FYI @yujiex

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Yep, check here: https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-a0f92d6fdf8a9666076dee4c916113d42225b6d0-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html#performance

This is indeed causing the big slow down.  @yujiex if you want to come up with a very quick way to fix the HI code so that it doesn't cause any slowdown, you can, but I'm likely to merge this to get a clean baseline again.

**Comment by Myoldmopar** [comment]
OK, I'm just going to merge this in.  @yujiex we can chat about strategies to get the code back in place to go in after release.  Again, if you want to find a way to get it in very quickly (today?) in a way that doesn't slow down our tests, I'm open to it.  But I want to get develop's performance cleaned back up.

**Comment by yujiex** [comment]
I will attempt to fix it today @Myoldmopar

**Comment by yujiex** [comment]
@Myoldmopar. I've tried changing the root finder to the following. The unit tests still passes. So it seems this doesn't affect the result much but limit the number of iterations to 5 (or according to user input for the HVACSystemRootFindingAlgorithm. Do you feel this could resolve the problem?

```
state.dataRootFinder->HVACSystemRootFinding.HVACSystemRootSolver = HVACSystemRootSolverAlgorithm::BisectionThenRegulaFalsi;
```

**Comment by Myoldmopar** [comment]
You are welcome to push it as a new branch with those changes made and see how CI responds.  If it's happy there, I'll do a quick additional test locally and if it's all clean and fast enough, it can surely drop right in.

**Comment by yujiex** [comment]
Sure. Let me push to a new branch

**Comment by rraustad** [comment]
I think you want to use RegulaFalsiThenBisection. Bisection already proved to give poor performance. You could always try both and choose the fastest option.

**Pull request merged**
