### PR TITLE
89976832 HPWH fan not autosizing #4693

### PR DESCRIPTION
**Pull request by rraustad**
Corrects #4693 HPWH fan not autosizing

### CODE REVIEW

**Comment by rraustad** [comment]
Three tests terminated. I will take another look at this using these files.
HeatPumpWaterHeater
HeatPumpWaterHeaterStratified
WaterHeaterHeatPumpStratifiedTank

**Comment by rraustad** [comment]
If I turn the availability schedule off for the 2 zone heat pump water heaters (HeatPumpWaterHeaterSch = 0), the max iterations go away. Even if I increase the HPWH capacity for the plant HPWH (the one I lowered to eliminate the bypass calculation error) and turn on those 2 HPWH's, the max iteration errors persist. The issue symptom was that the HPWH fan was sizing to 0, essentially turning off all the HPWH's. Now that the HPWH fan sizes correctly, something is causing max iterations.

**Comment by rraustad** [comment]
The max iteration errors were a result of a mistake made to fix this issue. Once that error was identified and corrected, the max iteration errors disappeared. We do still need a way to historically track changes to results.

**Comment by rraustad** [comment]
Defect file now shows fan size correctly.

Component Sizing Information, WaterHeater:HeatPump, HEATPUMPWATERHEATER1, Condenser water flow rate [m3/s], 3.76908E-002
Component Sizing Information, WaterHeater:HeatPump, HEATPUMPWATERHEATER1, Evaporator air flow rate [m3/s], 42.29400
Component Sizing Information, Fan:OnOff, HPWH FAN, Design Size Maximum Flow Rate [m3/s], 42.29400
Component Sizing Information, Coil:WaterHeating:AirToWaterHeatPump, HPWHDXCOIL, Design Size Rated Evaporator Air Flow Rate [m3/s], 42.29400
Component Sizing Information, Coil:WaterHeating:AirToWaterHeatPump, HPWHDXCOIL, Design Size Rated Condenser Water Flow Rate [m3/s], 3.76908E-002

**Comment by rraustad** [comment]
Review of CI results show eio file reporting looks correct now. Some new reports for items that were missed before (e.g., design size vs user-specified) and HPWH fan that is now sized correctly. Assigning to Gu.

**Comment by lgu1234** [comment]
I verified results.

**Comment by rraustad** [comment]
Added fan unit test

**Comment by lgu1234** [comment]
Verified testing results and unit test.

**Pull request merged**
