### PR TITLE
HAMT2: Component moisture source due to air flow

### PR DESCRIPTION
**Pull request by antretterf**
Pull request overview
---------------------
Internal moisture source in HAMT components due to air flow through the component. The moisture source is deposited on a user selected layer inside the component. Input options to determine the air flow are added to the idf file. The include a user defined air flow, air flow determined from stack height, air permeance of the component and ventilation overpressure as well as are flow computed with the airflow network model.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@antretterf @lgentile it has been 51 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@antretterf it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
The code changes here may be perfectly fine, but the reason this hasn't gotten merged is because it didn't follow the proper procedures for a contribution.  We should start with a proposal including justification, then a peer reviewed design document, and then the code submission.  If you are willing to take on that process @antretterf that's wonderful and we should start back from the proposal.  If you aren't able to do that, no problem.  I am going to close this PR, however, so our CI isn't continuing to report on it.

**Pull request closed without merging**
