### PR TITLE
Correction of Engineering Reference Figure 9.1

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
This corrects the problem noted in GitHub Issue #4247 where it was noted that Figure 9.1 in the Engineering Reference was never updated to reflect the current abilities of EnergyPlus.  This was updated a long time ago.  The figure has been recreated from scratch, updated to include the correct information, and given a more colorful look.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ x ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ x ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue #4247 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
So why not include the connection from the plant supply side to the condenser demand side?

**Comment by RKStrand** [comment]
@Myoldmopar That's a great point.  I'll add it in and put a new version up.  The old diagram didn't show this because it was "implied" that the plant supply to condenser demand was allowed, but that really doesn't make any sense to leave it out.

**Comment by RKStrand** [comment]
@Myoldmopar Ready for further review, missing connection added in as requested.

**Review by Myoldmopar — APPROVED** [review]
No unit test.  :laughing: JK!

This is fine.  The plant is so flexible these days that it's not feasible to draw every possible connection type and still have a meaningful, succinct image.  Approved.

**Pull request merged**
