### PR TITLE
Separate Infiltration from Natural Ventilation for AirflowNetwork

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
The zone infiltration report variables are divided into two sections as infiltration and ventilation from outdoor to a zone. Infiltration covers airflow via crack and effective leakage area, while ventilation covers airflow via detailed, simple and horizontal openings.

A test file was uploaded.

IO ref was revised by adding 8 new output variables from ventilation flows.  

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by Myoldmopar — APPROVED** [review]
File changes look fine.

**Comment by Myoldmopar** [comment]
@lgu1234  the branch is still showing about what it was before, 13 large diffs, and some other text-based ones.  This is pretty much as expected, but do you have any results showing that the 13 large diffs aren't breaking anything else?  I'd like to see some results on this discussion thread so I don't have to slog through the results.

**Comment by lgu1234** [comment]
@Myoldmopar I am looking at regression differences at eplusout.csv.diffsummary.csv. Differences in 13 files occur at output variable only as expected due to separation:

Zone Infiltration Sensible Heat Gain Energy [J](TimeStep)
Zone Infiltration Sensible Heat Loss Energy [J](TimeStep)

The rest outputs are the same.

**Comment by lgu1234** [comment]
@Myoldmopar The purpose of this issue is to separate Zone Infiltration Sensible Heat Gain Energy ... into Zone Infiltration Sensible Heat Gain Energy and Zone Vetilation Sensible Heat Gain Energy, based on opening component types. The differences are expected and occur at these output variables only.

**Comment by Myoldmopar** [comment]
Thanks for confirming @lgu1234 I don't think I have any problems with this going in.  @jasondegraw any thoughts before this merges?

**Comment by Myoldmopar** [comment]
Thanks @lgu1234

**Pull request merged**
