### PR TITLE
Evaporative Cooling Envelope Model

### PR DESCRIPTION
**Pull request by rongpengzhang**
Pull request overview
---------------------
The feature aims to implement the Evaporative Cooling Envelope Model developed by Prof. Zhang at the South China University of Technology. The model calculates the cooling effects of the external porous material because of evaporation.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 24 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Is this something being planned for this release?  It doesn't look like it has had activity, so I am doubtful anything is going to come of it over the next couple weeks.  I'm marking it for the next milestone instead.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@hongtz68 Status?

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@rongpengzhang @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Closing this as it has sat without any review or effort for a long time now.  I'll leave the branch on the repo so that someone can pick this up anytime and reopen a pull request.

**Pull request closed without merging**
