### PR TITLE
update nist escalation rates

### LINKED ISSUE #6362: Update LCC to use 2017 NIST supplement
Add life-cycle data set file for 2016 NIST 135 supplement

https://energy.gov/eere/femp/building-life-cycle-cost-programs

### PR DESCRIPTION
**Pull request by MatthewSteen**
Pull request overview
---------------------
Fixes #6362 and #6732.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@MatthewSteen @lgentile it has been 16 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@MatthewSteen I couldn't find a contribution agreement for EnergyPlus from you.  I believe you have one for your work with OpenStudio.  Could you also submit one for E+ so we can review/accept this PR?  If you have submitted one for E+, let me know and I'll investigate.  Thanks!

**Comment by MatthewSteen** [comment]
@Myoldmopar just emailed you my last one.

**Comment by nrel-bot-3** [comment]
@MatthewSteen @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@MatthewSteen @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@MatthewSteen @lgentile it has been 14 days since this pull request was last updated.

**Comment by MatthewSteen** [comment]
@JasonGlazer are you the appropriate person to review? I couldn't get the `ConvertENCOSTtoEnergyPlusLifeCycleCost.xls` spreadsheet to work for either `encost17.txt` or `encost18.txt` and thought a script might be a nice addition to the repo.

**Comment by JasonGlazer** [comment]
Yes, I would be glad too when it is ready to review. Seems like you are getting lots of diffs. Is your branch up to date?

**Comment by mjwitte** [comment]
@MatthewSteen @JasonGlazer There were problems last week where CI was comparing to an old v8.8 branch for regressions. If you get lots of diffs here, look closely at the paths for the regressions. If the baseline path has a PR number in it, then the diffs are still broken.

**Comment by MatthewSteen** [comment]
@JasonGlazer thanks I updated my branch. @mjwitte looks like #6730 might be preventing all the checks from passing.

```
Comparing   `C:/CI/EnergyPlus-d57990544e-PR6298-Win64-VS14/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil`  with  `C:/ci/EnergyPlus-b3704e5158-PR6374-Win64-VS14/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil`
```

**Comment by nrel-bot-2** [comment]
@MatthewSteen @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
We haven't discussed adding a dependency like Eppy to our workflows, so for this to go in soon, it would be better to just hang onto that Python script separately and we'll have a design discussion about adding that dependency.  We are planning on doing some fun things with Python moving forward, so we do need to have that discussion, but it probably won't be until after the 9.0 release this fall.  If you want the NIST rate updated included in 9.0 then my suggestion would be to branch off of this, remove that script, open that as a separate, easy to drop in PR, and then table this conversation about Eppy until later.

**Comment by MatthewSteen** [comment]
@Myoldmopar will do. I think EPPy could also be useful for #6377 and #6378.

**Comment by MatthewSteen** [comment]
@JasonGlazer I think this is ready for a review. I removed the Python script with the EPPy dependency and put it on my [eppy-scripts](https://github.com/MatthewSteen/EnergyPlus/tree/eppy-scripts) branch so this PR is just the 2017 and 2018 dataset IDFs.

**Comment by Myoldmopar** [comment]
@JasonGlazer this is ready to go.  Do you have any issue with this dropping in now?

**Comment by JasonGlazer** [comment]
Sorry, this fell off my radar @Myoldmopar, I still need to confirm the actual values from the NIST update before it should be merged.

**Comment by MatthewSteen** [comment]
@JasonGlazer do you have time to review these for the 9.0 release?

**Comment by JasonGlazer** [comment]
@MatthewSteen I did some spot checking of the 2018 values and they mostly line up. But I did find a problem that concerns me. The "USAvg - Commercial - Natural Gas" has a resource of FuelOil#2 which should be NaturalGas. I would like to do a more comprehensive review but the ordering of the objects has changed. How difficult would it be to arrange the objects in the same order as the previous years LCCusePriceEscalationDataSetXXXX.idf files.

**Comment by JasonGlazer** [comment]
Can you send me the ENCOST17.TXT file? It doesn't seem to be available on the NIST web site anymore.

**Comment by MatthewSteen** [comment]
@JasonGlazer here's the [encost17.txt](https://github.com/NREL/EnergyPlus/files/2332539/encost17.txt) file. I'll take a look at the ordering and the 2018 IDF.

**Comment by JasonGlazer** [comment]
@MatthewSteen if you don't want to mess with your script anymore, I have ended up making the LCCusePriceEscalationDataSet2017.idf and LCCusePriceEscalationDataSet2018.idf files via the spreadsheet approach so that I can check yours. I can just check those in.

**Comment by MatthewSteen** [comment]
@JasonGlazer sure that works. The issue you noticed with the Resource field mismatch was an easy fix (the two years '17 and '18 used inconsistent names - `Natural gas` and `Natural Gas`). Ordering the objects to follow previous years will take a bit more time so I'll wait until next year to do that. Have you considered committing your spreadsheet to the repo?

**Comment by JasonGlazer** [comment]
Would you mind taking a look at these files?

**Review by JasonGlazer — APPROVED** [review]
I ended up replacing the files that Matt had posted since they were in a different object order. I really can't review my own work.

**Comment by JasonGlazer** [comment]
@Myoldmopar @mjwitte @MatthewSteen can one of you review this and make sure it is ready to be incorporated?

**Comment by Myoldmopar** [comment]
@JasonGlazer @MatthewSteen I locally added the new LCC files to the install commands.  I'm building a test package.  If it works, I'll push the commit and merge this in right away.  Thanks for all the effort here.

**Comment by JasonGlazer** [comment]
@Myoldmopar Grazie!

**Pull request merged**
