### PR TITLE
Fix unit test for VS2015

### PR DESCRIPTION
**Pull request by mbadams5**

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mbadams5 I don't mind merging this, but I'm curious how you determined that version number.  Does Microsoft release patches to older versions?  Would there ever be a version of Visual Studio 2013 that fixes that number problem, but yet has an older _MSC_VER like 1801?  Sorry a bit random.

**Comment by Myoldmopar** [comment]
~~Oh, and I'm going to need to see a unit test before merging this, @mbadams5 (@kbenne).~~  Just kidding, @mbadams5 :wink:

**Comment by mbadams5** [comment]
@Myoldmopar http://stackoverflow.com/a/70630/2358662 https://msdn.microsoft.com/en-us/library/b0084kay.aspx

I don't know if they make a new Update to VS2013 whether or not that will be fixed like in VS2015. You can always change the #if check if/when that happens.

I do want to wait until the Windows CI machines finish this to make sure it works on VS2013 still.

**Comment by Myoldmopar** [comment]
Alright, if WinCI comes back happy, I'll merge.

**Pull request merged**
