### PR TITLE
Fix 7595 ADU rate outputs were summed should be averaged

### LINKED ISSUE #7595: ZoneHVAC:AirDistributionUnit output for Zone Air Terminal Sensible Heating/Cooling Rate is summed - should be averaged
Issue overview
--------------
While working on #7448 to remove AirTerminal:SingleDuctUncontrolled, notice these rdd diffs:
```
-Output:Variable,*,Zone Air Terminal Sensible Heating Rate,hourly; !- HVAC Average [W]
-Output:Variable,*,Zone Air Terminal Sensible Cooling Rate,hourly; !- HVAC Average [W]
+Output:Variable,*,Zone Air Terminal Sensible Heating Rate,hourly; !- HVAC Sum [W]
+Output:Variable,*,Zone Air Terminal Sensible Cooling Rate,hourly; !- HVAC Sum [W]
```

The error was in ZoneHVAC:AirDistributionUnit, so these rates have been wrong for all air terminal types (other than AirTerminal:SingleDuctUncontrolled) since these outputs were added five years ago.

This will be fixed in #7448, but noting it here to highlight the problem.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: FurnaceWithDXSystem.idf example file works.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #7595 
 - Output variables Zone Air Terminal Sensible Cooling Rate (and Heating) rate were incorrectly set to sum over time instead of average.
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Hmm, so this only introduces rdd diffs - nothing more. So that means these outputs are only used currently in test files without and ADU (i.e. only with AirTerminal:SingleDuct:Uncontrolled which does have the correct average setting). That's good, but it doesn't help explain the diffs in #7448.

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Closing temporarily.

**Comment by mjwitte** [comment]
This fix is included in #7448 so closing this PR.

**Pull request closed without merging**
