### PR TITLE
Fix the airflow network reference humidity problem

### LINKED ISSUE #8628: AirflowNetwork:MultiZone:ReferenceCrackConditions input problems
Issue overview
--------------
After updating another idf from v8.7 to v9.5, the simulation using the idf (v9.4) failed with the error message: ** Severe ** [json.exception.out_of_range.403] key 'reference_humidity_ratio' not found. The user's idf contains an airflow network model. The field 'reference_humidity_ratio' in the object 'AirflowNetwork:MultiZone:ReferenceCrackConditions' was left blank.  Users can provide a value for the field 'reference_humidity_ratio' of this object in the model temporarily as a workaround. 

Same problem exists if reference_temperature is blank. 

Also, simulations failed when more than one object of 'AirflowNetwork:MultiZone:ReferenceCrackConditions' were created in the model.

### Details
Some additional details for this issue (if relevant):
- Version of EnergyPlus: v9.4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files in EnergyPlusDevSupport\DefectFiles
        AirflowNetwork3zVent-BlankHumidity-v95.idf 
          - fails with v9.5 `** Severe  ** [json.exception.out_of_range.403] key 'reference_temperature' not found`
        AirflowNetwork3zVent-BlankTemperatureAndHumidity-v96.idf - (transitioned from v95 using #8807)
          - fails with develop `** Severe  ** [json.exception.out_of_range.403] key 'reference_humidity_ratio' not found`
          - runs to completion with #8807
       AirflowNetwork3zVent-2RefCond.idf (v9.6)
         - fails with develop `** Severe  ** getAirflowElementInputAirflowNetwork:MultiZone:Surface:Crack: CR-1. Cannot find reference crack conditions object "ReferenceCrackConditions1".`
         - runs to completion with #8807
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by LipingWang**
Pull request overview
---------------------
 - Fixes #8628 
 - Simulation failed with the error message: ** Severe ** [json.exception.out_of_range.403] key 'reference_humidity_ratio' not found due to the field 'reference_humidity_ratio' left blank in the object 'AirflowNetwork:MultiZone:ReferenceCrackConditions.'  

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@LipingWang Please add the same kind of fix for `reference_temperature`. It should be possible for this object to be a single name field and everything else will default.

**Comment by jasondegraw** [comment]
@mjwitte I'm not sure we really want a name-only field. I'm pretty sure that a completely defaulted object would not be any different than no object. It may be difficult to represent this in the IDD, but there really needs to be at least one field for the object to be worthwhile.

**Comment by mjwitte** [comment]
@jasondegraw The only way to force that would be to make one or more of the remaining fields required. Any reason not to make all three required?

**Comment by jasondegraw** [comment]
@mjwitte Not really that I can think of (thoughts, @lgu1234?). If we're only going to have one required, the most likely field would be temperature.

**Comment by nrel-bot-2** [comment]
@LipingWang @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@jasondegraw commented [above](https://github.com/NREL/EnergyPlus/pull/8634#issuecomment-804290423)

> If we're only going to have one required, the most likely field would be temperature.

@LipingWang Based on that, let's change the IDD to make the temperature field \required with the existing \default. And also update the comment in the code about this field. Note this branch has fallen far behind develop.

**Comment by nrel-bot-3** [comment]
@LipingWang @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Superseded by #8807. Closing.

**Pull request closed without merging**
