### PR TITLE
Add ShowRecurringWarningErrorAtEnd in Missing Locations

### LINKED ISSUE #7779: Warnings displayed in ERR file, but total number of errors is zero
Issue overview
--------------
The AirflowNetwork_MultiZone_SmallOffice_VAV.idf example file reports warnings in the ERR file, but the total number of warnings during any part of the simulation is zero.

```
Program Version,EnergyPlus, Version 9.2.0-921312fa1d, YMD=2020.02.14 10:15,
   ************* Beginning Zone Sizing Calculations
   ************* Beginning System Sizing Calculations
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
.
.
.
77 duplicates of above line
.
.
.
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
   ** Warning ** Air temperature above upper limit of 70C for conductivity calculation
   ************* Simulation Error Summary *************
   ************* There are 1 unused schedules in input.
   ************* Use Output:Diagnostics,DisplayUnusedSchedules; to see them.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Completed Successfully-- 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  7.75sec
```

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 9.2
 - Using C:\EnergyPlusV9-2-0\WeatherData\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] C:\EnergyPlusV9-2-0\ExampleFiles\AirflowNetwork_MultiZone_SmallOffice_VAV.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #7793: Errors in Convection Coefficients from CalcBeausoleilMorrisonMixedStableFloor
The IF statement conditions on [this line](https://github.com/NREL/EnergyPlus/blob/93a9c3609392c8dbe8e8a7e323428d1928fc4e8e/src/EnergyPlus/ConvectionCoefficients.cc#L8817) in ```CalcBeausoleilMorrisonMixedStableFloor``` are not correct. They should mimic what is shown in the other similar functions, such as [here](https://github.com/NREL/EnergyPlus/blob/93a9c3609392c8dbe8e8a7e323428d1928fc4e8e/src/EnergyPlus/ConvectionCoefficients.cc#L8888).

Will be addressed by #7780. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mitchute**
Addresses #7779. Calls to [```ShowWarningMessage```](https://github.com/NREL/EnergyPlus/blob/171e4ee74751694622bb86bee306f31f72f61a77/src/EnergyPlus/UtilityRoutines.cc#L1607) were not being counted in the error summary. Perhaps there is a reason for that, but given the numerous variations on "Error", "Warning", "Message" (and other terms) in our error handling, it's hard to tell.

By my IDE's count, there are approximately 235 usages of this across the code base, so this has the potential to cause error diffs across the board.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@mitchute Based on the comments in `ShowWarningMessage` this should always be followed by a `ShowRecurringWarningErrorAtEnd`.
```
    // This subroutine puts ErrorMessage with a Warning designation on
    // designated output files.
    // But does not bump the error count so can be used in conjunction with recurring
    // error calls.
```
For example, [here in Furnace.cc](https://github.com/NREL/EnergyPlus/blob/171e4ee74751694622bb86bee306f31f72f61a77/src/EnergyPlus/Furnaces.cc#L6541-L6551).

So, that says to me that the warning noted in #7779 has been misapplied - either it should be `ShowWarningError` or it should be paired with a `ShowRecurringWarningErrorAtEnd`.

**Comment by mitchute** [comment]
@mjwitte Thanks for pointing that out. I'd guess that this message is misapplied in numerous other locations. For example, [here](https://github.com/NREL/EnergyPlus/blob/171e4ee74751694622bb86bee306f31f72f61a77/src/EnergyPlus/ConvectionCoefficients.cc#L8671).

It looks to me like the call to ```ShowRecurringWarningErrorAtEnd``` should be pulled out of that final IF statement and placed right before the ```return```. Is that the proper usage, or should each ```ShowWarningMessage``` have ```ShowRecurringWarningErrorAtEnd``` called imediatly after (or in this case, after the calls to ```ShowContinueError```)?

**Comment by mjwitte** [comment]
@mitchute The instance you pointed to is well-formed since `DeltaTemp` can vary during the simulation. `ShowWarningMessage` should be written the first time the error condition occurs to give a more complete explanation, and `ShowRecurringWarningErrorAtEnd` should be called every time the error condition occurs to tally up the total count and optionally other statistics to write once at the end of the simulation.

The block before it seems incorrect since `Height` would not vary during the simulation, and it has no trap to prevent this warning from being written 1000s of times. The simple solution would be to keep a local flag and write this once as `ShowWarningError` and indicate that only the first instance of this will be reported. The next level would be to track this by zone.

**Comment by mitchute** [comment]
@mjwitte this should take care of the missing calls at these two locations. Should I expand this issue into a larger search of the codebase to correct other locations?

**Comment by mjwitte** [comment]
@mitchute That's your call, but this is adequate for now.

**Comment by mitchute** [comment]
I'm unsure how to handle the segfaults on this. I thought that pulling the local static variables out to the module level and putting them in a clear_state might help, but I haven't been able to make the unit tests pass reliably. It all works fine in debug mode but fails in release mode.

@Myoldmopar the priority on this is pretty low, so take a look and let me know how you suggest I proceed when you get a chance.

**Comment by Myoldmopar** [comment]
@mitchute extracting those static variables back out made the unit test pass locally for me.  I think this could be all set if CI comes back happy now.

**Comment by Myoldmopar** [comment]
That ERR diff looks so much better!  And best of all, no segfault!  OK, merging this in.

Thanks @mitchute

**Pull request merged**
