### PR TITLE
Changed Fuel Type field as required in Coil:Cooling:DX:MultiSpeed and…

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
Addresses #4851 

Changed the Fuel Type field as required in both Coil:Cooling:DX:MultiSpeed and Coil:Heating:DX:MultiSpeed object in Energy+.idd

Revised IO Ref sections to specify both fields as required without default.

Generated transition rules to add NaturalGas if the input field is blank.
 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 Would you be willing to change PropaneGas to Propane as part of this PR and add it to the transition rule?  Reference #5941

**Comment by lgu1234** [comment]
@mjwitte No problem. I am going to make changes.

**Comment by Myoldmopar** [comment]
@lgu1234 I took over this branch to fully flesh out the initial 8.6 to 8.7 transition work.  If CI comes back happy here, this will merge right in.

**Comment by Myoldmopar** [comment]
OK, I've got to figure out what's up with Linux.  I tried to reproduce locally on the CI box and couldn't, so I hoped they wouldn't remain when in develop.  But alas, there they are.  OK, unrelated to this branch, so this can go in.

**Pull request merged**
