### PR TITLE
Variable Speed DX Coil Enhancements

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Pull request overview
---------------------
New Feature Proposed, for current release cycle, to connect VS DX coil models into six existing parent objects.  

see design document at https://github.com/NREL/EnergyPlus/blob/VS-coil-gaps/design/FY2017/VS-Coil-Gaps.md 

IDD and I/O ref changes made.

Please send NFP review comments via github or email. 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
You've probably already seen this but pointing [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACUnitarySystem.cc#L6826) to show what needs to be done before RegulaFalsi. This should be a smooth add-in.

**Comment by nrel-bot-3** [comment]
@EnergyArchmage @lgentile it has been 27 days since this pull request was last updated.

**Comment by EnergyArchmage** [comment]
The status of this PR seems good to go for input freeze.  All the planned new applications of vs coil models are done and running in new integration testfiles.  Docs are all done.  I think CI should come back clean.  What remains to do is unit tests, and if it okay could finish those under a new issue.

**Comment by Myoldmopar** [comment]
Ha what?  No conflicts _at all_?  Awesome.

**Comment by EnergyArchmage** [comment]
git is trying make up for its bad behavior yesterday

**Comment by Myoldmopar** [comment]
Have you looked at those four debug integration failures?  They look like crashes, but could just be fatal errors.

**Comment by EnergyArchmage** [comment]
I am working on them now.  Was able to reproduce crashes with /fp:strict on windows and am working to fix them now.

**Comment by Myoldmopar** [comment]
All four test files ran successfully with the last changes?  If so, I'm inclined to tempt fate and merge this in as long as the Mac build comes back happy.  It's just this one and the Kiva that I am trying to get in before the next iteration meeting.

**Comment by EnergyArchmage** [comment]
yes all four run fine now, on my windows with fp:strict debug builds.

**Comment by Myoldmopar** [comment]
1 test warning is nothing to do with this branch, it's being fixed separately.  Hoping for the best and merging this now.

**Pull request merged**
