### PR TITLE
Added Error check for zone nodes being used more than once

### PR DESCRIPTION
**Pull request by rglazer2**
Addresses issue #4407  Check for use of the same zone node name in more than one place, such as in ZoneHVAC:EquipmentConnections and in AirLoopHVAC:ReturnPlenum (or SupplyPlenum). This is a severe error as it will cause invalid results in almost all cases.

### CODE REVIEW

**Comment by rglazer2** [comment]
@mjwitte @Myoldmopar  This is properly printing an error now. Let me know if everything looks alright and if the error message is good. 

Also I am unsure of how to go about adding a unit test for this fix. Any suggestions?

**Comment by mjwitte** [comment]
You could populate a small array of node connections once with a conflict and again without.

**Comment by rglazer2** [comment]
@mjwitte How could I actually check if the error had been printed or not? Is there a way to read the error file or something like that?

**Comment by mjwitte** [comment]
Oh right. Not sure if that's doable yet or not. @mbadams ?

**Comment by mjwitte** [comment]
@rglazer2 In energyplusfixture there is a function compare_cerr_stream but it's commented out in DXcoils.unit.cc  But you could use has_cerr_output to check is something went to error output.

**Comment by mbadams5** [comment]
@mjwitte that checks std::err, not the error file. Those error messages may be in std::err but not necessarily. One option is to check the sqlite error table which will have the error messages. There is no way yet to check the error file. 

I would try the has_err_stream though and if it returns true then check against compare_err_stream.

**Comment by mjwitte** [comment]
@mbadams5 I'm a bit confused.  has_cerr_output is being used in [DXCoil.unit.cc](https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/unit/DXCoils.unit.cc#L152) so I'm not sure what it's finding if that is std:err.

compare_eso_stream and compare_mtr_stream appear to working (used a bunch), so what's preventing the same functions for the err output?

**Comment by mbadams5** [comment]
@mjwitte what is written to the error file is sometimes written to cerr but not always. So yes errors will show up in cerr but not all necessarily. I forget which error functions write to cerr and which do not.

**Comment by rglazer2** [comment]
@mjwitte @mbadams5 Is there a specific way to access the sqlite error table? I tried using has_cerr_output(), but that doesn't work. I looked around at the SQLite code, but I'm not sure I entirely understand how it works.

**Comment by mbadams5** [comment]
@rglazer2 There is a way to access the sqlite error table. There are examples of this in [OutputProcessor.unit.cc](https://github.com/NREL/EnergyPlus/blob/b64fa1693d63c1dbc9ed74f2a9dbfc1d542fd638/tst/EnergyPlus/unit/OutputProcessor.unit.cc#L872). That said though, do you have a unit test already for this fix? I don't see any in your changes on GitHub thus far. I'm curious why has_cerr_output() or compare_cerr_stream() doesn't work.

**Comment by mjwitte** [comment]
@mbadams5 The error messages that @rglazer2 is looking at are only written to the err output file, not to cerr  Still wondering why we can't stream eplusout.err the same as eso?

**Comment by mbadams5** [comment]
@mjwitte we CAN but the way eplusout.err is created currently doesn't allow it to easily be captured by the unit testing framework. We would need to refactor it slightly so the framework can capture that stream like the other streams. I didn't want to devote the effort to do that refactor at the time when I added all this. Starting early next FY, I will look at refactoring it.

**Comment by mjwitte** [comment]
@mbadams5 Can you point me to what's different without too much trouble?

**Comment by mbadams5** [comment]
@mjwitte [These lines need to change](https://github.com/NREL/EnergyPlus/blob/b64fa1693d63c1dbc9ed74f2a9dbfc1d542fd638/src/EnergyPlus/UtilityRoutines.cc#L1557-L1572). Basically it needs to be a ostream pointer [like this](https://github.com/NREL/EnergyPlus/blob/b64fa1693d63c1dbc9ed74f2a9dbfc1d542fd638/src/EnergyPlus/DataGlobals.cc#L138), which gets set [here](https://github.com/NREL/EnergyPlus/blob/b64fa1693d63c1dbc9ed74f2a9dbfc1d542fd638/src/EnergyPlus/SimulationManager.cc#L1254) during a normal simulation run. But what I don't know just at a glance is where to move the error_stream pointer creation. It needs to be very early in the simulation process. Maybe it can stay where it is now, but check `if ( error_stream == nullptr ) { /* set pointer stream */ }`. This might work because in unit testing that pointer should be a valid pointer before the first time it hits the `ShowErrorMessage` function.

**Comment by mjwitte** [comment]
@mbadams5 Got it.  Thanks.

**Comment by rglazer2** [comment]
@mjwitte @mbadams5 Thanks for the help. I managed to set up the test with the SQLite method.

**Comment by mjwitte** [comment]
@rglazer2 This is throwing a new warning now for [HeatPumpSecondaryCoil](http://energyplus.s3-website-us-east-1.amazonaws.com/regressions/2015-09/d2971d259fc926578dc7a6eac504bb792a521ea1-320f7384ec7015458a7fcced4a969e3d70b2d76e/HeatPumpSecondaryCoil/i386-Windows-7-VisualStudio-12/eplusout.err.diff.html) This is because the DX coil is incorrectly using the Zone Name for Condenser Placement as both the zone name and the zone air node name.  Even if the input field was the zone node name, it shouldn't be registered as NodeConnectionType_ZoneNode. That should only be used by ZoneHVAC:EquipmentConfiguration, AirLoopHVAC:ZoneSupplyPlenum, and AirLoopHVAC:ZoneReturnPlenum or any new object that actually defines and sets conditions on a zone air node.  

New issue #5174 posted to fix the DX coils.

**Comment by rglazer2** [comment]
@mjwitte Sounds good. Is there anything else I need to do for this issue?

**Comment by mjwitte** [comment]
@rglazer2 No, this is ready for review.

**Comment by mjwitte** [comment]
@Myoldmopar This fix is ready, but it will break  HeatPumpSecondaryCoil.idf so this can't go in until #5174 is in.

**Comment by mjwitte** [comment]
Moving this to 8.4-bugfix.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @rglazer2 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @rglazer2 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @rglazer2 @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@rglazer2 Please merge in current develop into this and push it up.  The original failure for HeatPumpSecondaryCoil should be OK now that #5339 has been merged.

**Comment by mjwitte** [comment]
@rglazer2 On second thought, I'm going to move the changes from here into #5338 because it also has some doc and clear_state updates.

**Comment by rglazer2** [comment]
OK sounds good.

**Comment by mjwitte** [comment]
Node test and unit test combined with other doc and clear_state changes in #5338.  Closing this PR.

**Pull request closed without merging**
