### PR TITLE
Deprecated Boiler "Design Water Outlet Temperature" input field

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses issue #4431 

Pull request overview
---------------------
This is sort of defect. Deprecated Boiler "Design Water Outlet Temperature" input field and replaced its value with hot water design sizing calculation value of 60.0C. The user input value was inconsistent with the sizing calculation procedure. Transition rules were added and the 141 example files with hot water boiler objects.  Diffs are expected in 141 example files.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs

### CODE REVIEW

**Comment by Nigusse** [comment]
The table below shows hot water boiler autosized nominal capacity for selected sample of example files before and after the fix. The nominal capacity change is within 2.05%. This diffs is due to change in hot water temperature used to calculate density and specific heat value of hot water for autosizing boiler nominal capacity. 

4431_boliernomcap_eio_diffs

**Comment by Nigusse** [comment]
Some of failed example files has HVACTemplate that require ExpandObjects. Modified ExpandObjects FORTRAN code used to create Boiler:HotWater object.

**Comment by Nigusse** [comment]
Corrected field numbers in Boiler:HotWater object used with HVACTemplate:Plant:Boiler:ObjectReference object in expandobjects.  This should fix the failed example file HVACTemplate-5ZoneVAVWaterCooled-ObjectReference.idf.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
@Nigusse A bunch of the performance test files were failing because they also needed to be transitioned.  I made that transition, and those should all pass.  I also made one tiny change to an unrelated file here (RefrigeratedWarehouse.idf).  It will show diffs here just in the ERR file but it will stop the diffs from occurring in other branches.  I believe this will be good to go in when CI finishes with 6f2723a.

**Comment by Nigusse** [comment]
@Myoldmopar Thank you for transitioning the performance test files. I missed those. Thank you again for reviewing and merging.

**Comment by mjwitte** [comment]
@Myoldmopar Will you be adding the transition source code?

**Comment by Myoldmopar** [comment]
Yes...I'm working on the transition for the run period stuff now.

**Comment by Myoldmopar** [comment]
Added transition rule, tested it out and it worked fine.  CI should be happy and I think this will be ready to drop in.

**Pull request merged**
