### PR TITLE
Apply IDF Changes from v9.3 to v9.4 Transitions

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
PR incorporates changes from applying the 93 to 94 transition on the IDFs. ~PR expects that #8304 is merged first.~

Some files that need further investigation due unexpected diffs here, due to transition errors or stepping on other (non-transition) changes to these:

 - [x] 5Zone_Unitary_VSDesuperheatWaterHeater
 - [x] 5ZoneFanCoilDOAS_HumidifierOnOASystem
 - [x] _SmallOffice_Dulles
 - [x] AbsorptionChiller_Macro
 - [x] All "ASHRAE" files 
 - [x] EMSPlantLoopOverrideControl
 - [x] gasAbsorptionChillerHeater
 - [x] HeatPumpWaterToAirEquationFit_WaterHeatingDesuperheater_StratifiedTank
 - [x] MultiSpeedHeatPump*
 - [x] PurchAirTables_wAnnual
 - [x] PythonPluginPlantLoopOverrideControl
 - [x] SuperMarketDetailed_DesuperHeatingCoil
 - [x] UnitarySystem_WaterCoils_wMultiSpeedFan
 - [x] 5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd.idf, 5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MultiPath.idf, and RefMedOffVAVAllDefVRP.idf
 - [x] RadLoHydrHeatCoolAuto and RadLoHydrHeatCoolAutoCondFD.idf

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mitchute you mentioned this needs #8304 to go in first, but #8304 is targeting EnergyPlus Future, while this is targeting 9.4.  Can you confirm?

**Comment by mitchute** [comment]
@Myoldmopar I ran the transition on this using the transition exe build for #8304. We can roll those changes back easily enough. I think @mjwitte adjusted the milestones as they are currently, so that's probably the direction we should go.

**Comment by Myoldmopar** [comment]
Thanks, that works for me.  We'll make sure CI is happy with the rollback here and I'll give it a final review.

**Comment by Myoldmopar** [comment]
@mitchute let me know the target for diffs on this branch.  I'm hesitant to do a review with all the diffs showing up in case you are trying to achieve no diffs.  But if you expect diffs then we can proceed with review to justify them.

**Comment by mitchute** [comment]
@Myoldmopar feel free to review. I'll attempt to summarize the changes causing diffs below.

Nearly all files have table diffs and no other diffs due to the ```SimulationControl``` object going from this,
```
  SimulationControl,
    Yes,                     !- Do Zone Sizing Calculation	  
    Yes,                     !- Do System Sizing Calculation	   
    Yes,                     !- Do Plant Sizing Calculation	  
    No,                      !- Run Simulation for Sizing Periods	   
    Yes;                     !- Run Simulation for Weather File Run Periods
```
to this.
```
  SimulationControl,
    Yes,                     !- Do Zone Sizing Calculation	  
    Yes,                     !- Do System Sizing Calculation	   
    Yes,                     !- Do Plant Sizing Calculation	  
    No,                      !- Run Simulation for Sizing Periods	   
    Yes                      !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                         !- Maximum Number of HVAC Sizing Simulation Passes
```

It looks like most of the other major diffs (AUD, ERR, ESO) are coming from changes related to ```Controller:OutdoorAir```.

For this object, the minimum outdoor airflow rate goes from a value of ```0.0``` to a value of ```AUTOSIZE```. A minimum outdoor air schedule name and associated schedule are also added. Some of the numerical differences due to these changes are significant, though I'm not seeing most of them coincide with MTR diffs and I haven't plotted any time-series data to inspect results.

There are still 4 MTR diffs: 3 big, 1 small. I think I've just resolve one of them but I'm not seeing the reason for the other three. Maybe we just roll those three back... IDK. I'll take another look first thing tomorrow after CI has had another pass.

**Pull request merged**
