### PR TITLE
Remove round trim cleanup formatting

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview
---------------------
Refactoring to remove RoundSigDigits and TrimSigDigits while adding format() calls where reasonable.

expected failure:

* 1 regression test is now failing due to a copy-paste-error correction

No other changes expected.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This is going to be great.  I'll keep an eye on it for when CI is happy with it and you feel like you are done with it.

**Comment by lefticus** [comment]
@Myoldmopar I'm clearly quite confused on this as of course I've been building it all along on my systems and it's not building at all on any CI. I'll see what's going on.

**Comment by Myoldmopar** [comment]
Definitely closer, but Windows is still having trouble with an ambiguous `fmt` symbol.  Once that is resolved I'll take a final look here.

**Comment by Myoldmopar** [comment]
I'll resolve the conflicts here and get this ready to go.  Thanks for fixing the `fmt` issue @lefticus.

**Comment by lefticus** [comment]
Sorry, I missed the conflicts. I headed out of town for a couple of days

**Comment by mitchute** [comment]
I'm not sure why CI complained on the unit test coverage build, but the AFN error message diff is definitely fixing an erroneous error message here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/AirflowNetwork/src/Properties.cpp#L85

We'll keep an eye on CI for this next round of results and go from there.

**Comment by lefticus** [comment]
> I'm not sure why CI complained on the unit test coverage build, but the AFN error message diff is definitely fixing an erroneous error message here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/AirflowNetwork/src/Properties.cpp#L85
> 

Yes, I saw many minor mistakes during the conversion that I left because I didn't want to cause too many diffs, but when I saw this mistake which was 100% wrong, I felt I needed to fix it (it's mentioned in the PR also)

**Comment by mitchute** [comment]
Thanks, @lefticus. This is looking really good. I'll try to get this one in right away so we don't keep having to deal with merge conflicts.

**Review by Myoldmopar — APPROVED** [review]
Very nice to see these cleaned up!

**Comment by Myoldmopar** [comment]
I see the coverage dipped very slightly because of lines changed here.  I don't anticipate artificially pumping that back up or adjusting the limit, we'll leave the warning and try to bump it back up through other PRs.  This looks otherwise good on CI with the one expected diff and the GPU spurious regressions.  I see this is ready and will merge, thanks!

**Pull request merged**
