### PR TITLE
Fix DualDuct VAV and VAV:OA: Wrong int index used, fix for #6418

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix for #6418: Found a mistake in DualDuct::GetDualDuctInput where the wrong int index was used.
The rationale is that there are three types of DualDuct terminals in there: CV, VAV and VAV:OutdoorAir. 
For each type, you loop on the number of objects with an int `DamperIndex`, but you put all the results in a single `Damper` array (CV first, then VAV, then VAVOA), so you use a second int DamperNum. 
In the routine, it was wrongly using DamperIndex, which lead to:
* Overwrite of existing dampers of another type
* Uninitialized ADUNum for some dampers, leading to an assertion (contains) error.

The key is finding this bug is that you need to have at least two different damper types in your file, so the overwriting actually happens.

The file I submitted in #6418 will fail to run properly (and it's way too big to make it a simulation tests anyways) but I have checked that it no longer crashes, and using a debugger I can check that the Damper array (especially the ADUNums) are fine.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
I unfortunately have no free time to implement a unit test or a regression test for this, but as I have stated above: the key is finding this bug is that you need to have at least two different dual duct damper types in your file (eg: `AirTerminal:DualDuct:ConstantVolume` and `AirTerminal:DualDuct:VAV:OutdoorAir`), so the overwriting actually happens.

**Comment by mjwitte** [comment]
@jmarrec At first glance, these changes look correct.  Because the entire block(s) that are misusing `DamperIndex` use it everywhere in the block, the overwriting is putting the correct `ADUNum` in place for the earlier damper types, but the problem is that the later damper types end up with a zero.  I can pick this one up and finish it out with unit test and a smaller defect file.

**Comment by jmarrec** [comment]
@mjwitte I pushed the start of a unit test. It isn’t working as such (commit message indicates where), but may be a helpful as a starting point. I had no time to troubleshoot why the input isn’t working.

**Comment by Myoldmopar** [comment]
I'm not sure what to do on this one.  No one had time to write a unit test, but this is a clear fix and should go in.  I might comment out the start of the unit test that is currently there so I can uncomment it out and fix it so it actually tests.  Ugh.

**Pull request merged**
