### PR TITLE
ZoneHVAC:WaterToAirHeatPump with variable speed coils throws a fatal error about unitaryMultiSpeed

### LINKED ISSUE #7053: ZoneHVAC:WaterToAirHeatPump with variable speed coils throws a fatal error about unitaryMultiSpeed
Issue overview
--------------

This issue relates to https://github.com/NREL/OpenStudio/issues/3332

A `ZoneHVAC:WaterToAirHeatPump` that has variable speed heating and cooling coils (`Coil:XXX:WaterToAirHeatPumpVariableSpeedEquationFit`) throws a fatal:

```
**  Fatal  ** COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT = COIL COOLING WATER TO AIR HEAT PUMP VARIABLE SPEED EQUATION FIT 6 number of speeds not equal to number of speed specified in UnitarySystemPerformance:Multispeed object.
```

The coil isn't actually referenced by any `UnitarySystemPerformance:Multispeed` object

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: Current develop ae12ddd304a000290082d27013b86b466f6631f5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [7053/in.idf](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7053/in.idf) and [7053/in_smaller.idf](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7053/in_smaller.idf)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect): #7054

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7053 : ZoneHVAC:WaterToAirHeatPump with variable speed coils throws a fatal error about unitaryMultiSpeed

Problem was initialization of an index variable to 0 when this one is actually used to index a std::vector (0-index, as opposed to the `ObjexxFCL/Array1D` which is 1-indexed), which a later check for index > -1.

Extended a unit test to fake having a `UnitarySystemPerformance:Multispeed` in the "model" and produce the fatal.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by rraustad — APPROVED** [review]
Agreed. I thought I changed that.

**Comment by mjwitte** [comment]
@jmarrec @Myoldmopar cpp check is [not happy](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-a919c10e756ced687740e1d270031b2bab3a5034-PR7054-x86_64-Linux-Ubuntu-18.04-cppcheck-1.82.html) and there are lots of other diffs. I re-ran some of these today just to be sure it wasn't from recent CI problems. Is this branch not current with develop?

**Comment by Myoldmopar** [comment]
It's out of date with develop:

image

@jmarrec I know we have write access on your branches, but to keep it simple, could you pull the latest NREL/develop into this branch?  Thanks!

**Review by mjwitte — APPROVED** [review]
@Myoldmopar @jmarrec  I forgot we have permission. Branch is up to date. Tested with the defect files, ran unit tests, all looks good. Will merge after CI comes back green.

**Pull request merged**
