### PR TITLE
Add check to not show component loads when only SizingPeriod:WeatherFileConditionType is used

### LINKED ISSUE #6860: Crash in table reports with SizingPeriod:WeatherFileConditionType as the only type of sizing period
Issue overview
--------------
User file has two SizingPeriod:WeatherFileConditionType objects and not other sizing periods. Simulation crashes with an array bounds error in `CollectPeakZoneConditions` which is triggered by the ZoneComponentLoadSummary.

### Workaround
Disable the ZoneComponentLoadSummary report.

Or add a dummy design day like this one, but it's not clear if the ZoneComponentLoadSummary will report the correct peak conditions in this case.
```
  SizingPeriod:DesignDay,
    DummyDesignDay,  !- Name
    1,                       !- Month
    21,                      !- Day of Month
    WinterDesignDay,         !- Day Type
    22.0,                   !- Maximum Dry-Bulb Temperature {C}
    0.0,                     !- Daily Dry-Bulb Temperature Range {deltaC}
    ,                        !- Dry-Bulb Temperature Range Modifier Type
    ,                        !- Dry-Bulb Temperature Range Modifier Day Schedule Name
    Wetbulb,                 !- Humidity Condition Type
    10.0,                   !- Wetbulb or DewPoint at Maximum Dry-Bulb {C}
    ,                        !- Humidity Condition Day Schedule Name
    ,                        !- Humidity Ratio at Maximum Dry-Bulb {kgWater/kgDryAir}
    ,                        !- Enthalpy at Maximum Dry-Bulb {J/kg}
    ,                        !- Daily Wet-Bulb Temperature Range {deltaC}
    99063.,                  !- Barometric Pressure {Pa}
    4.9,                     !- Wind Speed {m/s}
    270,                     !- Wind Direction {deg}
    No,                      !- Rain Indicator
    No,                      !- Snow Indicator
    No,                      !- Daylight Saving Time Indicator
    ASHRAEClearSky,          !- Solar Model Indicator
    ,                        !- Beam Solar Day Schedule Name
    ,                        !- Diffuse Solar Day Schedule Name
    ,                        !- ASHRAE Clear Sky Optical Depth for Beam Irradiance (taub) {dimensionless}
    ,                        !- ASHRAE Clear Sky Optical Depth for Diffuse Irradiance (taud) {dimensionless}
    0.0;                     !- Sky Clearness
```

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.9.0 and v9.0 73281ffba3
 - Helpdesk ticket number 12889

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
The Load Component Summary Tables need specific design days to work. They work fine with SizingPeriod:DesignDay and with SizingPeriod:WeatherFileDays but do not work if the only sizing period in the file is SizingPeriod:WeatherFileConditionType. This fix adds a check to make sure that the sizing period type and the call for the component loads reports are consistent and provides a warning if they are not.

This fixes #6860 and #6756 which were both reporting the same crash.

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [x] Argument types
   - [x] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar this is ready for review.

**Review by mjwitte — COMMENTED** [review]
Tested defect files.
CTF_InfiniteR_FortIrwin-Crash-exp.err - crashes before, now generates the new warning and completes.
Added design days to this and it crashes.
Added design days to this and deleted all of the Sizing:* objects and it shows the correct warning and completes.

Bug-BaseboardDistrictrHeat-Gallavan - crash before, runs ok now with new warning.
Bug-BaseboardDistrictrHeat-Gallavan_noTabular - ran before and runs now.

So, the one with both types of SizingPeriod crashes in `CollectPeakZoneConditions` likely because the SizingPeriod:WeatherFile got selected as the peak?  

May need to flip this check and quit if there are any SizingPeriod:WeatherFile present?  OR check if `desDaySelected` is greater than number of DesignDays then quit?

**Comment by JasonGlazer** [comment]
@mjwitte the generation of the timestamp for the loads component report was causing the problem so added some protection around that. It takes care of the latest crash and should have been present all along.

**Comment by mjwitte** [comment]
So, with this in place, can the report work with any SizingPeriod or still just SizingPeriod:DesignDay and SizingPeriod:WeatherFileDays? Remove the other checks? It's disappointing that the time of peak comes out blank. Any way to figure it out from some other data?

**Comment by mjwitte** [comment]
But I've confirmed, no more crashes here, so that's good.

**Comment by JasonGlazer** [comment]
I don't think the SizingPeriod:WeatherFileDyas really ends up with a timestamp like the SizingPeriod:DesignDay does.

**Comment by mjwitte** [comment]
HVAC Sizing Summary shows time of peak for each zone. In CTF_InfiniteR_FortIrwin-Crash-exp-TestOtherErrorAddDesignDaysTable.html

**Comment by JasonGlazer** [comment]
@mjwitte I added some code that shows the timestamp from a different source. I seem to remember that is how it was originally and we needed to make the change for some other bug fix. It seems to work for this so that is better than a blank timestamp.

**Comment by Myoldmopar** [comment]
Looks like this is on pace to get in.  @mjwitte the last CI results had the build warning which is now fixed, and the Linux was forced to fail because of the doc issue.  I'm OK if you want to merge this before waiting on CI.

**Comment by mjwitte** [comment]
@Myoldmopar I was hoping to get a full clean CI report on this before merging. Will wait a little longer.

**Comment by Myoldmopar** [comment]
@mjwitte that is a full CI report (8 results) on 4381033 unless you've triggered the unhandled exception build to run again.  Oh I see you did trigger it to run again.  Ok, carry on, but it looks very clean, so merge at will.

**Comment by Myoldmopar** [comment]
Wait, @mjwitte, **did** you restart that failed build?  Now I'm a bit confused when looking at the CI repo.

**Comment by mjwitte** [comment]
I thought I did.

**Comment by mjwitte** [comment]
At this point, I guess we just merge this and hope for the best.

**Comment by Myoldmopar** [comment]
:+1:

**Pull request merged**
