### PR TITLE
Remove duplicate input in AirflowNetwork:Distribution:Node

### LINKED ISSUE #7762: Node duplication in some of the AirflowNetwork example files
Issue overview
--------------
Some of the the AirflowNetwork example files have duplicate nodes: multiple AFN nodes are pointing toward the same feature/component. See, for example, AirflowNetwork_Attic_Duct.idf, where MainInletNode and FanInletNode both reference Air Loop Inlet Node. The example files still run successfully, but the networks are possibly more complex than necessary. One possible solution is to upgrade the auditing script to warn about this, but it would also work to just check all of the files to make sure that the networks represent what is intended.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (example file AirflowNetwork_Attic_Duct.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
Check duplicated inputs of Component Name or Node Name in AirflowNetwork:Distribution:Node and issue an error
Provide a test file
Correct inputs in 7 example files
No differences were found in 7 example files on local computer

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jasondegraw** [comment]
@lgu1234 Is this PR ready for review?

**Comment by lgu1234** [comment]
@jasondegraw Yes. It is ready for review. Thanks.

**Review by jasondegraw — APPROVED** [review]
This corrects the issue, looks good to go.

**Comment by lgu1234** [comment]
@jasondegraw A failure of unit test was fixed.

**Comment by mitchute** [comment]
Unit tests pass on this locally. @lgu1234 anything else you're wanting to do here before final review and merge?

**Comment by lgu1234** [comment]
@mitchute No. Please merge.

**Pull request merged**
