### PR TITLE
Added reset for DataAirFlowUsedForSizing in water cooling coil sizing

### PR DESCRIPTION
**Pull request by rraustad**
if ( WaterCoil( CoilNum ).WaterCoilType == CoilType_Cooling ) { // 'Cooling'
<snip>
DataAirFlowUsedForSizing=0.0;
}

### CODE REVIEW

**Comment by mjwitte** [comment]
Fixes #4810 Tested defect file and the coil flow rates now line up with their respective airloop flow rates.  Will wait for CI to reveal if this results in diffs across the regression tests.

**Comment by rraustad** [comment]
Added unit test for water coils. Done and done.

**Comment by mjwitte** [comment]
@rraustad Your commit says you added a unit test, but I'm not seeing it here.

**Comment by rraustad** [comment]
It was 2 AM when I finished. I guess I didn't add it? right-click and add? I'll get it in when I get home. A little bit of a challenge to get a water coil to size.

**Comment by mjwitte** [comment]
@rraustad Unit tests on any of the sizing it rather challenging.  So, you don't have access to the file right now?  When doing the commit (if using tortoisegit) you need to show the unversioned files and check the box so it gets added.

**Comment by rraustad** [comment]
The unit test is on my home laptop.

**Comment by mjwitte** [comment]
@Myoldmopar @rraustad This is an important bug to get fixed.  Would like to see this get in to v8.3 even if the unit test is failing.

**Comment by jasondegraw** [comment]
@mjwitte The unit test problems look to be the usual difficulties. Some of those diffs look like they could be due to develop having moved - merging in develop again should hopefully fix that. So I'd say it can probably be merged.

**Comment by Myoldmopar** [comment]
Yeah, the one regression here looks intentional.  This can merge anytime unless anyone is waiting on anything here.

**Pull request merged**
