### PR TITLE
edited curve names to match tables J5/J7 (> changed to >=)

### PR DESCRIPTION
**Pull request by aowabinr**
Pull request overview
---------------------
 - Fixes ##9641(IF THIS IS A DEFECT)
 - DESCRIBE PURPOSE OF THIS PULL REQUEST
 
  We're changing the curve names in CodeCompliantEquipment.idf to reflect the actual curve specifications in Appendix G 90.1-2022.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@aowabinr is this contribution coming via PNNL like your previous PR?

**Comment by aowabinr** [comment]
> @aowabinr is this contribution coming via PNNL like your previous PR?

Hi @Myoldmopar, yes it's via PNNL.

**Comment by Myoldmopar** [comment]
Thanks @aowabinr 

@mjwitte or @JasonGlazer, do you anticipate any consequences to this name change?  I don't have a feel for how often anyone would be grabbing these objects "by name" and using them.  I assume that would be the only time something would break from it.

**Comment by JasonGlazer** [comment]
@Myoldmopar I would guess most of the time users are just copying the curves including the names so they would have update the names where ever they are referenced by chillers in the file. That said, having the correct names probably makes sense.

**Comment by Myoldmopar** [comment]
I agree, I think the correct naming is worth the change.  I'm just going to go ahead and merge.  Thanks @aowabinr

**Pull request merged**
