### PR TITLE
Add PlantEquipmentOperation:ThermalEnergyStorage controls

### PR DESCRIPTION
**Pull request by RKStrand**
@Myoldmopar @mjwitte @lgentile 
Work from September 2014 moved forward to latest develop and changes requested by Mike Witte addressed.  Input file working, giving nearly identical results as existing file in test suite with old control scheme.  New docs will be sent around via email.  I believe that this completes this work.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@RKStrand Docs aren't separate now.  You'll edit the documentation in Markdown directly in this branch in /doc/src.  That way it is merged into develop at the same time the source and idd and idf changes are merged in.  Let me know if you have any questions.

**Comment by RKStrand** [comment]
@Myoldmopar Oh yeah, I do remember something about this being mentioned in an iteration call at some point.  To refresh my memory...

So I make the change directly to the appropriate .md document rather than as a separate document that someone has to merge later?

What software on a Mac will preserve the proper format of the existing document so that I don't mess up what is already there?

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte @lgentile Ok, docs have been updated for the "b" portion of the input output reference.  I followed the format from the input that was right before this addition.  There were also some other minor edits but I followed the syntax for those as well.  This was done with TextEdit for Mac.  Hopefully there will not be any issues with using that software to edit these text files.  Thanks.

**Comment by Myoldmopar** [comment]
@RKStrand I merged develop in, resolved conflicts, and did some cleanup on the idd.  It builds, but I didn't do any testing or detailed review...that is coming next.  Should be providing more comments by the end of the week.

**Comment by RKStrand** [comment]
@Myoldmopar Thanks, Edwin.  Hopefully the testing will go well and there won't be any issues.  Thanks for working on this!

**Comment by Myoldmopar** [comment]
@RKStrand The first thing I see testing this is that the error file has a number of warnings in it.  Most of them are unrelated to this work.  I checked the difference in error files between `5ZoneDetailedIceStorage` and `5ZoneDetailedIceStorageSimpleCtrl` and found that the error messages are only in the new version.  It appears that the simple control file was based on that former file, and I anticipated the development would be a no-diffs-in-results change.  Only changing the inputs (which are so much simpler now, thanks). 

Can you clarify on whether you were trying to create an exact match in outputs between the two?  And in either case, can you comment on what we should change to get rid of the warning.

Here is the new warning text, it is familiar:

```
   ** Severe  ** FindRootSimpleController: Controller error for controller = "CENTRAL COOLING COIL CONTOLLER 1"
   **   ~~~   **  Environment=CHICAGO_IL_USA ANNUAL COOLING 1% DESIGN CONDITIONS DB/MCWB, at Simulation time=07/21 00:00 - 00:15
   **   ~~~   **   Controller function is inconsistent with user specified controller action = Reverse action
   **   ~~~   **   Actuator will be set to maximum action
   **   ~~~   ** Controller control type=Temperature
   **   ~~~   ** Controller temperature setpoint = 15.02 [C]
   **   ~~~   ** Controller sensed temperature = 29.07 [C]
   **   ~~~   ** Controller actuator mass flow rate set to 1.46 [kg/s]
   **   ~~~   ** Controller actuator temperature = 29.55 [C]
   **   ~~~   **   Note: Chilled water coils should be reverse action and the entering chilled
   **   ~~~   **         water temperature (controller actuator temperature) should be below the setpoint temperature
   **   ~~~   **   Note: Hot water coils should be normal action and the entering hot
   **   ~~~   **         water temperature (controller actuator temperature) should be above the setpoint temperature
```

**Comment by RKStrand** [comment]
@Myoldmopar That is weird.  As you mentioned, it has nothing to do with the ice storage work but rather the cooling coil.  So, I'm not sure why this error message is popping up.  I will not be able to look at this today but perhaps sometime early next week if the beginning of classes on Monday goes fairly smoothly.  Yes, the intent was to have no diffs or at least nearly identical diffs in the output.

**Comment by RKStrand** [comment]
@Myoldmopar Well, after thinking about it, it seems like the water temperatures would indicate that the ice storage system is not turning on.  After looking at the output closer, sure enough, the ice storage system is not turning on in the new control example.  I do not know why that is currently and will have to look at this further.  This behavior was exhibited at one point during the process of porting stuff to the most recent code.  However, I fixed whatever the issue was and was certain that I had checked things in.  I will try to jog my memory and maybe do some more debugging.  I know I had results that were nearly identical and that the ice storage system was running before I submitted it.

Also, on the internet version of GitHub, it shows that you changed the name of this branch which is totally fine and makes a lot of sense.  For some reason though, in my Mac GitHub version, the name change is not registering.  Not a big deal to me, but it did seem a bit odd.

**Comment by RKStrand** [comment]
@Myoldmopar Memory jogged.  It was a563025 (problem with compare fixed) where autosizing was being done but data was not being transferred to the proper simulation variables because E+ insisted that -9999 did not equal -9999.  I got around it by establishing a tolerance that the code really should not need.  However, it worked and the code ran.  That code was checked in and not somehow lost so I'm not sure why this is happening again.  I will have to investigate further but it does not appear to be an issue of code not getting pushed up to the repository.

**Comment by Myoldmopar** [comment]
Interesting, @RKStrand.  Thanks for looking into it.  I'm happy to help, but I won't be able to provide too deep of assistance beyond review.  As for the name, I think you mean I changed the pull request name, and yeah, who knows if the Github clients will pick that up or not.  I have no idea.  But it won't cause any issues with the underlying Git client since it has no concept of the PR on Github.

**Comment by RKStrand** [comment]
@Myoldmopar Well, good thing I looked back at that old "problem" that I had.  It was not what I though but rather a typo in a variable name.  So, I fixed that and change the compare logic back to what it should have been.  You should find the error message is now gone and the code is what it should have been.  Results are nearly identical to the example file that uses the old, long form control definition.  Unless a max difference of around a Joule is a concern (I didn't feel like it was), I think this is fixed and ready.

**Comment by Myoldmopar** [comment]
@RKStrand That's great!  I'll check it out locally and complete my review.  Hopefully it will be all done now!

**Comment by Myoldmopar** [comment]
@RKStrand This looks great.  I built and ran your stuff, and the error file is clean, and the results match the other long-winded example file.  I worked up a unit test for the calc routine.  As far as I am concerned this is good to merge once CI is happy with my last commit.

@mjwitte Any last minute comments before merge?

**Comment by mjwitte** [comment]
@RKStrand @Myoldmopar Nothing more from me.  This will be a welcome addition.

**Comment by Myoldmopar** [comment]
I'm going to be unavailable this afternoon, and CI is looking good already so I'm going to merge this now.  Thanks @RKStrand now we're on to the next one :smile:.

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte Awesome!  Thanks for pushing this one across the finish line.  Hope the next one goes even more quickly!

**Pull request merged**
