### PR TITLE
Code Cleanups and Minor Refinements

### PR DESCRIPTION
**Pull request by DeadParrot**
@Myoldmopar This is a non-urgent set of misc updates that can be reviewed when time allows. As requested, I separated this from more substantial revisions. It has passed my test suite with only the expected output fixups causing diffs.

The changes include:
 Automated pass to improve code consistency
 String literal breaks left over from F-to-C++ conversion removed
 String passing by value in some new code fixed
 Unnec trim() calls that appeared removed
 ProcessZoneData array args change from slices to references (faster)
 gio::Fmt const removed for reuse (faster)
 PlantPipingSystemsManager code refinements
 Misc minor code refinements

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@DeadParrot This looks pretty good, but maybe one issue.  There are many eio file changes, and most are just fine (whitespace differences), but as I was scanning through I did find one anomaly.  If you look at the diff [here](http://energyplus.s3-website-us-east-1.amazonaws.com/9e735926d57419b3af57cf6232297b51b50aa69a-beef9cff888952f5ccddca57b860d538ff0aa51d/1ZoneWith14ControlledHeat-CoolPanels/i386-Windows-7-VisualStudio-12/eplusout.eio.diff.html), in the first difference, if you scroll most of the way over, you'll see the line changed from:
 
```
... Sinusoidal Variation,Period of Sinusoidal Variation ...
```

to 

```
... Sinusoidal VariationPeriod of Sinusoidal Variation ...
```

Note the missing comma now.  This will have to be remedied.  

I'm wondering how engrained all the eio changes are with the rest of the cleanup.  Is it possible to extract out the eio changes and get a 100% clean report, then add the eio changes back in?  Or is it too widespread to do that?

**Comment by DeadParrot** [comment]
@Myoldmopar Fix for missing comma (my fault) pushed. This branch is all about separating the non-computational changes, as requested. The string cleanups are a main part of that and spread throughout the code (mostly done in an automated fashion) and separating those that affect eio from others would be very hard. But I'm happy to fix up any other problems testing finds. I know this is a pain and I'll try not to do these branches often: the extraneous string literal breaks were a remnant of the Fortran conversion that we didn't need/want going forward.

**Comment by Myoldmopar** [comment]
OK, thanks @DeadParrot.  I recall now this being split out already.  This branch is currently conflicted, but hold off on doing any merge, as one more branch will likely drop in this afternoon.  If it is a trivial conflict resolution, I'll merge it and push up the resolved state.

After that, I'll re-run the tests myself so that I can do some custom diff-ing of the output files, with added ignore-patterns.  I'll work through the false positives and hopefully find nothing of significance.  If that's true, this should be merge-able right away.

**Comment by DeadParrot** [comment]
@Myoldmopar OK, thanks. Let me know if I can help. I appreciate that this is a hassle.

**Comment by Myoldmopar** [comment]
No big deal.  One question though.  Did you make any functional changes to the third party sqlite library code?  The merge is conflicted on those files (sqlite.c; sqlite.h), but as far as I can tell it is only trailing spaces removed.  There are many conflicts, so I am highly inclined to just use the versions of the files currently on develop if you didn't make any functional changes.  If you did make actual changes over there, I'll work through the conflicts.

**Comment by Myoldmopar** [comment]
@DeadParrot (Didn't tag you in the [above comment](https://github.com/NREL/EnergyPlus/pull/4612#issuecomment-68932382), please read that first)

In addition, did you make any functional changes to the SQLiteProcedures.cc file?  It also has many conflicts, and it is due to the significant changes made by @mbadams5.  They change a lot of functionality, while as far as I can tell, your changes are mostly formatting.  I'd like to stick with the develop version on that file as well for now if possible.  Then clean up formatting in a follow-up commit.

Thus, could you let me know if you made any functional changes in these files:
  third_party/SQLite/sqlite.c
  third_party/SQLite/sqlite.h
  src/EnergyPlus/SQLiteProcedures.cc

For reference, I'm looking at the full diff here: https://github.com/NREL/EnergyPlus/pull/4612.patch, searching for those filenames as needed.  (@mjwitte this is a nice trick to search through diffs that are too large for GitHub to render; just add .patch to the end of the URL).

**Comment by DeadParrot** [comment]
@Myoldmopar No, there should be no functional changes to the SQLite code in this branch. The cleanup scripts remove trailing spaces: ideally that sort of cleanup would be better handled as a pre-commit script. The cleanup changes are non-essential so sticking with what is on develop is fine if that simplifies the merge and PR.

Github may not be the best way to look at changes when you want to filter some things out. It is crude but cloning two repos checked out to different revisions and diff + grep may be a good, low-tech way to ignore whitespace and other types of changes.

**Comment by kbenne** [comment]
Or git diff with one of the following...

       -b, --ignore-space-change
           Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all other sequences of one or more whitespace characters to be equivalent.

       -w, --ignore-all-space
           Ignore whitespace when comparing lines. This ignores differences even if one line has whitespace where the other line has none.

       --ignore-blank-lines
           Ignore changes whose lines are all blank.

**Comment by Myoldmopar** [comment]
@DeadParrot I had to do a couple merges to get everything worked out, but this branch should now be ready to go.  I think I'll let CI see if I missed something, but it should drop in today.

**Comment by Myoldmopar** [comment]
Those first CI results look good.  Lots of eio cleanup with a few error message cleanups as well.  This should be ready to go, but I'll let the other CI runs finish since they are already running.

**Pull request merged**
