### PR TITLE
Remove unnecessary warnings in two example files

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
More AirflowNetwork:MultiZone:Surface objects were added in both example files: AirflowNetwork_Simple_House.idf and AirflowNetwork_Simple_SamllOffice.idf. All unnecessary warning are removed in AirflowNetwork_Simple_SamllOffice.idf. However, since AirflowNetwork_Simple_House.idf does not have a flat roof, a warning still remains.
 
### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
The one failing CI looks completely unrelated, and I feel strongly that if I deleted those CI results, it would come back clean.  I don't plan on doing that.

I took a look at the two regressions, and the diffs do look fine, but I don't see the error differences on CI.  I'm building develop and this branch locally and I'll run those files and compare the differences in error output.  If they are good, I'll merge this one.

**Comment by Myoldmopar** [comment]
I ran the two changed files both on develop and this branch.  I didn't see any diffs.  Then I actually opened the error files themselves.  There's no warnings in the develop branch, it's clean.

```
Program Version,EnergyPlus, Version 8.9.0-c90c364c79, YMD=2018.05.31 20:26,
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ************* Simulation Error Summary *************
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Completed Successfully-- 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  9.35sec
```

So......I'm not sure what you were seeing.  Can you confirm that you did see warnings in develop branch, and that this branch did remove them?

**Comment by lgu1234** [comment]
@Myoldmopar The unnecessary warnings occur with an output request of Output:Diagnostics, DisplayExtraWarnings; Regular regression test will not show these warnings. Users complained these warnings with DisplayExtraWarnings outputs in different tickets. I uploaded two test files at EnergyPlusDevSupport\DefectFiles\6000s\6710. You can test them using the test files.

Thanks.

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 14 days since this pull request was last updated.

**Pull request merged**
