### PR TITLE
Add SpecialDays to Annual Run

### PR DESCRIPTION
**Pull request by mitchute**
Adding special days to an annual run.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I've got no problem with this.  Does this suffice for you, @mjwitte?

**Comment by mjwitte** [comment]
@mitchute Since #8215 is not merged yet, I expected this would error out. What's different in the https://github.com/NREL/EnergyPlus/issues/8214 defect file?

**Comment by Myoldmopar** [comment]
Yeah that's a good point @mjwitte.  In my head it was because this was built on the other branch, but it's not.  So I'm not sure.

**Comment by mitchute** [comment]
We should probably look into this a little more. This file was actually fine with special days. It was the stratified chilled water tank file that complained. Do we need to spend a little time investigating why, or maybe just add an annual run with that file?

**Comment by mjwitte** [comment]
For CI efficiency, we'd rather not add another annual run. Let's figure out why this one ran fine and the other one failed. Of course, the special days fix is already merged, so we'll have to test that locally.

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar following up on this.

I've rolled back the code to play with why the ```_5ZoneAirCooled_annual.idf``` file (which *has* special days already) failed to catch this. We can make the file fail like the ```5ZoneVAV-ChilledWaterStorage-Stratified``` file by changing the run period from this:

```
  RunPeriod,
    RUNPERIOD 1,             !- Name
    1,                       !- Begin Month
    1,                       !- Begin Day of Month
    2019,                    !- Begin Year
    ...
    2019,                    !- End Year
    ,                        !- Day of Week for Start Day
    ...
```

to this:

```
  RunPeriod,
    RUNPERIOD 1,             !- Name
    7,                       !- Begin Month
    11,                      !- Begin Day of Month
    ,                        !- Begin Year
    ...
    ,                        !- End Year
    Sunday,                  !- Day of Week for Start Day
    ...
```

Failing to provide a year make the code pick a default year which changes the calculation of the ```MonWeekDay``` array (https://github.com/NREL/EnergyPlus/blob/c3fbac0a78cc1f13110035e495678114a14b6206/src/EnergyPlus/WeatherManager.hh#L333). I don't understand why changing the month or start day changes it...

That doesn't, to me at least, fully explain the root cause of the issue, but I'm not sure this warrants further investigation at this point. I think @nmerket  is going to be spending some time in this part of the code next FY, so maybe he will be adding unit tests to help catch issues like this in the future.

Let me know how you suggest we proceed.

**Comment by mitchute** [comment]
Edit: Sorry, *this* PR is the reason ```_5ZoneAirCooled_annual``` has special days 🤦 

Regardless, even after adding special days, it still fails to catch the issue without the changes to the RunPeriod.

**Comment by mjwitte** [comment]
@mitchute I think this is good to add (as modified) to catch any future problems (even if it's not a complete test).

**Comment by Myoldmopar** [comment]
I second the motion to drop this in, and also to not spend too much time dwelling since it will hopefully have better unit testing added in soon.

**Comment by Myoldmopar** [comment]
Thanks @mitchute, merging.

**Comment by mjwitte** [comment]
Um, I don't think this had the enhanced RunPeriod object yet.

**Pull request merged**
