### PR TITLE
Spawn

### PR DESCRIPTION
**Pull request by kbenne**
Similar to the external HVAC manager callback function, which is the main Spawn hook, this PR adds an external surface manager that enables an external program to set individual surface temperatures.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@kbenne let's chat Monday about this if you are available.

**Comment by nrel-bot-2** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@kbenne I'm going to close this PR.  I don't know when we'll bring together these changes, and having the PR sit open all this time isn't doing anything but adding to CI's stale message count.  The branch should obviously live here, and some time we can reopen this with the goal of getting it merged.

**Pull request closed without merging**
