### PR TITLE
Use currDifSolarRad, currBeamSolarRad to hold adjusted solar and other cleanups in the incident solar multiplier feature

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
Local optimization and code cleanups.

- Use temp variables to hold multiplication results in surface loops: when terms like `state.dataEnvrn->BeamSolarRad * SurfIncSolarMultiplier`, `state.dataEnvrn->DifSolarRad * SurfIncSolarMultiplier`, `state.dataEnvrn->GndSolarRad * SurfIncSolarMultiplier` appear multiple times in surface loops, use a temp variable to hold these values instead of doing the multiplication every time could have performance gains.

This cleaning-up does not show CI performance improvement yet. It might need a lot more of such local optimization to have an impact.
image (8)

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@yujiex did you have any outcomes you'd like to share from this change?  It's just a simple cleanup, so I don't mind it going right in, but some commentary would be good to wrap it up and I'll get it merged in.

**Comment by yujiex** [comment]
@Myoldmopar maybe we can merge it in? I added some notes in PR about the performance differences of this modification.

**Comment by Myoldmopar** [comment]
Fine by me, I'm pulling upstream in and running the tests just to make sure nothing recently has broken anything here, then I'll merge.

**Comment by yujiex** [comment]
> Fine by me, I'm pulling upstream in and running the tests just to make sure nothing recently has broken anything here, then I'll merge.

Thanks @Myoldmopar

**Comment by Myoldmopar** [comment]
Tested fine with upstream pulled in.  Merging.  Thanks @yujiex

**Comment by yujiex** [comment]
Thanks @Myoldmopar

**Pull request merged**
