### PR TITLE
Integrate Eigen within HBIRE

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
This PR integrates work from PR #6737. 

This work attempted to integrate Eigen within CalcScriptF and CalcInteriorRadExchange. The CalcScriptF function saw a 200-1400x improvement. However, efforts to convert CalcInteriorRadExchange to use Eigen yielded a 1.87x _decline_ in performance and thus was reverted from the PR. This PR also adds new unit tests for CalcInteriorRadExchange(), CalcScriptF(), and CalcMatrixInverse(). Due to the added unit tests, a bug in the CalcScriptF conversion was found and corrected.

||Overall||CalcInterior</br>RadExchange||CalcScriptF||
|---|---|---|---|---|---|---|
||EP 8.9|Branch|EP 8.9|Branch|EP 8.9|Branch|
|4-sided|6.6s|6.67s (0.99x)|63ms|65ms (0.97x)|N/A|N/A|
|512-sided|2.23min|2.15min (1.04x)|1.47min|1.39min (1.06x)|3.27s|16ms (204x)|
|1024-sided|9.39min|6.97min (1.35x)|7.93min|5.46min (1.45x)|2.16min|93ms (1393x)|

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@mbadams5 So, can we close #6737?

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 68 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 16 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@mbadams5 there is at a minimum one unit test failure to be addressed.  Do you plan on addressing this and anything else that comes up in the next couple days to try to get this in for this release?

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by amirroth** [comment]
Let me ask a high-level question about Eigen. Is Eigen basically just a better, more standardized, somewhat more functional ObjexxFCL?

**Comment by mbadams5** [comment]
@amirroth, I think that is an unfair comparison to Eigen (or any specialized linear algebra library). ObjexxFCL is a Fortran emulation layer that has some performance and linear algebra functions. Eigen has much more broad linear algebra support, can use parallelization, better vectorization, Intel MKL backend, and better cache awareness and coherency. Yes, you do need to use their container classes to have the best performance results.

**Comment by amirroth** [comment]
@mbadams5 I meant no offense. What I meant was that it looks like we are trying to use Eigen to provide the built-in array functionality that FORTRAN currently supports at the language level and that we are currently using ObjexxFCL to provide. Understand that Eigen can do significantly more than that.

**Comment by mbadams5** [comment]
@amirroth, That is true for high dimensional arrays, but with the added benefit of faster computation. 
However, most of the arrays in E+ are 1 dimensional and even some of the multi-dimensional arrays could probably be rewritten to be 1D.
Personally I think the main goal of using a library like Eigen should be faster performance. Replacing the multi-dimensional fortran-like arrays with multi-dimensional Eigen arrays is a (good) ancillary benefit.

**Comment by amirroth** [comment]
@mbadams5 We will get performance improvements when we use the built-in Eigen functions. But how many linear algebra algorithms does EnergyPlus actually use in a compact form? I feel like most of what EnergyPlus does is combine simpler linear algebra primitives in loops. You don't want to encapsulate those using a library because you want the compiler to optimize across primitives for the same loop iteration. I think this is the cause of the slowdown you saw in HBIRE.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 19 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 17 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 23 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 21 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 12 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Any expectations for this PR this week before we freeze?  Just checking before I move the milestone.  Thanks!

**Comment by amirroth** [comment]
I’m 97.6% sure this branch is dead. And we have significantly more important things to do.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@Myoldmopar @mbadams5 it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mbadams5 it has been 10 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
> I’m 97.6% sure this branch is dead. And we have significantly more important things to do.

I'll take that note and close this PR but the branch will be here ready to re-open the PR if anyone wants to get it ready for merge.

**Pull request closed without merging**
