### PR TITLE
1277852 command line interface

### PR DESCRIPTION
**Pull request by nealkruis**
@kbenne @Myoldmopar This is the Command Line Interface pull. Can one of you review? I've tested on Ubuntu, OS X, and Windows 7.

### CODE REVIEW

**Comment by nealkruis** [comment]
@Myoldmopar It looks like the Windows build is having a problem with the merge you committed near the end of November. The values of the file names are not preserved after calling ProcessArgs from main(). Can you look into a solution?

**Comment by Myoldmopar** [comment]
@kbenne Looks like that cleaned up the failing build.  I think if we merge develop in to clean up the regressions it should be ready, right?  Do you want me to merge and resolve the conflict(s)?

**Comment by kbenne** [comment]
@Myoldmopar Go for it.

**Comment by Myoldmopar** [comment]
Yay? OK, will do.

**Comment by Myoldmopar** [comment]
@mjwitte @nealkruis @kbenne 

Interesting random note as I resolve conflicts.  I hadn't thought about how the run scripts automatically ran ExpandObjects, etc., but the new CLI requires an additional argument.  I'm not saying it's bad...I actually like that it is more _intentional_; just something to make sure is clear in the docs.

**Comment by mjwitte** [comment]
@Myoldmopar @kbenne @nealkruis Regarding the running of the preprocessors, it seems we keep wavering in the definition of what the default CLI usage should be - does it duplicate the existing scripts or not.  Seems that an argument should be required to turn off the preprocessing steps rather than activate.

**Comment by nealkruis** [comment]
I fixed the problem with the unit test. @mjwitte, the CLI usage should provide a posix-like interface to EnergyPlus. NREL has decided that it is best for the CLI to follow the executable behavior by default. The existing shell scripts will still function the same way, and the script behavior can be replicated through CLI arguments.

**Comment by Myoldmopar** [comment]
Hmmm, I do not know what is going on with the Ubuntu build.  Those integration tests are running fine for my debug build locally.  And they run on all the other platforms.  I'll pull develop in to get rid of the regression from the heat pump water heater commit, and maybe it will have just been an anomaly.

**Comment by Myoldmopar** [comment]
OK, with this last commit, I removed the full file paths for the idd and idf when it is simply reporting that it is starting and finishing reading them.  I didn't remove the file paths for the erroneous messages.  I don't have a strong stand on this at all, but just flushing out full paths seems like the wrong approach unless the user needs to know (error condition).  

Also, I am not seeing the issue with the unit test that is showing up on CI; all the E+ unit tests run successfully.  @kbenne @nealkruis could one of you confirm whether or not the unit tests are failing on your machines?

**Comment by nealkruis** [comment]
@Myoldmopar I fixed the unit test [here](https://github.com/NREL/EnergyPlus/commit/6ed197588a35c1cc77325fc0827e4a993d0b331f).

**Comment by Myoldmopar** [comment]
Perhaps you mean [here](https://github.com/NREL/EnergyPlus/commit/dfca3514dc48221af767567e1900f8e8e9e8d5e3)?  Anyway, it looks like another one is [failing](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-beef65057255e8126c3c3c4238e8354393ab8673-x86_64-Linux-Ubuntu-14.04-gcc-4.8-UnitTestsCoverage-Debug.html) now with the same type of issue.

**Comment by nealkruis** [comment]
Yep. I'm on the new one. This must be a recent merge from develop.

**Comment by Myoldmopar** [comment]
Is it reasonable that all these files be given defaults so that we don't have to manually do this when writing unit tests?

**Comment by nealkruis** [comment]
I think so. I'll go ahead and do that.

**Comment by Myoldmopar** [comment]
@nealkruis So, things are still improving, but I noticed something.  A new error is showing up because ExpandObjects can't find the idd file when it tries to run.  See [here](http://energyplus.s3-website-us-east-1.amazonaws.com/1b4e5eccd518c88ff3dd784cbc89799d68b1d966-beef65057255e8126c3c3c4238e8354393ab8673/5ZoneAirCooledWithSlab/x86_64-MacOS-10.9-clang/eplusout.err.diff.html).  This should be remedied somehow.

Next, it looks like the coverage warning will be triggered for integration test coverage.  I suppose it is possible that once the above issue is cleaned up, it will hit those last few lines of code and bump up to the limit.  But in case it isn't, here are my thoughts:

@lgentile @kbenne The CLI is being exercised pretty heavily as a core part of our testing framework.  It doesn't really need to be accompanied with a specific integration test.  I'm not sure if the right answer here, but here are some options:
 1. Reduce the coverage expectation (warning value) so that the light turns green...not great.
 2. Leave the light yellow until some additional coverage tests are added
 3. Require that @nealkruis come up with an "unrelated" additional integration test that gets the number above the limit.

At the moment, I am more interested in getting the CLI working **really well** and merged, and less interested in the coverage warning.  I can concoct an integration test that will bump up the coverage at any time.  Maybe I'll just do that now and this will be moot.

**Comment by Myoldmopar** [comment]
Unless...is this right @nealkruis?

http://energyplus.s3-website-us-east-1.amazonaws.com/coverage/2015-01-27-EP-beef650572-x86_64-G4.8UTCD/EnergyPlus/CommandLineInterface.cc.gcov.html

**Comment by Myoldmopar** [comment]
Nevermind on the above comment; I was apparently looking at the unit test coverage.

**Comment by Myoldmopar** [comment]
Oh, and then whatever is going on with the Windows cli-arg test.  Which...since the CLI is being used directly in with the other integration tests, is probably not necessary anyway, and should be removed.

**Comment by nealkruis** [comment]
I think I fixed the preprocessor related tests and the unit tests. Waiting on the CI for confirmation. What do you mean by "Windows cli-arg"? [This?](https://github.com/NREL/EnergyPlus/blob/1277852-CommandLineInterface/cmake/RunCommandLineArgTest.cmake)

**Comment by Myoldmopar** [comment]
@kbenne @lgentile @nealkruis This can be merged at will once CI reports that it doesn't have any beef with beef3d5.

**Pull request merged**
