### PR TITLE
Fix out of date optimized build commands

### LINKED ISSUE #4733: LTO / PGO commands are out of date with respect to current target names
The optimized build commands located in top level CMakeLists.txt are out of date.  They use camel case target names which no longer exist after reintegration of CLI.

### PR DESCRIPTION
**Pull request by kbenne**
fix #4733

### CODE REVIEW

**Comment by kbenne** [comment]
@lefticus some pgo/lto rules were left out of date when CLI changed the case of some target names.

**Comment by lefticus** [comment]
I'd kind of like to see a release tag made of this, just to make sure, before we merge everything and call it good. Do you have any problems with that? (I'll make the tag)

**Comment by kbenne** [comment]
@lefticus yep the branch tests don't actually prove it works.  That is actually why i did this work in the first place, because my release tag is failing.  How about i make a release branch and merge this in there first?  I have to grab the idd install work https://github.com/NREL/EnergyPlus/pull/4725 too.

**Comment by lefticus** [comment]
Sounds good

**Comment by kbenne** [comment]
@lefticus This should offer up the proof once the results come in.  

https://github.com/NREL/EnergyPlus/commits/v8.2.8

https://github.com/NREL/EnergyPlus/releases/tag/v8.2.8

**Comment by kbenne** [comment]
@lefticus I know we are still working out some LTO issues on Linux, but this has been played out on the iteration branch and v8.2.8 tag.  In the interest of moving forward can we reintegrate?

**Comment by lefticus** [comment]
Yeah, let's do that. Is this specific pull request still valid? Merging straight into develop?

**Comment by kbenne** [comment]
still valid.

**Pull request merged**
