### PR TITLE
Fix return flow basis node calculation

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Addresses #6725, corrects the flow rate calculation when using Zone Return Air Node 1 Flow Rate Basis Node or NodeList Name in `ZoneHVAC:EquipmentConnections`.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes n/a

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 27 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 29 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Before and after output. Still need a unit test.
image

**Comment by rraustad** [comment]
This looks correct. While I test the defect file think about this. 

The IF/ELSE IF where you made this change says "Make no return air flow adjustments during sizing" for the IF and requires numRetNodes == 1. So if there are 2 return nodes then the code falls to the ELSE IF and doesn't set returnNodeMassFlow when doing sizing? Doesn't returnNodeMassFlow need a value during sizing if there are 2 return nodes?

                 // Return node 1 is special
                 if (returnNum == 1) {
                     // Make no return air flow adjustments during sizing
                     if ((DataGlobals::DoingSizing || DataGlobals::isPulseZoneSizing) && numRetNodes == 1) {
                         returnNodeMassFlow = ExpTotalReturnMassFlow;
                         if (airLoop > 0) {
                             if (!DataAirSystems::PrimaryAirSystem(airLoop).OASysExists) {
                                 ExpTotalReturnMassFlow = max(0.0, ExpTotalReturnMassFlow - thisZoneEquip.ZoneExhBalanced + thisZoneEquip.ZoneExh);
                                 returnNodeMassFlow = ExpTotalReturnMassFlow;
                             }
                         }
                    } else if (!DataGlobals::DoingSizing && !DataGlobals::isPulseZoneSizing) {
                        if (thisZoneEquip.NumReturnFlowBasisNodes > 0) {
                            // Set base return air flow rate for node 1 using basis node flow rates
                            Real64 basisNodesMassFlow = 0.0;
                            for (int nodeNum = 1; nodeNum <= thisZoneEquip.NumReturnFlowBasisNodes; ++nodeNum) {
                                returnNodeMassFlow += DataLoopNode::Node(thisZoneEquip.ReturnFlowBasisNode(nodeNum)).MassFlowRate;
                                basisNodesMassFlow += DataLoopNode::Node(thisZoneEquip.ReturnFlowBasisNode(nodeNum)).MassFlowRate;
                            }
                            returnNodeMassFlow = max(0.0, (returnNodeMassFlow * returnSchedFrac));
                            returnNodeMassFlow = max(0.0, (basisNodesMassFlow * returnSchedFrac));
                            fixedReturn(returnNum) = true;
                        } else {
                            // If only 1 return node, use the standard return mass flow
                             if (numRetNodes == 1) {
                                 returnNodeMassFlow = max(0.0, (ExpTotalReturnMassFlow * returnSchedFrac * airLoopReturnFrac));
                             }
                         }
                     }
                 }
                 totReturnFlow += returnNodeMassFlow;
                 retNodeData.MassFlowRate = returnNodeMassFlow;

**Comment by rraustad** [comment]
There are 2 inlet and 2 outlet nodes in this zone with the VAV box inlet node as the "Zone Return Air Node 1 Flow Rate Basis Node".

    ZoneHVAC:EquipmentConnections,
      SPACE2-1,                !- Zone Name
      SPACE2-1 Eq,             !- Zone Conditioning Equipment List Name
      SPACE2-1 Inlets,         !- Zone Air Inlet Node or NodeList Name
      ,                        !- Zone Air Exhaust Node or NodeList Name
      SPACE2-1 Node,           !- Zone Air Node Name
      SPACE2-1 Outlets,        !- Zone Return Air Node or NodeList Name
      ,  !- Zone Return Air Node 1 Flow Rate Fraction Schedule Name
      SPACE2-1 Zone Equip Inlet;  !- Zone Return Air Node 1 Flow Rate Basis Node or NodeList Name

    NodeList,
      SPACE2-1 Inlets,         !- Name
      SPACE2-1 In Node,        !- Node 1 Name
      SPACE2-1 DOAS Supply Inlet;  !- Node 2 Name

    NodeList,
      SPACE2-1 Outlets,        !- Name
      SPACE2-1 DOAS Return Node,  !- Node 1 Name
      SPACE2-1 Out Node;       !- Node 2 Name

    AirTerminal:SingleDuct:VAV:NoReheat,
      SPACE2-1 DOAS Air Terminal,  !- Name
      ,                        !- Availability Schedule Name
      SPACE2-1 DOAS Supply Inlet,  !- Air Outlet Node Name
      SPACE2-1 Zone Equip Inlet,  !- Air Inlet Node Name

The main air loop nodes, Space2-1 In Node and Space2-1 Out Node track each other.
The DOAS air loop nodes, Space2-1 DOAS Return Node and Space2-1 DOAS Supply Node also track each other and follow the basis node flow of the DOAS VAV box inlet node (thin red line hard to see).

So this looks correct now.

image

**Review by rraustad — APPROVED** [review]
Approved once this is answered. Does the variable returnNodeMassFlow need to be set during sizing if there is more than 1 return node. See comment in discussion. This may be a different issue.

**Comment by mjwitte** [comment]
I'll have to review that whole "node 1 is special" sizing/not-sizing logic. I'm fairly certain that was left in there to eliminate diffs at the time for standard single-return-node runs. What's not clear is if it does the right thing for multi-return node cases.

**Comment by rraustad** [comment]
Issue #6955 created to identify any remaining issues discussed here.

**Pull request merged**
