### PR TITLE
Ummm, fixed the unit tests?

### PR DESCRIPTION
**Pull request by Myoldmopar**
OK, so....this gets unit tests running and not segfaulting!?  I am so confused right now.  Something has gone off the deep end with our unit tests...

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Interesting.  I assume the test fails with that. Perhaps the EXPECT_DOUBLE_EQ are the problem?  They could just as well be EXPECT_NEAR with a tolerance of, say 0.001.

**Comment by mbadams5** [comment]
@Myoldmopar @mjwitte I would be surprised if this fixes both Debug AND Release builds. When I ran across this unit test failing on one of my branches, changing the value would fix it for one of the builds but then cause the other build to fail. Basically, if it failed in Debug then you make this fix, it will then fail on Release in my local testing.

**Comment by mjwitte** [comment]
@Myoldmopar @mbadams5 I can reproduce the 20000 on my machine using a release build.  

[ RUN      ] SizePurchasedAirTest.Test1
..\..\..\..\tst\EnergyPlus\unit\PurchasedAirManager.unit.cc(84): error: Value of
: PurchAir( PurchAirNum ).MaxHeatVolFlowRate
  Actual: 20000
Expected: 1.0
Which is: 1

So, something isn't getting initialized the way it needs to be for SizePurchasedAir to return the correct value (1.0).  But what would get initialized differently for a release vs debug build?  I'll try to track down a way to fix this test.

But that doesn't explain why a failed EXPECT terminates the remaining tests.  Shouldn't it report the failure and continue on?

**Comment by mbadams5** [comment]
@mjwitte No it won't continue because of #4742. If you have ENABLE_GTEST_DEBUG_MODE to ON (which is default) then it will stop after a test failure.

**Comment by Myoldmopar** [comment]
Yeah, well, @mbadams5, with your :8ball: being able to predict it wouldn't work and blah blah OK I'm leaving... :wink:

OK, in serious, I still don't know what's going on here, but this branch and pull request are being deleted and closed respectively.

**Comment by mjwitte** [comment]
@Myoldmopar Well, this discussion prompted me to debug the purchased air unit test (using RelWithDebInfo config) and I may have found a problem.  If I get a reliable fix with both debug and release I'll make a new branch for it.

**Pull request closed without merging**
