### PR TITLE
Add a new example file for single sided natural ventilation

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
A new example file is added to demonstrate capability of advanced single-sided natural ventilation feature as AirflowNetworkAdvanced_SingleSided_NV.idf. This PR responses the GitHub issue #6180.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by jasondegraw — APPROVED** [review]
This looks good to me. It could maybe use some explanation added at the top of the file like some of the other example files, but I'll leave that to others to decide. I did notice an EIO oddity when running the file, will put in an issue.

**Comment by Myoldmopar** [comment]
Ran the file with develop merged in and got the expected file version error showing up in the err file.  Fixed that, everything else looks good.  Merging.

**Comment by mjwitte** [comment]
@lgu1234 Please edit the top description for this PR and reference the issue addressed, if there is one.

**Comment by lgu1234** [comment]
@mjwitte The top description is revised.

**Pull request merged**
