### PR TITLE
69208874 lbnl coil vs space peak

### PR DESCRIPTION
**Pull request by wfbuhl**
There's a new input field in Sizing:System, and a couple name changes. Existing inputs should run unchanged, however.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@wfbuhl I'll merge develop in this tomorrow and play with it.

**Comment by Myoldmopar** [comment]
@mjwitte @wfbuhl I'm on reviewing this now.

### IDD
On Sizing:System, I'm curious about the min-fields change from 27 to 37.  It appears you only added one field to the end, which has a default value, so do you really want users to have to add 10 more potentially blank fields?  Or leave it optional and enforce the default within the code?

### Code; in the order of the diff [here](https://github.com/NREL/EnergyPlus/pull/4635/files)
 - First off, the formatting looks mostly great (that is, in conjunction with the rest of the code base).
 - This is minor, in general we don't need to create/keep member constructors for the large structs we create.  These are littered through the code, so I understand why you added to them/created them, and it's no problem.  But they aren't actually needed in most cases.  This goes back to how FORTRAN specified that for any TYPE, the compiler was supposed to create 2 constructors: Default and Member.  The default would simply construct an instance of the TYPE with the default values defined when you created your TYPE.  (Think: ```TYPE(EquipData) :: ThisEquip```).  Then the member constructor would create it by passing it initial values.  (Think: ```TYPE(Node) :: Node(0.0, 0.0, "")```)  When the code was translated from FORTRAN, the translator automatically created both types in C++ land, but unless you are actually going to create a new instance and give it **every** one of those values, you don't need it.  And I wouldn't be surprised if there were only a handful of instances within the code that [does this](https://github.com/NREL/EnergyPlus/blob/149f03ea2ce84582828f037faf768892ca674f09/src/EnergyPlus/DataLoopNode.cc#L87).  So, in summary, don't worry about it, but feel free to ignore member constructors moving forward, and delete them if they aren't being used.
 - An added indent popped in [here](https://github.com/NREL/EnergyPlus/pull/4635/files#diff-de781ad7ec80e690e175811f4da40a5aR1294); was that intentional?
 - So removing the heating size ratio here was intentional also?  I'm not really doubting, but it seemed a bit sudden as I read through.
 - Gah, these sizing arrays are just getting monstrous.  It would be so much nicer to have a struct with scalar members such as ```HeatFlowSeq```, ```CoolFlowSeq```, etc., then we just create a _single_ array of these structs, only allocate it _once_, and change all the calls from: ```SysSizing( AirLoopNum, DesDayEnvrnNum ).CoolFlowSeq( NumOfTimeStepInDay );``` to ```SysSizing( AirLoopNum, DesDayEnvrnNum ).SomeStructName( NumOfTimeStepInDay ).CoolFlowSeq;```.  Might not look that much different, but it would make it easier for maintenance.  Anyway, no action items, just a note for refactoring opportunities.
 - Indentation/whitespace issues [here](https://github.com/NREL/EnergyPlus/pull/4635/files#diff-f51329ac8013440dabda3acd6c2d2a9aR3919) and [here](https://github.com/NREL/EnergyPlus/pull/4635/files#diff-f51329ac8013440dabda3acd6c2d2a9aR3919)
 - The format statements here should actually be non-const, right @DeadParrot?  There's a performance nuance involved.
 - There were a few other whitespace things that I can help run through and clean-up, but nothing major.
 - Whoa, adding the type-member array-transformation into [ObjexxFCL](https://github.com/NREL/EnergyPlus/pull/4635/files#diff-13), huh?  It's OK, just didn't expect it :wink: 
 - Overall, the code changes look like mostly some bookkeeping and renaming efforts more than anything else.

### Transition
So, this does change field names, so I'm not actually sure if the transition program needs a block for this object or not to update field names.  Either way, I can handle that side of it.  Of course, if the transition program needs to flush out blank values to accommodate the min-fields change, then I can be sure to do that.

### Docs
Can you put the doc changes up in BuildSupport [here](https://github.com/NREL/EnergyPlusBuildSupport/tree/master/docs/src/mods/for_2015_03_release) for review and to be added to the mods for the 2015-03 release?

### Testing
I can run some testing and evaluate the sizing effect.  Is there going to be a new idf exemplifying this or will this end up affecting existing idfs and causing diffs.

Thanks @wfbuhl for this.  We can chat on the next sizing call if not before.

**Comment by DeadParrot** [comment]
@Myoldmopar Good catch! Yes, it is best for performance now to have non-const `gio::Fmt` objects, even if they are static. Reusing the Fmt objects avoids an expensive tree representation clone.

The renaming of ObjexxFCL member arrays seems OK. We should discourage adding any new ones and, possibly, require removing rather than renaming them -- your call.

**Comment by Myoldmopar** [comment]
@wfbuhl I merged develop into this branch and had to resolve some conflicts.  The difficult ones were in the GetInput, where it appears that the "blank" check was removed in your branch, like [here](https://github.com/NREL/EnergyPlus/pull/4635/files#diff-5dfb1fbe2001fc786e85d6ca25868168L2110).  This could go hand-in-hand with my comments in the review about how the min-fields had changed for the Sizing:System object.  I also had to hand convert some humidifier code changes that had dropped in (by me), but I think they are fine.  We'll see when CI starts running regressions.  For the record, it did build fine for me.

So...make sure you do a Git Pull before you start making any changes on this code to avoid issues later.

**Comment by Myoldmopar** [comment]
@DeadParrot I am inclined to let this slide for right now; but I might just go into the code and back them back out and update the code to a more norm C++ style.

**Comment by wfbuhl** [comment]
Thanks Edwin. I'll be going through your comments. I'm sure I will learn a
lot. Here's one response:

>On Sizing:System, I'm curious about the min-fields change from 27 to 37.
It appears you only added one field to the end, which has >a default value,
so do you really want users to have to add 10 more potentially blank
fields? Or leave it optional and enforce the >
>default within the code?

I guess my opinion is that enforcing defaults in the code is not good
practice. The I was lazy and didn't want to stick my new input in the
middle of the fields. Perhaps this kind of issue will go away when we
switch to a keyword based input.

**Comment by wfbuhl** [comment]
>This is minor, in general we don't need to create/keep member constructors
...
This is interesting and good to know

>An added indent popped in here
<https://github.com/NREL/EnergyPlus/pull/4635/files#diff-de781ad7ec80e690e175811f4da40a5aR1294>;
was that intentional?
No

>So removing the heating size ratio here was intentional also?
Yes

>Gah, these sizing arrays are just getting monstrous...
Yes, and they are going to get bigger. Your suggestion seems like a good
idea.

>Whoa, adding the type-member array-transformation into ObjexxFCL
<https://github.com/NREL/EnergyPlus/pull/4635/files#diff-13>, huh? ...
Remember, I am monkey-coding. I understood what these are doing, and it
seemed OK though a bit odd. Would be happy to do it a different way,
particularly if it is concise.

>So, this does change field names,....
I did change field names everything else was handled so that there would
not need to be any transition program changes. In other words, example
files will run with no changes.

>Can you put the doc changes up in BuildSupport here
<https://github.com/NREL/EnergyPlusBuildSupport/tree/master/docs/src/mods/for_2015_03_release>
for review...
My doc changes are complete and I will move them up.

>I can run some testing and evaluate the sizing effect. Is there going to
be a new idf...
With the current defaults there will be changes to the sizing results and
of course downstream. We should talk about new examples and unit tests.

Fred

**Comment by mjwitte** [comment]
@Myoldmopar @wfbuhl Just to clarify, min-fields specifies how many fields the input processor will fill in with defaults that are declared in the IDD.  It does not mean that the user input must include that many fields.  If the idf object is shorter than min-fields, if there is not a required-field within the remaining min-fields, then it will run just fine with defaults filled in.  I agree with Fred that we want defaults to be in the IDD, not hidden in getinputs.

**Comment by Myoldmopar** [comment]
That's fine, it's just causing diffs because of IP warnings while it fills in defaults.  I guess the right thing would be to run the idfs through the transition program, which should pick up the new min-fields and write out the blanks.  This would get rid of the warnings.

**Comment by Myoldmopar** [comment]
@wfbuhl I whipped up the unit tests for the new function you added.  Feel free to mimic this moving forward.  I also did the clean-up steps I had previously mentioned.  The only thing I didn't do was run the idfs through Transition to update the blank fields, so the error files are still producing input-processor warnings about filling missing fields with defaults.  I'll let CI have a pass at this unit test and such and then I can clean up those as well.

**Comment by Myoldmopar** [comment]
Alright, did a test running an idf through transition.  The tool does fill out system sizing with the new field names and the default fields on the end.  This will make System Sizing objects get filled out to the min-fields length in the example files, which is fine.  Much better than a warning in the error file for all those files.  

I'm going to modify the transition tool so it won't update the files to 8.3, otherwise that error will start to be introduced instead.  Once I remedy that (hopefully here in just a few minutes), I'll run transition over all the files and update the idfs on this branch.  At that point, I think this should be good to go in.

@wfbuhl @mjwitte @larryscheier

**Comment by Myoldmopar** [comment]
So a couple IDF's need some minor tweaking after transition, and I need to add another case to the unit test I wrote. After _that_ this should be ready to go in I think...

**Comment by Myoldmopar** [comment]
@wfbuhl I cleaned up the unit test so it will have full coverage in the new function, and I cleaned up some minor issues with transition.  At this point, the regression tests will be failing, but it should be easier to look through as the changes may all be expected.

**Comment by Myoldmopar** [comment]
So, @mjwitte @JasonGlazer @wfbuhl, it looks like we might need to modify ExpandObjects so that when it pumps out Sizing:System objects, it puts the right number of fields so that we don't end up with IP warnings in the err file for the HVACTemplate files.  I took a quick look in there, and it looks like there are 8 spots where Sizing:System is written out, and decided I'd prefer if one of you would make the update in there.

I know I have at least one other file to update in the meantime, because I botched the recently updated HPWH example file during my transition pass.

**Comment by Myoldmopar** [comment]
And ooooooo criky.  Just noticed transition was pumping out this last line of the Sizing:System object:

```
    VAV;                     !- <none>
```

Then looked at the new IDD and found this guy:

```
+ A11; \Central Cooling Capacity Control Method
```

.....

I'll push the idd change...done @ beefd9c.  And then I'll use some script-o to clean up all the idfs with that object...done @ beef4c2.

**Comment by mjwitte** [comment]
And the other field name changes in Sizing:System should also be updated in expandobjects.

**Comment by Myoldmopar** [comment]
Sorry for cross-posting :wink: 

@wfbuhl @mjwitte @JasonGlazer As far as I can tell from looking over the CI results, the only issue remaining is the ExpandObjects update. Is anyone available to make those changes, or do I need to venture over there?

Oh, and I should amend to say that -- after beefc65 was checked in just now -- the only issue I see is ExpandObjects.

**Comment by mjwitte** [comment]
@Myoldmopar Later in the week I can look at it.

**Comment by Myoldmopar** [comment]
@wfbuhl @mjwitte @JasonGlazer Will you have availability to address ExpandObjects on this?  Or should I...

**Comment by mjwitte** [comment]
I was just in the process of sending you a message about this. Planning 
to fit this in this week.

**Comment by Myoldmopar** [comment]
Cool, I'll merge develop into it to resolve the (likely) minor conflict (probably in tst/EnergyPlus/unit/CMakeLists.txt).  So just make sure to git pull before starting to make any changes.

**Comment by mjwitte** [comment]
@Myoldmopar @wfbuhl Working on updating ExpandObjects to get rid of errors, but I'm confused.
(pasting idd here, 'cause github won't display file diffs - too many)
```
  A9, \field Cooling Design Capacity Method
      \type choice
      \key None
      \key CoolingDesignCapacity
      \key CapacityPerFloorArea
      \key FractionOfAutosizedCoolingCapacity
      \default CoolingDesignCapacity
      \note Enter the method used to determine the system cooling design capacity for scalable sizing.
      \note None is used when a cooling coils is not included in an airloop or this field may be blank.
      \note If this input field is left blank, then the design cooling capacity is set to zero.
      \note CoolingDesignCapacity => selected when the design cooling capacity value is specified or
      \note auto-sized. CapacityPerFloorArea => selected when the design cooling capacity is determined
<snip>
 N21, \field Cooling Design Capacity
      \type real
      \units W
      \minimum 0.0
      \autosizable
      \default autosize
```
With both of these fields blank (current state of ExpandObjects), this error comes out:
```
   ** Severe  ** Sizing:System = FURNACE DX 1-1
   **   ~~~   ** Input for Cooling Design Capacity Method = COOLINGDESIGNCAPACITY
   **   ~~~   ** Blank field not allowed for Cooling Design Capacity
```
If Cooling Design Capacity defaults to autosize, then blank should be acceptable. I'm updating all the field names in expandobjects anyway for clarity, but the getinput needs fixing here.

**Comment by mjwitte** [comment]
@wfbuhl I was going to add this field to the sizing:system objects coming out of ExpandObjects, but I'm not sure what to put.  If the default is VAV, is that consistent with what the "old" calcs were doing?  So, VAV = no change in results.  But ultimately, for, say a unitary system one of the other choices seems better suited, but that could change results?  What would you recommend - write VAV for all system types to maintain the same results, leave this field blank (which will result in VAV but not look silly for constant flow systems), or put in the appropriate choices and let results change.  Searching the modified idf files, looks like VAV has been used for all system types.

**Comment by Myoldmopar** [comment]
If it is marked as a required-field, will the input processor fill in 'autosize' so that the GetInput routine never see a blank?

**Comment by mjwitte** [comment]
If it's within min-fields the it will get filled with the default, but I 
don't remember if filling with default clear the blank flag, I guess it 
should.  Definitely don't want to make this required.

**Comment by mjwitte** [comment]
@Myoldmopar And technically, it's not just blank, the filed isn't even there, so if the getinput is doing a check on number of N fields, that may be part of the confusion?

**Comment by mjwitte** [comment]
@Myoldmopar @wfbuhl Hold on about the get input processing - some confusion here about whether EnergyPlus was rebuilt for this branch.

**Comment by mjwitte** [comment]
@Myoldmopar @wfbuhl Never mind on the getinput stuff.  The HVACTemplate files are running ok even without any expandobjects changes. We're just getting rid of these warnings:
```
   ** Warning ** IP: Note -- Some missing fields have been filled with defaults. See the audit output file for details.
```
Ultimately, it's good to get the field names in synch anyway.  And I see that these changes do impact sizing, even with defaults.  So, maybe I should be varying the coil control input for different system types?

**Comment by Myoldmopar** [comment]
OK cool.  Well thanks for addressing ExpandObjects and getting rid of those warnings.  Does the coil control input variation belong in this PR as well or can it be marked as a future enhancement?  

ExpandObjects was the last issue I remember seeing on this PR, so after it is addressed I don't think I need anything further code wise (doc changes should go over [here](https://github.com/NREL/EnergyPlusBuildSupport/tree/master/docs/src/mods/for_2015_03_release)).  I'll handle a merge back from develop if we are settled on the code for one last CI pass.

**Comment by mjwitte** [comment]
@Myoldmopar I'm almost done.  Making a second pass to clean up all the other object that got new field names from the changes for "during Cooling ..." to "Cooling ...".

**Comment by mjwitte** [comment]
@Myoldmopar That should be all for the expandobjects updates (even got rid of two longstanding IP warnings about missing fields being filled with defaults in HVACTemplate-5ZoneConstantVolumeChillerBoiler and HVACTemplate-5ZoneFanCoil-DOAS).  Let the CI times roll.

**Comment by Myoldmopar** [comment]
Welp, beef0e9 should be it.  I merged develop.  There were some conflicts with idfs that seemed to get worked out.  I am currently spot testing and then if something went awry I'll remedy it and push up again (maybe not til morning).

**Comment by Myoldmopar** [comment]
OK, something _did_ go awry in that merge process, and it was serious enough that I couldn't wait until morning.  There will be lots of failures in beef0e9, but beefe5d should be much better.  

If all goes well overnight, I think this will be able to merge in the morning.

@mjwitte @wfbuhl @EnergyArchmage @larryscheier

**Comment by Myoldmopar** [comment]
HospitalLowEnergy had a second EIR chiller that got messed up in transition.  I remedied that and looked over the diffs again.  Things will be good to go when that goes in.  CI is already testing it, so it shouldn't be long now...

**Comment by wfbuhl** [comment]
A11; \Central Cooling Capacity Control Method
      \note Method used to control the coil's output
      \type choice
      \key VAV
      \key Bypass
      \key VT
      \key OnOff
      \default VAV

Setting this field to "OnOff" will result in no change to the results.
Generally, this field should be set based on the system used in the actual
simulation. The only way to do this is to go through the test files by
hand!

Fred

**Comment by Myoldmopar** [comment]
Are you saying the IDD needs to be changed for ```\default OnOff```?

**Comment by wfbuhl** [comment]
It is up to you. Might be a good idea.

Fred

**Comment by Myoldmopar** [comment]
*sigh*  OK.  It'll have to be a brand new PR.  I'll make an issue out of it.

**Comment by EnergyArchmage** [comment]
I got a hard crash in SimAirServingZones.cc, line 4790 while running 5ZoneVAV-ChilledWaterStorage-Mixed.idf.  SysTotCoolCap was being used without being initialized.  It appears that an init for SysTotCoolCap is needed around line 4722.

**Comment by wfbuhl** [comment]
Yes; not sure how this got through. Am I running with uninitialized
variables set to zero?

Fred

**Pull request merged**
