### PR TITLE
Cooling Towers may fail to autosize tower UA

### PR DESCRIPTION
**Pull request by rraustad**
## Pull request overview

Calculation of tower UA fails if NominalCapacity method is selected and high speed air flow rate and free convection air flow rate are autosized. This corrects issue #4262. Example file differences are not expected.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [x] Argument types
  - [x] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by rraustad** [comment]
I see unit test ZoneTempPredictorCorrector_ReportingTest fail here (last line) where OpStartData.ActualZoneNum has not been allocated. But OptStartData.OptStartFlag hasn't been allocated either (size=0) so why does the code go into the IF block?

line 2953 ZoneTempPredictorCorrector.cc

```
if ( allocated( OptStartData.OptStartFlag ) ) {
    if ( ! allocated( DaySPValues ) ) {
        DaySPValues.allocate( NumOfTimeStepInHour, 24 );
    }
    if ( OptStartData.ActualZoneNum( ActualZoneNum ) == ActualZoneNum ) {
```

Both of these are only allocated if there is an optimum start availability manager in the input so why does the unit test fail while all example files run without a problem?

**Comment by mjwitte** [comment]
@rraustad That's odd.  I just ran all of the unit tests with develop (Win64 debug) and they all ran successfully.

**Comment by rraustad** [comment]
I wait to see what the CI says.

**Comment by EnergyArchmage** [comment]
I am seeing the same test failure here (  ZoneTempPredictorCorrector_ReportingTest )

**Comment by rraustad** [comment]
I don't see that array in the clear_state in ZoneTempPredictorCorrector, maybe that's it? Although I did see size=0 while looking into this unit test.

**Comment by rraustad** [comment]
I see this in the clear_state in DataHVACGlobals.cc. Is that the same as deallocate?

```
    OptStartData = OptStartDataType();
```

**Comment by rraustad** [comment]
Adding this line just before the offending line in the unit test allows it to pass. So this must have something to do with how this is deallocated in clear-state.

```
OptStartData.OptStartFlag.deallocate();
CalcZoneAirTempSetPoints();
```

If an array gets allocated in a previous unit test then what does this clear_state line actually do?
    OptStartData = OptStartDataType();

If I run all the unit tests through the debugger, when I get to this unit test deallocate statement (the new one I just added) this array looks like this:

optstart1

And this is what I get just after the new deallocate line:

optstart2

So something is obviously different. I suggest adding this line to the clear_state until we figure this out.

**Comment by rraustad** [comment]
Modified clear-state and this unit test passes now.

```
OptStartData = OptStartDataType();
// unit test ZoneTempPredictorCorrector_ReportingTest fails without this next line. Next 2 lines are just to be thorough.
OptStartData.OptStartFlag.deallocate();
OptStartData.ActualZoneNum.deallocate();
OptStartData.OccStartTime.deallocate();
```

**Comment by rraustad** [comment]
@Myoldmopar this should take care of the issue.

**Comment by rraustad** [comment]
Where do I find the file: integration.ASIHPMixedTank

**Comment by mjwitte** [comment]
ASIHPMixedTank is in \testfiles

**Comment by rraustad** [comment]
The one file that fails is ASIHPMixedTank. I ran that file here in debug mode and the simulation runs to completion. The error file is clean except for what is a bad input in the example file. Compiling release mode now but expect this to run here as well.

```
Program Version,EnergyPlus, Version 8.6.0-a237d0aea7, YMD=2016.08.26 08:51,IDD_Version 8.6.0
   ************* SizeFan: : Potential issue with equipment sizing for Fan:OnOff HPWHOUTDOORFAN
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 2.26850
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.26850
   ************* EnergyPlus Completed Successfully-- 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min 22.84sec

WaterHeater:HeatPump:PumpedCondenser,
  OutdoorHeatPumpWaterHeater,  !- Name
  0.2685,                  !- Evaporator Air Flow Rate {m3/s}
  Fan:OnOff,               !- Fan Object Type, Fan:OnOff
  HPWHOutdoorFan,          !- Fan Name

Fan:OnOff,
  HPWHOutdoorFan,          !- Name
  2.2685,                  !- Maximum Flow Rate {m3/s}
```

**Comment by rraustad** [comment]
UPDATE: ASIHPMixedTank runs in release mode here.

```
  ************* EnergyPlus Completed Successfully-- 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  3.79sec
```

**Comment by JasonGlazer** [comment]
@rraustad do you know if the EnergyPlusFixture.ZoneTempPredictorCorrector_ReportingTest issue been fixed in "develop"? I am still running across it.

**Comment by rraustad** [comment]
Im not aware of a problem with ZoneTempPredictorCorrector_ReportingTest

**Comment by JasonGlazer** [comment]
https://github.com/NREL/EnergyPlus/pull/5831#issuecomment-241816415

**Comment by EnergyArchmage** [comment]
I just built develop and still get the test failure in ZoneTempPredictorCorrector_ReportingTest when running all the tests together.  It passes when run by itself (which is what CI does). Maybe this needs its own issue.

**Comment by rraustad** [comment]
OK, I remember now. The comment I made above about the unit test ZoneTempPredictorCorrector_ReportingTest failing was due to how clear-state "tried" to deallocate the OptStartData array. If you look at the screen shot of my debugger above, this clear_state line did not remove the array from memory. I tried to use a deallocate on this array in the DataHVACGlobals clear_state function (i.e., OptStartData.deallocate) but it would not compile I guess due to how this array is declared.

```
OptStartData = OptStartDataType();
```

I corrected that issue in this branch using this method so this should be fixed now (unless someone has a better suggestion).

See this part of this PR (DataHVACGlobals line 584):

```
OptStartData = OptStartDataType();
// unit test ZoneTempPredictorCorrector_ReportingTest fails without this next line. Next 2 lines are just to be thorough.
OptStartData.OptStartFlag.deallocate();
OptStartData.ActualZoneNum.deallocate();
OptStartData.OccStartTime.deallocate();
```

**Comment by JasonGlazer** [comment]
@rraustad and @EnergyArchmage thanks for verifying that this is an issue with develop. Hopefully someone will review and merge this pull request soon.

**Comment by mjwitte** [comment]
Interesting, I just pulled develop, made a debug build and ran all the unit tests and EnergyPlusFixture.ZoneTempPredictorCorrector_ReportingTest did not fail.  I'm using VS2015 Community version 14.0.24720.00 Update 1 with Visual C++ 2015  Maybe this is a compiler bug that was fixed?

**Comment by mjwitte** [comment]
@rraustad This fixes the initial defect file.  I tried to make another test file based on 5ZoneWaterCooled_Baseboard and at first, it failed to size the UA if the free convection capacity was too large compared to the nominal capacity.  When the UA fails, it would be nice if the error could give some other information or some hints.  

And it's somewhat annoying that the NominalCapacity method errors out if certain fields are autosized that it doesn't like.  Seems it should just warn and move on.  

```
   ** Severe  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal capacity input method has been specified and design water flow rate is being autosized.
   **   ~~~   ** Design water flow rate must be left blank when nominal tower capacity input method is used.
   ** Severe  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal tower capacity has been specified and design tower UA is being autosized.
   **   ~~~   ** Design tower UA field must be left blank when nominal tower capacity input method is used.
   ** Severe  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal capacity input method has been specified and free convection UA is being autosized.
   **   ~~~   ** Free convection UA should be left blank when nominal tower capacity input method is used.
   **  Fatal  ** Errors found in getting cooling tower input.
```

**Comment by rraustad** [comment]
5ZoneWaterCooled_Baseboard-NomCapMethod-UAFail defect file:

```
 ** Severe  ** Bad starting values for UA calculations
 **   ~~~   ** Tower inlet design water temperature assumed to be 35.0 C.
 **   ~~~   ** Tower inlet design air dry-bulb temperature assumed to be 35.0 C.
 **   ~~~   ** Tower inlet design air wet-bulb temperature assumed to be 25.6 C.
 **   ~~~   ** Tower load assumed to be 1.25 times free convection capacity at 12500 W.
 **   ~~~   ** Tower capacity at lower UA guess (1.2500) = 49 W.
 **   ~~~   ** Tower outlet water temperature at lower UA guess = 34.99 C.
 **   ~~~   ** Tower capacity at upper UA guess (12500.0000) = 6314 W.
 **   ~~~   ** Tower outlet water temperature at upper UA guess = 34.29 C.
 **   ~~~   ** Free convection capacity should be less than tower capacity at upper UA guess
 **  Fatal  ** Autosizing of cooling tower UA failed for tower CENTRAL TOWER
```

**Comment by mjwitte** [comment]
@rraustad That's more info than before, maybe too much.  I'm confused by these:

```
 **   ~~~   ** Tower load assumed to be 1.25 times free convection capacity at 12500 W.
 **   ~~~   ** Tower capacity at lower UA guess (1.2500) = 49 W.
 **   ~~~   ** Tower outlet water temperature at lower UA guess = 34.99 C.
 **   ~~~   ** Tower capacity at upper UA guess (12500.0000) = 6314 W.
```

The input value in question is 10,000, so it would help to see that directly in the error message.  And why are the UA guesses 1.25 to 12500?  What drives those guesses?

**Comment by rraustad** [comment]
Eng.Ref. pg 546. Upper UA is assumed to be equal to a tower load of 1.25 (user input) times the free convection capacity (10000 \* 1.25). Lower UA guess is equal to this value divided by 10000.

9.7.20.4 Tower UA Value at Design Air Flow Rate
To obtain the UA of the tower, we specify the model inputs (other than the UA) at design
conditions and the design tower load that the tower must meet. Then we numerically invert
the tower model to solve for the UA that will enable the tower to meet the design tower load
given the specified inputs.
The design tower load is:
for Tower Performance Input Method = UFactorTimesAreaAndDesignWaterFlowRate
_ Qtower; des = Cp;w  w  _V
tower;w; des  ΔTloop; des (9.97)
for Tower Performance Input Method = NominalCapacity
Q_ tower; des = 1:25 x Q_ tower; nom (to allow for compressor heat)
Where, fdes;heat;ratio is the ratio of actual heat rejection capacity to nominal capacity.
This ratio is available as a user input with a default value of 1.25 (to allow for compressor
heat).
Then we assign the inputs needed for the model.
Tin;air = 35 oC (95 oF design air inlet temperature)
Tin;air;wb = 25.6 oC (78 oF design air inlet wetbulb temperature)
Win is calculated from the entering air drybulb and wetbulb.
The inlet water mass flow rate is just the design volumetric flow rate times the density
of water.
The inlet water temperature is set slightly differently for the 2 input methods. For
UFactorTimesAreaAndDesignWaterFlowRate
Tin;water = Tloop;exit;des+DTloop;des
NominalCapacity
Tin;water = 35 oC (95 oF design inlet water temperature).

**Comment by rraustad** [comment]
5ZoneWaterCooled_BAseboard-NomCapMethod-AutosizedEverything defect file:

```
 ** Warning  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal capacity input method has been specified and design water flow rate is being autosized.
 **   ~~~   ** Design water flow rate will be set according to nominal tower capacity.
 ** Warning  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal tower capacity has been specified and design tower UA is being autosized.
 **   ~~~   ** Design tower UA will be set according to nominal tower capacity.
 ** Warning  ** CoolingTower:SingleSpeed "CENTRAL TOWER". Nominal capacity input method has been specified and free convection UA is being autosized.
 **   ~~~   ** Free convection UA will be set according to nominal tower capacity.
 ************* Testing Individual Branch Integrity
 ************* EnergyPlus Completed Successfully-- 91 Warning; 3 Severe Errors; Elapsed Time=00hr 00min 39.63sec
```

**Comment by rraustad** [comment]
Revised warning. If there is something too detailed, let me know which part.

```
 ** Severe  ** Bad starting values for UA calculations
 **   ~~~   ** Tower inlet design water temperature assumed to be 35.0 C.
 **   ~~~   ** Tower inlet design air dry-bulb temperature assumed to be 35.0 C.
 **   ~~~   ** Tower inlet design air wet-bulb temperature assumed to be 25.6 C.
 **   ~~~   ** Tower load assumed to be 1.250 times free convection capacity of 10000 W.
 **   ~~~   ** Tower capacity at lower UA guess (1.2500) = 49 W.
 **   ~~~   ** Tower capacity at upper UA guess (12500.0000) = 6314 W.
 **   ~~~   ** Free convection capacity should be less than tower capacity at upper UA guess.
 **  Fatal  ** Autosizing of cooling tower UA failed for tower CENTRAL TOWER
```

**Comment by mjwitte** [comment]
I'll have to review this in more detail.  Capacity is UA times some deltaT but the deltaT seems missing  here in the starting guesses.

**Comment by rraustad** [comment]
Right. Q = UA \* dT. So if starting guess for upper UA = Q then dT = 1. dT should never be less than 1. If I increase the starting guess for upper UA (i.e., allowing dT to be < 1) then I am worried about unrealistic HX performance. I guess to be accurate, dT should be the plant sizing dT but I figured RegulaFalsi could find the right answer.

**Comment by mjwitte** [comment]
@rraustad Well this is a step in the right direction.  I still find the tower sizing assumptions a bit quirky, but this can be reviewed when #5020 and #5034 are addressed.

**Pull request merged**
