### PR TITLE
Final 8.3.0 work now that RCs are in process

### PR DESCRIPTION
**Pull request by Myoldmopar**
- [X] Clean up outdated manual release files (examplefiles.xls, etc...)
- [x] Get rules file updated with transition changes
- [x] Make sure build commands work with these new changes, like [this](http://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-v8.3.0-Win64-Windows-7-VisualStudio-12.html#package)
- [x] Clean bash operator error message during Linux installer
- [x] Changelog script doesn't get the Github token or something
- [x] Update README
- [x] Resolve whether we need the tar.gz and tar.Z Linux packages; it would be nice to disable unneeded cycles
- [x] Modify IDFVersionUpdater so it comes out as executable
- [x] IDFVersionUpdater.app is not working on Mac.  .app structure incorrect or dependencies missing.
- [ ] EPLaunchLite.app cannot find weather files.
- [ ] Is that the correct license.txt file?
- [x] Consider updating or removing EnergyPlus Quick Start Guide.pdf (Mac) according to CLI. (Considered: not going to do it yet. See next related item)
- [x] Does runenergyplus script stay or go with introduction of CLI? (Answer: Stay)
- [ ] Add any more problems found right here
- [ ] Remember to close any of the below issues when merging this

Make sure these issues are fixed:
- [x] #4780: Need to add 8.2 idd file and install commands
- #4718: Version Error Message
  - I think this is just an iteration problem, not a release problem.
- [x] #4571: Broken symlinks in Linux installer
  - I'm taking out dos2unix
  - The symlink to EnergyPlus didn't work since it is now lower case
  - IDFVersionUpdater isn't executable--now changed in BuildSupport
- [X] #4484: System sizing transition
  - Ran 5ZoneAirCooled which contains system sizing using packaged 8.2 to 8.3 transition, and the new 8.3 file ran perfectly fine.
- [ ] #4456: Transition for v8.1 to v8.2 is tripping on CoolingTower:TwoSpeed
  - This may be fixed with beef0ab; I'll test out a specific two-speed cooling tower file plus a full transition from like v1 to v8.3 for a misc file and make sure it's ok

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@kbenne So something is up with the CMake/environment.  The changelog isn't getting the GITHUB_TOKEN variable properly or something.  If I run the changelog script manually, passing in the github_token as an argument, it works perfect.  If I set the GITHUB_TOKEN variable in the environment and run make package, it gives an HTTP 401 unauthorized error and won't complete.  This had worked for me before when the autodocs scripts were a PRE_BUILD target, so I don't think it's something wrong with the changelog script itself.  Probably just an anomaly related to moving those commands into Install.cmake.  

Thoughts?

**Comment by Myoldmopar** [comment]
@kbenne OK, sorta scratch that.  I started anew, and passed GITHUB_TOKEN on the command line for each of ```ccmake```, ```make```, and ```make package```, and it worked fine.  I should've just exported it to begin with.  Anyway, I think everything is fine; we'll see on the next CI release candidate.  Carry on...

**Comment by Myoldmopar** [comment]
@kbenne Is [this line](https://github.com/NREL/EnergyPlus/blob/f981a5e5c3ac3c0f0a2a17fe2301ef937f7724d2/cmake/CPack.STGZ_Header.sh.in#L74) supposed to be setting the IDFVersionUpdater binary to executable?  I tried to set the executable bit on the binary in BuildSupport, but that didn't work, then I found that line.  The IDFVersionUpdater *folder* _is_ coming out as executable, but the binary inside _isn't_.  Not a big problem, most Linux users will see what's up, but if that line just needs a ```-R```, it's probably worth just fixing it now.

**Comment by kbenne** [comment]
@Myoldmopar  Re "So something is up with the CMake/environment."  I have intermittently seen this when building packages locally.  Flakey erratic behavior.  Not exactly confidence building.

**Comment by Myoldmopar** [comment]
Thanks for the reply.  I tried a brand new build, and this time, before doing any cmake stuff, I ```export```ed the github token to the environment.  I ran ccmake, make, and make package and it worked _perfectly_.  There might still be some flakiness, but I feel OK with this part of it.

**Comment by kbenne** [comment]
@Myoldmopar Re: " Is this line supposed to be setting the IDFVersionUpdater binary to executable?" well that is probably a solution of last resort.  I think what you need is this https://github.com/NREL/EnergyPlus/blob/develop/cmake/ProjectMacros.cmake#L5.  The directory is executable because that is how directories are in general.  I suspect the line you reference is adding write access because the program writes some crud to the executable directory when it does its work.

**Comment by Myoldmopar** [comment]
@kbenne Do we need the other Linux packages (tar.gz, tar.Z)?  If not, I'd like to disable them.

**Comment by kbenne** [comment]
No we don't need them.   But disable in yaml not in cmakelists.

**Comment by kbenne** [comment]
you definitely have to export the environment variables, but I am certain this behavior is still intermittent.  I have observed it with my own eyes, repeatedly issuing the same build command and it working one moment and the next not.

**Comment by Myoldmopar** [comment]
@lefticus, the decent_ci yaml file for Linux has ```"STGZ"``` as the generator.  How do you recommend we tell the generator to only make the ```sh``` package and not the ```tar.gz``` or ```tar.Z``` packages?

**Comment by kbenne** [comment]
@Myoldmopar are you positive the other types are being built?

**Comment by Myoldmopar** [comment]
image

**Comment by kbenne** [comment]
@Myoldmopar that looks like a local build.  to turn those off, disable the cpack cache variables.

**Comment by lefticus** [comment]
@Myoldmopar, @kbenne is correct. I'm directly calling cpack with the specific generator(s) listed for packaging.

**Comment by Myoldmopar** [comment]
Great, thanks!

**Comment by Myoldmopar** [comment]
@kbenne I would recommend leaving the run* scripts as-is for this release.  We'll use the 8.4 (9.0?) development cycle to start working on updating all the documentation for CLI and providing better guidance for using it.  I won't check the box above for it, but that would be my recommendation.

**Comment by Myoldmopar** [comment]
@kbenne wrote:
> well that is probably a solution of last resort. I think what you need is this
> https://github.com/NREL/EnergyPlus/blob/develop/cmake/ProjectMacros.cmake#L5. The directory is
> executable because that is how directories are in general. I suspect the line you reference is adding
> write access because the program writes some crud to the executable directory when it does its 
> work.

My mistake when looking at the permissions.  Yes, all the directories are executable, that one looked different because of the o+w giving _others_ write access on that directory.  I guess it's not a problem, but the IDFVersionUpdater should still get +x.  I'll look at the line you referenced to get the right form.  Thanks.

**Comment by Myoldmopar** [comment]
@kbenne OK, so I changed it to PROGRAMS and now it _does_ come down with executable permission.  However, I am not able to run it.  May be the same problem you mention above on Mac:

``` sh
$ ./IDFVersionUpdater
Failed to find/load Framework library
/tmp/EnergyPlus-8-3-0/PreProcess/IDFVersionUpdater/./RBGUIFramework.so: cannot open shared object file: No such file or directory

$ ldd ./IDFVersionUpdater
	linux-gate.so.1 =>  (0xf7718000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf76eb000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf76cf000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7520000)
	/lib/ld-linux.so.2 (0xf771b000)
```

**Comment by kbenne** [comment]
Yep.  Same issue I think.  Might need @JasonGlazer's help on this, but so far I'm not sure this isn't specific to our install commands which are retrieving the payload out of build support file by file.

**Comment by Myoldmopar** [comment]
@kbenne Yep.  That's it.  If you look over there in BuildSupport, @JasonGlazer just updated the files, which included adding some new shared libraries.  They just need to be added over here.  I'm going to be offline for a couple hours, so if you are able to add them in now, that'd be great.  If not, I'll do it later.  I'll be back on this evening.

**Comment by kbenne** [comment]
I'll try.  At the moment I'm trying to figure out why the gfortan runtime is not installed on linux.

**Comment by JasonGlazer** [comment]
I recompiled IDFVersionUpdater with a much newer version of the compiler to try to get the MacOS version working. See check in message at:

https://github.com/NREL/EnergyPlusBuildSupport/commit/8998b06211ef9c1c58e06e820d37ea007dff112f

Let me know if you need any help.

**Comment by mjwitte** [comment]
I agree.  Seems awfully late in the game to be moving anything around.

**Comment by Myoldmopar** [comment]
@kbenne I'm getting build errors with the statically built Fortran:
``` sh
CMake Error at /home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch/builds/8.3.0-Wrap/rpackage/src/ExpandObjects/cmake_install.cmake:45 (FILE):
  file RPATH_CHANGE could not write new RPATH:

    $ORIGIN

  to the file:

    /home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch/builds/8.3.0-Wrap/rpackage/_CPack_Packages/Linux/STGZ/EnergyPlus-8.3.0-6e33f55ba1-Linux-x86_64/EnergyPlus-8-3-0/./ExpandObjects

  No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
  /home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch/builds/8.3.0-Wrap/rpackage/cmake_install.cmake:1439 (INCLUDE)
```

Occurs on all the Fortran stuff now.  *Very* closely resembles [this](http://www.cmake.org/pipermail/cmake/2013-September/055755.html)

**Comment by Myoldmopar** [comment]
Also, @kbenne, the last commit (beefe92) adds the required RealBasic libraries for Windows and Linux.  Some questions arose:
 - On Windows, there were msvc*.dll files added.  I went ahead and included them here, without thinking of any issues.  
 - On Linux, there was a similar libc++.so file.  I also included that.
 - On Mac, there was a new file added (.app.tar), but I didn't know where the install command should put that.

I couldn't test these very well since the Fortran issues stopped the package from building.  If I don't hear from you in a while, I'll try re-disabling the static flag temporarily to test out the install command additions.

**Comment by Myoldmopar** [comment]
@kbenne Confirmed that when I take static back out to get the package to build, the new install commands properly bring in enough real basic libraries for IDFVersionUpdater to work.

If you want to run an RC tonight, I think the static issue will either have to be resolved or temporarily backed out to get it to build on Linux.  Let me know if I can provide any info, or if you want me to back it out or whatever.

**Comment by kbenne** [comment]
Yes i spent the afternoon with that blasted rpath problem.  I think i finally have a solution and will implement later tonight before i make RC.

I deliberately omitted  libc++.so file because I don't think it is such a great idea to ship it.  Or at least seems like bad form.

that tar is not part of the .app bundle but might need something out of it to get app working.  On my list.

**Comment by kbenne** [comment]
oh.  and if you are wondering why i switched to static in the first place, i have a good reason, but it is a little long winded.  I'll explain later.

**Pull request merged**
