### PR TITLE
Fix static Fortran compilation

### LINKED ISSUE #5854: Can't build EnergyPlus on Centos 6.6
@Myoldmopar @lefticus 

I've tried building EnergyPlus 8.6 on Centos 6.6.  The default compiler is gcc 4.4 which doesn't seem to support c++11.  I get compiler crashes using gcc 4.7 and 4.8.  When I tried to install clang 3.4 I get GLIBCXX_3.4.15, GLIBC_2.15 and GLIBC_2.14 not found.  What compiler should I use?

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
This fixes #5854, but doesn't yet fix a couple of related issues that I discovered while looking into the original issue. The issue arises when trying to find library dependencies of the Fortran executables, which are static for some platforms/compilers. It worked in CMake 2.8.X, which is what Ubuntu 14.04 has, but for newer versions of CMake (e.g. the 16.04 version) it does not. Older versions of CMake were not checking the return code of `ldd`, which is 1 (failure) for static exes. Newer versions are checking, and the build bombs out. The earlier CentOS fix only fixed things for CentOS/Red Hat. The fix is to not call CMake's GET_PREREQUISITES on static Fortran executables. 

The related issues are:
 - [x] There are some naming irregularities that could use straightening out, investigating that, too.
 - [x] The missing GITHUB_TOKEN message in the Linux package build is a little vague.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this

### CODE REVIEW

**Comment by jasondegraw** [comment]
This is going to require testing that I can't do (Mac), so it shouldn't go in until after it has been thoroughly checked out. I've done some Linux testing, but need to do more.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 15 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Do you have specific tests that you want me to run with this?  I can kick off a Mac build if you'd like.

**Comment by jasondegraw** [comment]
@Myoldmopar A Mac build would be good. I only build Fortran and package on Linux, so it'd be nice to know that I haven't broken those on Mac. It'd also be good to know that I correctly renamed ParametricPreprocessor (with the old lowercase name the Windows install was relying on case insensitivity to work).

I haven't tried to fix what is included in the Linux package yet, but we could punt that to another issue/PR. Probably enough going on here already

**Comment by Myoldmopar** [comment]
This does show a problem on Mac.

With develop branch, the file is properly linked to local files during fixup:

```
$ otool -L _CPack_Packages/Darwin/STGZ/EnergyPlus-8.7.0-173bb58bcc-Darwin-x86_64-Debug/EnergyPlus-8-7-0/PostProcess/ReadVarsESO
_CPack_Packages/Darwin/STGZ/EnergyPlus-8.7.0-173bb58bcc-Darwin-x86_64-Debug/EnergyPlus-8-7-0/PostProcess/ReadVarsESO:
	@executable_path/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	@executable_path/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

On this branch, the file is still linking to the system library files, so users that don't have gfortran will have failures:

```
$ otool -L _CPack_Packages/Darwin/TGZ/EnergyPlus-8.7.0-cb35fc3b64-Darwin-x86_64-Debug/EnergyPlus-8-7-0/PostProcess/ReadVarsESO
_CPack_Packages/Darwin/TGZ/EnergyPlus-8.7.0-cb35fc3b64-Darwin-x86_64-Debug/EnergyPlus-8-7-0/PostProcess/ReadVarsESO:
	/usr/local/gfortran/lib/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/local/gfortran/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/gfortran/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

We've got something to investigate now, anyway.

**Comment by jasondegraw** [comment]
@Myoldmopar In addition to the failures on the Windows CI, I'm getting some local unit test failures in Release mode that I can't explain (but are present on develop as well). But everything that was understood and broken is now fixed. Theoretically this branch shouldn't be the problem, so I've forced a Windows CI rerun to see what happens.

**Comment by mjwitte** [comment]
@jasondegraw Windows CI results have been flaky for months.  e.g.  DELight files showing diffs that don't show on any other platform, other files showing no diffs on Windows CI that have diffs on other platforms.  It's almost like one of the builds in the regression tests isn't the right one.  Hoping you can find the culprit.

**Comment by rraustad** [comment]
@kbenne @macumber are either of you willing to review this and comment?

**Comment by Myoldmopar** [comment]
I'm re-testing this now to try to help wrap it up.  First, on Linux. I pulled the branch, and successfully built a package.  Nothing really new there.  But then I tried to merge latest develop into this branch, and my local Git client is telling me there are conflicts that need to be addressed.  Which don't show up here.  I've checked out develop, deleted my local static-fortran-fix branch, pulled, checked a new static-fortran-fix branch back out, and tried again.  Only to get:

```
$ git merge origin/develop 
Removing third_party/ObjexxFCL/src/ObjexxFCL/Time_Date.hh
Removing third_party/ObjexxFCL/src/ObjexxFCL/Time_Date.cc
Removing third_party/ObjexxFCL/doc/images/Objexx.logo.svg
Removing third_party/ObjexxFCL/doc/favicon.ico
Auto-merging third_party/ObjexxFCL/doc/css/Objexx.css
Removing third_party/ObjexxFCL/VARIANT
Auto-merging src/Transition/CMakeLists.txt
CONFLICT (content): Merge conflict in src/Transition/CMakeLists.txt
Auto-merging src/Slab/CMakeLists.txt
CONFLICT (content): Merge conflict in src/Slab/CMakeLists.txt
Auto-merging src/ReadVars/CMakeLists.txt
CONFLICT (content): Merge conflict in src/ReadVars/CMakeLists.txt
Auto-merging src/ParametricPreprocessor/CMakeLists.txt
CONFLICT (content): Merge conflict in src/ParametricPreprocessor/CMakeLists.txt
Auto-merging src/HVAC-Diagram/CMakeLists.txt
CONFLICT (content): Merge conflict in src/HVAC-Diagram/CMakeLists.txt
Auto-merging src/ExpandObjects/CMakeLists.txt
CONFLICT (content): Merge conflict in src/ExpandObjects/CMakeLists.txt
Auto-merging src/ConvertESOMTR/CMakeLists.txt
CONFLICT (content): Merge conflict in src/ConvertESOMTR/CMakeLists.txt
Auto-merging src/CalcSoilSurfTemp/CMakeLists.txt
CONFLICT (content): Merge conflict in src/CalcSoilSurfTemp/CMakeLists.txt
Auto-merging src/Basement/CMakeLists.txt
CONFLICT (content): Merge conflict in src/Basement/CMakeLists.txt
Auto-merging src/AppGPostProcess/CMakeLists.txt
CONFLICT (content): Merge conflict in src/AppGPostProcess/CMakeLists.txt
Auto-merging cmake/ProjectMacros.cmake
CONFLICT (content): Merge conflict in cmake/ProjectMacros.cmake
Automatic merge failed; fix conflicts and then commit the result.
```

They for the most part aren't significant, but I don't know what the heck is going on with them only showing up for me.

Anyway, I'll kick off a package build on Mac now and we'll go from there getting this all tested out and merged in soon.

**Comment by Myoldmopar** [comment]
I can confirm that the Linux and Mac builds both seem good with this. On Linux, in the build dir, ParametricProcessor is a statically linked binary, so of course ldd fails.  On Mac, in the build dir, ParametricProcessor is dynamically linked, and otool shows it depending on the libgfortran etc files in the build tree, not on the system.  I think that from a Mac/Linux standpoint this is good.  I have not done anything on Windows.

**Comment by Myoldmopar** [comment]
So on my Win7 VM, with Visual Studio 2017, I was able to build this branch successfully.  I ran the Fortran utilities in raw form (not setting up input files, etc.), and they seemed to run fine (didn't fail to find dependent library, for example).  I think maybe this is fine to go in now.

**Comment by Myoldmopar** [comment]
@jasondegraw what do you think here?  I have tested it on the different platforms, and it looks OK, but at the same time, our packages from CI seem to be coming out OK.  I just kicked off a CI package build of this branch, so I'll pull that and make sure everything seems OK from that on Mac/Linux.  If so, this can probably go on in.  @mjwitte Would you care to do a quick WIndows test of a Fortran utility or two to make sure they function OK?  The packages should be popping up [here](https://github.com/NREL/EnergyPlus/releases/tag/v8.8.0-StaticFortranFix).

**Comment by mjwitte** [comment]
@Myoldmopar Will test once the Win package shows up.

**Comment by jasondegraw** [comment]
@Myoldmopar @mjwitte I'll test the Windows package too

**Comment by Myoldmopar** [comment]
Confirmed the Linux package that CI built.  Fortran executables are static and run fine.

**Comment by Myoldmopar** [comment]
Confirmed the Mac package that CI built.  Fortran executables are dynamic, and dependent on lib files that are packaged up as part of the installer.  All good on the non-windows side.

**Comment by mjwitte** [comment]
No win packages yet?

**Comment by Myoldmopar** [comment]
It failed to package. Maybe @kbenne or @jasondegraw can help. Just check the dashboard for build info.

**Comment by Myoldmopar** [comment]
I don't have time to investigate this by Friday, so unless @jasondegraw or @kbenne can figure out the WIndows problem, this will have to be punted.

**Comment by mbadams5** [comment]
@Myoldmopar I was able to package on Windows in my Windows 10 VM with VS2015 using NSIS 3.02.1 so I don't know what is different on the CI machines.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jasondegraw it looks like this is close, but on the last set of CI results, there are some integration failures.  Could you take a look at [them](https://github.com/NREL/EnergyPlus/pull/6042#commitcomment-27753830) and then we can move to resolve this?

**Comment by jasondegraw** [comment]
@Myoldmopar Those look to be from when JSON (no relation) broke develop, I'll merge up and see if that fixes it.

**Comment by Myoldmopar** [comment]
OK, they all seem to be about the parametric preprocessor.  I was just wondering if a binary got renamed and cmake wasn't executing it properly or something.

**Comment by jasondegraw** [comment]
@Myoldmopar That still could be a problem, those went away at one point but may be back.

**Comment by Myoldmopar** [comment]
Looks much better now.  I'm going to tag this branch and let CI build packages from it today.  If all is well there this will merge.  Thanks @jasondegraw

**Comment by Myoldmopar** [comment]
@jasondegraw OK, this is close, and may be done.  When I tagged a build, CI was able to successfully build packages for all the platforms, but on the Mac it couldn't build the packagemaker image.  We've seen something similar in the past, and our workaround was always sorta ripe for coming back to haunt us.  You can see the packaging failures [here](http://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-FortranFix-x86_64-MacOS-10.9-clang.html#package).  I'm going to have @kbenne make one small change to the CI system before I do anything else, and we'll retry the build.  If it still fails, then I'll kick off a tagged package build of develop to verify we are still good on the develop side.  Then we will know where the problem lies at least.

**Comment by Myoldmopar** [comment]
(For the record, I was able to build a full PackageMaker installer package on my own Mac locally, so I don't think it's anything to do with your branch.  So hopefully the one tweak I plan with Marvin will take care of this.)

**Comment by jasondegraw** [comment]
@Myoldmopar Hooray? It's not my fault?

**Comment by Myoldmopar** [comment]
Well, it has happened over and over now.  Mac CI can't build this branch into a package, for some reason.  I'll investigate a little further, but I don't really know what is going on since the error message isn't super helpful.

**Comment by jasondegraw** [comment]
@Myoldmopar @kbenne The error message may not be great, but it does say there is a log file, can we get that?

**Comment by Myoldmopar** [comment]
@jasondegraw so the develop branch does still build package successfully across the platforms.  It seems it was something to do with this branch.  I'm continually checking for the CI box to get done with the Clang build (should be soon...) to see if your last change fixes it.

**Comment by Myoldmopar** [comment]
Same error occurred again...and I can't reproduce locally.  We tried to snag the log file but missed it.  @kbenne made a tweak and suggested we retry, so I just kicked off another build on CI.  We'll see what CI does say this time around...**then** we'll ask what @kbenne actually did to fix it.

**Comment by jasondegraw** [comment]
@Myoldmopar Did that last tag work?

**Comment by Myoldmopar** [comment]
I downloaded this to my Ubuntu machine and tested out some of the Fortran utilities.  They are functioning statically and nicely.  I'm downloading the Mac version now and will test that as well.  If that's happy, I'll merge.

**Comment by Myoldmopar** [comment]
Downloaded this to my Mac and tested some Fortran things there.  They are working well.  I'm merging this.  Thanks for sticking with this @jasondegraw and thanks for getting @nrel-bot-3 in shape @kbenne.

**Pull request merged**
