### PR TITLE
Add an Output Rules File; Other Minor Changes

### PR DESCRIPTION
**Pull request by Myoldmopar**
This branch will add the standard input Rules*.xls file to the source tree and change CMake to install it from local instead of EnergyPlusBuildSupport.  

This branch will also add a new output-driven Rules type of file to document any changes in the output structure/schema of EnergyPlus, beyond Report Variable changes.

Maybe other minor things as I go along.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar How about making the rules file a csv or other text format?  xls was a convenient format, but it's only for human consumption anyway.

**Comment by Myoldmopar** [comment]
CSV definitely came to mind, but I'm afraid there may need to be "examples" to really show interfaces the types of changes made, and they won't be very friendly to make in csv.  But maybe I'm wrong and CSV would be perfect.

As @kbenne would say, this _screams_ for some xml or json schema documentation, but I'd like to keep it simpler for the team.  If anyone else has thoughts, just comment here and we'll figure out a good solution.

**Comment by mjwitte** [comment]
Definitely good to move it here.  Will think about format.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@macumber @kbenne, as interface users of E+, what would suffice for you in terms of documenting output changes like #5295.  On the input side the Rules file _rules_.  On the output side, I could imagine a very simple file, even plain text, that documents the output in a descriptive fashion.  I'd kinda like to see this just start as a simple text file, and then grow organically into a different format instead of rigoring over format ahead of time and trying to coerce descriptions into that pre-defined form.  

Thoughts?  This is now blocking #5295.

@amirroth @mjwitte @JasonGlazer FYI

**Comment by macumber** [comment]
Any sort of documentation would be fantastic

**Comment by Myoldmopar** [comment]
Perfect; I'll include this png in the next release.

image

**Comment by macumber** [comment]
Well that beats dead silence

**Comment by Myoldmopar** [comment]
OK, added a plain text file.  If someone has a problem with this as a stop-gap, speak now, because this is going in _soon_ so we can get other work merged in.

@macumber @kbenne @mjwitte

**Comment by mjwitte** [comment]
@Myoldmopar This is good.  Minor quibble - "html table" could be more generic "output table" or "table output" which can impact all of the table output formats (html, csv, txt, and sql).

**Comment by Myoldmopar** [comment]
Which file are you referring to @mjwitte?  I'll make that change and update the README.  Oh wait, do you mean in the README?

**Comment by mjwitte** [comment]
Oui, monsieur, dans la readmoi.

**Comment by Myoldmopar** [comment]
OK, just missed CI picking up the previous commit.  @mjwitte if you have nothing further and @kbenne or @macumber seem satisfied, would you merge this after CI finishes with bc82335?

**Comment by mjwitte** [comment]
@Myoldmopar Did you intend for OutputChanges8-4-0-to-5-5-0.txt to be included in the install?

**Comment by JasonGlazer** [comment]
@Myoldmopar I think documenting the changes to the output files is a great idea that we probably should have been doing for years. A few comments:
- I agree using the text format is a good idea for now. I think it would be difficult to come up with a more standardized format until we go through a release or two. It could also be in Markdown format since that would allow some more structured formatting.
- In the README.md the statement "the output side does not move as often" is probably not accurate. I think additions and fixes to the tabular reports and other output files have occurred often but usually fly under the radar since they are not major changes.
- The scope of this should include all output files and should sometimes include the numeric values shown in the table if the algorithm related to the reported value changes. For example, the original goal of #5295 was going to just change how values were counted toward bins and whether the value should be rounded to the same number of digits as shown for that output variable. This doesn't happen often but should be documented. 
- Specifically, the ERR file should be included in the list of changes. For a recent project, I was regularly parsing the individual errors shown in the ERR file and it would be good to be notified if the message text was updated for a new version.

**Comment by mjwitte** [comment]
@JasonGlazer @Myoldmopar Fixed the file name, built an installer and tested that it shows up.  This is ready to merge unless you want to edit the readme first.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte; let's just merge it in.  I agree with your comments, but I don't want to wait on another CI pass.  When we add in the documentation over in #5295 to the output file we can update the README there.

**Pull request merged**
