### PR TITLE
Add Single-Sided Wind Pressure Coefficient Calculation Documentation

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
This is a documentation-only change to add in the advanced single-sided wind pressure calculation documentation and address #6004.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
So it looks like the Linux build is failing, which probably means the docs are failing so the whole thing just shuts down.  Are you able to build the docs?  Do you need me to look into it?

**Comment by jasondegraw** [comment]
@Myoldmopar I don't think so, I'll fire up my 14.04 VM and try building again. My Windows setup is... unique. I think I know what is wrong, though.

It looks like

https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex

isn't actually getting built. I'll try to verify that locally.

**Comment by jasondegraw** [comment]
@Myoldmopar I think I'm done here now. I fixed the original issue, added in the hybrid model documentation, and moved the RoomAir models into a separate file. If it comes back clean, it should be good to go.

**Comment by Myoldmopar** [comment]
Looks good.  Merging.

**Pull request merged**
