### PR TITLE
68304232 1e) move parent object sizing calcs to a common routine

### PR DESCRIPTION
**Pull request by rraustad**
AirloopHVAC:UnitarySystem sizing consolidation ready for review and merge.

### CODE REVIEW

**Comment by rraustad** [comment]
Design Document discussion:

@Myoldmopar wrote:
Thanks for sending this, and sorry for the delay.  This will be a great enhancement and nice that it will fix at least one bug in the process.  A couple comments:

    We likely won't want that raw pointer in the code to point to the appropriate array based on a condition.  Instead of declaring a pointer * first, then assigning it to the address of a variable, we'll want to declare a reference & and assign it to the appropriate variable.  Underneath the hood this might be the same thing, but creating a reference is safer than having a raw pointer out there.  A reference is essentially just another name, or an alias, for a variable.  However, this gets a little tricky.  References must be initialized with a variable to alias, and never changed.  Thus, it won't really work in the IF block like you have it because the variable will lose scope.  See the attached cpp file for an example of how scope will affect this.
    I think the cleanest option would actually be a very small wrapper function whose job it is is just to select the appropriate array, then continue the call.  Something like this:

    void wrapper( numA, numB, numC ) {
      if ( numA > 0 ) {
        call actual_worker( globalArrayA );
      } elseif ( numB > 0 ) {
        call actual_worker( globalArrayB );
      } elseif ( numC > 0 ) {
        call actual_worker( globalArrayC );
      } else {
         // some failure
      }
    }


Does that seem like a reasonable thing to do?  If not, just let me know and we can figure out some other magic to accomplish what you are trying to do there.

In summary, yes it's approved, but we'll work on some details of that pointer issue before merge.  I have clicked "Finish" and "Deliver" on the Pivotal ticket, but I'll leave it open while we work on the pointer issue, then click "Accept" when we actually merge it in.

Thanks,
Edwin

@rraustad replied:

This does work perfectly. When will it lose scope? When SizeUnitarySystem loses scope? That's what is intended. I guess I should try it with 2 different equipment types (e.g., zone and air loop) or all 3 if it's easy enough. I can change it to whatever is best, I just need help in doing that.

I should create a pull request so these conversations will be saved?

In SystemReports at line 2669 (and then again at 2785):

// Report selection
ReportLoopData * select_ThisReportData( nullptr );

if ( PlantLoopNum <= NumPlantLoops ) {
    { auto const SELECT_CASE_var( LoopSideNum );
    if ( SELECT_CASE_var == DemandSide ) {
        select_ThisReportData = &VentRepPlantDemandSide( PlantLoopNum );
    } else if ( SELECT_CASE_var == SupplySide ) {
        select_ThisReportData = &VentRepPlantSupplySide( PlantLoopNum );
    } else {
        assert( false );
    }}
} else { // CondLoop
    { auto const SELECT_CASE_var( LoopSideNum );
    if ( SELECT_CASE_var == DemandSide ) {
        select_ThisReportData = &VentRepCondDemandSide( PlantLoopNum - NumPlantLoops );
    } else if ( SELECT_CASE_var == SupplySide ) {
        select_ThisReportData = &VentRepCondSupplySide( PlantLoopNum - NumPlantLoops );
    } else {
        assert( false );
    }}
}

// Object Data
ReportLoopData & ThisReportData( *select_ThisReportData );

**Comment by rraustad** [comment]
Pivotal ID: https://www.pivotaltracker.com/story/show/68304232

**Comment by rraustad** [comment]
From above comment on design document, Re: "I guess I should try it with 2 different equipment types (e.g., zone and air loop) or all 3 if it's easy enough."

I created a single file with a zone unitary system, an air loop unitary system, and a unitary system in the air loop's OA system. This file ran successfully, and while executing the sizing routine, each of the 3 arrays updated as expected. I'm not saying there isn't a better (safer) way to accomplish this only that what is there now works correctly.

The whole point of this was to remove large if blocks in the sizing routine (see previous code) that were specific to each array type.
if ( CurOASysNum > 0 ) {
many lines of code using OASysEqSizing( CurOASysNum );
} else if ( CurSysNum > 0 ) {
many lines of code using UnitarySysEqSizing( CurSysNum );
} else if ( CurZoneEqNum > 0 ) {
many lines of code using ZoneEqSizing( CurZoneEqNum );
} else {
assert( false );
}

Now the code simply writes to EqSizing.* to store the data used by RequestSizing (which does use these 3 arrays and does have large if blocks of nearly duplicate code).

Whatever method accomplishes this simplified code in HVACUnitarySystem is OK with me.

**Comment by Myoldmopar** [comment]
@rraustad I merged develop in to see if this comes out clean from CI with one more pass.

**Pull request merged**
