### PR TITLE
Added reporting of sizing parameters when coil sizes to 0.

### LINKED ISSUE #4826: Relax fatal error for DX coil zero capacity or flow rate add more sizing output
DX coils (cooling and heating) will cause a fatal error if the capacity or flow rate is <= 0.0.  These should just be warnings.  Not sure if this was done to prevent divide by zero errors in the calc routines, so it may require more code than simply commenting out these blocks
				if ( ErrorsFound ) {
					ShowFatalError( "Preceding condition causes termination." );
				}

It would also be helpful for the dx heating coil (and others?) to report more sizing info including the design inlet and outlet air conditions to help diagnose why a coil may have sized to zero, for example.

### PR DESCRIPTION
**Pull request by rraustad**
Fixes #4826 

Error file using DisplayExtraWarnings:

   ** Warning ** SizeDXCoil: Potential issue with equipment sizing for Coil:Heating:DX:SingleSpeed PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT
   **   ~~~   ** ...Rated Total Heating Capacity = 0.
   **   ~~~   ** ...Air flow rate used for sizing = 1.96842 [m3/s]
   **   ~~~   ** ...Outdoor air fraction used for sizing = 0.11
   **   ~~~   ** ...Coil inlet air temperature used for sizing = 19.36 [C]
   **   ~~~   ** ...Coil outlet air temperature used for sizing = -15.00 [C]

### CODE REVIEW

**Comment by mjwitte** [comment]
@rraustad I'm trying to test this but I can't seem to get the dx coil to size to zero in v8.3.  What's the trick?  I tried the -15 heating supply temp, and I tried this in sizing:system
    HeatingDesignCapacity,   !- Heating Design Capacity Method
    0.0,                !- Heating Design Capacity {W}

but I still get a non-zero DX heating coil.

**Comment by rraustad** [comment]
I just ran the defect file. I guess I changed the heating SAT to get there but didn't have a problem. I'll try it again when I get home.

**Comment by rraustad** [comment]
Well, not sure what is different now. I mistakenly ran the 4794 HX SAT control issue defect file and ran into some uninitialized variables. Fixing those mistakes shows these warnings in the HX file:
   *\* Warning *\* SizeWaterCoil: Potential issue with equipment sizing for Coil:Heating:Water MECH_ZN_1_FLR_1 VAV BOX REHEAT COIL
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Air flow rate used for sizing = 0.00000 [m3/s]
   *\*   ~~~   *\* ...Plant loop temperature difference = 11.00 [C]
   *\* Warning *\* SizeHeatingCoil: : Potential issue with equipment sizing for Coil:Heating:Gas PSZ-AC_1:6_UNITARY_PACKAGE_HEATCOIL
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Capacity passed by parent object to size child component = -16582.25 [W]

Fixing the uninit variables also now report a different flavor of error in the defect file (4826). They are valid warnings since some sizing does not use CoilInTemp and CoilOutTemp to size the coil, a parent passes in the requested capacity.
   *\* Warning *\* SizeDXCoil: Potential issue with equipment sizing for Coil:Heating:DX:SingleSpeed PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Capacity passed by parent object to size child component = -79926.43 [W]
   *\* Warning *\* SizeDXCoil Coil:Heating:DX:SingleSpeed PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT
   *\*   ~~~   *\* ...Gross Rated Heating Capacity [W] will be limited by the minimum rated volume flow per rated total capacity ratio.
   *\*   ~~~   *\* ...DX coil volume flow rate (m3/s ) = 1.968423
   *\*   ~~~   *\* ...Requested capacity (W ) = 0.000
   *\*   ~~~   *\* ...Requested flow/capacity ratio (m3/s/W ) = 0.000
   *\*   ~~~   *\* ...Minimum flow/capacity ratio (m3/s/W ) = 4.027E-005
   *\*   ~~~   *\* ...Adjusted capacity ( W ) = 48880.652
   *\* Warning *\* SizeHeatingCoil: : Potential issue with equipment sizing for Coil:Heating:Gas PSZ-AC:1_UNITARY_PACKAGE_HEATCOIL
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Capacity passed by parent object to size child component = -79926.43 [W]
   *\* Warning *\* SizeHeatingCoil: : Potential issue with equipment sizing for Coil:Heating:Gas PSZ-AC:2_UNITARY_PACKAGE_HEATCOIL
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Capacity passed by parent object to size child component = -273221.95 [W]

The defect file used here had:
Sizing:System,  
    PSZ-AC:1,                 !- AirLoop Name
    -15.0,                    !- Central Heating Design Supply Air Temperature

Sizing:System,  
    PSZ-AC:2,                 !- AirLoop Name
    -15.0,                    !- Central Heating Design Supply Air Temperature

Sizing:System,  
    PSZ-AC:3,                 !- AirLoop Name
    40.0,                     !- Central Heating Design Supply Air Temperature

Sizing:System,  
    PSZ-AC:4,                 !- AirLoop Name
    40.0,                     !- Central Heating Design Supply Air Temperature

Now I see another uninit. Expect another commit.

**Comment by rraustad** [comment]
I'd like to be able to stop-the-bot at times when I find something else that needs correcting and will need to make a second commit on the same branch to correct it.

**Comment by rraustad** [comment]
What does this mean? Noticed it on the last push.

remote: This repository moved. Please use the new location:
remote:   https://github.com/NREL/EnergyPlus.git

**Comment by Myoldmopar** [comment]
Stopping the bot has come up but there are some major issues with skipping
commits. We could look at it again sometime though.

Out looks like your repo might still be pointing to the old EnergyPlusTeam
repo that we renamed just EnergyPlus. In tortoise git there should be a
"remotes" menu or something where you can modify the url. I can help get
that straightened out tomorrow if you need any help.

**Comment by rraustad** [comment]
Here's another interesting result. The heating coil was sized to 0, then the DX coil flow/cap check said no and sized to the minimum flow/cap ratio. Then the simulation proceeded, operating at the rated flow rate during the simulation, and then the heating coil rode the TotCap curve and wound up at a much lower flow/cap ratio. At least that's what I think is happening without stepping through code...I'm done for the night.

   *\* Warning *\* SizeDXCoil: Potential issue with equipment sizing for Coil:Heating:DX:SingleSpeed PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT
   *\*   ~~~   *\* ...Rated Total Heating Capacity = 0.
   *\*   ~~~   *\* ...Capacity passed by parent object to size child component = -79926.43 [W]
   *\* Warning *\* SizeDXCoil Coil:Heating:DX:SingleSpeed PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT
   *\*   ~~~   *\* ...Gross Rated Heating Capacity [W] will be limited by the minimum rated volume flow per rated total capacity ratio.
   *\*   ~~~   *\* ...DX coil volume flow rate (m3/s ) = 1.968423
   *\*   ~~~   *\* ...Requested capacity (W ) = 0.000
   *\*   ~~~   *\* ...Requested flow/capacity ratio (m3/s/W ) = 0.000
   *\*   ~~~   *\* ...Minimum flow/capacity ratio (m3/s/W ) = 4.027E-005
   *\*   ~~~   *\* ...Adjusted capacity ( W ) = 48880.652
   *\* Warning *\* Coil:Heating:DX:SingleSpeed "PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT" - Air volume flow rate per watt of rated total heating capacity is out of range at 2.625E-005 m3/s/W.
   *\*   ~~~   *\*  During Warmup, Environment=MIAMI_FL_USA HEATING 99.6% CONDITIONS, at Simulation time=01/21 06:00 - 06:10
   *\*   ~~~   *\* Expected range for VolumeFlowPerRatedTotalCapacity=[2.684E-005--8.056E-005]
   *\*   ~~~   *\* Possible causes include inconsistent air flow rates in system components or
   *\*   ~~~   *\* inconsistent supply air fan operation modes in coil and unitary system objects.
   ************\*  *\* Warning *\* Coil:Heating:DX:SingleSpeed "PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT" - Air volume flow rate per watt of rated total heating capacity is out of range error continues...
   ************\*  *\*   ~~~   *\*   This error occurred 12430 total times;
   ************\*  *\*   ~~~   *\*   during Warmup 7002 times;
   ************\*  *\*   ~~~   *\*   during Sizing 0 times.
   ************\*  *\*   ~~~   *\*   Max=2.683999E-005  Min=2.574998E-005

**Comment by rraustad** [comment]
What the heck is happening. Why is my module I just checked in still marked as different (red check mark)? Did the last commit not work since I'm pointing at the wrong repo? If so, then where are my commits going?

**Comment by rraustad** [comment]
Here's what I got:
git.exe push --progress  "origin" 91362860-Relax-fatal-error-for-DX-coil-zero-capacity-or-flow-rate-add-more-sizing-output-#4826:91362860-Relax-fatal-error-for-DX-coil-zero-capacity-or-flow-rate-add-more-sizing-output-#4826

Counting objects: 41, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 739 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/NREL/EnergyPlus.git
To https://github.com/NREL/EnergyPlusTeam.git
03cc40d..088ac10  91362860-Relax-fatal-error-for-DX-coil-zero-capacity-or-flow-rate-add-more-sizing-output-#4826 -> 91362860-Relax-fatal-error-for-DX-coil-zero-capacity-or-flow-rate-add-more-sizing-output-#4826

Success (17250 ms @ 4/1/2015 11:02:55 PM)

So how do these code changes wind up here if I'm pointing to a different location? No wonder I never noticed this before.

**Comment by rraustad** [comment]
I don't see remotes.
tortgitmenu
gitconfig

**Comment by Myoldmopar** [comment]
So since we renamed the repo, github is simply passing your commits to the
new one. It gives you that message because I guess theoretically that could
stop at some point on the future.

The word remote is right under the selected tree node in the left side of
the bottom picture. I think from there you can choose to error the remote
URL and change it to EnergyPlus. Let me know if not and we'll get it worked
out.

**Comment by rraustad** [comment]
I've really got to get more sleep!
gitsettings

**Comment by mjwitte** [comment]
Tested new code and reproduced new messages.  Merging.

**Pull request merged**
