### PR TITLE
Remove FlowLock from Surface GHE

### PR DESCRIPTION
**Pull request by mitchute**
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Looks like another good set of changes, and I'm sure big diffs from the storage change.

**Comment by mitchute** [comment]
As in #7956, the authors were using ```FlowLock``` to determine if time had had advanced. This was incorrect and this corrects the behavior to only advance time when necessary.

GHE HT rate and outlet temperature don't seem to be too affected by this, but the changes to the chiller condenser entering water temperature don't look proportional to the diffs on the GHE.

Var_6
Var_11
Var_46

However, the condenser HT rates really haven't moved too much, so maybe it's all OK. Some diffs are expected due to the incorrect time advancement procedures.

Var_45

**Comment by rraustad** [comment]
More disturbing is the ground HX outlet temp IS the chiller condenser inlet temp and they were the same before but different now.

**Comment by Myoldmopar** [comment]
The diffs here are indeed pretty significant.  I'm wanting to definitely verify the diffs are purely due to the flowlock change.  I think I'm going to revert that one line, pull in develop, and let CI verify that.  If so it will be much easier to justify the diffs weren't accidentally introduced from one of the cleanup changes.

**Comment by Myoldmopar** [comment]
@mitchute when you get a chance, can you follow-up on what I kicked off here?  I was concerned about the diffs so I backed out the *actual* flowlock change.  There are now diffs, but I haven't had a chance to investigate.  I'm just wondering if the results look as bad now, indicating that the major diffs were due to some other change.  Or if the results look more aligned now, then it means the flowlock change was indeed the culprit.  We just need to see either way so we can proceed.  Thanks!

**Comment by mitchute** [comment]
@Myoldmopar This should clean up the diffs. Once CI reports back, we can drop those flowlock changes back in.

**Comment by mitchute** [comment]
Good call @Myoldmopar. This looks much nicer now.

Screen Shot 2020-06-09 at 12 47 14 PM

Screen Shot 2020-06-09 at 12 46 13 PM

**Comment by Myoldmopar** [comment]
Sooo much better!  Great job @mitchute, once CI reports, I'll take a final look and I suspect it'll be ready to drop in.

**Comment by Myoldmopar** [comment]
@mitchute looks like you got an unused variable warning.  The CI parser is catching the variable that is 'unused', but it's not showing you where it's 'unused'.  It's likely a `using` statement that is no longer needed.  If you aren't able to replicate the warning I can find it and fix it.  I think once that is fixed this can go in.

**Comment by mitchute** [comment]
@Myoldmopar I believe that will fix the issue.

**Comment by Myoldmopar** [comment]
:+1: thanks!  This should be good once CI is done.

**Comment by Myoldmopar** [comment]
What. the. heck. is up with that Windows failure?!  Couldn't copy expand objects?  I suspect a fluke.  I deleted the Windows results and will let it re-run.

**Comment by mitchute** [comment]
CI looks clean. Diffs on one file are expected here. Merging.

**Pull request merged**
