### PR TITLE
Fix crash in AirTerminal:SingleDuct:Mixer when DesignSpecification:OutdoorAir is shared across multiple Sizing:Zone objects

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Addresses #6399.
In Airterminal:SingleDuct:Mixer, if the Design Specification Outdoor Air Object Name field is left blank, the mixer gets the OA specs from the corresponding Sizing:Zone object. Before the fix, the mixer was actually using the pointer to the Sizing:Zone object rather than the OA spec object. If a single DesignSpecification:OutdoorAir was shared across several zones (which is common) this resulted in an array bounds crash.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by lgu1234** [comment]
@mjwitte 
I ran files with a blank field of OA specification in AirTerminal:SingleDuct:Mixer objects. No more crash. The fix is working.

I also checked file differences between 20171120 Propose_wDL_V890-AsOfNov28.idf and 20171120 Propose_wDL_V890-AsOfNov28-Fixed.idf. The differences are one file with a blank field and the other file with an object name of OA specification as “All_OA”.

Then I ran two test files and compared results from both CSV files. The results are identical. It means “All_OA” object index is assigned to the file with blank field. It makes me think a user may want to assign different OA specification objects, when there are many objects of OA specification.

Here is my suggestion. If there is a blank field of OA specification, we need to make a fatal error since this field is essential for sizing calculation, and let a user specify an object.

**Comment by mjwitte** [comment]
@lgu1234 Merged in develop and made some minor modification to a couple of warnings.

Three more defect test files have been added, with more design specification OA objects to show how the searching works.
```
20171120 Propose_wDL_V890-AsOfNov28-MultipleDSOAObject-Explicit.idf - various DSOA objects referenced explicitly in the ATMixer objects

20171120 Propose_wDL_V890-AsOfNov28-MultipleDSOAObject-AllBlank.idf - DSOA name blank in the ATMixer objects - all found from the various Sizing:Zone objects - should have identical results as "...-Explicit".

20171120 Propose_wDL_V890-AsOfNov28-MultipleDSOAObject-AllBlank-OneNotFound.idf - left the DSOA name blank in one zone to show the warning below - it's currently a warning - not fatal.

   ** Warning ** GetATMixers: AirTerminal:SingleDuct:Mixer="20F:LOBBY1 MIXER TERMINAL", invalid data.
   **   ~~~   ** Design Specification Outdoor Air Object Name is blank in both the mixer and the Sizing:Zone object for the same zone.
   **   ~~~   ** The mixer outdoor airflow rate is set to zero.
```

**Comment by lgu1234** [comment]
@mjwitte 
Tested all files with expected results. The correct index of OA specification is assigned to SysATMixer. It is ready to merge after all checks are complete. There is one successful check right now.

**Review by lgu1234 — APPROVED** [review]
It is ready to merge after all checks are completed.

**Pull request merged**
