### PR TITLE
Fix issues with previous version transition tools

### PR DESCRIPTION
**Pull request by Myoldmopar**
This fixes two transition issues:
- The cooling tower issue in 8.0 to 8.1 #4456 
- The evap cooler issue in 8.2 to 8.3 #4850 

My gut says this doesn't necessitate a re-release on its own.  But, if a re-release does happen, include this one.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mjwitte I assigned you here, but I will do the verification part and report to you about the status to reduce your burden.

**Comment by mjwitte** [comment]
@Myoldmopar OK.  We also need to get a corrected rules spreadsheet into buildsupport

**Comment by Myoldmopar** [comment]
@mjwitte OK, with a997755 the transition from 8.0 to 8.2 now completes without any warnings or messages.  That part of this should be good to go.  I'm testing the evap cooler changes next.  

Which rules spreadsheet?  The one from 8.0 to 8.1 looks correct to me, there was just an issue with the transition source.

**Comment by mjwitte** [comment]
If I'm not mistaken, Rules8-2-0-to-8-3-0.xls in the install packages is not correct.  It has some leftovers from 8-1-0-to-8-2-0 (e.g.PlantLoop, UnitHeater and UnitVentilator) and Sizing:System does not appear to be complete (or maybe it's old from 8.2 and needs to be replaced with the 8.3 changes).

**Comment by Myoldmopar** [comment]
As for #4850, here are the changes that the 8.3 install version produces:

```
--- /home/elee/tmp/transition_issues/evapcoolers_from_82_to_83/83InstallFiles/StripMallZoneEvapCooler.idfold
+++ /home/elee/tmp/transition_issues/evapcoolers_from_82_to_83/83InstallFiles/StripMallZoneEvapCooler.idfnew

@@ -4164,14 +4164,14 @@
   EvaporativeCooler:Direct:ResearchSpecial,
     LGstore1 Direct Evaporative Cooler,  !- Name
     ALWAYS_ON,               !- Availability Schedule Name
-    0.7,                     !- Cooler Effectiveness
-    55.0,                    !- Recirculating Water Pump Power Consumption {W}
+    0.7,                     !- Cooler Design Effectiveness
+    ,                        !- Effectiveness Flow Ratio Modifier Curve Name
+    55.0,                    !- Recirculating Water Pump Design Power {W}
+    ,                        !- Water Pump Power Sizing Factor {W/(m3/s)}
+    ,                        !- Water Pump Power Modifier Curve Name
     LGstore1 Indirect Outlet Node,  !- Air Inlet Node Name
     LGstore1 Inlet Node,     !- Air Outlet Node Name
-    LGstore1 Inlet Node,     !- Sensor Node Name
-    ,                        !- Water Supply Storage Tank Name
-    0.0,                     !- Drift Loss Fraction
-    3;                       !- Blowdown Concentration Ratio
+    LGstore1 Inlet Node;     !- Sensor Node Name

@@ -4450,22 +4450,22 @@
   EvaporativeCooler:Indirect:ResearchSpecial,
     SMstore5 Evaporative Cooler,  !- Name
     ALWAYS_ON,               !- Availability Schedule Name
-    0.7500,                  !- Cooler Maximum Effectiveness
-    ,                        !- Cooler Flow Ratio
-    55.0000,                 !- Recirculating Water Pump Power Consumption {W}
-    1.0,                     !- Secondary Fan Flow Rate {m3/s}
-    0.6000,                  !- Secondary Fan Total Efficiency
-    124.6000,                !- Secondary Fan Delta Pressure {Pa}
+    0.7500,                  !- Cooler Wetbulb Design Effectiveness
+    ,                        !- Wetbulb Effectiveness Flow Ratio Modifier Curve Name
+    ,                        !- Cooler Drybulb Design Effectiveness
+    ,                        !- Drybulb Effectiveness Flow Ratio Modifier Curve Name
+    55.0000,                 !- Recirculating Water Pump Design Power {W}
+    ,                        !- Water Pump Power Sizing Factor {W/(m3/s)}
+    ,                        !- Water Pump Power Modifier Curve Name
+    1.0,                     !- Secondary Air Design Flow Rate {m3/s}
+    1.0,                     !- Secondary Air Flow Scaling Factor {dimensionless}
+    Autosize,                !- Secondary Air Fan Design Power {W}
+    207.66666,               !- Secondary Air Fan Sizing Specific Power {W/(m3/s)}
+    ,                        !- Secondary Air Fan Power Modifier Curve Name
     SMstore5 Fan outlet,     !- Primary Air Inlet Node Name
     SMstore5 Inlet Node,     !- Primary Air Outlet Node Name
-    ,                        !- Control Type
-    0.9000,                  !- Dewpoint Effectiveness Factor
-    SMstore5 Evap Cooler OA node,  !- Secondary Air Inlet Node Name
-    SMstore5 Inlet Node,     !- Sensor Node Name
-    ,                        !- Relief Air Inlet Node Name
-    ,                        !- Water Supply Storage Tank Name
-    0.2,                     !- Drift Loss Fraction
-    3;                       !- Blowdown Concentration Ratio
+    Autosize,                !- Primary Design Air Flow Rate {m3/s}
+    0.9000;                  !- Dewpoint Effectiveness Factor
```

And here is the version from this branch:

```
--- /home/elee/tmp/transition_issues/evapcoolers_from_82_to_83/NewVersions/StripMallZoneEvapCooler.idfold
+++ /home/elee/tmp/transition_issues/evapcoolers_from_82_to_83/NewVersions/StripMallZoneEvapCooler.idfnew

@@ -4164,8 +4164,11 @@
   EvaporativeCooler:Direct:ResearchSpecial,
     LGstore1 Direct Evaporative Cooler,  !- Name
     ALWAYS_ON,               !- Availability Schedule Name
-    0.7,                     !- Cooler Effectiveness
-    55.0,                    !- Recirculating Water Pump Power Consumption {W}
+    0.7,                     !- Cooler Design Effectiveness
+    ,                        !- Effectiveness Flow Ratio Modifier Curve Name
+    55.0,                    !- Recirculating Water Pump Design Power {W}
+    ,                        !- Water Pump Power Sizing Factor {W/(m3/s)}
+    ,                        !- Water Pump Power Modifier Curve Name
     LGstore1 Indirect Outlet Node,  !- Air Inlet Node Name
     LGstore1 Inlet Node,     !- Air Outlet Node Name
     LGstore1 Inlet Node,     !- Sensor Node Name

@@ -4450,17 +4456,24 @@
   EvaporativeCooler:Indirect:ResearchSpecial,
     SMstore5 Evaporative Cooler,  !- Name
     ALWAYS_ON,               !- Availability Schedule Name
-    0.7500,                  !- Cooler Maximum Effectiveness
-    ,                        !- Cooler Flow Ratio
-    55.0000,                 !- Recirculating Water Pump Power Consumption {W}
-    1.0,                     !- Secondary Fan Flow Rate {m3/s}
-    0.6000,                  !- Secondary Fan Total Efficiency
-    124.6000,                !- Secondary Fan Delta Pressure {Pa}
+    0.7500,                  !- Cooler Wetbulb Design Effectiveness
+    ,                        !- Wetbulb Effectiveness Flow Ratio Modifier Curve Name
+    ,                        !- Cooler Drybulb Design Effectiveness
+    ,                        !- Drybulb Effectiveness Flow Ratio Modifier Curve Name
+    55.0000,                 !- Recirculating Water Pump Design Power {W}
+    ,                        !- Water Pump Power Sizing Factor {W/(m3/s)}
+    ,                        !- Water Pump Power Modifier Curve Name
+    1.0,                     !- Secondary Air Design Flow Rate {m3/s}
+    1.0,                     !- Secondary Air Flow Scaling Factor {dimensionless}
+    Autosize,                !- Secondary Air Fan Design Power {W}
+    207.66666,               !- Secondary Air Fan Sizing Specific Power {W/(m3/s)}
+    ,                        !- Secondary Air Fan Power Modifier Curve Name
     SMstore5 Fan outlet,     !- Primary Air Inlet Node Name
     SMstore5 Inlet Node,     !- Primary Air Outlet Node Name
-    ,                        !- Control Type
+    Autosize,                !- Primary Design Air Flow Rate {m3/s}
     0.9000,                  !- Dewpoint Effectiveness Factor
     SMstore5 Evap Cooler OA node,  !- Secondary Air Inlet Node Name
+    ,                        !- Secondary Air Outlet Node Name
     SMstore5 Inlet Node,     !- Sensor Node Name
     ,                        !- Relief Air Inlet Node Name
     ,                        !- Water Supply Storage Tank Name
```

Note that in the first version, there are lots of minus-es over the fields, because they were removed, as understood from the original issue.  In the new version, those minus-es are gone because the new version doesn't remove the fields.

**Comment by Myoldmopar** [comment]
OK, I gotcha, I'll look at the 8.2 to 8.3 rules file.

**Comment by Myoldmopar** [comment]
Gah!  I see now.  That file is correct for the first 59 rows.  ... Then the rest after that is simply lingering from the 8.1 to 8.2 version.  Apparently I forgot to scroll down?  I'll update that over in BuildSupport in the 8.3 branch, and that should solve it.  If we decide to re-release, it will automatically pick up the new version.

**Comment by Myoldmopar** [comment]
Updated in https://github.com/NREL/EnergyPlusBuildSupport/commit/f6f6f9f4d6e21ee97e9dcc903e04db97189f09fa

If anything remains (outside of waiting for robots), let me know, otherwise I think this PR is ready to go.

**Comment by mjwitte** [comment]
Tested the revised transitions and confirmed they are working properly now.

**Pull request merged**
