### PR TITLE
Fix Hybrid Unitary Operating Settings Initialization

### LINKED ISSUE #8420: Zone Hybrid Unitary HVAC Runtime Fraction doesn't initialize to 0 for operating settings when switching to standby mode
Issue overview
--------------
When using the ZoneHVAC:HybridUnitaryHVAC object, if the system goes from running in a mode other than standby mode and then switches to standby mode in the next timestep, the Zone Hybrid Unitary HVAC Runtime Fraction output variable for the other settings repeats the last timestep value until the setting is used again.  It appears that the operating settings are initialized to empty settings [here](https://github.com/NREL/EnergyPlus/blob/1cdc5c51fe2624f49a0000b2c97dade5b6405b8e/src/EnergyPlus/HybridEvapCoolingModel.cc#L1277) in the SetOperatingSetting function.  The problem is that if there is no demand for the system to turn on, it goes into standby mode and the SetOperatingSetting function is bypassed [here](https://github.com/NREL/EnergyPlus/blob/1cdc5c51fe2624f49a0000b2c97dade5b6405b8e/src/EnergyPlus/HybridEvapCoolingModel.cc#L1857).  The tables below shows the Zone Hybrid Unitary HVAC Runtime Fraction output variable for Setting 0 and Setting 1.  It shows the runtime fraction value continuing for Setting 1 which switching to full standby mode at 23:01.

image

This can be fixed by moving the initializing of the operating settings before calling the SetOperatingFunction and before determining whether there is a demand on the system or not, shown below.

```
        // Initialize all settings for all operating modes
        int size = CurrentOperatingSettings.size();
        CSetting empty_setting;
        for (int i = 1; i < size; i++) {
            CurrentOperatingSettings[i] = empty_setting;
        }

        // Go into standby if unit is off or not needed
        if ((!CoolingRequested && !HeatingRequested && !VentilationRequested && !HumidificationRequested && !DehumidificationRequested) ||
            ForceOff)
        {
            StandBy = true;
            oStandBy.Runtime_Fraction = 1;
            CurrentOperatingSettings[0] = oStandBy;
            ErrorCode = 0;
            PrimaryMode = 0;
            PrimaryModeRuntimeFraction = 0;
        } else {
            // set the operating conditions and respective part load fractions.
            ErrorCode = SetOperatingSetting(state, StepIns);
        }
```

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #8420 
 - This pull request addresses the issue when the runtime fractions added up for each operating setting is greater than 1 during some timesteps when in full standby mode (Mode 0).  It was determined that the operating settings were not being initialized before going into standby mode, so when utilizing 2 operating modes within the previous timestep, the second operating mode retained it's previous operating settings after going into full standby mode.  To fix this, I moved the section of code that initializes the operating settings to empty values from inside the `SetOperatingSettings` function to before the if statement that determines whether to go into full standby mode or step into the `SetOperatingSettings` function.   The before and after screenshots of the runtime fractions for the 2 operating settings during this condition are shown below.

Before:
image

After:
image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@matthew-larson @lgentile it has been 28 days since this pull request was last updated.

**Review by Myoldmopar — APPROVED** [review]
This looks good from a code standpoint and thanks for the unit test.  The one nitpick I would say is that if you are moving that loop around, it might've been good to go ahead and make it a range based loop.  That change reduces the possibility of bugs from indexing.  I'll pull develop in and test it out with the defect file and this should be able to go in.

**Comment by Myoldmopar** [comment]
I did not see a defect file on the issue or in the dev support repo, so I didn't run that.  But I did pull develop in and ran unit tests, including the new one here.  I am going to merge this.  Thanks @matthew-larson

**Comment by matthew-larson** [comment]
Thanks @Myoldmopar for the feedback, that makes sense.

**Pull request merged**
