### PR TITLE
Autosizing of heating coil UA failed for Coil:Heating:Water for plant loop exit temperature below 45C #5638

### PR DESCRIPTION
**Pull request by Nigusse**
Low hot water coil design inlet temperatures cause UA-value auto-size to fail. In this case the water heating coil sizing procedure checks for such condition and uses slightly higher coil inlet water temperature for UA auto-sizing and then issues a warning message that the UA-value was sized using a higher water inlet temperature and reports the value used. 

issue #5638 

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Nigusse** [comment]
This fix traps low coil design inlet hot water temperature (< 46.0 ) and resets the coil design inlet hot water temperature to a minimum of 46.0 C for UA value sizing only. This fix sizes the UA to a reasonable value and eliminated UA-value auto-sizing calc failure due to low coil design inlet water temperature. I have also added a function that estimates design inlet water temperature for this purpose. Maximum of 46.0 and the estimated coil inlet water temperature is used. This value is used for UA-sizing only.

**Comment by rraustad** [comment]
@Myoldmopar do I need to worry about the unhandled failure (invalid byte sequence) on the Linux machine?

**Comment by rraustad** [comment]
@Myoldmopar do I need to worry about the unhandled failure (invalid byte sequence) on the Linux machine?

**Comment by Myoldmopar** [comment]
> @Myoldmopar do I need to worry about the unhandled failure (invalid byte sequence) on the Linux machine?

Nope.

**Pull request merged**
