### PR TITLE
Fix RoomAirNode AirflowNetwork InternalGains IDD metadata

### PR DESCRIPTION
**Pull request by Myoldmopar**
Thanks to @macumber for pointing this out over in [OpenStudio](https://github.com/NREL/OpenStudio/commit/c5735dafd9364c5e2796a0664e2fa0a99058a225#commitcomment-14261183).

Note, this changes the IDD.  @mjwitte Not sure if this type of a change is something that eliminates it from the bug fix release.  @macumber, as one interface, what are your thoughts about this type of IDD change going out in a bug-fix supplemental release of the same major/minor number?  Does that break your autogenerated stuff so that you wouldn't be able to use the bug-fix release and would have to be anchored at the initial release?

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Github won't display the diffs <sigh>  Diffing locally shows only two lines changed?  Is there line-ending issue here?    Based on a local diff of this vs develop, the change is

```
RoomAir:Node:AirflowNetwork:InternalGains,
      \extensible:4
      \min-fields 5
```

to

```
RoomAir:Node:AirflowNetwork:InternalGains,
      \extensible:3
      \min-fields 4
```

I don't see why one wouldn't include this.  It's clearly wrong, so it's a bug-fix to me.

**Comment by macumber** [comment]
OpenStudio keeps it's own version of the EnergyPlus IDD that we've already fixed this in.  We have our own version of the IDD specifically so we can decouple what we need to do from EnergyPlus so we can fix these things on our own schedule, I can't speak for other developers, I'd assume everyone is doing things differently

**Comment by Myoldmopar** [comment]
Super small, and clearly correct change.  I'm merging.

**Comment by mjwitte** [comment]
@Myoldmopar Did you figure out why github was showing 381 additions and 381 deletions?

**Comment by mbadams5** [comment]
@mjwitte His editor took out extra whitespace at the end of lots of lines.

**Comment by mjwitte** [comment]
@mbadams5 I figured it might be that.  Why is github so wimpy about displaying that?  381 lines isn't all that much.

**Pull request merged**
