### PR TITLE
VRF using Fan:SystemModel fan shows full air flow rate when system is scheduled off or no load is present

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
When a Fan:SystemModel object is used in VRF and the system is either off or within the Tstat deadband, the fan operates at full air flow rate. This change corrects #6336.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
@EnergyArchmage I need your input here. Thanks in advance.

**Comment by rraustad** [comment]
I'm tentative about this fix. Why is it that when the system is on, the call to the fan model works as expected and when the system is "scheduled off or load = 0" the system model fan shows full flow?
This works but I am suspect of the fix.

**Comment by rraustad** [comment]
Results before (OnOffFfan) and after (SystemModel) with with this change (see https://github.com/NREL/EnergyPlus/issues/6336):

6336beforeandafter

**Comment by EnergyArchmage** [comment]
Fix looks okay to me.

**Pull request merged**
