### PR TITLE
Fix bug in PCM code

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
@nealrkuis found a typo-defect in the PCM code.  This was addressed here.  I will add a unit test.

The bug (in v8.8.0) causes a crash or invalid results if there is more than one material layer in the construction which holds the PCM material.
Ref: helpdesk ticket 12504

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nealkruis** [comment]
@Myoldmopar looks good. I think the Linux failure is a CI issue. Should we force a rebuild just to be safe?

**Comment by Myoldmopar** [comment]
Nah, I'll push up a unit test sometime soon anyway, so we'll let it retry then.  Thanks!

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
For reference, I checked out the diffs here and they are very small diffs, and is likely because in some of the changes we are now updating all the possible dynamic properties, not just specific heat.  Which we should've been doing all along.  This is OK.  I'm still thinking about how to best test that new little function.

**Comment by Myoldmopar** [comment]
CI appears happy.  The SQLiteFixture failure is fully unrelated.  The one regression diff is expected and reasonable.  If CI continues to be happy I'll merge it in.

**Comment by Myoldmopar** [comment]
OK, late diffs are due to HWBaseBoard PR, this branch is now 7 commits behind develop.  Not waiting for another go.  Merging.

**Pull request merged**
