### PR TITLE
Use TriDiagonal matrix solver to calculate window temperature

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 
The function of SolveForWindowTemperatures is identified by LBNL as a hot spot. The LU decomposition is used to solve a matrix. The matrix in most cases is tridiagonal, so that tridiagonal matrix solver can be used to replace the LU decpompostion solver. The new solver is more efficient than the LU decomposition for tridiagonal matrix.

This upload only deals with the case for single pane windows.  

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Is this intended for 9.5?

**Comment by lgu1234** [comment]
@Myoldmopar This will be for 9.6.

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 29 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@lgu1234 could you give a status update here?  Thanks!

**Comment by lgu1234** [comment]
@Myoldmopar I am waiting for 10x team decision.

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@lgu1234 please advise again on the status here.  If it is being tabled for now, you can close the PR. (you can always re-open it later)  If it is for this release, please set the milestone to either the IOFreeze or Release milestone.  Thanks!

**Comment by lgu1234** [comment]
@Myoldmopar It will not be for this release. I close it for future work.

**Pull request closed without merging**
