### PR TITLE
179d reporting based on v8.8.0

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview
---------------------
This PR adds a new option "179D_COMPLIANCE" to the EnergyPlus build which tests the current build of EnergyPlus with the last release of OpenStudio to generate 179D Compliance reports and stages them for upload to the CI.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] At least one of the following appropriate labels must be added to this PR to be consumed into the 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by lefticus** [comment]
The PR has now been updated to include posting of results to the CI dashboard.

This PR is enabled for building the reporting only on release builds. A separate branch was made that created the reports for all builds. The result of that can been seen here: http://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-c0f6d73f5f9a2cdb630e343e44ba5ab3531d70ef-x86_64-Linux-Ubuntu-14.04-gcc-4.8-179D_Reporting.html#build with the posted reports available: http://energyplus.s3-website-us-east-1.amazonaws.com/assets/2018-02-08-EnergyPlus-c0f6d73f5f-x86_64-gcc-4.8179-DR/

**Comment by Myoldmopar** [comment]
@lefticus I was going to push on this to get it in, but it's going to add CI effort and we can't really afford that at the moment.  I think we should still use this branch to build the CI results, but not merge it into develop at the moment.  This doesn't affect any C++ code so it doesn't matter to bring it up to date for the style update.

**Comment by nrel-bot-3** [comment]
@lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@lefticus @lgentile it has been 14 days since this pull request was last updated.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
I'm going to go ahead and merge this and later today I'll trigger a tag build.  If something goes awry, I'll leave the core changes in place but remove the -D179D_COMPLIANCE to OFF and figure out what we need to do to actually get it going.

**Comment by Myoldmopar** [comment]
Actually, let me get develop in here first to make sure CI is OK.

**Comment by Myoldmopar** [comment]
Ahh there we go, finally some good clean results.  I'll let CI run overnight though.

**Comment by Myoldmopar** [comment]
Actually, let me go ahead and tag a release of this branch and let that populate overnight.  :+1:

**Comment by Myoldmopar** [comment]
Merging this in as-is right now to get the code in there with the package build disabled for now.

**Pull request merged**
