### PR TITLE
Remove EMS exp error

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
Currently you get an EMS error if you try to use an exponent of <= -20.0. This causes the user to have to add checks to all their EMS programs that use exp, as shown below. Instead, we simply return 0.0 so the user doesn't have to handle it.

```
If eTm <= -20
  Set tsup = ah_tin
Else
  Set tsup = ah_tin + ((ah_tout - ah_tin) * (@Exp eTm))
EndIf
```

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Review by EnergyArchmage — APPROVED** [review]
looks good to me.  more user friendly underflow protection.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Luckily I felt in the unit test mood so I didn't push back and have you write unit tests.  I added them here.  Once CI confirms them I'll merge this.

**Comment by shorowit** [comment]
Thank you, our fearless benevolent dictator.

**Comment by mjwitte** [comment]
" . . . in the unit test mood"? That's a little worrisome - better check to make sure @Myoldmopar doesn't have a leaky head gasket.

**Comment by Myoldmopar** [comment]
Ugh, so how did Win64 decide to be the only platform with that failing unit test.  Makes no sense.  Debugging on Windows now...

**Comment by Myoldmopar** [comment]
OK, found the problem.  The errors found flag wasn't initialized, so it just happened to be coming in as false, and propagated through.  I reproduced the failure on Win64 and fixed it there.  I'm not waiting on CI to run again.  Merging now.

**Pull request merged**
