### PR TITLE
Corrects WaterUse:Equipment draw behavior when cold water is warmer than hot water

### LINKED ISSUE #9650: Unrealistic behavior of Wateruse:Equipment when Hot Water is colder than Cold Water
Issue overview
--------------
I have a model with a service water heating loop shown below. On the demand side, there is a Pipe:Indoor object (circled in red) with an ambient temperature of 80F to capture piping losses. This is followed by a WaterUse:Connection object referencing a WaterUse:Equipment object with a target temperature of 140F, and a water draw profile that goes to zero at night. On the supply side, there is a Pump:ConstantSpeed set to intermittent (assuming recirculation stops at night when no water draw is expected), followed by a WaterHeater:Mixed object with a setpoint of 140F.

image

What happens is that at the beginning of the year, the simulation behaves as expected. The pipe inlet (blue) is as-expected (~140F). The pipe outlet (orange) is as-expected, lower than the inlet, in this case the delta-T is high for illustration purposes. The water mains temperature (dark red) is taken from the .stat file, and goes from a low of ~60F in winter to a high of ~85F in summer.

During the winter, the "Hot" water coming into the WaterUse:Connections object from the pipe outlet is hotter than the "Cold" water from the water mains. The WaterIUse:Connections object functions as-expected, with all the flow coming from the "Hot" water side (light green). In this case it is unable to meet the 140F target temperature, and warnings are thrown, but that isn't the problem.  The problem is that as soon as the "Cold" water from the mains is hotter than the "Hot" water from the pipe outlet (due to the high heat loss from the pipes and the 80F ambient temperature, then the WaterUse:Connections object changes and decides that all flow should come from the "Cold" side (dark green) because it is closer to the target temperature.

water_heating

### Expected Behavior
In a typical building's service hot water system, if there is no recirculator, or if the recirculator turns off overnight when there is no water draw, the temperature of the water in the hot water piping system will drop down to roughly the ambient temperature where the pipes are located, typically ~70-80F. In the morning when the hot water draws start, the flow starts again and someone will leave it running long enough until this ambient-temperature water is cleared from the pipes and actual hot water starts coming out. Prior to EnergyPlus 9.6, this was the observed behavior. The current behavior is to see if the cold water is warmer, and if it is, use that instead of waiting for the hot water. By my judgment, this does not match how real buildings are typically operated. Whether the hot water system is properly designed so that a person doesn't have to wait a long time to get hot water is a separate issue. In my example model, the system isn't designed properly, which the warnings helped identify.

I believe that the behavior was changed as part of https://github.com/NREL/EnergyPlus/pull/8808.  I really like this PR because it adds lots of helpful warnings about the state of the SWH system. However, I believe that the behavior should be changed back to represent what is more common in real buildings. Users who aren't modeling piping losses will likely not be impacted, and users who have legitimate problems with hot water supply temperatures will still get the warnings.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (22.1)

### Checklist
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/9507634/in.idf.txt)
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by asparke2**
Pull request overview
---------------------
 - Fixes #9650
 - If cold water is warmer than hot water, continue to draw from hot water instead of switching draw to cold water.
 
I don't have an EnergyPlus development environment set up, so can't run the tests or verify the change.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
image

**Comment by asparke2** [comment]
@rraustad I don't have an EnergyPlus development environment set up, so can't run the tests or verify the change.

**Comment by Myoldmopar** [comment]
@asparke2 could I provide you with a build or anything to help you verify the fix works?  I'd love to get this discussed and if a change is justified, make sure it gets in this release.

**Comment by rraustad** [comment]
@Myoldmopar I have been meaning to run the defect file and maybe other files to see the impact of this change. Haven't gotten to it.

**Comment by asparke2** [comment]
@Myoldmopar yeah if you want to send me a Windows build I'd be happy to run the defect file and recreate the plots to verify the fix. I think this will only affect files that either have a Pipe:Indoor before the Wateruse:Connection or have a problem with the service water heating temperature. That's probably why the change went unnoticed when it was originally part of the PR.

**Comment by rraustad** [comment]
I will say that if the pipe temps impact the choice of what flow is requested (e.g., hot or cold) and this fixes an issue with stagnate water in the hot pipe, then it seems that the choice of hot or cold flow based on temperatures is not the best choice. Either hot water is requested or cold water is requested. I am not familar with this model so maybe I am off base. This is nothing that impacts this specific change but in general maybe this model needs a closer look. I know for a sink if I turn on the hot water valve I get cold water then hot water, but I did not choose that valve based on the temperature of the water at the valve inlet.

**Comment by rraustad** [comment]
Comparison of 9650 WaterUse:Equipment defect file in develop and this branch.

image

[9650-in.idf.txt](https://github.com/NREL/EnergyPlus/files/9583814/9650-in.idf.txt)

**Comment by rraustad** [comment]
All I can do at this point is rely on existing example file diffs (2) to determine if this is the correct fix. This is a mixing problem where the valve inlet is not the same temperature as the source. This fix appears to work but there are several temperature checks in this model. I am also unsure of the if (this->HotTemp == this->ColdTemp) this->HotMassFlowRate = 0.0; since it is possible the water temps could be equal and mains flow was requested. I would suggest that an issue be posted to review this model given this existing issue and discussion as the background. The existing example file diffs need to be reviewed.

**Comment by rraustad** [comment]
Diffs (results the same in both files):

EMSDemandManager_LargeOffice
EMSReplaceTraditionalManagers_LargeOffice

eio - warmup convergence diffs
err - elimination of WaterUse:Equipment warnings
eso - big diffs
mtr - big diffs

Example warning that was removed with this fix:

    -   ** Warning ** CalcEquipmentFlowRates: "CORE_BOTTOM WATER EQUIPMENT" - Hot water temperature is less than the cold water temperature (8.82 C)
    -   **   ~~~   **  Environment=CHICAGO ANN CLG .4% CONDNS DB=>MWB, at Simulation time=07/21 00:00 - 00:15
    -   **   ~~~   ** ...hot water temperature       = 10.00 C
    -   **   ~~~   ** ...cold water temperature       = 18.82 C
    -   **   ~~~   ** ...Note: hot water temperature should be greater than or equal to the cold water temperature
    -   **   ~~~   ** ...Hot water temperature should be greater than or equal to the cold water temperature. Verify temperature setpoints and schedules.

These results do tend to support this fix.

**Comment by rraustad** [comment]
This example file with diffs also appears to be corrected.

image

image

[9650-EMSDemandManager_LargeOffice - Copy.idf.txt](https://github.com/NREL/EnergyPlus/files/9584233/9650-EMSDemandManager_LargeOffice.-.Copy.idf.txt)

**Review by rraustad — APPROVED** [review]
This does appear to be the correct fix although I have questions as to the correct model implementation. I think it would be better to look at source temps instead of downstream of there, but again, I am not familiar with this model.

    if (this->Connections > 0) {
        // Get water temperature conditions from the CONNECTIONS object
        this->ColdTemp = state.dataWaterUse->WaterConnections(this->Connections).ColdTemp;
        this->HotTemp = state.dataWaterUse->WaterConnections(this->Connections).HotTemp;

**Comment by rraustad** [comment]
@Myoldmopar this appears to be correct. Back to you.

**Comment by Myoldmopar** [comment]
@rraustad thanks a bunch for providing those results.  I do see the hot water flowing now where in develop it went to zero on the second design day.  This seems to agree with the fix.  

However...I don't have a great feeling about reverting part of a change that was _just_ added a year ago.  It's possible that the fix a year ago never should have set the flow rate to zero.  In fact, it's probable based on these results.  I'm just having a tough time building the courage to merge this in without a deeper understanding of the implications.  

My current thought is to hold this for now, and I'll try to dig into the model a bit deeper, and still try to get this in next week.  If someone is already an expert in here, or if someone wants to go through all the temperature checks and flow rate assignments to understand and explain the implications, that would make me feel better about merging it.

**Comment by rraustad** [comment]
From what I see a year ago, the model was changed to look at the difference between the hot and cold temperatures. For a mixing problem there should be a comparison of water temps to the target temp. That was changed. I think this should be changed back and somehow look at what the hot water temp is leaving the source (before the pipes or connections). If the pipes have a temperature drop that probably shouldn't change the choice of flow but will affect the mixed temperature. Stagnation temps that can influence flow are an issue for this model where temps choose flow.

image

**Comment by rraustad** [comment]
Here's what I am thinking.

    // getInput would check that hot and cold source temps are valid
    if (this->TargetTemp < this->ColdTemp) {
        this->HotMassFlowRate = 0.0;
    } else if (this->TargetTemp > this->HotTemp) {
        this->HotMassFlowRate = this->TotalMassFlowRate; // this will purge stagnant hot water temps
    } else {
        // mix the 2 streams, whatever they are. Here there would? would not? be checks on temps.
    }
    this->ColdMassFlowRate = this->TotalMassFlowRate - this->HotMassFlowRate;

**Comment by mjwitte** [comment]
Looking at #8808 the intent was to add warnings, so this line does go beyond that:
```
            } else if ((this->ColdTemp - this->HotTemp) > EPSILON) {
                // Special case for HotTemp < ColdTemp, due to bad user input (could happen in a plant loop accidentally)
                this->HotMassFlowRate = 0;
```
@rraustad What happens if you simply remove that line?

**Comment by rraustad** [comment]
If I revert that one line the water flow shuts down. It's going to take more than that to get all the logic right, that is, a change from what is here now.

//                this->HotMassFlowRate = this->TotalMassFlowRate;

**Comment by rraustad** [comment]
No, it doesn't shut down flow, it converts to all cold water flow.

**Comment by rraustad** [comment]
It appears to me that this fix corrects the flow in the defect file and 2 example files. We get this merged as a baseline. Then go in and review the logic to make it a more logical list of steps (if blocks).

**Comment by rraustad** [comment]
I just tried my logic above and I get the same answer as this branch.

**Comment by rraustad** [comment]
I added this and commented out the current if block and warnings.

            if (this->TargetTemp < this->ColdTemp) {
                this->HotMassFlowRate = 0.0;
            } else if (this->TargetTemp > this->HotTemp) {
                this->HotMassFlowRate = this->TotalMassFlowRate; // this will purge stagnant hot water temps
            } else {
                // mix the 2 streams, whatever they are. Here there would? would not? be checks on temps.
                if ((this->HotTemp <= this->ColdTemp)) {
                    this->HotMassFlowRate = 0.0; // not sure here, will need to avoid divide by 0
                } else {
                    this->HotMassFlowRate = this->TotalMassFlowRate * (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp);
                }
            }

this then drops into the existing block below (i.e., below the big if block I just commented out):

            if (this->HotMassFlowRate < 0.0) {
                // Target temp is colder than the cold water temp; don't allow colder
                this->HotMassFlowRate = 0.0;
                TempDiff = this->ColdTemp - this->TargetTemp;
                if (!state.dataGlobal->WarmupFlag) {

Update: and it looks like I don't even need this if block at the bottom because I have already checked if target temp < cold.

**Comment by rraustad** [comment]
This IORef description may be where the cold water use in the defect file is coming from. The model thinks no hot water schedule is being used and reverts to using cold water. Realizing this model apsect makes review of the logic more understandable. The model does not know the difference between a missing hot water schedule and when the hot water is colder than the cold water.

    If the hot water schedule or target temperature schedule are omitted, all water is delivered as cold water.

**Comment by rraustad** [comment]
So now I know why this intro is troubled. If the hot and cold temps are the same that could either mean the hot temp schedule is missing (temps are set equal in that case) or that the water temps are the same. And the else looks at whether the cold temp > hot temp. But the target hasn't even been checked yet.

For the if: if no hot temp sch these water temps are equal use cold water. If there is a hot temp sch and these water temps are equal we would want to use hot water (this stagnant temp issue). But really we still need to know the target temp to make that decision.

For the else: if no hot temp sch these water temps are equal and this code is never hit. If there is a hot temp sch and cold > hot then yes, we want to use hot water. But we haven't checked the target temp yet (the schedule value). So, pun here, this is a hot mess. I've got my branch working but now I have to incorporate this missing hot schedule issue.

            if (this->HotTemp == this->ColdTemp) { // Avoid divide by zero
                // There is no hot water
                this->HotMassFlowRate = 0.0;
            } else if (this->ColdTemp > (this->HotTemp + EPSILON)) { //(HWCWTempDiff > EPSILON) {
                this->HotMassFlowRate = 0;                                           <-- develop
                this->HotMassFlowRate = this->TotalMassFlowRate;    <-- this branch

**Comment by mjwitte** [comment]
But if the water use object is connected to a plant loop, then you don't need/want a hot temp schedule, because that's determined by the water heater, etc in the plant loop. Does any of this logic know that status? (whether it's served by a plant loop or even served directly from a water heater).

**Comment by rraustad** [comment]
The water use object knows if it's connected to a plant via the WaterUse:Connections. I guess I need to understand all possible connections in order to correctly implement these conditionals. Sounds like there is more to it than I understand right now.

        if (this->Connections > 0) {
            // Get water temperature conditions from the CONNECTIONS object
            this->ColdTemp = state.dataWaterUse->WaterConnections(this->Connections).ColdTemp;
            this->HotTemp = state.dataWaterUse->WaterConnections(this->Connections).HotTemp;

**Comment by rraustad** [comment]
I think I have this now. There could be a tweak here or there but the logic is now:

    if (this->TotalMassFlowRate > 0.0 && this->allowHotControl) {
        if (this->TargetTemp <= this->ColdTemp + EPSILON) {
            this->HotMassFlowRate = 0.0;
        } else if (this->TargetTemp > this->HotTemp - EPSILON) {
            this->HotMassFlowRate = this->TotalMassFlowRate;
        } else {
            if (this->HotTemp <= this->ColdTemp + EPSILON) {
                this->HotMassFlowRate = this->TotalMassFlowRate;
            } else {
                // HotMassFlowRate should always be between 0 and max
                this->HotMassFlowRate = this->TotalMassFlowRate * (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp);
            }
        }
        this->ColdMassFlowRate = this->TotalMassFlowRate - this->HotMassFlowRate;

        this->MixedTemp = (this->ColdMassFlowRate * this->ColdTemp + this->HotMassFlowRate * this->HotTemp) / this->TotalMassFlowRate;
    } else {
        this->HotMassFlowRate = 0.0;
        this->ColdMassFlowRate = this->TotalMassFlowRate;
        this->MixedTemp = this->TargetTemp;
    }

**Comment by rraustad** [comment]
This change will be pushed as a separate branch so as not to lose the code changes to existing logic.

**Comment by Myoldmopar** [comment]
This PR is superseded by #9661 which includes not only a fix but also a broad cleanup of the water use module.

**Pull request closed without merging**
