### PR TITLE
Window shading control order new feature

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
New feature to add control for the sequence of window shades (or switchable glazing) as they are deployed in a zone based on glare.
Addresses #6582 new feature request.

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I have nothing to add to comments on the NFP.  This seems like a very straightforward set of changes and an elegant solution to the problem.

**Comment by Myoldmopar** [comment]
@JasonGlazer I started to review this, but it looks like it is still a ways off.  No big deal to me, I am just going to mark it for the fall release milestone instead.  If I'm missing something and you are trying to wrap it up for this week, just let me know and reassign the milestone.

**Comment by JasonGlazer** [comment]
@Myoldmopar I would like to get it done for this release but it is not going to be done this week. If the deadline gets delayed, it might make it in.

**Comment by Myoldmopar** [comment]
OK, makes sense.  I'll leave it at the Fall milestone and then if magic happens and it gets done for this one, that's great.  Thanks!

**Comment by JasonGlazer** [comment]
@mbadams5 can you help me figure out what is wrong in the JSON input processing for unit test SpectralAngularPropertyTest? I'm getting:

Assertion failed: m_it.object_iterator != m_object->m_value.object->end(), file I:\epRepo\EnergyPlus\third_party\nlohmann/json.hpp, line 4095

**Comment by mbadams5** [comment]
@JasonGlazer I'm building your branch now, but just looking over the code I think I might know what you need to do. Since you've added extensible to `WindowShadingControl `, [you need to add that object to here](https://github.com/NREL/EnergyPlus/blob/develop/scripts/dev/generate_epJSON_schema/modify_schema.py#L19) where it maps the object name to an appropriate extensible name. I think `fenestration_surfaces` is probably appropriate so you'd add `'WindowShadingControl': 'fenestration_surfaces'`. I am planning to address this (and more) in my followup PR in the new couple days so there are more descriptive errors for developers.

**Comment by JasonGlazer** [comment]
@mbadams5 thanks. How do I trigger the VS2015 to rebuild the Energy+.IDD and Energy+.schema.epJSON files now?

**Comment by mbadams5** [comment]
@JasonGlazer The quickest and easiest way is to touch the Energy+.idd.in file. You can temporarily add whitespace, save, delete whitespace, save and then it'll rebuild those files. Or you can use the `touch` command on Mac and Linux.

**Comment by mjwitte** [comment]
@mbadams5 The idd is no longer rebuilding in VS for me or @JasonGlazer . Suspecting this started with the input processor refactor merge.

**Comment by mbadams5** [comment]
That is odd. I didn't alter anything related to IDD creation. I'll look into it.

**Comment by mjwitte** [comment]
@mbadams5 @JasonGlazer Actually, the first time I tried, it did not build. Then I tried again and it did build. Tried again and it builds.  There is still the GenerateEmbeddedEpJSONSchema out of date issue which I've added to #6486.

**Comment by Myoldmopar** [comment]
@JasonGlazer  I was trying to just spend a couple minutes fixing up some of these failing branches.  I fixed the issues with this branch, would you like me to push up the changes?  I'm just trying to get the dashboard to turn green...

**Comment by JasonGlazer** [comment]
@Myoldmopar thanks, that would be great.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

**Comment by JasonGlazer** [comment]
@mjwitte thanks for adding the transition code changes.

**Comment by mjwitte** [comment]
@JasonGlazer The transition code is not complete yet. The daylighting control name complicates matters. In the current scheme, the same WindowProperty:ShadingControl object could be shared across many zones. If the shading control is using any sort of daylighting control (e.g. glare) then there will need to be a new WindowShadingControl object for every zone that has a surface which uses that. So, do we want to *always* clone the new WindowShadingControl by zone? And then look for a daylighting control and insert the name, regardless of the shading control type?

**Comment by JasonGlazer** [comment]
@mjwitte the way the NFP development process ended to me implies that he WIndowShadingControl object is *not* by zone at all but is independent of zone. I'm not sure if that was on purpose or not. It does not reference a zone and only indirectly implies a zone if all the fenestration surfaces are in one zone. I guess we could require that it is only serving a single zone and that all the fenestration surfaces that are being controlled are within one zone. That would probably be sufficient from my perspective and closer to the original intent of the project. 

So if we do assume that the WindowShadingControl list of fenestration surfaces all are in the same zone, than, yes, I think it would make sense to always clone them by zone.

**Comment by mjwitte** [comment]
I don't know that we necessarily need to impose that restriction overall, but it may be the safest thing to do for transition (make separate WindowShadingControl objects by zone).
For the new code, it should probably check and warn if a daylighting control name is specified and there are surfaces in the list that are in different zones?

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar assuming that I fixed all the CI issues in the last two commits, this should be ready to be merged.

**Comment by Myoldmopar** [comment]
@JasonGlazer The Mac build has been especially flaky, so I would normally delete those results and let them run again.  However, it looks like PurchAirWithDaylightingAndShadeControl is actually failing for real, so go ahead and address that and then we'll see if CI is happy after that.

**Comment by mjwitte** [comment]
@JasonGlazer These results looked great until I realized that the test suite doesn't have glare control applied to multiple windows. Should have added that as part of #6914. Attached idfs show diffs for ZN004:WALL00*:WIN00*:Surface Shading Device Is On Time Fraction (columns BM:BP) for example on 01/25 and 07/12. With the new shading controls, the 4 window shades in Zn004 are always all on or all off.
[Test Window Shade Order 2018-08-23.zip](https://github.com/NREL/EnergyPlus/files/2315031/Test.Window.Shade.Order.2018-08-23.zip)

**Comment by Myoldmopar** [comment]
@JasonGlazer  
- Github isn't showing the full diff for me since it touches so many files, but what I see looks ok.  Honestly there is a lot more code here than I thought there would be for this change, but I understand that's sometimes how these things go.  
- CI is super happy now with this last commit.  
- I pulled locally and the code, tests, and documentation built without issue.  
- I ran the unit tests, they all ran fine.  
- I ran the new PurchAirWithDaylightingAndShadeControl example file
   - It runs successfully with a clean error file.  
   - I took a look at the outputs, and wasn't able to see the staged shading control in the zone 1 window shading control outputs.  I ran it in annual mode thinking that was it but it also showed them all synced up.  
   - Maybe this is what is expected based on the input file specs and the specific zone/windows I was looking at.  I was going to dig a little further into the new example idf, but I saw @mjwitte 's comment pop up here and I'll hold off.  

Once you get his issue addressed and verify everything is working fine in the new example file, please post some example output plots from the latest commit and this should be good to go.

**Comment by mjwitte** [comment]
Oh, I hadn't realized there was a new test file - duh. @JasonGlazer Do you have a "before" version of PurchAirWithDaylightingAndShadeControl? If not, I can make one.

**Comment by JasonGlazer** [comment]
Sorry, I never made a "before" version of this file.

**Comment by Myoldmopar** [comment]
@mjwitte I couldn't tell there was a new test file from Github either.  I ended having to check for any new files added on this branch that aren't on develop, using the command line:  (output trimmed slightly for easier viewing)
```
$ git diff-tree -r --diff-filter=A develop WindowShadingControlOrder
:000000 100644 c7bfa7631ca6a8afdd84dcdc0f0117b67d830d47 A	design/FY2018/NFP-WindowShadeOrder.md
:000000 100644 4ce7e43abd5a9eeab6006a0a2cdb04228c78eadb A	testfiles/PurchAirWithDaylightingAndShadeControl.idf
```

**Comment by mjwitte** [comment]
I've made some modifications to the new test file (header info, monthly design days, fix window 10 coordinates, fewer output variables).  Attaching here rather than trigger another CI round. Zip also includes a -Before version of this which runs with current develop. The May and June results are probably the most interesting in the morning you can see some sequencing in the before version. Not sure why some times in the afternoon show the first 1 or 2 windows are not shaded but the rest are.  [PurchAirWithDaylightingAndShadeControl.zip](https://github.com/NREL/EnergyPlus/files/2315628/PurchAirWithDaylightingAndShadeControl.zip)

**Comment by Myoldmopar** [comment]
@JasonGlazer @mjwitte at this point, it's probably about time to close this up and just open a follow-on issue to evaluate any corner cases and odd behavior.  As long as we are done with the IO side, then please make any final commits, then open up an issue with problematic examples like 

> Not sure why some times in the afternoon show the first 1 or 2 windows are not shaded but the rest are

**Comment by JasonGlazer** [comment]
I would go ahead and merge it since it is clean at this point. The IO changes are complete but it looks like some more testing and fixing edges cases may be necessary. Thanks @mjwitte and @Myoldmopar!

**Comment by Myoldmopar** [comment]
OK.  I will merge now.  Please open up a new issue to track any remaining known tasks.

**Pull request merged**
