### PR TITLE
Install C API header files

### LINKED ISSUE #10072: C API header files are not installed
Issue overview
--------------
When the C library is installed, the API header files are not copied in the installation directory.
Therefore clients linking against energyplus miss fundamental include files to use the library.

The relevant code is in `src/EnergyPlus/CMakeLists.txt`:
```cmake
if(NOT BUILD_STATIC_ENERGYPLUS_API)
  install(
    TARGETS energyplusapi energyplus
    EXPORT energyplus
    RUNTIME DESTINATION ./
    LIBRARY DESTINATION ./
    ARCHIVE DESTINATION ./
    INCLUDES DESTINATION include
                         include/EnergyPlus/api
  )

  include(CMakePackageConfigHelpers)
  write_basic_package_version_file(
    "${PROJECT_BINARY_DIR}/energyplusConfigVersion.cmake"
    VERSION ${ENERGYPLUS_VERSION}
    COMPATIBILITY AnyNewerVersion
  )

  export(
    EXPORT
    energyplus
         NAMESPACE "energyplus::"
         FILE "${PROJECT_BINARY_DIR}/energyplusConfig.cmake"
  )

  install(
    EXPORT energyplus
          DESTINATION lib/cmake/energyplus
          NAMESPACE "energyplus::"
          COMPONENT "CPPAPI"
    FILE energyplusConfig.cmake
  )

  install(
    FILES
      "${PROJECT_BINARY_DIR}/energyplusConfigVersion.cmake"
    DESTINATION
      lib/cmake/energyplus/
    COMPONENT "CPPAPI"
  )
endif()
```
This installs the library and the cmake configuration file used to import it from other projects, but it doesn't copy the API header files.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 11, 22H2)
 - Version of EnergyPlus (23.1.0)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by stal12**
Pull request overview
---------------------
 - Fixes #10072

This pull request adds C include files to the installation of the library, when it is meant to be used as a C API.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
We already install the C header files [here](https://github.com/NREL/EnergyPlus/blob/15550d0997200b520c121b32c8c9a085f0860014/src/EnergyPlus/CMakeLists.txt#L901-L908).  What is it about your situation that isn't working?  They should live in the installed tree, mine are here:

```
$ cd /eplus/installs/EnergyPlus-23-1-0/
$ tree include
include
└── EnergyPlus
    └── api
        ├── datatransfer.h
        ├── EnergyPlusAPI.h
        ├── EnergyPlusPgm.hh
        ├── func.h
        ├── runtime.h
        ├── state.h
        └── TypeDefs.h

2 directories, 7 files

```

**Comment by stal12** [comment]
Hello, thanks for commenting.
I compile and install the library with:
```
mkdir build
cd build
cmake ..
cmake --build . -t install
```
This is the output of the install part:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/FMUParser/parser
-- Set runtime path of "/home/stefano/EnergyPlus/install/PreProcess/FMUParser/parser" to "$ORIGIN"
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-0-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-1-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-2-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-3-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-4-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-5-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V9-6-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V22-1-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V22-2-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/PreProcess/IDFVersionUpdater/V23-1-0-Energy+.idd
-- Installing: /home/stefano/EnergyPlus/install/./libenergyplusapi.so.23.2.0
-- Set runtime path of "/home/stefano/EnergyPlus/install/./libenergyplusapi.so.23.2.0" to "$ORIGIN"
-- Installing: /home/stefano/EnergyPlus/install/./libenergyplusapi.so
-- Installing: /home/stefano/EnergyPlus/install/./energyplus-23.2.0
-- Installing: /home/stefano/EnergyPlus/install/./energyplus
-- Set runtime path of "/home/stefano/EnergyPlus/install/./energyplus-23.2.0" to "$ORIGIN"
-- Installing: /home/stefano/EnergyPlus/install/lib/cmake/energyplus/energyplusConfig.cmake
-- Installing: /home/stefano/EnergyPlus/install/lib/cmake/energyplus/energyplusConfig-release.cmake
-- Installing: /home/stefano/EnergyPlus/install/lib/cmake/energyplus/energyplusConfigVersion.cmake
-- Installing: /home/stefano/EnergyPlus/install/./ConvertInputFormat-23.2.0
-- Installing: /home/stefano/EnergyPlus/install/./ConvertInputFormat
-- Set runtime path of "/home/stefano/EnergyPlus/install/./ConvertInputFormat-23.2.0" to "$ORIGIN"
```
And this is the content of the install directory:
```
stefano@pw55-w11-mo:~/EnergyPlus/install$ tree
.
├── ConvertInputFormat -> ConvertInputFormat-23.2.0
├── ConvertInputFormat-23.2.0
├── PreProcess
│   ├── FMUParser
│   │   └── parser
│   └── IDFVersionUpdater
│       ├── V22-1-0-Energy+.idd
│       ├── V22-2-0-Energy+.idd
│       ├── V23-1-0-Energy+.idd
│       ├── V9-0-0-Energy+.idd
│       ├── V9-1-0-Energy+.idd
│       ├── V9-2-0-Energy+.idd
│       ├── V9-3-0-Energy+.idd
│       ├── V9-4-0-Energy+.idd
│       ├── V9-5-0-Energy+.idd
│       └── V9-6-0-Energy+.idd
├── energyplus -> energyplus-23.2.0
├── energyplus-23.2.0
├── lib
│   └── cmake
│       └── energyplus
│           ├── energyplusConfig-release.cmake
│           ├── energyplusConfig.cmake
│           └── energyplusConfigVersion.cmake
├── libenergyplusapi.so -> libenergyplusapi.so.23.2.0
└── libenergyplusapi.so.23.2.0

6 directories, 20 files
```

[These lines](https://github.com/NREL/EnergyPlus/blob/15550d0997200b520c121b32c8c9a085f0860014/src/EnergyPlus/CMakeLists.txt#L901-L908) of CMake indeed specify rules for installing artifacts, such as static/shared libraries and executables, but not header files.
The meaning of `INCLUDES DESTINATION` is (from [CMake documentation](https://cmake.org/cmake/help/latest/command/install.html#targets)):
> This option specifies a list of directories which will be added to the [INTERFACE_INCLUDE_DIRECTORIES](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html#prop_tgt:INTERFACE_INCLUDE_DIRECTORIES) target property of the \<targets\> when exported by the [install(EXPORT)](https://cmake.org/cmake/help/latest/command/install.html#install-export) command. If a relative path is specified, it is treated as relative to the [$<INSTALL_PREFIX>](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:INSTALL_PREFIX).

And the documentation for `install(EXPORT)` is:
> The EXPORT form generates and installs a CMake file containing code to import targets from the installation tree into another project.

**Comment by Myoldmopar** [comment]
Thanks for the extra clarification.  @jmarrec before I dig in any further I'd love your thoughts here.

**Comment by jmarrec** [comment]
@stal12 You need to pass -DBUILD_PACKAGE:BOOL=ON to cmake and it'll work fine already

https://github.com/NREL/EnergyPlus/blob/6ac42b57bebed08623e9cc47a86360e540261b68/src/EnergyPlus/CMakeLists.txt#L836-L846

line 1005


https://github.com/NREL/EnergyPlus/blob/6ac42b57bebed08623e9cc47a86360e540261b68/src/EnergyPlus/CMakeLists.txt#L997-L1009

**Pull request closed without merging**
