### PR TITLE
Allow zone HVAC terminal units to draw return air from return air plenum and return duct

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
The new feature requests Zone HVAC objects to draw inlet air from return plenum and return duct. It should be pointed out that no return duct losses are calculated in Existing EnergyPlus, except for the AirflowNetwork model (beyond the topic for this new feature). Instead, light heat from return fraction is added to the return node after mixing. Therefore, light heat will be added into the drawn air for the scenario with return duct. There is no modification for the scenario with return plenum. 

This new feature is applied to the system configuration only when a zone equipment and an AirLoop serve the same zone. The proposed IO modification will be made in the ZoneHVAC:EquipmentConnections object by adding a new field as Plenum or Return Air Node Name for the last position, so that no transition is needed for this new feature.

The feature request is GitHub Issue #8190 at https://github.com/NREL/EnergyPlus/issues/8190

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lgu1234** [comment]
This new feature proposal is one of FSEC tasks in FY21. Please let me know your comments and concerns.

**Comment by mjwitte** [comment]
@lgu1234 This has no milestone. Is it intended for v9.5?

**Comment by nrel-bot-3** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by lgu1234** [comment]
A new pull request was created at https://github.com/NREL/EnergyPlus/pull/8719. Close this duplicated one.

**Pull request closed without merging**
