### PR TITLE
Post-v8.8 idd changes

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Catch-all for small IDD changes that missed the v8.8 IDD freeze.

 - [x] @rraustad \type node for new node name in ideal loads
 - [x] @JasonGlazer Conversion factor comment for  W/(m3/s)-Pa to W/(ft3/s)-inH2O - please add correct value to this
 - [x] @XuanLuoLBL Use local nodes for airflownetwork (from https://github.com/NREL/EnergyPlus/pull/6263/commits/120fea85858438dccd4b3a54d48c8a5c2d6a5e7a) - please confirm that the changes are correct here.
 - [x] @aaron-boranian Since ZoneHVAC:IdealLoadsAirSystem added a new input field for System Inlet Air Node Name, the min-fields requirement also needs to be increased by 1. Latent Heat Recovery Effectiveness used to be part of the list of minimum fields to define, and now it is not.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] CI status: all green or justified
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors

### CODE REVIEW

**Comment by xuanluo113** [comment]
@mjwitte That is correct.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by rraustad** [comment]
One more change required before merging. See description.

**Comment by aaron-boranian** [comment]
@rraustad To be clear, the *System Inlet Air Node Name* field is a new addition to the **ZoneHVAC:IdealLoadsAirSystem** object, not the **AirloopHVAC:ReturnPlenum** object mentioned in the description.

**Comment by rraustad** [comment]
Yeah, I just noticed that and corrected.

**Comment by aaron-boranian** [comment]
Cool, just double-checking.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@Myoldmopar Once CI reports back, this should be ready to drop in.

**Comment by Myoldmopar** [comment]
I just pulled develop in one more time to make sure no stray diffs are introduced.  I'll review and let CI build and merge if it's all good.

**Review by Myoldmopar — APPROVED** [review]

**Pull request merged**
