### PR TITLE
Continued Plant Component Refactoring

### PR DESCRIPTION
**Pull request by Myoldmopar**
## Pull request overview

This will bring in another batch of valid Hackathon refactor branches.  The list currently includes:
- WaterUse.*
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the labels applied
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Ummm, that Win64 fail is invalid.  I'm rebuilding that one.

**Comment by Myoldmopar** [comment]
Woo, so good!  Time to bring in some more. 

Let's see ....    :game_die: :game_die:      .......  TypeOfHPWaterPEHeating !!! Congrats @kbenne

**Comment by Myoldmopar** [comment]
Yikes, look at that red!!!    @mbadams5 @kbenne I'll take a look at this, but I suspect you'll immediately see the fix just from the error message.  If you have a tip for the fix but don't want to spend the time coding it, message me and I'll implement it and test it.

**Comment by mbadams5** [comment]
@Myoldmopar This compiles fine locally with VS2015 so it is VS2013 that is having the problem. I don't know the solution yet to make the offending code compatible for VS2013.

**Comment by Myoldmopar** [comment]
So all but one of the Windows CI boxes should be up to date with 2015.  I pulled develop in here, and I will now update the yaml file so that a new version 14 (2015) target is created.  It should build OK on that platform and we can decide what to do.

**Comment by Myoldmopar** [comment]
OK, now 791d9a5 should build OK as long as the single out-of-date CI box doesn't pick up that one specific target.  Roll the :game_die: :game_die: ...

**Comment by Myoldmopar** [comment]
OK, so now _all_ of the Win CI boxes should have 2015, so this should work on that platform no matter which box wins.

**Comment by mjwitte** [comment]
@Myoldmopar Does this mean we plan to require something beyond VS2013 Update 3?

**Comment by Myoldmopar** [comment]
This is part of an evaluation for such a decision, @mjwitte, but nothing has been decided so far.

**Comment by Myoldmopar** [comment]
And so the automated install of VS2015 on the CI box didn't grab the C++ tools after all.  But they are installing now.  I am highly suspect that the 2015 build will be successful the next round, no matter which CI box it lands on.

**Comment by Myoldmopar** [comment]
While the build time was 3 hours, the test time was great.  A typical test time for that box (PC0084243) on a regular branch is about 1400-1500s for Visual Studio 2013.  For Visual Studio 2015, it was 832s.  If that's repeatable, that's an enormous difference.   

@mbadams5 @DeadParrot @mjwitte

**Comment by mjwitte** [comment]
@Myoldmopar That speedup would certainly be useful for package.  Testing a build with the MinSizRel configuration.  That built in 10 minutes on my machine (compared to 2.5 hrs'ish for Release).  Can we go with MinSizRel (O1) for CI testing and Release (O2) for packages?

**Comment by Myoldmopar** [comment]
I hear your point @mjwitte.  Before I jump to that, I'm going to investigate a little more (and @mbadams5 already is as I understand it...).

**Comment by DeadParrot** [comment]
@Myoldmopar I'm not sure about the slow VC++ 2015 builds and I don't see that for release builds locally but a few things to consider:
- Does the /MP (parallel compiles) fight with the make operation also doing parallel compiles, swamping the CPU?
- Is it maxing out the system RAM (related to the first item) causing swapping to disk?

The improved run speed of the test builds is nice but I am seeing release builds run real-world (biggish) cases ~4% slower than VC++ 2013. There are some known performance regressions in VC++ 2015 optimization and library functions that may get fixed in a future update (or may not). If we are interested in run speed we should really evaluate doing public release builds with Intel C++ 2016, where I am seeing some large (up to 4X) performance gains over VC++. Intel C++ builds are horribly slow, though, so it isn't a good choice for a day-to-day compiler.

**Comment by mjwitte** [comment]
@DeadParrot On my machine, the compiles finish quickly and then the bulk of the time is spend linking energypluslib, and RAM is not anywhere near maxed out.

**Comment by DeadParrot** [comment]
@mjwitte So the lib link is what is sitting for a long time, not the compiles. I can't imagine why that is so much slower in VC++ 2015. If the disk i/o is the bottleneck then maybe fast SSDs are the only cure. I guess we need some more data points to understand what is going on.

**Comment by Myoldmopar** [comment]
Another data point: https://connect.microsoft.com/VisualStudio/feedback/details/1303648/build-time-slower-with-vs2015-than-vs2013

**Comment by mbadams5** [comment]
@DeadParrot It took me a hour to compile all of EnergyPlus (using 4 cores, 8 gig RAM in a Win7 VM). Then I waited another hour for it to link before I gave up and tried to start figuring out how to reduce the compile (and linking) times. This is on a machine with a fast SSD so I don't think disk i/o is the problem nor was my machine starved for RAM during compilation/linking.

**Comment by Myoldmopar** [comment]
On that Microsoft link above, one of the comments from MS talks about the build trace file and where to find it.  Maybe that will shine some light?  Maybe everyone already knows about that file except me?

**Comment by mjwitte** [comment]
Never done the trace file.

**Comment by DeadParrot** [comment]
@mbadams5 There might be a performance penalty running in a VM. I'll try some fresh builds here...

**Comment by mbadams5** [comment]
@DeadParrot there might be a very minor penalty but not an order of magnitude. Also it was assigned only half of my processors so I'd be surprised if there was much penalty at all.

**Comment by DeadParrot** [comment]
With current develop I'm still getting good VC++ 2015 release build times:
- Haswell workstation: 4 min (i7-4790K quad core, 32GB RAM, Samsung 850 Pro 1TB SSD)
- Haswell laptop: 6 min (i7-4702HQ quad core, 16GB RAM, Samsung 850 EVO 1TB SSD)

These are both on Win10 with lots of stuff disabled (Search, Superfetch, Prefetch, telemetry, ...). The results suggest that VC++ 2015 might be more h/w hungry or that it is partial to Win10, but none of that is definitive.

Note that I'm building with a script and using `cmake -G "MinGW Makefiles"` and then `make -j8`. Maybe it is letting VS do the builds that is slow? I can share my setup if someone want to try it.

**Comment by mbadams5** [comment]
@DeadParrot Maybe I am wrong but wouldn't `cmake -G "MinGW Makefiles"` cause it to compile with `MinGW` aka `gcc`?

I am using `"Visual Studio 14 2015 Win64"`, which creates a Visual Studio solution that I then open in Visual Studio 2015 and compile.

**Comment by DeadParrot** [comment]
@mbadams5 No, it just creates GNU style makefiles but they are set up for command line VC++ builds. You just need GNU make from MinGW installed on your PATH.

**Comment by mbadams5** [comment]
@DeadParrot Do you mind emailing me your CMakeCache.txt file for you build? I have thus far been unsuccessful in trying to get a makefiles approach that uses MSVC compiler.

**Comment by DeadParrot** [comment]
@mbadams5 Sure. It is all in the script, though. I'll send you both.

**Comment by mbadams5** [comment]
@DeadParrot OK. I think I finally have it figured out after spending too much time on this. When I run your script it does compile it in <10 minutes :+1: ,however, I was baffled why this was happening. When I look at the compiler flags actually passed to cl.exe during compilation, your script and a default CMake build of EnergyPlus are very similar except for two differences. Somehow when you are passing in the `DCMAKE_CXX_FLAGS_RELEASE` flags it is overwriting the default release flags BUT not the flags set in our CompilerFlags.cmake file. This means you are missing `/O2 /Ob2` which are [two optimization flags](https://msdn.microsoft.com/en-us/library/k1ack8f1.aspx) for maximizing speed and aggressive inlining of functions. If I add these two flags to your script then it takes as long as the normal CMake build. You can also see this by removing your passed in flags to cmake.

I will say that the makefile based approach using our default CMake did compile and link faster on the command line than within Visual Studio.

Also, there are a few files that are HOGS when it comes to the compiler spending a lot of time trying to optimize them. DXCoils is by far the worst.

**Comment by DeadParrot** [comment]
@mbadams5 Good catch! That may also explain the performance slowdown I was seeing although I built with VC++ 2013 the same way. I don't have this issue with Intel C++ because I set all the optimization flags so I didn't notice this with VC++. So the automatic options are overridden while the ones set with ADD_CXX_RELEASE_DEFINITIONS are appended to -- how I do love fighting with CMake to get different builds!

So I guess we are left with VC++ 2015 doing much slower builds than VC++ 2013 and no good explanation. (Sadly, this is still >2X faster than Intel C++.) Maybe day-to-day builds would be better done with `/O1 /Ob1`.

Yes, DXCoils has been a problem for a while. Previous versions of a couple of compilers simply died compiling it without reducing the optimization level. Maybe it is worth looking into what is going on with it at some point.

**Comment by mbadams5** [comment]
@Myoldmopar @DeadParrot 
Ok so I think I found the offending flag between those two optimizations. When I change `Ob2` to `Ob1` it dramatically reduces the compile time down to ~10 minutes for me. These flags are [described here](https://msdn.microsoft.com/en-us/library/47238hez.aspx).

Now the big question is whether or not the more aggressive inlining of `Ob2` improves runtime performance by a noticeable margin (and I don't have time to test that).

**Comment by DeadParrot** [comment]
@mbadams5 That is good to hear because I tried just changing to `/O1` and the build was still >90min. My guess is that `/Ob1` won't cost much for EnergyPlus performance: I think most inline-critical functions are already explicitly or implicitly declared inline and the rest are too big to inline. A public release could still be built with `/Ob2` if it is beneficial as long as some testing is done with that build. I vote for changing the CMake setup to use `/Ob1` (in a way that overrides the default `/Ob2`). The performance benchmarks should tell us if there is a significant penalty.

BTW I got an ICE compiling DXCoils.cc with `/O2 /Ob2` added to my VC++ release options after it sat for a long time. Maybe `/Ob1` will fix that but this code needs some attention. If it is going nuts trying to inline we could try some NEVER_INLINE macros.

**Comment by mjwitte** [comment]
O1 Ob1 is exactly what the MinSizRel configuration is vs Release with O2 Ob2.
@mbadams5 when you said you changed to Ob1 was that with O2 or O1?
I can do some timing tests today to see what the build and runtime impacts are of O1 vs O2 and Ob1 vs Ob2 .

**Comment by mbadams5** [comment]
@mjwitte 
It was with `\O2` so it was a hybrid of MinSizeRel and Release.

Basically you need to do what Edwin just committed.

**Comment by mjwitte** [comment]
OK then it looks like we'll get a runtime impact from CI shortly.

**Comment by Myoldmopar** [comment]
Sort of, since the performance tests are linux only (Valgrind....).  But it was super lucky that the VS2015 build hit the _same CI box_ as it did yesterday, so we'll have a nice comparison.  I still want to do local testing, but this is a nice bonus.

**Comment by mbadams5** [comment]
It will only be design day runs. The Performance CI is linux only, but yes it will give a beginning inkling.

**Comment by mjwitte** [comment]
Right - not the official performance - but a comparison against the runtimes noted [above](https://github.com/NREL/EnergyPlus/pull/5526#issuecomment-194504625)

> While the build time was 3 hours, the test time was great. A typical test time for that box (PC0084243) on a regular branch is about 1400-1500s for Visual Studio 2013. For Visual Studio 2015, it was 832s.

**Comment by Myoldmopar** [comment]
Prior build above:
- build_time: 10973.701224
- test_time: 832.3692

Build just now with ObiWan:
- build_time: 1427.34904
- test_time: 805.6776

:8ball: All signs pointing to freaking yes.

**Comment by mjwitte** [comment]
:+1:  :+1:  :+1:

**Comment by mbadams5** [comment]
Ok I ran annual RefBldgOutpatient with `\O2 \Ob1` and `\O2 \Ob2`.

\Ob1
7min 45.41sec
\Ob2
7min 49.12sec

So i'll be curious to see either @Myoldmopar or maybe @mjwitte results from running annual simulations locally to corroborate my results.

**Comment by DeadParrot** [comment]
Looking good! So I wonder why can't google find any complaints about `/Ob2` being very slow and not very useful.

**Comment by Myoldmopar** [comment]
I'm installing 2015 on my VM right now so I can run some more local tests.  This was a huge find, @mbadams5.

**Comment by DeadParrot** [comment]
I ran one of my performance cases and it is also showing the `/Ob1` build being slightly faster.

**Comment by DeadParrot** [comment]
So I tried the `/Ob1` with Intel C++ and it is helping with build times there also without any performance hit seen in a few cases I tried.

Is it OK if I add those CompilerFlags.cmake changes on this branch along with the ones for VC++?

**Comment by Myoldmopar** [comment]
OK.  We are seeing a dependency problem with VS2015.  An early diagnose thanks to some preliminary OpenStudio testing of release packages of EnergyPlus -- so send thanks along @kbenne.  Basically it is _forgetting_ to package up a runtime library.  Because of the time left before release, we will **not** be attempting to rush 2015 in for the release.  So this branch will stay dormant for the mean time.  

@DeadParrot yes, have at it.  Add the same flags for Intel if you wish.  

Sometime post release we will move to 2015 and get the kinks worked out.

**Comment by Myoldmopar** [comment]
But for reference, I can add to the confirmation of 2015 from a build-time run-time standpoint.  I ran several tests locally and it looks great, so that won't be a hold-up from moving to 2015.  Just other testing.

**Comment by Myoldmopar** [comment]
I don't like this red-ness on the dashboard, so I'm going to close this now and I'll reopen later.

**Pull request closed without merging**
