### PR TITLE
Remove std namespace from cpgfunctionEP headers

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
Remove `using namespace std;` from headers in cpgfunctionEP.
Since this is in the headers, it pollutes the EnergyPlus namespace with `using namespace std;`, which we have avoided.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
It looks like `third_party/cpgfunctionEP-0.5/src/utilities.cpp` needs an include fix.  Do you want me to address it?

**Comment by mitchute** [comment]
> It looks like `third_party/cpgfunctionEP-0.5/src/utilities.cpp` needs an include fix. Do you want me to address it?

This should be taken care of here: https://github.com/NREL/EnergyPlus/commit/86e152bfbc66fd65c01794935e29ef62d264341b

I tested locally on Linux, so 🤞  it works.

**Comment by mbadams5** [comment]
Thanks @Myoldmopar and @mitchute, it is interesting Mac was fine to compile it without the include but linux was not.

**Review by Myoldmopar — APPROVED** [review]
More good changes that will need to be ported back upstream @j-c-cook .  If CI is happy across the board I'll merge this in the morning.  Thanks @mbadams5 and @mitchute.

**Comment by mitchute** [comment]
I started over on #9031. Closing this in lieu of that.

**Pull request closed without merging**
