### PR TITLE
api/datatransfer.cc: remove extraneous semicolons (`;`) in `listAllAPIDataCSV`'s output

### PR DESCRIPTION
**Pull request by dogganon**
Pull request overview
---------------------
~~- Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)~~
~~- DESCRIBE PURPOSE OF THIS PULL REQUEST~~
This pull request aims to remove the extraneous semicolons (`;`), as the output CSV is already line (`\n`) terminated.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@chen1682-ntu-edu-sg thank you for noticing this!  Even though this is a tiny change, to be able to include your commit and merge this down, we'll need a contribution agreement.  Could you check out the page [here](https://energyplus.net/contributing) and if you are able to, send me over an agreement.  And if you have any questions, please email me at edwin _dot_ lee _at_ nrel _dot_ gov ?  Thanks!

**Comment by dogganon** [comment]
@Myoldmopar I agree to contribute to EnergyPlus. I agree to the following terms and conditions for my contributions: First, I agree that I am licensing the copyright to my contributions under the terms of the current EnergyPlus license. Second, I hereby grant to Alliance for Sustainable Energy, LLC, to any successor manager and distributor of EnergyPlus appointed by the U.S. Department of Energy, and to all recipients of a version of EnergyPlus that includes my contributions, a non-exclusive, worldwide, royalty-free, irrevocable patent license under any patent claims owned by me, or owned by my employer and known to me, that are or will be, necessarily infringed upon by my contributions alone, or by combination of my contributions with the version of EnergyPlus to which they are contributed, to make, have made, use, offer to sell, sell, import, and otherwise transfer any version of EnergyPlus that includes my contributions, in source code and object code form. Third, I represent and warrant that I am authorized to make the contributions and grant the foregoing license(s). Additionally, if, to my knowledge, my employer has rights to intellectual property that covers my contributions, I represent and warrant that I have received permission to make these contributions and grant the foregoing license(s) on behalf of my employer.

**Comment by Myoldmopar** [comment]
Thanks @chen1682-ntu-edu-sg, received agreement via email as well, this is fine to go in now.

**Review by Myoldmopar — APPROVED** [review]
Obvious change, no point in **not** taking this.  Merging.  Thanks @chen1682-ntu-edu-sg

**Pull request merged**
