### PR TITLE
Spawn of swig

### PR DESCRIPTION
**Pull request by macumber**
Pull request overview
---------------------
Adds cmake code to run swig to generate python bindings for epfmi

[test.py.txt](https://github.com/NREL/EnergyPlus/files/2939729/test.py.txt)

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I don't imagine this actually needs to be an open pull request.  The CI bots are going to start hassling us that the PR is outdated.  I'm closing it, but the branch can live on as needed.

**Comment by macumber** [comment]
I tried to make it a draft pr to indicate that it wasn’t ready to actually merge, might be worth setting the ci bots to ignore draft prs?

**Comment by Myoldmopar** [comment]
I like that idea @macumber.  I added it to my list.  Right now the draft status is only available on a preview API which is subject to change (https://developer.github.com/v3/pulls/#list-pull-requests) so I wouldn't be making any Decent CI changes to ignore it until that stabilizes.  And if you actually intend on merging this into the spawn branch soon, then go ahead and reopen it.

**Comment by macumber** [comment]
I think this is back on @kbenne to create a more permanent, nicer API to swig.  Doubt that it would get merged anywhere before that happens.  Also, the merge target was spawn and not develop, I'm not sure if CI should care about that or not.  Anyway, no hurt feelings, all good :-)

**Pull request closed without merging**
