### PR TITLE
Performance tuning; Autodesk contribution / ObjexxFCL Updates

### PR DESCRIPTION
**Pull request by DeadParrot**
This bundles some performance tuning contributions from Autodesk that give a nice boost to a few types of cases and an ObjexxFCL update that is meant to be transitional toward the planned migration to the row-major array version of ObjexxFCL.

Nothing controversial here I think but I did flip the index order of the T/QsrHist arrays to get better cache efficiency, which could be considered annoying but it does produce a speed bump.

There are some small numerical diffs causing test "failures".

### CODE REVIEW

**Comment by DeadParrot** [comment]
The test failures appear to be consistent with my testing and are at the small/expected level but I'm happy to review any diffs that are of concern.

**Comment by Myoldmopar** [comment]
@DeadParrot I merged develop into this branch to resolve the (minor) conflicts, and am building release builds of develop and this to run overnight.  I'll run annual simulations with daily or monthly output to quickly check for any big red flags.  Hopefully it will come out clean and we can merge this soon.

**Comment by DeadParrot** [comment]
@Myoldmopar Great. Thanks. If you get any performance info out of your test sets I'd be interested to see what you find.

**Comment by Myoldmopar** [comment]
@DeadParrot I'm still seeing the same behavior on my machine with fresh builds across the board.  @jasondegraw is doing Windows testing and @kbenne is doing Mac testing currently.  If their results are similar to what you are seeing, I am satisfied that it is just my thrown together version of GCC causing me issues.

**Comment by DeadParrot** [comment]
@Myoldmopar OK, but I'd still like to know what is going on if there is some Linux/GCC oddity. I could try it on Ubuntu 14.10 as another data point if you think that would give us more assurance -- just let me know. It might be something in the CMake options too but I can't imagine anything making that big a difference.

**Comment by Myoldmopar** [comment]
@DeadParrot If you can try it on Ubuntu 14.10 that would definitely be more assurance.  For kicks I can also do this on the Ubuntu CI machine, but I'd put the automated runs on hold so that I could get good results.  I think just the more data points the better. 

So yeah, tomorrow I'll pause the CI tests and run the builds on the 14.04 machine.  That, combined with @kbenne and @jasondegraw and any more of your tests should give us good confidence.

**Comment by DeadParrot** [comment]
@Myoldmopar OK, I will try to run this tonight and I'll post what I find.

**Comment by Myoldmopar** [comment]
@DeadParrot OK, thanks for confirming the behavior and adding the compiler switch to address the speed issue.  As for the other compiler switches, I was hoping to unmute all the warnings soon and address them, so you've started me down that path here I guess.  However, I don't want to muddy up your branch with that aspect.

 - My plan is to pull this branch, build and test those problem files with the new configuration, and report on the status of that.  
 - Re-mute the compiler flags for this branch so that the dashboard doesn't blow up when this gets merged into develop.  
    - Merge develop into this branch at the same time to resolve the merge conflict(s) present.
 - As soon as this gets merged into develop, make a branch and re-un-mute all the compiler warnings, and address them in that branch, so that the dashboard remains clean.

Does that sound OK?

@lefticus @kbenne @jasondegraw

**Comment by kbenne** [comment]
@Myoldmopar yes.  Please don't reintegrate with this much red.

**Comment by Myoldmopar** [comment]
@kbenne OK.  Can I just change the font color to [DB5700](http://www.color-hex.com/color/db5700)?

**Comment by Myoldmopar** [comment]
@DeadParrot OK, I went ahead and made the changes I mentioned above.  I didn't touch the Windows compiler flags, so if it is still noisy, we might have to mute it in one last commit.  As I mentioned, I'll re-un-mute these in a separate branch to get them addressed in short order.

**Comment by Myoldmopar** [comment]
Oh, and @kbenne, I'm looking through now, but I expect [these](http://energyplus.s3-website-us-east-1.amazonaws.com/ee0b1079f7201038b09af57df0ff623b4eb48682-beef4e46c8a3a47f55a9507fc2ddf28a58e2c6f7/4ZoneWithShading_Simple_1/x86_64-MacOS-10.9-clang/eplusout.eio.diff.html) are the types of diffs that are going to cause lots of red regressions.

**Comment by Myoldmopar** [comment]
@DeadParrot [This](http://energyplus.s3-website-us-east-1.amazonaws.com/ee0b1079f7201038b09af57df0ff623b4eb48682-beef4e46c8a3a47f55a9507fc2ddf28a58e2c6f7/5ZoneAirCooledConvCoef/x86_64-MacOS-10.9-clang/eplusout.audit.diff.html) small audit file diff came up.  Would you expect this based on some improvement you made?

**Comment by Myoldmopar** [comment]
And also, geez, the eio diffs are almost entirely at the very last sig fig on every result I open up.

**Comment by Myoldmopar** [comment]
And also, only 3 files had err file diffs, and they are just tiny diffs implying convergence was attained at very slightly different times.  It's good.  If this is green on the build results side, I'll look over the red regression results a bit more, but I'd like to merge this in soon.

**Comment by DeadParrot** [comment]
@Myoldmopar The audit diffs are expected: these are capacity, not in use sizes. This is due to the change of some array resizing to use a std::vector style approach of doubling rather than adding a fixed increment. This trades performance for some space use but if the space is a problem it is still best to to do one redimension shrink operation after the arrays are fully filled. I am seeing ~5% more memory use with this change. It isn't a massive performance gain so if the team hates this it is easily reverted.

**Comment by DeadParrot** [comment]
@Myoldmopar Whatever option changes you need to make are fine. I wanted to get this going and thought it might help to address some option issues as a group. The only important one for this aligned memory speed issue is `-DOBJEXXFCL_ARRAY_NOALIGN`.

**Comment by Myoldmopar** [comment]
This is looking great, even though it is going to be all red due to the tiny diffs.  Every one I sample looks good.  We'll let CI finish up this afternoon, but this should be readily merged so we can move on with these speed benefits.

**Comment by DeadParrot** [comment]
@Myoldmopar OK, sounds good. Once it is merged I'll branch for the row-major code. Thanks!

**Pull request merged**
