### PR TITLE
Fix when "other" shows up incorrectly in ABUPS end-used by subcategory table

### LINKED ISSUE #7556: "Other" heating subcategory appears (incorrectly)
Issue overview
--------------
See IDF below where >12 GJ of energy appears in an "Other" heating subcategory in the End Uses By Subcategory output table. The subcategory is being automatically created. Across several hundred test IDFs, this is the _only_ file where this subcategory appears. In every other test file, heating energy correctly shows up in the "General" subcategory. (This particular test file includes a complex set of HVAC systems serving a single conditioned zone.)

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3725469/in.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - Version 9.2.0-921312fa1d

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #7556 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Literally changing the default end-use subcategory in SetupOutputVariable just has too many repercussions. I don't think it is worth the effort to fix all the stuff that gets broken by this change for the solution we are looking for (just to fix the End Uses By Subcategory table in ABUPS).

**Comment by JasonGlazer** [comment]
I still think this has way to many impacts for what we are trying to do. I think I'm just going to focus on producing the end-use by subcategory report without the "other" row.

**Comment by JasonGlazer** [comment]
@mjwitte a lot of the unit test problems were related to setting up a variable and defining a new "end use" that was not one of the typical end uses. I ended up adding code here:

https://github.com/NREL/EnergyPlus/blob/587008775f1627a89d6a0aeee244b61cf8ef2278/src/EnergyPlus/OutputProcessor.cc#L3971

to prevent the new "general" end use subcategory from triggering the error message. They used to slip by because they had no end use subcategory so this routine wasn't called. What do you think of this fix? 

How have all these output variables being setup been using enduses that never existed in the "official" list in the past?

**Comment by mjwitte** [comment]
@JasonGlazer So, that "standard" list of end-uses corresponds with ABUPS rows. Other end-uses will create meters which can be used like any other meter, but aren't (hopefully) on any of the major utility resources like Electricity or NaturalGas. So, clearly, none of the things that are tripping now are passing in a subcategory. So, maybe we roll this back a little and add the "General" default subcategory only to end-uses that are in this list?

**Comment by JasonGlazer** [comment]
Looking over the CI results, the json output file diffs are reported because of column mismatch which makes sense given the changes to meters. The RadLoTempHydrMulti10 tabular difference seems to be a fix to something that was reported wrong before.

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar  VS2019 is reformatting lots of lines I'm not touching, should I have something configured differently to avoid this?

**Comment by mjwitte** [comment]
@JasonGlazer In VS, I have automatic reformatting turned off.  

Tools --> Options --> Text Editor --> c/c++ --> Formatting --> General --> Clang format execution "Run Clangformat only for manually invoked formatting commands". 

Then I just do manual formats via Edit --> Advanced --> Format Selection. This avoids extraneous formatting. 

Why autoformatting doesn't match what's already in the repo? Don't know, and stopped caring a while ago.

**Comment by JasonGlazer** [comment]
@mjwitte Thanks.

**Comment by JasonGlazer** [comment]
I think this is ready to be reviewed.

**Comment by mjwitte** [comment]
@JasonGlazer This PR has conflicts now. 
I added the OutputChanges label - this needs to go in before I/O freeze.
Please add an entry to \src\Transition\OutputRulesFiles\OutputChanges9-2-0-to-9-3-0.md describing the impact of this PR.

**Comment by JasonGlazer** [comment]
@mjwitte I will take a look

**Pull request closed without merging**
