### PR TITLE
81117318 fix idf versions

### PR DESCRIPTION
**Pull request by Myoldmopar**
Some of the idfs that were introduced in the middle of the 8.2 development cycle hadn't been transitioned up to 8.2.  Nothing was required to transition in their objects, the version just needed to be incremented.  At the same time, cleaned up the weather file definition for a scalable sizing file to use a weather file that was actually included in the repository.  That could show diffs, but it's expected.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
There may still be some lingering version things, but I'll address those later.  This branch has lingered for no reason for quite a while.  I merged develop in to resolve the merge issue and also see the CI results.  There should be minor diffs because I _corrected_ a weather file and it will also clean up version errors in the error file.

**Comment by mjwitte** [comment]
@Myoldmopar  I'm concerned if we delete the version comments from the imf files that we will lose track of what version they are at.  Not sure of a good solution that won't leave us in the same boat.  Perhaps we could have transition write a special comment at the top of imf files that it would update automatically?

**Comment by Myoldmopar** [comment]
I'll look into it; thanks for the comment.

**Comment by Myoldmopar** [comment]
@mjwitte I think given that I'd like to revamp the transition process as a whole, (stepping around the separate topic about overall input syntax change), I don't think I'll add any logic to carefully replace version information in imf files (comments).  I think I'll just keep it a little manual maintenance.  I'll go into this imf files and update them to just reflect the currently developing version and they'll stay that way until we (I) manually update them again.  Not a big deal.  Once I make that change, I think this should be merged.

**Comment by Myoldmopar** [comment]
And done.  Let me know if there are any issues, or if you'd like me to point it at anyone else, or merge at will.

**Comment by mjwitte** [comment]
@Myoldmopar I'll take it.  Will wait for at least a few CI reports.

**Comment by Myoldmopar** [comment]
Ci looks fine to me, merge as you see fit

**Pull request merged**
