### PR TITLE
Add fixtures to CMakeLists

### PR DESCRIPTION
**Pull request by mbadams5**
This isn’t necessary for the code to compile, but is good practice as
it allows Visual Studio to show the files in the solution explorer.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
> isn’t necessary for the code to compile

But it does cause the code not to compile?  :wink:

**Comment by Myoldmopar** [comment]
Aaaah what?

```
No CMAKE_CXX_COMPILER could be found.
```

**Comment by mbadams5** [comment]
@Myoldmopar Ok I merged in develop which should fix the failing tests and I fixed my windows CI machines so they don't fail compiling now. And no this change did not cause the code to not compile.

**Comment by Myoldmopar** [comment]
Don't try to fool me!  This change [did](https://github.com/NREL/EnergyPlus/pull/5050#commitcomment-12378659) cause the code to not compile!! :wink: 

OK, OK, ok.  After CI comes back happy I'll merge this.

**Pull request merged**
