### PR TITLE
82706250 adaptive convection new

### PR DESCRIPTION
**Pull request by lgu1234**
Avoid hard crash by making numerical calculation the same as mathematical calculation.

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 You mentioned that ISNAN seemed slow, so I am going to run some timing tests on some example files and the defect files to see if there is any significant change in run time.

**Comment by mjwitte** [comment]
Fixes #4791  Fixes #4646 Fixes #4591 Will test to verify all three of these.

**Comment by lgu1234** [comment]
@mjwitte What I meant slow is to have slow debug. I did not test ISNAN performance. The function call was used to catch NAN in my testing. You determine whether we need to keep the function call or not.

**Comment by Myoldmopar** [comment]
OK, so @mjwitte @lgu1234, if I go through and remove the isnan checks, this should be good to go in your eyes?  It looks good to me and I'd like to get it in right away.

**Comment by mjwitte** [comment]
@Myoldmopar I'm in the process of building and running this with all the related defect files.  You think we need to remove the isnan checks?

**Comment by Myoldmopar** [comment]
Yeah, I think we should...but go ahead and test with them if you want.  I can comment them and push a new commit up.

**Comment by mjwitte** [comment]
@Myoldmopar Be sure to merge in develop at the same time.

**Comment by Myoldmopar** [comment]
@mjwitte Done.  If CI is good with it and your testing goes fine; we'll merge it into develop today.

**Comment by mjwitte** [comment]
@lgu1234 We need to fix the warnings to be recurring and fix the language:
   ** Severe  ** CalcBeausoleilMorrisonMixedOpposingWall: Convection model not evaluated (would divide by zero)
   **   ~~~   ** Calculation resulted in negative argument to pow()
   **   ~~~   ** Occurs for zone named = THERMAL ZONE 2-7
   **   ~~~   ** Convection surface heat transfer coefficient set to 9.999 [W/m2-K] and the simulation continues

"(would divide by zero)" shouldn't be in these messages.

**Comment by mjwitte** [comment]
Defect file HVAC_01_02_4000_L_001-ddays-exp (from #4591 ) generates an err file that is over 98,000 lines long.

**Comment by Myoldmopar** [comment]
@mjwitte I don't understand.  Is that bad?

**Comment by mjwitte** [comment]
@Myoldmopar No, not really, 'cause LWwallDBL40Ventilation_V820-MoreOutput-DeleteDuplicateSurfaces err file is over 300k lines.  Looks like recurrings are getting accumulated but the individual warnings are still coming out.

**Comment by lgu1234** [comment]
@mjwitte @Myoldmopar Let me make recursive warning.

**Comment by mjwitte** [comment]
@Myoldmopar @lgu1234 Never mind about the recurring errors.  I had pulled an old branch for testing.  Retested with this branch, and all looks well.  Once CI reports back, this can be merged.

**Pull request merged**
