### PR TITLE
Add annual reporting option

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
Add an annual output option. There was already an "annual" choice available for output, but it always gave the same results as requesting "runperiod" outputs. This PR changes the code so that the an actual yearly value is produced. For single-year simulations, requesting "annual" reporting gives results identical to "runperiod", but there will now be both outputs in the results. For multi-year simulations or simulations that are not 1/1-12/31, "annual" and "runperiod" will represent different time periods.

I've replaced the const int frequency identifiers with an enumeration, and replaced a number of the if-then-else forests with switch statements. There's a new timestamp in the text outputs, and the ***SQL timestamps now have a year field***. The diffs are expected and are due to report identifier renumbering, there should be no real diffs.

The current calendar year of the simulation is tracked in a new variable, `DataGlobals::CalendarYear`. There were a couple of other possible places already existing, but those are are all associated with the weather file. I have left those intact so that any EMS programs that might be using that will continue to work unchanged. The new variable is not always set to something meaningful, that'll be addressed in a followup PR that combines `RunPeriod` and `RunPeriod:CustomRange`.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by macumber** [comment]
@jasondegraw if I understand correctly, this primarily affects how timeseries variables are reported, is that right?  I think I must not be understanding this correctly?

```
Output:Variable,*,Site Outdoor Air Drybulb Temperature,Hourly; !- reported at each hour with no year in timestamps
Output:Variable,*,Site Outdoor Air Drybulb Temperature,RunPeriod; !- reported at once end of run period with no year in timestamp
Output:Variable,*,Site Outdoor Air Drybulb Temperature,Annual; !- reported at midnight on 12/31 with year in timestamp
```

**Comment by jasondegraw** [comment]
@macumber That's sort of correct. For text output (ESO, etc) the only thing that has a year in the timestamp are annual variables/meters. but for the SQL there is a year in the timestamp for everything except "runperiod" variables/meters.

**Comment by jasondegraw** [comment]
I forgot that I needed to modify the IDD comments, so this actually is an IDD change.

**Comment by Myoldmopar** [comment]
The code changes for this seem OK to me.  The enum changes alone really improve the readability of the code, though they are so extensive that it's a little hard to scan through and see all the actual functional changes.

Other branches have merged into develop so the diffs shown here aren't just from this branch.  I'll merge develop in here one more time soon and see if the diffs go back to making sense.

The last time we had a structural change in the SQLite output, we had some complaints, so I just want to make sure plenty of people are aware of this change before it drops in: @mbadams5 @kbenne @macumber @nllong @lgentile

**Comment by Myoldmopar** [comment]
This looks very clean from CI's perspective.  @jasondegraw there aren't any new example files for this though?  Do you have one you used during testing?  I know our CI tests are typically design-day-only runs for CI efficiency, but still it would be nice to have an example there.

**Comment by Myoldmopar** [comment]
Given the still relatively high number of PRs we want to get run through CI, I'm not waiting on a test file to get added to this branch.  I'll make one locally, verify the outputs look good, and if so I'll merge this in and post a follow-up issue to add an example file.

**Comment by jasondegraw** [comment]
I ran a couple of test files locally, just used existing example files and added some yearly outputs. A follow-up issue sounds good to me.

**Comment by Myoldmopar** [comment]
I went ahead and added a very simple multiyear test file out of 1ZoneUncontrolled.  Testing it locally I see good results using a mix of annual and runperiod frequencies.  Merging now.  Thanks @jasondegraw.

**Comment by macumber** [comment]
@evanweaver DView crashes on this new output

ResultsViewer opens the file but doesn't show values for annual report

**Comment by evanweaver** [comment]
@macumber, not too surprising :(

Is there an example file to be had?

**Comment by mjwitte** [comment]
@jasondegraw Also, a description of the output changes should be added to [OutputChanges8-8-0-to-8-9-0.md](https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/OutputRulesFiles/OutputChanges8-8-0-to-8-9-0.md)

**Comment by jasondegraw** [comment]
@mjwitte Oops, missed that. PR put in.

**Comment by macumber** [comment]
@evanweaver 

[eplusout.sql.txt](https://github.com/NREL/EnergyPlus/files/1738868/eplusout.sql.txt)

**Comment by mjwitte** [comment]
@evanweaver Also, see this [description](https://github.com/NREL/EnergyPlus/blob/7f74f5d0994b498efe4408941f7099b6930bfcec/src/Transition/OutputRulesFiles/OutputChanges8-8-0-to-8-9-0.md) of the changes.

**Comment by macumber** [comment]
@jasondegraw is this what is supposed to show up for reporting frequency in the report data dictionary?

image

Also the time table goes from year 0 (whole year up to 12/30), to year 1 (lasts one day 12/31), to year 2 (1/1-12/31).  Does that sound right?  I added these input objects to the test file:
 
    Output:Variable,*,Zone Mean Air Temperature,hourly;
    Output:SQLite, SimpleAndTabular;

**Comment by macumber** [comment]
@evanweaver this has an hourly report too

[eplusout.sql.txt](https://github.com/NREL/EnergyPlus/files/1739125/eplusout.sql.txt)

**Comment by jasondegraw** [comment]
@macumber That first one is probably a bug, which isn't too surprising considering that there isn't a unified  enumeration (yet). On the second one, no, that doesn't seem right, but if you're using RunPeriod then what ends up in the year field may be not all that useful. If you send me the IDF I can take a look.

**Pull request merged**
