### PR TITLE
Correcting Non-physical GLHE Outlet Temps

### PR DESCRIPTION
**Pull request by mitchute**
The ground heat exchanger exiting fluid temperatures are being computed incorrectly. See the figure below for an example.

4ts

I'm documenting the issue here for now, but will update with a fix later.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@mitchute Helpdesk ticket 12887 may be related.

**Comment by nrel-bot-2** [comment]
@mitchute @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 60 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@mitchute it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 42 days since this pull request was last updated.

**Comment by rraustad** [comment]
Are these build failures accurate and need some form of correction to code?

**Comment by Myoldmopar** [comment]
@rraustad I'm guessing this won't be done for this release and just needs to be set to the next milestone.  @mitchute can you confirm and change the milestone?

**Comment by mitchute** [comment]
@Myoldmopar that's correct; next release.

**Comment by nrel-bot-2b** [comment]
@mitchute @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
Closing to get off PR list. Issue will be addressed in #7002.

**Pull request closed without merging**
