### PR TITLE
Correction of Infrared Transparent Material Code and Interior Radiation Exchange

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
This pull request addresses some issues with the infrared transparent material code.  First, it did not properly assign that this was an R-only layer and cleaned up the code in the get routine for this material type.  In addition, it also corrected an issue with the interior radiation balance that resulted when using an infrared transparent material.  This imbalance was the result of doubling the surface area without doubling the potential impact on the zone.  As there is no rationale for doubling the impact of this surface type on the rest of the zone, the original surface area is now maintained and the radiation on the interior side balances.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue #7384 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by RKStrand** [comment]
@mjwitte The two test files that have differences are ones that use the IRT material.

**Comment by mjwitte** [comment]
@EnergyArchmage You ok with these changes?

**Review by mjwitte — CHANGES_REQUESTED** [review]
Merged in develop and resolved the conflicts. Tested before and after with StackedZonesWithInterzoneIRTLayers example file (with additional outputs). Surface Inside Face Net Surface Thermal Radiation Heat Gain Energy across all surfaces balances to zero now.

Unit test looks good.

But the engineering reference needs changes to remove or alter the 2x area discussion.

**Comment by RKStrand** [comment]
@mjwitte I missed the eng ref changes that were needed and as I look back at the code I have to admit that I'm having a bit of "coder's remorse".  The description in the Eng Ref sort of makes sense with the simple case that it presents.  Though I am still having a hard time agreeing with it fully given that E+ is not as simple as the case presented in the Eng Ref.  So perhaps the second approach would be better--leaving the original doubling of area and then adjusting the NetLWRadToSurf.  I'd like to switch to that.  This would not require any changes to Eng Ref but to the code.  I will look into that asap...but for some reason, I'm not seeing any of the commits that you made on this branch.

@Myoldmopar Any idea why I'm not seeing the commits that Mike made?

**Comment by RKStrand** [comment]
@Myoldmopar Never mind...I got Mike's commits to show up.  User (my) error.

**Comment by mjwitte** [comment]
@RKStrand I tried the 2xNetLWRadToSurf a while back during the airwall development and ran into some instability. But I may have done it incorrectly back then. So, let's see what you come up with.

**Comment by RKStrand** [comment]
@mjwitte Ok, that's interesting.  Doubling the NetLWRadToSurf, the test input file does yield a net radiation balance in all three zones from what I saw.  However, the net radiation to individual surfaces is REALLY high (45kW for some surfaces like the IRT) and the temperatures for the IRT surfaces are not reasonable (-30C).  So, while I think I have done the correct change to double the NetLWRadToSurf for just the IRT surfaces, the end result is not what we want.  The net radiation to surfaces numbers for what I initially did in this are much closer to what the numbers for develop are and so are the temperatures for those "fake" surfaces.  I didn't see anything go unstable and cause a crash, but under other conditions that happening is a definite possibility.

So...I will adjust the language in the Eng Ref.  I think the example presented their works in a simple case, but the surface heat balance is not a simple case.  I will do what I can to adjust what's there.

**Comment by RKStrand** [comment]
@mjwitte I've made some changes to the Eng Ref to reflect the changes that were made to the code with respect to the radiation exchange and committed them.  Let me know if you have any questions or concerns.

**Review by mjwitte — APPROVED** [review]

**Comment by mjwitte** [comment]
Not waiting for more CI cycles here. Merging.

**Pull request merged**
