### PR TITLE
Add error check for zone nodes being used more than once

### PR DESCRIPTION
**Pull request by rraustad**
Addresses issue #4407  Check for use of the same zone node name in more than one place, such as in ZoneHVAC:EquipmentConnections and in AirLoopHVAC:ReturnPlenum (or SupplyPlenum). This is a severe/fatal error as it will cause invalid results.

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Note this PR fixes the same issue as #5150 - only one of these should go in.

**Comment by rraustad** [comment]
I do like Jason's fix and unit test. The fix is more generic and the unit test is very compact. 
My change does have clear-state fixes, but I can live without those (I'll copy them into something else).

As a side note, for #5174, I could have registered the uncontrolled zone's air node and then used that in the code instead of ZT and ZoneAirHumRat (i.e., write the zone air node number into the condenser inlet air node).

**Comment by Myoldmopar** [comment]
OK, so this one needs to just be closed un-merged now that #5150 is going to go in?

**Comment by mjwitte** [comment]
Correct. Closing.

**Comment by mjwitte** [comment]
Oh but this has additional content - doc changes and clear states - so maybe it would be useful with just the node name changes removed.  @rraustad

**Comment by mjwitte** [comment]
Maybe it would be cleaner to move the changes from #5150 into here.

**Comment by mjwitte** [comment]
Alternate node test and additional unit test from #5150 added here.  Should test clean with no diffs.

**Comment by rraustad** [comment]
I missed this discussion, got caught up in RH control for water coils. I like that these were merged.

**Comment by Myoldmopar** [comment]
@rraustad I pulled in develop, and there was a small conflict in a `clear_state` function that I think I cleaned out properly.  The conflicted version was:

```
<<<<<<< HEAD
        GetInputFlag = true;
        NumZonePlenums = 0;
        NumZoneReturnPlenums = 0;
        NumZoneSupplyPlenums = 0;
//      CheckRetEquipName.deallocate();
//      CheckSupEquipName.deallocate();
=======
        NumZonePlenums = 0;
        NumZoneReturnPlenums = 0;
        NumZoneSupplyPlenums = 0;
        CheckRetEquipName.deallocate();
        CheckSupEquipName.deallocate();
>>>>>>> origin/develop
```

So in this branch, the `GetInputFlag` was _added_ to the `clear_state`, while the `CheckRetEquipName` and `CheckSupEquipName` deallocations were commented out.  Thus, I ended up with:

```
        GetInputFlag = true;
        NumZonePlenums = 0;
        NumZoneReturnPlenums = 0;
        NumZoneSupplyPlenums = 0;
```

If this is good, then fine, but if the `CheckEquipName` deallocations should actually be put back in, then that needs to happen before this is merged.

**Comment by rraustad** [comment]
This is good. Those arrays get dimensioned [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZonePlenum.cc#L388-L389) in GetZonePlenumInput which will be called [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZonePlenum.cc#L210-L212) if GetInputFlag is true. So no need to deallocate in clear_state, they will just get redimensioned (and set to true) since GetInputFlag was added and set to true in clear_state.

**Comment by Myoldmopar** [comment]
I took another look at the code, and ended up adding the ( parentheses ) ( padding ) ( spaces ).  It still built locally.  I'm going to go ahead and merge it in.

**Pull request merged**
