### PR TITLE
fixing vshpwh stratified tank bug

### PR DESCRIPTION
**Pull request by nmerket**
This fixes it. You can see the before it was broken and now simulation results at:
http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/4969350/notebooks/vshpwh_strat_integration.ipynb

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@nmerket I was worried for a second when I saw the test failure!  But it is fine.  The error file shows diffs.  The diffs are removal of warning messages which became present on develop release builds because of the array bound issue you actually solved.  If CI is happy I'll merge this fix in.

**Comment by mjwitte** [comment]
@nmerket Is there an issue describing this bug?  The notebook link above is broken.

**Comment by nmerket** [comment]
@mjwitte No, we didn't create an issue for this. It came from [this comment thread](https://github.com/NREL/EnergyPlus/commit/e07692e592865fadb3ed77c2d8a1bedaa838ecf7#commitcomment-12303904). I took down the ipython notebook when this got merged in, so that's why you couldn't find it. I put it back up though and you can see it [here](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/4969350/notebooks/vshpwh_strat_integration.ipynb).

**Comment by mjwitte** [comment]
@nmerket Got it.  So, was this bug lurking before #4698 residential HPWH improvements or introduced with that?

**Comment by nmerket** [comment]
It was introduced with that.

**Pull request merged**
