### PR TITLE
Release testing enhancements - Reverse Design Day and Annual Simulation

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview

This PR adds additional release build targets for "Reverse Design Day" and "Annual Simulation"

 - The "Annual Simulation" target works by enabling the `TEST_ANNUAL_SIMULATION` CMake configuration option. Interestingly, I'm not seeing longer test times on the dashboard.
 - The "Reverse Design Day" target works with a new `REVERSE_DESIGN_DAY` option. I have verified that it does set the flag properly locally, since it is one I just added.

---------------------
### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] How much longer simulation times should we be seeing with the "Annual Simulation" runs? Does the dashboard look correct?
 - [ ] Should we expect to see dashboard failures for "Reverse Design Day" since the baseline does not have that option available?
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by lefticus** [comment]
@Myoldmopar FYI, this PR is still open if you want these additional tests.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 31 days since this pull request was last updated.

**Comment by rraustad** [comment]
So which files failed ReverseDD testing using this method?

**Comment by lefticus** [comment]
According to the bot history messages, last time this branch was built, none of them did.

**Comment by mjwitte** [comment]
Hmm, sounds too good to be true.

**Comment by rraustad** [comment]
@Myoldmopar it sounds like it's time to test for ReverseDD diff's using the old method so the we have something to comapre to.

**Comment by lefticus** [comment]
This is how it is enabled: using the environment flag: https://github.com/NREL/EnergyPlus/pull/6058/commits/326b69b8307dfbae096ad22234f8caa2510adf9d during testing I did monitor the output from EnergyPlus to ensure that the flag was being set correctly. However, it has been 5 months since I delivered this so it's difficult to recall the details.

**Comment by Myoldmopar** [comment]
@mitchute has worked on this recently.  I think he's got a good list to start from.

**Comment by Myoldmopar** [comment]
@lefticus there's actually more to it than just setting the flag.  We need to bring in some additional changes.  As I mentioned, I think @mitchute has been working on that, and we could probably start from his work to get CI doing actual reverse DD runs.  We should have a chat about it.  I'll email separately.

Beyond that, if you are wanting reverse DD results as of now, I again think @mitchute may have a starting list.

**Comment by mitchute** [comment]
Last time I worked on this, which admittedly has been a few months, I had the following files fail:

Large Diffs
```
5ZoneAirCooledWithCoupledInGradeSlab.idf
ASIHPMixedTank.idf
Fault_ChillerSWTSensorOffset_RefBldgLargeOfficeNew2004.idf
Fault_FoulingChillerBoiler_RefBldgLargeOfficeNew2004.idf
RefBldgLargeOfficeNew2004_Chicago-ReturnReset.idf
RefBldgLargeOfficeNew2004_Chicago.idf
UnitarySystem_WaterCoils_wMultiSpeedFan.idf
ZoneCoupledGroundHTBasement.idf
ZoneCoupledGroundHTSlabInGrade.idf
```

Small Diffs
```
1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf
2ZoneDataCenterHVAC_wEconomizer.idf
5ZoneFanCoilDOAS_HumidifierOnOASystem.idf
Attic_ASTM_C1340_Base_Case.idf
ChangeoverBypassVAV_AirToAir.idf
ChangeoverBypassVAV_AirToAirHeatPump.idf
DOAToWaterToAirHPInlet.idf
DOAToWaterToAirHPSupply.idf
GSHP-GLHE.idf
GSHP-Slinky.idf
GSHPSimple-GLHE.idf
HeatPumpSecondaryCoil.idf
HeatPumpWaterToAir.idf
HeatPumpWaterToAirEquationFit.idf
HeatPumpWaterToAirWithAntifreezeAndLatentModel.idf
HeatPumpWaterToAirWithAntifreezeAndLatentModel2.idf
PlateHeatExchanger.idf
UnitarySystem_VSHeatPumpWaterToAirEquationFit.idf
VSHeatPumpWaterToAirEquationFit.idf
WWHPSimpleAuto.idf
ZoneCoupledGroundHTSlabOnGrade.idf
```

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @lefticus @lgentile it has been 31 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lefticus @lgentile it has been 15 days since this pull request was last updated.

**Pull request closed without merging**
