### PR TITLE
Fixing calculation of EMPD surface mass transfer coefficient based on known heat-transfer coefficient

### PR DESCRIPTION
**Pull request by nmerket**
In the process of setting up the new EMPD model #5093, @jdwoods21 found and fixed the following bug:

> the equation below was changed because the previous equation was incorrect. The specific heat (PsyCpAir...) is defined on a dry-air basis [J/kg_da-K], so you want to multiply only by the density of air, (PsyRhoAir...) [kg_da/m^3]. Adding to this the vapor density (RhoVaporAirIn) puts the density on a total air/vapor mixture basis [kg_total/m^3], which is inconsistent with how the specific heat is defined, and thus gives the incorrect answer.

@Myoldmopar We pulled this out of the new feature EMPD branch.

### CODE REVIEW

**Comment by mjwitte** [comment]
@nmerket Can you make the title and description more specific about the scope of this change?  If appears this impacts only surface moisture balance calculations?

**Comment by nmerket** [comment]
@Myoldmopar What do we need to get this in?

**Comment by nrel-bot-3** [comment]
@nmerket @lgentile it has been 14 days since this pull request was last updated.

**Review by mjwitte — COMMENTED** [review]
@nmerket @jdwoods21 Does this equation show up in the engineering reference?

**Comment by nmerket** [comment]
Not that I'm aware of. @jdwoods21 did you see this equation in the engineering reference?

**Comment by jdwoods21** [comment]
No, I did not see it in the engineering reference. I’m fairly certain it is not in there.

**Comment by mjwitte** [comment]
@nmerket @jdwoods21 Merged.

**Comment by nmerket** [comment]
Thank you.

**Pull request merged**
