### PR TITLE
Added sentence to IOref about shading and DElight after testing

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #4046

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte A small change to the documentation after I did some testing.

**Comment by mjwitte** [comment]
Is it feasible to add an error message when DElight is used where shading surfaces are present in the input?

**Comment by JasonGlazer** [comment]
I just looked at the test files and found no specific error message is included for this situation. Should adding one be part of this issue or should I create a new issue for that?

**Comment by mjwitte** [comment]
I would just add it here.

**Comment by JasonGlazer** [comment]
Do you think it would be adequate to add a warning if the count of any of the SHADING:\* objects is greater than zero when the count of any DAYLIGHTING:DELIGHT:\* is greater than zero?

**Comment by mjwitte** [comment]
Seems reasonable.

**Comment by JasonGlazer** [comment]
Addresses the code changes in #4046 
Related to the documentation change in #5444

**Pull request merged**
