### PR TITLE
Add a solver field to AirflowNetwork SimulationControl

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
Add a solver field to the AirflowNetwork SimulationControl object to control which solver gets used to solve the pressure network. Right now, only "SkylineLU" has any meaning, but that'll change once the solver refactor is complete.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs

### CODE REVIEW

**Comment by jasondegraw** [comment]
I've got some warnings to work out yet, working on that right now.

**Comment by Myoldmopar** [comment]
bitmoji

**Comment by Myoldmopar** [comment]
I fixed one of the build warnings just now as it had snuck into develop.  There was also a filename typo (casing) that I fixed.  If you pull develop, you'll have at least a couple less issues now.

**Comment by Myoldmopar** [comment]
The only build warning remaining is the DataZoneEquip, which is fixed in develop now.  Windows looks all clean.  Merging to get this out of the way for any others.

**Pull request merged**
