### PR TITLE
Air-To-Water Heat Pump with Heat Recovery

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - This new feature adds capability to support heat recovery in air-to-water heat pumps
 
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by EnergyArchmage** [comment]
Here is rough feedback from TRANE... 

"Could the setup be expanded to 4 pipe units without any control changes?

Maybe I am mis-interpreting the diagram is this a four-pipe unit (or) a 2-pipe unit with heat recovery? 

Our definition of 2 pipe is it can only operate in only one mode (control to a particulate CHW or HW Setpoint). 4 pipes could control to both. 

Also, Bob did mention that we do sell heat recovery on four-pipe units but usually it works when its cooling dominant and recovered heat will be to supplement the heating side. To our awareness, the second diagram is not in market yet. 


We do agree Brent that we need extra modifier curves to support heat recovery operation, something like below :

I am using VRF example (AIrConditioner:VariableRefrigerantFlow object fields on heat recovery modifier)"

1.	 
image

2.	 
image


Sounds to me like the model could be setup to handle both 2 pipe or 4 pipe.  If there are both of the heating and cooling companion coils for the AWHP, then its a 4 pipe (6 pipes with HR and considering both companions), if no companion heat pump, then it is 2 pipe (4 pipe with HR).

**Comment by Nigusse** [comment]
@EnergyArchmage Thanks. Please take a look at my response below.

(1) It should be either 2-pipe or 4-pipe ASHP configurations with a heat recovery option. This implies the 2-pipe ASHP with heat recovery becomes a 4-pipe system, and the 4-pipe ASHP with heat recovery becomes a 6-pipe system, assuming the heat recovery generates either HW or CW at a time. The schematic in the initial NFP is just a simple display of the heat recovery concept. I am trying to create a schematic of the equipment and plant layout topology for a 6-pipe system in the EnergyPlus context. It is helpful to see if you have an actual equipment and plant layout configuration of such a system.

(2) It is possible to use different capacity modifier curves when the ASHP operates in heat recovery mode. I must add a new capacity modifier curve input field for cooling and heating modes.

(3) A question regarding the `Heat Recovery Ambient Relief Modifier Curve.` Is this curve also used to adjust the heat recovery mode capacity? If that is the case, I need to understand how these curves are normalized to implement them correctly.

**Comment by nrel-bot-2c** [comment]
@Nigusse @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Nigusse @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Merging this design/NFP only PR.  It accompanies #10455 (and #10544 )

**Pull request merged**
