### PR TITLE
Followup evap cooler flow autosizing fix

### PR DESCRIPTION
**Pull request by Myoldmopar**
@mjwitte This bumps the autosize flow rates back up as expected.  I'll update the unit test to catch this case and it should drop in easily.

Fixes #4940

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@mjwitte I updated the unit test to cover the lines changed plus also other code paths at the same time.  I pulled develop in just now as well.  If CI comes back green, this should go right in.

FYI @Nigusse

**Comment by Myoldmopar** [comment]
OK @mjwitte; the new unit test covers the line changed for this follow-up as well as a few additional lines in the size routine.  This is good to go in at your will.

**Comment by mjwitte** [comment]
@Myoldmopar I'm thinking I should merge this one and then we'll figure out what's missing in #5136 Does that seem like the best path forward?

**Comment by Myoldmopar** [comment]
Yes and thanks for re-opening that one to make sure it all gets in properly.

**Comment by mjwitte** [comment]
@Myoldmopar Is this PR a DoNotPublish? This just puts the secondary flow back to v8.3 values, correct?

**Comment by Myoldmopar** [comment]
Yeah, good call.  I changed it.

**Pull request merged**
