### PR TITLE
Removed lines causing latex error and clean up

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes a latex error introduced from #10372 
 
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
I should have called attention to the change in how I showed tables in the original pull request. Instead of trying to reproduce some of these very wide tables, I just used an image of the table. To facilitate searching, I also included a list of the column names. I would like @Myoldmopar @mjwitte and @rraustad to take a look at the output details doc for the Equipment Summary table for Chillers, Boilers, Cooling Towers and Fluid Coolers, Plant or Condenser Loop, and Air Terminals. Here is a screen shot of the boiler page.


Capture07

**Comment by Myoldmopar** [comment]
Awesome, thanks for the quick fix up, @JasonGlazer.  The documentation build passed happily now, and the rendered output details file is here for convenience:

[OutputDetailsAndExamples.pdf](https://github.com/user-attachments/files/16349593/OutputDetailsAndExamples.pdf)

I see all the table images you used but also laid out the column names as bullets.  That's nice.  I guess personally I wouldn't have worried about getting a full image in there since you were already laying out the column names, but it's kinda nice, so I say leave it.  I didn't go in and scrutinize every column name or anything, but spot checking looked good.

I'm inclined to merge to clean up the doc build in develop, please lay out any concerns soon-ish.

**Comment by rraustad** [comment]
Where is the definition of Reference/Rated Capacity/Efficiency? I wanted to see what these columns represented.

**Comment by JasonGlazer** [comment]
I think the rated and reference are from the chillers that use those inputs and are left blank if those inputs aren't part of the input object.

**Comment by JasonGlazer** [comment]
Looks like the CI came back clean (no surprise since it did not touch anything but a .tex file).

**Comment by Myoldmopar** [comment]
I'm going to go ahead and drop this in to clean up other PRs, thanks @JasonGlazer

**Pull request merged**
