### PR TITLE
Protect divide by 0 for Terminal Unit with Zone Floor Area = 0

### PR DESCRIPTION
**Pull request by rraustad**
## Pull request overview

Zone floor area must be greater than 0 when AirTerminal:SingleDuct:VAV:Reheat input for Maximum Flow per Zone Floor Area During Reheat is entered as AutoCalculate (#5273).
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

…Size Maximum Flow per Zone Floor Area during Reheat is AutoCalculate

### CODE REVIEW

**Comment by rraustad** [comment]
The way this is now may be too restrictive. If floor area = 0, then they get no flow during reheat. If I only set Sys( SysNum ).MaxAirVolFlowRateDuringReheat = 0, and leave Sys( SysNum ).MaxAirVolFractionDuringReheat to calculate it's own value, then MaxAirVolFractionDuringReheat = 0.3 and MaxAirVolFlowRateDuringReheat will wind up as 0.367 since:

```
Sys( SysNum ).MaxAirVolFlowRateDuringReheat = max( Sys( SysNum ).MaxAirVolFlowRateDuringReheat, Sys( SysNum ).MaxAirVolFractionDuringReheat * Sys( SysNum ).MaxAirVolFlowRate );

where:
  MaxAirVolFlowRate = 1.223

AirTerminal:SingleDuct:VAV:Reheat,
  Constant,                !- Zone Minimum Air Flow Input Method
  0.3,                     !- Constant Minimum Air Flow Fraction
  ,                        !- Fixed Minimum Air Flow Rate {m3/s}
  ,                        !- Minimum Air Flow Fraction Schedule Name
  AUTOCALCULATE,           !- Maximum Flow per Zone Floor Area During Reheat {m3/s-m2}
  AUTOCALCULATE;           !- Maximum Flow Fraction During Reheat
```

The user won't know what is setting the maximum flow during reheat, unless I show a warning, but then there is already a warning in the err file about zone floor area = 0.

```
 ** Warning ** No floor exists in Zone="ZN_1_FLR_1_SEC_1", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
```

I guess this needs more discussion and can wait until after release.

**Comment by rraustad** [comment]
Decided that discussion above dictated what needed to be done here. Since the model uses the max of the Maximum Flow per Zone Floor Area During Reheat and Maximum Flow Fraction During Reheat, they should each size independently and be used to calculate the final Maximum Flow per Zone Floor Area During Reheat. When you think about it, as zone floor area goes to 0, the Maximum Flow Fraction During Reheat becomes the limit. This code does just that.

```
// use the larger of the two reheat flow rate methods for the simulated maximum flow during reheat
Sys( SysNum ).MaxAirVolFlowRateDuringReheat = max( Sys( SysNum ).MaxAirVolFlowRateDuringReheat, Sys( SysNum ).MaxAirVolFractionDuringReheat * Sys( SysNum ).MaxAirVolFlowRate );
Sys( SysNum ).MaxAirVolFlowRateDuringReheat = min( Sys( SysNum ).MaxAirVolFlowRateDuringReheat, Sys( SysNum ).MaxAirVolFlowRate );
```

**Comment by rraustad** [comment]
Why would the performance change on the Full Dashboard when this fix changed nothing in the test suite results?

**Comment by Myoldmopar** [comment]
Just because of the extra checking being done.  Same numeric results but it is an extra couple steps along the way.  The difference is very small, and I don't see a way to easily _not_ have the conditional statement in there with this fix.  So it's fine.  Thanks.

**Pull request merged**
