### PR TITLE
Fix bug in IDFVersionUpdater when updating 22.1 files to 22.2

### LINKED ISSUE #9625: IDFVersionUpdater not working for V22-1-0 files to V22-2-0-IOFreeze
Issue overview
--------------

IDFVersionUpdater not working on Linux for V22-2-0-IOFreeze.

```shell
mkdir tmp
cd tmp
cp /usr/local/EnergyPlus-22-1-0/ExampleFiles/1ZoneUncontrolled.idf 
grep Version 1ZoneUncontrolled.idf 
>  Version,22.1;
../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/IDFVersionUpdater
```

image

The "New Version" dropdown also only shows 22.1, it does not detect 22.2

All the required files are there though:

```
$ ls ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/*22*
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/OutputChanges22-1-0-to-22-2-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/OutputChanges9-6-0-to-22-1-0.md
'../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Report Variables 22-1-0 to 22-2-0.csv'
'../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Report Variables 9-6-0 to 22-1-0.csv'
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Rules22-1-0-to-22-2-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Rules9-6-0-to-22-1-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Transition-V22-1-0-to-V22-2-0
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Transition-V9-6-0-to-V22-1-0
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/V22-1-0-Energy+.idd
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/V22-2-0-Energy+.idd
```

### Details

Some additional details for this issue (if relevant):

 - Platform (Operating system, version): Ubuntu 20.04
 - Version of EnergyPlus (if using an intermediate build, include SHA): V22-2-0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #9625 
 - Removes erroneous error message and completes the transition of 22.1 files to 22.2

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x]  Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@jmarrec and @Myoldmopar I tested this fix on Windows 10, MacOS 10.14 and Ubuntu 20.04. The last two were the VMs that I had handy. If you have different version of MacOS or Ubuntu to try it on, I would appreciate it. Thanks.

**Comment by jmarrec** [comment]
@JasonGlazer On my Ubuntu 20.04 I get this:

image

I see you added the mac libGzip.dylib in this PR, seems like linux might need it too?

**Comment by JasonGlazer** [comment]
@jmarrec please confirm this is happening when you start IDFVersionUpdater?

**Comment by jmarrec** [comment]
Yes, it's the xojo portion not the transition utilities

**Comment by JasonGlazer** [comment]
@jmarrec I missed that XOJO's updated some of its libraries. They were in github but just not being put into the installer. I just updated install.cmake. I don't have a development set up for Linux. Could you please see if it working now on Linux?

**Comment by jmarrec** [comment]
@JasonGlazer Adding them to the install.cmake is good. But you also need to commit those libs, I don't have them in the checkout of the branch

**Comment by JasonGlazer** [comment]
@jmarrec sorry, the linux *.so files were in the right folder but somehow I had not added them to the repo and they were being ignored, I must have been going to fast that day.

**Comment by Myoldmopar** [comment]
@JasonGlazer yeah, built binary blobs like `.so` files are ignored intentionally so that no one accidentally adds their EnergyPlus build artifacts to the repository history.  In the rare cases we need to update these, it just takes a force to override the ignore file.  Anyway, I tested on Ubuntu, and confirmed develop won't work, but this branch does work fine and produces a 22.2 file.  Merging this one in.  Thanks @JasonGlazer and @jmarrec

**Comment by Myoldmopar** [comment]
@JasonGlazer (or @jmarrec) there is something wrong with the changes here, as our packages won't build on Windows:  https://github.com/NREL/EnergyPlus/actions/runs/3085012770/jobs/4987822328.  If you have any thoughts on the matter, please advise or push up a fix.  Let me know if you need me to work on it, but for now I'll leave it to you.

**Comment by jmarrec** [comment]
Some Xojo DLL files for windows are not commited to the repo, same as the .so on linux. I would also double check the mac...

https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/cmake/Install.cmake#L463-L464

That file (and a couple others) isn’t commited to the repo (edited) 
https://github.com/NREL/EnergyPlus/tree/develop/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs

Exactly the same reason as when I pointed the linux libs were missing, it’s because the gitignore has it excluded https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/.gitignore#L3

**Comment by Myoldmopar** [comment]
When looking deep at the filename changes in this PR, it looks like the Mac bundle got an extra layer of `.app` here.  For example, the `plist` file was [moved](https://github.com/NREL/EnergyPlus/pull/9636/files#diff-34049abc787096936b976446f33731ed9b823efa1c63d3493460d8c31b10274a), with the old and new file names:

```
old: bin/IDFVersionUpdater/Run-Mac/IDFVersionUpdater.app/Contents/Info.plist
new: bin/IDFVersionUpdater/Run-Mac/IDFVersionUpdater.app/IDFVersionUpdater.app/Contents/Info.plist
```

While the installer is properly grabbing the contents of the `Run-Mac/IDFVersionUpdater.app` "top-layer" bundle, at install time, the installer tries to find the underlying contents relative to the "top-layer" bundle, and fails.  I will have to rename these files one layer up and see what happens.

FYI @JasonGlazer @jmarrec

**Comment by JasonGlazer** [comment]
That may have been my mistake in how I copied the files. Dealing with the app "bundle" is a little weird on Windows. Feel free to rearrange the files however they make the most sense. I will try to be extra careful next time.

**Pull request merged**
