### PR TITLE
Using correct executable name in shell script

### PR DESCRIPTION
**Pull request by nmerket**
The `runenergyplus` shell script wasn't pointing to the `energyplus` executable anymore. This fixes that.

@shorowit

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Hmmm, I'll let @nealkruis comment.  We are supposed to be providing the `EnergyPlus` binary as well for backward compatibility.  Maybe @kbenne will have a thought too, as far as moving away from the backward compatibility at some point.

I'll be freezing the code very shortly for the bug fix release, so if you have a strong opinion on this, please speak now.

**Comment by Myoldmopar** [comment]
Also, can you confirm the platform that you are seeing this?

**Comment by Myoldmopar** [comment]
But _actually_, as I noted in the shell script _every time it runs_ [here](https://github.com/NREL/EnergyPlus/blob/9c3ca4dfca4b88fc733cb223181f77253a42d641/scripts/runenergyplus.in#L35-L41), that script is obselete and users should be using the command line interface.  With that in mind, I don't care if this change goes in.  It will be transparent to the users if they are still relying on this script in their own workflow.  Except that it will work better :+1:.

OK merging.

**Comment by kbenne** [comment]
:+1: for merge

**Comment by nmerket** [comment]
We ran into this trying to use runenergyplus on Peregrine, so Linux. And, yes, I told @shorowit to use the new cli. It's just a legacy set up, so we don't want to spend time bringing it up to date even though we're going to start using Open Studio Server soon.

**Pull request merged**
