### PR TITLE
Update sqlite library

### PR DESCRIPTION
**Pull request by mbadams5**
This updates sqlite library to 3.8.8.2 and brings various bug fixes and a ~3.2% overall speed up to sqlite.

https://www.sqlite.org/releaselog/3_8_8_2.html

### CODE REVIEW

**Comment by kbenne** [comment]
I seem to recall we had some issues with the LTO/PGO related to sqlite engine changes.  I will need to test this with a release build, but at the moment there are other problems with the release that need to be worked out first.

**Comment by mbadams5** [comment]
@kbenne There was an issue previously but I thought it was resolved? Either way, I agree it would be good to test with a release build tag.

**Comment by kbenne** [comment]
@mbadams5 it's probably fine, but I'm not taking any chances after being surprised by failed packages a couple of time now.  Not exclusively because of sqlite.

**Comment by Myoldmopar** [comment]
So we took out LTO on Linux with the recent pull request, does that mean this can drop in before release?

**Comment by Myoldmopar** [comment]
(@kbenne @lefticus @mbadams5)

**Comment by kbenne** [comment]
lets let that merge run through the system and then do it.

**Pull request merged**
