### PR TITLE
Reduce Alternate Build Configurations Built by Github Actions

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Reduces the number of alternate build configurations built on Github Actions from 6 to 1
 - Eliminates duplicate base build which is already being built by DecentCI
 - Moves builds from Mac to Linux in hopes that GH Actions will be more responsive

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Yay!! It looks like it is still creating quite a few builds.  Having it as push and pull is fine, but I don't think we need both Ubuntu 18 and 20.  And I'm torn on whether we need the base build.  What do you think?

**Comment by mitchute** [comment]
I was just going to make sure that the base build completes then we can turn it off. I also need to eliminate the Python install on the alternate build, but I'm waiting to make sure this all completes OK before making another commit. I'll also turn off the 18.04 build when I do that.

**Comment by Myoldmopar** [comment]
I think you'll still need the Python install on the alternate build because CI looks for it just to do the build itself.  I think.  Hmm.  Yeah I think so.  OK, cool on the Ubuntu version as well.  This will be super helpful!  Thanks!

**Comment by mitchute** [comment]
Hmm, maybe we just keep it building on either "push" OR "pull_request"? Turning on "pull_request" will turn on builds on PRs from forked repos but likely won't build anything in this repo until a PR is opened. Thoughts @Myoldmopar

**Comment by mitchute** [comment]
Also, it appears that CMake was happy *without* a Python install. The current commit seems to be building OK so far.

**Comment by mitchute** [comment]
** Without an explicit Python 3.7 install. It looks like 20.04 comes pre-installed with a version of 3.8, unless this is a stripped-down version. 

https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default

**Comment by Myoldmopar** [comment]
I think keeping it like you have it right now is good.  Doing a PR build and a push build ensures we get results for all the commits we expect, but now we are down to just two builds per PR.  Quite reasonable to me!

**Comment by mitchute** [comment]
Sounds good. Merge at will.

**Comment by Myoldmopar** [comment]
I'll let everything finish up and if it's all green, it'll go right in.  Thanks for the quick effort getting all these runs cleaned up.

**Comment by Myoldmopar** [comment]
Hey yo, look at all that green.  This is a great thing.  Thanks @mitchute!  Merging.

**Comment by mitchute** [comment]
🤘

**Pull request merged**
