### PR TITLE
Fix UnitarySystem Setpoint Control and WaterToAirHeatPump:EquationFit Companion Coil Sizing

### LINKED ISSUE #9793: UnitarySystem Setpoint control issues
Issue overview
--------------
1. User file has AirloopHVAC:UnitarySystem with Setpoint control and Coil:Cooling/Heating:WaterToAirHeatPump:EquationFit. The cooling coils do not operate. Eventually stumbled across [these changes](https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827#diff-a4469a58b3b57ae5c4916cb9efb12f0c6ef79224175d09c796a7f6c2e1d3ec33R11606-R11616) in https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827 (part of #8729, v9.6).

These lines were added:
```
                Real64 NoOutput = 0.0; // CoilSystem:Cooling:DX
                Real64 ReqOutput = 0.0;
                FullOutput = 0.0;
                if (this->m_sysType == SysType::CoilCoolingDX) {
                    NoOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                               (Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(OutletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                    ReqOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                                (Psychrometrics::PsyHFnTdbW(DesOutTemp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                 Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                }
```
`ReqOutput` is being redefined here and stomping on the value calculated back up in line 12411 of UnitarySystem.cc This breaks what appears to be the FullOutput pass for coil types `Coil_CoolingWaterToAirHPSimple` and `Coil_CoolingWaterToAirHP`, because these two coil types use `ReqOutput` as a parameter to the coil simulation function. The other coil types use some other variables such as the part load frac, so they are still working (not really confirmed, but assumed).

I think technically it's defining a new `ReqOutput` in a tighter scope which is supposedly legal code, but really bad, because any use of `ReqOutput` in the tighter scope uses the new one instead of the original. If there's a way to get the compilers to yell about this, that would be great (because this is the second bug introduced by the same problem).

I've started on a tentative fix locally. Just commented out the `Real64 ReqOutput = 0.0;` on line 12652.

2. UnitarySystem with Setpoint control and Coil;Heating:Electric as the supplemental heating coil generates this fatal error, but a control node input isn't supposed to be required when the coil is wrapped in a UnitarySystem.
```
   ** Severe  ** Coil:Heating:Electric "ELEC HTG COIL 13"
   **   ~~~   ** ... Missing control node for heating coil.
   **   ~~~   ** ... enter a control node name in the coil temperature setpoint node field for this heating coil.
   **   ~~~   ** ... use a Setpoint Manager to establish a setpoint at the coil temperature setpoint node.
   **  Fatal  ** ... errors found in heating coil input.
```

*WAHP companion coil sizing issue moved from here to #9849*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v22.2 (also v22.1 and v9.6 ~v9.5~).
 - [Unmethours 86434](https://unmethours.com/question/86434/unitary-system-water-air-cc-control-issues/)
 - Helpdesk tickets 16321 and 16322.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9793
 - Fix UnitarySystem with Setpoint control problem where Coil:Cooling:WaterToAirHeatPump:EquationFit would never run. 
 See defect file 9793-in-v22.2.idf
 - Fix UnitarySystem with Setpoint control missing Control Node error when Coil:Heating:Electric (and likely some other coil types) is the supplemental heating coil. 
 See defect file ElectricSuppHeatingCoilControlNodeError-v22.2.idf
 - Fix companion coil array bounds error when Coil:Cooling:WaterToAirHeatPump:EquationFit and Coil:Heating:WaterToAirHeatPump:EquationFit are wrapped in 2 separate UnitarySystems. 
 See defect file 9793-Solution2-Separate UnitarySystems-in-v22-CompanionCoilCrash

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Unit tests fail [here](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-8799ee3a217e3604a366f9fd40731840cf9d6964-x86_64-Linux-Ubuntu-18.04-gcc-7.5-UnitTestsCoverage-Debug.html).

**Comment by mjwitte** [comment]
CI Diffs
* Five idf files were edited to remove unnecessary setpoint control node names and to clean up other unrelated warnings. This results in AUD, BND, and Table diffs. e.g. `regression.5Zone_Unitary_VSDesuperheater`
```
BND
- Node,8,REHEAT COIL AIR INLET NODE,Air,4
- Node,9,VAV SYS 1 OUTLET NODE,Air,7
+ Node,8,REHEAT COIL AIR INLET NODE,Air,3
+ Node,9,VAV SYS 1 OUTLET NODE,Air,6

Table (delta)
FullName:Object Count Summary_Entire Facility_Input Fields
Count
IDF Objects	2.0
```
* Four tests have err diffs, most are removing warnings, e.g.
```
-   ** Warning ** ProcessScheduleInput: Schedule:Constant="SUPPLY AIR HUM RATE SCHEDULE", Blank Schedule Type Limits Name input -- will not be validated.
-   ** Warning ** Coil:Heating:Fuel "MAIN HEATING COIL 1"
-   **   ~~~   **  The "Temperature Setpoint Node Name" input is not required for this heating coil.
-   **   ~~~   **  Leaving the input field "Temperature Setpoint Node Name" blank will eliminate this warning.
-   ** Warning ** The following Report Variables were requested but not generated -- check.rdd file
-   **   ~~~   ** Either the IDF did not contain these elements, the variable name is misspelled,
-   **   ~~~   ** or the requested variable is an advanced output which requires Output : Diagnostics, DisplayAdvancedReportVariables;
-   ************* Key=*, VarName=COOLING COIL SOURCE SIDE HEAT TRANSFER RATE, Frequency=Hourly
-   ************* Key=*, VarName=UNITARY SYSTEM CYCLING RATIO, Frequency=Hourly
-   ************* Key=*, VarName=UNITARY SYSTEM COMPRESSOR SPEED RATIO, Frequency=Hourly
-   ************* There are 2 unused schedules in input.
-   ************* Use Output:Diagnostics,DisplayUnusedSchedules; to see them.
```
And a slight change in error for `EMSSetpointBasedMultiSpeedDXCoilOverrideControl`
```
-   **   ~~~   ** Estimated part-load ratio  = 0.889
+   **   ~~~   ** Estimated part-load ratio  = 0.888
```
* One file has MTD diffs
```
- Meters for 1289,SUPPLY FAN 1:Fan Electricity Energy [J]
+ Meters for 1292,SUPPLY FAN 1:Fan Electricity Energy [J]
```
* And `WaterSideEconomizer_PreCoolCoil` has small eso diffs. Not sure why, but they're tiny, on the order of e-13.

**Comment by mjwitte** [comment]
Defect file results.
*9793-in-v22.2.idf*
develop, this branch
image   image

*ElectricSuppHeatingCoilControlNodeError-v22.2.idf*
develop
```
   ** Severe  ** Coil:Heating:Electric "ELEC HTG COIL 13"
   **   ~~~   ** ... Missing control node for heating coil.
   **   ~~~   ** ... enter a control node name in the coil temperature setpoint node field for this heating coil.
   **   ~~~   ** ... use a Setpoint Manager to establish a setpoint at the coil temperature setpoint node.
   **  Fatal  ** ... errors found in heating coil input.
   ************* EnergyPlus Terminated--Fatal Error Detected. 293 Warning; 4 Severe Errors; Elapsed Time=00hr 00min  7.66sec
```
this branch
```
   ************* EnergyPlus Completed Successfully-- 13784 Warning; 3 Severe Errors; Elapsed Time=00hr 01min 54.48sec
```

*9793-Solution2-Separate UnitarySystems-in-v22-CompanionCoilCrash*
develop-debug - crash
develop-release
```
COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP CLG COIL 1, Design Size Rated Air Flow Rate [m3/s], 1.71982
COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP CLG COIL 1, Design Size Rated Total Cooling Capacity [W], 62479.84393
COIL:HEATING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP HTG COIL 2, Design Size Rated Heating Capacity [W], 62479.84393
```
this branch - smaller heating capacity, because it's not linked to the cooling coil - not sure about this @rraustad ?
```
COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP CLG COIL 1, Design Size Rated Air Flow Rate [m3/s], 1.71982
COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP CLG COIL 1, Design Size Rated Total Cooling Capacity [W], 62479.84393
COIL:HEATING:WATERTOAIRHEATPUMP:EQUATIONFIT, WTR-TO-AIR HP HTG COIL 2, Design Size Rated Heating Capacity [W], 486.02159
 ```

**Comment by rraustad** [comment]
Being a heat pump would dictate that the coil sizes are linked since it's really a single coil. Whether the heating coil has a multiplier (e.g., 1.3 ish) should also be handled IF the model allows that type of input, which the UnitarySystem model has. The fact that heating coil sizing occurs at a much lower rated ambient I haven't looked into that much (i.e., comparing rated heating capacity to rated cooling capacity of real HPs).

    N1 , \field DX Heating Coil Sizing Ratio
         \type real
         \default 1.0
         \minimum> 0
         \note Used to adjust heat pump heating capacity with respect to DX cooling capacity
         \note used only for heat pump configurations (i.e., a DX cooling and DX heating coil is used).

There are places in UnitarySystem where DXCoolCap is set, but the coil model needs to use that global. And for separate UnitarySystems that can be tricky to set. I recall having a hard time with that when UnitarySystem was first added. I suspect that got messed up somehow. If you step through you should see something like this, and then the coil model should also use this variable to set heating capacity. I'm pretty sure the heating capacity multiplier is applied in HeatingCapacitySizing. I don't think this coil model uses the sizer functions but could be wrong on that. If you are close enough on your fixes here I could take a look. I probably need to do that anyway just to follow the flow of code (kinda like what you have already been doing in this branch).

    CoolCapAtPeak = sizerCoolingCapacity.size(state, TempSize, errorsFound);
    state.dataSize->DXCoolCap = CoolCapAtPeak;

**Comment by rraustad** [comment]
And I have always wondered if there are 2 UnitarySystem objects if this really is a HP, so just throwing that out there.

**Comment by mjwitte** [comment]
Added some more HP sizing changes (group effort with @rraustad ). There are some improvements with the defect files, but some unexpected diffs in cooling coil sizes and some unit test failures, but pushing this up anyway for now.

**Comment by mjwitte** [comment]
The companion heat pump coil sizing has gotten messy here, so splitting this into 2 PRs. 
See #9850 for setpoint control portion of this.

**Comment by Myoldmopar** [comment]
Closing the PR but keeping the branch per @mjwitte

**Pull request closed without merging**
