### PR TITLE
Correction of Some Problems in the ChillerHeater Model

### LINKED ISSUE #10065: CentralHeatPumpSystem / ChillerHeater Misbehavior
Issue overview
--------------
The ChillerHeater system in the latest versions seem to have some issue while in heating or simulataneous htg/clg mode. I read through couple of threads on unmet hours and Github but did not find any resolution for those. After noticing the misconduct in my detailed complex model, I just carried out the simulation for the example file in EnergyPlus 'CentralChillerHeaterSystem_Simultaneous_Cooling_Heating' and noticed similar misbehavior. The issue I notice is whenever it is running in mode '2 (Heating Only)' the electricity consumption is too high, i.e. it kind of runs at full capacity even at low loads. The EIR as fuct of PRL in the output shows always ~0.99 regardless of the load on that module. Thus the electricity consumption is too high for even small loads. This issue can be more easily spotted if system timestep is made same as zone timestep so that there is no averaging due to timestep difference. I saw similar issue reported at
https://unmethours.com/question/45860/central-heat-pump-heating-mode-power-input-is-constant/
Also, in mode '3(simultaneous)' for many hours it does not report any electricity in either heating or cooling, i.e. zero electric consumption but still meeting load. That especially happens when the PLR is <0.85 (never at PLR 1). This issue is more pronounced in larger model but still there in example file. I saw similar issue was reported https://unmethours.com/question/35582/centralheatpump-not-always-recording-electricity-consumption/
Attached some graphs to show the issue.
Is there any aspect that I am missing or is it still a pending issue?
Thanks in advance!

### Details
Some additional details for this issue (if relevant):
Windows 10
Found in both v9.6 and v22 of EnergyPlus
[ - Unmethours link or helpdesk ticket number](https://unmethours.com/question/35582/centralheatpump-not-always-recording-electricity-consumption/)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #10065 and #7838 
 - Changes were made to the ChillerHeater model to correct some issues that users noted.  First, when in heating mode or heating dominant mode, the evaporator heat flow and compressor power consumption were always fixed at maximum PLR and thus the evaporator and compressor sum would be higher than the condenser heat flow.  This was traced back to a bug in the algorithm for when the ChillerHeater was in that mode where when the condenser heat transfer was reduced the evaporator heat transfer and compressor power were never reduced accordingly.  This has been corrected.  Second, when there were cases where when in simultaneous heating and cooling mode that zero electric consumption from the compressor was being reported despite there being heat transfer at both the evaporator and condenser.  This was traced back to a problem in a key logic decision in the ChillerHeater code that caused the compressor energy to be left at zero and the condenser to not be simulated when in heat recovery mode when heating was dominant.  These issues along with a few other improvements in some parts of the algorithm and making the code much easier to read were made and 5 new unit tests were added to exercise new subroutines that were added as part of the code improvements.  Differences in the output were noted only for the two files that have ChillerHeaters in the file and this was expected because of the fixes to the problems noted above.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte Ok, this is a significant improvement over what we had before.  I think that the bugs noted by the users previously have been fixed now.  Not saying that this model is without problems but this should be a good step forward.  Let me know if you have any questions or concerns.

**Comment by RKStrand** [comment]
Graphs showing fix of evaporator/compressor always at full power when they should not be (this is for control mode 2--heating only):

image

image

**Review by Myoldmopar — APPROVED** [review]
This looks fine to me.  Good testing and description of the issue and changes.  And good improvement just for a few dozen lines of code.  I'm happy with this.

**Comment by Myoldmopar** [comment]
And CI has just the expected diffs in two files, otherwise clean.  I'm inclined to merge, anyone have any issues here?

**Comment by rraustad** [comment]
No issues. It looks much better than before.

**Comment by Myoldmopar** [comment]
Great, this is clean and ready!  Thanks @RKStrand and @rraustad

**Pull request merged**
