### PR TITLE
83782874 lbnl thermostat offset fault

### PR DESCRIPTION
**Pull request by rongpengzhang**
##Fault Thermostat Offset
(1) IDD files updated
(2) 2 cc files and 1 hh file updated
(3) 1 new IDF example file created

##Fault Humidistat Offset
(1) IDD files updated
(2) 2 cc files and 1 hh file updated
(3) 1 new IDF example file created

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@rongpengzhang This looks like some pretty minimal changes, which is good.  The new example files need to be added to the testfiles/CMakeLists.txt file so they are included in integration tests.  In addition, you'll have to concoct some unit tests on the new source.  I won't have much time trying to get in pull requests that have been open for much longer than this, but take a look at the other unit test files (in tst/EnergyPlus/unit/) and see if you can make some up.

**Comment by rongpengzhang** [comment]
@Myoldmopar 

# I have added the new example files into the testfiles/CMakeLists.txt file.
# Maybe we don't need a unit test here, since the key codes are embedded into existing methods instead of newly developed ones. Also, I have conducted many local tests.
# Tianzhen suggests to use more realistic example models (e.g. RefBldgMediumOffice) to demonstrate the application of fault models, rather than the 5ZoneAirCooled.idf I chose before. I have done that, and plan to upload the commit after Wednesday when CI is not that busy.

Please let me know if you have any comments.

**Comment by rongpengzhang** [comment]
@Myoldmopar What you just merged into develop is the old commit. I haven't push the most up-to-date commit (CMakeLists.txt & new example files) yet, since you suggested the team to do that after Wednesday. 

Should I push them now, instead of after Wednesday?

**Comment by Myoldmopar** [comment]
Push now, and open a new pull request and we'll slide it in after CI gets a
pass at it.

**Comment by rongpengzhang** [comment]
@Myoldmopar I pushed them here: 83782874 lbnl thermostat offset fault #4768

**Pull request merged**
