### PR TITLE
Fix a typo: temrinal -> terminal

### PR DESCRIPTION
**Pull request by felixonmars**
## Pull request overview

This is a trivial typo fix.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 23 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@felixonmars Could you send me an email at: edwin dot lee at nrel dot gov?  I'd like to chat with you about this.  Thanks!

**Comment by nrel-bot-3** [comment]
@felixonmars @lgentile it has been 15 days since this pull request was last updated.

**Pull request merged**
