### PR TITLE
Update indoor living wall sensible heat gain calculation

### PR DESCRIPTION
**Pull request by LipingWang**
Pull request overview
---------------------
This pull request updates the indoor living wall sensible heat gain calculation. In previous calculation, energy required for plants' evapotranspiration went to living wall surface first. This can create sudden drop of living wall surface temperature or substaintial radiation exchange between living wall and surrounding surfaces. In the updated calculation method, energy required for plants' evapotranspiration is first decomposed into sensible and latent to zone air heat balance and affect indoor living walls surface temperature through heat convection through surface heat balance. In additon, an example file with VAV system for the indoor living wall was uploaded to replace the example with an ideal load system. There is a update describing the output variable `Indoor Living Wall Sensible Heat Gain Rate` for input-output reference manual for indoor living wall.  

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Is this a totally separate PR from the other one?  We are right at the end of the release cycle and can't keep taking more PRs, so I'm not sure if this will go in.

**Comment by Myoldmopar** [comment]
Lots of conflicts, I'm not going to worry about this for now, pushing to later release.  If someone is so inclined, they can deal with the conflicts and clean it all up and push it back up.

**Comment by mjwitte** [comment]
@LipingWang @Myoldmopar I've fixed the conflicts, added engineering ref changes, and cleaned up the example file.

However, I'm not sure the new example file should stay. "Time Setpoint Not Met During Occupied Cooling" is 162 hrs in July, and 1821 hrs for an annual simulation. It also has many max iteration warnings. It's probably best to revert back to the ideal loads example file that's already in develop.

**Comment by LipingWang** [comment]
> n annual simulation. It also has many max iteration warnings. It's probably best to revert back to the ideal loads example file that's already in develop.

@mjwitte Thank you very much for fixing all the conflicts! Agreed. Let's keep the ideal load example file.

**Comment by mjwitte** [comment]
@Myoldmopar I've reverted the testfile, ran unit tests and regressions locally. Only diffs are for IndoorLivingWall, as expected due to the code changes.

**Comment by Myoldmopar** [comment]
Thank you @mjwitte.  I am counting on the build and test to run fine until it tries to report regressions, and then fail.  That won't bother me (much) when I see the red failure :)

**Comment by Myoldmopar** [comment]
Everything looks as expected.  Merging this.  Thanks @mjwitte for wrapping this up.  And thanks @LipingWang for the contribution.

**Comment by LipingWang** [comment]
> @Myoldmopar I've reverted the testfile, ran unit tests and regressions locally. Only diffs are for IndoorLivingWall, as expected due to the code changes.

Thank you very much, @mjwitte

**Comment by LipingWang** [comment]
> Everything looks as expected. Merging this. Thanks @mjwitte for wrapping this up. And thanks @LipingWang for the contribution.

Thanks so much, @Myoldmopar

**Pull request merged**
