### PR TITLE
RunPeriod bug fixes

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
Initial set of bug fixes on the RunPeriod changes for 9.0. This addresses #6928 and #6933 as well as a few others. More fixes are still in the works.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by mjwitte** [comment]
@jasondegraw @JasonGlazer Transition is failing on RefBldgStripMallNew2004_Chicago.idf (and many others), because Number of Times to Repeat = 1.0000 which fails the list directed Read statement which is expecting an integer. Working on fix, adding ProcessNumber() protection for all of the incoming numeric fields.

**Comment by mjwitte** [comment]
@jasondegraw @JasonGlazer @Myoldmopar Transition fixes pushed. Beat on it - try to break it.

**Comment by mjwitte** [comment]
@jasondegraw The RunPeriod changes here are ok. I'll wait to merge this so you can review the transition changes.

**Comment by jasondegraw** [comment]
@mjwitte It looks good to me. We probably should have been doing those checks before.

**Pull request merged**
