### PR TITLE
Missing commas in write statements fixed

### PR DESCRIPTION
**Pull request by DeadParrot**
Addresses #5349 
This fixes single comma entries in write statements that were omitted during conversion to C++ due to a tokenizer bug.

Thanks to @JasonGlazer for catching this!

### CODE REVIEW

**Comment by Myoldmopar** [comment]
So, I'm inclined to merge this in because it is correct.  But while I am here, @mjwitte, wtf is [this](https://github.com/NREL/EnergyPlus/pull/5350/files#diff-7bc01d3a27d80f07d31154cd65f3b99dR2513)?  Is it actually reachable in E+ code?  Or was it just in there for testing?  I may end up doing some pruning, but of course that would grow beyond the scope of this PR.  I just want to take a moment to discuss :smile:.

**Comment by Myoldmopar** [comment]
Hmm, @mjwitte, this link works: https://github.com/NREL/EnergyPlus/blob/74c0c9990aa231931c449c70a46a4bc5fbaa2acb/src/EnergyPlus/HVACControllers.cc#L2513

**Comment by mjwitte** [comment]
Not sure about the statistics.HVACControllers.csv - looks like it gets activated with an environment flag.  I never realized it was in there.  Not sure if it's worth keeping or not.

**Comment by Myoldmopar** [comment]
OK, created an issue to track the statistics file (#5354).  Will merge this now.  

Thanks for the quick cleanup on aisle 5 here, @DeadParrot.

**Pull request merged**
