### PR TITLE
WaterUse Plant Component Refactor

### PR DESCRIPTION
**Pull request by YanfeiNREL**
Pull request overview
---------------------
 - Refactoring for WaterUse:Equipment.cc

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Label the PR with at least one of: Refactoring

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] CI status: all green or justified

### CODE REVIEW

**Comment by YanfeiNREL** [comment]
I finally finished this one(also the first one refactoring) by using oop style. Thanks a lot for helps from Matt. I think it is ready for review.

**Comment by YanfeiNREL** [comment]
@Myoldmopar This pull request is ready for your review. Please let me know if you have any comments.

**Comment by mitchute** [comment]
This looks like it's ready. The table and other diffs are due to fields being reordered. There are small math diffs on one file but all of the others look good, so I'm not expecting any issues with it. Let me know if I need to take another look, though.

**Comment by Myoldmopar** [comment]
CI was reluctant to build that last commit so I pulled develop in one more time and we'll see.

**Comment by Myoldmopar** [comment]
EIO diffs are incredibly small warmup convergence changes, a couple small math diffs, showing values in the decimal values of joules.  Otherwise just reorder issues.  This is good to go.  Thanks @mitchute and @YanfeiNREL.

**Pull request merged**
