### PR TITLE
Build time investigation 2022

### PR DESCRIPTION
**Pull request by lefticus**
Pull request overview
---------------------

The purpose of this PR is to decrease compile times. Three approaches were used

* Modify PCH to add new files which have grown in impact
* Split out the `_json` user defined literals (UDLs) from json.hpp.
  This has a potentially large impact because the user defined literals force the instantiation of the entire JSON parser code, and json.hpp is included by nearly ever EnergyPlus file. By splitting up this part of json.hpp we are avoiding expensive template instantiations
* Use `extern template` to delay instantiation of expensive IOFiles.hh `format` templates.
  The `extern template` tells the compiler "don't bother worrying about this template function, someone else will do that for you." Then we explicitly instantiate the most common `format` template functions in IOFiles.cc

### CODE REVIEW

**Comment by lefticus** [comment]
@Myoldmopar can you verify on your side if you are seeing performance improvements like I am? I'm seeing at least 20% faster with debug builds compared to develop branch.

**Comment by mitchute** [comment]
Down 11.5% over here on Mac for a release build. FWIW.

**Comment by Myoldmopar** [comment]
I'm seeing about a 7% build time reduction on debug builds on Linux, but that's also building with 20 threads.  Regardless, with your build time improvement, Matt seeing a good improvement on Mac, and me seeing at least some improvement on Linux, I'd say this is a good step.  There are some Clang Format issues that I'm happy to fix up (or you can fix locally with `./scripts/dev/apply_formatting.sh .` from the repo root if you want), as well as one build warning about adding `inline` to a declaration.  Are you planning additional work here?  If not I'm happy to clean those little things and get this ready for merge.  If you are planning more I'll step aside for now.

**Comment by mjwitte** [comment]
On Windows laptop (Visual Studio 2019), debug rebuild, develop 5:45, this branch 6:16, hmm. Will try again on desktop.

**Comment by lefticus** [comment]
@Myoldmopar I'll deal with any remaining issues.

@mjwitte that's unfortunate. I might have to see which change caused that regression once you report back.

**Comment by mjwitte** [comment]
Rebuilt again on the same machine and this time it completed in 5:32.

**Comment by mjwitte** [comment]
Now with the windows desktop, VS2019, times vary a bit, but both branches are essentially the same build time.

**Comment by rraustad** [comment]
@lefticus is there an explaination as to why different platforms respond differently to these changes to improve build times?

**Comment by lefticus** [comment]
> @lefticus is there an explaination as to why different platforms respond differently to these changes to improve build times?

Most of the changes are pretty mundane, just reducing template code and increasing the PCH coverage.

* It's possible that more files in the PCH could have an adverse affect on some platforms, but unlikely I think?
* It's a bit of an experiment for me where I used `extern template` for the first time to reduce template instantiations associated with the `format` code. It's possible that some compilers cannot make as good use out of the `extern template` technique?

**Comment by lefticus** [comment]
I just did a round of clean builds to try and determine the gains I'm seeing on my side (Ubuntu 18.04, GCC 7.5.0, -j10, Debug, full build including tests, PCH enabled).

 * develop: 19:15
 * PCH changes: 18:05
 * PCH + `extern template`:  17:35

This represents all of the current low-hanging fruit I see in build time impact, in the current development

**Comment by Myoldmopar** [comment]
@mbadams5 this looks like a good step to help our build times on Linux and Mac at least.  Do you have any thoughts before this merges?

**Comment by Myoldmopar** [comment]
This is great.  The updates to the PCH are fine, it may be helpful to understand when we should consider adding to that ourselves.  The extern template work makes sense.  Splitting the literals portion of nlohmann is fine.  Build time is improved or at worst unaffected on Windows, so I'm merging this in.  We may go into the next round of low-hanging fruit at some point, but this is good for now.  Thanks @lefticus.

**Pull request merged**
