### PR TITLE
Fixed GitHub #4648 which was a crash if no Zone:EquipmentConnection was used with refrigerated case object

### PR DESCRIPTION
**Pull request by JasonGlazer**
An error message covering the case already existed but the crash was preventing a clean exit from EnergyPlus so added some shield if blocks for each instance that caused crash.

### CODE REVIEW

**Comment by mjwitte** [comment]
@JasonGlazer Does the defect file actually produce reasonable results if refrigeration equipment is in a zone without a ZoneHVAC:EquipmentConnections object?  i.e.  Does the refrigeration equipment have an impact on the zone?

**Comment by JasonGlazer** [comment]
It never gets to the simulation and does a fatal error.

**Comment by mjwitte** [comment]
Fixes #4648

**Comment by JasonGlazer** [comment]
@Myoldmopar I pointed this and the pivotal ticket to you to verify but feel free to point it to someone else.

**Comment by jasondegraw** [comment]
@JasonGlazer I've made one small change to add a deallocate in your unit test. I'll hold off pushing that until tomorrow to keep the CI machines working on new features, but I expect we can merge this tomorrow.

**Comment by JasonGlazer** [comment]
Thanks @jasondegraw, I haven't internalized the need to deallocate yet. I am working on it.

**Comment by jasondegraw** [comment]
@JasonGlazer No problem. Deallocation is pretty much all I added to the other two tickets you assigned to me as well, so those should be ready to go once the CI situation improves.

**Pull request merged**
