### PR TITLE
Add new example file for VAV Box Minimum Air Flow turndown schedule use

### LINKED ISSUE #7815: Example file for VAV Box Minimum Air Flow turndown schedule use
Issue overview
--------------
Add example file for VAV Box Minimum Air Flow turndown schedule use demonstration. This is not defect.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #7815
 - Adds new example for Example file to demonstrate the use of Minimum Air Flow turndown schedule use in VAV box air terminal

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Nigusse** [comment]
See below plots showing zone air temperature and supply air flow rates at the VAV Box Air Terminal Outlet Node with and without Minimum Air Flow Turndown Schedule. The second plot (blue line) shows the minimum air flow was adjusted below the the design fixed minimum. 

VAVBoxMinAirFlowTurnDownSch

**Comment by Nigusse** [comment]
This pull request adds new example file and is ready for review.

**Comment by nrel-bot-2** [comment]
@Nigusse it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Built this branch and ran the new example file.  Error file is clean, results are fine.  Good to go.  Merging.

**Pull request merged**
