### PR TITLE
ObjexxFCL 4.3 Upgrade

### PR DESCRIPTION
**Pull request by DeadParrot**
This updates ObjexxFCL to version 4.3, which has some minor refinements:
* Visual C++ /W4 warning level compatibility
* Undefined sanitizer compatibility (#6897)
* Multithreading support _via_ defining OBJEXXFCL_THREADS (@kbenne)
* Stream wrapper protected cin/cout/cerr handling (#6885)

No EnergyPlus code changes were made and no solution changes are expected.

**Update** This appears to incur a surprising performance penalty on the GCC 4.8 Ubuntu platform. My testing at the loop and application levels did not show this. Investigating should:
* See if slowdown is reproduced on other platforms with newer (better optimizing) compilers
* See if profiling can identify some key loops where linear indexing can recover the performance
* If a penalty remains team must decide if they prefer speed or making the undefined sanitizer happy

I cannot do this work for a while so let's put this PR on hold.

### CODE REVIEW

**Comment by mjwitte** [comment]
Re-running the failed linux tests, may show some diffs due to recent change in develop.

**Comment by mjwitte** [comment]
@DeadParrot This is showing a signficant [performance](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-3282e0eab840b406eb3d7da2434682a98ff4c6b6-x86_64-Linux-Ubuntu-14.04-gcc-4.8.html) decline.

**Comment by DeadParrot** [comment]
@mjwitte A 6% slowdown is very unlikely for the Array change but I don't run an ancient compiler like GCC 4.8 (why are we doing performance runs on such an old compiler?). And if we insist on being undefined sanitizer clean this change is needed.

I'll do a merge+submit tonight and we'll see what the failures and performance look like after that. This may be more related to the many new commits than anything in ObjexxFCL.

**Comment by mjwitte** [comment]
@DeadParrot Still showing a 6.6% slowdown. Use any of the [active performance test files](https://github.com/NREL/EnergyPlus/blob/develop/performance_tests/CMakeLists.txt) to confirm locally. 15zonePSZ.idf should work.
@Myoldmopar Would you be ok with moving the inactive performance test idfs to an Inactive subfolder ?

**Comment by DeadParrot** [comment]
@mjwitte Please see update that was added to the summary.

**Comment by Myoldmopar** [comment]
> @Myoldmopar Would you be ok with moving the inactive performance test idfs to an Inactive subfolder ?

Fine with me, there should be updates to the performance test suite in the coming months.

**Comment by mjwitte** [comment]
With this on hold, does that block #6885?

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@DeadParrot after we released 9.0, we overhauled our Linux CI box and got Ubuntu 18.04 with GCC 7.3 set up and running.  We now have that setup in our develop branch and we are starting to pull that into the other open branches.  I did that to your ObjexxFCL 4.3 branch here, hoping to see a performance gain, but it is still showing a performance degradation in this branch compared to develop.  Now that we are seeing this on a more up-to-date compiler toolchain, could you provide some commentary or investigate?  It would be great to get this merged, but we'll need to understand/address the performance implications of doing so.

**Comment by Myoldmopar** [comment]
(https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-282e421b7a41c08281df1ebb290ce0fe70f23947-x86_64-Linux-Ubuntu-18.04-gcc-7.3.html)

**Comment by DeadParrot** [comment]
@Myoldmopar thanks for testing this. The performance hit is surprising -- I got ~1% in an array-heavy application. I don't see a way to get the pointer offset speedup without using technically undefined behavior that triggers undefined sanitizer warnings. My preference (and I think that of @kbenne) would be to eliminate undefined behavior and then use linear indexing in hot spots to recover the performance. I don't really want to further fork the ObjexxFCL into "fast" and "proper" versions or to only enable the offset pointer hack in non-debug builds.

The way forward is your call. Some profiling to see where the performance is going would be a good idea. And I can review linear indexing transformations with whoever does the tuning.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DeadParrot @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Since this PR is on hold, I'm going to close it but we'll leave the branch in place so we can open it back up later.

**Comment by DeadParrot** [comment]
@Myoldmopar I have a new ObjexxFCL 4.3 that preserves the original faster lookups and a compile-time macro to enable the (slower) undefined sanitizer clean code. This update also has some C++11 modernizations. I can provide it upon request.

**Pull request closed without merging**
