### PR TITLE
Water Thermal Tanks Plant Component Refactor

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
Refactor water thermal tanks to use plant component.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
Finally ready here. Some small math diffs that are intermittent and big table diffs that are just due to reordered fields. An example table excerpt from VSHeatPumpWaterHeater is below.

Baseline branch:
image

Mod branch:
image

Looks like we're ready, but let me know if there are other issues we need to look at.

**Comment by Myoldmopar** [comment]
A monster refactor, @mitchute, thanks.  I'll take a look at the diffs before this goes in since there are so many, but I imagine it's likely ready too.

**Comment by mitchute** [comment]
# Results Summary

## HeatPumpWaterHeaterStratified
eplusout.csv diff summary: The output fields```PLANTHEATPUMPWATERHEATER:Water Heater Off Cycle Ancillary Electric Power [W](Hourly)``` and ```ZONE4BHEATPUMPWATERHEATER:Water Heater Off Cycle Ancillary Electric Power [W](Hourly)``` had a trailing space which were removed during this work. These fields are not compared by the CI but they are plotted below:

Var_0
Var_1

EIO diffs are due to some differences in the tank nodes. The tables for these are shown below. It looks like nodes 51-60 swapped places with nodes 61-70. @Myoldmopar do you think this warrants further investigations?

**develop**
Screen Shot 2019-12-20 at 3 35 04 PM

**mod branch**
Screen Shot 2019-12-20 at 3 36 14 PM

mdd/mtd/rdd diffs are due to fields being reordered.

Besides these, the rest of the results look identical to the baseline. A few samples are plotted below.

Var_30
Var_41

## HeatRecoveryElectricChiller
csv diff summary: again a few fields are not being compared due to string differences in the variables.

bnd/eio/mdd/mtd/rtd diff are due to fields moving around.

Table diffs are due to tables and fields moving around. 

**develop**
Screen Shot 2019-12-20 at 3 50 13 PM

**mod branch**
Screen Shot 2019-12-20 at 3 50 58 PM

## ShopWithPVandBattery
As usual, fields moving around here.

Some small math diffs, but the source is unknown. They don't look worth investigation though.

Var_27
Var_26
Var_29

Lots more like that. There is one JSON diff, but I'm suspecting it's due to the string diffs noted above. Let me know if that needs further investigation.

**Comment by Myoldmopar** [comment]
When you say string diffs, do you mean the output variable name changed?  If so we need to add it to the Report Variables csv file for transition to pick up.

**Comment by mitchute** [comment]
@Myoldmopar they changed due to trailing whitespace being stripped. This type of change needs to be added to the CSV, too?

**Comment by Myoldmopar** [comment]
Hmm.  No.  It wouldn't make a difference in terms of the final IDF that the transition tool would write out.  Interesting issue though.

**Comment by Myoldmopar** [comment]
Lots of tiny math diffs, lots of table reordering, lots of text reordering, and no big math diffs.  This looks good to go in.  I'm happy to let anyone else look at it this morning but if no one is going to then I'll call this good to merge.

**Pull request merged**
