### PR TITLE
Fix #10665 - HeatPump:AirToWater:FuelFired:Heating was not using Outside air temperatures to evaluate curves

### LINKED ISSUE #10387: The PlantLoop:EIR heat pump power calculation is incorrect
Issue overview
--------------
The equation:

    this->powerUsage =
        (this->loadSideHeatTransfer / this->referenceCOP) * eirModifierFuncPLR * eirModifierFuncTemp * InputPowerMultiplier * this->cyclingRatio;

uses loadSideHeatTransfer which is already multiplied by PLR a few lines up. This means the eirModifierFuncPLR curve output must be near unity to give appropriate results. The EIRfPLR curve typically accounts for a change in power as a function of PLR. Of course, the definition of this curve could be discussed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10665: `HeatPump:AirToWater:FuelFired:Heating` curves not using two independent temperature variables
Issue overview
--------------

Take "Normalized Capacity Function of Temperature Curve Name" for example. The idd and example idf file both suggest that the object supports a bivariate function (i.e., of outdoor air temperature and water temperature). But if you output "Performance Curve Input Variable 1 Value" and "Performance Curve Input Variable 2 Value", the values are the same at each timestep. It appears that perhaps water temperature is being used as both inputs.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/10000s/10665
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #10665 

Using PlantLoopHeatPump_Fuel-Fired.idf , before versus after, plotting the `CAPCURVEFUNCTEMP2`

image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
Now, I change the evaluation variables

image

image

**Comment by shorowit** [comment]
@jmarrec This fixes #10665, not #10387, right?

**Comment by jmarrec** [comment]
> @jmarrec This fixes #10665, not #10387, right?

:man_facepalming: yes, thank you.

**Comment by jmarrec** [comment]
Redone in https://github.com/NREL/EnergyPlus/pull/10682, apologies

**Pull request closed without merging**
