### PR TITLE
#7589 - Add silent install capability to QtIFW installers

### LINKED ISSUE #7589: Restore silent install option
Issue overview
--------------
From one corporate and one university admins:
Is there a silent command line install available for the EnergyPlus-9.2.0-921312fa1d-Windows-x86_64.exe installer? For previous versions we were able to deploy silently via SCCM using /S /D=C:\EnergyPlusV9-2-0 but this latest installer does not appear to have the option available.

We've historically distributed this software with SCCM, using the '/S' switch to install it silently. It appears that this no longer works with 9.2.0. Is there a different switch we can use?

From @jmarrec regarding the new installer software:
you can create stuff that allows silent install on QtIFW, but it requires writing a javascript file (that mimics going to next page etc).

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus v9.2.0
 - Helpdesk ticket number 15290 and 15298

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7589
 - The previous NIST installer on Windows had silent install capability. Wrote a javascript install script for QtIFW that allow silent install and uninstall.
- Tested on:
   * [x] Windows 10
   * [x] macOS 10.14

**The install_script.qs includes a markdown docstring in the header. That I will paste in a a post right below for reading convenience**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
Here's the (current, at time of writing https://github.com/NREL/EnergyPlus/pull/7615/commits/ed7ef1c41d1e37a450530805ce8a53917f9f3d8c) Docstring in the `install_script.qs`

-----

# QtIFW Installer script for EnergyPlus

Allows performing silent installs on all platforms.

## Installation

NOTE: By running a silent install, you agree to the EnergyPlus License Agreement

Usage:

```
# Linux
sudo ./EnergyPlus-9.2.0-0e6e9c08a0-Linux-x86_64.run --verbose --platform minimal --script install_script.qs

# Mac: `--plaftorm minimal` appears to produce a segmentation fault
open EnergyPlus-9.2.0-0e6e9c08a0-Darwin-x86_64.dmg
sudo /Volumes/EnergyPlus-9.2.0-0e6e9c08a0-Darwin-x86_64/EnergyPlus-9.2.0-0e6e9c08a0-Darwin-x86_64.app/Contents/MacOS/EnergyPlus-9.2.0-0e6e9c08a0-Darwin-x86_64 --verbose --script install_script.qs

# Windows: open cmd.exe as admin: `--platform minimal` appears unsupported (but we use gui.setSilent(true) so nothing will pop up)
EnergyPlus-9.2.0-0e6e9c08a0-Windows-x86_64.exe --verbose --script install_script.qs
```

You can also customize the install directory by passing `TargetDir`
If you don't, it defaults to:
* Linux: `/usr/local/EnergyPlus-9-2-0`
* Mac: `/Applications/EnergyPlus-9-2-0`
* Windows: `C:\EnergyPlusV9-2-0`

```
 sudo ./EnergyPlus-9.2.0-0e6e9c08a0-Linux-x86_64.run --verbose --platform minimal --script install_script.qs TargetDir=/usr/local/Eplus
```

By default, all components will be installed.
We also built-in a way to unselect components via the command line by passing
`<ComponentName>=false` (case matters, has to be `false` exactly)

Unix:
```
 sudo ./EnergyPlus-9.2.0-0e6e9c08a0-Linux-x86_64.run --verbose --platform minimal --script install_script.qs Documentation=false ExampleFiles=false WeatherData=false Datasets=false Symlinks=false
```

Windows: Open cmd.exe as admin

```
EnergyPlus-9.2.0-0e6e9c08a0-Windows-x86_64.exe --verbose --script install_script.qs Documentation=false ExampleFiles=false WeatherData=false Datasets=false CreateStartMenu=false RegisterFileType=false
```

On Windows only, if CreateStartMenu is true (default), there is a built-in option `AllUsers=true`
which will in particular create the shortcuts in the All Users start menu (C:\ProgramData\Microsoft\Windows\Start Menu\Programs)
which is useful if you use SCCM (or psexec) to run the commands as you are LOCAL SYSTEM account when you do and these shortcuts won't work for the regular user

```
EnergyPlus-9.2.0-0e6e9c08a0-Windows-x86_64.exe --verbose --script install_script.qs AllUsers=true
```

-------------------------------------------------------------------------------

## Uninstallation

NOTE: You can also pass this same script to the maintenancetool for a silent
complete uninstall

```
# Linux
sudo /usr/local/EnergyPlus-9-2-0/maintenancetool --verbose --plaftorm minimal --script install_script.qs

# Mac: `--platform minimal` appears to produce a segfault right now
sudo /Applications/EnergyPlus-9-2-0/maintenancetool.app/Contents/MacOS/maintenancetool --verbose --script install_script.qs

# Windows: `--platform minimal` appears unsupported at the moment
C:\EnergyPlusV9-2-0\maintenancetool.exe --verbose --script install_script.qs
```

**Comment by jmarrec** [comment]
I had a back and forth conversation with two users that deploy E+ installs using SCCM (one of which is @gtaylor-feduni) and they provided excellent feedback (thanks!) which allowed to ensure that it works for their needs

* An original problem was that the Start Menu Shortcuts were not working when deploying like this, since the current user is the local system admin and not the actual user: these need to be placed in the "All Users" start menu. I originally went with a workaround, but there's actually a built-in QtIFW argument `AllUsers=true` that correctly create shortcuts in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\EnergyPlusV9-2-0`. I tested that I can see them.
    * I also see the `EnergyPlusV-9-2-0` install entry in the `Control Panel\Programs\Programs and Features` and I can uninstall from there
* I added the `gui.setSilent(true)` and now I no longer see any GUI element popping up, which was the case on windows since `--platform minimal` isn't supported (and neither on mac, I opened an issue on the Qt issue tracker [[QTIFW-1471]](https://bugreports.qt.io/browse/QTIFW-1471)

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
So this would be a great one to get in as well, but I am not sure about testing it prior to it merging in.  I don't think either of you @mjwitte or @mitchute can build package, right?  The missing string table issue is still there?  Or maybe that was fixed, I cannot recall.

Anyway, we can just let CI build a package of this and try it out, but unfortunately we can't do that until it merges into our repo, or we replicate this branch in our repo.

Anyone have thoughts/concerns?

**Comment by mjwitte** [comment]
@Myoldmopar I'm attempting to build a package from develop in VS2019 as we speak. I know it fails if there's a space in the path to the build folder, but I think the other bug has been fixed. Will know shortly.

**Comment by Myoldmopar** [comment]
> I know it fails if there's a space in the path to the build folder

We can have this conversation later, but I am curious what error you get in cases with spaces in the build directory path.  At least one of the issues related to spaces in paths was addressed a few weeks back.  Probably not the same issue.

**Comment by mjwitte** [comment]
The no-space package builds successfully here now with VS2019 16.5.0. @jmarrec 
I'll switch to this branch now and build.
Then I'll re-do the space-in-path build and post the errors. As I recall, @jmarrec concluded it was a bug in VS or Qtif that we can't work around.

**Comment by mjwitte** [comment]
@Myoldmopar @jmarrec Here's the output when building a package on VS2019 with a space in the build path. It says it failed, but it does create a working installer exe. 
[PathWithSpaceBuildOutput.txt](https://github.com/NREL/EnergyPlus/files/4375927/PathWithSpaceBuildOutput.txt)
There are a couple of error messages along the way that reference a truncated path "C:\MJW" and then theres a bunch of error messages at the end.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte.  I'm definitely concerned about the EXEC errors.  What is missing in the installer because those were not executed?  Did you try to run the installer/uninstaller in both graphical/silent mode?  That would be very informative if you could.

**Comment by mjwitte** [comment]
I built a package on this branch (with develop merged in) and tried a silent install. It spit out some messages, but didn't install anything. I opened the command window as administrator. 
```
C:\MJWGitNoSpace\EnergyPlus-Review4\Build>EnergyPlus-9.3.0-3ed30e487d-Windows-x86_64.exe --verbose --script install_script.qs CreateStartMenu=false TargetDir=C:\EnergyPlus\EnergyPlus-9-3-0-Test7Silent

C:\MJWGitNoSpace\EnergyPlus-Review4\Build>IFW Version: 3.1.1, built with Qt 5.9.5.
Build date: May 15 2019
Installer Framework SHA1: 8730cb0
[0] Language: en-US
[0] Arguments: EnergyPlus-9.3.0-3ed30e487d-Windows-x86_64.exe, --verbose, --script, install_script.qs, CreateStartMenu=false, TargetDir=C:\EnergyPlus\EnergyPlus-9-3-0-Test7Silent
[6] Operations sanity check succeeded.
[6] Resource tree:
[7]      :/translations
[8]      :/translations/ifw_zh_CN.qm
[8]      :/translations/qt_da.qm
[9]      :/translations/qt_de.qm
[9]      :/translations/qt_en.qm
[10]      :/translations/qt_es.qm
[10]      :/translations/qt_fr.qm
[10]      :/translations/qt_ja.qm
[11]      :/translations/qt_it.qm
[11]      :/translations/qt_pl.qm
[13]      :/translations/qt_ru.qm
[13]      :/translations/ifw_de.qm
[16]      :/translations/ifw_da.qm
[16]      :/translations/ifw_es.qm
[17]      :/translations/ifw_en.qm
[18]      :/translations/ifw_fr.qm
[18]      :/translations/ifw_it.qm
[19]      :/translations/ifw_ja.qm
[19]      :/translations/ifw_pl.qm
[20]      :/translations/ifw_ru.qm
[21]      :/translations/qt_zh_CN.qm
[21]      :/uninstall.png
[22]      :/installer.png
[22]      :/installer.ico
[23]      :/keepinstalled.png
[23]      :/installer.icns
[25]      :/install.png
[25]      :/keepuninstalled.png
[28]      :/metadata
[28]      :/metadata/RegisterFileType
[29]      :/metadata/RegisterFileType/install_registerfiletype.qs
[29]      :/metadata/config
[30]      :/metadata/config/config-internal.ini
[30]      :/metadata/installer-config
[31]      :/metadata/installer-config/ep.ico
[32]      :/metadata/installer-config/ep_nobg_png.png
[32]      :/metadata/installer-config/config.xml
[33]      :/metadata/CopyAndRegisterSystemDLLs
[33]      :/metadata/CopyAndRegisterSystemDLLs/install_win_copydll.qs
[34]      :/metadata/Updates.xml
[34]      :/metadata/Unspecified
[35]      :/metadata/Unspecified/install_operations.qs
[35]      :/metadata/rccprojectl24920.qrc
[38]      :/metadata/CreateStartMenu
[38]      :/metadata/CreateStartMenu/install_win_createstartmenu.qs
[40]      :/metadata/Licenses
[40]      :/metadata/Licenses/LICENSE.txt

C:\MJWGitNoSpace\EnergyPlus-Review4\Build>
```

**Comment by Myoldmopar** [comment]
OK.  This is enough information for me to go on.  Thank you for the effort @mjwitte and @mitchute, but this is too flaky to drop in at the moment.  I think the Linux installer one will go in, but this will not proceed.  Silent installers will make a comeback with 9.4!

**Comment by jmarrec** [comment]
Rebased onto develop for clarity (this was opened in November).

**Comment by jmarrec** [comment]
I've just sucessfully built the package, installed it silently, and uninstalled it silently.

Windows 10. Built with CMake 3.17 and QtIFW 3.2.2

```bash
cd C:\Users\julien\Software\Others\EnergyPlus\build

# Install
.\EnergyPlus-9.3.0-141b2e46e9-Windows-x86_64.exe --verbose --script ..\cmake\qtifw\install_script.qs

# Uninstall
C:\EnergyPlusV9-3-0\maintenancetool.exe --verbose --script ..\cmake\qtifw\install_script.qs
```

**Comment by mjwitte** [comment]
Hmm, what was the full command line for the silent install?

**Comment by jmarrec** [comment]
cf edited comment above: I tried also `.\EnergyPlus-9.3.0-141b2e46e9-Windows-x86_64.exe --verbose --script ..\cmake\qtifw\install_script.qs AllUsers=true` with the same result.

ANd I tried it both in an elevated cmd.exe and a regular one (with the regular one it prompts you to allow elevated operation during the run)

**Comment by mjwitte** [comment]
Ah! `..\cmake\qtifw\install_script.qs`. I didn't understand where the script lived. With that added to the script path, it works now. Need to clarify that in the instructions at the top.

**Comment by mitchute** [comment]
I tested both the silent and GUI install methods today on Windows 10. For all cases, I tested with LINK_WITH_PYTHON=ON, but also tested with and without OpenGL. All cases successfully installed and ran E+ files. I will pull in the latest commits and rebuild another package tonight and test again in the morning just to verify.

**Comment by Myoldmopar** [comment]
Thanks @mitchute !  

@mjwitte it seems like you were also having some good success here.  If you feel like it is running well, merge at will, and we'll kick off another package build on CI to make sure it behaves.

**Comment by mitchute** [comment]
The package built, and the scripted and GUI methods all installed/uninstalled and ran files successfully. 

I guess the only remaining question I have is whether it makes sense to just point users to the most current version of ```install_script.qs``` for when they want to uninstall it, rather than just shipping it with the package? Couldn't this conceivably change between versions, and therefore not uninstall properly?

**Comment by Myoldmopar** [comment]
It would be much better to ship it with the package.  But I don't know if we'll get that done today.  If it could, that would make this complete.  If not, we'll need to make it available for this release and then add it to the package after.

**Comment by Myoldmopar** [comment]
@mjwitte it looked like this was working for you.  If you are happy with this, we can merge this in.  I'd like to close up shop this afternoon, but if you want more time to investigate, just let me know.

**Comment by samuelduchesne** [comment]
Hi @jmarrec, I am installing EnergyPlus as part of a CI build on Travis-CI and thanks to your install script, it is now possible to do a silent install for earlier versions of EnergyPlus. The script works flawlessly on the macOS Build Environment (the Linux Build Environment can still use the simple bash script). The build on Windows, on the other hand, fails with this [error](https://travis-ci.com/github/samuelduchesne/archetypal/jobs/319867938#L350): 
`Operation \"Execute\" with arguments \"C:\\Windows\\SysWOW64\\regsvr32.exe; /s; C:\\Windows\\SysWOW64\\Graph32.ocx\" failed: Execution failed (Unexpected exit code: 3): \"C:\\Windows\\SysWOW64\\regsvr32.exe /s C:\\Windows\\SysWOW64\\Graph32.ocx\"`

Not sure why Graph32.ocx could not be registered. Any ideas?

**Comment by jmarrec** [comment]
@samuelduchesne I'm not familiar with the windows boxes on travis, but they appear to be Windows Servr 1809, which I am not familiar with. The regsvr32 exit code 3 indicates "LoadLibrary failed".

I don't think you should use any installers if the goal is to make E+ available to your travis CI. You should just download the ZIP / Tar.gz, extract that, and potentially make a couple of symlinks or add it to PATH. 

These DLLs are for VB executable mostly, so if you're only trying to use the CLI to run simulations you don't need them.

**Comment by samuelduchesne** [comment]
Never thought a simple zip extract could do it. Do you recommend doing the same for Linux and macOS build environnements?

Samuel

**Comment by jmarrec** [comment]
Yes, you can totally do the same for unix, it is probably easier too.

On linux the .sh script for eg is just a self-extracting tar.gz with a couple of questions and creation of symlinks, cf https://github.com/NREL/EnergyPlus/blob/185e20e71c38982ae12f355ab950587cc20caa7f/cmake/CPack.STGZ_Header.sh.in

**Pull request merged**
