### PR TITLE
Include CurveFitTool.xlsm in all install packages

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
We were adding the IceStorageCurveFitTool but not this one, so this PR adds it to all installer packages.

### CODE REVIEW

**Review by jmarrec — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Looks like you have a unit test failure there @mitchute, could you fix that before this merges?


:smile: 


JK, OK, merging, thanks.

**Comment by EnergyArchmage** [comment]
I would think an excel macro would only be useful for windows

**Comment by Myoldmopar** [comment]
I think Macros run fine on Excel for Mac.  And Libreoffice may even interpret the macros if you open a macro enabled file.

**Comment by bonnema** [comment]
I think office for Mac supports them now.

**Pull request merged**
