### PR TITLE
Update version to 24.2

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
Typical update of version number with accompanying changes.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
EpJSON check failure is unrelated, and that particular check on Mac has already been disabled on develop for right now.  I won't waste CI clock cycles on pulling in that one line change from develop though.  If this comes back clean from Decent it is a good indicator that the main pieces are in place to change from 24.1 to 24.2.  @mjwitte sometimes spots something I've missed though...

**Comment by Myoldmopar** [comment]
One test file had an incorrect version number, so I've fixed that locally as well as pulled in develop to eliminate the EpJSON issue.  I will wait to see what Mac says before pushing it up for a clean round.

**Comment by Myoldmopar** [comment]
Excellent, IndoorLivingWall is the only one failing on Mac as well.  Pushing up that fix along with pulled in develop and this should be basically ready pending any additional testing.

**Review by mjwitte — APPROVED** [review]
Built a package and tested transition from 23.2 from EP-Launch, and transition from 9.4 with IDFVersionUpdater. All good.

**Comment by Myoldmopar** [comment]
Awesome, thanks @mjwitte !  On to 24.2!!

**Pull request merged**
