### PR TITLE
Updated ASHRAE Revised Clear Sky "tau" Model with new 2017 option

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses Issue #6864

Pull request overview
---------------------
This fix added new ASHRAE's Revised Clear Sky "TauModel" solar model indicator key choice based on updated coefficients from ASHRAE 2017 Handbook of Fundamentals. User can run ASHRAE's Revised Clear Sky "TauModel" solar model using  taub and taud data from the 2009, 2013, or 2017 ASHRAE HOF. Diffs are not expected for this change. 

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)

### CODE REVIEW

**Comment by Nigusse** [comment]
19 test files shown diffs in regression tests are expected since those test files have "ASHRAETAU" as their solar indicator model.

**Comment by lgu1234** [comment]
@Nigusse I would like to make a suggestion to give users a choice to select different sets of coefficients. In other words, the old coefficients may be kept in some way. For example, we may add a new object to store coefficients. The suggestion may not be for this fix. Instead, it may be a new feature development

**Comment by Nigusse** [comment]
The unit test "PackagedTerminalHP_VSCoils_Sizing" fails but the cause for this unit test failure is not related to this fix. However, the 19 test files that show diffs are caused by the ASHRAETau Model coefficients update and is expected.

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar the ASHRAETau Model coefficients are hard coded. Reproducing previous results is not possible when we change the hard coded coefficients. Is this is a concern? @lgu1234 is suggesting to consider adding the a objects that EnergyPlus can read the coefficients from an object instead of hard coding.

**Comment by mjwitte** [comment]
@lgu1234 @Nigusse @Myoldmopar Not only have the coefficients changed from 2009 to 2013/2017, the user inputs for taub and taud have changed from 2009 to 2013 and again from 2013 to 2017. Given that, users will need the option to select ASHRAETau2009 or ASHRAETau20132017 or something like that. But since ASHRAETau is embedded in many (all?) of the ddy files, we may want to go with ASHRAETau as the 2009 correlation, and ASHRAETau201317 as the new one?  Marking this as IDD change.

**Comment by mjwitte** [comment]
Or maybe just ASHRAETau2017 and forget that 2013 ever happened.

**Comment by Nigusse** [comment]
@mjwitte I support to add ASHRAETau2017 only since the coefficients ab and ad remain the same for 2013 and 2017 HOF versions. But needs to add explanation in the I/O ref documentation that ASHRAETau2017 can be used for 2013 HOF with matching tauB and tauD coefficients.

**Comment by Nigusse** [comment]
I will start working on this branch to accommodate these changes. So, I will add new key choice ASHRAETau2017.

**Comment by Nigusse** [comment]
Now the DesignDay Sizing object model allows to select solar model indicator ASHRAETau or ASHRAETau2017 keys. ASHRAETau is used with the 2009 ASHRAE HOF and ASHRAETau can be used with either the 2013 or 2017 ASHRAE HOF data. No diffs are expected.

**Comment by Nigusse** [comment]
Also updated I/O and Eng reference documents and Idd as needed.

**Review by mjwitte — APPROVED** [review]
Code, idd, and doc changes all look OK.  Made a set of test files using 2009, 2013, and 2017 options for Atlanta, July 21 to reproduce the example results in the handbooks. Solar noon and 3pm EDT all agree.

**Pull request merged**
