### PR TITLE
Correct fan heat accounting for multiple air loops

### LINKED ISSUE #8176: Multiple air loops are using the wrong fan to calculate fan heat during sizing
Issue overview
--------------
Testing of example files show that the wrong fan index is used to calculate fan heat during sizing. An example of the problem code shows the issue. Once the DataFanIndex is set by the first air loop, it is not reset to the correct value for the next air loop.

    if (DataFanIndex == -1) {
        if (PrimaryAirSystem(CurSysNum).supFanModelTypeEnum == DataAirSystems::structArrayLegacyFanModels) {
            DataFanEnumType = DataAirSystems::structArrayLegacyFanModels;
            DataFanIndex = PrimaryAirSystem(CurSysNum).SupFanNum;
        } else if (PrimaryAirSystem(CurSysNum).supFanModelTypeEnum == DataAirSystems::objectVectorOOFanSystemModel) {
            DataFanEnumType = DataAirSystems::objectVectorOOFanSystemModel;
            DataFanIndex = PrimaryAirSystem(CurSysNum).supFanVecIndex;
        }
    }

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #8176.
 - Correct over protected fan heat calculation during sizing. Only affects multiple air loops with coil on branch configuration and impacts water cooling coil inlet or outlet temperature used during sizing. Small differences in coil sizing were noted after the correction. Parent objects on main branch (e.g., UnitarySystem or Furnace) are not affected. Zone equipment are not affected.

Example file ASHRAE9012016_Hospital_Denver shows the problem.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] ~Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair~
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] ~If any defect files are updated to a more recent version, upload new versions here or on DevSupport~
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
This is somewhat of a hot fix and is required to move forward with the Autosizing Library. The Autosizing work will eliminate this code. This change is only needed to minimize diffs in the Autosizing branch.

**Comment by rraustad** [comment]
There were no eio diff's in example file ASHRAE9012016_Hospital_Denver when comparing this branch and the Autosizing Library branch.

**Comment by rraustad** [comment]
A typical difference is shown below and is expected with this change. The coil outlet temperature has changed slightly since the wrong fan was used to calculate fan heat.

image

**Comment by Myoldmopar** [comment]
I'm building this locally to verify the unit test is fine since it failed in one build above.  I don't have any problem with your change here and I get that it is temporary, so I anticipate this will drop in this afternoon.  Thanks for the quick fix @rraustad.

**Comment by rraustad** [comment]
Here is another test to see if this corrects the problem. I ran develop and this branch with the defect file (example file). Then I changed the ER fan to produce 0 fan heat and ran them again.

    Fan:VariableVolume,
      VAV_ER_Fan,              !- Name
      0.0,                 !- Pressure Rise {Pa}
      0.000000001,                    !- Motor Efficiency
      0.0,                     !- Motor In Airstream Fraction

In develop, the coil outlet temp didn't change, because it's looking at the wrong fan. In this branch, when fan heat is 0 the coil outlet temp is equal to the design supply air temp.

    Sizing:System,
      VAV_ER,                  !- AirLoop Name
      12.8,                    !- Central Cooling Design Supply Air Temperature {C}


Develop then develop with 0 fan heat for ER fan:

    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 10.49906
    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 10.49906

This branch then this branch with 0 fan heat for ER fan:

    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 10.58765
    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 12.80000

Debugger shows ER fan heat is 2.21235 and fan power is 12069.3.

fanDeltaT = FanCoolLoad / (CpAir * StdRhoAir * DataAirFlowUsedForSizing);
2.21235 = 12069.3 / (1018.636 * 0.965082 * 5.549358)

so 12.8 - 2.21235 = 10.58765 is a match

**Comment by rraustad** [comment]
I also thought this was an indicator of a problem, yet less likely to be noticed. The difference in these numbers is the air loop air flow rate and differences in the fan inputs. Yet develop shows they are roughly the same.

Develop branch:

    Component Sizing Information, Coil:Cooling:Water, VAV_1_COOLC, Design Size Design Outlet Air Temperature [C], 10.49573
    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 10.49906
    Component Sizing Information, Coil:Cooling:Water, VAV_OR_COOLC, Design Size Design Outlet Air Temperature [C], 10.49655
    Component Sizing Information, Coil:Cooling:Water, VAV_ICU_COOLC, Design Size Design Outlet Air Temperature [C], 10.49580
    Component Sizing Information, Coil:Cooling:Water, VAV_PATRMS_COOLC, Design Size Design Outlet Air Temperature [C], 10.49570
    Component Sizing Information, Coil:Cooling:Water, VAV_2_COOLC, Design Size Design Outlet Air Temperature [C], 10.49635
    Component Sizing Information, Coil:Cooling:Water, VAV_LABS_COOLC, Design Size Design Outlet Air Temperature [C], 10.49654
    Component Sizing Information, Coil:Cooling:Water, CAV_KITCHEN_COOLC, Design Size Design Outlet Air Temperature [C], 10.49688

This branch:

    Component Sizing Information, Coil:Cooling:Water, VAV_1_COOLC, Design Size Design Outlet Air Temperature [C], 10.49573
    Component Sizing Information, Coil:Cooling:Water, VAV_ER_COOLC, Design Size Design Outlet Air Temperature [C], 10.58765
    Component Sizing Information, Coil:Cooling:Water, VAV_OR_COOLC, Design Size Design Outlet Air Temperature [C], 10.61113
    Component Sizing Information, Coil:Cooling:Water, VAV_ICU_COOLC, Design Size Design Outlet Air Temperature [C], 10.47365
    Component Sizing Information, Coil:Cooling:Water, VAV_PATRMS_COOLC, Design Size Design Outlet Air Temperature [C], 10.49570
    Component Sizing Information, Coil:Cooling:Water, VAV_2_COOLC, Design Size Design Outlet Air Temperature [C], 10.51808
    Component Sizing Information, Coil:Cooling:Water, VAV_LABS_COOLC, Design Size Design Outlet Air Temperature [C], 10.42620
    Component Sizing Information, Coil:Cooling:Water, CAV_KITCHEN_COOLC, Design Size Design Outlet Air Temperature [C], 11.11187

**Comment by rraustad** [comment]
@Myoldmopar what is the status of this PR ?

**Comment by rraustad** [comment]
@Myoldmopar @mjwitte I will merge this PR by end of day, pending comments of course.

**Comment by rraustad** [comment]
image

**Pull request merged**
