### PR TITLE
Reorder OAMixer MixMassFlowRate calc for better precision to avoid invalid unbalanced flow warnings

### PR DESCRIPTION
**Pull request by mjwitte**
Addresses #4293 
Order of calculations in OA mixer caused fancoil mixed air flow rate (and then fan coil outlet flow rate) to be slightly less than the fan coil inlet (return) flow rate. This resulted in false unbalanced exhaust flow warnings.  The OA mixer mixed air mass flow rate calculation was reordered to improve precision.

### CODE REVIEW

**Comment by mjwitte** [comment]
Kind of expected, but surprised by how many, test files with small diffs.  And HospitalBaseline and HospitalBaselineReheatReportEMS show a couple of additional max iteration warnings.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Sorry, just now getting on to looking at this.  So the unbalanced flow warnings are really so sensitive that a change by an order of magnitude like the tail end of a floating point variable can fix the bug?  I'm not surprised that the changes causes diffs.  Epsilon changes like this just means small state differences propagating through time.  But I am surprised that this fixed the bug.

**Comment by mjwitte** [comment]
It's more subtle than that.  The exhaust flow into one of the fancoil units is set by the fancoil, then the OA mixer comes along a calculates the mixed air flow rate which ends up being slightly smaller.  The DOAS air handler is off, so when the zone checks the mass balance, the leaving flow is on the order of e-18 greater than the supply flow entering the zone, which trips the warning.  And I expect the leaving conditions from the OA mixer are slightly off as well.  Bigger picture, the OA mixer should not be dictating the mixed air node mass flow rate, but that's how things are set up at the moment.  I have a unit test locally that doesn't work.  Perhaps a better fix would be to add a smallmassflow tolerance to the unbalance flow warning.

**Comment by Myoldmopar** [comment]
> Perhaps a better fix would be to add a smallmassflow tolerance to the unbalance flow warning.

That's what I was thinking.

**Comment by mjwitte** [comment]
I'll revisit this with that in mind.

**Comment by mjwitte** [comment]
This is Plan A for this fix, pushed up just to save the changes.  Will make a new branch for Plan B.

**Comment by mjwitte** [comment]
Superceded by #5422

**Pull request closed without merging**
