### PR TITLE
Add CO2-based Proportional Demand Controlled Ventilation Based on Design Occupancy

### PR DESCRIPTION
**Pull request by lgu1234**
Add CO2 demand controlled ventilation based on design occupancy.  Addresses #5031

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 Code looks correct to me.  I will test the transition and the new option.  @Myoldmopar Any objection to merging this if my testing finds everything OK?

**Comment by Myoldmopar** [comment]
No problem; I've got my transition changes in there.  Have at it.

**Comment by mjwitte** [comment]
@lgu1234 I ran example file HeatPumpProportionalControl_DCV as-is and with the new ProportionalControlBasedOnDesignOccupancy option.  For the most part the results make sense, but in the afternoon of 7/25, the ProportionalControlBasedOnDesignOccupancy case is increasing the amount of outdoor air as the occupancy goes down.  Why?  Seems like it should be going lower.  Then I tried changing the CO2 setpoint schedule from 900 to 500 and the results are identical.  I'm not understanding how this control should work.

**Comment by lgu1234** [comment]
@mjwitte For the new choice, the amount of OA is calculated based on design level occupancy, independent of occupancy schedule. Therefore, when occupancy is down, the amount of OA should change slightly. When I read Eng. Ref and found a mistake to calculate target indoor CO2 level. When a new choice is applied, the design level should be used for zone occupancy, instead of scheduled occupancy. I am going to commit. Please take a look at it again.

**Comment by mjwitte** [comment]
@lgu1234 My confusion is regarding the target indoor CO2 concentration.  When I change the CO2 setpoint schedule in the contaminant controller, it appears to have no effect on the OA quantities.

**Comment by lgu1234** [comment]
@mjwitte It may be true. When the indoor CO2 concentration equals or greater than max CO2 value, the max OA is used. The max  CO2 value is calculated based on Eq. 3 in the Proportional Control section in the Eng. Ref. Since the min and max CO2 values are very close, and indoor CO2 is greater than the max CO2 value, the maximum OA values is used. That is why you don't any values changed. If you set the set point is slightly larger than 400, you may see OA changed.

**Comment by lgu1234** [comment]
@mjwitte I made a test case by setting occupancy schedule at 1 all times using the same example file. Then, I switch both choices: ProportionalControlBasedonOccupancySchedule and ProportionalControlBasedonDesignOccupancy. Results of both choices are the same. Therefore, the code is doing what is expected.

**Comment by mjwitte** [comment]
@lgu1234 Looks good.  I was changing the wrong schedule before.  Changing the minimum target CO2 does have an effect on the answer.

**Pull request merged**
