### PR TITLE
Fix #8289 segfault when using new window shading control 

### LINKED ISSUE #8289: New Segfault in SolarShading.cc in v940-RC1 (regression from v940-IOFreeze)
Issue overview
--------------

Probably related to #8269 

OpenStudio has an IDF file that's simulated early in the build, called Daylighting_Scool.idf. This was working fine at v9.4.0-IOFreeze and now segfaults. See https://github.com/NREL/OpenStudio/blob/develop/resources/energyplus/Daylighting_School/in.idf

I built E+ v9.4.0-RC1 in Debug mode:

```
(py38)julien@Daylighting_School$ $ep_build/Products/energyplus
EnergyPlus Starting
EnergyPlus, Version 9.4.0-5a40ebd3b9, YMD=2020.09.21 12:02
Initializing Response Factors
Calculating CTFs for "INTERIORFURNISHINGS"
Calculating CTFs for "IEAD R-15 CI ROOF"
Calculating CTFs for "INTERIOR WALL"
Calculating CTFs for "MASS R-7.6 CI EXTERIOR WALL"
Calculating CTFs for "UNHEATED 8IN EXTERIOR SLAB W/ CARPET"
Calculating CTFs for "LIGHT_SHELF_CONSTRUCTION"
Initializing Window Optical Properties
Initializing Light Shelf Daylighting Devices
Initializing Solar Calculations
Allocate Solar Module Arrays
Initializing Zone and Enclosure Report Variables
Initializing Surface (Shading) Report Variables
Determining Shadowing Combinations
Computing Window Shade Absorption Factors
energyplus: /home/julien/Software/Others/EnergyPlus/third_party/ObjexxFCL/src/ObjexxFCL/Array1.hh:1172: T& ObjexxFCL::Array1< <template-parameter-1-1> >::operator()(int) [with T = EnergyPlus::Construction::ConstructionProps]: Assertion `contains( i )' failed.
Aborted (core dumped)
```

```
energyplus: /home/julien/Software/Others/EnergyPlus/third_party/ObjexxFCL/src/ObjexxFCL/Array1.hh:1172: T& ObjexxFCL::Array1< <template-parameter-1-1> >::operator()(int) [with T = EnergyPlus::Construction::ConstructionProps]: Assertion `contains( i )' failed.
Process 29861 stopped
* thread #1, name = 'energyplus', stop reason = hit program assert
    frame #4: 0x00007ffff3dc4deb libenergyplusapi.so.9.4.0`ObjexxFCL::Array1<EnergyPlus::Construction::ConstructionProps>::operator(this=0x00007ffff7d4ae88, i=0)(int) at Array1.hh:1172
   1169		T &
   1170		operator ()( int const i )
   1171		{
-> 1172			assert( contains( i ) );
   1173			return sdata_[ i ];
   1174		}
   1175	
(lldb) bt
* thread #1, name = 'energyplus', stop reason = hit program assert
    frame #0: 0x00007ffff1499f47 libc.so.6`__GI_raise(sig=<unavailable>) at raise.c:51
    frame #1: 0x00007ffff149b8b1 libc.so.6`__GI_abort at abort.c:79
    frame #2: 0x00007ffff148b42a libc.so.6`__assert_fail_base(fmt="%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion="contains( i )", file="/home/julien/Software/Others/EnergyPlus/third_party/ObjexxFCL/src/ObjexxFCL/Array1.hh", line=1172, function="T& ObjexxFCL::Array1< <template-parameter-1-1> >::operator()(int) [with T = EnergyPlus::Construction::ConstructionProps]") at assert.c:92
    frame #3: 0x00007ffff148b4a2 libc.so.6`__GI___assert_fail(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.c:101
  * frame #4: 0x00007ffff3dc4deb libenergyplusapi.so.9.4.0`ObjexxFCL::Array1<EnergyPlus::Construction::ConstructionProps>::operator(this=0x00007ffff7d4ae88, i=0)(int) at Array1.hh:1172
    frame #5: 0x00007ffff4adff91 libenergyplusapi.so.9.4.0`EnergyPlus::SolarShading::ComputeWinShadeAbsorpFactors() at SolarShading.cc:11800
    frame #6: 0x00007ffff4a5c542 libenergyplusapi.so.9.4.0`EnergyPlus::SolarShading::InitSolarCalculations(ioFiles=0x00007fffffff8550) at SolarShading.cc:444
    frame #7: 0x00007ffff5ce5cc5 libenergyplusapi.so.9.4.0`EnergyPlus::HeatBalanceManager::InitHeatBalance(state=0x00007fffffff70d0, dataWindowComplexManager=0x00007fffffff9398, dataWindowEquivalentLayer=0x00007fffffff9508, dataWindowManager=0x00007fffffff9640, ioFiles=0x00007fffffff8550) at HeatBalanceManager.cc:5207
    frame #8: 0x00007ffff5ca2823 libenergyplusapi.so.9.4.0`EnergyPlus::HeatBalanceManager::ManageHeatBalance(state=0x00007fffffff70d0) at HeatBalanceManager.cc:372
    frame #9: 0x00007ffff4a23a51 libenergyplusapi.so.9.4.0`EnergyPlus::SizingManager::SetupZoneSizing(state=0x00007fffffff70d0, ErrorsFound=0x00007ffff7d74009) at SizingManager.cc:3954
    frame #10: 0x00007ffff49f9a4a libenergyplusapi.so.9.4.0`EnergyPlus::SizingManager::ManageSizing(state=0x00007fffffff70d0) at SizingManager.cc:295
    frame #11: 0x00007ffff49d8f96 libenergyplusapi.so.9.4.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffff70d0) at SimulationManager.cc:375
    frame #12: 0x00007ffff3b833b9 libenergyplusapi.so.9.4.0`RunEnergyPlus(state=0x00007fffffff70d0, filepath="\xc0p\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:401
    frame #13: 0x00007ffff3b82901 libenergyplusapi.so.9.4.0`EnergyPlusPgm(state=0x00007fffffff70d0, filepath="\xc0p\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:224
    frame #14: 0x00005555555e7154 energyplus`main(argc=1, argv=0x00007fffffffc218) at main.cc:60
    frame #15: 0x00007ffff147cb97 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:56), argc=1, argv=0x00007fffffffc218, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffc208) at libc-start.c:310
    frame #16: 0x00005555555e6f7a energyplus`_start + 42

(lldb) fr select 5
frame #5: 0x00007ffff4adff91 libenergyplusapi.so.9.4.0`EnergyPlus::SolarShading::ComputeWinShadeAbsorpFactors() at SolarShading.cc:11800
   11797	                        WindowShadingControl(WinShadeCtrlNum).ShadingType == WSC_ST_ExteriorShade ||
   11798	                        WindowShadingControl(WinShadeCtrlNum).ShadingType == WSC_ST_BetweenGlassShade) {
   11799	                        int ConstrNumSh = Surface(SurfNum).activeShadedConstruction; // Window construction number with shade
-> 11800	                        int TotLay = dataConstruction.Construct(ConstrNumSh).TotLayers; // Total layers in a construction
   11801	
   11802	
   11803	                        if (WindowShadingControl(WinShadeCtrlNum).ShadingType == WSC_ST_InteriorShade) {

(lldb) p Surface(SurfNum).Name
(std::__cxx11::string) $1 = "PUNCHED WINDOW 2"
(lldb) p Surface(SurfNum).activeShadedConstruction
(int) $2 = 0
```

Found this in  https://github.com/NREL/OpenStudio/pull/4085#issuecomment-696020518 for info.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4.0-RC1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/OpenStudio/blob/develop/resources/energyplus/Daylighting_School/in.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #8289 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
This looks ready to review and merge. I tagged this DoNotPublish since it was bug from a new feature being added for this release.

**Comment by Myoldmopar** [comment]
@jmarrec are you able to try this out directly?  If not I can do it soon.

**Comment by mitchute** [comment]
This runs for me.

**Comment by Myoldmopar** [comment]
Merge at will!

**Comment by jmarrec** [comment]
thanks for the quick fix.

**Comment by JasonGlazer** [comment]
Thanks for finding the problem. I wish I had seen this issue and fixed it in the original PR.

**Pull request merged**
