### PR TITLE
Water coil autosizing expanded to allow specifying design water temperature difference separately for each coil

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #5655

This change allows for finer control when sizing water coil design water flow rates using a water temperature difference specified in the water coil object instead of using the loop temperature difference from the Sizing:Plant object.  A new Design Water Temperature Difference input field is added to three water-to-air coils: Coil:Cooling:Water, Coil:Heating:Water, and Coil:Cooling:Water:DetailedGeometry.

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Nigusse** [comment]
No diffs is expected from this commit/push. Get input changes will follow.

**Comment by Nigusse** [comment]
I am thinking to add the new input field for "Water Coil Design DeltaT" right after "Maximum Water Flow Rate" input field for each water coil object. This option requires transition.  Is there any concern? Should I make the last input field to avoid transition. Let me know your thoughts. @mjwitte @Myoldmopar @EnergyArchmage ?

**Comment by mjwitte** [comment]
I would name the new field "Design Water Temperature Difference". I'm ok with putting the new field at the end.

**Comment by Nigusse** [comment]
@EnergyArchmage I forgot to update documentation. I will make documentation changes and push it shortly. Thanks.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by EnergyArchmage** [comment]
@Nigusse this branch has conflicts now, can you please resolve them?

**Comment by Nigusse** [comment]
I will start working on it shortly.

**Comment by Nigusse** [comment]
@EnergyArchmage conflict resolved. I had to switch to VS 2015 community version to check if complies. This branch did not compile in VS 2013 version that I had been using until this morning.

**Comment by EnergyArchmage** [comment]
@Nigusse  I think some existing integration testfiles should be modified to use the new feature, at least once for each coil.  You could put in the same delta T as in Sizing:Plant to avoid diffs.  

I made a commit. a unit test was crashing so I fixed the test frame WaterCoilsTest.  and fixed the I/O ref ordering problem.

**Comment by Nigusse** [comment]
@EnergyArchmage OK. I will use the example files "5ZoneAirCooled.idf" and "5ZoneCoolBeam.idf". I will make changes to all coils in these two example files to use coil deltaT for consistency.

**Comment by Myoldmopar** [comment]
Merged develop here.  Super curious what the regression results will look like.  Awesome if all green.  If Linux has two fails, at least I'll have confirmation.

**Comment by Myoldmopar** [comment]
Yay! All green!  

@Nigusse @EnergyArchmage @mjwitte Any remaining issues here before this merges?  I'm anxious to get this in so that the dashboard gets all nice and clean again.

**Comment by mjwitte** [comment]
@Myoldmopar Just made a quick glance over this.  Changes look good.  A little surprised that this required code changes in so many places (like fancoil, unit heater, unit ventilator, etc.).  I was expecting just WaterCoils and ReportSizingManager. Potential for some more centralization in the future.

**Comment by Nigusse** [comment]
I agree. Parent level maximum water flow rating sizing are done in the parent object sizing routine for most zone HVAC equipment (including ventilated slab) that could be consolidated into ReportSizingManager.

**Comment by EnergyArchmage** [comment]
Yes, I think this is good to go.  Thanks for cleaning up develop, strong work

**Pull request merged**
