### PR TITLE
Update third party libraries

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
Update JSON library: 3.10.2 -> 3.10.5
Update SQLite library: 3.36.0 -> 3.38.1
Update RE2 2021-08-01 -> 2022-02-01
Update GSL::span 0.38.1 -> 0.40.0

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Testing this one now with latest develop, but I'm assuming it will merge in a few minutes.

**Comment by nealkruis** [comment]
@mbadams5 Eigen is also a little out of date. Do you think it makes sense to update it in this PR too?

**Comment by Myoldmopar** [comment]
It might make sense but we are already days past the original freeze so I would prefer not to have any more surprise changes coming.  I am hoping to freeze this afternoon unless there is some show stopper.

**Comment by mitchute** [comment]
@nealkruis is Eigen used anywhere? When I last looked, I don't think I found any usages.

**Comment by nealkruis** [comment]
@mitchute It is used by Kiva.

**Comment by mitchute** [comment]
I'm gonna have to take a CMake class from you then. How does this work

https://github.com/NREL/EnergyPlus/blob/b59dc8412f40c3568217c03bdc36e09ffb5ff35e/third_party/kiva-ep/src/libkiva/CMakeLists.txt#L180

when you don't have Eigen in your `vendor` directory? It's finding the one in the `third-party` folder?

**Comment by Myoldmopar** [comment]
I tested this locally, running the full test suite as well as regressions against current develop.  No issues.  Please keep discussing the Eigen topic as needed, but I need to merge this as-is and move on to other PRs.  Thanks!

**Comment by nealkruis** [comment]
It's picking up the include directory from the INTERFACE target [here](https://github.com/NREL/EnergyPlus/blob/b59dc8412f40c3568217c03bdc36e09ffb5ff35e/CMakeLists.txt#L261).

Since the `kiva-ep/vendor/eigen` doesn't exist in the EnergyPlus repository it isn't searching there.

**Comment by mitchute** [comment]
Interesting. Good to know we can do that. Had thought that each `third-party` project would need to include a copy of their own dependencies, but I'm glad to see I was wrong.

**Comment by nealkruis** [comment]
This works for header-only libraries like Eigen, but there are different tricks for compiled libraries like [googletest](https://github.com/NREL/EnergyPlus/blob/e54147703aca61b7365065c3ba3e3e7ed4f08383/third_party/kiva-ep/vendor/CMakeLists.txt#L65) and [fmt](https://github.com/NREL/EnergyPlus/blob/e54147703aca61b7365065c3ba3e3e7ed4f08383/third_party/kiva-ep/vendor/CMakeLists.txt#L4).

**Pull request merged**
