### PR TITLE
Global-Elements

### PR DESCRIPTION
**Pull request by jmythms**
Pull request overview
---------------------
Deglobalizes Elements.cpp, Elements.hpp. Waiting for CI results. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@jmythms this may have conflicts after the merge from @mitchute's global branch.  I also have a globals branch ready to go in sometime this evening.  Are you planning any additional work here or is this ready if CI is happy?

**Comment by jmythms** [comment]
@Myoldmopar  Don't intend to do any more additional work on here. Can go in if CI is happy.

**Comment by jmythms** [comment]
@Myoldmopar it seems to have some diffs. I will check them out and let you know if it is ready by tonight.

**Comment by jmythms** [comment]
Everything except the EIO diffs went away after merging develop. Pushing fixed code now.

**Comment by Myoldmopar** [comment]
Very nice!  OK, I will build this branch locally now and see if I get all clean results and see if we can get this merged in.  (I'll do a test build on Windows if I don't wait for CI, @mjwitte)

**Comment by jmythms** [comment]
Does this look ok? I don't think the Windows CI build failure is something I did, please let me know if it is. The regression test failure in the Linux CI is SolarShadingTestGPU and integration failure is HospitalLowEnergy which are the common ones.

**Comment by Myoldmopar** [comment]
@jmythms no you didn't cause the Windows failure.  It snuck into develop but @mjwitte fixed it up quickly and develop is already clean again.  I built this branch on my Windows laptop and it built successfully.  Yes, this looks completely clean to me.  Let me evaluate the PRs this morning and make sure I don't need to drop any others in first and then this will go in.

**Comment by jmythms** [comment]
Thank you very much!

**Comment by Myoldmopar** [comment]
OK, I pulled develop in and built it once again.  Unit tests pass and I ran 100 regressions with zero diffs as expected.  I think this is good to go in.  Thanks @jmythms .  Once again, I'll be ready to resolve conflicts in subsequent branches as we continue this globals/PRMerge frenzy.

**Comment by jmythms** [comment]
Thank you!

**Pull request merged**
