### PR TITLE
Address Improve documentation for Zone Air Heat Balance Internal Convective Heat Gain Rate

### LINKED ISSUE #9832: Improve documentation for Zone Air Heat Balance Internal Convective Heat Gain Rate
Issue overview
--------------
This is a request to make the documentation for `Zone Air Heat Balance Internal Convective Heat Gain Rate` more descriptive.

Currently, the documentations reads:

_1.10.5.7 Zone Air Heat Balance Internal Convective Heat Gain Rate [W]
The Zone Air Heat Balance Internal Convective Heat Gain Rate is the sum, in watts, of heat transferred to the zone air from all types of internal gains, including people, lights, equipment etc. This and the following provide results on the load components of the zone air heat balance. This field is not multiplied by zone or group multipliers._

The "etc." is doing quite a lot of heavy lifting.  The variable is [calculated here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataHeatBalance.cc#L236-L242).
`SumIntGains`, which constitutes the variable, appears to include some [return air gains](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5812-L5833) and [surface convection from certain kinds of window-related objects](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5931-L5956).

This isn't clear in the documentation, and one could reasonably assume that `Zone Air Heat Balance Internal Convective Heat Gain Rate`, would report the same values as `Zone Total Internal Convective Heating Rate`, calculated [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/InternalHeatGains.cc#L4304-L4310) and documented as:

_1.10.5.25 Space or Zone Total Internal Convective Heating Rate [W]
1.10.5.26 Space or Zone Total Internal Convective Heating Energy [J]
These output variables represent the sum of convective gains from specific sources (e.g. equipment) throughout the space or zone in Watts (for rate) or joules. This includes convective gain from People, Lights, Electric Equipment, Gas Equipment, Other Equipment, Hot Water Equipment, and Steam Equipment._

In some cases, such as restaurant prototype models, the extra variables in the "etc." of `Zone Air Heat Balance Internal Convective Heat Gain Rate` are significant enough to flip the sign and magnitude of the values compared to `Zone Total Internal Convective Heating Rate`.  That's really confusing for two variables that supposedly just capture the same internal gains.

### Details
- OpenStudio v3.5.1 / EnergyPlus v22.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9832 
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Nigusse** [comment]
`Space or Zone Total Internal Convective Heating Rate [W]` and `Space or Zone Total Internal Convective Heating Energy [J]` variables constitute internal convective heat gains from eight EnergyPlus objects. Snapshot of new table in IO Ref documentation is shown below. Two other report variables also reference the same table.

image

**Comment by Nigusse** [comment]
image


image

image

**Comment by Nigusse** [comment]
This PR is ready for review.

**Comment by Myoldmopar** [comment]
@Nigusse there were build issues with the docs due to the underscore literals in there (that's a math token, so LaTeX expects them only in underscore environments).  I cleaned them up and committed.  This PR is still only changing the one doc file, so if the Documentation build passes, I'll merge this in.

**Comment by Myoldmopar** [comment]
Building fine now.  This is from the artifact on GHA:

image

Unfortunately it look long enough that Decent CI will be making a pass over it.  I'll still merge and delete the branch.  Thanks.

**Comment by Nigusse** [comment]
@Myoldmopar Thank you for fixing the build issue.

**Pull request merged**
