### PR TITLE
Fix false unbalanced exhaust flow warning

### PR DESCRIPTION
**Pull request by mjwitte**
Addresses #4293 
OA mixer calcs resulted in fancoil mixed air flow rate (and then fan coil outlet flow rate) slightly less than the fan coil inlet (return) flow rate. This resulted in a tiny negative value for AirLoopFlow(AirLoopNum).SupFlow in ZoneEquipmentManager::CalcZoneMassBalance causing a false unbalanced exhaust flow warning.  Fixed by limiting AirLoopFlow(AirLoopNum).SupFlow to be >=0.

### CODE REVIEW

**Comment by mjwitte** [comment]
Interesting.  With the original Plan B approach that limited TotSupplyAirMassFlowRate>=0 in CalcZoneMassBalance, an unbalanced flow warning was eliminated in ZoneVSWSHP_wDOAS.

But now with that taken out, and only a SmallMassFlow tolerance applied to the test, ZoneVSWSHP_wDOAS still has the warning, but now the warning is eliminated in RefBldgQuickServiceRestaurantNew2004_Chicago.  Need to look at these more closely.

**Comment by mjwitte** [comment]
ZoneVSWSHP_wDOAS has a separate issue.  If you change to detailed output there are two timesteps (running with Chicago weather, where the supplemental heat kicks on at 7am and the  ZoneHVAC:WaterToAirHeatPump zone inlet mass flow rate is 1.42 while the outlet flow rate (into the WSHP) is 2.10.  The WSHP mixed air node also shows the higher flow rate.

**Comment by mjwitte** [comment]
New issue posted for the ZoneHVAC;WaterToAirHeatPump problem.  This is ready for review.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Pull request merged**
