### PR TITLE
Detect arm64 target arch (M1 silicon chips)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Technically I'm detecting armv8 architecture, but it seems safe to assume it's an M1 mac so arm64.

Source: https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qprocessordetection.h

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I marked this as DoNotPublish for now but I'm open to discussing how visible we want this to be.  I'm also pulling develop in to see if we can get this cleaned up.

Does anyone have any preliminary thoughts while we wait on CI here?  (I haven't actually looked at the changes yet...)

**Comment by Myoldmopar** [comment]
This looks good to me.  The Windows error is happening on other branches.  I've rebooted the CI machine and hopefully that gets cleaner now, but these changes are not related and I'm not going to worry about another round of results here.  

@nealkruis this does add support for the m1 chipset in the Kiva CMake files, so I want to give you a chance to take a look or pull it down and test it out if you want.  Otherwise I think this is ready to go.

**Review by nealkruis — APPROVED** [review]
@Myoldmopar Changes to Kiva look fine to me. I will update the primary Kiva repository to reflect these changes to keep them in sync.

**Comment by Myoldmopar** [comment]
Nice, thanks!  OK, this will merge now then.  Thanks @jmarrec

**Pull request merged**
