### PR TITLE
Allow HX to control to set point temperature regardless of operating mod...

### LINKED ISSUE #4794: HeatExchanger:AirToAir:SensibleAndLatent Supply Air Outlet Temperature Control problems
User file has three similar VAV systems plus other with heat recovery using HeatExchanger:AirToAir:SensibleAndLatent.  Supply Air Outlet Temperature Control is set to Yes for all of the HX, but only the first one seems to be honoring that.  The others are over-recovering sending warm air into the system causing the cooling coil to operate at a high load.  Even the first HX is not controlling well and the cooling coil is coming on at a small load, but that's a separate (maybe) issue.

### PR DESCRIPTION
**Pull request by rraustad**
Allows HX to control to set point regardless of operating (heating or cooling) mode.  Fixes #4794.

### CODE REVIEW

**Comment by rraustad** [comment]
in HeatRecovery.unit.cc (and several other unit tests), what happens when there is #include <EnergyPlus/UtilityRoutines.hh>
without a corresponding using namespace?

**Comment by mjwitte** [comment]
@rraustad I've also encountered one unit test that would fail only once every three or four times I would run it. If you haven't seen it, the error messages from MacOS-10.9-clang give you lots of clues to go on.  Also, when you run locally, consult the err output file (same folder as energyplus_tests.exe) and it may give you some clues.

**Comment by mjwitte** [comment]
@rraustad Have you made any progress on the failing unit test?

**Comment by rraustad** [comment]
I have reviewed and run the HX unit test in debug and release. No issues that I can see. How do I run the CI again to see if they still fail? Do I have to make a commit, or is there a more direct way?

**Comment by Myoldmopar** [comment]
You can delete the results and it should kick off a new build.  But it may
actually be easier to just make a dummy commit (update the README with an
extra space or something).

On Fri, Apr 3, 2015 at 10:23 AM, Richard Raustad notifications@github.com
wrote:

> I have reviewed and run the HX unit test in debug and release. No issues
> that I can see. How do I run the CI again to see if they still fail? Do I
> have to make a commit, or is there a more direct way?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NREL/EnergyPlus/pull/4833#issuecomment-89342902.

## 

Edwin Lee, PhD
Engineer, Commercial Buildings Research Staff
National Renewable Energy Laboratory

**Comment by mjwitte** [comment]
@rraustad Even better would be to merge in develop to bring this branch up to date.

**Comment by rraustad** [comment]
It appeared to be up to date already. Merge said it was 0 commits ahead and already up to date when I tried merging. I used suggestion from @Myoldmopar to update readme.

**Comment by mjwitte** [comment]
@rraustad Interesting.  Github still says this branch is 58 commits behind develop.
https://github.com/NREL/EnergyPlus/branches
Did you merge from

**Comment by rraustad** [comment]
The previous attempt used TortoiseGit merge from remotes/origin/develop and said it was up to date.
I switched to my local develop branch and did a pull. There were updates to that branch. So why didn't TortoisGit merge do the same thing?
I switched back to this branch and instead merged from my develop branch, there were updates. I guess I should push this branch again?

**Comment by mjwitte** [comment]
@rraustad Did you do a fetch before the merge from remotes/origin/develop ?

**Comment by Myoldmopar** [comment]
So, it's all about what you are merging from.  A few notes:
- "Git Merge" doesn't know anything about remote repositories like the GitHub origin.
- "origin/<branchname>" is the most recently known copy of a remote branch, but is stored locally.
- "Git Pull" does two operations:
  - Git Fetch: which pulls down all remote branch info and updates all local origin/branch pointers
  - Git Merge: if your current branch tracks a remote branch it pulls in those remote changes

When I want to merge in develop, I do these steps:
- "Git Fetch", so that my local repo has an updated version of develop.  On my local repo this information is contained in "origin/develop".  You could also do "Git Pull" here, but I don't like commands doing 2 things at once, especially when I am out on a branch that could be conflicted.
- "Git Merge origin/develop", make sure that I am updating from the remote version of develop

One more clarification:
Let's say you are on branch "FeatureBranch".  You do a Git Pull operation.  First it fetches all the remote information and stores it in the origin/\* pointers.  If changes have been made in the remote FeatureBranch branch, then it merges those changes into your local FeatureBranch.  However, this **did not** update your local develop branch.  Next time you change to the develop branch, Git will tell you "Branch 'develop' is behind origin/develop by N commits".  This is because origin/develop was updated, but Git doesn't jump to conclusions and merge into local develop.  This is a good thing.  But you'll still likely want to bring those changes into your develop branch before you start working.  So when you are on develop, do another Git Pull.  It will first make sure that origin/develop is updated, then it will merge into local develop.

We can chat more anytime.

**Comment by rraustad** [comment]
Now when I do a TortoiseGit fetch, it says all is up-to-date. And TortoiseGit merge also says it's up to date. So I guess my local branch is now up to date with GitHub develop.

I still don't understand why the HX unit test is failing. It's the second EXPECT_DOUBLE_EQ that fails first. 

EXPECT_DOUBLE_EQ( ( ExchCond( ExchNum ).SupInTemp + ( ExchCond( ExchNum ).CoolEffectSensible75 \* ( ExchCond( ExchNum ).SecInTemp - ExchCond( ExchNum ).SupInTemp ) ) ), Node( ExchCond( ExchNum ).SupOutletNode ).Temp );

In the debugger I see:
ExchCond( ExchNum ).SupInTemp = 24.0
ExchCond( ExchNum ).SecInTemp = 15.0
ExchCond( ExchNum ).SupOutletNode = 2
ExchCond( ExchNum ).CoolEffectSensible75 = 0.75
Node(2).Temp = 17.25
Doing the math yields 17.25 which is why this unit test is passing on my PC. WaterCoilTests also passes on my PC.

The only other thing I can think to try is to remove the math from the EXPECT_DOUBLE_EQ line:
Toutlet = ( ExchCond( ExchNum ).SupInTemp + ( ExchCond( ExchNum ).CoolEffectSensible75 \* ( ExchCond( ExchNum ).SecInTemp - ExchCond( ExchNum ).SupInTemp ) ) );
Tnode = Node( ExchCond( ExchNum ).SupOutletNode ).Temp;

EXPECT_DOUBLE_EQ( Toutlet, Tnode );

**Comment by rraustad** [comment]
Here's a clue. Any idea why another module would cause this failure? Do I need to #include General ?
hxutfailed

**Comment by rraustad** [comment]
All 4 (5 using Ubuntu) of the example files with diff's have:
  HeatExchanger:AirToAir:SensibleAndLatent,
    Yes,   !- Supply Air Outlet Temperature Control

**Comment by rraustad** [comment]
All unit tests passed.

**Comment by rraustad** [comment]
There is not much more time to get this merged in before the contract deadline. Is there some problem that was found regarding HX temperature control?

**Comment by mjwitte** [comment]
@rraustad @Myoldmopar Tested and reviewed defect file results and several other example files that use HeatExchanger:AirToAir:SensibleandLatent.  All looks OK.  I've merged in develop now to bring this branch up to date, will wait to see how test results come back.

**Comment by rraustad** [comment]
I must have missed this on the cc. I was just told to push to develop and that doesn't sound right. Am I to create a new branch for doc revisions or not?

**Comment by mjwitte** [comment]
@rraustad Yes, a new branch and a new pull request.  Had I known the new docs would be added to develop today, I would have waited to merge this.  In the future, the doc changes will go in with the code changes on the same branch.

**Pull request merged**
