### PR TITLE
Chiller Electric EIR Plant Component Refactor

### PR DESCRIPTION
**Pull request by mitchute**
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
IDK what's going on with these failures. I can't reproduce it locally. Hopefully it'll settle down once the merge-flurry clears.

**Comment by mitchute** [comment]
@Myoldmopar the results coming out of this morning's merge from develop are showing some small math diffs and text diffs which are due to fields being reordered. The small math diffs are for site and plant energy usage, which are intermittent and on the order of less than 1E-7 J. I can't point to anything specific which is causing the diffs, but I'm thinking this work is ready to go in. Let me know if we need to dig further, though.

**Comment by Myoldmopar** [comment]
Yep, this looks really good.  As for the diffs, with all those shared variables you cleaned up, it's certainly possible one of them was accidentally being shared between chillers.  To have so many files with no math diffs at all and just some with small math diffs makes me feel pretty confident in this.  CI just started working on the style commit so I might as well wait until that's done but then this should be good to go in.  Thanks!

**Comment by Myoldmopar** [comment]
OK, I'll take it.  CI looks happier now, and Equip control is assigned in a good spot.  Merging, thanks @mitchute

**Pull request merged**
