### PR TITLE
Pretty up testfiles

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Pretty up testfiles to reduce non-substantive changes in #7448. This should be no-diffs.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
@mjwitte this is going to cause a lot of diffs when we go to merge in the coil refactor since I've already applied transition over there. Just noting it here so we don't forget when we're moving on that project again.

**Comment by mjwitte** [comment]
@mitchute All of these changes should already be present there, so it should just fall through.

**Comment by mjwitte** [comment]
Hmm, no CI results yet?

**Comment by mitchute** [comment]
@mjwitte OK, NM then. I didn't realize git was smart enough to figure that out. Carry on...

**Comment by Myoldmopar** [comment]
> Hmm, no CI results yet?

The machine had gone down at some point at the end of last week; NREL may have endured a power issue.  Anyway, I just got the Windows and Linux booted up and running again.  I expect results to come in overnight, and I'll check on the Mac in the morning.

**Comment by mjwitte** [comment]
@Myoldmopar This is simply a formatting cleanup (spacing, field names, etc.) using the `MakingPretty` option in transition. This will help reduce the number of extraneous files that show changes both in #7448 and the new DX coil work. I've tested merging this into both of those branches and there are a handful of files that have conflicts, but they should be easy to resolve.

**Comment by Myoldmopar** [comment]
I have no problem with this going in now, CI is happy.  Merging.

**Pull request merged**
