### PR TITLE
Zone-level equipment output may not match system outputs when there is significant thermostat setpoint change 

### PR DESCRIPTION
**Pull request by Nigusse**
Issue #5908

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
- [ ] Documentation changes in place
 - [ ] Changed docs build successfully

### CODE REVIEW

**Comment by Nigusse** [comment]
The differences between these variables is expected under certain conditions per the design. Hence only explanation was added to the three output variables description. @mjwitte Would please review the updates description?

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@Nigusse These say "when the zone thermostat temperature setpoint is changing significantly." That is usually what drives this, but isn't it more general that these will differ "when the zone temperature is changing significantly."?

**Comment by Nigusse** [comment]
@mjwitte Yes, as long as the previous zone air temperature and the corrected (current) zone temperatures are different, then difference in these three variables is expected. One more thing that I noted also was that if AnalyticalSolution is used for ZoneAirHeatBalanceAlgorithm then the diffs are relatively smaller.

**Pull request merged**
