### PR TITLE
Fix #8357 - tweak GitHub actions

### LINKED ISSUE #8357: Suggest a few tweaks on Github Actions
Now that we are using Github Actions, there are many possibilities.  There are also already a few things I'd like to fix up.

- [x] Need to tweak the add-path stuff to properly set the path to the miktex and qtifw binaries
- [x] Something still goes wrong sometimes while trying to install miktex.  It's nothing we are doing, just a communication error.  I think we may need to investigate an alternative miktex install approach.
- [x] We should try to collapse the two Windows builds into a matrix, maybe even moving all the package builds to a matrix if it is reasonable.
- Maybe other things, but that alone would help.

@jmarrec care to take a crack at some of this?

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Note: I used my fork to avoid polluting the Release page with a few dozen failing tags/builds

 - Fixes #8357
 - Two tags are present on this PR: `8357_test_ok` (468ed2cca9dbad2dfa6c6c9ccfce02fc9bdeb9e4) and `8357_single` (650e08a3d6f567c7d042e568b1c13724d4715d56):
    - `8357_test_ok` is windows made into a matrix, linux and mac release still separated. See result of build in https://github.com/jmarrec/EnergyPlus/releases/tag/8357_test_ok and windows actions run at https://github.com/jmarrec/EnergyPlus/actions/runs/340551242
    - `8357_single` is every build into a single matrix. See result of build in https://github.com/jmarrec/EnergyPlus/releases/tag/8357_single and https://github.com/jmarrec/EnergyPlus/runs/1341725027?check_suite_focus=true

It's really a matter of preference to choose between the two. Having a single matrix avoids repeating code and makes it clear that this is the release build only. But that also means if you need to rerun the workflow, you need to rerun all builds at once, you can't just reboot windows or mac.

That being said, another big improvement in this PR is that the MiKTeX stuff on windows now uses a fixed repo (I picked `https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/` since it seems reliable, unlike the koddos mirror that's often erroring), so it shouldn't pose too many problems. I also moved away from using chocolatey, since I couldn't make the miktex.install package options work for our needs, instead I'm directly downloading the miktex CLI install tool, and using that to install and configure miktex.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@jmarrec this is awesome!  OK, so your point about being able to re-run individual workflows really is a nice thing about keeping them separate.  In addition, keeping the build rules simple and straightforward on each platform is also nice.  The fewer IF Windows style things is actually nice to me.  My preference would be to clean this up so each platform has their own workflow, but having Windows 32 and 64 in their own little matrix is ideal.  And thanks for cleaning up the MikTeX stuff, go ahead and get rid of any old commented chocolatey stuff while cleaning up the other changes.

I'm super excited about this!  Thanks!

**Comment by jmarrec** [comment]
@Myoldmopar I reverted to using one workflow per platform and did some clean up. I put the single release in disabled workflows, as I think it's a healthy base should we decide to do a cross-platform matrix workflow at some point. You can delete it if you disagree.

My Fork is running Github Actions on my last tag push at https://github.com/NREL/EnergyPlus/pull/8364/commits/fee824465fff2b0f1a21de0a83c4f2da51552af0:

* Linux: https://github.com/jmarrec/EnergyPlus/actions/runs/359909787
* Mac: https://github.com/jmarrec/EnergyPlus/actions/runs/359909791
* Windows: https://github.com/jmarrec/EnergyPlus/actions/runs/359909795

**Comment by Myoldmopar** [comment]
Awesome, I'll take another look and once it runs and merges I'll kick off a test build here just to verify.

**Comment by jmarrec** [comment]
@Myoldmopar Seems like it can't find QtIFW... Not sure why, It worked in the matrix.... I'll have another look.

**Comment by Myoldmopar** [comment]
> It worked in the matrix....

image

**Comment by jmarrec** [comment]
My guess is that it's just a difference of version of aqtinstall. In the matrix build, it was 0.9.7 and it was issuing a warning about invalid combination but working. In 0.9.8 seems like it does exactly nothing now. Lucky me.

Matrix build:

```
out_dir=/home/runner/work/EnergyPlus/Qt
+ aqt tool linux tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=/home/runner/work/EnergyPlus/Qt
2020-11-02 11:24:11,740 - aqt - INFO - aqtinstall(aqt) v0.9.7 on Python 3.7.9 [CPython GCC 7.5.0]
2020-11-02 11:24:11,740 - aqt - WARNING - Specified target combination is not valid: linux tools_ifw qt.tools.ifw.32
2020-11-02 11:24:12,464 - aqt - INFO - Downloading qt.tools.ifw.32...
2020-11-02 11:24:12,465 - aqt - DEBUG - Download URL: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.2ifw-linux-x64.7z
2020-11-02 11:24:12,921 - aqt - INFO - Redirected URL: http://qt.mirrors.tds.net/qt/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.2ifw-linux-x64.7z
2020-11-02 11:24:18,134 - aqt - INFO - Finish installation of ifw-linux-x64.7z in 5.669658829000014
2020-11-02 11:24:18,136 - aqt - INFO - Finished installation
2020-11-02 11:24:18,136 - aqt - INFO - Time elasped: 6.39893362 second
```

Now

```
out_dir=/home/runner/work/EnergyPlus/Qt
+ aqt tool linux tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=/home/runner/work/EnergyPlus/Qt
2020-11-12 23:05:38,849 - aqt - INFO - aqtinstall(aqt) v0.9.8 on Python 3.7.9 [CPython GCC 7.5.0]
2020-11-12 23:05:39,432 - aqt - INFO - Finished installation
2020-11-12 23:05:39,432 - aqt - INFO - Time elasped: 0.58545507 second
+ echo /home/runner/work/EnergyPlus/Qt/Tools/QtInstallerFramework/3.2/bin
```

**Comment by jmarrec** [comment]
Bingo: https://github.com/miurahr/aqtinstall/pull/172

**Comment by Myoldmopar** [comment]
@jmarrec so you still need to make a tweak to get the right version of the tool, right?  Otherwise this is ready?

**Comment by jmarrec** [comment]
My Fork is running Github Actions on my last tag push at https://github.com/NREL/EnergyPlus/pull/8364/commits/31347de67f2ad8ac9d019688fc660c2ca8cd8d13

* Linux: https://github.com/jmarrec/EnergyPlus/actions/runs/365912713
* Mac: https://github.com/jmarrec/EnergyPlus/actions/runs/365912716
* Windows: https://github.com/jmarrec/EnergyPlus/actions/runs/365912714

**Comment by jmarrec** [comment]
@Myoldmopar with the upgrade to 4.0 it seems to work fine now, cf https://github.com/jmarrec/EnergyPlus/releases/tag/8357_multiple

**Review by Myoldmopar — APPROVED** [review]
This looks fantastic!

**Comment by Myoldmopar** [comment]
This is all wonderful.  Builds look clean and great.  Thanks for splitting out the workflows but also keeping the combined one in the disabled folder.  Merging this.

**Pull request merged**
