### PR TITLE
Provide a C-API for the EnergyPlus DLL for ease of calling from other programming languages

### PR DESCRIPTION
**Pull request by michael-okeefe**
Pull request overview
---------------------
**Summary**: This pull request builds off pull request [“Add API function EnergyPlusReturnCodes that uses return codes instead of std::exit()”](https://github.com/NREL/EnergyPlus/pull/6885) . This pull request adds a C-compatible API equivalent to the current C++ API but with different names and calling conventions and arguments so as to make it much easier to call the EnergyPlus DLL from other non-C++ programming languages. These new API functions take C-compatible types that are easily marshallable to allow much easier use of the DLL from other languages.

----------------------

A new feature proposal for this effort is available: ["Add C-API for EnergyPlus DLL and API Method that uses Return Codes instead of std::exit()"](https://github.com/NREL/EnergyPlus/blob/capi_pull_request/design/FY2018/NFP-capi-and-return-codes.md)

----------------------

A C-API allows a DLL to be more easily called from non-C++ languages. The C Abstract Binary Interface (ABI) is stable and does not experience the name-mangling of the C++ compiler. The exposure of a C-API in a C++ DLL is commonly recommended for allowing calling from non-C++ programming languages (see [1], [2], and [3]).

[1]: https://msdn.microsoft.com/en-us/library/wf2w9f6x.aspx
[2]: https://msdn.microsoft.com/en-us/library/dt232c9t.aspx
[3]: http://rvelthuis.de/articles/articles-dlls.html

This pull request provides such a C-compatible API and translates arguments to be C-compatible arguments as well. For example, the directory path argument of EnergyPlusPgm is currently a C++ String Object which makes calling the API only possible via C++. By adding a C-compatible API to the EnergyPlus DLL, the DLL can be called from many other non-C++ languages such as Python (via ctypes), C, Delphi, Ruby (via the FFI gem), and others.

This pull request builds on the pull request ["Add API function EnergyPlusReturnCodes that uses return codes instead of std::exit()"](https://github.com/NREL/EnergyPlus/pull/6885), incorporating all of its changes and adding this pull request's C-API changes on top.

**Work completed under the Big Ladder Contribution License Agreement.**

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by kbenne** [comment]
This seems reasonable to me and I don't disagree with the merits @michael-okeefe calls out. A few questions.

1. What specific use cases are there? You guys must have some application in mind or you wouldn't be making this investment.
2. How does this play out if EnergyPlus develops a more capable api? It isn't hard to imagine future exports from EnergyPlus that desire to expose more complex types.

**Comment by michael-okeefe** [comment]
Hi Kyle:

Here are some thoughts for your questions:

1. The specific use case we are unable to achieve with the current DLL is calling the energyplusapi.dll via another language. We're updating an application that uses EnergyPlus 8.0 to 8.9. The current application used the EnergyPlus DLL from 8.0 (Fortran) and used both the main simulation function as well as the progress and message callback functions. We'd like to preserve that functionality while enabling use of the 8.9 engine. In trying to upgrade to EnergyPlus 8.9, we were particularly stymied when the DLL exits via std::exit() from the main simulation routine. The exit is hard to signal forward to the application we're updating unless we change the architecture to be more of a polling architecture. We thought proposing this fix as a PR would be more expedient.

2. If you're talking about exposing a C-API that allows manipulation of complex types from EnergyPlus (i.e., objects in C++), there is a great article about how to expose this to non-C++ languages here (written in the context of Delphi but the C++ library changes are applicable across the board):

http://rvelthuis.de/articles/articles-cppobjs.html#flattening

I think it would be a case that, if you're calling directly from a program written in C++, something "richer" could be provided directly in the C++ API (similar to how the current C++ API uses std::string for the path) whereas for non-C++ languages, a "C flattened" API would be required. That "raw" API can be then made pretty by a little work in the calling language to make things look more like objects again if so desired but it's plenty useful as is.

**Comment by nrel-bot-2** [comment]
@michael-okeefe @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@michael-okeefe @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@michael-okeefe @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@michael-okeefe @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@michael-okeefe @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@michael-okeefe @lgentile it has been 51 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@michael-okeefe it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@michael-okeefe it has been 8 days since this pull request was last updated.

**Comment by wta12** [comment]
@michael-okeefe @Myoldmopar : Have this features been tested and gotten published soon? May I try to compile and test now?

**Comment by Myoldmopar** [comment]
@wta12 we actually have a completely separate API work that is going to supersede this.  The new API will be available in the next release and have user guides to get up and running with it.  There's no pull request yet, so I would watch the pull request list to watch for when it pops up.

Based on the call today, @nealkruis, we should close this, right?

**Comment by nealkruis** [comment]
@Myoldmopar I think so. Let's double check with @michael-okeefe.

**Comment by michael-okeefe** [comment]
Fine by me

**Pull request closed without merging**
