### PR TITLE
Fix airloop OA limiting factor

### LINKED ISSUE #8802: Air System Outdoor Air Limiting Factor can be wrong for simple OA controls due to tiny differences
Issue overview
--------------
Air System Outdoor Air Limiting Factor uses several < or > tests to determine if the OA flow rate has been constrained by a particular limiting factor (e.g. economizer, OA schedule, etc.). For simple OA controllers with no economizer, no min OA schedule, and no other constraints, this should always be zero. But occasional 1s show up due to tiny differences in comparing two values which should be equal, but due to different calculation paths for the two values, they differ out in the 10th decimal or so. Probably need to add a tolerance to one or more of these comparisons, and review the entire logic for this output.

Also, this output is reset to zero every time step inside `CalcOAController` which I'm pretty sure is not called if an airloop is off. Need a test file to prove this.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.6.0-b8f984adb5
 - Discovered while investigating unexpected diffs in #8759 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #8802

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Closing this for now until I get back to working on it.

**Comment by mjwitte** [comment]
Superseded by #9947

**Pull request closed without merging**
