### PR TITLE
Improve TimeBins report rounding

### PR DESCRIPTION
**Pull request by JasonGlazer**
to the same precision as the reporting. This will hopefully stabilize the TimeBins reports when working with the vectorization.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@amirroth @Myoldmopar @nealkruis @lgentile @mjwitte Here is the change to the TimeBins report that rounds the values to the same number of digits as the final report during the gathering process. This will hopefully help your testing.

**Comment by amirroth** [comment]
If I just do a pull, does that get me this change?

-Amir

**Comment by JasonGlazer** [comment]
I think this change would need to be accepted and merged into develop and then your could merge from develop. 

It is only a few lines so it might be easier to copy it into your active code and see if it helps first. It definitely changed the results of the AIR SYSTEM OUTDOOR AIR FLOW FRACTION timebin report in the full service restaurant file between the 0.8000 to 1.0000 bin and the greater than 1.0000 bin.

**Comment by mjwitte** [comment]
@amirroth In theory, you could fetch, then merge from this branch, but until it's in develop, the CI reports will still have the old form as the base result for regressions.

**Comment by JasonGlazer** [comment]
@amirroth Please let me know if this helps with your testing. If it doesn't then I will just get rid of the pull request but if it does help, I will add a unit test so that it can be committed to the Develop branch.

**Comment by Myoldmopar** [comment]
There is a workaround if you want to test a different baseline branch for your own branch @mjwitte: https://github.com/NREL/EnergyPlus/blob/develop/.decent_ci.yaml#L6

**Comment by mjwitte** [comment]
@Myoldmopar Be careful about showing me secret places . . .

**Comment by Myoldmopar** [comment]
Expanding my comment [above](https://github.com/NREL/EnergyPlus/pull/5295#issuecomment-152581139).

@amirroth I think the best way to proceed would be to:
- Keep this branch by @JasonGlazer on a branch for now, don't try to force a merge in
- Pull in his changes into your own branch: from a command line:

```
$ git status                # make sure you are on your own branch in this repo
$ git fetch origin        # pull down latest changes into origin/* pointers
$ git merge origin/ModifyTimeBinsToUseRounding  # pull reporting changes into your branch
```

This will get the fix into your branch, but like @mjwitte said, CI will still be comparing against develop, which doesn't have this improvement.  However, if you change the line [here](https://github.com/NREL/EnergyPlus/blob/develop/.decent_ci.yaml#L6) to use a different baseline branch, CI will do a better comparison for you.  So it would be from:

```
regression_baseline_default : develop
```

to:

```
regression_baseline_default : ModifyTimeBinsToUseRounding
```

We'll have to make sure to revert that back once the ModifyTimeBinsToUseRounding branch gets into develop, but we can worry about that later.

Let me know if you need anything.

**Comment by amirroth** [comment]
Yes, git master.

**Comment by amirroth** [comment]
That got rid of almost all big diffs except for:

_HVAC Sizing Summary_Entire Facility_Plant Loop Coincident Design Fluid
Flow Rate Adjustments_ on LargeOffice

and

_AIR SYSTEM OUTDOOR AIR FLOW FRACTION []_PSZ-AC:4_Time Bin Results_ on
SuperMarket

-Amir

**Comment by amirroth** [comment]
@JasonGlazer, may need a few tweaks, but definitely going in the right direction. @nealkruis, six big diffs down, two to go.

**Comment by JasonGlazer** [comment]
@amirroth, what tweaks do you think are needed?

**Comment by amirroth** [comment]
I don't know yet, I need @nealkruis to help chase down the remaining big
diffs. One thing I did notice is that the diffs are no longer in the N (max
value) and N-1 bins, they are in the interior bins. Does that give you a
hint?

**Comment by JasonGlazer** [comment]
Could you post some screen shots of the timebins reports that do not match but should?

**Comment by amirroth** [comment]
supermarket_oaff_2015-11-02

**Comment by JasonGlazer** [comment]
@amirroth I am not sure what is causing this, maybe @nealkruis will have a better idea. I am leaving the pull request open until we are sure that we don't need to modify the TimeBins reporting any further.

**Comment by nealkruis** [comment]
There is one timestep (7/10 20:15:00) in the simulation where the numerical precision in the HBIRE calculations causes a calculated value to fall on either side of the bin separation (0.6000). It is surprising, (and a little unsettling) that the change in order of operations can have 0.1% impact on the numeric precision in a fairly unrelated section of the code.

screen shot 2015-11-03 at 11 48 39 am

There are likely greater differences in numerical precision at this level between compilers and platforms, we just never compare them as far as I'm aware (for example: clang on Mac OS X vs. MSVC on Windows).

Does this kind of difference bother people? If not, perhaps we can relax the diff tolerance for the time bin tables?

Either way, I don't think the solution is changing the way time bin rounding works beyond the changes already in this PR.

@amirroth @JasonGlazer

**Comment by mjwitte** [comment]
@nealkruis Which example file are we talking about here?  I would start looking at the diffs in the zone load and surface temperatures to see what's driving the (I'm guessing) economizer to land at a different OA fraction.  My recollection is that compiler/platform differences are very tiny, much smaller than these differences.

**Comment by amirroth** [comment]
I agree on both accounts.
1. The differences across compilers are likely to be bigger than the
   differences within a single compiler, even for transforms as significant as
   vectorization.
2. Numeric optimizations will result in "big diffs" whenever there is a
   continuous-to-discrete mapping like TimeBins no matter how much we round so
   there needs to be a diffing-based solution. Now in order to create a
   diffing-based solution, the column headings need units and/or levels of
   aggregation, which the time bins tables do not have. Actually, many tables
   do not have these, but we are not seeing big diffs on these tables. I
   suggest that for TimeBins add the units [hours].

**Comment by amirroth** [comment]
RefBldgSuperMarket

**Comment by mjwitte** [comment]
RefBldgSuperMarket has constant volume "PSZ" systems which use the (risky) SetpointManager;SingleZoneReheat.  And PSZ-AC:4 has DifferentialDryBulb economizer.  So, the difference in OA fraction is either due to a change in the sizing, and/or a change in the zone load.  I would compare the setpoints coming from the SZRH setpoint managers, and look at the detailed frequency predicted zone loads.

**Comment by amirroth** [comment]
@JasonGlazer, @nealkruis can confirm but I don't think additional tweaks are need to the TimeBins code. I think what is needed is more {aggregation}[units] in the HTML table headings to enable more nuanced diffing.

**Comment by nealkruis** [comment]
@mjwitte I'm guessing you're correct about the path of:
1. Radiation Exchange
2. Surface Temperatures
3. Surface Convection
4. Zone Air Temperature
5. Economizer Differential
6. Outdoor Air Fraction

We could step through the calculations to confirm that that's the case, but I'm not sure that it will tell us much more than we already know: The root of these changes is propagation of minuscule floating point precision differences. Overall, the changes we're looking at have had no **real** impact on the results---just artifacts of floating point comparisons. I still have one other example file to look at, but I suspect I will find a similar phenomenon there. I'll keep people posted.

I am in favor of using "units of hours" for the diffing of time-binning tables. Keep in mind, though, that the differences here are limited by the resolution of the timestep duration. If one of these binning issues happens with hourly timesteps, we'll see a whole hour difference in the results, which might be more concerning in the unmet hours table than it is for time-binning.

**Comment by mjwitte** [comment]
@nealkruis Not suggesting stepping through code, I'm suggesting looking at detailed time-series output to see if there are significant differences in any of the above values which may not be showing simply because they aren't being reported in this example file.

**Comment by nealkruis** [comment]
@mjwitte ah, yes. I used detailed time-series output to track down the culprit 15 minute timestep. Nothing in the other outputs jumped out at me.

**Comment by mjwitte** [comment]
@nealkruis Sorry - not following "the culprit 15 minute timestep"?

**Comment by nealkruis** [comment]
The 15 minute timestep where the diff occurred.

**Comment by JasonGlazer** [comment]
I added "{TIMESTAMP}" not "{TIMESTEP}" which is what I said by mistake in the commit message

**Comment by Myoldmopar** [comment]
Deleted the Mac build failure results so it would come back clean now that @nrel-bot-3 is appearing to have come out of his bad mood.

@amirroth @mjwitte I have sat by watching all this happen, and I've been uncertain if the `{TIMESTAMP}` tag is something we were using specifically to isolate and resolve the diffs, or that is something that the release should include.  If so, we probably need to think about how to document this, because it could be the first output related change that needs to be documented for this release cycle  (#5280).  Let me tag a few people who may have interest in this change: @kbenne @macumber.

Otherwise I guess I don't have a problem with this going in.  Let me know what you think @mjwitte.

**Comment by macumber** [comment]
I didn't really follow all of this thread but this does look concerning to me:

pdchZnClPkTime = newPreDefColumn( pdstZoneClSize, "Date/Time Of Peak {TIMESTAMP}" );

Does this mean that there will be column names that are autogenerated?  We often use column names in our sql queries to find data in tables.  If we don't know the column names a priori, then this could be an issue.

Does this column show up in the E+ SQL output or only in E+ diff reports?

**Comment by amirroth** [comment]
Yes, this change is largely aimed at quarantining "big diff" artifacts in
our continuous-to-discrete mappings like peak value time stamps and time
bins. Although in general having consistent units and aggregation
directives {ANNUAL, MAX, TIMESTAMP} on the tables will help automated tools
(including TableDiff) deal with these outputs. If we are concerned that
these additional outputs would confuse users, we can add a flag to activate
them and then only use them in CI. But I hope that is not necessary.

**Comment by Myoldmopar** [comment]
I think it is probably more just about documenting clearly that we are changing them and ensuring that programs can anticipate the name in a deterministic manner every time that way they can query the table by header text.

**Comment by mjwitte** [comment]
@JasonGlazer @amirroth It would be helpful to see a couple of examples showing how the tables look before and after.

**Comment by JasonGlazer** [comment]
The {TIMESTAMP} descriptor in column headings is not new and has been used for many years to show on the monthly reports what time a maximum or minimum happened. It was not been used consistently for other tabular reports. These changes make the output more consistent. Also, the column headings are just as stable as they ever have been the {TIMESTAMP} is a string and does not indicate anything being autogenerated. I believe that all tables that are in the HTML file also show up in the SQL file so, yes this will impact those tables also. Although because monthly and annual reports are user defined, the column names for those kinds of reports could not be known in advance. 

I think this change would be good for users since it makes columns that are timestamps more easy to parse out. As far as the rounding in the TimeBins report which was the first part of this pull request, I also think that would be good for users that might be seeing little "wobbles" in the TimeBins reports due to rounding of continuous variables.

**Comment by macumber** [comment]
Thanks @JasonGlazer , as long as this is a static string we can deal with it.  I was only concerned if that was a marker that got replaced by a timestamp in the output.  However, it still is good to avoid changing anything if possible.

**Comment by JasonGlazer** [comment]
Here is an example:

capture5

**Comment by Myoldmopar** [comment]
OK, this is good discussion.  And a good point to try to resolve #5280.  I'm going to head over there to try to coerce that to finality through discussion.

**Comment by Myoldmopar** [comment]
OK.  I pulled develop into this branch to get the output file tracking ready.  I added an initial line of description, but will rely on @JasonGlazer to follow up with a better description of where this change can be expected.  I also changed that file to Markdown for easier rendering up here and I updated the README text slightly.

@JasonGlazer if you can update that file with some more detail, this may be ready to drop in.  Then we can move forward on @amirroth's PR.

**Comment by JasonGlazer** [comment]
@Myoldmopar I just updated the new OutputChanges file. Let me know if this was not the level of detail you wanted.

**Comment by Myoldmopar** [comment]
That looks awesome, @JasonGlazer.  And besides, per @macumber, "[Any sort of documentation would be fantastic](https://github.com/NREL/EnergyPlus/pull/5280#issuecomment-155141194)."  

I don't have a strong opinion here, so I am open to this merging in if it is ready per @mjwitte or others.  If I need to have a stronger opinion, I can generate one. :8ball:

**Comment by amirroth** [comment]
Not sure if this is the place to discuss, but one of the things that was
pointed out in the BL Usability Study was the need to communicate I/O
changes to third-party client-app developers in a timely manner. Actually,
what was pointed out was somewhat bigger, but this is a minimal
interpretation. Should we use this change to trial a mechanism or channel
for doing this?

**Comment by Myoldmopar** [comment]
I thought tagging @macumber accomplished that, @amirroth.  ...   .....

Yeah, this is wide open, so it would be great if we got some more eyes on it besides a single app developer to help guide the information flow back to them in a timely manner.  I had hoped just having this file living throughout the development cycle would suffice as a singular place for an app developer to check on upcoming changes.  Do we need additional effort?

**Comment by Myoldmopar** [comment]
@JasonGlazer Yeah, taking out the example is fine.  In the future, when we start a new release cycle, we will have the previous one as an example basis.  This time we didn't.

**Comment by amirroth** [comment]
@Myoldlady, I'm not sure what we need/want to do. At the very least, we
need to proactively point the third-party developers to the I/O change
document(s) and example files. Incrementally, we could engage them in the
proposal/review process for I/O changes. Incrementally on top of that, we
could engage them in the proposal/review process for all changes.

**Comment by Myoldmopar** [comment]
@amirboss Thanks, that makes sense.  If it turns out these input/output change docs are too deep inside the repo and hinder visibility, we can re-org.  For now, we can point them to the files on the Helpdesk and maybe some other places.  ([UH](https://unmethours.com/questions/)?)

**Comment by nealkruis** [comment]
This is a pretty minor change, but I think it would fall under the category of an enhancement. The UserVoice site is the venue where users (including the developers) should be making suggestions, and where implementations of those suggestions can be discussed publicly. 

From a UserVoice entry, we can mark it as "In Design" so that people know it's coming down the pipeline. We can link to this PR, so that people can follow this discussion if they want more details or if they want to see the way the EnergyPlus team mocks each other's user names : ).

**Comment by amirroth** [comment]
1. My user name is mock-proof.
2. I didn't force Edwin to hide behind a ridiculous, obscure handle like
   @myoldmopar. What person that grew up north of the Mason-Dixon line would
   even know what a Mopar is? Although, I grant you, the mental non-image of
   @myoldmopar >>> the mental image of @deadparrot.
3. I was not aware that we were using the UV site in that modality, i.e.,
   as a way to publicly discuss, refine, vet, etc. internally-generated
   features. I guess it makes sense, though. And it would make the UV site
   more useful...

**Comment by DeadParrot** [comment]
@amirroth to help with the image problem and prevent further sullying of my escutcheon I offer this important cultural landmark: 
https://www.youtube.com/watch?v=4vuW6tQ0218

**Comment by amirroth** [comment]
Of course! Mental image revised. Thanks.

**Pull request merged**
