### PR TITLE
GroundDomain Testing

### PR DESCRIPTION
**Pull request by mitchute**
PR for adding/modifying the testing framework and select test cases for the GroundDomain objects.

### CODE REVIEW

**Comment by mitchute** [comment]
@Myoldmopar FYI. The NFP has been added.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @lgentile it has been 14 days since this pull request was last updated.

**Pull request closed without merging**
