### PR TITLE
DHW end use category changed to WaterSystems

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
This PR fixes a couple of issues:
- Fixes issue #10195
- Fixes an early issue #9143 about obsolete `DHW` end use category

Described in an earlier issue #9143, In the IORef documentation the “DHW” is still listed as a type of End Use Category (Output:Meter, Table 5.3). However, in the code there is no such definition (in neither the EndUse `enum` nor the `endUseCategoryNames` string array. At the same time, in the code,  the `DHW` End Use Category is still used in some Variable Setup (e.g. in the Water Heater Tanks and the Heat Pump Water Heater coils).

After some investigation, it is found that the `DHW` type will be finally corrected to be `WaterSystems` in a validation routine here:
https://github.com/NREL/EnergyPlus/blob/b1f909c787c8515c3178692912edfebd51f6a5df/src/EnergyPlus/OutputProcessor.cc#L1828-L1829
This seems to indicate that `DHW` can be processed in the code; but will soon replaced by `WaterSystems` by a validation procedure (`ValidateNStandardizeMeterTitle()’).

Therefore, it is suggested to replace the obsolete `DHW` End Use Category used by some Water Heaters and Heat Pump Water Heat Coils) to the more standard `WaterSystems` from the start. In the IORef description for "Output:Meter",  the “DHW” line should also be removed from the End Use Category Types table (Table 5.3).

This question turned up again when investigating the new InchPoundExceptElectricty unit conversion options; and also in investigating a recent helpdesk Ticket 16412 seemed to have some link on some “Water System – Other” subCategory not reporting numbers correctly. Therefore, it is suggested to do some cleaning and get rid of the potential confusions before going further for the other fixes.

Diffs: CI Diffs could be expected to show up for test files that contains the affected objects, such as “WaterHeater:Mixed”, “Coil:WaterHeating:Desuperheater”, “WaterHeater:HeatPump:PumpedCondenser”, “Coil:WaterHeating:AirToWaterHeatPump:Pumped” , and “Coil:WaterHeating:AirToWaterHeatPump:Wrapped”.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 27 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 12 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Another draft, though this one has conflicts.  @jcyuan2020 just update this appropriately when you are either ready for review, or if you feel like it won't make it for 23.2.

**Comment by jcyuan2020** [comment]
@Myoldmopar From last time, it was the (many) diffs that need to be explained. I will continue a little bit on this---could be a possibility to be included for v23.2.

**Comment by mjwitte** [comment]
@jcyuan2020 I think now that all of @dareumnam 's fueltype PRs are merged, this should have no diffs.

**Comment by Myoldmopar** [comment]
> @jcyuan2020 I think now that all of @dareumnam 's fueltype PRs are merged, this should have no diffs.

So there are a handful of MTD/MDD/Audit diffs, and one file showing big table diffs.  The MTD diffs are a bit tough to analyze, might be easier to show a side-by-side comparison.  The Audit and MDD diffs show a new meter being added.  

Since you expected no diffs, could you advise on the status here?

**Comment by mjwitte** [comment]
@jcyuan2020 The new sub-end-use meters look correct. For example, WaterHeaterHeatPumpWrappedCondenser
```
+ For Meter=General:WaterSystems:Electricity [J], ResourceType=Electricity, EndUse=WaterSystems, contents are:
+  HPWHPLANTDXCOIL:Cooling Coil Crankcase Heater Electricity Energy
+  HPWHPLANTDXCOIL:Cooling Coil Water Heating Electricity Energy
```
If you run this file as a full annual simulation, you can see that there was WaterSystems energy use reported as "Other" (which gets added automatically by the end-use reporting is there's any energy left over after comparing the sum of the sub-end-uses with the totals). With this branch, the Other row is gone and the value has moved to General.
image 
image

So, for some reason, in develop, the General sub-end-use meter is not getting attached to the DX coil. Maybe you can track this in the debugger and explain why this behavior has changed.

**Comment by Myoldmopar** [comment]
I marked it as 23.2 and "waiting on developer," but feel free to update this if it's not going to be ready, or if I am misinterpreting the requested investigation, @mjwitte or @jcyuan2020

**Comment by jcyuan2020** [comment]
Thanks! @Myoldmopar

**Comment by jcyuan2020** [comment]
@mjwitte Thanks for the comments! I am able find the root cause on why the DX coil missed placing it into the "General" end use subcategory---it is a little bit subtle issue here that at a point the "EndUse" should have been "corrected" from the various "alias" in order to make a default assignment to "General" correctly. I will post some more comments about this issue.

On the other hand, the above statement also further supports that here "DHW" should no longer be used as an "alias" in the code to make the meters behavior as expected.

Also, it is confirmed that the energy listed in `Other` subcategory under `WaterSystem` should get into `General` in this case---So the table diffs are able to be explained now.

**Comment by Myoldmopar** [comment]
OK, with the diffs explained, I think this is ready to go.  I will hold briefly in case someone wants to further comment/scrutinize, but otherwise I'll get this in and we can always continue fixing it later.

**Comment by Myoldmopar** [comment]
I'll verify this is still fine with latest develop and if so, merge.

**Comment by Myoldmopar** [comment]
Everything is good with develop pulled in, this is merging.  Thanks @jcyuan2020 and @mjwitte

**Pull request merged**
