### PR TITLE
Refactoring Plant Components

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
This continues the refactor of plant components to use the new PlantComponent interface.  The idea is to get effectively no diffs, though some diffs due to different calling sequences may cause tiny diffs or different row ordering in the tabular output.  The specific components being refactored in this branch will depend on how the diffs come about.  As long as the diffs are easy to justify, more components will be added, but once they become unwieldy, a new branch will be started to continue refactoring.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
The diffs from 846a4a8 are as follows:

- 3 files _fail_ regressions because of large table diffs - these are all just reordered rows in the tabular output, no results actually changed
- 1 file had meter small diffs, GSHPSlinky - the actual difference is on the order of E-07 joules
- RDD, MTD, MDD, BND diffs are all expected due to reordering

So far so good, I'll keep continuing on with other components here in this branch.

**Comment by Myoldmopar** [comment]
Next up HeatPumpWaterToWaterHEATING.cc.

**Comment by nrel-bot-2** [comment]
@Myoldmopar it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Closing, replaced with #7325

**Pull request closed without merging**
