### PR TITLE
Fix radiation variable outputs

### LINKED ISSUE #7706: Horizontal Infrared Radiation variable outputs 9999
Issue overview
--------------
Setting the Infrared Sky Radiation column in the weather file to zero results in value of 9999 being written out the Site Horizontal Infrared Radiation Rate per Area output variable.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ajscimone**
Pull request overview
---------------------
 - Fixes #7706
 - This pull request fixes the output from the weather manager to the "Site Horizontal Infrared Radiation Rate per Area" field in the output csv file. Instead of outputting a default value of 9999.0 which is a value given arbitrarily when no input is given in the weather file, this code will calculate a virtual infrared radiation and output this instead. This gives the user a value which provides insights into their weather conditions as opposed to filling a column with a useless value in the output csv.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2b** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nealkruis @ajscimone it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@nealkruis @ajscimone it has been 7 days since this pull request was last updated.

**Comment by mitchute** [comment]
@ajscimone do you have an example weather file you can point me to?

**Comment by ajscimone** [comment]
@mitchute I believe the attached file was the original weather file that the issue was found on.
[in-zero.epw.zip](https://github.com/NREL/EnergyPlus/files/4645488/in-zero.epw.zip)

You can also use the `/tst/EnergyPlus/unit/WeatherManagerIROutputTest.epw` weather file included in this PR. We got some feedback from the team recently that files like this should be moved to a "Resources" folder, so I have just done that. It is now in `/tst/EnergyPlus/unit/Resources/WeatherManagerIROutputTest.epw`. Hope that helps!

**Comment by nealkruis** [comment]
@mitchute Notice that this PR is unit tests only because the new sky temperature models feature resolved this at the same time we were working on it. i.e., the bug was already fixed in developed and we decided we might as well contribute the unit tests we wrote.

**Comment by mitchute** [comment]
I merged in develop locally and ran unit tests successfully. The fix was confirmed (even though it's already been merged in) by rolling back to v9.2 and making sure the horizontal radiation output comes out in the CSV rather than just a useless 99999 value.

@Myoldmopar should I merge now or wait for CI?

**Comment by Myoldmopar** [comment]
Ummm, that's a pretty big set of test failures.  Since CI is finally super clean and running well let's just let CI take a full pass and merge as soon as it's done.

**Comment by ajscimone** [comment]
It's probably because I pushed before I merged the current version of develop. That's my fault. I made a second push with develop merged. The next CI run should come back clean.

**Comment by Myoldmopar** [comment]
Sounds great.  CI is running much faster now so this should be able to merge this afternoon/evening.

**Comment by mitchute** [comment]
Failures due to the mtr files are not related to this work, and the labels warning looks like a false positive. Merging.

**Comment by mitchute** [comment]
Does this PR still show "Open" on the main PR list for anyone else? It's been merged. I first thought it was a browser caching issue, but after clearing that it still shows that it's open.

**Comment by mjwitte** [comment]
@mitchute Shows "Merged" for me. Maybe the data is running a bit slow in that thin Colorado air.

**Comment by mitchute** [comment]
NOW it shows closed. GitHub is just messing with me :suspect:

**Pull request merged**
