### PR TITLE
Fixes crash when duplicate node names are used in zone connections object

### PR DESCRIPTION
**Pull request by JasonGlazer**
This is to fix Github issue #4577 , Pivotal #84202670. Change to a single line of code that is part of a error message so it is only executed when the error condition occurs. Thanks to LKL for identifying the problem code.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte Added a unit test.

**Comment by Myoldmopar** [comment]
@JasonGlazer This is a good fix, and the unit test looks great.  I made a commit just to clean up a whitespace change, and I'll let CI make a pass through then merge it in.

**Comment by JasonGlazer** [comment]
These CI tests that have failed don't seem be related to the changes in the source files. Could this be from other changes in the source?

**Comment by mjwitte** [comment]
@JasonGlazer To get a clean test, you'll need to merge from develop into this branch.  In tortoisegit, switch to develop, pull, switch back to this branch, merge (from develop into this branch). Hopefully it merges without any conflicts.

**Comment by JasonGlazer** [comment]
Hopefully I merged it properly. It took me two times since the first time it did not have @Myoldmopar whitespace padding.

**Pull request merged**
