### PR TITLE
Updates to ObjexxFCL and 2+D arrays for row-major

### PR DESCRIPTION
**Pull request by Myoldmopar**
This passes my test suite with only a few _small_ diffs.  I will merge shortly.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Nice, CI and I found the exact same diffs.  That's great news.

**Comment by mjwitte** [comment]
@Myoldmopar Interesting that the diffs all come from ground heat transfer files.

**Comment by amirroth** [comment]
The word you are looking for is ironic.

**Comment by Myoldmopar** [comment]
@mjwitte (@amirroth), so I think the reason is because when I had written the piping system manager code, I had switched the loop so it was similar to:

```
for Z = 1, numZ
  for Y = 1, numY
    for X = 1, numX
```

which gave me the best performance in FORTRAN for then operating on the A(X,Y,Z) matrix.  In these changes, @DeadParrot changed the indexing so that it goes through them in the X, Y, Z order instead.  This simply changes the convergence slightly each iteration, which is why it is causing small diffs and not big diffs.  The results aren't different in a meaningful way.  My code was probably in the minority (the only one...?) for going Z-Y-X in the code, which is why no other diffs are showing up.

Does that sound right @DeadParrot?

**Comment by amirroth** [comment]
A likely story.

**Comment by DeadParrot** [comment]
This makes sense. Only arrays where I reverted the index flip (for a more natural usage) would be accessing elements in a different order than before, thus an accumulation can have (typically small) diffs. In cases where I reverted the index order (there were a couple of others so far) I would normally also invert the looping order unless it was unnecessarily in a cache-unfriendly order before.

**Pull request merged**
