### PR TITLE
NFP for Error Enhancement

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
New feature proposal for the error enhancement feature.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 11 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 35 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 23 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 11 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Merging this in as an NFP, it could be taken to design/implementation at any later date.

**Pull request merged**
