### PR TITLE
Sundry Fixes

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
Adding in some items from my personal to do list.  

First is better protection and clearer error messaging for the check_pr_labels script.  I'll make this PR, re-run custom_check without labeling it, and get a warning.  Then I'll add the label and re-run custom_check and get it green again.  -- This all worked well if you look through the CI responses below.

This also addresses #7248, some post 9.1 cleanups that were requested.

This is also going to include fixes for #4888, ensuring Python cross version compatibility.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
For the Python changes, this table will be updated as I go.  The status will be one of:

- :grey_question: Untested
- :heavy_check_mark: Success, which indicates that the file runs with both Python 2 and 3
- :bangbang: Failed, which indicates the file currently does not run with either 2 or 3, with notes
- :information_source: Removed, which indicates the file was not needed anymore and removed from the repo in this branch
- :information_source: Some other status, like the file is old and we won't maintain it but it can still live here

| Python Script Path                                             | Python Compatibility Status         | Notes |
|----------------------------------------------------------------|----------------|-------|
| ./doc/tools/example_file_objects.py                            | :heavy_check_mark: Success       |       |
| ./doc/tools/make_pdfs.py                                       | :information_source: Removed        |       |
| ./doc/tools/idd_parser_library.py                              | :heavy_check_mark: Success       | Indirectly through example_file_objects.py      |
| ./doc/tools/idf_summary_class.py                               | :heavy_check_mark: Success       | Indirectly through example_file_summary.py      |
| ./doc/tools/idf_parser_library.py                              | :heavy_check_mark: Success       | Indirectly through example_file_objects.py      |
| ./doc/tools/make_html.py                                       | :information_source: Removed        |       |
| ./doc/tools/parse_output_variables.py                          | :heavy_check_mark: Success       |       |
| ./doc/tools/example_file_summary.py                            | :heavy_check_mark: Success       |       |
| ./doc/tools/create_changelog.py                                | :heavy_check_mark: Success       |       |
| ./doc/tools/parse_ems_actuators.py                             | :heavy_check_mark: Success       |       |
| ./scripts/dev/check_non_utf8.py                                | :heavy_check_mark: **FIXED**       |       |
| ./scripts/dev/make_pretty.py                                   | :information_source: Removed       |       |
| ./scripts/dev/license-check.py                                 | :heavy_check_mark: Success       |       |
| ./scripts/dev/clear_coverage_results.py                        | :heavy_check_mark: Success       |       |
| ./scripts/dev/179D_Generate_Index.py                           | :information_source: Removed       |       |
| ./scripts/dev/licensetext.py                                   | :heavy_check_mark: **FIXED**       |       |
| ./scripts/dev/gen...ema/generate_epJSON_schema.py | :heavy_check_mark: Success       |       |
| ./scripts/dev/gen...ema/modify_schema.py          | :heavy_check_mark: Success       | Indirectly through gener..ema.py      |
| ./scripts/dev/gen...ema/idd_parser.py             | :heavy_check_mark: Success       | Indirectly through gener..ema.py      |
| ./scripts/dev/verify_idfs_in_cmake.py                          | :heavy_check_mark: Success       |       |
| ./scripts/dev/transition_run_check.py                          | :information_source: Removed        |       |
| ./scripts/dev/validate_idd_units.py                            | :heavy_check_mark: **FIXED**      | Added to custom_check     |
| ./scripts/dev/check_stray_fields_in_idd.py                     | :heavy_check_mark: Success       |       |
| ./scripts/dev/verify_file_encodings.py                         | :heavy_check_mark: Success       |       |
| ./scripts/dev/check_pr_labels.py                               | :heavy_check_mark: **FIXED**       |       |
| ./scripts/dev/change_version.py                                | :heavy_check_mark: **FIXED**       |       |
| ./scripts/dev/license-update.py                                | :heavy_check_mark: **FIXED**       |       |
| ./src/Transition/transition_coil_heating_gas.py                | :information_source: Old-Irrelevant |       |

**Comment by Myoldmopar** [comment]
OK, well [that](https://github.com/NREL/EnergyPlus/pull/7309#issuecomment-496757975) was fun!  As far as I can tell, we now have **full** Python 2/3 compatibility in all of the relevant (and even irrelevant really) Python scripts in our repo.  I tested them all out as best I could and fixed a bunch of them along the way.  I'll probably call this PR a wrap now once CI gets all done with the last commit there (b73e3ce).

**Comment by Myoldmopar** [comment]
Since I added the `validate_idd_units` script to custom_check, it is now properly reporting that there are two unit issues in the IDD.  I'll fix them like this:

- Make the units "rpm"
- Add it to the list of unconverted units at the top of the idd 
- Add it to the standard units in the I/O Ref.  
- Fix "  A8 ,  \field Pump *RPM* Schedule Name"

@JasonGlazer any additional thoughts?

**Comment by JasonGlazer** [comment]
@Myoldmopar there is already a rev/min unit in the unconverted section that is used for motors and compressors. I would just use that instead of the "Rotations Per Minute" in those two places.

**Comment by JasonGlazer** [comment]
Also, I noticed that the validate_idd_units.py script has two units in an ignore list 

`ignore_list = ["hh:mm", "kgWater/kgDryAir"]
`

These should probably just be added to the top of the IDD.

**Comment by Myoldmopar** [comment]
OK, I am taking @mjwitte's advice and fixing field A8, just the casing of rpm -> RPM.  I am then taking @JasonGlazer's advice and using the existing rev/min as the units type, and then moving the ignored units from the validation script directly into the IDD.  Let me know if these changes are still lacking.  As far as I can tell, this branch should be ready to go in now with all these cleanups.

**Comment by Myoldmopar** [comment]
OK, this is all cleaned up, I'm merging it in and moving on.

**Pull request merged**
