### PR TITLE
design document for advanced BIPVT model

### PR DESCRIPTION
**Pull request by khaddad**
Design document for advanced BIPVT model in E+

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@khaddad it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@khaddad it has been 7 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@khaddad Sorry for the delay in reviewing this proposal. For the most part this looks very good. 

My only comments at this point would be to modify some of the field names (and as this develops, we might want to tweak those again):
Field 4: Effective Plenum Gap Thickness Behind PV Modules
Field 7: PV Module Normal Transmittance-Absorptance Product
Field 10: PV Module Top Thermal Resistance
Field 11: PV Module Bottom Thermal Resistance
Field 12: PV Module Thermal(?) Emissivity
Field 13: Backing Material Thermal(?) Emissivity

**Comment by nrel-bot-2b** [comment]
@khaddad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@khaddad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@khaddad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@khaddad it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@khaddad @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
This seems to have gone dormant.  I'm going to close the PR, but feel free to just click re-open whenever.

**Pull request closed without merging**
