### PR TITLE
Enable usage of ccache and ninja

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Enables usage of [ccache](https://ccache.samba.org/) and the [Ninja Generator](https://ninja-build.org/), and add color output when building with Ninja. **This PR only modifies CMakeLists.txt** and nothing else.

Changes perceived by the user:
* If ccache is installed on the user's machine, use it
    * Note: ccache can be used both with `make`, or with `ninja`.
* If you have installed ninja and you specify `ccmake -G Ninja path/to/EnergyPlus` then `ninja` is used as a generator, and you can build using `ninja` (uses all available threads by default) instead of  `make -jXX`

**This means that unless you have installed ccache (that means you're on Unix and not windows), or installed AND explicitly chosen ninja, you'll just keep building using make and no ccache like you did before and won't notice any difference**.

I had done a similar PR for OpenStudio [here](https://github.com/NREL/OpenStudio/pull/2847) which got merged in. This has been speeding up my build time quite a lot. The first build is a bit slower (builds the cache), but when rebuilding or even switching branches (unless you have an IDD change of course...) it goes much much faster. This is especially true for OpenStudio because the project is a **lot** heavier, but I figured E+ might benefit from it.

This time I actually benchmarked (on a single Ubuntu machine, granted) for three configurations:
* standard make
* make + ccache
* ninja + ccache

For each, I ran three scenarios: 
* clean (first-time) build of develop
* merge CBVAVFix6544 into develop, then rebuild (=minor change scenario)
* subsequently merge json_followup, then rebuild (=major change scenario)

all builds are configured with: `BUILD_TYPE=DEBUG`. Enabled options: `BUILD_TESTING`, `BUILD_FORTRAN`, `CMAKE_EXPORT_COMPILE_COMANDS`
All ran either with `time make -j14` or `time ninja -j14` to ensure I have the same number of threads are used.

Here are the results. Note that all % as calculated as compared to the "make-only" scenario, and the time numbers are in seconds.

image

Side Note: if you aim to also build fortran when using Ninja, you will need to install the Kitware binaries for now: https://github.com/Kitware/ninja/releases

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@jmarrec Thanks for offering this contribution; we'll evaluate it after our release of 8.9.0, which we're trying to get out the door this week.  It looks like this branch is now nice and clean on CI.  If you have further commits to push, if you could hold off until after we lock down the code, that would be great.  We are trying to keep our CI focused on the final branches to get 8.9.0 out the door right now.  Thanks!

**Comment by jmarrec** [comment]
@Myoldmopar I don't have anything else to push, but if it happens, I will wait.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 23 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 8 days since this pull request was last updated.

**Comment by jmarrec** [comment]
@Myoldmopar Merged develop in, and resolved conflicts. Would be great if this could be finally reviewed.

Really this shouldn't make much change, since unless you specifically use `cmake -G Ninja ...` it would keep using the regular generator. Also, the ccache thing, unless you have it specifically installed on your machine it wouldn't be used (but if used, it's a well tested thing!).
I've been building OpenStudio with the same settings for more than a year, and EnergyPlus with ninja and ccache since I opened this PR without any kind of problems.
 (The only thing worth mentioning if someone wants to use Ninja AND build fortran is to download the kitware binaries like I said in the OP)

**Comment by Myoldmopar** [comment]
Tested this again locally with ccache installed and it looks good.  Merging this in.  Thanks @jmarrec and sorry for the delay getting this in.

**Pull request merged**
