### PR TITLE
Remove `using namspace *` in cpgfunction headers

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - A more minimal version of https://github.com/NREL/EnergyPlus/pull/8998 to address strange build errors and test failures.
 - Removes OpenMP CMake warning
 - Fixes bug where `numThreads` was not being passed through from the CLI

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I wish Linux had already run on this, I'm hesitant to merge until I verify CI is happy.  I guess it's just that the PR list is rapidly back up to 67 and it can't really seem to keep up.  Anyway, I'll hold off for now and see if it catches up on this this morning, and if not I'll test on my own 18.04 instance and then merge.

**Comment by mitchute** [comment]
I built and ran unit tests yesterday on a Linux 18.04 machine, FWIW.

**Comment by Myoldmopar** [comment]
Built and ran fine here.  I'm going to take the small risk and get this merged in.  Worst case is CI has an issue that I have to resolve this afternoon.  But who knows exactly when CI will get around to this branch.  Anyway, thanks @mitchute, and thanks @mbadams5 for starting this cleanup.

**Comment by mitchute** [comment]
@j-c-cook FYI

**Pull request merged**
