### PR TITLE
Use correct argument to calculate hg in AirflowNetwork

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
This fix is based on #7844, which should be merged first. The main issue is to ensure that a sum of sensible and latent loads is equal to the enthalpy difference between two points, either a zone and outdoor or two adjacent two zones.

The fix is divided into 2 sections.

1. Infiltration

Outdoor W is used to calculate Cp, and zone temperature is used to calculate hg.

2. Air flow between two adjacent zones

The average W between two zones is used to calculate Cp, and the average zone air temperature is used to calculate hg. 

The test file of #7844 can be used for this issue. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@lgu1234 @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@lgu1234 the changes here have conflicts with the other `hg` changes.  Can you merge in latest develop and resolve those conflicts?  They are likely pretty straightforward, especially since you made both sets of changes.

**Comment by lgu1234** [comment]
@Myoldmopar I am going to solve conflicts.

**Comment by Myoldmopar** [comment]
This seems fine to me, diffs are tiny, unit test is fine.  I'm going to build this locally with develop since I just merged the other branch but if it runs fine I'll merge this next.

**Comment by Myoldmopar** [comment]
Everything looks good locally, merging away.  Thanks @lgu1234

**Pull request merged**
