### PR TITLE
Fix IDFVersionUpdater LST files on MacOS and Linux

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
- Continues fixes from #9283 
- Fixes for MacOS and Linux so that LST files can be used.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — COMMENTED** [review]
Tested on Windows (10). Updated several v9.4 files using a lst file, ran them all in v22.1. Then did the same with a group of mixed files from various older versions. All good.

**Comment by JasonGlazer** [comment]
@mjwitte thanks for testing this.

**Comment by mjwitte** [comment]
@JasonGlazer Is this ready to merge? I tested on Windows.
@mitchute Did you test on Mac?
Has anyone tested on Linux?

**Comment by JasonGlazer** [comment]
@mjwitte I tried it only on VM's for Linux and MacOS. Matt was going to test it on a real Mac but I don't think any real Linux testing was done. That said, it should be ready to merge.

**Comment by mitchute** [comment]
I tested it on macOS 10.15 and 11.6. My 10.15 NREL computer needed me to copy the files out of the /Applications folder, but I think that's just NREL IT trying to protect us from being productive. My 11.6 computer worked fine, but the picture in the icon didn't show up. I don't think either of these indicates a problem with the actual functionality of the updater.

**Comment by mjwitte** [comment]
That's enough testing for me. Merging.

**Pull request merged**
