### PR TITLE
Fix typo in test files CMake list

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
Fix typos in test files cmake list.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [X] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Nice.  Is this actually draft?  If not, I'll merge as soon as CI comes back (almost certainly) clean.

**Comment by lymereJ** [comment]
Well, I'm expecting some diffs (based on what I saw on another branch) so I was waiting for that.

**Comment by Myoldmopar** [comment]
OK, yeah, that makes sense.  It will use a different EPW file.  But honestly...those diffs are going to be fully understandable.  So even when they show up, I don't think we need to do anything.  Unless I'm missing something...

**Comment by lymereJ** [comment]
Ok, that sounds good to me. Not a draft anymore.

**Comment by Myoldmopar** [comment]
Yes, this has diffs.  Yes, we are using a different weather file for these tests.  So yes, diffs will happen.  There's nothing that needs investigation.  Thanks for noticing and fixing this @lymereJ, merging.

**Pull request merged**
