### PR TITLE
Documentation Corrections for V24.2

### LINKED ISSUE #9972: Documentation 2023-2024
A place to keep an ongoing list of documentation issues.

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #9972 
 - This defect corrects a variety of documentation issues over the last 15 months.  All issues were corrected that were noted on the defect description as well as a few others that were noticed while fixing these problems.  One input file was changed to trigger a particular output report for the hybrid model.  No unit tests as this is a documentation only defect.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@RKStrand I added the tiny request from @mjwitte.  Built it locally and everything is happy.  I'm going to merge before CI wastes cycles building this.  Thanks!

**Comment by Myoldmopar** [comment]
Oh wait....I didn't even realize what happened.  You had already made that change, my push was rejected, but it's all fine!

**Comment by RKStrand** [comment]
I just made the change and pushed it not realizing you were going to do this separately.  Not sure how to resolve this, but I'm trusting if I stop and don't touch anything after that last tiny fix commit, you'll get it all tied up.  Sorry that I didn't check my email.  I had stepped away from my computer while it was building the PDF and totally missed the notification from GitHub coming in.

**Comment by mjwitte** [comment]
@RKStrand @Myoldmopar Sorry to cause trouble with that untimely addition!

**Comment by RKStrand** [comment]
Well, on the plus side, everyone is hard at work on a Friday! 🤣

**Pull request merged**
