### PR TITLE
Convective Baseboard Crashing in Sizing Routine When Autosizing is Not Requested

### LINKED ISSUE #10677: Simulation crashes in SizeBaseboard because SetUpZoneSizingArrays was never called
Issue overview
--------------

After getting the defect file from https://github.com/NREL/EnergyPlus/issues/10665 which does run in 24.1, I transitionned it to 24.2 (no real change in the idf format for that matter), but now it crashes due to an array being accessed while not allocated.

```
lldb $ep_build/Products/energyplus -- -w G3400350.epw -d out-ori in.idf
```

```
Process 2278848 exited with status = 9 (0x00000009) killed
Process 2279619 launched: '/home/julien/Software/Others/EnergyPlus-build/Products/energyplus' (x86_64)
EnergyPlus Starting
EnergyPlus, Version 24.2.0-f274ccbcef, YMD=2024.08.21 15:20
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Process 2279619 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGABRT
    frame #0: 0x00007fffe63f800b libc.so.6`__GI_raise(sig=<unavailable>) at raise.c:51:1
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGABRT
  * frame #0: 0x00007fffe63f800b libc.so.6`__GI_raise(sig=<unavailable>) at raise.c:51:1
    frame #1: 0x00007fffe63d7859 libc.so.6`__GI_abort at abort.c:79:7
    frame #2: 0x00007fffe6693ee6 libstdc++.so.6`___lldb_unnamed_symbol7360 + 96
    frame #3: 0x00007fffe66a5f8c libstdc++.so.6`___lldb_unnamed_symbol7814 + 12
    frame #4: 0x00007fffe66a5ff7 libstdc++.so.6`std::terminate() + 23
    frame #5: 0x00007fffe66a6258 libstdc++.so.6`__cxa_throw + 72
    frame #6: 0x00007fffe66972a7 libstdc++.so.6`___lldb_unnamed_symbol7525 + 40
    frame #7: 0x00007fffece6cff6 libenergyplusapi.so.24.2.0`std::__cxx1998::vector<EnergyPlus::DataSizing::ZoneSizingData, std::allocator<EnergyPlus::DataSizing::ZoneSizingData>>::_M_range_check(this=0x0000555556e89e18 size=0, __n=0) const at stl_vector.h:1073:28
    frame #8: 0x00007fffece6c0bc libenergyplusapi.so.24.2.0`std::__cxx1998::vector<EnergyPlus::DataSizing::ZoneSizingData, std::allocator<EnergyPlus::DataSizing::ZoneSizingData>>::at(this=0x0000555556e89e18 size=0, __n=0) at stl_vector.h:1094:16
    frame #9: 0x00007fffece6ac0a libenergyplusapi.so.24.2.0`EnergyPlus::EPVector<EnergyPlus::DataSizing::ZoneSizingData>::operator[](this=0x0000555556e89e00, n=0) at EPVector.hh:79:34
    frame #10: 0x00007fffece695a8 libenergyplusapi.so.24.2.0`EnergyPlus::EPVector<EnergyPlus::DataSizing::ZoneSizingData>::operator()(this=0x0000555556e89e00, n=1) at EPVector.hh:90:23
    frame #11: 0x00007fffedcf46f2 libenergyplusapi.so.24.2.0`EnergyPlus::BaseboardRadiator::BaseboardParams::SizeBaseboard(this=0x0000555555f60910, state=0x00007fffffffab30, baseboardNum=1) at BaseboardRadiator.cc:627:107
    frame #12: 0x00007fffedcf39ac libenergyplusapi.so.24.2.0`EnergyPlus::BaseboardRadiator::BaseboardParams::InitBaseboard(this=0x0000555555f60910, state=0x00007fffffffab30, baseboardNum=1) at BaseboardRadiator.cc:536:32
    frame #13: 0x00007fffedcee6a5 libenergyplusapi.so.24.2.0`EnergyPlus::BaseboardRadiator::SimBaseboard(state=0x00007fffffffab30, EquipName="UNIT1_BOILER_BASEBOARD", ControlledZoneNum=1, FirstHVACIteration=true, PowerMet=0x00007fffffff9620, CompIndex=0x0000555558b6a648) at BaseboardRadiator.cc:146:36
    frame #14: 0x00007fffedb3dfc5 libenergyplusapi.so.24.2.0`EnergyPlus::ZoneEquipmentManager::SimZoneEquipment(state=0x00007fffffffab30, FirstHVACIteration=true, SimAir=0x000055555573add8) at ZoneEquipmentManager.cc:3754:48
    frame #15: 0x00007fffedb142bc libenergyplusapi.so.24.2.0`EnergyPlus::ZoneEquipmentManager::ManageZoneEquipment(state=0x00007fffffffab30, FirstHVACIteration=true, SimZone=0x000055555573addb, SimAir=0x000055555573add8) at ZoneEquipmentManager.cc:160:25
    frame #16: 0x00007fffee737141 libenergyplusapi.so.24.2.0`EnergyPlus::HVACManager::SimSelectedEquipment(state=0x00007fffffffab30, SimAirLoops=0x000055555573add8, SimZoneEquipment=0x000055555573addb, SimNonZoneEquipment=0x000055555573addc, SimPlantLoops=0x000055555573adda, SimElecCircuits=0x000055555573add9, FirstHVACIteration=0x00007fffffff99f5, LockPlantFlows=false) at HVACManager.cc:1771:50
    frame #17: 0x00007fffee72bb66 libenergyplusapi.so.24.2.0`EnergyPlus::HVACManager::SimHVAC(state=0x00007fffffffab30) at HVACManager.cc:824:25
    frame #18: 0x00007fffee724fb1 libenergyplusapi.so.24.2.0`EnergyPlus::HVACManager::ManageHVAC(state=0x00007fffffffab30) at HVACManager.cc:269:12
    frame #19: 0x00007fffee90de94 libenergyplusapi.so.24.2.0`EnergyPlus::HeatBalanceAirManager::CalcHeatBalanceAir(state=0x00007fffffffab30) at HeatBalanceAirManager.cc:4899:32
    frame #20: 0x00007fffee8c7753 libenergyplusapi.so.24.2.0`EnergyPlus::HeatBalanceAirManager::ManageAirHeatBalance(state=0x00007fffffffab30) at HeatBalanceAirManager.cc:168:23
    frame #21: 0x00007fffeea2eaa9 libenergyplusapi.so.24.2.0`EnergyPlus::HeatBalanceSurfaceManager::ManageSurfaceHeatBalance(state=0x00007fffffffab30) at HeatBalanceSurfaceManager.cc:171:48
    frame #22: 0x00007fffee961a4c libenergyplusapi.so.24.2.0`EnergyPlus::HeatBalanceManager::ManageHeatBalance(state=0x00007fffffffab30) at HeatBalanceManager.cc:208:33
    frame #23: 0x00007fffed411e08 libenergyplusapi.so.24.2.0`EnergyPlus::SimulationManager::SetupSimulation(state=0x00007fffffffab30, ErrorsFound=0x00007fffffffa8a3) at SimulationManager.cc:1885:30
    frame #24: 0x00007fffed3fb93b libenergyplusapi.so.24.2.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffffab30) at SimulationManager.cc:271:24
    frame #25: 0x00007fffec841228 libenergyplusapi.so.24.2.0`RunEnergyPlus(state=0x00007fffffffab30, filepath="") at EnergyPlusPgm.cc:419:56
    frame #26: 0x00007fffec83f9a4 libenergyplusapi.so.24.2.0`EnergyPlusPgm(args=size=6, filepath="") at EnergyPlusPgm.cc:242:25
    frame #27: 0x0000555555604015 energyplus`main(argc=6, argv=0x00007fffffffc208) at main.cc:60:25
    frame #28: 0x00007fffe63d9083 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:54:1), argc=6, argv=0x00007fffffffc208, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffc1f8) at libc-start.c:308:16
    frame #29: 0x0000555555603e3e energyplus`_start + 46
(lldb) f 11
frame #11: 0x00007fffedcf46f2 libenergyplusapi.so.24.2.0`EnergyPlus::BaseboardRadiator::BaseboardParams::SizeBaseboard(this=0x0000555555f60910, state=0x00007fffffffab30, baseboardNum=1) at BaseboardRadiator.cc:627:107
   624 	
   625 	            if (state.dataSize->CurZoneEqNum > 0) {
   626 	                auto &zoneEqSizing = state.dataSize->ZoneEqSizing(state.dataSize->CurZoneEqNum);
-> 627 	                auto const &finalZoneSizing = state.dataSize->FinalZoneSizing(state.dataSize->CurZoneEqNum);
   628 	                bool FlowAutoSize = false; // Indicator to autosizing water volume flow
   629 	
   630 	                if (this->WaterVolFlowRateMax == DataSizing::AutoSize) {
(lldb) p state.dataSize->FinalZoneSizing
(EnergyPlus::EPVector<EnergyPlus::DataSizing::ZoneSizingData>) {
  std::__debug::vector<EnergyPlus::DataSizing::ZoneSizingData, std::allocator<EnergyPlus::DataSizing::ZoneSizingData> > = size=0 {}
  m_allocated = false
}
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): develop, f274ccbcef211face33328309188b29b36fd0668

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/10000s/10665
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #10677 
 - A user found that for an input file that had a convective baseboard in it that there was a hard crash.  This hard crash was traced back to a line in a sizing subroutine that assumed that certain data structures were already allocated.  Oddly, this user's file did not request that the baseboard by autosized.  It was eventually determined that the MySizeFlag is initialized to true and never reset when autosizing is not requested like in this user input file.  With MySizeFlag still set to true, the sizing routines in the convective baseboard unit were called as a result of MySizeFlag being true.  Since autosizing was not requested elsewhere in the file either, none of the sizing arrays were allocated, leading to the problem.  This fixes this issue by resetting the MySizeFlag to false in the convective baseboard data structure when no autosizing is requested.  This avoids then the call to the sizing routine since it does not need to be executed and thus also the referencing of data structures that have not been allocated.  The solution tests all three inputs that could be autosized in the convective baseboard unit to see if any autosizing condition is met.  If not, MySizeFlag is set to true.  This test is done during the reading of the input to avoid it being called more than once.  A unit test verifying the correct operation of the new subroutine is included in this pull request.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — CHANGES_REQUESTED** [review]
@RKStrand This fixes the defect file, but it still doesn't protect against trying to size without sizing active.
e.g. Take the user file and change the heating capacity to "autosize" - vector crash.
Take the user file and leave the baseboard hardsized, but change the fan to autosize:
```
   ** Severe  ** For autosizing of Fan:SystemModel UNIT1_ROOM_AC_SUPPLY_FAN, a system sizing run must be done.
   **   ~~~   ** The "SimulationControl" object did not have the field "Do System Sizing Calculation" set to Yes.
   **  Fatal  ** Program terminates due to previously shown condition(s).
 ```
So something is still missing in the baseboard sizing to check if sizing is active. @rraustad probably knows this by heart.

**Comment by rraustad** [comment]
From the defect description, the FinalZoneSizing array won't exist if there is no sizing run:

    auto const &finalZoneSizing = state.dataSize->FinalZoneSizing(state.dataSize->CurZoneEqNum);

because those arrays are allocated in this call:

    if (state.dataGlobal->ZoneSizingCalc) {
        SizeZoneEquipment(state);

That line should be moved down to after this check, for the places it's needed, and this check should be in all the correct places because it may be that only 1 input is autosized. If the flag this->MySizeFlag does actually work correctly then this check could be the first thing that happens (because you know that this zone equipment needs to be autosized) and only have to do it once, but that's risky if that flag is not set correctly.

    CheckZoneSizing(state, cCMO_BBRadiator_Water, this->EquipID);

**Comment by Myoldmopar** [comment]
OK, so this still needs some work, I'm going to just move on from this for now.

**Comment by RKStrand** [comment]
Thanks for the feedback, @mjwitte and @rraustad.  I will look into this as soon as possible and will let you know when I have hopefully resolved this.

**Comment by RKStrand** [comment]
I believe that the flag will now be set correctly based on the user input for this object.  However, as @mjwitte pointed out, the file will crash in its current form if you set any of the three key input parameters to autosize.  The file (I think this is a contradiction when you set one of those inputs to autosize without doing other things) says "NO" to zone sizing.  If you want a piece of zone equipment sized, shouldn't you have to actually tell E+ that you are sizing it?  I think that is what @rraustad is pointing out.  The question now is what to do about it.

Here is what I propose: in the new subroutine which checks for the presence of things that are autosized, also check to see if the user has requested zone sizing (state.dataGlobal->DoZoneSizing = true), then everything should be fine and other existing checks will weed out any other problems.  However, if DoZoneSizing is false but one of the baseboard parameters is autosize, send a severe/fatal stating that in order to autosize a baseboard unit that flag in the SimulationControl input must be set to "Yes" and other inputs need to be set properly.

Would this address the concern here, assuming that the correct checks are being made (I think they are) for autosizing baseboard inputs?

**Comment by rraustad** [comment]
@RKStrand CheckZoneSizing is the call that does the check you suggest and SizeBaseboard is already set up to do that. It's just that the FinalZoneSizing shortcut is set before that check. I guess it makes no difference if CheckZoneSizing is called from GetBaseboardInput or SizeBaseboard (like all other models in E+). Your choices are to move the shortcut for FinalZoneSizing below the call to CheckZoneSizing, or call CheckZoneSizing from the new function in GetBaseboardInput and delete all the calls to CheckZoneSizing in SizeBaseboard.

**Comment by RKStrand** [comment]
I have just made a commit that should fix the issue that @mjwitte noted using one of the methods that @rraustad recommended.  Hopefully, this addresses the concerns and still comes back green.  I went with doing the CheckZoneSizing from the new subroutine and getting rid of all of the other calls.  That seemed to me to be more "efficient" and clearer though different from some other models.

**Comment by Myoldmopar** [comment]
@RKStrand I'm not sure if you saw or not, but this has got 3 failing unit tests that would need to be addressed:

- 352 - integration.HVACStandAloneERV_Economizer (Failed)
- 664 - integration.VAVSingleDuctReheatBaseboard (Failed)
- 696 - integration.WindACRHControl (Failed)

**Comment by RKStrand** [comment]
@Myoldmopar Yes, I did see that.  I will try to address that either today or tomorrow.  I know why they are failing and should be able to edit those files so that they don't crash.  In my opinion, they should not have worked previously because they autosize without actually requesting an autosizing run.

**Comment by Myoldmopar** [comment]
Looks like maybe @mjwitte's concerns were addressed and CI is now happy.  If you agree @mjwitte, please go ahead and mark your review as approved and we'll get this on the path to merge.  Thanks!

**Review by mjwitte — APPROVED** [review]
This is all good now. Thanks @RKStrand 
Merge-queued.

**Comment by Myoldmopar** [comment]
And guess what it's all clean. Thanks @RKStrand and @mjwitte !

**Pull request merged**
