### PR TITLE
Removed deprecated fields from AirTerminal:SingleDuct:SeriesPIU:Reheat and ParallellPIU

### PR DESCRIPTION
**Pull request by Nigusse**
AirTerminal:SingleDuct:SeriesPIU:Reheat deprecated field still required #4902

Removed hot fluid control nodes from AirTerminal:SingleDuct:SeriesPIU:Reheat object and  deprecated hot fluid control node from AirTerminal:SingleDuct:ParallelPIU:Reheat objects

### CODE REVIEW

**Comment by Nigusse** [comment]
The transition rules spreadsheet file for the series and parallel PIU objects and the transition rule to the Fortran file "CreateNewIDFUsingRulesV8_5_0" were updated. Also updated expand object epfile.f90.

**Comment by mjwitte** [comment]
The example files that contain these objects will need to be fixed.  You can do that manually or build and test transition to do it.

**Comment by Nigusse** [comment]
Manually transitioned the 10 example files and pushed the branch.

**Comment by Nigusse** [comment]
Manually transitioned the ten example files and pushed the branch.  But the "HVACTemplate-5ZoneVAVFanPowered.idf", the 11th example file should be taken care by Expand.  I built and tested epfilter.f90 locally and the Expandobjects run successfully. So, the epfilter code change I made is OK.

**Comment by mjwitte** [comment]
Reviewed, merged up, tested transition, tested expandobjects changes, will let CI report back then should be ready to merge.

**Comment by mjwitte** [comment]
Was surprised to see eso diffs in two files: 5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MultiPath.idf and 5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd.idf  Turns out these files had the wrong node name in the deprecated field - should have been the coil inlet instead of the coil outlet.  Tested one by putting in the correct node name and running with v8.4 and no more diffs.

**Pull request merged**
