### PR TITLE
Clean up various IDD issues and restore DisplayInputInAudit environment variable

### PR DESCRIPTION
**Pull request by mjwitte**
## Pull request overview

Addresses various IDD issues:
- [x] #5502 
- [x] #5603 (partial)
- [x] #4613
- [x] #5550 (partial)

Also restored code to use environment variable DisplayInputInAudit which was added in #4638 but somehow got deleted in [a merge from develop](https://github.com/NREL/EnergyPlus/commit/c7c641a998d4e23f81492a008407c37cf45f1f76#diff-17484dc8ed3df4c99e5415ed8acd2929) soon after.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] Changed docs build successfully
- [ ] ExpandObjects changes?
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by macumber** [comment]
@mjwitte here are the warnings based on the current file

```
[utilities.idd.IddField] <1> Field is of type choice but keys are empty: 'Optical Data Type'
[utilities.idd.IddField] <-1> Field 'Optical Data Type' of object 'WindowMaterial:Glazing:EquivalentLayer' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Illuminance Setpoint at Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Fraction of Zone Controlled by Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Rated Sensible Heat Ratio at Speed 1' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Rated Water Heating COP at Speed 1' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Nominal Speed Level' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Speeds' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Depth' of object 'EvaporativeCooler:Direct:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Area' of object 'EvaporativeCooler:Direct:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Depth' of object 'EvaporativeCooler:Indirect:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Area' of object 'EvaporativeCooler:Indirect:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Nominal Supply Air Flow Rate' of object 'HeatExchanger:AirToAir:FlatPlate' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Compressor Loading Index Entries' of object 'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Compressor Loading Index Entries' of object 'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'G-Function Reference Ratio' of object 'GroundHeatExchanger:Vertical' is both required and has default value, setting required = false.
[utilities.idd.IddField] <1> Field is not of type choice but has non-empty keys: 'Heat Exchange Model Type'
[utilities.idd.IddField] <-1> Field 'Heat Exchange Model Type' of object 'HeatExchanger:FluidToFluid' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Maximum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:ChilledWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Minimum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:ChilledWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Maximum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:HotWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Minimum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:HotWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Selection Control' of object 'DemandManager:Ventilation' is both required and has default value, setting required = false.

```

**Comment by mjwitte** [comment]
@macumber Thanks!  Will address those here.

**Comment by macumber** [comment]
@mjwitte I'm still getting the following:

```
[utilities.idd.IddField] <-1> Field 'Deep Layer Penetration Depth' of object 'MaterialProperty:MoisturePenetrationDepth:Settings' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Surface Layer Penetration Depth' of object 'MaterialProperty:MoisturePenetrationDepth:Settings' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Illuminance Setpoint at Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Fraction of Zone Controlled by Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Heat Exchange Model Type' of object 'HeatExchanger:FluidToFluid' is both required and has default value, setting required = false.
```

**Comment by mjwitte** [comment]
@macumber Thanks.  I've addressed all but the daylighting ones.  They will change with #5725.  With several new features still yet to drop, there could be more that creep in, but I'll try to watch for that.

**Pull request merged**
