### PR TITLE
IDF Editor - add new Duplicate Object and Change function and support new units

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
Address #6199 to support new types of units.

New 'Duplicate Object and Change' menu item under Edit and 'Dup Obj + Chg' toolbar item. This will duplicate the currently selected object and for each field in the object replace any text with new text. The original suggested text for change is based on the name of the object. This is especially useful for HVAC related objects when the node names are based on some of the same text as the name of the object.

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by mjwitte** [comment]
@JasonGlazer Duplicate and change object function works well.

For Table:TwoIndependentVariables, when Input Unit Type for Y = Wavelength, the units for Min/Max Value of Y should be micron, not dimensionless.

Conversion for W/(m3/s)-Pa to W/(ft3/s)-inH2O looks wrong.  The default of 1.66667 {W/(m3/s)-Pa } * 249.08891 {Pa/inH2O} * 0.028316846592 {m3/s per ft3/s} = 11.75571 {W/(ft3/s-inH2O}

**Comment by JasonGlazer** [comment]
In the conversion, the IP unit is W/((ft3/min)-inH2O). I think you missed the seconds to minute conversion (it is CFM after all). That makes it 0.1959 which is what the conversion factor shows.

Also, that conversion factor was actually added back in March. When you posted the bug you must have been using IDF Editor 1.49 not 1.49a which included that conversion factor and was part of the 8.7 release. Either way, I appreciate you checking.

**Comment by JasonGlazer** [comment]
@mjwitte I fixed the unitsBasedOnField issue with Wavelength.

**Comment by mjwitte** [comment]
Oh - duh.  I need to make sure I have all of my working folders updated with the latest IDF Editor.  I do notice that the IDD conversion factor comment is missing.  I added it with ??? in #6297.

**Comment by mjwitte** [comment]
Everything is good now.

**Pull request merged**
