### PR TITLE
Fix hybridevap solution space searching

### LINKED ISSUE #8059: HybridEvapCoolingModel does not generate the entire solution space for all mass flow ratio and outdoor air fraction CandidateSettings.
Issue overview
--------------
The HybridEvapCoolingModel does not currently loop through the entire solution space for generating CandidateSettings. Instead, it currently checks to make sure that the solutions MassFlowRatio vector lookup and OutdoorAirFraction vector are the same size, and uses a single index to pull a value from each. This results in the operating settings only creating candidate settings for each member along the diagonal of the solution matrix instead of the creating a setting for each member of the matrix.

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ajscimone**
Pull request overview
---------------------
 - Fixes #8059 
 - This pull request fixes the solution space generation and solution space searching for the HybridEvapCoolingModel of EnergyPlus. Prior to this pull request, the function for GenerateSolutionSpace would simply use some hard coded values (0.2) to loop over the minimum and maximum values set in the idf for the outdoor air fraction and mass flow rate. This minimum and maximum are often both left at a constant value for regression tests, and thus the solution space would end up a with a vector of size six where each memeber was a just a constant `1`. The function which actually finds the correct mode of the unit to use for the sitation (SetOperatingSetting) would then incorrectly loop over the solution space. Instead of looping through the entire matrix, it would simply ensure that the MSA and OAF solution spaces where the same size and use a common index to loop through each one. This is equivalent to following the diagonal of a matrix instead of looking at each value of the matrix. This function now searches the entire solution space by applying a double loop.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@ajscimone with the other hybrid PR merged, this now has a conflict.  Can you address the conflict and take a look at the failing unit test...I would say it could be a fluke but it is a unitary hybrid failure.  Is it maybe because the file was moved to the resources dir in the unit test directory?  Just guessing.

**Comment by ajscimone** [comment]
Yeah, this conflict does need to be addressed and changes made for this to work again in light of the new PR. Specifically, fields in my unit test idf snippets are now obsolete. I will get it wrapped up here shortly so the CI can take a look.

**Comment by ajscimone** [comment]
@Myoldmopar This pull request is looking ready if you want to give it another review sometime.

**Review by Myoldmopar — APPROVED** [review]
All good here.

**Comment by Myoldmopar** [comment]
CI is all happy, no issues.  Merging.  Thanks @ajscimone

**Pull request merged**
