### PR TITLE
Minor performance tweaks

### PR DESCRIPTION
**Pull request by mbadams5**
These are a few minor performance tweaks i've come across.

The biggest impact is moving to unordered_map within SystemReports::CalcSystemEnergyUse. 

@DeadParrot If you could just glance over this, I know you moved to sorted binary search almost a year ago.

The next is just moving a few expensive function calls so they are not called unnecessarily.

These are speed increases on my machine for Outpatient Reference Building...

24870.0ms -> 10499.0ms :::: EnergyPlus::SystemReports::ReportSystemEnergyUse()
17505.0ms -> 5705.0ms :::: EnergyPlus::SystemReports::CalcSystemEnergyUse()
9534.0ms -> 6497.0ms :::: EnergyPlus::WaterCoils::InitWaterCoil()
8719.0ms -> 6849.0ms :::: EnergyPlus::ZoneEquipmentManager::CalcZoneLeavingConditions()

### CODE REVIEW

**Comment by mjwitte** [comment]
@mbadams5 Do you know if these system reports are called for _every_ run, regardless of selected output variables?

**Comment by mbadams5** [comment]
@mjwitte I'm not sure. Let me try to look into it a little. When should it be called?

**Comment by mjwitte** [comment]
@mbadams5 Not 100% certain, but my recollection is that the system reports code was added to support the Ventilation Load Reports
https://www.energyplus.net/sites/default/files/docs/site_v8.3.0/InputOutputReference/01c-InputOutputReference/#outdoor-air-ventilation-outputs
and possibly supports the Systems Level Reporting
https://www.energyplus.net/sites/default/files/docs/site_v8.3.0/InputOutputReference/01c-InputOutputReference/#systems-level-reporting
@Myoldmopar may have helped with this code, or it may be before his time.
My thinking is if none of the output variables in these groups have been requested, then the system reports code does not need to run, but it may be more complicated than that, and the logic to skip it may already be in place.  You can test that by removing all Output:\* objects from your profiling idf and see if ReportSystemEnergyUse and CalcSystemEnergyUse show the same activity.

**Comment by DeadParrot** [comment]
@mbadams5 Sure, I'll take a look within a day. To assess performance of containers you really need to look at a few sizes, running it out big enough to be sure that you are seeing the "scalability" winner. Also, the performance of unordered_map, while looking very good so far in my experience, is not that consistent across compilers yet, so it is important to verify your benchmark on the main ones: GCC and Clang on Linux, and Intel and VC on Windows.

**Comment by mbadams5** [comment]
@mjwitte It appears like the system reports are run every time. I commented out all outputs in the IDF and it still has 7805ms and 4254ms for SystemReports::ReportSystemEnergyUse() and SystemReports::CalcSystemEnergyUse() respectively. I can look into it more a little later.

@DeadParrot I agree with you on all your points. For this use case though, the size of the container is fixed at compile time. I've run this with VC on Windows but i'll try it with the rest of the compilers and OSes as well.

**Comment by mjwitte** [comment]
@mbadams5 Thanks for checking if the system reports run every time.  Should probably post a new issue to disable these when not needed, if possible.  I wouldn't mix that in here, as it may have unexpected side effects.

**Comment by mbadams5** [comment]
I looked at the performance of SystemReports::CalcSystemEnergyUse() using various compilers on different OSes. In total, I compared Mac - Clang, Intel; Linux - GCC, Intel; Windows - MSVC, Intel. Since I am more familiar with profiling tools on Mac, it was more difficult to get good in-depth analysis on Linux and Windows. From what I was able to figure out using VTune on Linux and Windows, it seems like across the compilers and OSes that the change to unordered_map for this use case is at worst the same, and typically faster, than the binary search of the vector. 

Unfortunately I am about at the end of my internal time allowance for this branch of 'good will' work.

**Comment by DeadParrot** [comment]
@mbadams5 You have my vote to go ahead with this: less code and usually faster is a win. Nice!

**Comment by Myoldmopar** [comment]
@mbadams5 This does look good.  A nice small PR :wink:  Performance improvements with no diffs is generally a good thing.  And a net of -29 lines, w00t!

Looks like the changes include a lot of creating references, which is a great thing.  On the unordered_map, I trust the conclusions you and @DeadParrot came up with.

I feel good about this going in.  Anything further @mbadams5 @DeadParrot?  And FYI @mjwitte.

**Comment by DeadParrot** [comment]
@Myoldmopar I'm good with this. The switch to unordered_map is a win due to less code even on those platforms where the performance is a wash. And he removed the leftover code I noted. Well done!

**Pull request merged**
