### PR TITLE
Fix humidity control anomalies

### LINKED ISSUE #8290: Humidity control anomalies
Issue overview
--------------
Documenting some interesting results noted in the research of diffs for #7861 which need further investigation.

- [ ] Changes in "CheckWarmupConvergence: Loads Initialization" severe errors. These errors went away for Supermarket, New errors appeared for Fault_HumidistatOffset_Supermarket, Fault_HumidistatOffset_Supermarket, Fault_HumidistatOffset_ThermostatOffset_Supermarket. _SmallOffice_Dulles already had some, but more appeared.

 - [ ] FurnaceWithDXSystemRHcontrol seems to fall into one of two modes when first entering setback. Sometimes it falls into dehumidification with reheat and lands at the 18C heating setpoint with RH approx 50%. But at other times it will land between the heating and cooling setpoints and the RH is in the 30s. On 08/05, for example, develop (before #7861) lands in the deadband, but after #7861 is dehumidifying. But on 07/23 it's the opposite (develop is dehumidifying and this branch is not). A fix for this was attempted in #8286 related to using the `Setback` flag vs `CurDeadbandOrSetback`. This helped FurnaceWithDXSystemRHcontrol  but caused unexpected changes in Supermarket humidity control.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.4.0-2a4633d (near release)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #8290 

Part 1 - The problem is that sometimes when the zone is in the deadband between heating and cooling setpoints and the furnace is running with continuous fan, and there's a humidistat, sometimes the furnace decides to turn on the cooling coil (and then lots of reheat) just to avoid raising the humidity level slightly in the zone. This is with Furnace which should only operate the cooling coil for sensible load (not for latent load only). Not completely understood is why this only happened on certain days during evening setback, but not on others. Once the cooling coil decided to turn on, then the zone temp got pushed down to the setback heating setpoint of 18C which then drove up the RH in the zone and resulted in hours of this type of operation. Problem can be seen in both annual simulations of Supermarket and FurnaceWithDXSystemRHcontrol and likely others.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Not sure if it's related but see #7528.

**Comment by mjwitte** [comment]
@rraustad Well, yes i#7528 is related, but with a different fix than here. It eliminates `CurDeadBandOrSetback` from the UnitarySystem control logic. That would be a much bigger lift for the furnaces - there are 15 occurrences of `CurDeadBandOrSetback` remaining.

**Comment by Nigusse** [comment]
These next two plots show Sales-Floor zone air temperature and relative humidity for two consecutive days in July and august at time-step level (07/23-24, and 08/05-06). 

ZoneAirTemp_RH

ZoneAirTemp_RH_Aug05

**Comment by Nigusse** [comment]
These next two plots show Sales-Floor predicted sensible load heat transfer rate and predicted moisture load for the same periods as the previous plots at time-step level (07/23-24, and 08/05-06). Clearly there is shift when the dehumidification is triggered and warrants further investigation to determine the root cause and provide justification.

Predicted_sensLatLoad_July23

Predicted_sensLatLoad_Aug05

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar further investigation:
The logic where CurDeadBandOrSetback replaced setback in Furnace did not change. From code change point of view the change is straight forward. However, the most important difference that drives the diffs is how these two flag variables CurDeadBandOrSetback and setback are reset.

The Setback variable is reset based on temperature while CurDeadBandOrSetback variable reset is load based reset.  Stepping through the code CurDeadBandOrSetback and Setback at the point of use in Furnace can have different value for current time and this difference can impact whether to call for Dehumidification or not, hence a shift on furnace operation mode. In the above plots frequent shift for Dehumidification call between develop and PR8286 is driven by difference in CurDeadBandOrSetback and Setback flag value. See the plot below that shows the value of these two variables variable on 07/23 for supermarket example file for develop and this branch. 

Setback_FlagComparison07-23

**Comment by mjwitte** [comment]
@Nigusse Thanks for looking at this. I think it's clear this needs more thought, so I'm moving this PR to post-9.4.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Closing this PR for now to clear clutter.

**Comment by mjwitte** [comment]
Starting with v22.2 develop (as of today), reproduced the same code changes (replace `Setback` with `CurDeadBandOrSetback`). There's no obvious improvement in the control, similar patterns, and develop if more stable mid-day on July 23, so abandoning this PR for good and deleting the branch.

image

**Pull request closed without merging**
