### PR TITLE
Make EnergyPlus suitable for use as a cmake sub project

### PR DESCRIPTION
**Pull request by kbenne**
EnergyPlus does not lend itself to be used as a cmake sub project, meaning if you try to add_subdirectory(EnergyPlus) from a parent cmake project it will typically fail. This is because the variable CMAKE_SOURCE_DIR is often used, where a better choice would be PROJECT_SOURCE_DIR. The former will resolve to the top level source directory, whereas the latter will always resolve to the root of the EnergyPlus project source directory.

#7613

### CODE REVIEW

**Review by Myoldmopar — APPROVED** [review]
I have no problem with this change.  If CI is happy with it across platforms, and no one else speaks up, it will drop in directly.

**Comment by Myoldmopar** [comment]
So I am a little concerned that **none** of our _actual_ builds finished here.  Is there something about this change that requires a super new version of CMake or anything?

**Comment by nrel-bot-2c** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Windows and Mac have _still_ never reporting on this.  Windows is nearly caught up after all the build madness it went through, just one build plus the one it is currently running.  @kbenne there are a few conflicts after the IO freeze craze, but they look pretty easy to resolve.  If you can pull develop in one more time and push, we'll see if CI finally runs it across the board, and if not, we can investigate why CI hates this branch so much.

**Pull request merged**
