### PR TITLE
Fix #7136 - Clarify which peak the outputs of the coil sizing details are referring to

### LINKED ISSUE #7136: Unclear which peak the outputs of the coil sizing details are referring to
Issue overview
--------------

### Details
Checked using EnergyPlus 9.0.1. The coil sizing details outputs contain a coil sensible, total and airflow ideal loads peak all of which may or may not occur at the same time. Aside from the timestamps, all the other outputs state some output at "Ideal Loads Peak", but it isn't clear which peak that is associated with (Sensible, Total or Airflow). I think it'd be helpful to report out which peak the outputs are referring to. The documentation for these outputs can be found here below, but also don't quite clarify the peak at which the output is reporting.

https://bigladdersoftware.com/epx/docs/9-0/output-details-and-examples/eplustbl-lt-ext-gt.html

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7136 - Clarify which peak the outputs of the coil sizing details are referring to

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [x] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
@mjwitte I have reviewed this and see a new column in the Coil Sizing Details table as Peak Load Type to Size On. Either total or sensible is reported based on the user selection for:

```
  Sizing:System,
    VAV Sys 1,               !- AirLoop Name
    sensible,                !- Type of Load to Size On
```

The only question I would have is if we want to report total or sensible based on DataSizing::FinalSysSizing(curSysNum).CoolingPeakLoadType

```
            // assign CoolingPeakLoadType based on LoadSizeType for now
            if (SysSizInput(SysSizIndex).LoadSizeType == Sensible) {
                SysSizInput(SysSizIndex).CoolingPeakLoadType = SensibleCoolingLoad;
            } else if (SysSizInput(SysSizIndex).LoadSizeType == Total) {
                SysSizInput(SysSizIndex).CoolingPeakLoadType = TotalCoolingLoad;
            } else {
                SysSizInput(SysSizIndex).CoolingPeakLoadType = SensibleCoolingLoad;
            }
```
 or if we want to report sensible, total or ventilationrequirement based on the actual Sizing:System user input for Type of Load to Size On via SysSizInput(SysSizIndex).LoadSizeType.

```
                auto const loadSizeType(cAlphaArgs(iLoadTypeSizeAlphaNum));
                if (loadSizeType == "SENSIBLE") {
                    SysSizInput(SysSizIndex).LoadSizeType = Sensible;
                    // } else if ( loadSizeType == "LATENT" ) {
                    // SysSizInput( SysSizIndex ).LoadSizeType = Latent;
                } else if (loadSizeType == "TOTAL") {
                    SysSizInput(SysSizIndex).LoadSizeType = Total;
                } else if (loadSizeType == "VENTILATIONREQUIREMENT") {
                    SysSizInput(SysSizIndex).LoadSizeType = Ventilation;
```

Example file 5ZoneAutoDXVAV.idf

CoilSizingDetails

Other than that I have no issues with the changes here (other than maybe the location of the new column and if this report should also be included in Coil Sizing Summary).

**Comment by mjwitte** [comment]
The one referenced at the top of Sizing:System is for the airflow rates, so, I would think that `DataSizing::FinalSysSizing(curSysNum).CoolingPeakLoadType` is the correct one to use.
This is still a draft PR, and if it's adding a column to an output table, it's not going to get in for v9.2 I/O freeze.

**Comment by mjwitte** [comment]
@jmarrec Because this changes the structure of an output table, it should have an entry in 
src/Transition/OutputRulesFiles/OutputChanges9-2-0-to-9-3-0.md (which would be a new file here in this PR - just copy the prior one and clean out old stuff)

**Comment by jmarrec** [comment]
@mjwitte done in https://github.com/NREL/EnergyPlus/pull/7397/commits/e94d988d562b18be6a59d991ce154c3a2e576fee

**Pull request merged**
