### PR TITLE
Fix documentation for HybridModel:Zone model

### PR DESCRIPTION
**Pull request by xuanluo113**
- [x] I/O Ref section for HybridModel:Zone is not in the pdf. The source files were added in #5882 but there's no line in overview.tex 
- [x] I/O Ref doesn't have the output variables for "Zone Infiltration Hybrid Model Air Change Rate"
- [x] For example file HybridZoneModel.idf with the request for Output:VariableDictionary, "Zone Infiltration Hybrid Model Air Change Rate" is not in the RDD, while the Flag should be initialized here since there are objects that have Calculate Zone Internal Thermal Mass or Calculate Zone Air Infiltration Rate enabled.
- [x] This object could read begin/end day and month from the RunPeriod.

### CODE REVIEW

**Comment by xuanluo113** [comment]
#6947

**Comment by jasondegraw** [comment]
@XuanLuoLBL Similar to my question elsewhere, how should this object behave in a multiyear simulation?

**Comment by xuanluo113** [comment]
> @XuanLuoLBL Similar to my question elsewhere, how should this object behave in a multiyear simulation?

@jasondegraw I checked with the original developers. The start/end month are for the period of measured data. The feature only supports the measured period and does not support multiyear simulation. We'll update this in the document.

**Review by mjwitte — CHANGES_REQUESTED** [review]
There is a build warning now:
unused variable ‘EnergyPlus::HybridModel::FlagHybridModel’

The engineering reference section from #5822 is still missing.

The Hybrid Zone Model group now shows in the Input Output Reference, but it is incomplete. It needs the following:
1. Section heading for the object `HybridModel:Zone`.
2. The overview description of the feature is not clear, it could use some additional text. e.g. "for existing buildings *by supplying measured temperature data*."
3. Sample idf object.
4. Outputs section.
5. Most of the field descriptions need work. The Yes/No fields don't mention "No" as an option, and they don't indicate what the default is.
6. The Year/Month field descriptions are all wrong. "... for the annual run period desired." should be "... for the period of the measured data during which the hybrid model will be active." (or something similar)
7. The description of the temperature schedule says to reference a Schedule:File object, but does the code restrict this to Schedule:File or can it be any schedule object? The description here needs to make that clear. And it also needs to mention that all schedules must include data for a full year, so especially when using schedule:file, the dates outside the range of the actual measured data can be zeros, but all of the rows must be there or the data will be read for the wrong dates. Unless the hybrid code is treating this schedule in a special way.

**Comment by xuanluo113** [comment]
@mjwitte 

Thanks for the comments. As the new PR overlaps with this a lot I was thinking merging them together. I integrated the changes in this PR into #7094 in the latest commit and updated the PR review there including the tasks and your comments here.

For the new comments, the only question is that I didn't get how #5822 is related. The others are addressed in the other PR.

If you think it's Okay to do it I'll just close this one.

**Comment by mjwitte** [comment]
Oh - sorry - I meant #5882

**Comment by xuanluo113** [comment]
@mjwitte We completed the engineering reference of #5882 altogether with #7094 at [here](doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex). The other listed documentation issues are also addressed at that PR. Would you mind taking another look if I can close this one?
Thanks very much.

**Comment by mjwitte** [comment]
@XuanLuoLBL Yes, this has been covered in other PRs. Closing.

**Pull request closed without merging**
