### PR TITLE
Refactor the way end use category names got standardized

### LINKED ISSUE #10224: Missing default General subcategory meter due to the use of (valid) End Use category aliases
Issue overview
--------------

While working on PR10011, there is another issue found in the code, in that some of the non-standard “alias” end use category might accidently skip adding a `General` subcategory meter since the end use category name “standardization” comes in too late.

The affected code is here:
https://github.com/NREL/EnergyPlus/blob/8134ee039ce1cba8a9b53dba5e3e006e945d7560/src/EnergyPlus/OutputProcessor.cc#L4440-L4445

If “EndUse” is a non-standard alias, it would normally be converted to a “standard” name when a meter is added. However, at this point in setting up variables, the conversion has not happened yet. This would then cause a look up failure and then later a missing meter with “General” sub category.

One item that was affected it the “DHW” alias used in the code---which was trying to be addressed in PR10011 to eliminate the use of that alias. However, since there are so many other alias “end use” that could be used according to the “standardization” code section, it is likely that the other ones could be affected as well.

The solution is to do a refactoring so that “standardization” portion could happen earlier, or the above affected code portion could occur later. Code changes will follow soon.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v23.2 pre-release, and possiblly in earlier versions as well
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #10224
 - Initial fixes to test out the outcomes and to examine diffs

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — APPROVED** [review]
@jcyuan2020 This solves the missing "general" sub-enduse meters when a non-standard end use type is passed in. Ultimately this code will be unnecessary once all calls to `SetupOutputVariable" (and related functions) use enums, but this is a good step forward.

@Myoldmopar Tag!

**Comment by jcyuan2020** [comment]
Thanks @mjwitte! True, this is a logic issue (somewhat quite subtle and hidden there) that needs to be addressed with the existing code; and could be ultimately eliminated after more SOV refactorings down the road. On the other this logic correction will still be needed for a while at least during the transitions.

**Comment by amirroth** [comment]
I should probably let you know at this point that I have a completed but not fully tested branch that is a complete refactor of OutputProcessor. The branch is called `QSort` (because that is where it started). It conflicts with the stuff you've already checked in here and with this as well. That's fine. I should have spoken up earlier. However, after checking in this set of changes please stop working on this module until we have spoken. Thanks.

**Comment by Myoldmopar** [comment]
@jcyuan2020 this has some conflicts now, could you take a look when you get a chance?  It looks like this PR isn't changing  **too** many lines once you exclude the unit test, so if the conflicts are weird, it may be easier to just re-apply your fix on a new branch. Up to you.

**Comment by jcyuan2020** [comment]
> @jcyuan2020 this has some conflicts now, could you take a look when you get a chance? It looks like this PR isn't changing **too** many lines once you exclude the unit test, so if the conflicts are weird, it may be easier to just re-apply your fix on a new branch. Up to you.

Sure. I am taking a look at this.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
With #10347 this PR is moot. Closing.

**Pull request closed without merging**
