### PR TITLE
Add Initial Ruleset Model Description JSON File Output File-NFP Only

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Implement the draft ASHRAE Standard 229 Ruleset Model Description

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by shorowit** [comment]
Some high-level feedback:

I don't have a particular objection to this work, but I will state that it's hard for me to imagine EnergyPlus ever providing a useful RMD for residential buildings (e.g., RESNET). EnergyPlus does not have an input schema that at all aligns with inputs commonly collected for residential buildings. For these buildings, it will make far more sense to generate the RMD using a higher-level schema, like HPXML, which is specifically used to describe residential building features and properties, than the EnergyPlus schema, which is specifically used to describe how a detailed energy model should behave.

Two (of many) examples where EnergyPlus inputs are not aligned with residential features:
1. HVAC: For a residential RMD, you will have to distinguish an air-source heat pump vs central air conditioner vs room air conditioner vs furnace, etc. All of these are simply represented as UnitarySystem objects in EnergyPlus. Furthermore, you need their rated performance values (SEER, HSPF, AFUE, etc.), which are represented in EnergyPlus as disaggregated inputs (COPs, fan powers, etc.).
2. Appliances: Residential appliances have detailed inputs (a clothes washer, for example, has 7 detailed inputs from an EnergyGuide label) but they are all represented in EnergyPlus simply as an ElectricEquipment object with a power level. 

You could obviously do a lot of tagging of EnergyPlus objects to store this information and retrieve it for the RMD, but everyone would have to tag things in a standardized way and I don't know that there's a particular benefit.

I would think that commercial buildings would share _some_ of these issues, but perhaps 90.1 and other programs are more well-aligned with the EnergyPlus schema than I realize.

**Comment by amirroth** [comment]
@shorowit, three quick reactions:

1. Ever is a strong word.
2. Nobody is surprised that EnergyPlus' inputs match those more typically available used in commercial energy codes/programs/modeling-in-general than they do those typically used in their residential counterparts.
3. We (I?) did consider implementing this report in OpenStudio instead of EnergyPlus, but there are a number of compelling reasons to put it into EnergyPlus itself including reporting on what is actually being simulated, having access to internal calculations (maybe less important), and providing this feature to more end-user applications. I still think this was the right decision for commercial, but maybe it isn't for residential. Maybe for residential, the right level in which to implement an RMD export is HPXML (or equivalent level of abstraction).
4. If we ultimately determine that we do want to support RMD export for residential in EnergyPlus, we can add uninterpreted payload fields to individual objects to support it. The use of JSON makes this much easier that it would be with IDF.

**Comment by nealkruis** [comment]
I agree with @shorowit. EnergyPlus is a physics calculation engine, not a compliance shell. While much of the RMD structure can (and probably should) be stubbed out by the engine, I feel the idea of creating new objects just for payloads is exactly the kind of thing we are trying to move away from with the deprecation effort. Even for commercial buildings, I would think the engine could only fill out about 75% of an RMD without some explicit knowledge of the ruleset (which, again, I really don't think belongs in the engine). The other 25% could be supplemented by a compliance shell that leverages object tags to map engine inputs to ruleset inputs (e.g., lighting space types, space conditioning types, equipment ratings, specific appliances, infiltration metrics, etc.).

My preference would be for EnergyPlus to output a skeleton of an incomplete RMD containing as much of the structure that can be defined in a ruleset agnostic fashion. A compliance shell could then supplement data specific to the ruleset it is targeting for analysis.

**Comment by amirroth** [comment]
@nealkruis,

1. RMD is intended to be ignorant of the ruleset. In theory, RMD export should not have to know whether it is currently exporting the proposed, user, or baseline model. Another reason to put it "beneath" the compliance shell. The fact that EnergyPlus would not be able to fill out 25% of the RMD even for commercial to me suggests that there is something wrong with how that 25% is specified in the ruleset or even with what its intended use is. These issues are things we are flagging in the course of the 229 project, but may not be able to address right away.
2. RMD is also intended to be ruleset neutral, but of course is heavily influenced by the ruleset we are initially targeting. 
3. Given the difference in level of abstraction between residential and commercial rulesets, it's probably not possible to have a single-level RMD that works for both. If the existing RMD is expanded to include information required for residential rulesets, or if a separate residential RMD is developed, it probably doesn't make sense to implement export for that RMD in EnergyPlus.   
4. The comment about payload was intended to get you and @shorowit to agree on something. And it worked!

**Comment by nealkruis** [comment]
@amirroth

1. The RMD schema is ruleset agnostic, but the determination of the values for an RMD instance is not. One example of this is all the ruleset-specific enumerations that need to be defined. In other ways, the RMD schema is designed to represent a superset of ruleset model information and allow multiple ways of describing the same component of the model (e.g., U-factors vs. layer-by-layer constructions). Which approach you use will depend on the requirements of the ruleset.
2. I don't think the issue is really residential vs. commercial, it is more about the level of abstraction between an engine and its application and the differences between rulesets. For example, I think you could use the same process to develop RMDs for Title 24 commercial and residential buildings, because there is a lot more consistency across those rulesets.

**Comment by supriyagoel** [comment]
I agree with @nealkruis point regarding a compliance shell that provides 25% of the RMD inputs and the simulation engine provides the remaining 75%. As an initial effort it might also be helpful to identify the data elements that could be generated from E+ versus the ones which would require a compliance shell.

**Comment by JasonGlazer** [comment]
I welcome detailed comments on the PR but I specifically would like advice on three questions:

- what data structure would make the most sense for ultimately outputing a JSON file?
- how can we reduce the footprint of adding to the data structure since it will appear in many places in the code?
- are there any recommendations since we know we will be making many changes in the future since the 229 schema is still undergoing revisions?

Since these are JSON related questions, feedback from @jasondegraw @mbadams5 @mitchute @Myoldmopar would be really appreciated.

**Comment by jasondegraw** [comment]
@JasonGlazer After reading the NFP and the discussion on the call, I'll go ahead and leave this comment here. There's been some additional discussion that I haven't been able to fully digest yet, so I may come back here with another comment in the next couple days.

I believe that this is something that should be technically possible by processing the input and output files. If that's not possible and it's because we're not outputting enough information, that strikes me as a problem that we should fix. All of the information needed to do something like this should already be an output (setting aside for the moment the potential difficulties in marshalling that into a usable form). If we can make sure that is that case, and that implementing this in EnergyPlus proper isn't going to lead to an output form that has information that isn't also there in other forms (at least optionally), then I'm less concerned. Even so I'd feel a lot better if the default was to write out enough information that this sort of evaluation would be easy, but when we have a flag to turn on conservation of mass (🤯) I guess I should check myself.

As for how/where this is done, I personally would not chose C++ for this kind of thing. Python (for one example) is probably going to be a lot easier to do this in, especially if there's validation involved. If we need to add a `GimmeAllTheRmdStuff` flag (will defer to @mjwitte on the naming) to the engine proper, then I guess going to the additional step of formatting it as JSON is less of a deal, but still it'll be a pain in C++ compared to Python. I'd rather have the flag and a Python script to translate the output forms that we have already into the new form.

**Comment by hongtz68** [comment]
Nice discussion. Thanks Jason for writing a nice NFP on an important feature/function.

A few comments:
1. I support a feature/functionality that produces rmd files from EnergyPlus input and output files. Code compliance is an essential use case of BPS and the EnergyPlus user ecosystem.
2. It is worth thinking of the pros and cons of how this feature can be implemented, either outside EnergyPlus through the development of an open-source Python tool, or inside EnergyPlus through code changes/additions.
3. As an rmd file requires quite some amount of information that is only used for code compliance and not currently in EnergyPlus input definition (the team has included some of such information, e.g., space type, in recent releases), either approach requires extra information for code compliance defined in separate source/files to create a complete rmd file.
4.  **I would consider the approach of developing an open-source Python tool** that reads EnergyPlus input and output files, and optional additional information on compliance (required by rmd specification) in a separate file, to produce an rmd file (with critical or complete information). This avoids the complexity of changing EnergyPlus input structure significantly (and maybe frequently) just to facilitate one use case (code compliance) especially considering 229 is under development and the rmd and ruleset are subject to code cycle changes down the road. The Python code can also be adopted and improved by 3rd party EnergyPlus GUI developers.
5. About 13 years ago I looked into this issue for the CEC project in which we studied the feasibility of using EnergyPlus for Title 24 code compliance. I am glad to see a lot of progress in EnergyPlus, digital representation of energy codes/standards, and automatic code compliance checking.

**Comment by shorowit** [comment]
@JasonGlazer I like the direction this is going. Where additional inputs are needed beyond what's in epJSON, perhaps your python tool could have its own JSON schema where more inputs are required (compared to EnergyPlus) and entered as `additionalProperties` elements in the epJSON file. (This would have some overlap with [this EnergyPlus feature request](https://github.com/NREL/EnergyPlus/issues/8775), which is supposed to get implemented at some point.)

**Comment by nrel-bot-2b** [comment]
@JasonGlazer @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by JasonGlazer** [comment]
Any comments on the Design Document section of the NFP? 

Since this is being implemented in Python, @jasondegraw @amirroth @Myoldmopar (and any other Python programmers on the team) your review of that section would be appreciated.

**Comment by JasonGlazer** [comment]
I'm working on this development work at:

https://github.com/JasonGlazer/createRulesetModelDescription

**Comment by nrel-bot-2c** [comment]
@JasonGlazer @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte this PR is kind of dangling since it only contains the NFP for the ruleset work and the rest of the ruleset work was done in a different repo. I presume we want to merge it so we don't lose the NFP itself. I merged it up to to develop.

**Comment by mjwitte** [comment]
@JasonGlazer merging, labeled DoNotPublish

**Pull request merged**
