### PR TITLE
Li-ion battery code and docs updates

### PR DESCRIPTION
**Pull request by nmerket**
Pull request overview
---------------------
- Updates the Li-ion battery code to the latest from SSC.
- Now with engineering docs

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nmerket** [comment]
It looks like the build errors are related to [this problem](https://github.com/actions/runner/issues/932) in github actions.

**Comment by nmerket** [comment]
@Myoldmopar  I talked with @dguittet on the SAM team, the one CI error was due to a new check that was being triggered by a cumulative rounding thing on the battery lifetime because we keep changing the timestep. It's not an elegant fix, but I commented out that check and am calling the change timestep only when we need to now, which should improve things. Worst case scenario the battery degredation will kick in a timestep off from when it was supposed to. (on the order of days)

I'm going to let CI run and see if that solved the problems. I'll keep an eye on it over the weekend.

**Comment by Myoldmopar** [comment]
Integration test is now passing, that's good.  The other integration tests are not your problem here.  There is still the funny issue on Ubuntu 20.04 Debug builds that doesn't seem to be showing up in our tests.  That should be investigated post-release.

There are conflicts that I will be happy to resolve, as more could continue coming as PRs are merged.  Other than that is there anything else you are planning on adding here?

**Comment by nmerket** [comment]
No, I think we're done here. Thanks.  I'll look into the Ubuntu 20.04 failures on Monday.

-Noel

________________________________

**Comment by Myoldmopar** [comment]
Excellent.  I resolved the tiny conflict and am building it now.  Will likely merge shortly if everything passes.

**Comment by Myoldmopar** [comment]
Built, unit tested, and regression tested it with latest develop.  The only thing noted was the same LiIon test file that is showing up on CI.  This is good to go.  I'll push the conflict resolved branch now and get it merged.  Thanks @nmerket

**Pull request merged**
