### PR TITLE
Change IDD/epJSON Schema for EnergyManagementSystem:Program to allow blank lines

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
Part of #6601, [this comment](https://github.com/NREL/EnergyPlus/issues/6601#issuecomment-377024207)

EnergyManagementSystem:Program did not accept a blank line in the middle of the object. Changed IDD to no longer \require lines within the extensible fields (Program Lines). In epJSON schema there is now a requirement for minItems of 1 for extensible fields, which is likely the original intent of \require on only the first line of program lines.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Code style (parentheses padding, variable names)
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check -- verify this
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [x] Verify naming conventions and styles, memos and notes and defaults
   - [x] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs

### CODE REVIEW

**Comment by mjwitte** [comment]
Linux gcc tests have failed twice today, going to try for a third time to see if they will run.

**Review by mjwitte — APPROVED** [review]
Tested with defect file. Fix is good.

**Comment by SchildCode** [comment]
This issue needs to be opened again: This change is not accepted by my in-house epJSON schema reader, which double-checks the compatibility of the epJSON "patternProperties" and "legacy_idd" for each object in the schema. I fixed the problem by editing my copy of the v.9.1.0 schema, either removing the requirement for "lines" or by reverting object "EnergyManagementSystem:Program" back to v.8.9.0. The problem is that the v.9.1.0 schema requires field "lines" (which is the group-name of the extended fields, but not the name of any individual field). There is no field called "lines"; the requirement should be dropped, or revert to requiring extended field "program_line" instead. The change between 8.9.0 and 9.1.0 breaks the established practice that only fields listed in legacy_idd:{fields:[]} or legacy_idd:{extensibles[]} can be required, not extension group names. I understand that complete backwards-compatibility break from .idd will not occur before v.10.0.0.

### **Original epJSON object schema in v.8.9.0:**
        "EnergyManagementSystem:Program": {
            "patternProperties": {
                ".*": {
                    "type": "object", 
                    "properties": {
                        "lines": {
                            "items": {
                                "required": [
                                    "program_line"
                                ], 
                                "type": "object", 
                                "properties": {
                                    "program_line": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "type": "array"
                        }
                    }
                }
            }, 
        }, 

### **Corrupt object schema in v.9.1.0:**
        "EnergyManagementSystem:Program": {
            "patternProperties": {
                ".*": {
                    "required": [
                        "lines"        <=== OFFENDING CODE
                    ], 
                    "type": "object", 
                    "properties": {
                        "lines": {
                            "minItems": 1, 
                            "items": {
                                "type": "object", 
                                "properties": {
                                    "program_line": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "type": "array"
                        }
                    }
                }
            }, 
        },

**Comment by mjwitte** [comment]
@SchildCode Please open a new issue for this and reference this pull request.

**Pull request merged**
