### PR TITLE
Fix HeatPump:PlantLoop:EIR:* Inlet Temperatures

### LINKED ISSUE #8071: HeatPump:PlantLoop:EIR:* Inlet Temperatures Don't Update When Unit Off
HeatPump:PlantLoop:EIR* inlet temperatures don't update unless the unit is running. The following lines need to be moved out of the ```doPhysics``` method, which is only called when the unit runs.

https://github.com/NREL/EnergyPlus/blob/431d52730f3c519476342ed7f5c9f9c7c35818d5/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L297-L298

A fix will be pushed shortly.

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 10.14.6)
 - Version of EnergyPlus (9.4 431d52730f3c519476342ed7f5c9f9c7c35818d5)
 - Helpdesk ticket 15447

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8071)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mitchute**
Fixes #8071 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
From the test file provided by the user for an air-source heat pump.

The unit never operated so the temperatures were never updated.

Screen Shot 2020-06-10 at 1 53 44 PM

After the fix, the temperatures now behave as they should.

Screen Shot 2020-06-10 at 1 53 00 PM

**Review by Myoldmopar — APPROVED** [review]
I know this is draft, but this looks like a reasonable fix to me.

**Comment by Myoldmopar** [comment]
As for the failing unit test, I wouldn't be surprised if the new value is simply the correct value.

**Comment by Myoldmopar** [comment]
OK, I understand why that unit test was failing.  Previously the unit test was setting the inlet node conditions to specified values so that the unit would run under those conditions.  This worked because inside `doPhysics` is where we were pulling the data from the node onto the unit data structure.  However, your change here pulled that assignment up to the `simulate` level, so the unit was running with zero inlet temperatures on both source and load side.  To fix it, I just changed the unit test so that it sets up the data structure inlet temps directly and runs the physics calculation.  Everything seems good now, so I'll let CI run and this should be able to drop in shortly.

**Comment by Myoldmopar** [comment]
All good here, merging.  Thanks @mitchute !

**Pull request merged**
