### PR TITLE
Fix bad IDD search path for local Windows unit testing

### LINKED ISSUE #5051: Unit tests not finding IDD on Windows VS build
@mbadams5 @kbenne EnergyPlusFixture is expecting the IDD to be in the same directory as energyplus_tests.exe which is either Products\Debug or Products\Release, but the generated IDD is up a level in Products.

### PR DESCRIPTION
**Pull request by mbadams5**
Fixes #5051 

@mjwitte This works on my Windows VM with a completely fresh build folder. I think I previously put the Energy+.idd in the folder with my energyplus.exe for a different reason and that is why I didn't catch this bug.

fyi @kbenne @Myoldmopar

### CODE REVIEW

**Comment by mjwitte** [comment]
@mbadams5 Thanks for the fix.  Tested and it works.  Inadvertently ran from wrong build folder first and that failed, so I ran this in debug mode and realized that energyplus_tests needs the _NO_DEBUG_HEAP=1 setting since it processes the IDD now.  Added that to the readme.  If you agree with the readme change, I'll merge this.  @kbenne @Myoldmopar

**Comment by kbenne** [comment]
Can `_NO_DEBUG_HEAP=1` be added to the cmake project?

I seem to recall some reason why this was not possible.

**Comment by mjwitte** [comment]
@myoldmopar can answer to that.  Originally, it couldn't but maybe it 
can be now?  That would be nice.

**Comment by kbenne** [comment]
Yeah I see now. It is a environment variable with no obvious compiler flag alternatives. That is problematic.

**Comment by Myoldmopar** [comment]
Yeah, it is not in the domain of standard CMake configurable files.  I
think I read about some super hacky approaches to manually write that file,
etc., that could easily cause other problems to trickle down.

On Wed, Jul 29, 2015 at 10:10 AM, Kyle Benne notifications@github.com
wrote:

> Yeah I see now. It is a environment variable with no obvious compiler flag
> alternatives. That is problematic.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NREL/EnergyPlus/pull/5052#issuecomment-126003531.

## 

Edwin Lee, PhD
Engineer, Commercial Buildings Research Staff
National Renewable Energy Laboratory

**Comment by kbenne** [comment]
https://public.kitware.com/Bug/view.php?id=8884
http://www.cmake.org/Bug/view.php?id=2582

**Comment by kbenne** [comment]
The hacks that come to mind are to put an executable around the test to set the environment variable. I don't have the energy to go there now and I'm not sure it is even a good idea.

**Comment by mbadams5** [comment]
~~I guess I don't understand why you needed to add this in the first place? I ran energyplus_tests without needing to specify that on my build.~~

It is just to speed up running unit tests. 

I did wonder why it took so long on Windows.

**Comment by kbenne** [comment]
PS @mjwitte there is a solution to your /MP thing. I will take some screenshots to outline once I get my VS environment updated in a few more minutes.

@mbadams5 It seems without the debug heap thing, the tests just run slowly.

**Comment by mjwitte** [comment]
@mbadams5 It's only a problem when you run the interactive debugger (right-click on energyplus_tests in the solution explorer and debug - start a new instance).  The tests run fine until it gets to processing the IDD and then sits there (pretty much forever) without this setting.  Add the setting and it keeps chugging along nicely.  BTW I noticed that the IDD search code gets executed multiple times along the way through all the tests.  Is that expected?

**Comment by mbadams5** [comment]
Yeah that all makes sense now @mjwitte.

It should be executed a few times. It will execute the first time a unit test is run that uses the idd parsing. After that it is cached and the cache is used instead. I do have a few unit tests though that specifically avoid using the cache to make sure I catch any mistakes. I think there are 2 other unit tests that parse the full IDD.

PS: @kbenne Yet another reason to rewrite InputProcessor :wink:

**Pull request merged**
