### PR TITLE
It must be the min, right?

### LINKED ISSUE #9732: Using actuator Unitary System DX Coil Speed Value doesn't report correctly in the latest release
Issue overview
--------------
I surprisingly found that whenever an EMS program using following speed level actuator will remove the output variables: ``Output:Variable,*,Cooling Coil Crankcase Heater Electricity Rate,hourly; !- HVAC Average [W]`` and ``Output:Variable,*,Cooling Coil Crankcase Heater Electricity Energy,hourly; !- HVAC Sum [J]`` from idd file, and a warning of requesting unexpected output variables will be thrown.

EnergyManagementSystem:Actuator,
  central_ac_unitary_system_speed_override, !- Name
  central ac unitary system,              !- Actuated Component Unique Name
  Coil Speed Control,                     !- Actuated Component Type
  Unitary System DX Coil Speed Value;     !- Actuated Component Control Type

Attached are two idfs that the only difference is a dumb EMS program and the RDD files generated.
[in-noEMS.txt](https://github.com/NREL/EnergyPlus/files/9984983/in-noEMS.txt)
[in-dumbSpeedLevelActuator.txt](https://github.com/NREL/EnergyPlus/files/9984984/in-dumbSpeedLevelActuator.txt)
[in-dumbSpeedLevelActuator-rdd.txt](https://github.com/NREL/EnergyPlus/files/9984992/in-dumbSpeedLevelActuator-rdd.txt)
[in-noEMS-rdd.txt](https://github.com/NREL/EnergyPlus/files/9984993/in-noEMS-rdd.txt)

More descriptions here: [Link](https://github.com/NREL/OpenStudio-HPXML/pull/744#issuecomment-1309665978)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows, 11)
 - Version of EnergyPlus (22.2.0)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9732 sensible capcity issue
 - system and coil use different W in calculation of Cp.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
This does not seem to be the correct change. If I want state point A to B sensible, I must know what each state humrat is.

**Comment by rraustad** [comment]
Thought provoker:

image

    inline Real64 PsyCpAirFnW(Real64 const dw // humidity ratio {kgWater/kgDryAir}
        Real64 const w(max(dw, 1.0e-5));
        Real64 const cpa((1.00484e3 + w * 1.85895e3)); // result => heat capacity of moist air {J/kg-C}

**Comment by rraustad** [comment]
The volume flow rate at A1 and A2 are the same because the fan is constant volume equipment. It's the mass that's different. In all E+ models, Init calculates V * StdRho to get MassFlowRate and then uses that flow rate as the operating flow rate. This equipment is operating at that mass flow rate, at A1 and A2, and it should be:

    Mdot = V * rho, actual. 

So the mass flow in E+ is the same in : Mdot * Cp (T, in - T, out) and Cp has changed because air density has changed but Mdot did not change accordingly. I think that explains one of the differences in the sensible calculation.

**Comment by yzhou601** [comment]
> The volume flow rate at A1 and A2 are the same because the fan is constant volume equipment. It's the mass that's different. In all E+ models, Init calculates V * StdRho to get MassFlowRate and then uses that flow rate as the operating flow rate. This equipment is operating at that mass flow rate, at A1 and A2, and it should be:
> 
> ```
> Mdot = V * rho, actual. 
> ```
> 
> So the mass flow in E+ is the same in : Mdot * Cp (T, in - T, out) and Cp has changed because air density has changed but Mdot did not change accordingly. I think that explains one of the differences in the sensible calculation.

Should we modify the Mdot to be changed based on the actual rho instead of StdRho then? I remember in the past when I inspected equations with rho values, I got confused too, but I didn't remember the reason why E+ did it in this way. Is there any concern that we cannot use a more accurate rho? And can we make some changes in this PR to test if the mass flow is the reason that cause the discrepancy?

**Comment by rraustad** [comment]
> Should we modify the Mdot to be changed based on the actual rho instead of StdRho then? I remember in the past when I 
> inspected equations with rho values, I got confused too, but I didn't remember the reason why E+ did it in this way. Is there 
> any concern that we cannot use a more accurate rho? And can we make some changes in this PR to test if the mass flow is
> the reason that cause the discrepancy?

No, this was just a test to see how much the answer changed. At this point there should be no changes made to how E+ manages mass flow rate. I will likely close the PR since it did not have the impact I thought it would.

**Comment by rraustad** [comment]
@yzhou601 if you want to make changes to this branch as a test case, go right ahead. But they will likely not be included in E+.

**Comment by yzhou601** [comment]
I think this is a separate issue from the EMS error, so I created a new issue to better track this: https://github.com/NREL/EnergyPlus/issues/9838

**Comment by Myoldmopar** [comment]
@rraustad it feels like this was just a test, so I'm going to close the PR.  I'll leave the branch, so if you want to reopen the PR, have at it.

**Pull request closed without merging**
