### PR TITLE
Fix DX Coil crankcase heater meter

### LINKED ISSUE #7254: DX Coil Crankcase Heater Electricity Submeter Shouldn't be on Plant
Issue overview
--------------
During DX coil refactor, it was found that the base DXCoils output variable call for cooling coil basin electricity was improperly putting basin heater electricity on the plant submeter when it should be on the system (search on [this raw page](https://raw.githubusercontent.com/NREL/EnergyPlus/develop/src/EnergyPlus/DXCoils.cc) for "plant" with quotes and it's easy to spot).  In order to get no diffs in the refactor, we are just replicating this behavior, but this should be fixed separately and the fix pulled into the branch when it's done.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #7254 
 - Coil:Cooling:DX:* output variable "Cooling Coil Crankcase Heater Electricity Energy" was on the "Plant" submeter, but should be on "HVAC" (System) meter. 
For Coil:WaterHeating:* this remains on the Plant submeter.
No documentation changes are required, the I/O Ref already indicates the correct submeter.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] ~Check any new function arguments for performance impacts~
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Wow.  I was about to say this doesn't need to get CI's approval as minimal as it is.  But Ubuntu was just sitting waiting for it.  Carry on...

**Comment by mjwitte** [comment]
Diffs are mostly as expected. Energy moved from Electricity:Plant to Electricity:HVAC. 
Big table diffs for other rows in the FullName:Energy Meters_Entire Facility_Annual and Peak Values - Electricity table output are due to the row order changing (because the Electricity:Plant meter is first used at a different point in the setup).
3 files have err diffs like this:
```
+   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="ELECTRICITY:PLANT" - not found.
+   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="ELECTRICITY:PLANT" - not found.
    ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
    ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
```
I suppose I could remove both of these meters from the 3 offending files.

**Comment by Myoldmopar** [comment]
Since the changes are a bit more broad now I'll let CI at least run one test on this before merging.

**Comment by mjwitte** [comment]
Oui, monsieur.

**Comment by mjwitte** [comment]
@Myoldmopar This is ready for review and merge. 
Err diffs:
HVACTemplate-5ZonePTAC-DOAS - deleted this meter request from idf.
```
-   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
-   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
```
Exercise2A-Solution - these meters are in the base solution file, and become active in a later exercise, so leaving these in the idf.
```
+   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="ELECTRICITY:PLANT" - not found.
+   ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="ELECTRICITY:PLANT" - not found.
    ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
    ** Warning ** Output:Meter:MeterFileOnly: invalid Key Name="NATURALGAS:PLANT" - not found.
```

mtr big diffs in Electricity:HVAC
Big table diffs are due to Energy moved from Electricity:Plant to Electricity:HVAC.
Big table diffs for other rows in the FullName:Energy Meters_Entire Facility_Annual and Peak Values - Electricity table output are due to the row order changing (because the Electricity:Plant meter is first used at a different point in the setup).

**Comment by Myoldmopar** [comment]
All good here, thanks @mjwitte

**Pull request merged**
