### PR TITLE
Improve information in surface height out of range warning

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #5434 
Now if the surface height is out of range, then the offending surface name is also included as part of the fatal error message.

### CODE REVIEW

**Comment by Nigusse** [comment]
Cleaned the code to remove warning error messages. The CI machine is expected to run all green.

**Comment by nrel-bot-3** [comment]
@Nigusse @lgentile it has been 14 days since this pull request was last updated.

**Comment by Nigusse** [comment]
Modified the code to allow throwing error message for than one offending surface if they exist. Previously it was reporting the offending surface with the maximum height only.

**Comment by Nigusse** [comment]
Removed unused variables and merged develop in to confirm that the one example file diff shown is due to lag from develop. The CI machine is expected to come all green.

**Pull request merged**
