### PR TITLE
91245424 central dx heating coil sizes to zero if cooling coils have not sized yet #4827

### PR DESCRIPTION
**Pull request by rraustad**
Allows HX to control to set point regardless of operating (heating or cooling) mode

### CODE REVIEW

**Comment by rraustad** [comment]
Shoot, this is the wrong branch. How do I move this commit to a different branch?

**Comment by rraustad** [comment]
I created a new branch for this commit. How do I delete the commit off of this branch?

**Comment by mjwitte** [comment]
@rraustad Please confirm that #4833 replaces this PR.  You can close this PR and the go to the list of branches and delete this branch.

**Comment by rraustad** [comment]
Yes is replaces this branch. I'll close this one.

**Pull request closed without merging**
