### PR TITLE
Call DXCoils::DisableLatentDegradation after getting cooling coil index

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
The program was crashed due to 0 cooling coil index, because DXCoils::DisableLatentDegradation is called before getting cooling coil index. The function is moved to a right location after getting cooling coil index. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by shorowit** [comment]
I can confirm that this fixes the crash.

I also see the simulation results change very slightly when using this object, which suggests that it's doing something, however the err file suggests that it's unused:
```
   ** Warning ** The following lines are "Unused Objects".  These objects are in the input
   **   ~~~   **  file but are never obtained by the simulation and therefore are NOT used.
   **   ~~~   **  Only the first unused named object of an object class is shown.  Use Output:Diagnostics,DisplayAllWarnings; to see all.
   **   ~~~   **  See InputOutputReference document for more details.
   ************* Object=PerformancePrecisionTradeoffs=PerformancePrecisionTradeoffs 1
```

**Comment by lgu1234** [comment]
@shorowit I ran the test file and unable to get your message. Could you upload the your test file?

**Comment by shorowit** [comment]
@lgu1234 Here you go:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3898492/in.idf.txt)
[eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/3898497/eplusout.err.txt)

**Comment by lgu1234** [comment]
@shorowit Thanks for your input file. I checked the cause. Since PerformancePrecisionTradeoffs is a unique object and does not have an object name field, it is unnecessary to check the object name and confuses the program to provide a wrong message.

                auto const &thisObjectName = UtilityRoutines::MakeUPPERCase(instance.key());
                inputProcessor->markObjectAsUsed("PerformancePrecisionTradeoffs", thisObjectName);

The fix is easy by removing thisObjectName check and checking uniqueness.

This issue is nothing to do with "Unused Objects" and the fix addressed the crash. Please close this issue. I am going to create a new issue to address "Unused Objects".

**Comment by Myoldmopar** [comment]
@lgu1234 the hash symbol (octothorpe, #) in the branch name is causing CI to skip running this branch.  I can review this when it is ready and provide regression results manually so that you don't have to create a new branch and pull request.  Let me know when you feel this is completely ready to go.

**Comment by lgu1234** [comment]
@Myoldmopar Thanks for letting me know. I will not create a branch with # from now on. The branch is ready for review.

**Comment by Myoldmopar** [comment]
@shorowit thanks for verifying the fix worked.  Also thanks for noting the error file issue.  This is indeed merely that in the new input processing approach, where we grab the inputs directly from the internal JSON representation, we need to call to mark the object as "used".  This needs to be cleaned up for this object.

@lgu1234 I tried to verify the bug fix also locally, but when I transitioned up the defect file, it ended up truncating the EMS code due to long lines, so it would no longer run.  I will base the verification on @shorowit's prior verification.  Also, it looks like we don't have an example file with the tradeoff object, so that's fun.

There were a few build warnings due to unused variables.  I fixed them and will push that up then merge this into develop right away.

**Comment by Myoldmopar** [comment]
Was there a defect to close with this PR?

**Comment by shorowit** [comment]
https://github.com/NREL/EnergyPlus/issues/7601

**Comment by lgu1234** [comment]
@Myoldmopar I am going to make an example file for the object.

**Pull request merged**
