### PR TITLE
Add Kiva message callback functionality

### PR DESCRIPTION
**Pull request by nealkruis**
Pull request overview
---------------------
This follows on the recent addition of Kiva to perform ground heat transfer calculations. It is an internal (i.e., no interface changes) modification to allow messages (warnings and errors) from Kiva to be displayed consistently in the EnergyPlus ERR output file.

Work completed for:

- Subcontract AEU-7-70112-01: “2017 EnergyPlus Foundation Heat Transfer Algorithm Model Development”

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully

### CODE REVIEW

**Comment by mjwitte** [comment]
@nealkruis My guess is that develop moved before CI got around to running the tests on this branch (it was way behind a couple of days ago).  I'd merge in develop again.  Also, there's a conflict now on this branch.

**Comment by nealkruis** [comment]
@mjwitte done. hmmm...I didn't see any conflicts when I merged.

**Comment by mjwitte** [comment]
Odd - this page here noted one, but not any more.

**Comment by Myoldmopar** [comment]
Looks like everything got cleaned up here, I'm going to merge this one.

**Pull request merged**
