### PR TITLE
Exhaust Absorber refactor

### PR DESCRIPTION
**Pull request by Myoldmopar**
Plant refactor for ExhFiredAbsorptionChiller.idf -- the last component....

### CODE REVIEW

**Comment by Myoldmopar** [comment]
OK, this refactor is complete.  I get a single BND diff in the one example file.  Note that I didn't take the time to rigorously refactor all the local variables in every function.  This object is only used in one example file, and there wasn't sufficient value to spend all the time optimizing this object to the max.

**Comment by Myoldmopar** [comment]
@mitchute let me know if you see anything here.  I see one unused local variable warning which I will clean up and push, but I don't need to waste CI cycles on that, so I'll just push that once this is approved and it can merge.

**Comment by Myoldmopar** [comment]
Oh, nevermind, the build warning was from an earlier commit, the most recent one should be all green -- just BND diffs for one file.

**Comment by Myoldmopar** [comment]
Re-running Windows now after I rebooted it again.  Expecting all green...

**Comment by Myoldmopar** [comment]
@mitchute in the midst of all the other business, this branch looks good to go in anytime.  Let me know if you see any issues.

**Comment by mitchute** [comment]
@Myoldmopar agreed, this looks good. Merging.

**Pull request merged**
