### PR TITLE
Fix Issue #10286 window material shade mis-alignment for Output:Constructions

### LINKED ISSUE #10286: WindowMaterial:Shade eio output write-out CSV format typo
Issue overview
--------------
It was reported by a user that in the EIO report there is a column shift occurred between the header and the actual information:
image

After examining the source code, this was found to be caused by a formatting typo in the source code:
https://github.com/NREL/EnergyPlus/blob/d07d7ad64207285b241ab79b67b66ed98e2db594/src/EnergyPlus/WindowManager.cc#L7405-L7409

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): at least since v9.4, till v23.2
 - Helpdesk Ticket Number: 16512

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/10000s/10286/10286_in.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #10286 
 - Quick fix to the eio WindowMaterial:Shade header and data mis-alignment:
 
Before:
image

After:
image

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — APPROVED** [review]
This works as advertised. The shift can also be seen in the Initialization Summary table report.

Before:
image

After:
image

I've added an entry to the Output Rules file and will push up shortly.

Thanks @jcyuan2020

**Comment by mjwitte** [comment]
Diffs are as expected. eio and table diffs in several files. This is ready to merge.

**Comment by Myoldmopar** [comment]
The test failure there was purely because this is coming from a fork and there is still an issue with PRs from forks that have regressions.  I need to resolve a conflict on here anyway, so maybe I'll take a look at that again before pushing up the resolved branch.

**Comment by Myoldmopar** [comment]
OK, so that didn't work.  This is a real challenge with the security in place.  I'm not complaining, just trying to work through it.  I definitely don't want to let external fork PRs slip regressions in, so without a comment ability, I think I need to have the regression workflow.  A little more gracefully would be good though.  I'll try one more tweak.

**Comment by Myoldmopar** [comment]
OK, this might be a nice intermediate fix. 

- For PRs from branches inside this repo, it behaves like normal and reports the regressions right on the PR page
- For PRs from forked repos, it skips that step since the action won't have write access to emit a comment here.  Instead it will fail with a decently formatted message explaining that there were regressions, and hinting the reviewer to the job summary page.

If this behaves alright, we'll get this merged in.  Sorry to hold up this fix while I worked out the GHA issue, but it was convenient to do this on an existing fork+diffs PR.

**Comment by jcyuan2020** [comment]
No sure if the problem was due to a very outdated `develop` branch in the forked repo. Anyway I just updated the `develop` branch in the forked repo to see if that would help.

**Comment by Myoldmopar** [comment]
@jcyuan2020 the Build and Test failure is actually occurring as intended.  (Unfortunately)  The details page quickly gets the reviewer to the reason why it failed: https://github.com/NREL/EnergyPlus/actions/runs/11845688475/job/33011694597?pr=10750#step:21:16, and then the job summary page has the regression bundle ready to download and inspect: https://github.com/NREL/EnergyPlus/actions/runs/11845688475?pr=10750. 

The Windows failure appears unrelated.  I kicked the Windows machine and deleted these test results to get a fresh run, and I expect this to merge in without any issue after that's done.

**Comment by Myoldmopar** [comment]
Yep, this was all fine after the re-run of Windows.  Merging this.

**Pull request merged**
