### PR TITLE
Refactor Crack Calculations

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
This PR refactors most of the crack calculations and adds testing. The refactoring combines logical operations where possible and corrects a few issues with the laminar calculation. In testing, this has consistently improved the function call time by about 5%. These functions get called a lot, so there's some possibility of overall speedup. There are a few more warnings to address, and while I believe that the diffs are expected (reordering some of the calculations does result in small changes), I still need to investigate them further.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
> There are a few more warnings to address, and while I believe that the diffs are expected (reordering some of the calculations does result in small changes), I still need to investigate them further.

Since this hasn't been touched in a while, I'm going to assume that you won't be wrapping the diff investigation and build warnings and such for this release.  I am going to mark it for the next release.  If you are still planning on bringing it into this release, feel free to revert the milestone back and I'll review when ready.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jasondegraw @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jasondegraw it has been 15 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jasondegraw I'm going to push this to next release again.  If you feel like spending some time investigating the issues, fixing build warnings, and resolving the conflict, feel free to re-mark it for 9.3 and we'll get it reviewed.

**Comment by jasondegraw** [comment]
@Myoldmopar Actually, I'm going to close this PR. I've moved some of the better parts of the branch over to a new one that has no diffs, so I'll probably end up deleting this PR branch once I've gotten the parts that worked moved over.

**Pull request closed without merging**
