### PR TITLE
Add Python code to license check

### LINKED ISSUE #8446: License checking does not check Python code
Issue overview
--------------
The current license checking script does not check Python code (nothing outside of C/C++ is checked). As more Python is added, we should fix that. Some of the scripts live in the source tree now, so those will get found. What other locations should we add to the search? The entire scripts directory? Is there anything that should be skipped? 

### Details
This is a dev/repo issue. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
The current license checker doesn't check Python files, this addresses that shortcoming and expands the coverage of C/C++ a little (a newer subdirectory wasn't getting hit). These files are spread out a bit so the search is a little more broad. This should be merged after #8445.

The script is changed so that it can handle the Python version of the license and all of the Python code that I could find should now have (or will have soon) the correct license.

Fixes #8446

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@myoldmopar To Do

Fix license in:
 - [x] `scripts/diagnostics/afn_auditor.py`
 - [x] `doc/tools/parse_ems_actuators.py`

**Comment by Myoldmopar** [comment]
@jasondegraw I fixed the license in the two diagnostic files and the doc tool file.  Can you confirm it's all good?  I believe it will be ready to go once CI approves and you confirm.

**Comment by Myoldmopar** [comment]
Unknown why the github mac instance failed, but it's nothing to do with this.  This looks ready to go in now.  Am I missing anything  @jasondegraw ?

**Comment by jasondegraw** [comment]
@Myoldmopar No, I don't think you've missed anything, I think this can go in. I pulled it, ran the script, and everything seemed to be in order. The scripting around updating the license year will need to be brought into line with these changes, but that can wait until my annual foray into mass editing.

**Pull request merged**
