### PR TITLE
Intelligent Defaults for Minimum Flow Fraction on VAV Terminals

### PR DESCRIPTION
**Pull request by wfbuhl**
## Pull request overview

A new feature allows intelligent defaulting of minimum flow fraction for VAV terminals (input object AirTerminal:SingleDuct:VAV:Reheat).  The minimum flow fraction can now be autosized.  
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [x] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [x] Documentation changes in place
- [ ] ExpandObjects changes??
- [x] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@wfbuhl @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@wfbuhl @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@wfbuhl I'm pushing some commits to this branch, so you'll have to do a `git pull` before you push any more work up here.  Some details:
- I wanted to clean up the unused variable build warnings.  They were all in the new unit test, not a big deal.
- There were merge conflicts:
  - A tiny one in the unit test file, not a big deal.
  - `5ZoneDetailedIceStorageSimpleCtrl.idf` had bad line endings.  What editor are you using to edit your idfs?  This may have been a fluke if you pasted in a chunk of idf from another file on your machine or something, but my recommendation would be to use as simple of an editor as you can when editing the idfs (Notepad++, etc.)

I'm building it now and then I'll push up the commits.  You can continue as if nothing has happened.  Just do a Git Pull as soon as possible to avoid further issues.

**Comment by EnergyArchmage** [comment]
From an EIO diff, I see this new sizing report.  
- Component Sizing Information, AirTerminal:SingleDuct:VAV:Reheat, SPACE2-1 VAV REHEAT, Minimum Air Flow Rate (from Min Air Flow Frac) [m3/s], 7.25957E-002

The name ( "Minimum Air Flow Rate (from Min Air Flow Frac)" ) of the sizing report should be prepended with either "Design Size" or "User Specified"    And it may need to report both flavors.

**Comment by EnergyArchmage** [comment]
Okay, I have scanned through the test "failures" and agree they are as expected.

**Comment by wfbuhl** [comment]
With respect to the component sizing report column headings and the eio
file: Minimum Air Flow Rate (from Min Air Flow Frac) means that the user
input the minimum flow fraction and we are reporting out, as a convenience
to the user, the flow rate derived from that flow fraction. So should this
be labeled "User Specified" or "Design Size"? I guess it should be "User
Specified". As for reporting out the design results, remember there is a
warning message that shows both user and design if the user input differs
by more than 10%. Of course this only comes out if only with
Output:Diagnostics, DisplayExtraWarning. I guess I am afraid of outputting
too much information and just getting the user lost in a forest of outputs.

**Comment by EnergyArchmage** [comment]
I have reveiwed the source code, etc.  Just merged in develope, I think this is good to go in.

**Pull request merged**
