### PR TITLE
IDD cleanup and other minor fixes for v8.9.0

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Various minor IDD changes that should be merged before the next release.

1. Incorrect name reference placement for `SolarCollector:FlatPlate:PhotovoltaicThermal` - caused the surface name to be considered a valid component name in the Branch Component Name fields, instead of the collector name.  From [Unmethours 28869](https://unmethours.com/question/28869/problem-with-shopwithsimplepvt-idf/). Test by opening example file ShopWithSimplePVT in IDF Editor and look at the Branch objects that hold the collectors.  Prior to this fix the collector names are flagged as invalid.

2. Units cleanup for  `GroundHeatExchanger:Vertical:Properties` introdcued in v8.9 in #6359.

3. Fix several occurrences of "\Key" to "\key" and fix "\ group" to "\group".

4. Fix incorrect "WaterUse:Tank" object class name in error messages, should be "WaterUse:Storage". From [Unmethours 29509](https://unmethours.com/question/29509/energyplus-88-error-file-refers-to-waterusestorage-object-as-waterusetank-object/).

5. Fix missing Speed N in field names for Coil:Cooling:DX:Multispeed and several instances of "minimum >0" (should be minimum> 0).  From helpdesk ticket 12509.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 14 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@mitchute Please confirm IDD changes for ground HX.

**Comment by mitchute** [comment]
@mjwitte looks good to me.

**Comment by Myoldmopar** [comment]
There are two things I found just today when running the IDD through my parser:
- AirflowNetwork:MultiZone:Surface
  - Field A8: `\key` is capitalized (twice)
- `\ group Hybrid Model` has a space between the backslash and the word group

**Comment by mjwitte** [comment]
@Myoldmopar Just fixed the \Key  and \ group problems.

**Comment by Myoldmopar** [comment]
Thanks!

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
I don't see an explicit Github issue for any of these.  Let me know if there is and I can close them.

**Comment by mjwitte** [comment]
@Myoldmopar Correct - no separate issues for these.

**Pull request merged**
