### PR TITLE
Solve root cleanups continued

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - Continuing the solve root / Par refactor to a proper callback/payload system.  
 - Plan is to just wrap them all up in this PR, and call this task complete, so I'm not stopping to cleanup every aspect, but trying to cleanup wherever reasonable.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
At this point I think there's only a handful or two of old-style Par calls to SolveRoot.  I'll be trying to wrap them up tomorrow or early Monday, and if clean, I'll delete the "extra" temporary version of SolveRoot, and this should go right in.

**Comment by Myoldmopar** [comment]
OK this is all clean now.  It's probably worth giving an overview of the ultimate impact here.  The SolveRoot pattern we've employed in EnergyPlus has been an artifact of not having lambdas available to us.  As we've moved into modern C++ standards, we now have nicer ways of doing SolveRoot.

Up to now, the approach has been:

```c++
// Write a residual function that takes a Par array of floats
Real64 myResidual(EnergyPlusData &state, Real64 const x, Array1D<Real64> Par) {
  int myIndex = int(Par(1));
  bool firstHVAC = Par(2) == 1.0;
  Real64 targetLoad = Par(3);
  return targetLoad - state->dataThings(myIndex).output(x, firstHVAC);
}

// then in the component model or manager routine:
void ObjectClass::manager(EnergyPlusData &state, bool FirstHVACIteration, Real64 loadToMeet) {
  Array1D<Real64, 4> Par;  // these are allocated to various sizes, many times not matching the residual function needs
  // do stuff, then set the par array
  Par(1) = this->indexInArray;
  Par(2) = FirstHVACIteration;
  Par(3) = loadToMeet;
  // call SolveRoot with the residual and Par array
  SolveRoot(state, myResidual, Par);
  // other stuff going on like checking the solver status
}
```

OK, so that's how it has been since the beginning, and in Fortran, that was a fantastic way to do it.  But let's see what it looks like now:

```c++
// no residual function unless the calculation is really large or you want to explicitly unit test the residual function separately

// then in the component model or manager routine:
void ObjectClass::manager(EnergyPlusData &state, bool FirstHVACIteration, Real64 loadToMeet) {
  auto f = [&state, FirstHVACIteration, loadToMeet, this](Real64 const x) {
    return loadToMeet - state->dataThings(this->indexInArray).output(x, FirstHVACIteration);
  };
  SolveRoot(state, f);
  // other stuff going on like checking the solver status
}
```

That's it.  No more creating Par arrays of floats.  No more coercing ints and bools into floats so they fit in the Par array...and then coercing them back into ints and bools inside the residual function thousands of times.  Simply capture the variables you want and do the residual calculation on those variables directly.  In the case where the residual function is really big, or you want to test it separately, just clean it up into a nice normal function with a normal set of arguments, and call it inside the lambda, like:

```c++
void ObjectClass::manager(EnergyPlusData &state, bool FirstHVACIteration, Real64 loadToMeet) {
  auto f = [&state, FirstHVACIteration, loadToMeet](Real64 const x) {
    return myResidual(state, x, FirstHVACIteration, loadToMeet);
  };
  SolveRoot(state, f);
}
```

A huge benefit to this will also be that you can simply capture `this` in the lambda list.  So you may not need to pass an array index into the residual at all, and instead access the current instance instead:

```c++
void ObjectClass::manager(EnergyPlusData &state, bool FirstHVACIteration, Real64 loadToMeet) {
  auto f = [&state, this, FirstHVACIteration, loadToMeet](Real64 const x) {
    return loadToMeet - this->function(state, x, FirstHVACIteration, loadToMeet);
  };
  SolveRoot(state, f);
}
```

**Comment by amirroth** [comment]
We have been using lambdas in a few other places in the code (e.g., Kiva), but this is the first extensive use of them. Lambda is a pretty handy C++ feature. You don't really need it that often, but when you do ... man, it really helps to have it because trying to replicate that functionality can get convoluted pretty quickly as you have seen with the old `SolveRoot`. If you are interested, here is a quick intro to the [lambda feature and when to use it](https://github.com/NREL/EnergyPlus/wiki/Lambdas%3A-When-and-How-to-Use-Them). Thanks @Myoldmopar for this pass!

**Comment by Myoldmopar** [comment]
> Thanks @Myoldmopar for this pass!

Yeah, it was fun, and painful. :)

I'll be happy to answer questions on the technicalities call today before this merges.

**Comment by rraustad** [comment]
Reviewed and discussed. Everything compiles and answers have not changed. Lot's of good work here.

**Pull request merged**
