### PR TITLE
Fix GHE Bugs

### LINKED ISSUE #10494: Problem with GHE Construction from Single BH Objects
Issue overview
--------------
The GHE model has a problem when constructing GHE objects from instances of single borehole objects. Instead of only using the single BH objects named, it is instead using all available. The problem occurs in this line:

https://github.com/NREL/EnergyPlus/blob/696bda5bde27c336ae8e14b6e7c5ff120e46008b/src/EnergyPlus/GroundHeatExchangers.cc#L652

Instead of looping over all single BH objects, it should only consider the ones being passed through the vector in the argument. This would only be a problem if users were using this feature for GHE construction and also had multiple GHE or unused BH objects.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes #10494

This is likely to be a running PR where GHE bug fixes are posted.

Beyond that, we are starting a larger effort to refactor and enhance the E+ GHE model. The bugs, reactors, and features will be trickling in over the next couple of release cycles.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@mitchute @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mitchute @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mitchute @myoldmopar it has been 31 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
All clean here, merging this.

**Pull request merged**
