### PR TITLE
Plant heat exchanger dual deadband control fixed to run when beneficial

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Addresses #5258.

### CODE REVIEW

**Comment by mjwitte** [comment]
@EnergyArchmage If I'm following this correctly, the setpoint high/low temps for TRANSFER Supply Outlet Node are 19.0/17.5, but the TRANSFER LOOP:Plant Supply Side Outlet Temperature is controlling to 20.0/17.5.  Why 20 and not 19?

**Comment by mjwitte** [comment]
Also, the unit tests don't seem to be checking the dual setpoint node temp?

**Comment by EnergyArchmage** [comment]
The reason it is 20 and not 19 is because the demand side loop inlet is 20 and it cannot cool it all the way to 19 (pesky 2nd law of thermodynamics).  This is the whole point of the issue.  It should try to get as close as it can without just giving up and not even trying at all when setpoint cannot be totally reached.

**Comment by EnergyArchmage** [comment]
in the unit test, the node temps that result from the HX control are checked here.  

https://github.com/NREL/EnergyPlus/blob/5258-Plant-HX-Dual-DeadBand-Control/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L1148

https://github.com/NREL/EnergyPlus/blob/5258-Plant-HX-Dual-DeadBand-Control/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L2274

**Comment by mjwitte** [comment]
Got it on the 20.  So, what's the difference between the two unit tests - not jumping out at me without diffing the two sections of inputs.

**Comment by EnergyArchmage** [comment]
Yeah, cannot diff the input between the unit tests.  The only difference is in the schedules for the setpoints.  (Just for the record I did try to do a more low level unit test but after spending too much time trying to flush out all the plant loop structure needed to test the control I gave up and stuffed the whole input file from the defect file into tests that run an entire design day. )

the first unit test works the hi side control by setting the hi side setpoint down to 19.0 here
https://github.com/NREL/EnergyPlus/blob/8de3ff04b8dff8d8deb5110551436753fa7bb934/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L980

The second unit test works the lo side control by setting the lo side setpoint up to 21.0 (also not attainable) here 
https://github.com/NREL/EnergyPlus/blob/8de3ff04b8dff8d8deb5110551436753fa7bb934/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L2113

**Comment by mjwitte** [comment]
OK. Some explanatory comments would be useful in general in unit tests so they can be understood down the road by someone else.  And it threw me that both tests were testing for the same temperature.

**Pull request merged**
