### PR TITLE
EvaporativeCooler:*:ResearchSpecial Primary Air Flow autosize and reporting problems

### PR DESCRIPTION
**Pull request by Nigusse**
Regression results diffs are expected due to sizing report variables change or addition. One new sizing variable was added and an existing sizing variable was renamed.  The "Secondary fan Flow Rate" was renamed to "Secondary Air Design Flow Rate" and "Primary Air Design Flow Rate" new variable was added. These changes impacted the following six example files: 

2ZoneDataCenterHVAC_wEconomizer.idf
DirectIndirectEvapCoolers.idf
DirectIndirectEvapCoolersVSAS.idf
IndEvapCoolerRTUoffice.idf
ReliefIndEvapCoolerRTUoffice.idf
StripMallZoneEvapCooler.idf

Other changes made include:
(1) reviewed the IDD objects of the five evaporative coolers and required fields were added and minor editing and defaults values were specified as needed.
(2) IO REF documentation was updated
(3) transition rule was prepared for "EvaporativeCooler:Direct:ResearchSpecial," and committed to remote build support branch of 8.4.

This fix is ready for review.  Addresses #5060 and #5061

### CODE REVIEW

**Comment by mjwitte** [comment]
@nealkruis You could start with this one if @Myoldmopar agrees.  I see the branch is conflicted now because this waited so long for review.

**Comment by Myoldmopar** [comment]
Please hold.  @Nigusse can you comment on this PR?  Is this what already went in with my evap cooler changes?  I'm hesitant for anyone to spend time on this one until I get a little clarification.

**Comment by Nigusse** [comment]
It has not been updated since the original pull request.  So, I believe this is what you merged into your branch.

**Comment by Myoldmopar** [comment]
OK based on @Nigusse's comments, I am closing this PR without merging.  My other sizing PR brought in the fixes. (#4940)

**Comment by mjwitte** [comment]
@Myoldmopar @Nigusse Most of the content of this pull request is not in develop yet.  IDD changes, new field in EvaporativeCooler:Direct:ResearchSpecial, etc.

**Comment by Myoldmopar** [comment]
@mjwitte @Nigusse I think I got all the kinks worked out here.  The merge conflicts are gone, the test files (integration tests) run, the unit tests pass, and the transition rules appear to be correct (tested transitioning an 8.3 file up).

I think we're ready to merge as long as CI didn't find anything I missed.  Here's to hoping.  

If CI, and both of you, agree, I think this should drop in first thing in the morning and we should bring code freeze along later in the day.

**Comment by Myoldmopar** [comment]
@lefticus same issue again...

**Comment by Myoldmopar** [comment]
Re-merged to get rid of some diffs...

**Comment by mjwitte** [comment]
@Nigusse @Myoldmopar It appears that these changes address #5060 and #5061.  If so, please close those issues.

**Pull request merged**
