### PR TITLE
Update License Year to 2022

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Updates license year to 2022
 - Minor auto-formatting and method name update in `license-update.py` and `licensetext.py` (`mergeParagraphs` was renamed to `merge_paragraphs` but that change had only been made in the check script).
 - Extends the update to the Python language files.
 - Reformats the error output into something more human readable instead of the JSON that `decent_ci` was looking for:
 ```
license-check(.\scripts\dev\licensetext.py, line 1): License year is incorrect
```
 - Changes the behavior a little on detection of year issues so that there's less of a chance of double reporting.

There's still more that could be done, but that's enough for this year.

### CODE REVIEW

**Comment by mitchute** [comment]
Hmm, I guess the license-update script doesn't update the python files. Maybe I have to update those manually?

**Comment by jasondegraw** [comment]
@mitchute The checking of Python wasn't added until recently, so I was waiting until the yearly update to make those changes. I'll do that tomorrow and add that to this PR.

**Comment by mitchute** [comment]
Thanks @jasondegraw. You're the expert on this, so feel free to take over.

**Comment by jasondegraw** [comment]
Since I've now committed to this branch, I won't review it because I'd just approve it. But this is ready to go as far as I know.
@mitchute @Myoldmopar

**Comment by Myoldmopar** [comment]
Great, thanks @jasondegraw and @mitchute !

**Comment by Myoldmopar** [comment]
Yeah, this is all good to go, thanks for all the improvements here.

**Pull request merged**
