### PR TITLE
Modify HVACTemplate:Zone:BaseboardHeat Rated Average Water Temperature

### LINKED ISSUE #7297: HVACTemplate:Zone:BaseboardHeat Rated Average Water Temperature needs better value
Issue overview
--------------
HVACTemplate:Zone:BaseboardHeat writes a hard-wired default value of 87.78C for Rated Average Water Temperature in the ZoneHVAC:Baseboard:RadiantConvective:Water object. This value impacts the sizing of the baseboard UA and it should be consistent with the hot water loop design temperature. In this case, the HVACTemplate default hot water supply temp is 82C, so the baseboard will never see an average water temp of 87.78.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.1.0
 - Helpdesk ticket number 15167

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #7297 
 - This pull request changes the  HVACTemplate:Zone:BaseboardHeat hard-wired default value of 87.78C for Rated Average Water Temperature in the ZoneHVAC:Baseboard:RadiantConvective:Water object to 82.2C to match the HVACTemplate default hot water supply temp of 82.2C. This value impacts the sizing of the baseboard UA and it should be consistent with the hot water loop design temperature.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

**Comment by mitchute** [comment]
This seems reasonable to just make values consistent. Does anyone have strong opinions here? If not, this is going straight in.

**Comment by rraustad** [comment]
I tried to find what water temperature was used for baseboard ratings. I did not find anything other than this I-B-R inference of 150 F. Since other HW coils use 82.2 (epfilter.f90) this change is reasonable.

https://www.ahrinet.org/app_content/ahri/files/certification/i=b=rbaseboardradiation.pdf

image

**Comment by mitchute** [comment]
Thanks, @rraustad. I tested this to verify the values coming through. Merging now.

**Comment by matthew-larson** [comment]
Thanks @mitchute!

**Pull request merged**
