### PR TITLE
Addresses inconsistent reference hot water temperature are used to calculate density in water flow autosize

### PR DESCRIPTION
**Pull request by Nigusse**
Addresses #5442
## Pull request overview

Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.
### Work Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
- [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
  - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
  - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
  - NewFeature: This pull request includes code to add a new feature to EnergyPlus
  - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
  - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog
### Review Checklist

This will not be exhaustively relevant to every PR.
- [ ] Code style (parentheses padding, variable names)
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit the fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check -- verify this
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
  - [ ] If any virtual classes, ensure virtual destructor included, other things
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF Editor with modified IDD to check for errors
  - [ ] If transition, add rules to spreadsheet
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Documentation changes in place
- [ ] ExpandObjects changes??
- [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Nigusse** [comment]
@mjwitte @rraustad @EnergyArchmage @Myoldmopar I added two global variables (HWCoilInitTemp  and CWCoilInitTemp) that hold Init water temperatures for density and Cp values calculation during sizing (in some cases it is also used during initialization).  In this commit I changed all numeric values of 60.0C used for hot water by HWCoilInitTemp variable for sizing. For chilled water in almost of all cases the variable InitConvTemp (which is initialized to 5.05 C) is used but in a few I cases I also noted that numeric value 5.0 was used. 

In this commit, all chilled water related properties calculations that use InitConvTemp variables were replaced with the variable CWCoilInitTemp. The CWCoilInitTemp variable is initialized to 5.05C.  Diffs were not expected in this commit. This also confirmed by CI machine run above. 

In the next step I will make the following selected changes in **Hot Water Coils** related calculations:
(1) If there is any mismatch between parent and child object use of Water Init Temp for property (density and CP) calculation, then they will be forced to use HWCoilInitTemp, which is 60.0C 

(2) In the few places that I noted 5.0C use for chilled water related sizing calculation will be replaced with CWCoilInitTemp, which is 5.05C.  

Note that there are several places/modules (e.g., cooling towers, Fluid coolers, Evapcoolers, PlantHeatExchangersFluidToFluid, pumps, etc) that cannot be categorized as chilled or hot water. In those modules the code will remain to use InitConvTemp as is. The values of InitConvTemp and CWCoilInitTemp are identical.

These two changes are expected to bring diffs in several example files for sizing and annual run results.

If you have any concerns or suggestion please let me know; otherwise, I will go ahead with the proposed changes.

**Comment by Nigusse** [comment]
Removed unused variables to get rid of the warning message.

**Comment by Myoldmopar** [comment]
I support this change too, but I'd like to see all the `using DataGlobals` changed to simply reference the variable itself in the code.  I'll likely make that change and push it up.  That should also address the [build warnings](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-127d6de36dc57bb529bb0c738459dbe005ef61ff-x86_64-Linux-Ubuntu-14.04-gcc-4.8-IntegrationCoverage-Debug.html).

**Comment by Nigusse** [comment]
@Myoldmopar I see in several places that CWCoilInitTemp variable not referenced. Will you make a second pass?

**Comment by Myoldmopar** [comment]
Well, instead of booting up the Ubuntu machine to find the rest of the error message and correct a single instance or two, I just eliminated all the `using` of InitConvTemp, CWInitConvTemp, and HWInitConvTemp.  This is nicer now anyway.  CI should come back clean and this should be mergeable.

**Comment by Myoldmopar** [comment]
And bonus, net of 500 lines of source removed. (Almost entirely empty comment blocks, but still)

image

**Comment by Myoldmopar** [comment]
Yay, looking good enough to merge before bed.  Thanks @Nigusse.

**Pull request merged**
