### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
This updates RE2, SQLite, GTest, and Eigen libraries.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jasondegraw do you or anyone else listening have an issue with updating these libraries?  CI looks real happy with it.  I will pull it up to latest develop this evening and make sure, but if it's all green I'd like to get this in.

**Comment by Myoldmopar** [comment]
I had thought the warnings branch might add some diffs so I didn't want to bring develop into this branch until that was merged.  But it looks like that won't be merged tonight, so I'll pull develop in here now.  If anyone has concerns with updating this, speak tonight; I'll probably merge in the morning time tomorrow.

**Comment by jasondegraw** [comment]
@Myoldmopar No issues here, merge away

**Comment by mjwitte** [comment]
@Myoldmopar I assume you see the two [test failures](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-68393748300aae14d43ed8a246b48282e60138c8-x86_64-Linux-Ubuntu-14.04-gcc-4.8-UnitTestsCoverage-Debug.html) back in March?

**Comment by nrel-bot-3** [comment]
@Myoldmopar @mbadams5 @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@mbadams5 thoughts on the unit test failures associated with the library upgrade?

**Comment by mbadams5** [comment]
Not yet, I'm spinning up my linux instance to try and figure it out.

**Comment by mbadams5** [comment]
Ok so the issue is related to the newest version of re2 and GCC 4.8.4. When I use GCC 5.4.0 everything compiles and runs perfectly. I've reverted to a newer, but not newest version of re2 for this release. If, or when, we move to ubuntu 16.04/18.04 then we can update to latest version of re2 without failing unit tests. @Myoldmopar

**Comment by mbadams5** [comment]
@Myoldmopar This should be good to go now. If you want to wait on the ubuntu CI after I merged develop in, that is fine.

**Pull request merged**
