### PR TITLE
Change single zone reheat setpoint manager to use actual OA fraction when in deadband

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Revise logic in Single Zone Reheat Setpoint manager.  When in deadband and calculating alternate setpoints use actual outdoor air fraction instead of minimum outdoor air fraction.  This change primarily impacts cases where this setpoint manager is used to control supply air temperature when the zone has exhaust air which forces the OA damper to open beyond minimum.  For unitary systems which only use this setpoint manager to set the economizer mixed air setpoint, it is recommended that SetpointManager:SingleZone:Cooling be used instead.  That change has been made in several example files and in HVACTemplate:System:Unitary, UnitaryHeatPump, and UnitarySystem.

address issue #4967 

expect regression test "Failures" in the following files.  
RefBldgFullServiceRestaurantNew2004_Chicago
RefBldgSecondarySchoolNew2004_Chicago
RefBldgSuperMarketNew2004_Chicago
RefBldgWarehouseNew2004_Chicago
AirflowNetwork_MultiZone_SmallOffice 
AirflowNetwork_MultiZone_SmallOffice_GenericContam`
AirflowNetwork_MultiZone_SmallOffice_HeatRecoveryHXSL 
AirflowNetwork_Simple_SmallOffice
DirectIndirectEvapCoolers 
DirectIndirectEvapCoolersVSAS 

Other files would show diffs is run in annual mode

### CODE REVIEW

**Comment by mjwitte** [comment]
@wfbuhl @Myoldmopar Would like your comments on this change.  Additional discussion in #4967

**Comment by Myoldmopar** [comment]
Seems super reasonable, and the clear_state and unit test work looks good.  I realize this will cause those diffs you mentioned, but after reading the conversation in #4967, it seems like the right move.  The baselines will be better, and later we can look into further improving setpoints for these applications.  I'd recommend merging in.

**Comment by wfbuhl** [comment]
This is OK with me. Note that set point managers are called once before HVAC simulation and never again. They typically use last time steps values. The idea was to keep them out of the controller loop to prevent endless iteration. Using OAFrac is the correct thing to do.

I also agree with Mike's comments about handling floating supply air temperature. We need some sort of flag for this.

**Comment by mjwitte** [comment]
@EnergyArchmage Have you run a full annual diff with this change?  Also, unless you object, I'm going to change the handful of files that have the SZRH manager just to place an economizer setpoint for unitary systems.

**Comment by EnergyArchmage** [comment]
yes I did do full annual runs on my local machine on a subset of about 60 test suite files that use the SZRH.  I examined the diffs in all the tabular reports and error files.  Many more files show diffs during annual runs compared to the regular test suite.  For the most part the annual energy changes are small sometimes heating goes down and cooling goes up, sometimes they both go down.  The main exceptions are some fairly large changes in these files where both heating and cooling increase with new algorithm.  These would be good candidates for a different setpoint manager. 

```
   FurnaceWithDXSystemRHcontrol            
   HeatPumpAirToAirWithRHcontrol           
   HP_wICSSolarCollector                 
   DirectIndirectEvapCoolers           
   DirectIndirectEvapCoolersVSAS       
```

**Comment by EnergyArchmage** [comment]
I went ahead and changed five example files to use SetpointManager:SingleZone:Cooling instead of reheat. Local testing showed that they all run better, use less energy.  It is expected that there will be diff failures in these files because of input changes.

```
  FurnaceWithDXSystemRHcontrol            
  HeatPumpAirToAirWithRHcontrol           
  HP_wICSSolarCollector                 
  DirectIndirectEvapCoolers           
  DirectIndirectEvapCoolersVSAS   
```

**Comment by mjwitte** [comment]
@EnergyArchmage @Myoldmopar Expandobjects changes made.  Tested HVACTemplate files locally.  If CI comes back OK, then this should be ready to merge.

**Comment by mjwitte** [comment]
@Myoldmopar This is ready to merge - shall I proceed or wait for the evap cooler merge?  I don't see any overlap.

**Comment by Myoldmopar** [comment]
Merge away

**Pull request merged**
